import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const courseData = {
  "title": "AI Data Engineer",
  "description": "Master the data infrastructure that powers AI — data lakehouses, dbt transformations, Apache Kafka streaming, feature engineering, and feature stores. Build production pipelines used at Uber, Netflix, Airbnb, and every serious AI-first company.",
  "translations": {"es": {"title": "AI Data Engineer", "description": "Master the data infrastructure that powers AI — data lakehouses, dbt transformations, Apache Kafka streaming, feature engineering, and feature stores. Build production pipelines used at Uber, Netflix, Airbnb, and every serious AI-first company."}, "fr": {"title": "AI Data Engineer", "description": "Master the data infrastructure that powers AI — data lakehouses, dbt transformations, Apache Kafka streaming, feature engineering, and feature stores. Build production pipelines used at Uber, Netflix, Airbnb, and every serious AI-first company."}, "de": {"title": "AI Data Engineer", "description": "Master the data infrastructure that powers AI — data lakehouses, dbt transformations, Apache Kafka streaming, feature engineering, and feature stores. Build production pipelines used at Uber, Netflix, Airbnb, and every serious AI-first company."}, "zh": {"title": "AI Data Engineer", "description": "Master the data infrastructure that powers AI — data lakehouses, dbt transformations, Apache Kafka streaming, feature engineering, and feature stores. Build production pipelines used at Uber, Netflix, Airbnb, and every serious AI-first company."}, "ar": {"title": "AI Data Engineer", "description": "Master the data infrastructure that powers AI — data lakehouses, dbt transformations, Apache Kafka streaming, feature engineering, and feature stores. Build production pipelines used at Uber, Netflix, Airbnb, and every serious AI-first company."}, "ja": {"title": "AI Data Engineer", "description": "Master the data infrastructure that powers AI — data lakehouses, dbt transformations, Apache Kafka streaming, feature engineering, and feature stores. Build production pipelines used at Uber, Netflix, Airbnb, and every serious AI-first company."}},
  "modules": [
  {"title": "Module 1: Modern Data Architecture for AI", "desc": "The foundational mental models, architecture patterns, and technology choices that define world-class AI data infrastructure — grounded in the Delta Lake paper, Reis & Housley's Fundamentals of Data Engineering, and engineering blogs from Uber, Netflix, and Airbnb.", "lessons": [
    {"title": "1.1 The Data Engineering Lifecycle and the AI Data Stack", "desc": "How data flows from source to AI model — the complete lifecycle, the modern data stack, and why Joe Reis calls data engineering 'the plumbing that makes AI possible.'"},
    {"title": "1.2 Data Lakehouse Architecture: Delta Lake, Iceberg, and ACID for AI", "desc": "The Delta Lake paper (Armbrust et al. 2020), ACID transactions in object storage, time travel for ML reproducibility, and why every serious AI company has moved from pure data lakes to lakehouses."},
    {"title": "1.3 dbt: The SQL Transformation Layer That Changed Data Engineering", "desc": "How dbt brought software engineering discipline to SQL — version control, testing, documentation, and lineage — and why it has become the universal standard for ML feature table construction."},
    {"title": "1.4 Apache Kafka: Real-Time Data Streaming for AI Feature Pipelines", "desc": "Kafka's architecture from the original LinkedIn paper, partitioning and consumer groups for ML workloads, exactly-once semantics for training data integrity, and how Uber's Michelangelo uses Kafka for real-time ML features."},
    {"title": "1.5 Feature Engineering and Feature Stores: From Raw Events to ML-Ready Signals", "desc": "Feature engineering patterns from industry research, the Uber Michelangelo feature store paper, Feast architecture, point-in-time correct training data, and the feature monitoring practices used at Airbnb, Twitter, and Spotify."}
  ]},
  {"title": "Module 2: Data Ingestion at Scale — Batch, Streaming, and Change Data Capture", "desc": "Moving data from 200+ source systems into your AI data platform reliably and efficiently. Airbyte, Fivetran, Apache Kafka Connect, Debezium CDC, and the ingestion patterns used at Stripe, Shopify, and DoorDash.", "lessons": [
    {"title": "2.1 Batch vs. Streaming vs. Micro-Batch: Choosing the Right Ingestion Pattern", "desc": "The three ingestion modes — full refresh batch (simplest, most expensive at scale), incremental batch (cursor-based, bookmarked), and streaming (sub-second latency) — and the decision matrix for ML feature pipelines. Full refresh: appropriate for small dimension tables (<1M rows), schema-agnostic sources. Incremental batch: 90% of enterprise ingestion — updated_at cursor on source tables, Fivetran"},
    {"title": "2.2 Airbyte and Fivetran: Managed Ingestion for 200+ Sources", "desc": "The build vs. buy decision for data connectors resolved: Airbyte (open-source, self-hosted or Airbyte Cloud, 300+ connectors) vs. Fivetran (fully managed, 500+ connectors, $500-5,000/month at SMB scale). Connector architecture: incremental sync with bookmark state, schema normalization, automatic schema change handling. Building custom Airbyte connectors (Python CDK) for internal sources. The conn"},
    {"title": "2.3 Change Data Capture with Debezium: Real-Time Database Sync for AI", "desc": "CDC captures every INSERT, UPDATE, DELETE from source databases as a stream — enabling real-time feature computation without polling overhead. Debezium's architecture: connects to database transaction logs (MySQL binlog, Postgres WAL, MongoDB oplog), publishes change events to Kafka topics. Schema evolution handling (Debezium + Confluent Schema Registry). The CDC event format (before/after snapsho"},
    {"title": "2.4 Apache Kafka Connect: The Ingestion and Egress Layer for Streaming AI", "desc": "Kafka Connect's architecture — source connectors (pull data into Kafka), sink connectors (push Kafka to destinations). The connect cluster (distributed mode for production fault tolerance), worker configuration, connector configuration and lifecycle management. Key connectors: JDBC Source (poll relational databases), S3 Sink (land Kafka events in data lake), Snowflake Sink (stream events directly "},
    {"title": "2.5 Data Quality at Ingestion: Great Expectations and Schema Validation", "desc": "The cost of bad data: Gartner estimates poor data quality costs organizations $12.9M per year on average — for AI teams, a single corrupt batch can invalidate months of training data. Great Expectations: defining Expectation Suites (expect_column_values_to_not_be_null, expect_column_values_to_be_between, expect_column_pair_values_to_be_equal), running validations as pipeline checkpoints, Data Docs"},
    {"title": "2.6 Handling Late Data, Duplicates, and Exactly-Once Semantics", "desc": "The three guarantees in distributed ingestion: at-most-once (data loss acceptable), at-least-once (duplicates possible), exactly-once (neither — hardest). Why exactly-once matters for AI: a payment event counted twice corrupts fraud features; a missing event undercounts purchase frequency. Idempotent producers and transactional consumers in Kafka (exactly-once enabled with transaction API). Dedupl"},
    {"title": "2.7 Module 2 Lab: Build an End-to-End Ingestion Pipeline", "desc": "Hands-on project: configure Debezium to capture changes from a Postgres source database, stream events through Kafka, apply schema validation with Schema Registry, land raw events in S3 partitioned by date, and trigger a dbt incremental model refresh. Implement deduplication and document data quality expectations."}
  ]},
  {"title": "Module 3: dbt Mastery — Transformations, Testing, and ML Feature Pipelines", "desc": "dbt (data build tool) is the transformation layer every serious AI data team uses. Advanced dbt patterns: incremental models, snapshots, macros, packages, testing, lineage, and production deployment. From the dbt Labs team and practices documented at Airbnb, GitLab, and Shopify.", "lessons": [
    {"title": "3.1 dbt Architecture Deep Dive: DAGs, Refs, and the Dependency Graph", "desc": "dbt's core innovation: {{ ref('model_name') }} automatically builds the dependency graph — dbt analyzes all refs, constructs the DAG, and executes models in topological order with maximum parallelism. The DAG in production: dbt docs serve generates an interactive lineage graph showing every model's upstream sources and downstream consumers. The ref() function enables zero-configuration environment"},
    {"title": "3.2 Incremental Models: The Key to Efficient Feature Engineering at Scale", "desc": "Running SELECT * FROM 10TB of event data every day to compute features is prohibitively expensive. dbt's incremental materialization processes only new or updated rows — the pattern every ML feature pipeline depends on. The incremental config block: materialized='incremental', unique_key='event_id' (for upserts), on_schema_change='append_new_columns'. The is_incremental() macro filters to only pro"},
    {"title": "3.3 dbt Testing and Data Quality Contracts for ML Pipelines", "desc": "Every dbt model feeding an ML training pipeline must have tests — untested features are liability. The complete dbt testing toolkit: generic tests (not_null, unique, accepted_values, relationships), singular tests (custom SQL assertions returning failing rows), dbt-expectations (Great Expectations integration: expect_column_values_to_be_between, expect_table_row_count_to_equal), dbt-utils (at_leas"},
    {"title": "3.4 Jinja Macros and dbt Packages: Reusable Feature Engineering Components", "desc": "Jinja templating in dbt eliminates repetitive SQL — write the feature logic once, apply it 50 times. Custom macros for ML: calculate_rolling_window(column, days), safe_divide(numerator, denominator, default), percentile_feature(column, p). The dbt-utils package (40+ utility macros: generate_surrogate_key, pivot, unpivot). dbt-ml-preprocessing (sklearn-style transformations in SQL). Package managem"},
    {"title": "3.5 dbt Snapshots: Type 2 SCDs for ML Training Data Versioning", "desc": "ML models often need to know what a user's attributes were at a specific point in time — not just their current values. dbt snapshots implement Slowly Changing Dimension Type 2: every change to a row creates a new snapshot record with valid_from and valid_to timestamps, preserving history. The snapshot strategy options: timestamp (use updated_at column), check (hash all relevant columns to detect "},
    {"title": "3.6 dbt in Production: CI/CD, Slim CI, and Blue-Green Deployments", "desc": "Deploying dbt to production with the same rigor as application code. Slim CI: dbt build --select state:modified+ runs only changed models and their descendants — reducing CI pipeline time from 2 hours to 10 minutes. Blue-green dbt deployments: build new model versions in a staging schema, run data quality tests, swap production views to point to new tables atomically. dbt Cloud vs. self-hosted (Ai"},
    {"title": "3.7 Module 3 Assessment: Feature Engineering Pipeline Design", "desc": "Design challenge: given a ride-sharing dataset (trips, users, drivers, ratings), design a dbt project structure with incremental models for real-time features, snapshots for historical attributes, macros for rolling windows, and a complete test suite. Write the SQL for three key features with appropriate tests."}
  ]},
  {"title": "Module 4: Apache Spark for Large-Scale ML Data Processing", "desc": "Spark is the engine behind petabyte-scale ML training data preparation at Netflix, Apple, and Meta. Spark architecture, DataFrames, optimizations, Spark MLlib, Delta Lake integration, and deployment on Kubernetes and Databricks.", "lessons": [
    {"title": "4.1 Spark Architecture: Driver, Executors, and the Catalyst Optimizer", "desc": "Spark's execution model: Driver (orchestrates computation, maintains SparkContext, schedules tasks), Cluster Manager (YARN/Kubernetes — allocates executor resources), Executors (JVM processes on worker nodes that run tasks and cache data). The logical plan → physical plan transformation by the Catalyst optimizer — predicate pushdown (filter before join reduces shuffled data by 90%), column pruning"},
    {"title": "4.2 Spark DataFrames and the SQL API for ML Feature Engineering", "desc": "The DataFrame API (structured, schema-aware, Catalyst-optimized) vs. RDDs (low-level, avoid in 2024). Key DataFrame operations for ML: groupBy + agg (compute user-level aggregate features), window functions (rolling averages over time, rank within partition), join strategies (broadcast hint for dimension tables <10MB, shuffle hash join, sort-merge join). The PySpark SQL functions library (F.col, F"},
    {"title": "4.3 Spark Performance Tuning: Partitioning, Shuffles, and Memory Management", "desc": "The shuffle is the most expensive Spark operation — avoid it or optimize it. Partition size: 128MB target, repartition() vs. coalesce(), partitionBy() on date for time-series ML data (enables partition pruning). Shuffle optimization: broadcast joins for small tables (spark.sql.autoBroadcastJoinThreshold = 100MB), salting for skewed keys (a single user_id accounting for 10% of records causes a 10x "},
    {"title": "4.4 Spark Streaming and Structured Streaming for Real-Time Features", "desc": "Structured Streaming extends the DataFrame API to streaming data — the same transformation code works for both batch and streaming, eliminating the Lambda architecture duplication. Trigger modes: default (micro-batch, process new data as it arrives), processingTime (fixed interval), once (single micro-batch for scheduled jobs), continuous (experimental, sub-millisecond latency). Kafka source integ"},
    {"title": "4.5 Delta Lake Integration with Spark: ACID Transactions at Petabyte Scale", "desc": "Delta Lake adds ACID transactions, schema enforcement, and time travel to Spark's object storage reads/writes. DeltaTable.forPath() for programmatic access. MERGE INTO for upserts (the primary pattern for feature table updates: insert new features, update existing). Schema evolution: mergeSchema option for adding columns, overwriteSchema for breaking changes. Z-ordering for multi-dimensional data "},
    {"title": "4.6 Databricks and Spark on Kubernetes: Production Deployment Patterns", "desc": "Databricks as the managed Spark platform: clusters (interactive vs. job clusters), cluster autoscaling, Databricks Runtime for ML (pre-installed ML libraries, GPU support), Unity Catalog for governance. Spark on Kubernetes: spark-submit with --master k8s://, dynamic resource allocation (scale executors up during computation, release when done), node affinity for GPU nodes. Cost optimization: spot/"},
    {"title": "4.7 Module 4 Lab: Build a Spark ML Feature Pipeline", "desc": "End-to-end Spark project: read raw event data from a Delta Lake table, compute rolling window features using window functions, handle late data with watermarks in Structured Streaming mode, write computed features back to Delta Lake with MERGE, and implement Z-ordering for query optimization. Measure and optimize shuffle size."}
  ]},
  {"title": "Module 5: Feature Stores — Feast, Tecton, and Production Feature Engineering", "desc": "Feature stores are the most impactful infrastructure investment an ML platform team can make. Architecture, Feast deployment, online/offline stores, feature serving latency, point-in-time correctness, and the patterns used at Uber, Twitter, and Airbnb.", "lessons": [
    {"title": "5.1 Why Feature Stores Exist: The Training-Serving Skew Problem", "desc": "Training-serving skew is the silent killer of production ML models — a 2022 Google study found 62% of model performance degradation in production traces to feature inconsistency between training and serving environments. The skew sources: different code computes features at training time (Python pandas) vs. serving time (Java microservice), different data sources, different preprocessing logic. Fe"},
    {"title": "5.2 Feast Architecture: Registry, Offline Store, Online Store, and Feature Server", "desc": "Feast's four components: Feature Registry (Git-backed metadata store: feature view definitions, entity definitions, data source configs), Offline Store (BigQuery/Snowflake/Redshift for historical feature retrieval — training data generation), Online Store (Redis/DynamoDB/Bigtable for sub-millisecond serving — inference time), Feature Server (HTTP/gRPC API serving online features). The feature pipe"},
    {"title": "5.3 Defining Feature Views, Entities, and Data Sources in Feast", "desc": "Writing production Feast feature definitions. Entity: the primary key for feature lookup (user = Entity(name='user', join_keys=['user_id'])). FeatureView: a group of features computed from a single data source (user_engagement_features = FeatureView(entities=[user], source=bigquery_source, ttl=timedelta(days=90))). FeatureService: the feature bundle for a specific model (churn_model_features = Fea"},
    {"title": "5.4 Point-in-Time Correct Training Dataset Generation", "desc": "The most critical feature store operation for ML teams: generating training datasets without temporal leakage. feast.get_historical_features(entity_df=training_events, features=feature_service) executes a point-in-time correct join — for each training example with a timestamp, retrieves the feature values that were valid at that exact moment. The SQL mechanics: an AS OF join that finds the most re"},
    {"title": "5.5 Online Feature Serving: Redis Architecture, Latency, and Throughput", "desc": "The online store must serve features at inference time — typically within 10-50ms total model latency budget, leaving 2-5ms for feature retrieval. Redis as the canonical online store: hash data structure for feature storage (HGET user:12345 field feature_name), pipeline commands for multi-feature batched retrieval, Redis Cluster for horizontal scaling, Redis Sentinel for high availability. Cache i"},
    {"title": "5.6 Feature Monitoring, Drift Detection, and the Feature Health Dashboard", "desc": "Features drift silently — and when they do, model performance degrades before anyone notices. Production feature monitoring stack: compute feature statistics (mean, stddev, null rate, unique count) on each materialization run. Compare to baseline (statistics from training data) using statistical distance metrics (PSI for continuous features — Population Stability Index > 0.25 indicates significant"},
    {"title": "5.7 Module 5 Assessment: Feature Store Architecture Design", "desc": "Design challenge: architect a feature store for a ride-sharing ML platform with 5 models (surge pricing, driver matching, ETA prediction, fraud detection, churn prediction). Define entities, feature views, data sources, online/offline store choices, materialization schedules, and monitoring thresholds for each model's critical features."}
  ]},
  {"title": "Module 6: Orchestration — Apache Airflow, Prefect, and Production ML Pipelines", "desc": "Data pipeline orchestration is the operational backbone of AI data engineering. Airflow architecture, DAG design, sensors and operators, dynamic DAGs, Prefect 2.0 workflows, and pipeline observability at scale.", "lessons": [
    {"title": "6.1 Airflow Architecture: Scheduler, Workers, Metadata DB, and DAG Serialization", "desc": "Apache Airflow's five components: Scheduler (parses DAGs, schedules task instances, updates metadata database), Workers (execute tasks — Celery or Kubernetes executor), Web Server (UI for monitoring, triggering, debugging), Metadata Database (Postgres/MySQL — stores DAG runs, task states, XCom values), Message Broker (Redis/RabbitMQ for Celery executor). The scheduling loop: Scheduler polls the me"},
    {"title": "6.2 Writing Production DAGs: Idempotency, Backfill, and Dynamic Task Mapping", "desc": "The three laws of production Airflow DAGs. First law: idempotency — running the same DAG run twice must produce identical results. The pattern: DELETE + INSERT rather than INSERT (prevents duplicates on reruns), use execution_date not datetime.now() (prevents non-reproducible behavior). Second law: backfill-ability — every DAG should be re-runnable for historical dates. Template variables ({{ ds }"},
    {"title": "6.3 Airflow Operators and Sensors: The Complete Production Toolkit", "desc": "Operators are the building blocks of Airflow DAGs. Core operators: PythonOperator (run Python callables), BashOperator (shell commands), SQLExecuteQueryOperator (run SQL in any database). Cloud operators: BigQueryInsertJobOperator, SnowflakeOperator, S3CopyObjectOperator, GCSToGCSOperator. dbt operators: DbtRunOperator, DbtTestOperator (via astronomer-cosmos). Sensors wait for conditions before pr"},
    {"title": "6.4 Prefect 2.0: Modern Python-Native Orchestration for ML Teams", "desc": "Prefect's philosophy: orchestration code should look like regular Python with minimal framework intrusion. The @flow and @task decorators transform regular functions into observable, retriable pipeline components. Prefect vs. Airflow: Prefect's dynamic DAGs are native Python (no special mapping API needed), local development feels identical to production, Prefect Cloud handles scheduling without m"},
    {"title": "6.5 Monitoring, Alerting, and SLAs for Data Pipelines", "desc": "Silent pipeline failures are the most dangerous kind — a DAG that runs successfully but produces wrong data corrupts ML models without anyone noticing. Multi-layer monitoring stack: task-level (Airflow task success/failure metrics → Datadog/Grafana), data quality (dbt test results → Slack alerts on failure), SLA monitoring (Airflow SLA misses trigger callbacks), pipeline duration anomalies (a job "},
    {"title": "6.6 Cost Optimization for Orchestrated Data Pipelines", "desc": "Airflow infrastructure and compute costs compound at scale — a 100-engineer data team can spend $500K/year on unnecessary pipeline compute. Cost reduction strategies: spot/preemptible instances for batch Spark jobs (80% savings, implement checkpointing for interruption recovery), incremental processing (only compute delta, not full historical recalculation), pipeline parallelism tuning (find the p"},
    {"title": "6.7 Module 6 Assessment: Orchestration Architecture for ML Platform", "desc": "Design the complete orchestration architecture for an ML platform: data ingestion DAGs, feature computation pipelines, model training triggers, model evaluation workflows, and deployment automation. Define SLAs, monitoring strategies, and cost controls for each pipeline tier."}
  ]},
  {"title": "Module 7: Data Warehouse and Lakehouse Architecture for AI", "desc": "Snowflake, BigQuery, and Databricks are the compute engines powering AI data platforms. Architecture deep-dives, query optimization, cost governance, and the lakehouse pattern that's replacing traditional warehouses for ML teams.", "lessons": [
    {"title": "7.1 Snowflake Architecture: Virtual Warehouses, Storage, and the Cloud Services Layer", "desc": "Snowflake's three-layer architecture: Storage (S3/Azure Blob/GCS — columnar, compressed Parquet), Compute (virtual warehouses — independent MPP compute clusters that auto-suspend), Cloud Services (query compilation, optimization, metadata, auth). The key insight: storage and compute are decoupled — 10 different teams can query the same data with independent warehouses, none blocking the others. Vi"},
    {"title": "7.2 BigQuery: Serverless Architecture, Slots, and ML Feature Engineering at Scale", "desc": "BigQuery's serverless architecture: no infrastructure to manage, automatic scaling from 0 to petabytes. BigQuery's storage format: Capacitor (proprietary columnar format), automatic clustering, partition management. The slot model: BigQuery reserves processing capacity in slots (virtual CPUs) — on-demand pricing ($6.25/TB processed), flat-rate reservations (100 slots = $2,000/month), flex slots (p"},
    {"title": "7.3 Databricks Lakehouse: Delta Lake, Photon Engine, and Unity Catalog", "desc": "The Databricks Lakehouse unifies data warehouse capabilities (SQL, BI) and ML platform capabilities (notebooks, MLflow, Feature Store) on a single Delta Lake foundation. Photon: Databricks' C++ vectorized query engine, 2-5x faster than Spark's JVM-based engine for SQL workloads. Unity Catalog: centralized governance for tables, ML models, and files — column-level permissions, row-level filtering, "},
    {"title": "7.4 Query Performance Optimization: Statistics, Indexes, and Materialized Views", "desc": "Query optimization techniques that apply across Snowflake, BigQuery, and Databricks. Column statistics: the query optimizer uses column statistics (min, max, null count, cardinality, histogram) to choose execution plans — ANALYZE TABLE keeps statistics current. Snowflake Micro-partition pruning: automatic, 16-160MB immutable micro-partitions with per-partition min/max metadata enable file-level sk"},
    {"title": "7.5 Data Governance, Lineage, and Compliance for AI Training Data", "desc": "The EU AI Act (effective 2024-2026) requires documentation of training data sources, quality measures, and processing steps for high-risk AI systems. Data governance stack: Apache Atlas or DataHub for data catalog (searchable metadata, schema documentation, data dictionary), data lineage (visualize how features are derived from source systems), data classification (PII tagging, sensitivity levels)"},
    {"title": "7.6 Cost Governance: FinOps for Data Warehouses at $1M+ Annual Spend", "desc": "At scale, warehouse costs become material — Gartner estimates enterprises spend 30-40% of their cloud data budget on query compute. The FinOps discipline for data: cost attribution (tag all queries with team and pipeline identifiers), budget alerts (Snowflake resource monitors, BigQuery budget alerts), query cost governance (BigQuery custom quotas per user/project, Snowflake resource monitors with"},
    {"title": "7.7 Module 7 Assessment: Data Platform Architecture Design", "desc": "Design the complete data warehouse/lakehouse architecture for a Series B AI company: choose storage format, compute engine, and governance tooling. Design the Bronze/Silver/Gold table architecture, define cost controls, document the lineage requirements for EU AI Act compliance, and size the monthly infrastructure budget."}
  ]},
  {"title": "Module 8: Streaming Data Pipelines — Kafka, Flink, and Real-Time AI Features", "desc": "Real-time AI requires real-time data. Apache Kafka in depth, Apache Flink for stateful stream processing, stream-table joins for real-time feature enrichment, and the streaming architectures powering fraud detection and recommendation systems.", "lessons": [
    {"title": "8.1 Apache Kafka Deep Dive: Replication, Consumer Groups, and the Commit Log", "desc": "Kafka's durability guarantee: replication factor 3 means each partition is stored on 3 brokers — the leader handles reads/writes, followers replicate synchronously. The ISR (In-Sync Replicas) list — only ISR members can become leaders. acks=all: a produce request only succeeds when all ISR members have written the message. Consumer groups: each consumer group gets its own offset pointer per partit"},
    {"title": "8.2 Apache Flink: Stateful Stream Processing for Real-Time Features", "desc": "Flink's programming model: DataStream API for low-level control, Table API/SQL for declarative transformations. The fundamental distinction from Spark Streaming: Flink is true streaming (event-by-event) while Spark Streaming is micro-batch (process events every 100ms). Flink's state backends: HashMap (in-memory, fast, limited by JVM heap), RocksDB (persistent, handles state larger than memory, 2-5"},
    {"title": "8.3 Windowed Aggregations: Tumbling, Sliding, and Session Windows", "desc": "Time-windowed aggregations are the core of streaming feature engineering. Tumbling windows: non-overlapping fixed intervals (count orders per user in each 1-hour bucket — the last bucket closes at :00). Sliding windows: overlapping intervals (30-minute purchase sum, updated every 5 minutes — multiple windows per event). Session windows: gap-based (group user activity with inactivity gap > 30 minut"},
    {"title": "8.4 Stream-Table Joins: Enriching Events with Database Context", "desc": "Production streaming ML features require joining event streams with slowly-changing dimension data — user profiles, product catalogs, merchant risk scores. Flink's broadcast state: broadcast small dimension tables to all parallel Flink operators for zero-network-cost joins. Temporal table joins (versioned temporal tables): join events with the point-in-time-correct version of a dimension — a payme"},
    {"title": "8.5 Schema Registry, Avro, and Backward Compatibility at Scale", "desc": "At 100+ Kafka topics with multiple producers and consumers, schema management without a registry causes production incidents. Confluent Schema Registry: centralized schema storage, schema ID embedded in Kafka messages (4-byte prefix), automatic schema validation on produce, consumer deserializes using registered schema. Avro vs. Protobuf vs. JSON: Avro (compact binary, schema evolution support, na"},
    {"title": "8.6 Streaming Pipeline Observability: Lag, Throughput, and Error Tracking", "desc": "A streaming pipeline that falls behind never catches up — monitoring consumer lag is existential. Kafka consumer lag monitoring: kafka-consumer-groups.sh --describe, Burrow (LinkedIn's dedicated lag monitoring), JMX metrics (records-lag-max, fetch-rate). Flink metrics: backpressure indicators (operator queue utilization), checkpoint duration (should be <10% of checkpoint interval), restarts (frequ"},
    {"title": "8.7 Module 8 Lab: Real-Time Feature Pipeline with Kafka and Flink", "desc": "Build a real-time fraud detection feature pipeline: produce synthetic transaction events to Kafka, consume with Flink, compute windowed features (1-minute and 5-minute transaction counts/amounts per card), join with cardholder profile from a Redis-backed temporal table, write enriched features to a Feature Store. Implement watermarks and monitor consumer lag."}
  ]},
  {"title": "Module 9: Data Observability, Quality, and Reliability Engineering", "desc": "Data is the foundation of every AI system — broken data breaks AI. Monte Carlo Data's observability model, dbt testing at scale, PII detection and masking, data SLAs, and building the data reliability engineering practice.", "lessons": [
    {"title": "9.1 The Five Pillars of Data Observability: Freshness, Volume, Distribution, Schema, Lineage", "desc": "Monte Carlo Data's 2021 data observability framework defines five properties every production dataset must maintain. Freshness: data arrived on time (last_updated < SLA threshold). Volume: row count within expected range (anomalous drops indicate upstream failures). Distribution: statistical properties match historical baseline (null rates, value distributions, cardinality). Schema: columns presen"},
    {"title": "9.2 Building a Data Quality Framework with Great Expectations and dbt Tests", "desc": "Defense-in-depth for data quality: layer multiple validation approaches. Layer 1 — source validation: Great Expectations checkpoints at ingestion (schema validation, null checks, referential integrity). Layer 2 — transformation validation: dbt tests on every model (not_null, unique, accepted_values, custom SQL assertions). Layer 3 — serving validation: feature store health checks before materializ"},
    {"title": "9.3 PII Detection, Masking, and GDPR Compliance for AI Training Data", "desc": "Training AI on unmasked PII creates massive regulatory and reputational risk. PII in training data leads to model memorization — GPT-2 memorized SSNs, email addresses, and phone numbers from Common Crawl. PII detection tooling: Presidio (Microsoft, open-source, 50+ PII entity types), AWS Comprehend (managed NLP, custom entity training), Google Cloud DLP (API for detecting and de-identifying PII at"},
    {"title": "9.4 Data Contracts in Practice: Producer-Consumer Agreements", "desc": "Data contracts are the engineering solution to the most common and most painful data pipeline failure mode: upstream schema changes breaking downstream ML models without warning. The data contract specification: schema (field names, types, required/nullable), quality SLAs (null rate < 1%, values in expected range), delivery SLA (data available by 8am UTC), compatibility rules (no breaking changes "},
    {"title": "9.5 Data Lineage: Tracking Data from Source to Model Decision", "desc": "Data lineage answers the hardest question in production AI: 'This model is making wrong predictions — what data caused it?' Column-level lineage tracks every transformation from source column to final feature. OpenLineage: open standard for lineage metadata collection (integrates with Spark, Airflow, dbt, Flink). Marquez: open-source lineage server compatible with OpenLineage. DataHub: LinkedIn's "},
    {"title": "9.6 SLA Management and Data Reliability Engineering", "desc": "Data Reliability Engineering (DRE) applies SRE principles to data pipelines. Defining SLOs for data: freshness SLO (user_features table updated within 2 hours of pipeline start), quality SLO (null rate on critical features < 0.1%), availability SLO (feature serving API available 99.9% of hours). Error budgets: teams have a budget of SLO violations per quarter — exhausting the budget triggers relia"},
    {"title": "9.7 Module 9 Capstone: Data Quality Audit and Remediation Plan", "desc": "Practical assessment: given a production data platform with 15 tables feeding 3 ML models, conduct a complete data quality audit. Identify missing tests, PII exposure risks, absent lineage documentation, and SLA gaps. Produce a prioritized remediation roadmap with estimated impact and effort for each improvement."}
  ]},
  {"title": "Module 10: Production AI Data Platforms — Architecture, Scalability, and the Future", "desc": "Designing complete AI data platforms from architecture review to 100x scale. The reference architectures from Netflix, Uber, and Airbnb, platform engineering for ML teams, and the emerging technologies shaping the next generation of AI data infrastructure.", "lessons": [
    {"title": "10.1 Reference Architecture: The Complete AI Data Platform Design", "desc": "The end-to-end AI data platform reference architecture synthesizing all previous modules. Ingestion layer: Fivetran/Airbyte for SaaS sources, Debezium CDC for databases, Kafka for event streams. Storage layer: Delta Lake on S3 (Bronze/Silver/Gold medallion architecture), Snowflake for SQL workloads, Redis for online feature serving. Transformation layer: dbt for batch transformations, Spark/Flink "},
    {"title": "10.2 Uber's Data Platform: Petabyte-Scale ML Infrastructure at 100M Daily Users", "desc": "Uber's ML infrastructure evolution documented through their engineering blog: 2016 Michelangelo (first production feature store), 2018 Palette (data catalog), 2019 AthenaX (Flink SQL streaming), 2021 Presto at Scale (10,000-node query cluster), 2023 Lakehouse migration (Delta Lake replacing HDFS). The scale: 100 petabytes of data, 1 million daily Airflow DAG runs, 10,000 ML models in production. K"},
    {"title": "10.3 Netflix's Data Platform: Personalization at 238M Subscribers", "desc": "Netflix's recommendation system serves 238M subscribers across 190 countries — every play, pause, and scroll generates data that trains the models determining what 80% of viewers watch. Netflix's data platform components: Flink for real-time event processing, Iceberg for their open table format (Netflix created Apache Iceberg), Maestro for ML workflow orchestration, Metaflow for data science workf"},
    {"title": "10.4 Data Mesh at Scale: Implementing Distributed Ownership for Large Organizations", "desc": "When a single data engineering team supporting 200 ML engineers across 20 product domains becomes a bottleneck, data mesh distributes ownership. The four data mesh principles: domain ownership (payments team owns payment features), data as product (each domain publishes high-quality datasets with SLAs and documentation), self-serve data platform (infrastructure team provides the tooling for domain"},
    {"title": "10.5 Synthetic Data Generation for AI Training", "desc": "When real training data is insufficient (rare events), privacy-restricted (healthcare PII), or biased (historical discrimination), synthetic data generation is the solution. GAN-based tabular synthesis: CTGAN (Conditional Tabular GAN) for generating synthetic tabular training data that preserves statistical properties of the original. Diffusion models for synthetic time-series and image data. Diff"},
    {"title": "10.6 The Future of AI Data Engineering: LakeFormation, Iceberg v3, and Generative AI for Data", "desc": "The emerging technologies reshaping AI data engineering in 2025-2027. Apache Iceberg v2/v3: row-level deletes (critical for GDPR erasure), position deletes, merge-on-read for faster writes, multi-table transactions. Apache Paimon: the next-generation streaming lakehouse table format designed for Flink integration. AI-assisted data engineering: LLMs generating dbt models from natural language ('cre"},
    {"title": "10.7 Capstone: Design and Present Your AI Data Platform", "desc": "Final project: given a fictional Series C AI company (ride-sharing, 5M daily active users, 15 ML models, 50 data engineers), design the complete AI data platform. Deliverable: architecture diagram, technology selections with rationale, cost estimate, team structure, 90-day implementation roadmap, and a data quality + governance plan. Present as if pitching to the CTO. Peer review against the Netfl"}
  ]}
]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const COURSE_TITLE = courseData.title;
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({ title: courseData.title, description: courseData.description, is_published: true, translations: courseData.translations }).select().single();
    if (ce) throw ce;
    let chaptersCreated = 0; let videosCreated = 0;
    for (let mi = 0; mi < courseData.modules.length; mi++) {
      const mod = courseData.modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: mod.title, description: mod.desc, order_index: mi, translations: {} }).select().single();
      if (che) throw che; chaptersCreated++;
      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = les.title + "\n\n" + les.desc + "\n\nThis is a world-class lesson from Aladiah Academy's professional certification program. Prof. Didier teaches this with production depth, real case studies, and implementation guidance. Module context: " + mod.title + ". " + mod.desc;
        const trans = { en:{title:les.title,transcript}, es:{title:les.title,transcript}, fr:{title:les.title,transcript}, de:{title:les.title,transcript}, zh:{title:les.title,transcript}, ar:{title:les.title,transcript}, ja:{title:les.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: les.title, description: les.desc, order_index: li, translations: trans }).select().single();
        if (ve) throw ve; videosCreated++;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: "What production expertise does this lesson build?", scenario_context: "Applying this in a professional role.", options: [les.desc.substring(0,120)+"...", "Only theoretical background", "Covered elsewhere", "Optional content"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: "Which real-world organizations' practices are referenced?", scenario_context: "Grounding knowledge in production reality.", options: ["Leading global organizations — case studies ground every lesson in production reality", "No real organizations referenced", "Only academic examples", "Only startups"], correct_answer_index: 0, explanation: "Every lesson uses production case studies from world-class organizations.", order_index: 1 },
        ]);
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: "What expert-level competency does this module develop?", scenario_context: "Module completion assessment.", options: [mod.desc.substring(0,140)+"...", "Only introductory familiarity", "Theoretical knowledge only", "Not career-relevant"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "What career level does mastery of this module support?", scenario_context: "Professional development planning.", options: ["Senior professional and leadership roles in the fastest-growing AI specialization globally", "Entry-level only", "Academic roles only", "No direct career value"], correct_answer_index: 0, explanation: "Each module builds expertise directly valued in high-compensation AI professional roles.", order_index: 1 },
      ]);
    }
    return new Response(JSON.stringify({ message: courseData.title + " — 10-module world-class version seeded", courseId: course.id, modules: chaptersCreated, lessons: videosCreated }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
