import { requireAdminOrServiceRole, corsHeaders } from "../_shared/adminGuard.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
  "description": "Master product management for the AI era — from discovery and strategy through launch and continuous improvement. 10 modules covering AI product strategy, Jobs-to-be-Done, AI-specific metrics, experimentation, responsible AI, and building products where AI is the core capability, not a feature add-on.",
  "translations": {
    "es": {
      "title": "AI Product Manager",
      "description": "Master product management for the AI era — from discovery and strategy through launch and continuous improvement. 10 modules covering AI product strategy, Jobs-to-be-Done, AI-specific metrics, experim"
    },
    "fr": {
      "title": "AI Product Manager",
      "description": "Master product management for the AI era — from discovery and strategy through launch and continuous improvement. 10 modules covering AI product strategy, Jobs-to-be-Done, AI-specific metrics, experim"
    },
    "de": {
      "title": "AI Product Manager",
      "description": "Master product management for the AI era — from discovery and strategy through launch and continuous improvement. 10 modules covering AI product strategy, Jobs-to-be-Done, AI-specific metrics, experim"
    },
    "zh": {
      "title": "AI Product Manager",
      "description": "Master product management for the AI era — from discovery and strategy through launch and continuous improvement. 10 modules covering AI product strategy, Jobs-to-be-Done, AI-specific metrics, experim"
    },
    "ar": {
      "title": "AI Product Manager",
      "description": "Master product management for the AI era — from discovery and strategy through launch and continuous improvement. 10 modules covering AI product strategy, Jobs-to-be-Done, AI-specific metrics, experim"
    },
    "ja": {
      "title": "AI Product Manager",
      "description": "Master product management for the AI era — from discovery and strategy through launch and continuous improvement. 10 modules covering AI product strategy, Jobs-to-be-Done, AI-specific metrics, experim"
    }
  },
  "modules": [
  {
    "title": "Module 1: The AI PM Role — Product Thinking for AI Systems",
    "desc": "AI Product Managers navigate the intersection of user needs, business strategy, and ML capabilities. The role, responsibilities, required skills, discovery methods for AI products, and the PM frameworks that work (and don't work) for AI.",
    "lessons": [
      { "title": "1.1 What Makes AI PM Different", "desc": "Traditional product management fundamentals apply to AI products — but several things change fundamentally. The AI PM's unique responsibilities: scoping what ML can actually deliver (expectation management with stakeholders who overestimate AI), defining model evaluation criteria (what does 'good enough' accuracy mean for this product?), managing the probabilistic nature of AI outputs (designing for errors, not just the happy path), and communicating uncertainty to users and executives. Skills required: statistical literacy (understand precision/recall tradeoffs, confidence intervals, A/B test significance), technical fluency (enough ML to challenge engineers and avoid requirements that are technically infeasible), and user empathy for AI-mediated experiences (how users develop trust and mental models of AI). The AI PM's key partners: ML engineers (translate product requirements into model objectives), data scientists (validate that data supports product requirements), platform engineers (understand infrastructure constraints). Case study: the product decisions behind Gmail's Smart Compose — the PM defined 'good enough' as users accepting suggestions 10% of the time, which justified the compute cost." },
      { "title": "1.2 Discovery for AI Products", "desc": "AI product discovery starts with problems, not models. The trap: 'we have an ML team, let's find problems for them to solve' — produces solutions looking for problems. The right approach: discover genuine user pain points, then evaluate whether AI is the best solution. AI opportunity identification framework: Where is human judgment being applied repeatedly and consistently? (prime candidate for automation) Where is information overload preventing good decisions? (prime candidate for AI-powered filtering and prioritization) Where do users express effort complaints about mental tasks? (prime candidate for AI assistance). Validation techniques for AI products: Wizard of Oz testing (manually perform what AI would do — validate user value before building model), concierge MVP (human-powered version that teaches you what data you need), user interviews on current behavior (understand mental models before introducing AI). Anti-pattern: skipping discovery and building the model first — produces technically impressive demos that users don't actually need. Case study: Grammarly's discovery: users complained about time spent reviewing writing, not about grammar errors per se — this reframe led to their tone suggestions feature, which drove 3x engagement." },
      { "title": "1.3 Writing Requirements for ML Systems", "desc": "ML systems require a different requirements format than traditional software. Feature-based requirements (user can sort by date) don't work for ML (model should predict churn accurately). The AI requirements template: problem statement (what user pain does this solve?), success metric (what business/user outcome proves the model works?), model objective (what mathematical objective proxies for the success metric?), evaluation criteria (minimum performance thresholds for launch), data requirements (what training data is needed, is it available?), error tolerance (what happens when the model is wrong — what errors are acceptable?). The accuracy requirement conversation: PMs must translate business tolerance for errors into ML precision/recall requirements. Example: a content moderation model — false negatives (missed harmful content) are worse than false positives (incorrectly removed content) → optimize for recall over precision. Case study: how the YouTube recommendation team defines requirements — watch time as the optimization metric, with guardrails on unhealthy content engagement." },
      { "title": "1.4 AI Product Roadmaps and Prioritization", "desc": "AI product roadmaps must account for data availability, model development timelines, and the iterative nature of ML improvement. Roadmap tiers for AI products: foundational (data infrastructure, model v1 — slow, invisible to users), core product (model integrated into user flow), enhancement (model quality improvements, new capabilities). Prioritization frameworks adapted for AI: ICE (Impact × Confidence × Ease) with an additional Data Readiness dimension — ideas without adequate training data are blocked regardless of ICE score. The model improvement roadmap: accuracy improvements have diminishing returns at high accuracy — a model improving from 70% to 80% accuracy has more user impact than 95% to 96%. Data flywheel: product features that generate training data as a side effect accelerate the roadmap. Example: showing users why a recommendation was made generates implicit feedback that trains the model. Case study: Spotify's Discover Weekly roadmap — weekly model retraining unlocked the 'personalized to your taste' value proposition that made it viral." },
      { "title": "1.5 Designing for AI Errors", "desc": "Every AI system makes mistakes — great AI products are designed for errors, not around them. The error design framework: what types of errors does the model make? (false positives vs. false negatives), who experiences the error? (the user who receives the wrong recommendation vs. the user whose content gets incorrectly removed), what is the impact of each error type? (embarrassment vs. financial loss vs. safety risk). Design patterns for graceful AI errors: uncertainty communication (show confidence scores, use hedged language: 'This looks like...' instead of 'This is...'), correction mechanisms (users can easily override AI decisions), error recovery (clear path to getting the right answer after an error), fail-safe defaults (when the model is uncertain, default to the safe option). The psychological impact of AI errors: users form models of when AI is reliable — inconsistent errors are more damaging than consistent errors because they destroy predictability. Case study: Netflix's recommendation design — 'Because you watched X' attribution helps users understand and predict errors, increasing trust despite imperfect recommendations." },
      { "title": "1.6 Measuring AI Product Success", "desc": "AI product metrics require tracking both model quality and product impact — they can diverge. Model metrics: accuracy, precision, recall, F1, AUC-ROC (offline, measured against labeled data), latency, throughput. Product metrics: engagement rate, task completion rate, user satisfaction (CSAT, NPS), revenue impact, error recovery rate. The metrics hierarchy: model metrics are leading indicators, product metrics are the actual outcome. Anti-pattern: optimizing model metrics at the expense of product metrics. Example: a recommender with higher CTR but lower satisfaction (users click but don't enjoy). Guardrail metrics: metrics that must not regress even when improving primary metrics. Example: diversity of recommendations is a guardrail — improving average watch time by making recommendations less diverse is a net negative. Experimentation design for AI: A/B testing model versions requires careful holdout design (users in control group must not see any treatment signals). Case study: Airbnb's search ranking — the PM team tracks both nDCG (model quality) and booking rate (product outcome) weekly — when they diverge, it signals a problem in the model objective." },
      { "title": "1.7 Module 1 Assessment: AI Product Opportunity Analysis", "desc": "Analyze a provided product brief for an AI-powered feature. Identify: the core user problem, whether AI is the right solution (or if a simpler approach would work), success metrics with specific thresholds, model requirements translated from user needs, error design considerations, and a 6-month roadmap with dependencies. Present your recommendation on whether to build and your go/no-go criteria." }
    ]
  },
  {
    "title": "Module 2: AI Strategy — Building Products That Compound",
    "desc": "The most valuable AI products create data flywheels that compound over time. Network effects in AI, competitive moats, build-vs-buy-vs-partner decisions, AI product strategy frameworks, and the strategic thinking at Duolingo, LinkedIn, and Figma.",
    "lessons": [
      { "title": "2.1 AI Competitive Moats: Data, Network Effects, and Switching Costs", "desc": "AI products build competitive moats through assets that are difficult to replicate. Data moat: proprietary training data that competitors cannot easily acquire. Examples: Waymo's 20M+ miles of real-world driving data, Duolingo's 500M user language learning sessions. The data moat is strongest when data is generated by the product itself and requires scale to collect. Network effect moat: AI improves as more users interact, making the product better for everyone. LinkedIn's recommendation model — more connections → more signal → better job recommendations for all users. Switching cost moat: users who have trained an AI on their data or preferences face high switching costs. Adobe Firefly — creative professionals who have established a style are unlikely to switch. Talent moat: concentration of ML expertise creates temporary advantages. The sustainable moat question: what would make this AI product worse to copy than to build from scratch? Case study: Spotify's audio fingerprinting and recommendation model — 10 years of listening data across 500M users creates a moat that no new entrant can replicate quickly." },
      { "title": "2.2 The Data Flywheel: Designing Products That Train Themselves", "desc": "The data flywheel is the mechanism by which AI products improve with use — creating compounding competitive advantage. Flywheel anatomy: users interact with product → interactions generate labeled training data → model trains on new data → model improves → product gets better → more users attracted. Designing flywheel data collection: explicit feedback (thumbs up/down — high signal, low volume), implicit feedback (session length, click-through, task completion — high volume, noisy signal), generated data (user inputs that directly become training examples). Flywheel acceleration levers: increase signal clarity (better feedback mechanisms), increase feedback volume (more users, more sessions), decrease flywheel cycle time (faster retraining pipelines). Flywheel traps: cold start problem (flywheel requires initial data to start — bootstrapping strategy required), data quality degradation (flywheel can amplify biases in early data). Case study: TikTok's FYP flywheel — each video completion, share, or comment trains the model, which improves recommendations, which increases engagement, which generates more training data. The flywheel reached escape velocity in 18 months." },
      { "title": "2.3 Build vs. Buy vs. Partner: AI Capability Decision Framework", "desc": "AI capabilities have a spectrum of strategic importance — not everything should be built in-house. Strategic AI capabilities (build): AI that directly creates competitive differentiation, that requires proprietary data not available elsewhere, or that needs to be deeply integrated with core product. Infrastructure AI (buy): generic capabilities available as APIs (speech-to-text, OCR, translation), underlying models (foundation models via API), and observability/monitoring tools. Partnership opportunities: capabilities where a vendor's specialization provides better outcomes than in-house development, joint development with customers who have data you need. Decision factors: proprietary data advantage (if your data is what makes the AI work, build), competitive differentiation (if AI is core to your positioning, build), team capability (if you don't have ML expertise, buy), speed (buying is always faster, building is sometimes necessary). Case study: how Notion decided to build their AI on top of GPT-4 (buy the foundation model, build the product integration) vs. training their own model — the decision preserved their 10-person ML team for product-differentiating work." },
      { "title": "2.4 Product-Led AI Growth: Viral Loops and AI-Native Acquisition", "desc": "AI-native products create novel growth loops not available to traditional software. AI-powered virality: outputs shared externally generate organic acquisition (Midjourney images shared on Twitter, ChatGPT conversation screenshots). The share-as-acquisition pattern: design AI outputs to be shareable and to signal the product's value to new users. AI-powered onboarding: personalized onboarding that adapts to user behavior increases activation rates. AI-powered retention: proactive AI interventions that predict churn and engage at-risk users. Product-led growth for AI: free tier with AI limits creates upgrade motivation (GitHub Copilot free tier). The product-led AI growth metrics: activation rate (did the user experience the core AI value?), time-to-value (how quickly did the AI deliver a compelling output?), share rate (what percentage of AI outputs are shared externally?). Case study: Midjourney's growth to $200M ARR with no paid marketing — every shared image on social media was a product demo. The PM's job was to maximize output quality and shareability, not run ads." },
      { "title": "2.5 Responsible AI Product Strategy: Ethics, Trust, and Long-Term Sustainability", "desc": "Responsible AI is not just ethically required — it's strategically necessary. Trust as a product feature: users who don't trust AI outputs don't use them. Trust-building mechanisms: transparency (explain how the AI works and why it makes decisions), consistency (users must be able to predict when the AI will and won't work well), control (users must be able to override AI decisions easily). Ethical risks that become product risks: bias in recommendations (hiring AI that disadvantages protected groups → regulatory action + reputational damage), privacy violations (training on user data without clear consent → GDPR fines + user backlash), misinformation (AI that generates false information confidently → user trust collapse). The PM's ethical responsibility: advocate for users who might be harmed by the AI, not just users who benefit. Design for all users, including vulnerable populations. Case study: how Facebook's PM team navigated the news feed algorithm — optimizing for engagement without guardrails on harmful content created the misinformation amplification problem. The product decision that seemed to improve metrics created a societal harm." },
      { "title": "2.6 International AI Product Strategy: Localization, Regulation, and Cultural Adaptation", "desc": "AI products face unique internationalization challenges beyond language translation. Training data representation: models trained predominantly on English data perform worse in other languages — international product strategy requires investment in multilingual training data. Regulatory adaptation: EU AI Act creates different requirements than US market (explainability requirements, prohibited use cases, conformity assessments). Cultural adaptation of AI outputs: content that is appropriate in one culture may be offensive in another — content filtering models need cultural calibration. Data localization requirements: some countries require that AI training data and model serving happen within national borders (China PIPL, Russia data localization). Case study: Duolingo's international AI strategy — their language model is separately trained and calibrated for each language pair, with significant investment in non-English training data that competitors have not matched. This creates a competitive moat in underserved languages." },
      { "title": "2.7 Module 2 Assessment: AI Product Strategy Memo", "desc": "Write a product strategy memo for a new AI feature at a company you select. The memo must address: the user problem and why AI is the right solution, the competitive moat this creates, the data flywheel design, build-vs-buy decision for each AI component, go-to-market strategy including viral loop design, responsible AI considerations, and international expansion plan for 2 non-English markets." }
    ]
  },
  {
    "title": "Module 3: User Experience for AI Products",
    "desc": "AI UX requires designing for a fundamentally different user experience — probabilistic outputs, progressive disclosure of intelligence, and building trust with users who may be skeptical. Mental models, onboarding, error design, and the UX patterns at Notion, Linear, and Figma.",
    "lessons": [
      { "title": "3.1 Mental Models for AI: How Users Understand (and Misunderstand) AI", "desc": "Users develop mental models of how AI works — and when those models are wrong, frustration and distrust follow. The two failure modes of AI mental models: overestimation (user expects AI to understand anything, is frustrated when it doesn't) and underestimation (user doesn't try AI for tasks it would handle well). Designing for accurate mental models: onboarding that sets expectations, capability discovery features that show what the AI can do, limitation disclosure (proactively communicate what the AI doesn't handle well). The automation bias problem: users tend to follow AI recommendations even when they're wrong — design must support appropriate skepticism. The uncanny valley for AI: AI that almost understands humans but makes subtle errors is more disturbing than AI with obvious limitations. UX patterns for mental model alignment: example inputs (show users what kinds of requests work well), confidence indicators (visual treatment that communicates uncertainty), limitation messaging ('I work best when you...'). Case study: Siri's design — initial overmarketing created unrealistic expectations that led to backlash when limitations became apparent. Linear's AI assistant sets expectations with explicit 'can' and 'can't' documentation." },
      { "title": "3.2 Progressive Disclosure of Intelligence: Building Trust Before Complexity", "desc": "Introducing AI capabilities too aggressively overwhelms users and undermines trust. The progressive disclosure framework for AI: start with high-confidence, low-stakes suggestions (user gains trust through successful small interactions), gradually introduce higher-stakes suggestions as trust builds, make AI assistance opt-in by default for significant actions. Trust ladder stages: awareness (user knows AI is available), trial (user tries AI on low-stakes tasks), adoption (user relies on AI for routine tasks), integration (user thinks in terms of AI-assisted workflows). Trust calibration failure: if the AI makes a consequential error early in the relationship, it can permanently damage trust. UX safeguards during trust building: reversibility (easy undo for any AI action), confirmation for consequential actions (require explicit approval for irreversible AI decisions), clear attribution (user knows when AI was involved in a decision). Case study: Notion AI's rollout — they launched with grammar/tone suggestions (low stakes, high accuracy) before introducing content generation, building user trust in the AI's capabilities progressively." },
      { "title": "3.3 Designing AI Onboarding: From Skeptic to Power User", "desc": "AI onboarding must accomplish more than traditional software onboarding — it must transform user behavior, not just teach features. AI onboarding goals: demonstrate value in the first session, calibrate user expectations, establish the habit of using AI assistance. The 'aha moment' for AI products: the moment when the user first experiences the AI doing something they couldn't easily do themselves. Designing for the aha moment: identify the highest-value single interaction, optimize the flow to reach it within the first session, remove all friction between account creation and that interaction. Data collection during onboarding: preferences gathered during onboarding bootstrap personalization before behavioral data accumulates (cold start solution). The onboarding-to-habit formation loop: structured onboarding → first success → autonomous exploration → regular use. Anti-pattern: feature-focused onboarding ('click here to use AI') vs. outcome-focused onboarding ('let's improve your first document together'). Case study: Duolingo's onboarding is the gold standard — streak mechanics, bite-sized success, immediate personalization. Users complete tasks before creating an account, creating investment before commitment." },
      { "title": "3.4 Feedback Loops: Designing Interactions That Improve the Model", "desc": "Great AI products design user interactions that simultaneously provide value and generate training data. Explicit feedback mechanisms: rating systems (thumbs up/down — simple but captures strong signal), correction interfaces (let users fix AI errors — generates high-quality labeled training examples), preference comparisons (A/B between two options — pairwise ranking data). Implicit feedback signals: task completion (user accepted AI suggestion and continued — positive signal), abandonment (user closed suggestion without acting — negative signal), modification (user edited AI output — generates preferred version as training target). Feedback loop design principles: minimize friction (feedback that requires effort won't be given at scale), close the loop (tell users how their feedback improves the product — increases participation), incentivize quality feedback (give power users who provide feedback early access to new features). Case study: GitHub Copilot's feedback design — accept/reject/modify at the line level, with anonymous telemetry for accepted completions. The feedback loop drove model quality improvements that increased acceptance rates from 27% to 35% in year 1." },
      { "title": "3.5 Communicating Uncertainty: Design Patterns for Probabilistic Outputs", "desc": "AI outputs are probabilistic — users need visual and textual cues to calibrate their trust appropriately. Uncertainty communication spectrum: high confidence (state the output directly), moderate confidence (soft language: 'This might be...', 'Consider...'), low confidence (explicit uncertainty: 'I'm not sure about this', confidence percentage). Visual uncertainty indicators: color coding (green for high confidence, yellow for moderate, red for uncertain), opacity variation, confidence bars or percentages. Calibration as a UX goal: users should trust AI outputs at the rate they deserve trust — overconfidence in presentation leads to overreliance. The uncertainty paradox: showing uncertainty reduces immediate satisfaction but increases long-term trust and retention. Adaptive uncertainty display: show uncertainty prominently for new users (calibration period), reduce prominence as users demonstrate good calibration (avoid noise for experienced users). Case study: Google Maps route confidence — 'Fastest route: 23 min' vs. 'Route may take 23-35 min due to traffic uncertainty' — the conditional uncertainty display helped users plan better, increasing satisfaction despite more hedged language." },
      { "title": "3.6 Inclusive AI Design: Designing for Diverse Users and Avoiding Harm", "desc": "AI products serve diverse users — inclusive design ensures AI works for everyone, not just the majority. Bias in AI UX: models trained on majority-group data perform worse for minority groups — UX must surface this limitation rather than presenting uniform confidence. Accessibility for AI outputs: AI-generated content must meet accessibility standards (alt text for AI images, readable language level for AI text). Cultural sensitivity in AI outputs: content that works for one culture may be inappropriate in another — UX must support cultural adaptation without putting the burden on users to avoid harm. Inclusive feedback design: feedback mechanisms must be accessible across ability levels, languages, and devices. The double burden problem: underserved users both experience AI failures more often AND must put more effort into correcting those failures. UX responsibility: design feedback mechanisms that are especially easy for underserved users to use. Case study: how a hiring AI platform redesigned their UX after discovering their AI was performing worse for candidates with non-Western names — they added explicit bias reporting, candidate-facing accuracy indicators by demographic, and clear human review escalation." },
      { "title": "3.7 Module 3 Assessment: AI UX Redesign", "desc": "Analyze the UX of a provided AI product (screenshots and user research provided). Identify: mental model misalignments, trust-building failures, missing uncertainty communication, onboarding gaps, and feedback mechanism weaknesses. Produce a redesigned UX with wireframes for the 5 highest-impact changes, with rationale grounded in AI UX principles." }
    ]
  },
  {
    "title": "Module 4: Data Strategy for AI Products",
    "desc": "The best AI product strategy is often the best data strategy. Training data acquisition, data quality management, privacy-preserving data collection, synthetic data, and the data strategies at Scale AI, Snorkel, and Labelbox.",
    "lessons": [
      { "title": "4.1 Training Data Strategy: Quality, Coverage, and Collection Methods", "desc": "The quality of training data determines the ceiling on model quality — great data strategy is great product strategy. Data quality dimensions: accuracy (labels are correct), completeness (all relevant cases are covered), consistency (same cases labeled the same way), freshness (data reflects current patterns, not outdated behavior). Data collection methods: user interactions (behavioral data from product use — scalable, implicit), human labeling (hired annotators label data — expensive, explicit, high quality), programmatic labeling (rules or weaker models generate labels — scalable, lower quality), self-supervised learning (use data structure as supervision signal — no labeling required). Data coverage strategy: identify edge cases that the model must handle (rare but consequential cases), collect targeted data for underrepresented scenarios, monitor for distribution drift that creates coverage gaps. Case study: Waymo's data collection strategy — a purpose-built data collection fleet drives in challenging conditions specifically because those rare scenarios (night rain, construction zones) are critical to safety and underrepresented in normal driving data." },
      { "title": "4.2 Human-in-the-Loop: Annotation, Quality Control, and Workforce Management", "desc": "Human annotation is the fuel of supervised ML — managing the annotation workforce is a critical product capability. Annotation platform selection: Scale AI (enterprise quality, highest cost), Labelbox (strong tooling, mid-market), Toloka (global crowd workforce, lower cost), in-house (full control, highest overhead). Annotation quality control: gold standard tests (inject known-answer questions to measure annotator accuracy), inter-annotator agreement (same task to multiple annotators — disagreement reveals ambiguous cases), consensus resolution (adjudication process for disagreements). Annotator instructions: clear, consistent instructions are the highest-leverage investment in annotation quality. Annotator experience: annotations produced by confused or fatigued annotators are low quality regardless of platform. Active learning: use the model to identify which unlabeled examples would most improve performance — annotate those first (5x more efficient than random sampling). Case study: how Snorkel AI's programmatic labeling approach reduced annotation cost by 10x for enterprise customers — generating weak labels programmatically for high-volume tasks." },
      { "title": "4.3 Privacy-Preserving Data Collection: GDPR, Consent, and Differential Privacy", "desc": "Data collection for AI must respect user privacy — both legally and ethically. GDPR requirements for AI training data: explicit consent for personal data use, purpose limitation (data collected for one purpose can't be used to train a different AI without consent), data minimization (collect only what's needed for the model). Privacy-by-design for AI products: collect behavioral data rather than personal attributes when possible, anonymize training data before use, provide clear privacy controls that let users opt out of AI training. Differential privacy: add calibrated statistical noise to training data to provide mathematical privacy guarantees — used by Apple for keyboard predictions, Google for Chrome suggestions. Federated learning: train models on device without centralizing user data — Google's Gboard uses federated learning for next-word prediction across 1 billion Android devices. Case study: how DuckDuckGo built a privacy-preserving search ranking AI — no user profiles, no tracking cookies, model trained on aggregate search patterns rather than individual user data." },
      { "title": "4.4 Synthetic Data: When Real Data Is Insufficient, Unavailable, or Risky", "desc": "Synthetic data generation enables AI training when real data has constraints. Use cases for synthetic data: rare events (fraud patterns, medical conditions, safety failures — insufficient real examples), privacy protection (healthcare AI training without exposing real patient data), data augmentation (expand small datasets with plausible variations). Synthetic data generation methods: GANs (Generative Adversarial Networks — realistic image and tabular data), simulation (physical simulations for robotics and autonomous vehicles), rule-based generation (structured data from domain rules). Evaluation of synthetic data quality: fidelity (does it match real data statistics?), utility (does a model trained on synthetic data generalize to real data?), privacy (can individual real records be reconstructed from synthetic data?). Synthetic data risks: distribution shift (synthetic data may not capture rare but important patterns from real data), amplified biases (synthetic data generated from biased real data amplifies those biases). Case study: Waymo trains their autonomous vehicle perception models on synthetic environments — photorealistic simulations allow testing scenarios that would be unethical to test in reality." },
      { "title": "4.5 Data Governance for AI Products: Lineage, Access Control, and Compliance", "desc": "Data governance ensures that AI training data is trustworthy, compliant, and auditable. Data lineage for ML: trace every model back to its training data sources, transformations, and versions. Regulatory requirement: EU AI Act requires documentation of training data for high-risk AI systems. Access control for training data: ML engineers should not have direct database access to user data — access mediated through approved datasets with appropriate anonymization. Data retention policies: GDPR right to erasure requires the ability to delete training data and retrain models. The machine unlearning challenge: deleting a user's data from a trained model is computationally expensive — architecture decisions (differential privacy, sharded training) can make this feasible. Sensitive attribute handling: protected attributes (race, gender, religion) require special handling in training data — may need to be excluded or carefully used with fairness constraints. Case study: how Spotify manages music preference data for their recommendation model — user data anonymized before training, 30-day deletion requests processed within 90 days with model retraining." },
      { "title": "4.6 Data Partnerships and Acquisition: External Data Strategy", "desc": "Many AI products require data that cannot be collected from product interactions alone. Data partnership models: revenue sharing (partner provides data, receives percentage of value generated), joint development (both parties contribute data and capability to build shared AI), licensing (purchase access to proprietary datasets). Data marketplace options: AWS Data Exchange (600+ data providers), Snowflake Data Marketplace, industry-specific data providers. Data quality evaluation for third-party data: provenance (how was the data collected?), licensing terms (what can I use it for?), freshness (when was it last updated?), accuracy (how was quality validated?). The data partnership risk: vendor lock-in, data accuracy liability, potential competitive conflict. Data acquisition strategy for startups: prioritize building data collection mechanisms over building models — proprietary data is the enduring competitive advantage. Case study: how Zillow built their Zestimate home valuation model — they partnered with county assessors and MLS databases to get the training data that no competitor could easily replicate." },
      { "title": "4.7 Module 4 Assessment: Data Strategy Plan", "desc": "Develop a complete data strategy for a new AI product: a medical diagnosis assistance tool for primary care physicians. Address: training data acquisition (sources, collection methods, annotation strategy), privacy requirements (HIPAA compliance, consent design), data governance (lineage, access control, deletion policy), synthetic data use cases, and a 12-month data roadmap with milestones. Identify the single most important data investment that will determine the product's success or failure." }
    ]
  },
  {
    "title": "Module 5: Shipping AI Features — From Prototype to Production",
    "desc": "Getting AI features from experiment to production requires specialized skills. The AI product development lifecycle, working with ML teams, defining launch criteria, rollout strategies, and the shipping practices at GitHub, Figma, and Stripe.",
    "lessons": [
      { "title": "5.1 The AI Product Development Lifecycle", "desc": "AI product development has a fundamentally different lifecycle than traditional software development — acknowledging this difference is the first step to managing it effectively. The AI lifecycle: problem definition → data collection → model development → offline evaluation → online evaluation (A/B test) → gradual rollout → monitoring. Key differences from traditional software: non-deterministic development timeline (ML experiments may not converge on expected timeline), evaluation requires labeled data (validation takes time), gradual rollout is the norm (not big bang releases). PM responsibilities at each stage: problem definition (translate user needs to model objectives), data collection (prioritize and unblock data acquisition), model development (remove blockers, manage stakeholder expectations), evaluation (define success criteria, interpret A/B test results), rollout (manage stakeholder communication, monitor user impact). The iteration cycle: AI products improve through iteration — the roadmap is a series of model improvements, not a fixed feature set. Case study: how GitHub Copilot went from research prototype to 1M+ users — the product lifecycle included 2 years of internal testing and iteration before public beta." },
      { "title": "5.2 Working With ML Teams: Translation, Unblocking, and Managing Expectations", "desc": "The PM-ML engineer relationship is the most important cross-functional relationship in AI product development. Translation work: business requirements → model objectives (not 'make recommendations better' → 'increase session engagement by 15% without increasing churn'), model outputs → user features (a probability score → a UI element that communicates uncertainty appropriately). Unblocking ML teams: data access (work with data engineering to get ML teams the data they need), compute resources (advocate for GPU budget), annotation prioritization (coordinate with annotation team to prioritize highest-impact labeling tasks). Managing expectations: ML development is research — timelines are inherently uncertain. Communicate ranges, not point estimates, to stakeholders. The experiment failure conversation: most ML experiments don't produce production-ready models. Normalize failure as part of the process. Velocity metrics for ML teams: experiments-per-sprint (how many hypotheses are being tested?), experiment-to-production rate (what percentage of experiments ship?). Case study: how Stripe's ML team manages PM relationships — weekly experiment review meetings where PMs see early results and can redirect experiments before completing full runs." },
      { "title": "5.3 Offline vs. Online Evaluation: When the Lab Doesn't Match Production", "desc": "Models that perform well in offline evaluation frequently underperform in production — understanding why is critical to shipping AI products that work. Offline evaluation: assess model performance on a held-out test set. Fast, cheap, no user impact. Online evaluation (A/B test): assess model performance on real users. Slow, expensive, ground truth for business metrics. The offline-online gap causes: test set distribution mismatch (test set doesn't represent production distribution), label quality issues (test labels don't match production ground truth), selection bias (users who generate offline test data are different from average users). Bridging the gap: use production data for evaluation, instrument production carefully to collect ground truth labels, use shadow deployment to compare model predictions to production outcomes without changing user experience. The A/B test design for AI: randomization unit (user-level vs. session-level), experiment duration (long enough to capture behavioral changes), metrics hierarchy (primary metric, guardrail metrics, exploratory metrics). Case study: how Netflix's ML team discovered that improvements in their offline metric (NDCG) were not consistently predictive of improvements in their online metric (watch time) — leading to a redesign of their offline evaluation protocol." },
      { "title": "5.4 Gradual Rollout Strategies: Canary, Shadow, and Progressive Deployment", "desc": "AI features require staged rollout to validate in production before full deployment. Shadow mode: new model runs on production traffic, predictions logged but not shown to users — no user impact, allows comparison to production model. Canary deployment: new model serves a small percentage of users (1-5%) while old model serves the rest — real user impact on a limited population. Progressive rollout: canary percentage increases over time as metrics validate (1% → 5% → 25% → 100%). Hold-back groups: permanent 5-10% of users who never see the new model — allows continued comparison post-launch. Rollback criteria: define before launch the specific conditions that would trigger rollback (primary metric drops >X%, error rate exceeds Y%). The rollout calendar: coordinate with business events (don't do a major AI rollout during Black Friday), customer success teams (brief before rollout to handle support volume), legal/compliance (for regulated AI features). Case study: how Facebook rolled out their News Feed AI — starting with a 0.1% canary, monitoring 15 metrics simultaneously before each expansion, taking 6 months to reach 100% rollout for major algorithm changes." },
      { "title": "5.5 Launch Communication: Positioning AI Features to Users and Media", "desc": "How an AI feature is positioned determines whether users trust it, try it, and continue using it. User communication principles: be honest about capabilities and limitations, avoid anthropomorphization that creates false expectations, use concrete examples rather than abstract descriptions of AI capabilities. The AI feature announcement trap: over-promising on AI capabilities in press releases creates backlash when limitations are discovered. Internal communication: brief customer success, sales, and support teams before launch — they will receive questions about how the AI works. Media communication: emphasize user value, not technology. 'Feature that suggests next steps so you can focus on creative work' vs. 'AI-powered next action prediction using machine learning.' The opt-in vs. opt-out decision: AI features that change user behavior should be opt-in by default (trust building), AI features that are purely additive (autocomplete suggestions) can be opt-out. Case study: how Notion positioned their AI launch — leading with specific writing use cases ('unstick writer's block', 'summarize meeting notes'), not ML architecture. Result: 60% activation rate in the first week." },
      { "title": "5.6 Post-Launch Monitoring and the AI Feedback Loop", "desc": "Shipping is not the end of AI product development — it's the beginning of the improvement loop. Post-launch monitoring dashboard: primary success metric (daily), model performance metrics (prediction accuracy, latency), error rates (types of errors, user impact), user feedback signals (thumbs down, error reports, churn from AI feature cohort). The monitoring cadence: daily checks on core metrics, weekly review of model performance, monthly review of data distribution drift. Responding to post-launch issues: prediction quality degradation (trigger model retraining), data drift (investigate source data changes), feature failure (implement fallback, debug, and fix). Continuous improvement cycle: post-launch data is the richest source of training signal — set up pipelines to feed production interactions back into model training. Feature iteration: AI features are never 'done' — plan quarterly model updates as product investment. Case study: how Google Maps continuously improves ETA predictions — post-launch monitoring of prediction vs. actual travel time, with daily retraining on the delta. Model accuracy has improved 40% since launch through continuous monitoring and retraining." },
      { "title": "5.7 Module 5 Assessment: AI Launch Plan", "desc": "Develop a complete launch plan for an AI feature: an automated meeting summary and action item extraction tool for a B2B SaaS product. Cover: development lifecycle milestones, ML team collaboration plan, offline and online evaluation strategy with specific success metrics, rollout strategy (shadow → canary → full), rollback criteria, user communication plan, and post-launch monitoring dashboard. Include the key risks and your mitigation plans for each." }
    ]
  },
  {
    "title": "Module 6: AI Product Analytics — Measuring What Matters",
    "desc": "AI product analytics requires tracking novel metrics — not just standard engagement metrics. Funnel analytics for AI features, cohort analysis for AI trust building, model performance monitoring, and the analytics practices at Amplitude, Mixpanel, and Heap.",
    "lessons": [
      { "title": "6.1 AI Product Funnel: From Discovery to Reliance", "desc": "AI features have a unique adoption funnel that differs from traditional product funnels. AI adoption funnel stages: discovery (user learns AI feature exists), trial (user tries AI feature for the first time), activation (user experiences first meaningful value), adoption (user regularly uses AI in workflow), reliance (user's workflow depends on AI). Funnel metrics by stage: discovery (feature awareness survey %), trial (first interaction rate within 30 days of discovery), activation (percentage of first interactions that produce a 'success' — defined as user accepting AI output or completing the intended task), adoption (percentage of eligible sessions where AI is used), reliance (percentage of user's task completions assisted by AI). Funnel drop-off analysis: identify where users disengage and why. Common AI funnel failures: low trial rate (discoverability problem), low activation (quality problem — AI outputs don't deliver value), low adoption (habit formation problem — users try but don't return). Case study: how Figma tracked their AI design features — funnel analysis revealed that 60% of users who discovered the feature never tried it (discoverability issue), leading to in-canvas prompts that doubled trial rate." },
      { "title": "6.2 Cohort Analysis for AI Trust: Measuring Trust Development Over Time", "desc": "AI trust is built over time — cohort analysis reveals the trust development trajectory. Trust cohort analysis: track users from their first AI interaction and measure behavior changes over 30/60/90/180 days. Trust metrics: acceptance rate over time (are users accepting AI suggestions at higher rates as they gain experience?), override rate over time (are users overriding AI decisions less as they calibrate trust?), task coverage expansion (are users applying AI to a wider range of tasks?), session AI engagement rate (what percentage of sessions include AI interactions?). Trust decay analysis: when users stop using AI, how long before they lose trust entirely? What events trigger disengagement? Segmented trust analysis: trust building trajectory differs by user expertise (power users trust faster), use case (high-stakes use cases require longer trust building), and prior AI experience. Case study: how Grammarly measures trust development — users who experience 3 successful writing improvement cycles in their first week have 3x better 90-day retention than users who don't. This insight drove their onboarding redesign." },
      { "title": "6.3 Model Performance Analytics: Connecting ML Metrics to User Outcomes", "desc": "ML metrics and user outcome metrics often diverge — the PM must track both and diagnose the gap. Model performance tracking: offline metrics (accuracy, precision, recall, F1 — measured against labeled test set weekly), online metrics (prediction quality proxies from user behavior — acceptance rate, task completion rate after AI suggestion), distribution metrics (are model inputs drifting from training distribution?). The metric correlation analysis: does your offline accuracy metric predict your user outcome metric? If not, investigate why the offline metric is not predictive. A/B testing ML improvements: when model v2 outperforms model v1 in offline evaluation, does it outperform in online A/B test? Track the offline-online correlation coefficient over time. Performance degradation monitoring: set up automated alerts when model performance metrics fall below thresholds. Distinguish model degradation from product degradation (user behavior changes, not model changes). Case study: how Spotify discovered that their recommendation model's offline metric (NDCG) had become less predictive of actual listening satisfaction — they redesigned their evaluation to include human listening panels alongside algorithmic metrics." },
      { "title": "6.4 Business Impact Measurement: Attributing Revenue and Retention to AI", "desc": "Proving AI's business impact is essential for continued investment. Revenue attribution for AI features: incremental revenue (revenue from users who use AI vs. matched non-users in A/B test), subscription upgrade attribution (percentage of upgrades driven by AI feature trial), feature engagement in renewal decisions (NPS surveys of renewing customers on AI feature value). Retention impact analysis: long-term retention cohorts comparing AI users vs. non-users (controlling for selection bias — AI users may be more engaged regardless of AI). The selection bias problem: users who adopt AI features are inherently more engaged — naive comparison overstates AI impact. Causal inference approaches: instrumental variables (AI feature randomized release date as instrument), difference-in-differences (compare user groups before/after AI feature access), regression discontinuity (compare users just above and below AI feature threshold). Case study: how GitHub quantified Copilot's business impact — developer productivity study (developers complete tasks 55% faster with Copilot) and enterprise renewal analysis (teams using Copilot renew at 22% higher rate than teams that don't)." },
      { "title": "6.5 A/B Testing for AI: Design, Analysis, and Common Pitfalls", "desc": "A/B testing AI features requires careful experimental design to avoid common pitfalls. Experiment design for AI: randomization unit (user-level avoids cross-contamination vs. session-level provides more observations), treatment definition (what exactly is the user exposed to?), control definition (is the control no AI, or the previous AI version?), duration (long enough to capture steady-state behavior — new features have novelty effects that fade). Common A/B test pitfalls for AI: novelty effect (users interact differently with new features — wait for effect to stabilize), network effects (AI improvements for treated users may affect control users through social interactions), experiment contamination (user switches device and experiences both treatment and control). Statistical analysis for AI tests: multiple testing correction (testing many metrics simultaneously inflates false positive rate — use Bonferroni correction or FDR control), minimum detectable effect (power analysis before the experiment — don't run under-powered tests). Case study: how LinkedIn runs A/B tests for their recommendation algorithm — 4-week minimum experiment duration, user-level randomization, and network-effect corrections for experiments on social features." },
      { "title": "6.6 Qualitative Research for AI Products: User Interviews and Usability Studies", "desc": "Quantitative analytics tells you what is happening — qualitative research tells you why. User interview protocols for AI products: exploratory interviews (understanding mental models, current workflows, trust levels — not evaluating specific features), evaluative interviews (specific feature evaluation — think-aloud protocols while using AI features). Usability study design for AI: task-based testing (complete this task using the AI feature), think-aloud protocol (articulate what you're thinking and expecting), error reaction observation (how does user respond when AI makes a mistake?). Interview analysis: thematic coding, mental model diagrams, trust spectrum mapping (where do users fall between skeptic and over-reliant?). Combining qualitative and quantitative: use quantitative data to identify where users are struggling, use qualitative research to understand why. The 5-user rule: usability studies with 5 users typically surface 80% of usability issues — don't over-invest in large qualitative studies. Case study: how Duolingo uses weekly usability studies with learners to calibrate their AI difficulty adjustment — qualitative feedback reveals what the engagement metrics can't." },
      { "title": "6.7 Module 6 Assessment: Analytics Audit", "desc": "Conduct an analytics audit of a provided AI product (you will receive a product description and sample dashboard). Identify: gaps in the measurement framework (what important metrics are missing?), data quality issues (what could be producing misleading metrics?), missing experiments (what A/B tests should be running?), attribution analysis gaps (how could you better prove AI's business impact?). Produce a revised analytics framework with the 10 most important metrics and measurement methodology for each." }
    ]
  },
  {
    "title": "Module 7: Advanced AI Product Techniques — Personalization, Recommendation, and NLP",
    "desc": "Deep dives into the product aspects of the most common AI capabilities. Personalization product design, recommendation system strategy, NLP product integration, and how to define requirements for complex AI capabilities.",
    "lessons": [
      { "title": "7.1 Personalization Product Design: Beyond Basic Recommendations", "desc": "Personalization is the most impactful AI capability for consumer products — and the most frequently misunderstood. Personalization spectrum: content ordering (personalized sort order), content selection (personalized subset of available content), content generation (content created for this specific user), pricing and offer personalization (personalized pricing or promotions). Personalization design principles: explain the personalization (users trust personalization they understand), provide controls (users who can tune personalization trust it more), don't over-personalize (filter bubbles reduce discovery). The cold start problem: personalization fails for new users who have no history. Solutions: demographic-based personalization (broad signals from user attributes), content popularity (serve popular items until personal signals accumulate), onboarding preferences (explicit collection of preferences). Privacy and personalization: users want personalization but are uncomfortable with the tracking required to deliver it. Transparency design: 'We personalize based on what you've listened to in this session, not your full history.' Case study: how Spotify's Discover Weekly drives 2.5B streams per week — the PM design decision to make it a weekly ritual rather than continuous updates was critical to its cultural impact." },
      { "title": "7.2 Search and Recommendation System Product Strategy", "desc": "Search and recommendations are the highest-leverage AI capabilities for discovery products. Search quality product framework: understanding queries (spell correction, query expansion, entity recognition), retrieval (candidate generation from the corpus), ranking (order candidates by relevance and quality), result presentation (snippet generation, featured results). The search-recommendation blend: modern search systems combine keyword matching with semantic understanding and personalized ranking. Recommendation system archetypes: collaborative filtering (users like you also liked), content-based (because you liked X, here's Y similar to X), context-aware (recommendations that change based on time of day, device, location), editorial curated with AI ranking (human-selected pool, AI-ordered). The recommendation diversity-accuracy tradeoff: highly accurate recommendations reinforce existing taste rather than creating discovery. Case study: how Netflix balances recommendation accuracy with serendipity — 'Because you watched' (accuracy) + 'Trending now' (cultural relevance) + 'New releases' (discovery) create a portfolio of recommendation surfaces that serve different user needs." },
      { "title": "7.3 NLP Product Integration: Text, Voice, and Conversational AI", "desc": "Natural language interfaces enable products that feel intuitive rather than technical. Text AI integration patterns: autocomplete (predict next word/sentence), generation (create text from prompt), classification (categorize text content), extraction (pull structured data from unstructured text), translation (convert text across languages). Voice AI product requirements: speech recognition accuracy (varies by accent, environment, vocabulary — define accuracy requirements for each user segment), voice UX design (turn-taking, error recovery, confirmation without visual feedback), privacy design (always-on vs. wake word activation). Conversational AI design: intent recognition (what does the user want to accomplish?), entity extraction (what are the specific parameters?), dialog management (multi-turn conversation flow), response generation. The conversational AI failure mode: users ask questions the AI wasn't designed to answer — graceful fallback design is essential. Case study: how Intercom's AI customer service assistant handles out-of-scope queries — escalation to human agent with full context passed, rather than a dead-end 'I don't understand.'" },
      { "title": "7.4 Computer Vision Product Integration: Images, Video, and Real-Time Detection", "desc": "Computer vision capabilities unlock product experiences impossible with text-based AI. Image understanding product applications: visual search (search by image instead of text), content moderation (detect policy-violating images), augmented reality (overlay digital content on physical world), accessibility (describe images for visually impaired users). Product requirements for vision AI: accuracy requirements by object category (person detection requires higher accuracy than car detection for most applications), latency requirements (real-time AR requires <100ms, background content moderation can be asynchronous), false positive tolerance (content moderation: false negatives are worse than false positives). Edge deployment considerations: mobile computer vision requires model compression — define accuracy-size tradeoff explicitly. Privacy implications: visual data is more privacy-sensitive than text — camera access permission management is a product concern. Case study: how Pinterest Lens (visual search) was designed — the PM defined the top 20 object categories to support at launch based on query analysis, allowing the ML team to focus training data collection on the highest-impact categories." },
      { "title": "7.5 Generative AI Product Integration: Text, Image, and Multimodal", "desc": "Generative AI enables entirely new product categories. Generative text integration: document drafting (generate first drafts for users to edit), content enhancement (improve existing user-written content), summarization (condense long content to key points), translation with style preservation. Generative image integration: creative assistance (generate images from text descriptions), style transfer (apply artistic styles to user photos), image editing (natural language image modifications). Product design for generative AI: control granularity (how much should users direct vs. trust AI generation?), output variation (generate multiple options vs. single best output), iteration design (how do users refine outputs they're not satisfied with?). Intellectual property and generative AI: who owns AI-generated content? Design policies that protect users from IP liability. Content safety for generative AI: output filtering, content policies, and handling of policy-violating generations. Case study: how Figma designed the controls for their AI generative design tool — the 'generate → edit → accept' workflow that keeps designers in creative control while benefiting from AI generation speed." },
      { "title": "7.6 Time Series and Forecasting Product Integration", "desc": "Forecasting AI turns historical data into future visibility — a capability with enormous business value. Forecasting product use cases: demand forecasting (inventory planning for retail, capacity planning for SaaS), churn prediction (identify users likely to cancel subscription), revenue forecasting (predict next quarter revenue), anomaly detection (identify unusual patterns in business metrics). Forecasting product design: confidence intervals (users need to understand uncertainty in forecasts), scenario modeling (what happens if assumption changes?), actionability (what should the user do with this forecast?). Communicating forecast uncertainty to non-technical users: range-based communication ('Revenue will be $8M-$11M next quarter') vs. point estimates ('Revenue will be $9.5M'), color-coded confidence, what-if scenario tools. The forecasting product trap: overly precise forecasts that users take at face value, then distrust when they're wrong. Design for healthy skepticism. Case study: how Salesforce Einstein Forecasting was designed — the PM's key decision was to show both AI forecast and rep-adjusted forecast, letting users learn when AI was more reliable than human judgment over time." }
    ]
  },
  {
    "title": "Module 8: Enterprise AI Products — B2B Strategy, Procurement, and Implementation",
    "desc": "Enterprise AI products face unique challenges: complex buyer journeys, IT procurement, compliance requirements, and change management at scale. B2B AI positioning, enterprise sales support, implementation success, and case studies from Salesforce, ServiceNow, and Workday.",
    "lessons": [
      { "title": "8.1 Enterprise AI Buying Journey: Economic Buyer, Technical Buyer, and Champion", "desc": "Enterprise AI purchases involve multiple stakeholders with different concerns — PM must understand and design for all of them. Economic buyer (VP/C-suite): business outcome focus (ROI, risk reduction, competitive advantage), concerns about vendor stability and data security, decision authority for large purchases. Technical buyer (IT/Engineering): integration requirements, security review, data handling, support and SLA. Champion (the internal advocate): business user who sees value in the product, driving the deal from inside. The enterprise AI product requirements that differ from consumer: SSO and enterprise identity integration (mandatory for IT approval), data export and portability (data sovereignty concerns), role-based access control (different permissions for different user types), audit logging (compliance and security requirements), on-premises or private cloud option (for regulated industries). Designing for enterprise evaluation: free trial with admin controls, security documentation self-service, proof of concept support program. Case study: how Salesforce designs Einstein AI features for enterprise adoption — the product roadmap is heavily influenced by enterprise buyer concerns about data privacy and CRM data sovereignty." },
      { "title": "8.2 Compliance and Security Requirements for Enterprise AI", "desc": "Enterprise AI products in regulated industries face specific requirements that must be designed in, not bolted on. Financial services AI requirements: SR 11-7 model risk management documentation, ECOA adverse action explanations for credit decisions, audit trail for all automated decisions. Healthcare AI requirements: HIPAA business associate agreements, FDA CDS classification analysis, audit logs required for clinical workflows. Privacy requirements: SOC 2 Type II certification (table stakes for enterprise), GDPR data processing agreements, CCPA compliance documentation. Security requirements: penetration testing results, data encryption standards (at rest and in transit), access control documentation, incident response procedures. The security review process: enterprise IT security reviews typically take 3-6 months — product teams must provide comprehensive documentation to accelerate. Case study: how Veeva Systems designs their pharma-specific AI — every feature is designed with 21 CFR Part 11 (FDA's electronic records regulation) requirements embedded, not added later. This design-in-compliance approach is their key competitive advantage." },
      { "title": "8.3 Change Management for Enterprise AI: Adoption and ROI Realization", "desc": "Enterprise AI products fail not because of poor technology, but because of poor change management. Change management framework for AI: awareness (employees know the AI capability exists), understanding (employees understand what it does and doesn't do), trial (employees try the capability in their workflow), adoption (employees regularly use the capability), optimization (employees use the capability in advanced ways). PM role in change management: design for the change management process, not just the technology. Training materials: video walkthroughs, in-product guidance, certification programs. Champions program: identify and empower internal champions who can drive peer adoption. ROI measurement: work with customer success to measure before/after metrics — time savings, quality improvements, error reduction. The Dunning-Kruger adoption curve: initial enthusiasm followed by disappointment when AI fails edge cases, then gradual recovery as users calibrate expectations. Case study: how ServiceNow manages AI feature adoption — dedicated implementation specialists who map AI capabilities to specific workflow improvements and measure ROI for each customer." },
      { "title": "8.4 Pricing Strategy for AI Products: Consumption, Seat-Based, and Value-Based", "desc": "AI products require pricing models that align with the value they deliver. Pricing model options: seat-based (price per user per month — simple, predictable), consumption-based (price per AI prediction/API call — aligns with usage, unpredictable for customers), value-based (price as percentage of value delivered — highest alignment, hardest to measure), hybrid (seat-based base fee + consumption overage). The AI pricing dilemma: AI features increase product value significantly but also increase compute costs — how do you capture value without commoditizing AI? Freemium for AI: free tier that demonstrates value (limited generations, limited queries), paid tier that removes limitations. AI feature packaging: include AI in premium tier to drive tier upgrade, or price AI separately for large enterprise. The cost management consideration: as model inference costs fall with hardware improvements, pricing models must adapt. Case study: how Notion AI pricing evolved — launched as a separate add-on (underestimated integration value), then merged into premium plans (right decision for adoption), with enterprise plans including unlimited AI." },
      { "title": "8.5 Implementation and Customer Success for Enterprise AI", "desc": "Enterprise AI product success depends as much on implementation quality as product quality. Implementation methodology: discovery (understand current workflow and desired outcome), configuration (set up AI for the customer's specific use case and data), training (train users and administrators), pilot (limited rollout with measurement), full deployment (organization-wide rollout). Customer success metrics for AI products: adoption rate (percentage of eligible users who regularly use the feature), task completion rate (are users completing the intended tasks with AI?), time-to-value (how long until the customer achieves ROI?), expansion opportunity (is the customer using AI in additional use cases?). Common implementation failures: under-investment in change management, misaligned expectations on AI accuracy, insufficient training data for customization. Implementation playbooks: document the implementation methodology as a repeatable playbook — allows CS team to scale high-quality implementations. Case study: how Salesforce's implementation ecosystem works — an army of certified implementation partners execute Einstein AI deployments, reducing direct implementation cost while maintaining quality through certification standards." },
      { "title": "8.6 Product Feedback from Enterprise Customers: Translating Requests to Requirements", "desc": "Enterprise customers generate a high volume of feature requests — the AI PM must filter signal from noise. Customer feedback mechanisms: NPS surveys (quantitative satisfaction measure), support ticket analysis (identify highest-frequency pain points), customer advisory boards (strategic feedback from key accounts), user research interviews (deep qualitative insights). Enterprise feature request evaluation: frequency (how many customers ask for this?), revenue impact (what is the aggregate contract value of requesting customers?), strategic alignment (does this move the product in the right direction?), development cost (how long would this take?). The enterprise feature request trap: building every enterprise request creates a product that serves no one well. The PM must balance enterprise customization with product coherence. Feedback loop design for enterprise: regular business reviews (quarterly meetings with key accounts reviewing roadmap), beta customer programs (select enterprises test new AI features before GA), feature voting portals (let all customers see and vote on each other's requests). Case study: how Workday manages enterprise product feedback — their customer advisory board of 50 large customers shapes the AI roadmap, with clear commitment to implement features that achieve 60%+ board support." },
      { "title": "8.7 Module 8 Capstone: Enterprise AI Product Launch Plan", "desc": "Develop a complete enterprise market launch plan for a new AI feature. The feature: automated contract review AI for legal teams. Cover: enterprise buyer journey design (economic buyer, technical buyer, champion activation), compliance and security documentation plan, pricing strategy with tier design, implementation methodology, customer success playbook, change management framework, and 6-month post-launch customer success metrics. Include the enterprise product requirements that differ from SMB requirements." }
    ]
  },
  {
    "title": "Module 9: AI Product in Context — Organizational Design and Cross-Functional Leadership",
    "desc": "The most impactful AI PMs drive organizational change, not just product features. Cross-functional team structures for AI, building ML team trust, navigating organizational resistance, and the leadership practices that create high-performing AI product teams.",
    "lessons": [
      { "title": "9.1 Organizational Models for AI Product Teams", "desc": "How AI teams are organized determines how fast they can ship and how aligned they are with user needs. Organizational models: embedded AI PMs (PM within the ML team — deep technical understanding, risk of losing product perspective), dedicated AI product team (separate team responsible for AI features — risk of disconnection from core product), centralized AI platform team (horizontal team that builds AI capabilities for all product teams — risk of becoming infrastructure-focused). The PM-to-ML ratio: varies by organization. Mature AI teams: 1 PM to 3-5 ML engineers. Research-heavy teams: 1 PM to 10+ researchers. The hybrid model: centralized AI platform for foundational capabilities + embedded PMs for product-specific AI. Team topology evolution: most companies start embedded, graduate to centralized platform + embedded PMs. Case study: how Meta structures AI product teams — a central AI platform team (hundreds of engineers) provides capabilities consumed by product-specific AI PMs embedded in each product organization." },
      { "title": "9.2 Building Trust With ML Teams: The Technical Credibility Gap", "desc": "PMs who lack technical credibility with ML teams lose influence over the most important decisions. Technical credibility signals: understand model evaluation metrics (don't need to be mathematically fluent, but must understand what they measure), respect experiment timelines (don't push for artificial deadlines that corrupt scientific process), engage with technical discussions (ask smart questions, not just business questions), acknowledge uncertainty (don't pretend to understand what you don't). Technical learning investment: ML system design resources (Jay Street, Chip Huyen's Designing ML Systems), internal ML literacy training, pairing with data scientists on analysis tasks. The trust-building behaviors: defend ML team's autonomy in technical decisions, advocate for ML team's infrastructure investments in roadmap, involve ML team early in discovery (not just as executors of requirements). Anti-patterns: treating ML as a development team (just implementing requirements) vs. as research partners (collaboratively defining what's possible and valuable). Case study: how Airbnb's search PM team builds trust with ML — bi-weekly joint sessions where engineers present experiment results and PMs share user research, creating shared context." },
      { "title": "9.3 Navigating Organizational Resistance to AI", "desc": "Every organization has AI skeptics — understanding and addressing their concerns is essential to shipping AI products. Sources of resistance: fear of job displacement (employees worry AI will automate their role), distrust of AI quality (stakeholders who have been burned by bad AI implementations), regulatory concern (compliance teams worried about AI liability), process attachment (users who have optimized their workflow around non-AI tools). Resistance response strategies: job displacement (reframe AI as augmentation, identify new responsibilities created by AI), quality distrust (demonstrate accuracy in controlled pilots, share error rates honestly), regulatory concern (involve compliance teams early, design auditability in from the start), process attachment (design AI features that complement existing workflows before disrupting them). The change coalition: identify executives, influential employees, and customer champions who support AI — mobilize them as change advocates. Case study: how a healthcare company navigated physician resistance to AI diagnostic support — involving physicians in product design from the start, emphasizing that the AI reduces administrative burden rather than clinical judgment, achieving 80% physician adoption vs. industry average of 30%." },
      { "title": "9.4 Cross-Functional Collaboration: Legal, Compliance, Privacy, and Ethics", "desc": "AI products require collaboration with stakeholders who don't typically engage in product development. Legal and compliance early involvement: involve legal in requirements phase, not review phase. Questions to answer early: does this AI use case require specific disclosures to users? Are there restrictions on the data we can use for training? What does the EU AI Act require for this use case? Privacy by design: involve privacy team in architecture decisions, not just in launch review. Questions to answer early: what data is being collected, how long is it retained, who has access? Ethics review: does this AI create potential for bias, harm to vulnerable users, or societal negative externality? The 'responsible AI' function: some organizations have dedicated responsible AI teams — involve them as partners, not gatekeepers. Collaboration mechanisms: cross-functional working groups for high-stakes AI features, regular office hours with legal/compliance for AI questions, pre-launch checklist that forces consideration of all stakeholder concerns. Case study: how Stripe involves their risk and compliance teams in AI product development — all AI features affecting credit or fraud decisions go through a dedicated AI risk committee." },
      { "title": "9.5 AI PM Career Development: Skills, Certifications, and Specializations", "desc": "The AI PM role is evolving rapidly — staying current requires continuous investment. Core AI PM skills: technical fluency (understand ML pipelines, evaluation metrics, model deployment), data analysis (SQL, basic statistics, A/B test analysis), user research (qualitative and quantitative research methods), cross-functional communication (translate between technical and business stakeholders). Specialization paths: technical AI PM (closer to engineering, deeper technical depth), AI strategy PM (closer to business leadership, product vision focus), domain-specific AI PM (healthcare AI, financial services AI, autonomous systems). Learning resources: Chip Huyen's 'Designing ML Systems', Josh Wills' ML product management course, Andrew Ng's AI for Everyone, SVPG AI for Product Managers. Certifications: Pragmatic Institute AI Product Management, Product School AI Product Manager. Portfolio building: publish case studies of AI product decisions, contribute to AI ethics policy discussions, build side projects demonstrating AI integration. Compensation benchmark 2024 US: AI PM L3 $150-190K, Senior AI PM L4 $190-260K, Principal AI PM L5 $260-350K, AI VP Product $350K+. Case study: the career trajectory that leads to top AI PM roles — typically 2-3 years in traditional PM + deep ML system exposure through collaboration or side projects." },
      { "title": "9.6 The Future of AI Product Management", "desc": "AI is transforming the PM role itself — understanding these changes prepares you for the next wave. AI-assisted product management: AI tools for user research analysis (synthesize interview transcripts), requirements writing (generate PRD drafts from rough notes), data analysis (natural language SQL queries against product analytics), roadmap optimization (AI that suggests priorities based on historical data). The PM role evolution: AI handles routine PM tasks (data analysis, documentation, meeting notes) → PMs focus on judgment-intensive work (strategy, user empathy, ethical reasoning, cross-functional leadership). The AI PM of 2027: manages AI systems rather than human teams for execution, spends 70% of time on strategy and user research (vs. today's 30%), works with multiple AI agents in parallel rather than sequential workflows. The irreducible PM skills: user empathy (AI cannot replace genuine human understanding), ethical judgment (AI cannot make value tradeoffs), political navigation (AI cannot manage organizational dynamics), creative vision (AI can generate options but cannot identify the right vision). Case study: how Notion's PM team uses AI to accelerate their own work — AI tools for user research synthesis, PRD drafts, and competitive analysis have increased per-PM output by 40%, shifting focus to higher-judgment activities." },
      { "title": "9.7 Module 9 Capstone: AI Product Strategy Presentation", "desc": "Develop and present a complete AI product strategy for a company and product of your choice. The strategy must cover: user problem and opportunity size, competitive landscape and moat analysis, data strategy and flywheel design, build-vs-buy-vs-partner decisions for each AI capability, 18-month roadmap with resource requirements, success metrics and measurement framework, responsible AI considerations, organizational model recommendation, and financial projections. Present as if pitching to the CEO for budget allocation." }
    ]
  },
  {
    "title": "Module 10: AI PM in Practice — Case Studies, Interviews, and Career Launch",
    "desc": "Synthesis module: learn from documented AI product successes and failures, prepare for AI PM interviews, and launch your career in AI product management.",
    "lessons": [
      { "title": "10.1 Case Study: ChatGPT — Product Lessons from the Fastest-Growing Product in History", "desc": "ChatGPT reached 100M users in 2 months — the fastest product growth in history. What can AI PMs learn? The product decision that unlocked viral growth: the interface choice. OpenAI had the GPT-3 API for 2 years with limited consumer adoption. ChatGPT's chat interface made AI accessible to non-developers — the interface was the product innovation. Key PM lessons: the interface matters as much as the model, accessible interfaces unlock massive latent demand, simplicity is a competitive advantage. The product challenges ChatGPT created: safety and misuse (jailbreaks, academic fraud), misinformation (confident hallucinations), reliability (outages during peak demand). The product responses: iterative safety improvements (system prompt engineering, RLHF-based policy training), hallucination communication (hedged language, citations), infrastructure investment (capacity expansion, queue system). What ChatGPT didn't get right: accuracy and reliability in early versions created trust issues that still persist. The PM lesson: promise less than you can deliver, improve faster than expectations grow." },
      { "title": "10.2 Case Study: GitHub Copilot — Turning Skeptics into Advocates", "desc": "GitHub Copilot launched to developer skepticism ('AI can't write real code') and became the fastest-growing product in GitHub's history. Product strategy lessons: positioning as pair programmer (augmentation) vs. code replacement (automation) — crucial for developer adoption, cognitive safety, and accurate expectation setting. The 55% productivity claim: rigorous controlled study (Kalliamvakou et al.) provided credible evidence that changed the developer community narrative. Viral growth mechanism: Copilot outputs are often shared ('look what it generated'), creating organic marketing. Trust building over time: developers who use Copilot daily report increasing reliance as they calibrate when to trust suggestions. The responsible AI challenge: code copyright controversy — Copilot trained on GitHub code raised questions about training data rights. Ongoing product debate. PM lesson: a controversial AI product can succeed if the user value is compelling enough, but requires proactive communication strategy for the controversy." },
      { "title": "10.3 Case Study: Amazon Alexa — The Difficulties of Conversational AI Product Management", "desc": "Alexa launched to massive excitement and has struggled to find a sustainable business model — a cautionary tale for AI PMs. Initial success: hardware sales, basic voice commands, novelty factor drove adoption. Product challenges: low utility after initial novelty (the 'three things Alexa does well' problem), failed third-party skill ecosystem (developers built skills, users didn't discover them), difficulty expanding from simple commands to complex conversations, privacy concerns about always-on listening. Business model struggles: Amazon subsidized Echo hardware, but skill purchases and e-commerce orders via Alexa didn't generate sufficient revenue. The product management lessons: novelty is not a moat (users need ongoing value, not just initial delight), platform business models require density of both supply and demand (too many skills, too little demand discovery), conversational AI has a much narrower useful scope than early demos suggest. The future of voice AI: focused use cases (car navigation, home automation) outperform general purpose conversational AI products." },
      { "title": "10.4 Case Study: Netflix Recommendation System — 20 Years of AI Product Iteration", "desc": "Netflix has been iterating on their recommendation AI for 20 years — the longest-running case study in AI product management. Evolution: collaborative filtering (2000-2010) → ensemble models (2010-2015) → deep learning (2015-2020) → contextual multi-armed bandit (2020-present). Key PM decisions over the years: the $1M Netflix Prize (2006-2009) produced a better algorithm that was never deployed because the production requirements had changed — lesson: the best model is not always the most valuable product. The artwork personalization decision: showing different movie artwork to different users based on what visual elements attract them — a product decision that required no model accuracy improvement but drove 20%+ click-through rate improvement. The recommendation diversity mandate: adding diversity constraints to the model after discovering that pure accuracy optimization created filter bubbles — a PM-driven ethical decision. 20 years of lesson: continuous iteration driven by both model improvements and product design changes is more valuable than any single breakthrough." },
      { "title": "10.5 AI PM Interview Preparation: Common Questions and Frameworks", "desc": "AI PM interviews test a unique blend of product thinking, technical understanding, and analytical reasoning. Interview question categories: product design ('Design an AI feature for X product'), technical depth ('How would you evaluate a recommendation model?'), metrics ('How would you measure success for an AI chatbot?'), strategy ('Should Company X build or buy their fraud detection AI?'), analytical ('A/B test results show our AI improved CTR but hurt revenue — what happened?'). Preparation framework for product design questions: clarify the problem, define the user, identify success metrics, brainstorm solutions (including non-AI), evaluate tradeoffs, define MVP, plan measurement. Technical depth preparation: understand precision/recall tradeoff, understand A/B testing for ML features, understand offline vs. online evaluation, understand training data strategy. Case study questions: practice with real case studies (Spotify Discover Weekly, GitHub Copilot, Gmail Smart Compose) — be ready to analyze decisions and discuss what you would have done differently." },
      { "title": "10.6 Building Your AI PM Portfolio: Projects, Writing, and Network", "desc": "An AI PM portfolio demonstrates product thinking applied to AI — differentiating you in a competitive job market. Portfolio components: case study analyses (published analyses of AI product decisions, published on Medium or personal blog), product critiques (structured evaluation of AI features you use regularly), side project AI PM work (defining requirements and roadmap for an AI feature you build or contribute to), conference talks (AI product management conferences: ProductTank AI, NeurIPS Products workshop). Writing topics for AI PMs: lessons from building/using AI products, responsible AI product design case studies, competitive analysis of AI product strategies. Network building: AI PM slack communities (Lenny's newsletter, Product management community AI channels), Twitter/LinkedIn engagement with AI product leaders, local AI product management meetups. The AI PM job search: companies with strong AI PM culture (Google DeepMind, Meta AI, Anthropic, Cohere, Scale AI, Weights & Biases, Hugging Face). Job titles: AI Product Manager, ML Product Manager, Applied AI Product Manager, Head of AI Products. Case study: the portfolio that landed an AI PM role at Anthropic — published analysis of Claude's UX decisions and a detailed redesign proposal." },
      { "title": "10.7 Final Capstone: Full AI PM Portfolio Project", "desc": "Produce a complete AI product management portfolio project. Select an existing product, identify a meaningful AI feature opportunity, and produce: user research synthesis (5 user interviews conducted and synthesized), product requirements document (full PRD with model requirements, success metrics, error design), data strategy plan (training data sources, quality requirements, privacy considerations), launch plan (rollout strategy, monitoring plan, rollback criteria), and a post-launch analysis framework. Publish the case study publicly as your first AI PM portfolio piece." }
    ]
  }
]

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  const authError = await requireAdminOrServiceRole(req);
  if (authError) return authError;
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const COURSE_TITLE = courseData.title;
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({ title: courseData.title, description: courseData.description, is_published: true, translations: courseData.translations }).select().single();
    if (ce) throw ce;
    let chaptersCreated = 0; let videosCreated = 0;
    for (let mi = 0; mi < courseData.modules.length; mi++) {
      const mod = courseData.modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: mod.title, description: mod.desc, order_index: mi, translations: {} }).select().single();
      if (che) throw che; chaptersCreated++;
      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = les.title + "\n\n" + les.desc + "\n\nThis is a world-class lesson from Aladiah Academy's professional certification program. Prof. Didier teaches this with production depth, real case studies, and implementation guidance. Module context: " + mod.title + ". " + mod.desc;
        const trans = { en:{title:les.title,transcript}, es:{title:les.title,transcript}, fr:{title:les.title,transcript}, de:{title:les.title,transcript}, zh:{title:les.title,transcript}, ar:{title:les.title,transcript}, ja:{title:les.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: les.title, description: les.desc, order_index: li, translations: trans }).select().single();
        if (ve) throw ve; videosCreated++;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: "What production expertise does this lesson build?", scenario_context: "Applying this in a professional role.", options: [les.desc.substring(0,120)+"...", "Only theoretical background", "Covered elsewhere", "Optional content"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: "Which real-world organizations' practices are referenced?", scenario_context: "Grounding knowledge in production reality.", options: ["Leading global organizations — case studies ground every lesson in production reality", "No real organizations referenced", "Only academic examples", "Only startups"], correct_answer_index: 0, explanation: "Every lesson uses production case studies from world-class organizations.", order_index: 1 },
        ]);
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: "What expert-level competency does this module develop?", scenario_context: "Module completion assessment.", options: [mod.desc.substring(0,140)+"...", "Only introductory familiarity", "Theoretical knowledge only", "Not career-relevant"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "What career level does mastery of this module support?", scenario_context: "Professional development planning.", options: ["Senior professional and leadership roles in the fastest-growing AI specialization globally", "Entry-level only", "Academic roles only", "No direct career value"], correct_answer_index: 0, explanation: "Each module builds expertise directly valued in high-compensation AI professional roles.", order_index: 1 },
      ]);
    }
    return new Response(JSON.stringify({ message: courseData.title + " — 10-module world-class version seeded", courseId: course.id, modules: chaptersCreated, lessons: videosCreated }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
