// =============================================================================
// AI Scrum Master Professional Certification — redesigned 18-module blueprint.
// Course Completion → Career Transformation. Each module includes lesson content,
// an AI mentor, a tool-based lab, an enterprise simulation, a portfolio artifact,
// three quiz tiers, and a competency assessment. Lab tools and portfolio artifacts
// rotate across the required tool/evidence set.
// =============================================================================
import { ModuleBlueprint } from '@/types/curriculum';

const ALL_TIERS: ModuleBlueprint['quizTiers'] = ['practice', 'adaptive', 'final'];

export const SCRUM_18_BLUEPRINT: ModuleBlueprint[] = [
  { no: 1, title: 'Agile & Scrum Foundations (AI-Augmented)', competencies: ['scrum:framework', 'scrum:empiricism'], aiMentorFocus: 'AI explains concepts and adapts examples to your background', lab: { tool: 'Confluence', task: 'Draft a team charter and Agile primer' }, simulation: { company: 'Global fintech adopting Scrum', scenario: 'A waterfall org pilots Scrum; you set the foundation' }, portfolioArtifact: 'Team Charter', quizTiers: ALL_TIERS, careerOutcome: 'Foundational fluency for interviews' },
  { no: 2, title: 'The Scrum Master Role & Servant Leadership', competencies: ['scrum:roles', 'scrum:team-dynamics'], aiMentorFocus: 'AI role-plays coaching conversations', lab: { tool: 'Miro', task: 'Map the Scrum Master role canvas' }, simulation: { company: 'Healthcare SaaS scale-up', scenario: 'Earn a new team’s trust in week one' }, portfolioArtifact: 'Scrum Master Role Canvas', quizTiers: ALL_TIERS, careerOutcome: 'Role clarity for behavioral interviews' },
  { no: 3, title: 'Scrum Team Accountabilities', competencies: ['scrum:roles'], aiMentorFocus: 'AI quizzes you on accountability boundaries', lab: { tool: 'Confluence', task: 'Build an accountabilities / RACI map' }, simulation: { company: 'E-commerce platform', scenario: 'PO, SM, and Developers clash over responsibilities' }, portfolioArtifact: 'Accountabilities Map', quizTiers: ALL_TIERS, careerOutcome: 'Clear articulation of team roles' },
  { no: 4, title: 'The Sprint & Sprint Planning', competencies: ['scrum:events'], aiMentorFocus: 'AI forecasts a realistic sprint and flags risks', lab: { tool: 'Jira', task: 'Set up a sprint and plan capacity' }, simulation: { company: 'Logistics enterprise', scenario: 'Plan a sprint under aggressive deadline pressure' }, portfolioArtifact: 'Sprint Plan', quizTiers: ALL_TIERS, careerOutcome: 'Demonstrable planning capability' },
  { no: 5, title: 'Daily Scrum & Sprint Execution', competencies: ['scrum:events', 'scrum:team-dynamics'], aiMentorFocus: 'AI summarizes standups and surfaces blockers', lab: { tool: 'Jira', task: 'Run a sprint board and manage flow' }, simulation: { company: 'Telecom', scenario: 'Rescue a failing sprint mid-cycle' }, portfolioArtifact: 'Impediment Log', quizTiers: ALL_TIERS, careerOutcome: 'Execution under pressure' },
  { no: 6, title: 'Sprint Review & Retrospective', competencies: ['scrum:events', 'scrum:empiricism'], aiMentorFocus: 'AI synthesizes retro themes into experiments', lab: { tool: 'Miro', task: 'Facilitate a retrospective board' }, simulation: { company: 'Media company', scenario: 'Run a high-stakes stakeholder review' }, portfolioArtifact: 'Retrospective + Action Items', quizTiers: ALL_TIERS, careerOutcome: 'Continuous-improvement evidence' },
  { no: 7, title: 'Scrum Artifacts & Commitments', competencies: ['scrum:artifacts'], aiMentorFocus: 'AI checks artifact transparency', lab: { tool: 'Jira', task: 'Structure Product & Sprint Backlogs' }, simulation: { company: 'Bank', scenario: 'Improve transparency across distributed teams' }, portfolioArtifact: 'Product + Sprint Backlog', quizTiers: ALL_TIERS, careerOutcome: 'Artifact mastery' },
  { no: 8, title: 'Definition of Done & Quality', competencies: ['scrum:artifacts', 'scrum:delivery-metrics'], aiMentorFocus: 'AI reviews your Definition of Done', lab: { tool: 'Azure DevOps', task: 'Define DoD with a CI/CD quality gate' }, simulation: { company: 'Insurtech', scenario: 'Stakeholder pressure: scope vs. Definition of Done' }, portfolioArtifact: 'Definition of Done', quizTiers: ALL_TIERS, careerOutcome: 'Quality leadership' },
  { no: 9, title: 'Product Backlog Management & Refinement', competencies: ['scrum:artifacts', 'scrum:stakeholders'], aiMentorFocus: 'AI drafts and splits user stories', lab: { tool: 'Jira', task: 'Run backlog refinement + story mapping' }, simulation: { company: 'Retail chain', scenario: 'Refine a messy backlog with a demanding PO' }, portfolioArtifact: 'Refined Backlog + Story Map', quizTiers: ALL_TIERS, careerOutcome: 'Backlog craftsmanship' },
  { no: 10, title: 'Empiricism, Transparency & Scrum Values', competencies: ['scrum:empiricism'], aiMentorFocus: 'AI surfaces transparency gaps', lab: { tool: 'Confluence', task: 'Build transparency radiators' }, simulation: { company: 'Gov digital service', scenario: 'Navigate a Scrum-values conflict' }, portfolioArtifact: 'Team Working Agreement', quizTiers: ALL_TIERS, careerOutcome: 'Values-based leadership' },
  { no: 11, title: 'Facilitation Mastery', competencies: ['scrum:team-dynamics', 'scrum:events'], aiMentorFocus: 'AI critiques your facilitation language', lab: { tool: 'Miro', task: 'Design facilitation techniques for each event' }, simulation: { company: 'Consultancy', scenario: 'Facilitate a contentious cross-team session' }, portfolioArtifact: 'Facilitation Playbook', quizTiers: ALL_TIERS, careerOutcome: 'Facilitation as a hireable skill' },
  { no: 12, title: 'Coaching & Team Dynamics', competencies: ['scrum:team-dynamics'], aiMentorFocus: 'AI coach simulates difficult team members', lab: { tool: 'AI tools', task: 'Practice coaching dialogues with an AI role-player' }, simulation: { company: 'Manufacturing', scenario: 'Coach a low-trust, low-performing team' }, portfolioArtifact: 'Team Coaching Plan', quizTiers: ALL_TIERS, careerOutcome: 'Coaching evidence for senior roles' },
  { no: 13, title: 'Stakeholder Engagement & Communication', competencies: ['scrum:stakeholders'], aiMentorFocus: 'AI drafts tailored stakeholder updates', lab: { tool: 'Confluence', task: 'Build a stakeholder communications plan' }, simulation: { company: 'Energy enterprise', scenario: 'Manage conflicting senior stakeholders' }, portfolioArtifact: 'Stakeholder Engagement Plan', quizTiers: ALL_TIERS, careerOutcome: 'Executive communication' },
  { no: 14, title: 'Organizational Change & Removing Impediments', competencies: ['scrum:stakeholders', 'scrum:team-dynamics'], aiMentorFocus: 'AI maps systemic impediments', lab: { tool: 'Miro', task: 'Map organizational impediments + change plan' }, simulation: { company: 'Airline', scenario: 'Drive change through organizational resistance' }, portfolioArtifact: 'Risk Register + Change Plan', quizTiers: ALL_TIERS, careerOutcome: 'Change leadership' },
  { no: 15, title: 'Agile Metrics, Flow & Forecasting', competencies: ['scrum:delivery-metrics'], aiMentorFocus: 'AI analyzes flow and forecasts delivery', lab: { tool: 'Azure DevOps', task: 'Build flow metrics + forecast' }, simulation: { company: 'SaaS unicorn', scenario: 'Resist metric misuse as performance targets' }, portfolioArtifact: 'Agile Metrics Dashboard', quizTiers: ALL_TIERS, careerOutcome: 'Data-driven delivery' },
  { no: 16, title: 'Scaling Scrum & Enterprise Agility', competencies: ['scrum:delivery-metrics', 'scrum:stakeholders'], aiMentorFocus: 'AI models cross-team dependencies', lab: { tool: 'Jira', task: 'Coordinate multi-team delivery' }, simulation: { company: 'Global tech (Spotify-style squads)', scenario: 'Scale with heavy cross-team dependencies' }, portfolioArtifact: 'Scaling Roadmap', quizTiers: ALL_TIERS, careerOutcome: 'Enterprise-readiness' },
  { no: 17, title: 'AI for the Scrum Master', competencies: ['scrum:framework', 'scrum:delivery-metrics'], aiMentorFocus: 'Master AI workflows end to end', lab: { tool: 'GitHub', task: 'Assemble an AI Scrum Master toolkit (prompts + automations)' }, simulation: { company: 'AI-first startup', scenario: 'Deliver with an AI-augmented team' }, portfolioArtifact: 'AI Workflow Toolkit', quizTiers: ALL_TIERS, careerOutcome: 'AI-augmented differentiation' },
  { no: 18, title: 'Capstone: Career Transformation & Placement', competencies: ['scrum:team-dynamics', 'scrum:stakeholders', 'scrum:delivery-metrics'], aiMentorFocus: 'AI runs full mock interviews + portfolio review', lab: { tool: 'GitHub', task: 'Assemble the Aladiah Profile + portfolio' }, simulation: { company: 'Multi-stakeholder enterprise', scenario: '3-Sprint leadership turnaround capstone' }, portfolioArtifact: 'Capstone Case Study + Aladiah Profile', quizTiers: ALL_TIERS, careerOutcome: 'Employment + placement readiness' },
];

export const SCRUM_18_TITLE = 'AI Scrum Master Professional Certification (18-module redesign)';
