// =============================================================================
// AI-Augmented Business Analyst & Product Intelligence Specialist — 10-module
// blueprint, built to the Aladiah Program Standard (same shape as blueprint18.ts).
// Promotes the prior seeded BA course to a standard program: every module carries
// an AI mentor, a tool-based lab, an enterprise simulation, a portfolio artifact,
// three quiz tiers, explicit AI skills, and a future-of-work angle. Competency
// slugs come from COMPETENCY_TAXONOMY.md §2A (program key `ba`).
// =============================================================================
import { ModuleBlueprint } from '@/types/curriculum';

const ALL_TIERS: ModuleBlueprint['quizTiers'] = ['practice', 'adaptive', 'final'];

export const BA_10_BLUEPRINT: ModuleBlueprint[] = [
  { no: 1, title: 'Business Analysis in the AI Era — The Evolved BA Role', competencies: ['ba:foundations'], aiMentorFocus: 'AI explains the evolved BA role and adapts examples to your domain', lab: { tool: 'Confluence', task: 'Document the AI requirements lifecycle and the BA-as-AI-translator operating model' }, simulation: { company: 'Global retailer launching AI personalization', scenario: 'Stakeholders expect deterministic specs for a probabilistic model; align them' }, portfolioArtifact: 'AI BA Operating Model + Requirements Lifecycle Map', quizTiers: ALL_TIERS, careerOutcome: 'Frame the AI-era BA role in interviews', aiSkills: ['Use AI to translate business goals into probabilistic AI requirements', 'Prompt AI to map an AI requirements lifecycle for a use case', 'Draft an AI-adoption stakeholder brief with AI'], futureOfWork: 'How the BA shifts from deterministic requirements gathering to AI-adoption champion and probabilistic-requirements translator.' },
  { no: 2, title: 'Requirements Engineering for AI Systems', competencies: ['ba:requirements'], aiMentorFocus: 'AI drafts functional + non-functional AI requirements and acceptance criteria', lab: { tool: 'Jira', task: 'Write an AI requirements spec with accuracy, latency, fairness and explainability NFRs' }, simulation: { company: 'Healthcare AI vendor', scenario: 'A clinical model must hit F1, latency and fairness bars under regulatory scrutiny' }, portfolioArtifact: 'AI System Requirements Specification', quizTiers: ALL_TIERS, careerOutcome: 'Demonstrable AI requirements rigor', aiSkills: ['Write AI acceptance criteria (F1, latency SLOs, fairness) with AI help', 'Use AI to generate non-functional requirements for an ML feature', 'Have AI stress-test requirements for ambiguity and uncertainty'], futureOfWork: 'Why requirements become probabilistic and outcome-based, and how the BA specifies accuracy, fairness and explainability rather than fixed behavior.' },
  { no: 3, title: 'SQL and Python for Business Analysts', competencies: ['ba:data-analysis'], aiMentorFocus: 'AI tutors SQL/Python and explains query and EDA results', lab: { tool: 'SQL + Python (Jupyter)', task: 'Run SQL joins/CTEs and a pandas EDA to validate a requirement with data' }, simulation: { company: 'Fintech analytics team', scenario: 'Validate a fraud-model requirement against messy production data under deadline' }, portfolioArtifact: 'Data Analysis Notebook + Requirement-Validation Report', quizTiers: ALL_TIERS, careerOutcome: 'Hands-on data fluency employers test for', aiSkills: ['Generate and debug SQL (joins, window functions, CTEs) with AI', 'Use AI to write pandas EDA and interpret distributions', 'Apply AI to spot sampling bias and correlation-vs-causation traps'], futureOfWork: 'As AI writes first-draft SQL and analysis, the BA’s edge becomes framing the right questions and validating AI-generated data work.' },
  { no: 4, title: 'Process Modeling and AI Opportunity Mapping', competencies: ['ba:process-modeling'], aiMentorFocus: 'AI suggests AS-IS/TO-BE redesigns and flags AI opportunities', lab: { tool: 'Lucidchart (BPMN)', task: 'Model AS-IS and TO-BE processes and build a prioritized AI opportunity map' }, simulation: { company: 'Insurance carrier', scenario: 'Map 150 claims processes and prioritize AI opportunities against ROI and risk' }, portfolioArtifact: 'BPMN AS-IS/TO-BE + AI Opportunity Map', quizTiers: ALL_TIERS, careerOutcome: 'Process + opportunity framing for AI initiatives', aiSkills: ['Use AI to draft BPMN AS-IS/TO-BE from process interviews', 'Run AI-assisted Monte Carlo on process outcomes', 'Identify and rank AI opportunities in a process with AI'], futureOfWork: 'The BA evolves from documenting processes to designing AI-augmented processes and discovering where AI creates measurable value.' },
  { no: 5, title: 'Stakeholder Analysis and AI Communication', competencies: ['ba:stakeholders'], aiMentorFocus: 'AI tailors AI explanations for executives, data scientists, users and regulators', lab: { tool: 'Miro', task: 'Build an AI stakeholder map + communication matrix and a RACI for AI decisions' }, simulation: { company: 'Bank AI program', scenario: 'Executives, data science and compliance disagree on a model’s go/no-go' }, portfolioArtifact: 'Stakeholder Map + AI Communication Plan', quizTiers: ALL_TIERS, careerOutcome: 'Translate AI across audiences', aiSkills: ['Use AI to tailor one AI decision for four stakeholder audiences', 'Generate a RACI for AI decisions with AI', 'Draft an AI governance briefing for non-technical leaders with AI'], futureOfWork: 'The BA becomes the AI translator and governance partner, brokering trust between business, data science, users and regulators.' },
  { no: 6, title: 'Data Governance and Quality Requirements for AI', competencies: ['ba:data-governance'], aiMentorFocus: 'AI links data-quality dimensions to model performance and drafts governance rules', lab: { tool: 'Confluence + SQL', task: 'Author a data quality + lineage spec (DAMA-DMBOK) tied to model performance' }, simulation: { company: 'Telco AI platform', scenario: 'Class imbalance and null rates silently degrade a churn model in production' }, portfolioArtifact: 'Data Quality + Governance Requirements Spec', quizTiers: ALL_TIERS, careerOutcome: 'Govern the data AI depends on', aiSkills: ['Use AI to map data-quality dimensions to model-performance risk', 'Generate a data dictionary and lineage doc with AI', 'Draft data governance rules for an AI use case with AI'], futureOfWork: 'As models become commodities, governed high-quality data becomes the moat — and specifying it becomes a core BA responsibility.' },
  { no: 7, title: 'AI System Testing and Acceptance', competencies: ['ba:testing-acceptance'], aiMentorFocus: 'AI drafts test plans, bias tests and edge-case catalogs for AI features', lab: { tool: 'GitHub + AI tools', task: 'Build an AI acceptance test plan with bias, adversarial and monitoring criteria' }, simulation: { company: 'Hiring-platform AI', scenario: 'A model passes accuracy but fails a fairness audit days before launch' }, portfolioArtifact: 'AI Acceptance Test Plan + Bias Test Protocol', quizTiers: ALL_TIERS, careerOutcome: 'Define “done” for AI features', aiSkills: ['Generate an AI test plan (unit, integration, UAT) with AI', 'Design bias and adversarial test cases using AI', 'Specify monitoring-based acceptance criteria with AI'], futureOfWork: 'The BA redefines “done”: not when accuracy is hit, but when bias is tested and live monitoring is in place — continuous, not one-time.' },
  { no: 8, title: 'Agile Business Analysis for AI Teams', competencies: ['ba:agile-delivery'], aiMentorFocus: 'AI helps run ML sprints and manage requirement uncertainty', lab: { tool: 'Jira', task: 'Run an ML-sprint backlog (research/experiment/deployment) with uncertainty-aware stories' }, simulation: { company: 'AI product scale-up', scenario: 'Requirements keep changing as the model changes mid-sprint' }, portfolioArtifact: 'ML Sprint Backlog + Uncertainty Plan', quizTiers: ALL_TIERS, careerOutcome: 'Operate inside AI delivery teams', aiSkills: ['Use AI to structure research/experiment/deployment ML sprints', 'Estimate uncertain ML work with AI assistance', 'Draft BA–data-scientist collaboration agreements with AI'], futureOfWork: 'The BA works as an embedded partner in cross-functional AI teams where discovery is experimental and requirements evolve with the model.' },
  { no: 9, title: 'BI and Analytics Requirements for AI Monitoring', competencies: ['ba:analytics-monitoring'], aiMentorFocus: 'AI specs monitoring dashboards and KPIs for AI systems', lab: { tool: 'Power BI', task: 'Specify and prototype an AI monitoring dashboard (drift, fairness, value KPIs)' }, simulation: { company: 'E-commerce AI ops', scenario: 'Leadership can’t see model drift until revenue drops — design the monitoring' }, portfolioArtifact: 'AI Monitoring Dashboard Spec + KPI Set', quizTiers: ALL_TIERS, careerOutcome: 'Make AI observable to the business', aiSkills: ['Use AI to define drift, fairness and value KPIs for a model', 'Draft Power BI / Tableau dashboard requirements with AI', 'Generate alerting thresholds for AI monitoring with AI'], futureOfWork: 'Monitoring becomes a first-class requirement; the BA keeps AI systems observable, governed and value-accountable after launch.' },
  { no: 10, title: 'BA Leadership and Capstone Project', competencies: ['ba:foundations', 'ba:requirements', 'ba:stakeholders'], aiMentorFocus: 'AI runs mock BA interviews and reviews the capstone deliverable set', lab: { tool: 'GitHub', task: 'Assemble the full AI-BA capstone portfolio + Aladiah Profile' }, simulation: { company: 'Enterprise AI transformation', scenario: 'Lead AI requirements workshops across business units to a board-ready recommendation' }, portfolioArtifact: 'Capstone: End-to-End AI Requirements Package + Aladiah Profile', quizTiers: ALL_TIERS, careerOutcome: 'Placement-ready AI Business Analyst', aiSkills: ['Run AI mock interviews and act on AI scoring', 'Use AI to review the capstone package for gaps', 'Generate an AI product-strategy narrative with AI'], futureOfWork: 'Positions the graduate as an AI-Augmented Business Analyst & Product Intelligence Specialist — from requirements gatherer to AI product strategist.' },
];

export const BA_10_TITLE = 'AI-Augmented Business Analyst & Product Intelligence Specialist (10-module program)';
export const BA_PROGRAM_KEY = 'ba';
