// =============================================================================
// AI Scrum Master Professional Certification — redesigned 18-module blueprint.
// Course Completion → Career Transformation. Each module includes lesson content,
// an AI mentor, a tool-based lab, an enterprise simulation, a portfolio artifact,
// three quiz tiers, a competency assessment, explicit AI skills, and a
// future-of-work angle. Lab tools and portfolio artifacts rotate across the
// required tool/evidence set. AI-readiness is scored by aiReadiness.ts.
// =============================================================================
import { ModuleBlueprint } from '@/types/curriculum';

const ALL_TIERS: ModuleBlueprint['quizTiers'] = ['practice', 'adaptive', 'final'];

export const SCRUM_18_BLUEPRINT: ModuleBlueprint[] = [
  { no: 1, title: 'Agile & Scrum Foundations (AI-Augmented)', competencies: ['scrum:framework', 'scrum:empiricism'], aiMentorFocus: 'AI explains concepts and adapts examples to your background', lab: { tool: 'Confluence', task: 'Draft a team charter and Agile primer' }, simulation: { company: 'Global fintech adopting Scrum', scenario: 'A waterfall org pilots Scrum; you set the foundation' }, portfolioArtifact: 'Team Charter', quizTiers: ALL_TIERS, careerOutcome: 'Foundational fluency for interviews', aiSkills: ['Set up an AI study co-pilot to explain Scrum concepts on demand', 'Prompt an AI to contrast Scrum vs. waterfall for a specific context', 'Draft a “why Scrum” narrative for a skeptical manager with AI'], futureOfWork: 'How AI co-pilots compress the Agile learning curve and shift the Scrum Master from process-teacher to outcome-coach.' },
  { no: 2, title: 'The Scrum Master Role & Servant Leadership', competencies: ['scrum:roles', 'scrum:team-dynamics'], aiMentorFocus: 'AI role-plays coaching conversations', lab: { tool: 'Miro', task: 'Map the Scrum Master role canvas' }, simulation: { company: 'Healthcare SaaS scale-up', scenario: 'Earn a new team’s trust in week one' }, portfolioArtifact: 'Scrum Master Role Canvas', quizTiers: ALL_TIERS, careerOutcome: 'Role clarity for behavioral interviews', aiSkills: ['Use an AI role-player to rehearse servant-leadership conversations', 'Get AI feedback that flags directive vs. facilitative language', 'Generate a personalized stop-doing / start-doing plan with AI'], futureOfWork: 'As AI absorbs status and admin work, the Scrum Master’s durable core becomes coaching, trust, and team health.' },
  { no: 3, title: 'Scrum Team Accountabilities', competencies: ['scrum:roles'], aiMentorFocus: 'AI quizzes you on accountability boundaries', lab: { tool: 'Confluence', task: 'Build an accountabilities / RACI map' }, simulation: { company: 'E-commerce platform', scenario: 'PO, SM, and Developers clash over responsibilities' }, portfolioArtifact: 'Accountabilities Map', quizTiers: ALL_TIERS, careerOutcome: 'Clear articulation of team roles', aiSkills: ['Generate a RACI for ambiguous accountability scenarios with AI', 'Use AI to detect role anti-patterns in a meeting transcript', 'Draft accountability-boundary explanations tailored per stakeholder'], futureOfWork: 'As AI absorbs coordination overhead, human accountability clarity becomes the differentiator the Scrum Master curates.' },
  { no: 4, title: 'The Sprint & Sprint Planning', competencies: ['scrum:events'], aiMentorFocus: 'AI forecasts a realistic sprint and flags risks', lab: { tool: 'Jira', task: 'Set up a sprint and plan capacity' }, simulation: { company: 'Logistics enterprise', scenario: 'Plan a sprint under aggressive deadline pressure' }, portfolioArtifact: 'Sprint Plan', quizTiers: ALL_TIERS, careerOutcome: 'Demonstrable planning capability', aiSkills: ['Forecast a realistic sprint from historical velocity using AI', 'Have AI stress-test a Sprint Goal and surface over-commitment risk', 'Generate planning-facilitation prompts and capacity scenarios with AI'], futureOfWork: 'AI-assisted forecasting moves planning from gut-feel to probability; the Scrum Master stewards AI forecasts instead of manual estimates.' },
  { no: 5, title: 'Daily Scrum & Sprint Execution', competencies: ['scrum:events', 'scrum:team-dynamics'], aiMentorFocus: 'AI summarizes standups and surfaces blockers', lab: { tool: 'Jira', task: 'Run a sprint board and manage flow' }, simulation: { company: 'Telecom', scenario: 'Rescue a failing sprint mid-cycle' }, portfolioArtifact: 'Impediment Log', quizTiers: ALL_TIERS, careerOutcome: 'Execution under pressure', aiSkills: ['Summarize standups and auto-extract blockers with AI', 'Classify and prioritize impediments using an AI assistant', 'Draft Scrum-grounded impediment-removal strategies with AI'], futureOfWork: 'AI standup synthesis and blocker detection shift the daily focus from collecting status to leading real-time flow.' },
  { no: 6, title: 'Sprint Review & Retrospective', competencies: ['scrum:events', 'scrum:empiricism'], aiMentorFocus: 'AI synthesizes retro themes into experiments', lab: { tool: 'Miro', task: 'Facilitate a retrospective board' }, simulation: { company: 'Media company', scenario: 'Run a high-stakes stakeholder review' }, portfolioArtifact: 'Retrospective + Action Items', quizTiers: ALL_TIERS, careerOutcome: 'Continuous-improvement evidence', aiSkills: ['Cluster retrospective inputs into themes and experiments with AI', 'Draft a value-tied Sprint Review narrative using AI', 'Recommend retro formats matched to team mood via AI'], futureOfWork: 'AI-driven retro analysis surfaces patterns humans miss; the Scrum Master evolves into an experiment designer acting on AI-clustered insight.' },
  { no: 7, title: 'Scrum Artifacts & Commitments', competencies: ['scrum:artifacts'], aiMentorFocus: 'AI checks artifact transparency', lab: { tool: 'Jira', task: 'Structure Product & Sprint Backlogs' }, simulation: { company: 'Bank', scenario: 'Improve transparency across distributed teams' }, portfolioArtifact: 'Product + Sprint Backlog', quizTiers: ALL_TIERS, careerOutcome: 'Artifact mastery', aiSkills: ['Use AI to audit backlog and artifact transparency', 'Draft a Product Goal from a raw vision with AI', 'Structure a backlog from unstructured ideas using AI'], futureOfWork: 'When AI maintains artifact hygiene automatically, the Scrum Master shifts to safeguarding commitment intent and empirical trust.' },
  { no: 8, title: 'Definition of Done & Quality', competencies: ['scrum:artifacts', 'scrum:delivery-metrics'], aiMentorFocus: 'AI reviews your Definition of Done', lab: { tool: 'Azure DevOps', task: 'Define DoD with a CI/CD quality gate' }, simulation: { company: 'Insurtech', scenario: 'Stakeholder pressure: scope vs. Definition of Done' }, portfolioArtifact: 'Definition of Done', quizTiers: ALL_TIERS, careerOutcome: 'Quality leadership', aiSkills: ['Have AI review a Definition of Done for gaps', 'Generate CI/CD quality-gate suggestions with AI', 'Role-play scope-vs-DoD pressure with an AI stakeholder'], futureOfWork: 'AI-enabled quality gates and test generation raise the bar; the Scrum Master defends “done” where AI output still needs human review.' },
  { no: 9, title: 'Product Backlog Management & Refinement', competencies: ['scrum:artifacts', 'scrum:stakeholders'], aiMentorFocus: 'AI drafts and splits user stories', lab: { tool: 'Jira', task: 'Run backlog refinement + story mapping' }, simulation: { company: 'Retail chain', scenario: 'Refine a messy backlog with a demanding PO' }, portfolioArtifact: 'Refined Backlog + Story Map', quizTiers: ALL_TIERS, careerOutcome: 'Backlog craftsmanship', aiSkills: ['Draft and split user stories with AI', 'Auto-generate acceptance criteria and edge cases using AI', 'Flag dependencies and risks across a backlog with AI'], futureOfWork: 'AI story-splitting and criteria generation speed refinement; the future Scrum Master curates AI drafts and protects outcome-over-output thinking.' },
  { no: 10, title: 'Empiricism, Transparency & Scrum Values', competencies: ['scrum:empiricism'], aiMentorFocus: 'AI surfaces transparency gaps', lab: { tool: 'Confluence', task: 'Build transparency radiators' }, simulation: { company: 'Gov digital service', scenario: 'Navigate a Scrum-values conflict' }, portfolioArtifact: 'Team Working Agreement', quizTiers: ALL_TIERS, careerOutcome: 'Values-based leadership', aiSkills: ['Use AI to surface transparency gaps in reporting', 'Generate a Scrum-values self-assessment with AI', 'Rehearse a values-conflict conversation with an AI coach'], futureOfWork: 'As AI makes real status radically transparent, empiricism strengthens and the Scrum Master’s role centers on trust and safety AI cannot manufacture.' },
  { no: 11, title: 'Facilitation Mastery', competencies: ['scrum:team-dynamics', 'scrum:events'], aiMentorFocus: 'AI critiques your facilitation language', lab: { tool: 'Miro', task: 'Design facilitation techniques for each event' }, simulation: { company: 'Consultancy', scenario: 'Facilitate a contentious cross-team session' }, portfolioArtifact: 'Facilitation Playbook', quizTiers: ALL_TIERS, careerOutcome: 'Facilitation as a hireable skill', aiSkills: ['Get AI critique of facilitation language and neutrality', 'Design an event session plan with AI', 'Rehearse difficult-participant scenarios with an AI role-player'], futureOfWork: 'AI can plan and document sessions, but facilitating live human dynamics becomes the higher-value, harder-to-automate Scrum Master craft.' },
  { no: 12, title: 'Coaching & Team Dynamics', competencies: ['scrum:team-dynamics'], aiMentorFocus: 'AI coach simulates difficult team members', lab: { tool: 'AI tools', task: 'Practice coaching dialogues with an AI role-player' }, simulation: { company: 'Manufacturing', scenario: 'Coach a low-trust, low-performing team' }, portfolioArtifact: 'Team Coaching Plan', quizTiers: ALL_TIERS, careerOutcome: 'Coaching evidence for senior roles', aiSkills: ['Practice coaching dialogues with an AI role-player', 'Get AI feedback scoring your coaching questions', 'Build a coaching plan for a struggling team with AI'], futureOfWork: 'AI role-players let Scrum Masters rehearse hard conversations at scale; coaching judgment and team trust remain the irreplaceable human edge.' },
  { no: 13, title: 'Stakeholder Engagement & Communication', competencies: ['scrum:stakeholders'], aiMentorFocus: 'AI drafts tailored stakeholder updates', lab: { tool: 'Confluence', task: 'Build a stakeholder communications plan' }, simulation: { company: 'Energy enterprise', scenario: 'Manage conflicting senior stakeholders' }, portfolioArtifact: 'Stakeholder Engagement Plan', quizTiers: ALL_TIERS, careerOutcome: 'Executive communication', aiSkills: ['Draft audience-tailored stakeholder updates with AI', 'Build a stakeholder map and engagement plan using AI', 'Rehearse a demanding-executive conversation with an AI role-player'], futureOfWork: 'AI drafts tailored communications instantly; the Scrum Master shifts to relationship strategy and executive trust AI messaging cannot earn.' },
  { no: 14, title: 'Organizational Change & Removing Impediments', competencies: ['scrum:stakeholders', 'scrum:team-dynamics'], aiMentorFocus: 'AI maps systemic impediments', lab: { tool: 'Miro', task: 'Map organizational impediments + change plan' }, simulation: { company: 'Airline', scenario: 'Drive change through organizational resistance' }, portfolioArtifact: 'Risk Register + Change Plan', quizTiers: ALL_TIERS, careerOutcome: 'Change leadership', aiSkills: ['Map systemic impediments with AI assistance', 'Draft an organizational change plan using AI', 'Role-play organizational resistance with an AI stakeholder'], futureOfWork: 'AI can model change and dependencies, but driving transformation through human resistance becomes the defining future agile-leadership skill.' },
  { no: 15, title: 'Agile Metrics, Flow & Forecasting', competencies: ['scrum:delivery-metrics'], aiMentorFocus: 'AI analyzes flow and forecasts delivery', lab: { tool: 'Azure DevOps', task: 'Build flow metrics + forecast' }, simulation: { company: 'SaaS unicorn', scenario: 'Resist metric misuse as performance targets' }, portfolioArtifact: 'Agile Metrics Dashboard', quizTiers: ALL_TIERS, careerOutcome: 'Data-driven delivery', aiSkills: ['Analyze flow and run probabilistic delivery forecasts with AI', 'Detect metric anti-patterns (Goodhart’s law) using AI', 'Build a leadership metrics narrative with AI'], futureOfWork: 'AI flow analytics and Monte-Carlo forecasting replace manual reporting; the Scrum Master becomes an interpreter who guards against weaponized metrics.' },
  { no: 16, title: 'Scaling Scrum & Enterprise Agility', competencies: ['scrum:delivery-metrics', 'scrum:stakeholders'], aiMentorFocus: 'AI models cross-team dependencies', lab: { tool: 'Jira', task: 'Coordinate multi-team delivery' }, simulation: { company: 'Global tech (Spotify-style squads)', scenario: 'Scale with heavy cross-team dependencies' }, portfolioArtifact: 'Scaling Roadmap', quizTiers: ALL_TIERS, careerOutcome: 'Enterprise-readiness', aiSkills: ['Model cross-team dependencies with AI', 'Draft a scaling roadmap using AI', 'Simulate a multi-team planning event with AI'], futureOfWork: 'AI dependency modeling makes scaling tractable; future enterprise-agility leaders orchestrate AI-surfaced insight across many teams.' },
  { no: 17, title: 'AI for the Scrum Master', competencies: ['scrum:framework', 'scrum:delivery-metrics'], aiMentorFocus: 'Master AI workflows end to end', lab: { tool: 'GitHub', task: 'Assemble an AI Scrum Master toolkit (prompts + automations)' }, simulation: { company: 'AI-first startup', scenario: 'Deliver with an AI-augmented team' }, portfolioArtifact: 'AI Workflow Toolkit', quizTiers: ALL_TIERS, careerOutcome: 'AI-augmented differentiation', aiSkills: ['Build an AI prompt library for facilitation, refinement, and metrics', 'Automate retro synthesis and flow-metric analysis with AI', 'Apply responsible-AI practices (bias, privacy, human judgment)'], futureOfWork: 'Defines the AI-augmented Scrum Master end to end: where AI augments delivery, where human judgment must stay, and how the role evolves rather than disappears.' },
  { no: 18, title: 'Capstone: Career Transformation & Placement', competencies: ['scrum:team-dynamics', 'scrum:stakeholders', 'scrum:delivery-metrics'], aiMentorFocus: 'AI runs full mock interviews + portfolio review', lab: { tool: 'GitHub', task: 'Assemble the Aladiah Profile + portfolio' }, simulation: { company: 'Multi-stakeholder enterprise', scenario: '3-Sprint leadership turnaround capstone' }, portfolioArtifact: 'Capstone Case Study + Aladiah Profile', quizTiers: ALL_TIERS, careerOutcome: 'Employment + placement readiness', aiSkills: ['Run full AI mock interviews and act on AI scoring', 'Use AI to review the portfolio for gaps and polish artifacts', 'Generate an Aladiah Profile narrative with AI'], futureOfWork: 'Positions the graduate as an AI Enterprise Scrum Master & Agile Transformation Leader, leading AI-augmented delivery and organizational change.' },
];

export const SCRUM_18_TITLE = 'AI Scrum Master Professional Certification (18-module redesign)';
