import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'zh' | 'ar' | 'fr' | 'de' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  zh: '中文',
  ar: 'العربية',
  fr: 'Français',
  de: 'Deutsch',
  ja: '日本語',
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.programs': 'Programs',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.enroll': 'Enroll Now',
    
    // Hero
    'hero.badge': 'AI-Powered Professional Training',
    'hero.title.line1': 'Master Agile Leadership',
    'hero.title.line2': 'With AI Innovation',
    'hero.subtitle': 'Transform your career with cutting-edge Scrum Master and Project Management training, enhanced by the latest AI tools. Join the future of professional development in the Dominican Republic.',
    'hero.cta.primary': 'Explore Programs',
    'hero.cta.secondary': 'Learn More',
    'hero.stats.students': 'Students Trained',
    'hero.stats.rate': 'Success Rate',
    'hero.stats.partners': 'Corporate Partners',
    'hero.scene1': 'María works long hours at a restaurant in Santo Domingo…',
    'hero.scene2': 'One night, she sees an ad on Instagram — Aladiah Academy. A chance to change everything.',
    'hero.scene3': 'She enrolls, studies late into the night, and earns her Scrum Master certification.',
    'hero.scene4': '6 months later — she leads a professional team, earning $60,000 a year.',
    'hero.scene5': 'She moves to a beautiful apartment. Her life is forever changed.',
    
    // Programs
    'programs.badge': 'Our Programs',
    'programs.title': 'World-Class Training Programs',
    'programs.subtitle': 'Comprehensive courses designed to elevate your professional skills and career prospects in agile project management.',
    'programs.scrum.title': 'Scrum Master Certification',
    'programs.scrum.desc': 'Become a certified Scrum Master with hands-on training, real-world projects, and AI-enhanced learning methodologies.',
    'programs.pm.title': 'Project Management Professional',
    'programs.pm.desc': 'Master project management frameworks with modern AI tools for planning, execution, and stakeholder management.',
    'programs.ai.title': 'AI Tools for Managers',
    'programs.ai.desc': 'Learn to leverage cutting-edge AI tools to enhance productivity, decision-making, and team collaboration.',
    'programs.duration': 'Duration',
    'programs.weeks': 'weeks',
    'programs.format': 'Format',
    'programs.hybrid': 'Hybrid',
    'programs.online': 'Online',
    'programs.learnMore': 'Learn More',
    'programs.startCourse': 'Start Course',
    'programs.comingSoon': 'Join Waitlist',
    'programs.liveProject.title': 'Live Scrum Project: 2-Week Sprint Simulation',
    'programs.liveProject.desc': 'Experience a realistic two-week sprint with all Scrum ceremonies in sequence — daily standups, sprint planning, backlog refinement, sprint review, and retrospective through interactive real-world scenarios.',
    'programs.liveProject.prereq': 'Requires completion of specific courses to unlock',
    'programs.liveProject.duration': '2-week sprint',
    'programs.rogersProject.title': 'IT Merger Project: Rogers-Shaw Network Integration',
    'programs.rogersProject.desc': 'Lead a real-world IT integration project inspired by the Rogers-Shaw $26B telecommunications merger. Manage 3 cross-domain Scrum teams over 4 sprints as they consolidate cable, wireless, and enterprise systems across Canada.',
    'programs.rogersProject.prereq': 'Requires completion of specific courses to unlock',
    'programs.rogersProject.duration': '2-month project (4 sprints)',
    'programs.rogersProject.teams': '3 Scrum Teams',
    
    // About
    'about.badge': 'About Us',
    'about.title': 'Founded on Excellence',
    'about.p1': 'Aladiah Academy was founded with a clear vision: to bridge the gap between traditional project management education and the rapidly evolving demands of the modern business world.',
    'about.p2': 'Led by our founder, a seasoned professional currently at Royal Caribbean International, we bring real-world expertise and industry connections to every program we offer.',
    'about.p3': 'Operating under Aladiah Management, we maintain the highest standards of professional training while embracing innovation and the transformative power of AI in education.',
    'about.founder': 'Founder & CEO',
    'about.company': 'Aladiah Management',
    
    // Founder
    'founder.bio.title': 'Visionary Leader in Agile & AI Education',
    'founder.bio.p1': 'Didier Boumtje is a seasoned IT executive and Agile transformation leader with over 10 years of experience driving large-scale technology initiatives across the cruise, hospitality, and enterprise sectors. Currently a Senior Project Manager at Royal Caribbean International, he orchestrates multi-million-dollar digital transformation programs spanning global operations.',
    'founder.bio.p2': 'Passionate about democratizing professional education, Didier founded Aladiah Academy to bring world-class Scrum Master and Project Management training to emerging markets — powered by cutting-edge AI tools that personalize the learning journey for every student.',
    'founder.credential1': 'Senior PM at Royal Caribbean International — leading cross-functional teams across 5 countries',
    'founder.credential2': 'Certified Scrum Master (CSM), PMP, and SAFe Agilist with 10+ years in enterprise IT',
    'founder.credential3': 'AI & Education innovator — pioneering AI-powered curriculum design for professional training',
    'founder.credential4': 'Multilingual leader fluent in 4 languages, building a global academy across 7 languages',
    'founder.quote': 'I believe in the power of "automate the automation" in a sophisticated way.',
    'founder.teaching.caption': 'Didier Boumtje delivering hands-on Scrum training to the next generation of Agile leaders',

    // Features
    'features.ai.title': 'AI-Enhanced Learning',
    'features.ai.desc': 'Cutting-edge AI tools integrated into our curriculum',
    'features.expert.title': 'Industry Experts',
    'features.expert.desc': 'Learn from professionals with real-world experience',
    'features.network.title': 'Professional Network',
    'features.network.desc': 'Connect with industry leaders and peers',
    
    // CTA
    'cta.title': 'Ready to Transform Your Career?',
    'cta.subtitle': 'Join hundreds of professionals who have advanced their careers through our programs. Start your journey today.',
    'cta.button': 'Get Started Now',
    
    // Footer
    'footer.description': 'Professional Training Institute for Scrum Masters and Project Managers, powered by AI innovation.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.location': 'Dominican Republic',
    'footer.rights': 'All rights reserved.',
    'footer.company': 'A division of Aladiah Management',

    // Blog
    'blog.badge': 'Industry Insights',
    'blog.title': 'The Rise of Scrum in the Dominican Republic',
    'blog.subtitle': 'Why Agile methodology is transforming careers and creating unprecedented demand for certified professionals',
    'blog.intro': 'The Dominican Republic is emerging as a strategic hub for Agile transformation in the Americas. With its growing tech sector, bilingual workforce, and proximity to North American markets, the country is perfectly positioned to meet the surging global demand for Scrum Masters and Agile professionals.',
    'blog.section1.title': 'Global Scrum Adoption: The Numbers',
    'blog.section1.content': 'According to the 15th State of Agile Report, 66% of organizations worldwide now use Scrum as their primary Agile framework. This dominance has created unprecedented demand for certified Scrum Masters, with the World Economic Forum projecting a 37.9% growth in Scrum-related roles over the next decade.',
    'blog.section2.title': 'Salary Trends Across Markets',
    'blog.section2.content': 'Scrum Master salaries reflect this high demand. In Australia, Senior Scrum Masters earn an average of A$156,000 annually. In the UK, salaries range from £55,000 to £95,000 depending on experience. The United States leads with averages of $115,000-$145,000 for experienced professionals.',
    'blog.section3.title': 'The Dominican Advantage',
    'blog.section3.content': 'The Dominican Republic offers unique advantages for Scrum professionals: a bilingual Spanish-English workforce perfectly suited for nearshoring, competitive costs for multinational corporations, and a rapidly growing IT sector. Major companies are increasingly looking to the Caribbean for Agile talent.',
    'blog.section4.title': 'Industries Driving Demand',
    'blog.section4.content': 'While Scrum originated in software development, today\'s demand spans multiple sectors: Financial Services, Healthcare, Manufacturing, Government, Marketing, and Consulting. Energy and Life Sciences sectors offer the highest entry-level salaries, often 20-30% above average.',
    'blog.section5.title': 'Career Growth Paths',
    'blog.section5.content': 'A Scrum Master certification opens multiple career trajectories: Agile Coach, Scrum Mentor, Agile Program Manager, or even Chief Agile Officer. Each path offers increasing responsibility and compensation, with Agile Coaches commanding salaries 40-60% higher than entry-level Scrum Masters.',
    'blog.section6.title': 'The Multilingual Edge',
    'blog.section6.content': 'In today\'s global economy, multilingual Scrum Masters are exceptionally valuable. Professionals who can facilitate ceremonies and coach teams in multiple languages—particularly English, Spanish, and Portuguese—are commanding premium salaries in international organizations.',
    'blog.cta': 'Explore Our Scrum Master Course',
    'blog.source': 'Sources: State of Agile Report, World Economic Forum, Glassdoor, The Knowledge Academy',
    'blog.stats.adoption': 'Agile Adoption Rate',
    'blog.stats.scrum': 'Use Scrum Framework',
    'blog.stats.growth': 'Projected Job Growth',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.programs': 'Programas',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.enroll': 'Inscríbete',
    
    // Hero
    'hero.badge': 'Formación Profesional con IA',
    'hero.title.line1': 'Domina el Liderazgo Ágil',
    'hero.title.line2': 'Con Innovación en IA',
    'hero.subtitle': 'Transforma tu carrera con formación de vanguardia en Scrum Master y Gestión de Proyectos, potenciada por las últimas herramientas de IA. Únete al futuro del desarrollo profesional en República Dominicana.',
    'hero.cta.primary': 'Explorar Programas',
    'hero.cta.secondary': 'Más Información',
    'hero.stats.students': 'Estudiantes Formados',
    'hero.stats.rate': 'Tasa de Éxito',
    'hero.stats.partners': 'Socios Corporativos',
    'hero.scene1': 'María trabaja largas horas en un restaurante en Santo Domingo…',
    'hero.scene2': 'Una noche, ve un anuncio en Instagram — Aladiah Academy. Una oportunidad para cambiarlo todo.',
    'hero.scene3': 'Se inscribe, estudia hasta altas horas de la noche y obtiene su certificación de Scrum Master.',
    'hero.scene4': '6 meses después — lidera un equipo profesional, ganando $60,000 al año.',
    'hero.scene5': 'Se muda a un hermoso apartamento. Su vida cambió para siempre.',
    
    // Programs
    'programs.badge': 'Nuestros Programas',
    'programs.title': 'Programas de Formación de Clase Mundial',
    'programs.subtitle': 'Cursos completos diseñados para elevar tus habilidades profesionales y perspectivas de carrera en gestión ágil de proyectos.',
    'programs.scrum.title': 'Certificación Scrum Master',
    'programs.scrum.desc': 'Conviértete en un Scrum Master certificado con formación práctica, proyectos reales y metodologías de aprendizaje mejoradas con IA.',
    'programs.pm.title': 'Profesional en Gestión de Proyectos',
    'programs.pm.desc': 'Domina los marcos de gestión de proyectos con herramientas modernas de IA para planificación, ejecución y gestión de stakeholders.',
    'programs.ai.title': 'Herramientas IA para Gestores',
    'programs.ai.desc': 'Aprende a aprovechar herramientas de IA de vanguardia para mejorar la productividad, toma de decisiones y colaboración en equipo.',
    'programs.duration': 'Duración',
    'programs.weeks': 'semanas',
    'programs.format': 'Formato',
    'programs.hybrid': 'Híbrido',
    'programs.online': 'En Línea',
    'programs.learnMore': 'Más Información',
    'programs.startCourse': 'Iniciar Curso',
    'programs.comingSoon': 'Únete a la Lista',
    'programs.liveProject.title': 'Proyecto Scrum en Vivo: Simulación de Sprint de 2 Semanas',
    'programs.liveProject.desc': 'Experimenta un sprint realista de dos semanas con todas las ceremonias Scrum en secuencia — standups diarios, planificación del sprint, refinamiento del backlog, revisión del sprint y retrospectiva.',
    'programs.liveProject.prereq': 'Requiere completar cursos específicos para desbloquear',
    'programs.liveProject.duration': 'Sprint de 2 semanas',
    'programs.rogersProject.title': 'Proyecto de Fusión IT: Integración de Red Rogers-Shaw',
    'programs.rogersProject.desc': 'Lidera un proyecto de integración IT del mundo real inspirado en la fusión de $26B de Rogers-Shaw. Gestiona 3 equipos Scrum durante 4 sprints consolidando sistemas de cable, inalámbricos y empresariales.',
    'programs.rogersProject.prereq': 'Requiere completar cursos específicos para desbloquear',
    'programs.rogersProject.duration': 'Proyecto de 2 meses (4 sprints)',
    'programs.rogersProject.teams': '3 Equipos Scrum',
    
    // About
    'about.badge': 'Sobre Nosotros',
    'about.title': 'Fundados en la Excelencia',
    'about.p1': 'Aladiah Academy fue fundada con una visión clara: cerrar la brecha entre la educación tradicional en gestión de proyectos y las demandas en rápida evolución del mundo empresarial moderno.',
    'about.p2': 'Liderada por nuestro fundador, un profesional experimentado actualmente en Royal Caribbean International, aportamos experiencia del mundo real y conexiones de la industria a cada programa que ofrecemos.',
    'about.p3': 'Operando bajo Aladiah Management, mantenemos los más altos estándares de formación profesional mientras abrazamos la innovación y el poder transformador de la IA en la educación.',
    'about.founder': 'Fundador y CEO',
    'about.company': 'Aladiah Management',
    
    // Founder
    'founder.bio.title': 'Líder Visionario en Educación Agile e IA',
    'founder.bio.p1': 'Didier Boumtje es un ejecutivo de TI experimentado y líder en transformación Agile con más de 10 años de experiencia impulsando iniciativas tecnológicas a gran escala en los sectores de cruceros, hospitalidad y empresarial. Actualmente Gerente Senior de Proyectos en Royal Caribbean International, orquesta programas de transformación digital multimillonarios a nivel global.',
    'founder.bio.p2': 'Apasionado por democratizar la educación profesional, Didier fundó Aladiah Academy para llevar formación de clase mundial en Scrum Master y Gestión de Proyectos a mercados emergentes — impulsada por herramientas de IA de vanguardia que personalizan el viaje de aprendizaje de cada estudiante.',
    'founder.credential1': 'PM Senior en Royal Caribbean International — lidera equipos multifuncionales en 5 países',
    'founder.credential2': 'Scrum Master Certificado (CSM), PMP y SAFe Agilist con 10+ años en TI empresarial',
    'founder.credential3': 'Innovador en IA y Educación — pionero en diseño curricular con IA para formación profesional',
    'founder.credential4': 'Líder multilingüe fluido en 4 idiomas, construyendo una academia global en 7 idiomas',
    'founder.quote': 'Creo en el poder de "automatizar la automatización" de manera sofisticada.',
    'founder.teaching.caption': 'Didier Boumtje impartiendo formación práctica en Scrum a la próxima generación de líderes Agile',

    // Features
    'features.ai.title': 'Aprendizaje con IA',
    'features.ai.desc': 'Herramientas de IA de vanguardia integradas en nuestro currículo',
    'features.expert.title': 'Expertos de la Industria',
    'features.expert.desc': 'Aprende de profesionales con experiencia real',
    'features.network.title': 'Red Profesional',
    'features.network.desc': 'Conecta con líderes de la industria y colegas',
    
    // CTA
    'cta.title': '¿Listo para Transformar tu Carrera?',
    'cta.subtitle': 'Únete a cientos de profesionales que han avanzado en sus carreras a través de nuestros programas. Comienza tu viaje hoy.',
    'cta.button': 'Comenzar Ahora',
    
    // Footer
    'footer.description': 'Instituto de Formación Profesional para Scrum Masters y Gestores de Proyectos, impulsado por innovación en IA.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.location': 'República Dominicana',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.company': 'Una división de Aladiah Management',

    // Blog
    'blog.badge': 'Perspectivas de la Industria',
    'blog.title': 'El Auge de Scrum en República Dominicana',
    'blog.subtitle': 'Por qué la metodología Agile está transformando carreras y creando una demanda sin precedentes de profesionales certificados',
    'blog.intro': 'República Dominicana está emergiendo como un centro estratégico para la transformación Agile en las Américas. Con su creciente sector tecnológico, fuerza laboral bilingüe y proximidad a los mercados norteamericanos, el país está perfectamente posicionado para satisfacer la creciente demanda global de Scrum Masters y profesionales Agile.',
    'blog.section1.title': 'Adopción Global de Scrum: Los Números',
    'blog.section1.content': 'Según el 15º Informe State of Agile, el 66% de las organizaciones en todo el mundo ahora usan Scrum como su marco Agile principal. Este dominio ha creado una demanda sin precedentes de Scrum Masters certificados, con el Foro Económico Mundial proyectando un crecimiento del 37.9% en roles relacionados con Scrum en la próxima década.',
    'blog.section2.title': 'Tendencias Salariales en los Mercados',
    'blog.section2.content': 'Los salarios de Scrum Master reflejan esta alta demanda. En Australia, los Senior Scrum Masters ganan un promedio de A$156,000 anuales. En el Reino Unido, los salarios varían de £55,000 a £95,000 según la experiencia. Estados Unidos lidera con promedios de $115,000-$145,000 para profesionales experimentados.',
    'blog.section3.title': 'La Ventaja Dominicana',
    'blog.section3.content': 'República Dominicana ofrece ventajas únicas para profesionales Scrum: una fuerza laboral bilingüe español-inglés perfectamente adaptada para nearshoring, costos competitivos para corporaciones multinacionales y un sector de TI en rápido crecimiento. Las grandes empresas buscan cada vez más talento Agile en el Caribe.',
    'blog.section4.title': 'Industrias que Impulsan la Demanda',
    'blog.section4.content': 'Si bien Scrum se originó en el desarrollo de software, la demanda actual abarca múltiples sectores: Servicios Financieros, Salud, Manufactura, Gobierno, Marketing y Consultoría. Los sectores de Energía y Ciencias de la Vida ofrecen los salarios de nivel de entrada más altos, a menudo 20-30% por encima del promedio.',
    'blog.section5.title': 'Trayectorias de Crecimiento Profesional',
    'blog.section5.content': 'Una certificación de Scrum Master abre múltiples trayectorias profesionales: Agile Coach, Mentor Scrum, Gerente de Programa Agile o incluso Chief Agile Officer. Cada camino ofrece mayor responsabilidad y compensación, con los Agile Coaches ganando salarios 40-60% más altos que los Scrum Masters de nivel inicial.',
    'blog.section6.title': 'La Ventaja Multilingüe',
    'blog.section6.content': 'En la economía global actual, los Scrum Masters multilingües son excepcionalmente valiosos. Los profesionales que pueden facilitar ceremonias y entrenar equipos en múltiples idiomas—particularmente inglés, español y portugués—están obteniendo salarios premium en organizaciones internacionales.',
    'blog.cta': 'Explora Nuestro Curso de Scrum Master',
    'blog.source': 'Fuentes: State of Agile Report, Foro Económico Mundial, Glassdoor, The Knowledge Academy',
    'blog.stats.adoption': 'Tasa de Adopción Agile',
    'blog.stats.scrum': 'Usan Framework Scrum',
    'blog.stats.growth': 'Crecimiento Proyectado',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.programs': '课程',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.enroll': '立即报名',
    
    // Hero
    'hero.badge': 'AI驱动的专业培训',
    'hero.title.line1': '掌握敏捷领导力',
    'hero.title.line2': '借助AI创新',
    'hero.subtitle': '通过最新AI工具增强的Scrum Master和项目管理培训，转变您的职业生涯。加入多米尼加共和国专业发展的未来。',
    'hero.cta.primary': '探索课程',
    'hero.cta.secondary': '了解更多',
    'hero.stats.students': '培训学员',
    'hero.stats.rate': '成功率',
    'hero.stats.partners': '企业合作伙伴',
    'hero.scene1': 'María在圣多明各的一家餐厅辛苦工作…',
    'hero.scene2': '一天晚上，她在Instagram上看到一则广告——Aladiah Academy。一个改变一切的机会。',
    'hero.scene3': '她报名了，深夜学习，并获得了Scrum Master认证。',
    'hero.scene4': '6个月后——她领导一个专业团队，年收入60,000美元。',
    'hero.scene5': '她搬进了一套漂亮的公寓。她的生活从此改变。',
    
    // Programs
    'programs.badge': '我们的课程',
    'programs.title': '世界级培训课程',
    'programs.subtitle': '全面的课程设计，提升您在敏捷项目管理方面的专业技能和职业前景。',
    'programs.scrum.title': 'Scrum Master认证',
    'programs.scrum.desc': '通过实践培训、真实项目和AI增强学习方法，成为认证的Scrum Master。',
    'programs.pm.title': '项目管理专业人士',
    'programs.pm.desc': '使用现代AI工具掌握项目管理框架，用于规划、执行和利益相关者管理。',
    'programs.ai.title': '管理者AI工具',
    'programs.ai.desc': '学习利用尖端AI工具来提高生产力、决策能力和团队协作。',
    'programs.duration': '时长',
    'programs.weeks': '周',
    'programs.format': '形式',
    'programs.hybrid': '混合式',
    'programs.online': '在线',
    'programs.learnMore': '了解更多',
    'programs.startCourse': '开始课程',
    'programs.comingSoon': '加入等候名单',
    'programs.liveProject.title': '实战Scrum项目：两周冲刺模拟',
    'programs.liveProject.desc': '体验一个真实的两周冲刺，按顺序完成所有Scrum仪式——每日站会、冲刺计划、待办精化、冲刺评审和回顾。',
    'programs.liveProject.prereq': '需要完成特定课程才能解锁',
    'programs.liveProject.duration': '两周冲刺',
    'programs.rogersProject.title': 'IT合并项目：Rogers-Shaw网络整合',
    'programs.rogersProject.desc': '领导一个以Rogers-Shaw 260亿美元电信合并为灵感的真实IT整合项目。在4个冲刺中管理3个跨领域Scrum团队，整合加拿大各地的有线、无线和企业系统。',
    'programs.rogersProject.prereq': '需要完成特定课程才能解锁',
    'programs.rogersProject.duration': '2个月项目（4个冲刺）',
    'programs.rogersProject.teams': '3个Scrum团队',
    
    // About
    'about.badge': '关于我们',
    'about.title': '卓越奠基',
    'about.p1': 'Aladiah Academy的成立有着明确的愿景：弥合传统项目管理教育与现代商业世界快速发展需求之间的差距。',
    'about.p2': '在我们创始人的领导下，这位目前在皇家加勒比国际公司工作的资深专业人士，我们为每个课程带来真实的专业知识和行业关系。',
    'about.p3': '在Aladiah Management旗下运营，我们保持最高的专业培训标准，同时拥抱创新和AI在教育中的变革力量。',
    'about.founder': '创始人兼CEO',
    'about.company': 'Aladiah Management',
    
    // Founder
    'founder.bio.title': '敏捷与AI教育的远见领导者',
    'founder.bio.p1': 'Didier Boumtje是一位经验丰富的IT高管和敏捷转型领导者，拥有超过10年推动邮轮、酒店和企业领域大规模技术计划的经验。目前担任皇家加勒比国际公司高级项目经理，他策划跨全球运营的数百万美元数字化转型项目。',
    'founder.bio.p2': 'Didier热衷于教育民主化，创立了Aladiah Academy，旨在将世界一流的Scrum Master和项目管理培训带到新兴市场——借助前沿AI工具为每位学员个性化学习旅程。',
    'founder.credential1': '皇家加勒比国际高级项目经理——在5个国家领导跨职能团队',
    'founder.credential2': '认证Scrum Master (CSM)、PMP和SAFe敏捷师，10年以上企业IT经验',
    'founder.credential3': 'AI与教育创新者——开创AI驱动的专业培训课程设计',
    'founder.credential4': '精通4种语言的多语言领导者，正在构建一所覆盖7种语言的全球学院',
    'founder.quote': '我相信以精密方式"自动化自动化"的力量。',
    'founder.teaching.caption': 'Didier Boumtje为下一代敏捷领导者提供实战Scrum培训',

    // Features
    'features.ai.title': 'AI增强学习',
    'features.ai.desc': '尖端AI工具融入我们的课程',
    'features.expert.title': '行业专家',
    'features.expert.desc': '向具有实战经验的专业人士学习',
    'features.network.title': '专业网络',
    'features.network.desc': '与行业领袖和同行建立联系',
    
    // CTA
    'cta.title': '准备好转变您的职业生涯了吗？',
    'cta.subtitle': '加入数百位通过我们的课程推进职业发展的专业人士。今天就开始您的旅程。',
    'cta.button': '立即开始',
    
    // Footer
    'footer.description': 'Scrum Master和项目经理专业培训机构，由AI创新驱动。',
    'footer.quickLinks': '快速链接',
    'footer.contact': '联系方式',
    'footer.location': '多米尼加共和国',
    'footer.rights': '版权所有。',
    'footer.company': 'Aladiah Management旗下',

    // Blog
    'blog.badge': '行业洞察',
    'blog.title': 'Scrum在多米尼加共和国的崛起',
    'blog.subtitle': '为什么敏捷方法论正在改变职业生涯并创造对认证专业人员的空前需求',
    'blog.intro': '多米尼加共和国正在成为美洲敏捷转型的战略中心。凭借其不断发展的科技行业、双语劳动力以及与北美市场的邻近优势，该国完美地定位于满足全球对Scrum Master和敏捷专业人员不断增长的需求。',
    'blog.section1.title': '全球Scrum采用：数据',
    'blog.section1.content': '根据第15届敏捷状态报告，全球66%的组织现在使用Scrum作为其主要敏捷框架。这种主导地位为认证Scrum Master创造了前所未有的需求，世界经济论坛预测未来十年Scrum相关职位将增长37.9%。',
    'blog.section2.title': '市场薪资趋势',
    'blog.section2.content': 'Scrum Master的薪资反映了这种高需求。在澳大利亚，高级Scrum Master的年均收入为156,000澳元。在英国，根据经验，薪资范围为55,000至95,000英镑。美国以115,000-145,000美元的经验丰富专业人员平均水平领先。',
    'blog.section3.title': '多米尼加优势',
    'blog.section3.content': '多米尼加共和国为Scrum专业人员提供独特优势：非常适合近岸外包的西班牙语-英语双语劳动力、对跨国公司具有竞争力的成本，以及快速发展的IT行业。主要公司越来越多地在加勒比地区寻找敏捷人才。',
    'blog.section4.title': '推动需求的行业',
    'blog.section4.content': '虽然Scrum起源于软件开发，但今天的需求跨越多个行业：金融服务、医疗保健、制造、政府、营销和咨询。能源和生命科学行业提供最高的入门级薪资，通常比平均水平高20-30%。',
    'blog.section5.title': '职业发展路径',
    'blog.section5.content': 'Scrum Master认证开启多种职业轨迹：敏捷教练、Scrum导师、敏捷项目经理，甚至首席敏捷官。每条路径都提供更多的责任和薪酬，敏捷教练的薪资比入门级Scrum Master高40-60%。',
    'blog.section6.title': '多语言优势',
    'blog.section6.content': '在当今的全球经济中，多语言Scrum Master极具价值。能够用多种语言（尤其是英语、西班牙语和葡萄牙语）主持仪式和指导团队的专业人员在国际组织中获得高薪。',
    'blog.cta': '探索我们的Scrum Master课程',
    'blog.source': '来源：敏捷状态报告、世界经济论坛、Glassdoor、The Knowledge Academy',
    'blog.stats.adoption': '敏捷采用率',
    'blog.stats.scrum': '使用Scrum框架',
    'blog.stats.growth': '预计增长',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.programs': 'البرامج',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.enroll': 'سجل الآن',
    
    // Hero
    'hero.badge': 'تدريب مهني مدعوم بالذكاء الاصطناعي',
    'hero.title.line1': 'أتقن القيادة الرشيقة',
    'hero.title.line2': 'مع ابتكار الذكاء الاصطناعي',
    'hero.subtitle': 'حوّل مسيرتك المهنية من خلال تدريب Scrum Master وإدارة المشاريع المتطور، المعزز بأحدث أدوات الذكاء الاصطناعي. انضم إلى مستقبل التطوير المهني في جمهورية الدومينيكان.',
    'hero.cta.primary': 'استكشف البرامج',
    'hero.cta.secondary': 'اعرف المزيد',
    'hero.stats.students': 'متدربون',
    'hero.stats.rate': 'معدل النجاح',
    'hero.stats.partners': 'شركاء مؤسسيون',
    'hero.scene1': 'ماريا تعمل ساعات طويلة في مطعم في سانتو دومينغو…',
    'hero.scene2': 'ذات ليلة، ترى إعلانًا على إنستغرام — أكاديمية علاديا. فرصة لتغيير كل شيء.',
    'hero.scene3': 'تسجل، تدرس حتى وقت متأخر من الليل، وتحصل على شهادة Scrum Master.',
    'hero.scene4': 'بعد 6 أشهر — تقود فريقًا محترفًا، وتكسب 60,000 دولار سنويًا.',
    'hero.scene5': 'تنتقل إلى شقة جميلة. حياتها تغيرت إلى الأبد.',
    
    // Programs
    'programs.badge': 'برامجنا',
    'programs.title': 'برامج تدريب عالمية المستوى',
    'programs.subtitle': 'دورات شاملة مصممة لرفع مهاراتك المهنية وآفاقك الوظيفية في إدارة المشاريع الرشيقة.',
    'programs.scrum.title': 'شهادة Scrum Master',
    'programs.scrum.desc': 'كن Scrum Master معتمدًا من خلال التدريب العملي والمشاريع الحقيقية ومنهجيات التعلم المعززة بالذكاء الاصطناعي.',
    'programs.pm.title': 'محترف إدارة المشاريع',
    'programs.pm.desc': 'أتقن أطر إدارة المشاريع باستخدام أدوات الذكاء الاصطناعي الحديثة للتخطيط والتنفيذ وإدارة أصحاب المصلحة.',
    'programs.ai.title': 'أدوات الذكاء الاصطناعي للمديرين',
    'programs.ai.desc': 'تعلم الاستفادة من أدوات الذكاء الاصطناعي المتطورة لتعزيز الإنتاجية واتخاذ القرارات والتعاون الجماعي.',
    'programs.duration': 'المدة',
    'programs.weeks': 'أسابيع',
    'programs.format': 'الشكل',
    'programs.hybrid': 'هجين',
    'programs.online': 'عبر الإنترنت',
    'programs.learnMore': 'اعرف المزيد',
    'programs.startCourse': 'ابدأ الدورة',
    'programs.comingSoon': 'انضم للقائمة',
    'programs.liveProject.title': 'مشروع سكرم مباشر: محاكاة سبرنت لمدة أسبوعين',
    'programs.liveProject.desc': 'عش تجربة سبرنت واقعية لمدة أسبوعين مع جميع احتفالات سكرم بالتسلسل — الاجتماعات اليومية وتخطيط السبرنت وتنقيح الباكلوج ومراجعة السبرنت والاسترجاع.',
    'programs.liveProject.prereq': 'يتطلب إكمال دورات محددة للفتح',
    'programs.liveProject.duration': 'سبرنت أسبوعين',
    'programs.rogersProject.title': 'مشروع دمج تقنية المعلومات: تكامل شبكة Rogers-Shaw',
    'programs.rogersProject.desc': 'قُد مشروع تكامل تقنية معلومات حقيقي مستوحى من اندماج Rogers-Shaw بقيمة 26 مليار دولار. أدِر 3 فرق سكرم عبر 4 سبرنتات لدمج أنظمة الكابل واللاسلكي والمؤسسات.',
    'programs.rogersProject.prereq': 'يتطلب إكمال دورات محددة للفتح',
    'programs.rogersProject.duration': 'مشروع شهرين (4 سبرنتات)',
    'programs.rogersProject.teams': '3 فرق سكرم',
    
    // About
    'about.badge': 'من نحن',
    'about.title': 'تأسست على التميز',
    'about.p1': 'تأسست أكاديمية علاديا برؤية واضحة: سد الفجوة بين تعليم إدارة المشاريع التقليدي والمتطلبات سريعة التطور لعالم الأعمال الحديث.',
    'about.p2': 'بقيادة مؤسسنا، المحترف المخضرم الذي يعمل حاليًا في Royal Caribbean International، نقدم خبرة حقيقية واتصالات صناعية لكل برنامج نقدمه.',
    'about.p3': 'نعمل تحت إدارة علاديا، ونحافظ على أعلى معايير التدريب المهني مع تبني الابتكار والقوة التحويلية للذكاء الاصطناعي في التعليم.',
    'about.founder': 'المؤسس والرئيس التنفيذي',
    'about.company': 'إدارة علاديا',
    
    // Founder
    'founder.bio.title': 'قائد صاحب رؤية في تعليم Agile والذكاء الاصطناعي',
    'founder.bio.p1': 'ديدييه بومتجي هو مدير تنفيذي متمرس في تقنية المعلومات وقائد في التحول الرشيق مع أكثر من 10 سنوات من الخبرة في قيادة مبادرات التكنولوجيا واسعة النطاق في قطاعات الرحلات البحرية والضيافة والمؤسسات. يعمل حاليًا كمدير مشاريع أول في Royal Caribbean International، وينظم برامج تحول رقمي بملايين الدولارات عبر العمليات العالمية.',
    'founder.bio.p2': 'شغوف بديمقراطية التعليم المهني، أسس ديدييه أكاديمية علاديا لتقديم تدريب عالمي المستوى في Scrum Master وإدارة المشاريع للأسواق الناشئة — مدعومة بأدوات ذكاء اصطناعي متطورة تخصص رحلة التعلم لكل طالب.',
    'founder.credential1': 'مدير مشاريع أول في Royal Caribbean International — يقود فرقًا متعددة الوظائف في 5 دول',
    'founder.credential2': 'Scrum Master معتمد (CSM)، PMP وSAFe Agilist مع أكثر من 10 سنوات في تقنية المعلومات المؤسسية',
    'founder.credential3': 'مبتكر في الذكاء الاصطناعي والتعليم — رائد في تصميم المناهج المدعومة بالذكاء الاصطناعي للتدريب المهني',
    'founder.credential4': 'قائد متعدد اللغات يتحدث 4 لغات بطلاقة، يبني أكاديمية عالمية بـ 7 لغات',
    'founder.quote': 'أؤمن بقوة "أتمتة الأتمتة" بطريقة متطورة.',
    'founder.teaching.caption': 'ديدييه بومتجي يقدم تدريب Scrum عملي للجيل القادم من قادة Agile',

    // Features
    'features.ai.title': 'تعلم معزز بالذكاء الاصطناعي',
    'features.ai.desc': 'أدوات ذكاء اصطناعي متطورة مدمجة في مناهجنا',
    'features.expert.title': 'خبراء الصناعة',
    'features.expert.desc': 'تعلم من محترفين ذوي خبرة حقيقية',
    'features.network.title': 'شبكة مهنية',
    'features.network.desc': 'تواصل مع قادة الصناعة والأقران',
    
    // CTA
    'cta.title': 'هل أنت مستعد لتحويل مسيرتك المهنية؟',
    'cta.subtitle': 'انضم إلى مئات المحترفين الذين تقدموا في حياتهم المهنية من خلال برامجنا. ابدأ رحلتك اليوم.',
    'cta.button': 'ابدأ الآن',
    
    // Footer
    'footer.description': 'معهد تدريب مهني لـ Scrum Masters ومديري المشاريع، مدعوم بابتكار الذكاء الاصطناعي.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.contact': 'اتصل بنا',
    'footer.location': 'جمهورية الدومينيكان',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.company': 'قسم من إدارة علاديا',

    // Blog
    'blog.badge': 'رؤى الصناعة',
    'blog.title': 'صعود Scrum في جمهورية الدومينيكان',
    'blog.subtitle': 'لماذا تحوّل منهجية Agile المسارات المهنية وتخلق طلبًا غير مسبوق على المحترفين المعتمدين',
    'blog.intro': 'تبرز جمهورية الدومينيكان كمركز استراتيجي للتحول الرشيق في الأمريكتين. مع قطاعها التقني المتنامي وقوتها العاملة ثنائية اللغة وقربها من الأسواق الأمريكية الشمالية، فإن البلاد في وضع مثالي لتلبية الطلب العالمي المتزايد على Scrum Masters ومحترفي Agile.',
    'blog.section1.title': 'اعتماد Scrum العالمي: الأرقام',
    'blog.section1.content': 'وفقًا للتقرير الخامس عشر لحالة Agile، يستخدم 66٪ من المنظمات حول العالم الآن Scrum كإطار عمل Agile الرئيسي. خلق هذه الهيمنة طلبًا غير مسبوق على Scrum Masters المعتمدين، مع توقع المنتدى الاقتصادي العالمي نموًا بنسبة 37.9٪ في الأدوار المرتبطة بـ Scrum خلال العقد القادم.',
    'blog.section2.title': 'اتجاهات الرواتب عبر الأسواق',
    'blog.section2.content': 'تعكس رواتب Scrum Master هذا الطلب المرتفع. في أستراليا، يكسب كبار Scrum Masters متوسط 156,000 دولار أسترالي سنويًا. في المملكة المتحدة، تتراوح الرواتب من 55,000 إلى 95,000 جنيه إسترليني حسب الخبرة. تتصدر الولايات المتحدة بمتوسطات 115,000-145,000 دولار للمحترفين ذوي الخبرة.',
    'blog.section3.title': 'الميزة الدومينيكانية',
    'blog.section3.content': 'تقدم جمهورية الدومينيكان مزايا فريدة لمحترفي Scrum: قوة عاملة ثنائية اللغة إسبانية-إنجليزية مثالية للنقل القريب، وتكاليف تنافسية للشركات متعددة الجنسيات، وقطاع تكنولوجيا المعلومات سريع النمو. تبحث الشركات الكبرى بشكل متزايد في منطقة البحر الكاريبي عن المواهب الرشيقة.',
    'blog.section4.title': 'الصناعات التي تدفع الطلب',
    'blog.section4.content': 'بينما نشأ Scrum في تطوير البرمجيات، يمتد الطلب اليوم عبر قطاعات متعددة: الخدمات المالية والرعاية الصحية والتصنيع والحكومة والتسويق والاستشارات. تقدم قطاعات الطاقة وعلوم الحياة أعلى رواتب مستوى الدخول، غالبًا 20-30٪ فوق المتوسط.',
    'blog.section5.title': 'مسارات النمو الوظيفي',
    'blog.section5.content': 'تفتح شهادة Scrum Master مسارات وظيفية متعددة: مدرب Agile، مرشد Scrum، مدير برنامج Agile، أو حتى كبير مسؤولي Agile. يوفر كل مسار مسؤولية وتعويضًا متزايدين، حيث يحصل مدربو Agile على رواتب أعلى بنسبة 40-60٪ من Scrum Masters المبتدئين.',
    'blog.section6.title': 'الميزة متعددة اللغات',
    'blog.section6.content': 'في الاقتصاد العالمي اليوم، يعد Scrum Masters متعددو اللغات ذوي قيمة استثنائية. المحترفون الذين يمكنهم تسهيل الاحتفالات وتدريب الفرق بلغات متعددة - خاصة الإنجليزية والإسبانية والبرتغالية - يحصلون على رواتب مميزة في المنظمات الدولية.',
    'blog.cta': 'استكشف دورة Scrum Master لدينا',
    'blog.source': 'المصادر: تقرير حالة Agile، المنتدى الاقتصادي العالمي، Glassdoor، The Knowledge Academy',
    'blog.stats.adoption': 'معدل اعتماد Agile',
    'blog.stats.scrum': 'يستخدمون إطار Scrum',
    'blog.stats.growth': 'النمو المتوقع',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.programs': 'Programmes',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.enroll': 'S\'inscrire',
    
    // Hero
    'hero.badge': 'Formation Professionnelle Alimentée par l\'IA',
    'hero.title.line1': 'Maîtrisez le Leadership Agile',
    'hero.title.line2': 'Avec l\'Innovation IA',
    'hero.subtitle': 'Transformez votre carrière avec une formation de pointe en Scrum Master et Gestion de Projet, enrichie par les derniers outils IA. Rejoignez l\'avenir du développement professionnel en République Dominicaine.',
    'hero.cta.primary': 'Explorer les Programmes',
    'hero.cta.secondary': 'En Savoir Plus',
    'hero.stats.students': 'Étudiants Formés',
    'hero.stats.rate': 'Taux de Réussite',
    'hero.stats.partners': 'Partenaires Corporatifs',
    'hero.scene1': 'María travaille de longues heures dans un restaurant à Saint-Domingue…',
    'hero.scene2': 'Un soir, elle voit une publicité sur Instagram — Aladiah Academy. Une chance de tout changer.',
    'hero.scene3': 'Elle s\'inscrit, étudie tard dans la nuit et obtient sa certification Scrum Master.',
    'hero.scene4': '6 mois plus tard — elle dirige une équipe professionnelle, gagnant 60 000 $ par an.',
    'hero.scene5': 'Elle emménage dans un bel appartement. Sa vie est changée à jamais.',
    
    // Programs
    'programs.badge': 'Nos Programmes',
    'programs.title': 'Programmes de Formation de Classe Mondiale',
    'programs.subtitle': 'Des cours complets conçus pour élever vos compétences professionnelles et vos perspectives de carrière en gestion de projet agile.',
    'programs.scrum.title': 'Certification Scrum Master',
    'programs.scrum.desc': 'Devenez un Scrum Master certifié avec une formation pratique, des projets réels et des méthodologies d\'apprentissage améliorées par l\'IA.',
    'programs.pm.title': 'Professionnel en Gestion de Projet',
    'programs.pm.desc': 'Maîtrisez les cadres de gestion de projet avec des outils IA modernes pour la planification, l\'exécution et la gestion des parties prenantes.',
    'programs.ai.title': 'Outils IA pour Managers',
    'programs.ai.desc': 'Apprenez à exploiter les outils IA de pointe pour améliorer la productivité, la prise de décision et la collaboration d\'équipe.',
    'programs.duration': 'Durée',
    'programs.weeks': 'semaines',
    'programs.format': 'Format',
    'programs.hybrid': 'Hybride',
    'programs.online': 'En Ligne',
    'programs.learnMore': 'En Savoir Plus',
    'programs.startCourse': 'Commencer le Cours',
    'programs.comingSoon': "Rejoindre la Liste",
    'programs.liveProject.title': 'Projet Scrum en Direct : Simulation de Sprint de 2 Semaines',
    'programs.liveProject.desc': 'Vivez un sprint réaliste de deux semaines avec toutes les cérémonies Scrum en séquence — standups quotidiens, planification du sprint, affinage du backlog, revue du sprint et rétrospective.',
    'programs.liveProject.prereq': 'Nécessite de compléter des cours spécifiques pour débloquer',
    'programs.liveProject.duration': 'Sprint de 2 semaines',
    'programs.rogersProject.title': 'Projet de Fusion IT : Intégration Réseau Rogers-Shaw',
    'programs.rogersProject.desc': 'Dirigez un projet d\'intégration IT réel inspiré de la fusion Rogers-Shaw à 26 milliards $. Gérez 3 équipes Scrum sur 4 sprints pour consolider câble, sans-fil et systèmes d\'entreprise.',
    'programs.rogersProject.prereq': 'Nécessite de compléter des cours spécifiques pour débloquer',
    'programs.rogersProject.duration': 'Projet de 2 mois (4 sprints)',
    'programs.rogersProject.teams': '3 Équipes Scrum',
    
    // About
    'about.badge': 'À Propos de Nous',
    'about.title': 'Fondée sur l\'Excellence',
    'about.p1': 'Aladiah Academy a été fondée avec une vision claire : combler le fossé entre l\'éducation traditionnelle en gestion de projet et les exigences en constante évolution du monde des affaires moderne.',
    'about.p2': 'Dirigée par notre fondateur, un professionnel chevronné actuellement chez Royal Caribbean International, nous apportons une expertise réelle et des connexions industrielles à chaque programme que nous offrons.',
    'about.p3': 'Opérant sous Aladiah Management, nous maintenons les plus hauts standards de formation professionnelle tout en embrassant l\'innovation et le pouvoir transformateur de l\'IA dans l\'éducation.',
    'about.founder': 'Fondateur et PDG',
    'about.company': 'Aladiah Management',
    
    // Founder
    'founder.bio.title': 'Leader Visionnaire en Éducation Agile et IA',
    'founder.bio.p1': 'Didier Boumtje est un cadre IT chevronné et leader de la transformation Agile avec plus de 10 ans d\'expérience dans la conduite d\'initiatives technologiques à grande échelle dans les secteurs des croisières, de l\'hôtellerie et de l\'entreprise. Actuellement Chef de Projet Senior chez Royal Caribbean International, il orchestre des programmes de transformation numérique de plusieurs millions de dollars à travers les opérations mondiales.',
    'founder.bio.p2': 'Passionné par la démocratisation de l\'éducation professionnelle, Didier a fondé Aladiah Academy pour apporter une formation de classe mondiale en Scrum Master et Gestion de Projet aux marchés émergents — propulsée par des outils IA de pointe qui personnalisent le parcours d\'apprentissage de chaque étudiant.',
    'founder.credential1': 'PM Senior chez Royal Caribbean International — dirige des équipes pluridisciplinaires dans 5 pays',
    'founder.credential2': 'Scrum Master Certifié (CSM), PMP et SAFe Agilist avec 10+ ans en IT d\'entreprise',
    'founder.credential3': 'Innovateur en IA et Éducation — pionnier de la conception curriculaire par IA pour la formation professionnelle',
    'founder.credential4': 'Leader multilingue parlant couramment 4 langues, construisant une académie mondiale en 7 langues',
    'founder.quote': 'Je crois au pouvoir d\'«automatiser l\'automatisation» de manière sophistiquée.',
    'founder.teaching.caption': 'Didier Boumtje dispensant une formation Scrum pratique à la prochaine génération de leaders Agile',

    // Features
    'features.ai.title': 'Apprentissage Amélioré par l\'IA',
    'features.ai.desc': 'Outils IA de pointe intégrés dans notre programme',
    'features.expert.title': 'Experts de l\'Industrie',
    'features.expert.desc': 'Apprenez de professionnels avec une expérience réelle',
    'features.network.title': 'Réseau Professionnel',
    'features.network.desc': 'Connectez-vous avec les leaders de l\'industrie et vos pairs',
    
    // CTA
    'cta.title': 'Prêt à Transformer Votre Carrière ?',
    'cta.subtitle': 'Rejoignez des centaines de professionnels qui ont fait avancer leur carrière grâce à nos programmes. Commencez votre voyage aujourd\'hui.',
    'cta.button': 'Commencer Maintenant',
    
    // Footer
    'footer.description': 'Institut de Formation Professionnelle pour Scrum Masters et Gestionnaires de Projet, alimenté par l\'innovation IA.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.location': 'République Dominicaine',
    'footer.rights': 'Tous droits réservés.',
    'footer.company': 'Une division d\'Aladiah Management',

    // Blog
    'blog.badge': 'Perspectives de l\'Industrie',
    'blog.title': 'L\'Essor de Scrum en République Dominicaine',
    'blog.subtitle': 'Pourquoi la méthodologie Agile transforme les carrières et crée une demande sans précédent pour les professionnels certifiés',
    'blog.intro': 'La République Dominicaine émerge comme un hub stratégique pour la transformation Agile dans les Amériques. Avec son secteur technologique en croissance, sa main-d\'œuvre bilingue et sa proximité avec les marchés nord-américains, le pays est parfaitement positionné pour répondre à la demande mondiale croissante de Scrum Masters et de professionnels Agile.',
    'blog.section1.title': 'Adoption Mondiale de Scrum : Les Chiffres',
    'blog.section1.content': 'Selon le 15e Rapport State of Agile, 66% des organisations dans le monde utilisent maintenant Scrum comme leur cadre Agile principal. Cette dominance a créé une demande sans précédent pour les Scrum Masters certifiés, le Forum Économique Mondial projetant une croissance de 37,9% des rôles liés à Scrum au cours de la prochaine décennie.',
    'blog.section2.title': 'Tendances Salariales sur les Marchés',
    'blog.section2.content': 'Les salaires des Scrum Masters reflètent cette forte demande. En Australie, les Senior Scrum Masters gagnent en moyenne 156 000 A$ par an. Au Royaume-Uni, les salaires varient de 55 000 £ à 95 000 £ selon l\'expérience. Les États-Unis sont en tête avec des moyennes de 115 000 $ à 145 000 $ pour les professionnels expérimentés.',
    'blog.section3.title': 'L\'Avantage Dominicain',
    'blog.section3.content': 'La République Dominicaine offre des avantages uniques pour les professionnels Scrum : une main-d\'œuvre bilingue espagnol-anglais parfaitement adaptée au nearshoring, des coûts compétitifs pour les multinationales et un secteur informatique en croissance rapide. Les grandes entreprises recherchent de plus en plus les talents Agile dans les Caraïbes.',
    'blog.section4.title': 'Industries Stimulant la Demande',
    'blog.section4.content': 'Bien que Scrum soit né dans le développement logiciel, la demande actuelle s\'étend à plusieurs secteurs : Services Financiers, Santé, Fabrication, Gouvernement, Marketing et Conseil. Les secteurs de l\'Énergie et des Sciences de la Vie offrent les salaires d\'entrée les plus élevés, souvent 20-30% au-dessus de la moyenne.',
    'blog.section5.title': 'Parcours de Croissance de Carrière',
    'blog.section5.content': 'Une certification Scrum Master ouvre plusieurs trajectoires de carrière : Coach Agile, Mentor Scrum, Gestionnaire de Programme Agile, ou même Chief Agile Officer. Chaque parcours offre des responsabilités et une rémunération croissantes, les Coachs Agile percevant des salaires 40-60% plus élevés que les Scrum Masters débutants.',
    'blog.section6.title': 'L\'Avantage Multilingue',
    'blog.section6.content': 'Dans l\'économie mondiale actuelle, les Scrum Masters multilingues sont exceptionnellement précieux. Les professionnels capables de faciliter les cérémonies et de coacher des équipes dans plusieurs langues—notamment l\'anglais, l\'espagnol et le portugais—obtiennent des salaires premium dans les organisations internationales.',
    'blog.cta': 'Explorez Notre Cours Scrum Master',
    'blog.source': 'Sources : Rapport State of Agile, Forum Économique Mondial, Glassdoor, The Knowledge Academy',
    'blog.stats.adoption': 'Taux d\'Adoption Agile',
    'blog.stats.scrum': 'Utilisent le Framework Scrum',
    'blog.stats.growth': 'Croissance Projetée',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.programs': 'Programme',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.enroll': 'Jetzt anmelden',
    
    // Hero
    'hero.badge': 'KI-gestützte Berufsausbildung',
    'hero.title.line1': 'Meistere Agile Führung',
    'hero.title.line2': 'Mit KI-Innovation',
    'hero.subtitle': 'Transformiere deine Karriere mit modernster Scrum Master und Projektmanagement-Ausbildung, erweitert durch die neuesten KI-Tools. Tritt der Zukunft der beruflichen Entwicklung in der Dominikanischen Republik bei.',
    'hero.cta.primary': 'Programme erkunden',
    'hero.cta.secondary': 'Mehr erfahren',
    'hero.stats.students': 'Ausgebildete Studenten',
    'hero.stats.rate': 'Erfolgsquote',
    'hero.stats.partners': 'Unternehmenspartner',
    'hero.scene1': 'María arbeitet lange Stunden in einem Restaurant in Santo Domingo…',
    'hero.scene2': 'Eines Nachts sieht sie eine Anzeige auf Instagram — Aladiah Academy. Eine Chance, alles zu ändern.',
    'hero.scene3': 'Sie schreibt sich ein, lernt bis spät in die Nacht und erhält ihre Scrum Master-Zertifizierung.',
    'hero.scene4': '6 Monate später — sie leitet ein professionelles Team und verdient 60.000 $ pro Jahr.',
    'hero.scene5': 'Sie zieht in eine schöne Wohnung. Ihr Leben hat sich für immer verändert.',
    
    // Programs
    'programs.badge': 'Unsere Programme',
    'programs.title': 'Weltklasse-Trainingsprogramme',
    'programs.subtitle': 'Umfassende Kurse, die darauf ausgelegt sind, deine beruflichen Fähigkeiten und Karrierechancen im agilen Projektmanagement zu verbessern.',
    'programs.scrum.title': 'Scrum Master Zertifizierung',
    'programs.scrum.desc': 'Werde ein zertifizierter Scrum Master mit praxisnahem Training, realen Projekten und KI-erweiterten Lernmethoden.',
    'programs.pm.title': 'Projektmanagement-Fachmann',
    'programs.pm.desc': 'Beherrsche Projektmanagement-Frameworks mit modernen KI-Tools für Planung, Ausführung und Stakeholder-Management.',
    'programs.ai.title': 'KI-Tools für Manager',
    'programs.ai.desc': 'Lerne, modernste KI-Tools zu nutzen, um Produktivität, Entscheidungsfindung und Teamzusammenarbeit zu verbessern.',
    'programs.duration': 'Dauer',
    'programs.weeks': 'Wochen',
    'programs.format': 'Format',
    'programs.hybrid': 'Hybrid',
    'programs.online': 'Online',
    'programs.learnMore': 'Mehr erfahren',
    'programs.startCourse': 'Kurs starten',
    'programs.comingSoon': 'Warteliste beitreten',
    'programs.liveProject.title': 'Live-Scrum-Projekt: 2-Wochen-Sprint-Simulation',
    'programs.liveProject.desc': 'Erleben Sie einen realistischen zweiwöchigen Sprint mit allen Scrum-Zeremonien in der richtigen Reihenfolge — tägliche Standups, Sprint-Planung, Backlog-Verfeinerung, Sprint-Review und Retrospektive.',
    'programs.liveProject.prereq': 'Erfordert den Abschluss bestimmter Kurse zum Freischalten',
    'programs.liveProject.duration': '2-Wochen-Sprint',
    'programs.rogersProject.title': 'IT-Fusionsprojekt: Rogers-Shaw Netzwerkintegration',
    'programs.rogersProject.desc': 'Leiten Sie ein reales IT-Integrationsprojekt, inspiriert von der Rogers-Shaw 26-Milliarden-Dollar-Fusion. Verwalten Sie 3 Scrum-Teams über 4 Sprints zur Konsolidierung von Kabel-, Funk- und Unternehmenssystemen.',
    'programs.rogersProject.prereq': 'Erfordert den Abschluss bestimmter Kurse zum Freischalten',
    'programs.rogersProject.duration': '2-Monats-Projekt (4 Sprints)',
    'programs.rogersProject.teams': '3 Scrum-Teams',
    
    // About
    'about.badge': 'Über Uns',
    'about.title': 'Gegründet auf Exzellenz',
    'about.p1': 'Aladiah Academy wurde mit einer klaren Vision gegründet: die Lücke zwischen traditioneller Projektmanagement-Ausbildung und den sich schnell entwickelnden Anforderungen der modernen Geschäftswelt zu schließen.',
    'about.p2': 'Unter der Leitung unseres Gründers, eines erfahrenen Profis, der derzeit bei Royal Caribbean International arbeitet, bringen wir praktische Expertise und Branchenverbindungen in jedes Programm ein, das wir anbieten.',
    'about.p3': 'Unter Aladiah Management halten wir die höchsten Standards der Berufsausbildung aufrecht und nutzen gleichzeitig Innovation und die transformative Kraft der KI in der Bildung.',
    'about.founder': 'Gründer & CEO',
    'about.company': 'Aladiah Management',
    
    // Founder
    'founder.bio.title': 'Visionärer Führer in Agile & KI-Bildung',
    'founder.bio.p1': 'Didier Boumtje ist ein erfahrener IT-Führungskraft und Agile-Transformationsleiter mit über 10 Jahren Erfahrung in der Leitung großer Technologieinitiativen in der Kreuzfahrt-, Gastgewerbe- und Unternehmensbranche. Derzeit Senior-Projektmanager bei Royal Caribbean International, orchestriert er millionenschwere digitale Transformationsprogramme über globale Operationen hinweg.',
    'founder.bio.p2': 'Leidenschaftlich für die Demokratisierung der Berufsausbildung gründete Didier die Aladiah Academy, um erstklassige Scrum Master und Projektmanagement-Ausbildung in aufstrebende Märkte zu bringen — angetrieben von modernsten KI-Tools, die den Lernweg jedes Studenten personalisieren.',
    'founder.credential1': 'Senior PM bei Royal Caribbean International — leitet funktionsübergreifende Teams in 5 Ländern',
    'founder.credential2': 'Zertifizierter Scrum Master (CSM), PMP und SAFe Agilist mit 10+ Jahren in Unternehmens-IT',
    'founder.credential3': 'KI & Bildungsinnovator — Pionier im KI-gestützten Curriculumdesign für Berufsausbildung',
    'founder.credential4': 'Mehrsprachiger Leader fließend in 4 Sprachen, baut eine globale Akademie in 7 Sprachen auf',
    'founder.quote': 'Ich glaube an die Kraft, „die Automatisierung zu automatisieren" auf eine raffinierte Weise.',
    'founder.teaching.caption': 'Didier Boumtje bei der praxisnahen Scrum-Schulung der nächsten Generation agiler Führungskräfte',

    // Features
    'features.ai.title': 'KI-erweitertes Lernen',
    'features.ai.desc': 'Modernste KI-Tools in unseren Lehrplan integriert',
    'features.expert.title': 'Branchenexperten',
    'features.expert.desc': 'Lerne von Profis mit praktischer Erfahrung',
    'features.network.title': 'Professionelles Netzwerk',
    'features.network.desc': 'Vernetze dich mit Branchenführern und Kollegen',
    
    // CTA
    'cta.title': 'Bereit, deine Karriere zu transformieren?',
    'cta.subtitle': 'Schließe dich Hunderten von Fachleuten an, die ihre Karriere durch unsere Programme vorangebracht haben. Beginne noch heute deine Reise.',
    'cta.button': 'Jetzt starten',
    
    // Footer
    'footer.description': 'Professionelles Ausbildungsinstitut für Scrum Masters und Projektmanager, angetrieben durch KI-Innovation.',
    'footer.quickLinks': 'Schnelllinks',
    'footer.contact': 'Kontakt',
    'footer.location': 'Dominikanische Republik',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.company': 'Eine Abteilung von Aladiah Management',

    // Blog
    'blog.badge': 'Brancheneinblicke',
    'blog.title': 'Der Aufstieg von Scrum in der Dominikanischen Republik',
    'blog.subtitle': 'Warum die agile Methodik Karrieren transformiert und eine beispiellose Nachfrage nach zertifizierten Fachleuten schafft',
    'blog.intro': 'Die Dominikanische Republik entwickelt sich zu einem strategischen Zentrum für die agile Transformation in Amerika. Mit ihrem wachsenden Technologiesektor, der zweisprachigen Belegschaft und der Nähe zu den nordamerikanischen Märkten ist das Land perfekt positioniert, um die wachsende globale Nachfrage nach Scrum Masters und Agile-Profis zu befriedigen.',
    'blog.section1.title': 'Globale Scrum-Einführung: Die Zahlen',
    'blog.section1.content': 'Laut dem 15. State of Agile Report verwenden 66% der Organisationen weltweit jetzt Scrum als ihr primäres Agile-Framework. Diese Dominanz hat eine beispiellose Nachfrage nach zertifizierten Scrum Masters geschaffen, wobei das Weltwirtschaftsforum ein Wachstum von 37,9% bei Scrum-bezogenen Rollen im nächsten Jahrzehnt prognostiziert.',
    'blog.section2.title': 'Gehaltstrends auf den Märkten',
    'blog.section2.content': 'Die Gehälter von Scrum Masters spiegeln diese hohe Nachfrage wider. In Australien verdienen Senior Scrum Masters durchschnittlich 156.000 A$ jährlich. Im Vereinigten Königreich reichen die Gehälter je nach Erfahrung von £55.000 bis £95.000. Die USA führen mit Durchschnittswerten von $115.000-$145.000 für erfahrene Fachleute.',
    'blog.section3.title': 'Der dominikanische Vorteil',
    'blog.section3.content': 'Die Dominikanische Republik bietet einzigartige Vorteile für Scrum-Profis: eine zweisprachige spanisch-englische Belegschaft, die sich perfekt für Nearshoring eignet, wettbewerbsfähige Kosten für multinationale Unternehmen und einen schnell wachsenden IT-Sektor. Große Unternehmen suchen zunehmend in der Karibik nach agilen Talenten.',
    'blog.section4.title': 'Branchen, die die Nachfrage antreiben',
    'blog.section4.content': 'Während Scrum aus der Softwareentwicklung stammt, erstreckt sich die heutige Nachfrage über mehrere Sektoren: Finanzdienstleistungen, Gesundheitswesen, Fertigung, Regierung, Marketing und Beratung. Energie- und Life-Science-Sektoren bieten die höchsten Einstiegsgehälter, oft 20-30% über dem Durchschnitt.',
    'blog.section5.title': 'Karrierewachstumspfade',
    'blog.section5.content': 'Eine Scrum Master-Zertifizierung eröffnet mehrere Karrierewege: Agile Coach, Scrum Mentor, Agile Program Manager oder sogar Chief Agile Officer. Jeder Pfad bietet zunehmende Verantwortung und Vergütung, wobei Agile Coaches Gehälter verdienen, die 40-60% höher sind als die von Einsteiger-Scrum-Masters.',
    'blog.section6.title': 'Der mehrsprachige Vorteil',
    'blog.section6.content': 'In der heutigen globalen Wirtschaft sind mehrsprachige Scrum Masters außergewöhnlich wertvoll. Fachleute, die Zeremonien moderieren und Teams in mehreren Sprachen coachen können—insbesondere Englisch, Spanisch und Portugiesisch—erhalten Premium-Gehälter in internationalen Organisationen.',
    'blog.cta': 'Entdecke unseren Scrum Master Kurs',
    'blog.source': 'Quellen: State of Agile Report, Weltwirtschaftsforum, Glassdoor, The Knowledge Academy',
    'blog.stats.adoption': 'Agile-Einführungsrate',
    'blog.stats.scrum': 'Nutzen Scrum Framework',
    'blog.stats.growth': 'Prognostiziertes Wachstum',
  },
  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.programs': 'プログラム',
    'nav.about': '私たちについて',
    'nav.contact': 'お問い合わせ',
    'nav.enroll': '今すぐ登録',
    
    // Hero
    'hero.badge': 'AI駆動のプロフェッショナルトレーニング',
    'hero.title.line1': 'アジャイルリーダーシップをマスター',
    'hero.title.line2': 'AIイノベーションと共に',
    'hero.subtitle': '最新のAIツールで強化されたスクラムマスターとプロジェクトマネジメントトレーニングでキャリアを変革しましょう。ドミニカ共和国でのプロフェッショナル開発の未来に参加してください。',
    'hero.cta.primary': 'プログラムを探索',
    'hero.cta.secondary': '詳しく見る',
    'hero.stats.students': '受講生',
    'hero.stats.rate': '成功率',
    'hero.stats.partners': '法人パートナー',
    'hero.scene1': 'マリアはサントドミンゴのレストランで長時間働いています…',
    'hero.scene2': 'ある夜、Instagramで広告を見ます——Aladiah Academy。すべてを変えるチャンス。',
    'hero.scene3': '入学し、夜遅くまで勉強し、スクラムマスター認定を取得します。',
    'hero.scene4': '6ヶ月後——プロフェッショナルチームをリードし、年収60,000ドルを稼いでいます。',
    'hero.scene5': '美しいアパートに引っ越します。彼女の人生は永遠に変わりました。',
    
    // Programs
    'programs.badge': '私たちのプログラム',
    'programs.title': 'ワールドクラスのトレーニングプログラム',
    'programs.subtitle': 'アジャイルプロジェクトマネジメントにおける専門スキルとキャリアの見通しを高めるために設計された包括的なコース。',
    'programs.scrum.title': 'スクラムマスター認定',
    'programs.scrum.desc': '実践的なトレーニング、実際のプロジェクト、AI強化学習方法論で認定スクラムマスターになりましょう。',
    'programs.pm.title': 'プロジェクトマネジメントプロフェッショナル',
    'programs.pm.desc': '計画、実行、ステークホルダー管理のための最新AIツールでプロジェクトマネジメントフレームワークをマスターしましょう。',
    'programs.ai.title': 'マネージャー向けAIツール',
    'programs.ai.desc': '生産性、意思決定、チームコラボレーションを向上させるための最先端AIツールの活用方法を学びましょう。',
    'programs.duration': '期間',
    'programs.weeks': '週間',
    'programs.format': '形式',
    'programs.hybrid': 'ハイブリッド',
    'programs.online': 'オンライン',
    'programs.learnMore': '詳しく見る',
    'programs.startCourse': 'コースを開始',
    'programs.comingSoon': 'ウェイトリストに参加',
    'programs.liveProject.title': 'ライブスクラムプロジェクト：2週間スプリントシミュレーション',
    'programs.liveProject.desc': 'すべてのスクラムセレモニーを順番に体験する、リアルな2週間スプリント——デイリースタンドアップ、スプリント計画、バックログリファインメント、スプリントレビュー、レトロスペクティブ。',
    'programs.liveProject.prereq': '特定のコースを完了してロック解除が必要',
    'programs.liveProject.duration': '2週間スプリント',
    'programs.rogersProject.title': 'IT合併プロジェクト：Rogers-Shawネットワーク統合',
    'programs.rogersProject.desc': 'Rogers-Shawの260億ドル通信合併に触発された実際のIT統合プロジェクトをリード。4スプリントにわたり3つのスクラムチームを管理し、ケーブル、ワイヤレス、企業システムを統合。',
    'programs.rogersProject.prereq': '特定のコースを完了してロック解除が必要',
    'programs.rogersProject.duration': '2ヶ月プロジェクト（4スプリント）',
    'programs.rogersProject.teams': '3つのスクラムチーム',
    
    // About
    'about.badge': '私たちについて',
    'about.title': '卓越性に基づいて設立',
    'about.p1': 'Aladiah Academyは明確なビジョンを持って設立されました：従来のプロジェクトマネジメント教育と現代ビジネス世界の急速に進化する要求との間のギャップを埋めることです。',
    'about.p2': '現在Royal Caribbean Internationalで活躍するベテランプロフェッショナルである創設者のリーダーシップの下、私たちは提供するすべてのプログラムに実世界の専門知識と業界とのつながりをもたらします。',
    'about.p3': 'Aladiah Managementの下で運営し、イノベーションと教育におけるAIの変革力を受け入れながら、プロフェッショナルトレーニングの最高基準を維持しています。',
    'about.founder': '創設者兼CEO',
    'about.company': 'Aladiah Management',
    
    // Founder
    'founder.bio.title': 'アジャイル＆AI教育の先見的リーダー',
    'founder.bio.p1': 'Didier Boumtjeは、クルーズ、ホスピタリティ、エンタープライズセクターにおいて大規模なテクノロジーイニシアチブを推進してきた10年以上の経験を持つ熟練したITエグゼクティブ兼アジャイル変革リーダーです。現在Royal Caribbean Internationalのシニアプロジェクトマネージャーとして、グローバルオペレーション全体で数百万ドル規模のデジタルトランスフォーメーションプログラムを統括しています。',
    'founder.bio.p2': 'プロフェッショナル教育の民主化に情熱を持ち、DidierはAladiah Academyを設立し、世界クラスのスクラムマスターおよびプロジェクトマネジメント研修を新興市場に届けています——最先端のAIツールが各学生の学習旅路をパーソナライズします。',
    'founder.credential1': 'Royal Caribbean Internationalシニアプロジェクトマネージャー——5カ国でクロスファンクショナルチームをリード',
    'founder.credential2': '認定スクラムマスター（CSM）、PMP、SAFe Agilist、エンタープライズIT10年以上の経験',
    'founder.credential3': 'AI＆教育イノベーター——専門研修のためのAI駆動カリキュラムデザインのパイオニア',
    'founder.credential4': '4言語に堪能な多言語リーダー、7言語でグローバルアカデミーを構築中',
    'founder.quote': '「自動化を自動化する」力を、洗練された方法で信じています。',
    'founder.teaching.caption': 'Didier Boumtjeが次世代のアジャイルリーダーに実践的なスクラム研修を提供',

    // Features
    'features.ai.title': 'AI強化学習',
    'features.ai.desc': '最先端のAIツールがカリキュラムに統合',
    'features.expert.title': '業界エキスパート',
    'features.expert.desc': '実務経験を持つプロフェッショナルから学ぶ',
    'features.network.title': 'プロフェッショナルネットワーク',
    'features.network.desc': '業界リーダーや同僚とつながる',
    
    // CTA
    'cta.title': 'キャリアを変革する準備はできましたか？',
    'cta.subtitle': '私たちのプログラムを通じてキャリアを前進させた数百人のプロフェッショナルに参加してください。今日から旅を始めましょう。',
    'cta.button': '今すぐ始める',
    
    // Footer
    'footer.description': 'AIイノベーションによって駆動されるスクラムマスターとプロジェクトマネージャーのためのプロフェッショナルトレーニング機関。',
    'footer.quickLinks': 'クイックリンク',
    'footer.contact': 'お問い合わせ',
    'footer.location': 'ドミニカ共和国',
    'footer.rights': '無断転載を禁じます。',
    'footer.company': 'Aladiah Managementの一部門',

    // Blog
    'blog.badge': '業界インサイト',
    'blog.title': 'ドミニカ共和国でのスクラムの台頭',
    'blog.subtitle': 'なぜアジャイル方法論がキャリアを変革し、認定プロフェッショナルへの前例のない需要を生み出しているのか',
    'blog.intro': 'ドミニカ共和国は、アメリカ大陸におけるアジャイル変革の戦略的ハブとして台頭しています。成長するテクノロジーセクター、バイリンガルな労働力、北米市場への近接性を持つこの国は、スクラムマスターとアジャイルプロフェッショナルへの急増するグローバル需要に応えるのに完璧な位置にあります。',
    'blog.section1.title': 'グローバルスクラム採用：数字',
    'blog.section1.content': '第15回State of Agileレポートによると、世界中の組織の66%が現在、主要なアジャイルフレームワークとしてスクラムを使用しています。この優位性は認定スクラムマスターへの前例のない需要を生み出し、世界経済フォーラムは今後10年間でスクラム関連の役割が37.9%成長すると予測しています。',
    'blog.section2.title': '市場全体の給与動向',
    'blog.section2.content': 'スクラムマスターの給与はこの高い需要を反映しています。オーストラリアでは、シニアスクラムマスターは年間平均156,000豪ドルを稼いでいます。英国では、経験に応じて£55,000から£95,000の範囲です。米国は経験豊富なプロフェッショナルで$115,000-$145,000の平均でリードしています。',
    'blog.section3.title': 'ドミニカの優位性',
    'blog.section3.content': 'ドミニカ共和国はスクラムプロフェッショナルに独自の利点を提供します：ニアショアリングに最適なスペイン語-英語バイリンガル労働力、多国籍企業にとって競争力のあるコスト、急速に成長するITセクター。大企業はますますカリブ海でアジャイル人材を探しています。',
    'blog.section4.title': '需要を牽引する産業',
    'blog.section4.content': 'スクラムはソフトウェア開発で生まれましたが、今日の需要は複数のセクターにまたがっています：金融サービス、ヘルスケア、製造、政府、マーケティング、コンサルティング。エネルギーとライフサイエンスセクターは最高のエントリーレベル給与を提供し、多くの場合平均より20-30%高いです。',
    'blog.section5.title': 'キャリア成長パス',
    'blog.section5.content': 'スクラムマスター認定は複数のキャリア軌道を開きます：アジャイルコーチ、スクラムメンター、アジャイルプログラムマネージャー、さらにはチーフアジャイルオフィサー。各パスは増加する責任と報酬を提供し、アジャイルコーチはエントリーレベルのスクラムマスターより40-60%高い給与を得ています。',
    'blog.section6.title': '多言語の優位性',
    'blog.section6.content': '今日のグローバル経済において、多言語のスクラムマスターは非常に価値があります。複数の言語—特に英語、スペイン語、ポルトガル語—でセレモニーを促進し、チームをコーチできるプロフェッショナルは、国際組織でプレミアム給与を得ています。',
    'blog.cta': 'スクラムマスターコースを探索',
    'blog.source': '出典：State of Agileレポート、世界経済フォーラム、Glassdoor、The Knowledge Academy',
    'blog.stats.adoption': 'アジャイル採用率',
    'blog.stats.scrum': 'スクラムフレームワーク使用',
    'blog.stats.growth': '予測成長',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
