// Auto-generated Overview page translations (7 launch languages).
// Used by StudentPortal.tsx. Add more languages by adding blocks here.
// Falls back to English for any language not present.

export const OVERVIEW_STR: Record<string, Record<string, string>> = {
  en: {
    welcome: 'Welcome back',
    subtitle: '"You’re building the future. Stay consistent, stay focused, and the world is yours."',
    your_next_action: 'Your Next Action',
    fastest_path: 'The fastest path to your next milestone',
    continue: 'Continue',
    ai_mentor: 'AI Mentor',
    ai_mentor_sub: 'Get personalized guidance from your AI Mentor',
    chat_now: 'Chat Now',
    daily_challenge: 'Daily Challenge',
    daily_challenge_sub: 'Complete today’s challenge and earn 50 points',
    start_challenge: 'Start Challenge',
    live_session: 'Live Session',
    live_session_sub: 'Join live Q&A with industry experts',
    join_now: 'Join Now',
    overall_progress: 'Overall Progress',
    keep_going: 'Keep going!',
    day_streak: 'Day Streak',
    amazing: 'Amazing consistency!',
    points_earned: 'Points Earned',
    this_week: '+350 this week',
    labs_completed: 'Labs Completed',
    labs_week: '+3 this week',
    certifications: 'Certifications',
    in_progress: 'In Progress',
    ai_workforce: 'AI Workforce Programs',
    programs_schools: 'programs across 4 schools',
    view_all: 'View All Programs →',
    prof_greeting: 'Good morning',
    prof_analyzed: 'I’ve analyzed your progress and prepared a custom plan to get you to the next level.',
    talk_prof: 'Talk to Prof. Didier',
    prof_greet_onboarding: 'Welcome',
    prof_greet_daily: 'Welcome back',
    prof_greet_upgrade: 'Congratulations',
    prof_rec_onboarding: 'First step',
    prof_rec_daily: 'Next up',
    prof_rec_upgrade: 'Your next move',
    talent_score_label: 'Talent Score™',
    rising_star: 'Rising Star',
    view_breakdown: 'View Full Breakdown →',
    top_skills: 'Top Skills Strength',
    career_momentum: 'Career Momentum',
    live_feed: 'Live Feed',
    future_ready: 'You are future-ready',
    future_sub: 'Keep building. The world needs your talent.',
    done_day: 'Done for the Day',
    hours_employable: 'Hours to Employable',
    lessons: 'Lessons',
    start: 'Start →',
    pro_member: 'Pro Member',
    all_access: 'All-Access Pass™',
    overview: 'Overview',
    my_academy: 'My Academy',
    my_career: 'My Career Path',
    talent: 'Talent Score™',
    certs: 'Certifications',
    career_tools: 'Career Tools',
    portfolio: 'My Portfolio',
    labs: 'Labs',
    community: 'Community',
    leaderboard: 'Leaderboard',
    events: 'Events',
    settings: 'Settings',
    management: 'Aladiah Management',
    refer: 'Refer & Earn',
    refer_sub: 'Invite friends and earn premium rewards',
    account: 'ACCOUNT',
    got_hired: 'just got hired as',
    completed: 'completed',
    earned: 'earned',
    at: 'at',
    year: '/year',
    ago: 'ago',
    min: 'min',
    new: 'New',
    ai_interview: 'AI Interview',
    practice_now: 'Practice Now',
    resume_builder: 'Resume Builder',
    optimize_cv: 'Optimize CV',
    job_matches: 'Job Matches',
    new_jobs: 'New Jobs',
    portfolio_analyzer: 'Portfolio Analyzer',
    get_feedback: 'Get AI Feedback',
    salary_insights: 'Salary Insights',
    know_worth: 'Know Your Worth',
    countries_community: 'Countries in Community',
    top_learners: 'of Learners',
    nav_my_portal: 'My Portal',
    nav_courses: 'Courses',
    nav_talent_score: 'Talent Score™',
    nav_career: 'Career',
    nav_community: 'Community',
    nav_resources: 'Resources',
    rising: 'Rising',
    continue_learning: 'Continue Learning →',
  },
  es: {
    welcome: 'Bienvenido de vuelta',
    subtitle: '"Estás construyendo el futuro. Sé constante, mantente enfocado, y el mundo es tuyo."',
    your_next_action: 'Tu Próxima Acción',
    fastest_path: 'El camino más rápido hacia tu próximo hito',
    continue: 'Continuar',
    ai_mentor: 'Mentor IA',
    ai_mentor_sub: 'Recibe orientación personalizada de tu Mentor IA',
    chat_now: 'Chatear',
    daily_challenge: 'Desafío Diario',
    daily_challenge_sub: 'Completa el desafío de hoy y gana 50 puntos',
    start_challenge: 'Comenzar',
    live_session: 'Sesión en Vivo',
    live_session_sub: 'Únete a preguntas en vivo con expertos',
    join_now: 'Unirse',
    overall_progress: 'Progreso General',
    keep_going: '¡Sigue adelante!',
    day_streak: 'Días Seguidos',
    amazing: '¡Consistencia increíble!',
    points_earned: 'Puntos Ganados',
    this_week: '+350 esta semana',
    labs_completed: 'Labs Completados',
    labs_week: '+3 esta semana',
    certifications: 'Certificaciones',
    in_progress: 'En Progreso',
    ai_workforce: 'Programas de IA',
    programs_schools: 'programas en 4 escuelas',
    view_all: 'Ver Todos los Programas →',
    prof_greeting: 'Buenos días',
    prof_analyzed: 'He analizado tu progreso y preparado un plan personalizado para llevarte al siguiente nivel.',
    talk_prof: 'Hablar con Prof. Didier',
    prof_greet_onboarding: 'Bienvenido',
    prof_greet_daily: 'Bienvenido de nuevo',
    prof_greet_upgrade: 'Felicidades',
    prof_rec_onboarding: 'Primer paso',
    prof_rec_daily: 'Siguiente',
    prof_rec_upgrade: 'Tu siguiente paso',
    talent_score_label: 'Talent Score™',
    rising_star: 'Estrella en Ascenso',
    view_breakdown: 'Ver Desglose Completo →',
    top_skills: 'Habilidades Principales',
    career_momentum: 'Impulso Profesional',
    live_feed: 'En Vivo',
    future_ready: 'Estás listo para el futuro',
    future_sub: 'Sigue construyendo. El mundo necesita tu talento.',
    done_day: 'Listo por Hoy',
    hours_employable: 'Horas para ser Empleable',
    lessons: 'Lecciones',
    start: 'Empezar →',
    pro_member: 'Miembro Pro',
    all_access: 'Pase Todo Acceso™',
    overview: 'Resumen',
    my_academy: 'Mi Academia',
    my_career: 'Mi Carrera',
    talent: 'Talent Score™',
    certs: 'Certificaciones',
    career_tools: 'Herramientas de Carrera',
    portfolio: 'Mi Portafolio',
    labs: 'Labs',
    community: 'Comunidad',
    leaderboard: 'Clasificación',
    events: 'Eventos',
    settings: 'Configuración',
    management: 'Aladiah Management',
    refer: 'Refiere y Gana',
    refer_sub: 'Invita amigos y gana recompensas premium',
    account: 'CUENTA',
    got_hired: 'acaba de ser contratado como',
    completed: 'completó',
    earned: 'obtuvo',
    at: 'en',
    year: '/año',
    ago: 'hace',
    min: 'min',
    new: 'Nuevo',
    ai_interview: 'Entrevista IA',
    practice_now: 'Practicar Ahora',
    resume_builder: 'Creador de CV',
    optimize_cv: 'Optimizar CV',
    job_matches: 'Empleos',
    new_jobs: 'Nuevos Empleos',
    portfolio_analyzer: 'Analizador de Portafolio',
    get_feedback: 'Obtener Feedback IA',
    salary_insights: 'Información Salarial',
    know_worth: 'Conoce tu Valor',
    countries_community: 'Países en la Comunidad',
    top_learners: 'de los Estudiantes',
    nav_my_portal: 'Mi Portal',
    nav_courses: 'Cursos',
    nav_talent_score: 'Talent Score™',
    nav_career: 'Carrera',
    nav_community: 'Comunidad',
    nav_resources: 'Recursos',
    rising: 'En Ascenso',
    continue_learning: 'Continuar Aprendiendo →',
  },
  fr: {
    welcome: 'Bon retour',
    subtitle: '"Vous construisez l’avenir. Restez constant, restez concentré, et le monde est à vous."',
    your_next_action: 'Votre Prochaine Action',
    fastest_path: 'Le chemin le plus rapide vers votre prochain jalon',
    continue: 'Continuer',
    ai_mentor: 'Mentor IA',
    ai_mentor_sub: 'Obtenez des conseils personnalisés de votre Mentor IA',
    chat_now: 'Discuter',
    daily_challenge: 'Défi du Jour',
    daily_challenge_sub: 'Relevez le défi du jour et gagnez 50 points',
    start_challenge: 'Commencer',
    live_session: 'Session en Direct',
    live_session_sub: 'Rejoignez des Q&R en direct avec des experts',
    join_now: 'Rejoindre',
    overall_progress: 'Progression Générale',
    keep_going: 'Continuez !',
    day_streak: 'Jours Consécutifs',
    amazing: 'Constance incroyable !',
    points_earned: 'Points Gagnés',
    this_week: '+350 cette semaine',
    labs_completed: 'Labs Complétés',
    labs_week: '+3 cette semaine',
    certifications: 'Certifications',
    in_progress: 'En Cours',
    ai_workforce: 'Programmes IA',
    programs_schools: 'programmes dans 4 écoles',
    view_all: 'Voir Tous les Programmes →',
    prof_greeting: 'Bonjour',
    prof_analyzed: 'J’ai analysé votre progression et préparé un plan personnalisé pour vous faire passer au niveau supérieur.',
    talk_prof: 'Parler à Prof. Didier',
    prof_greet_onboarding: 'Bienvenue',
    prof_greet_daily: 'Bon retour',
    prof_greet_upgrade: 'Félicitations',
    prof_rec_onboarding: 'Première étape',
    prof_rec_daily: 'À suivre',
    prof_rec_upgrade: 'Votre prochaine étape',
    talent_score_label: 'Talent Score™',
    rising_star: 'Étoile Montante',
    view_breakdown: 'Voir le Détail Complet →',
    top_skills: 'Compétences Principales',
    career_momentum: 'Élan Professionnel',
    live_feed: 'En Direct',
    future_ready: 'Vous êtes prêt pour l’avenir',
    future_sub: 'Continuez à construire. Le monde a besoin de votre talent.',
    done_day: 'Terminé pour Aujourd’hui',
    hours_employable: 'Heures vers l’Employabilité',
    lessons: 'Leçons',
    start: 'Commencer →',
    pro_member: 'Membre Pro',
    all_access: 'Pass Tout Accès™',
    overview: 'Aperçu',
    my_academy: 'Mon Académie',
    my_career: 'Ma Carrière',
    talent: 'Talent Score™',
    certs: 'Certifications',
    career_tools: 'Outils de Carrière',
    portfolio: 'Mon Portfolio',
    labs: 'Labs',
    community: 'Communauté',
    leaderboard: 'Classement',
    events: 'Événements',
    settings: 'Paramètres',
    management: 'Aladiah Management',
    refer: 'Référer et Gagner',
    refer_sub: 'Invitez des amis et gagnez des récompenses premium',
    account: 'COMPTE',
    got_hired: 'vient d’être embauché comme',
    completed: 'a complété',
    earned: 'a obtenu',
    at: 'chez',
    year: '/an',
    ago: 'il y a',
    min: 'min',
    new: 'Nouveau',
    ai_interview: 'Entretien IA',
    practice_now: 'Pratiquer',
    resume_builder: 'Créateur de CV',
    optimize_cv: 'Optimiser le CV',
    job_matches: 'Emplois',
    new_jobs: 'Nouveaux Emplois',
    portfolio_analyzer: 'Analyseur de Portfolio',
    get_feedback: 'Obtenir un Retour IA',
    salary_insights: 'Données Salariales',
    know_worth: 'Connaissez votre Valeur',
    countries_community: 'Pays dans la Communauté',
    top_learners: 'des Apprenants',
    nav_my_portal: 'Mon Portail',
    nav_courses: 'Cours',
    nav_talent_score: 'Talent Score™',
    nav_career: 'Carrière',
    nav_community: 'Communauté',
    nav_resources: 'Ressources',
    rising: 'En Hausse',
    continue_learning: 'Continuer l’Apprentissage →',
  },
  de: {
    welcome: 'Willkommen zurück',
    subtitle: '"Du baust die Zukunft. Bleib beständig, bleib fokussiert, und die Welt gehört dir."',
    your_next_action: 'Deine Nächste Aktion',
    fastest_path: 'Der schnellste Weg zu deinem nächsten Meilenstein',
    continue: 'Fortfahren',
    ai_mentor: 'KI-Mentor',
    ai_mentor_sub: 'Erhalte persönliche Beratung von deinem KI-Mentor',
    chat_now: 'Jetzt Chatten',
    daily_challenge: 'Tägliche Herausforderung',
    daily_challenge_sub: 'Meistere die heutige Herausforderung und verdiene 50 Punkte',
    start_challenge: 'Starten',
    live_session: 'Live-Sitzung',
    live_session_sub: 'Nimm an Live-Q&A mit Branchenexperten teil',
    join_now: 'Beitreten',
    overall_progress: 'Gesamtfortschritt',
    keep_going: 'Weiter so!',
    day_streak: 'Tagesserie',
    amazing: 'Unglaubliche Beständigkeit!',
    points_earned: 'Verdiente Punkte',
    this_week: '+350 diese Woche',
    labs_completed: 'Labs Abgeschlossen',
    labs_week: '+3 diese Woche',
    certifications: 'Zertifizierungen',
    in_progress: 'In Bearbeitung',
    ai_workforce: 'KI-Programme',
    programs_schools: 'Programme an 4 Schulen',
    view_all: 'Alle Programme Anzeigen →',
    prof_greeting: 'Guten Morgen',
    prof_analyzed: 'Ich habe deinen Fortschritt analysiert und einen individuellen Plan erstellt, um dich auf die nächste Stufe zu bringen.',
    talk_prof: 'Mit Prof. Didier Sprechen',
    talent_score_label: 'Talent Score™',
    rising_star: 'Aufsteigender Stern',
    view_breakdown: 'Vollständige Übersicht →',
    top_skills: 'Top-Kompetenzen',
    career_momentum: 'Karriere-Dynamik',
    live_feed: 'Live-Feed',
    future_ready: 'Du bist zukunftsbereit',
    future_sub: 'Bau weiter. Die Welt braucht dein Talent.',
    done_day: 'Fertig für Heute',
    hours_employable: 'Stunden bis zur Anstellung',
    lessons: 'Lektionen',
    start: 'Starten →',
    pro_member: 'Pro-Mitglied',
    all_access: 'All-Access Pass™',
    overview: 'Übersicht',
    my_academy: 'Meine Akademie',
    my_career: 'Mein Karriereweg',
    talent: 'Talent Score™',
    certs: 'Zertifizierungen',
    career_tools: 'Karriere-Tools',
    portfolio: 'Mein Portfolio',
    labs: 'Labs',
    community: 'Gemeinschaft',
    leaderboard: 'Bestenliste',
    events: 'Veranstaltungen',
    settings: 'Einstellungen',
    management: 'Aladiah Management',
    refer: 'Empfehlen & Verdienen',
    refer_sub: 'Lade Freunde ein und verdiene Premium-Belohnungen',
    account: 'KONTO',
    got_hired: 'wurde gerade eingestellt als',
    completed: 'abgeschlossen',
    earned: 'erhielt',
    at: 'bei',
    year: '/Jahr',
    ago: 'vor',
    min: 'Min',
    new: 'Neu',
    ai_interview: 'KI-Interview',
    practice_now: 'Jetzt Üben',
    resume_builder: 'Lebenslauf-Ersteller',
    optimize_cv: 'Lebenslauf Optimieren',
    job_matches: 'Jobangebote',
    new_jobs: 'Neue Jobs',
    portfolio_analyzer: 'Portfolio-Analyse',
    get_feedback: 'KI-Feedback Erhalten',
    salary_insights: 'Gehaltseinblicke',
    know_worth: 'Kenne deinen Wert',
    countries_community: 'Länder in der Gemeinschaft',
    top_learners: 'der Lernenden',
    nav_my_portal: 'Mein Portal',
    nav_courses: 'Kurse',
    nav_talent_score: 'Talent Score™',
    nav_career: 'Karriere',
    nav_community: 'Gemeinschaft',
    nav_resources: 'Ressourcen',
    rising: 'Steigend',
    continue_learning: 'Weiter Lernen →',
  },
  pt: {
    welcome: 'Bem-vindo de volta',
    subtitle: '"Você está construindo o futuro. Seja consistente, mantenha o foco, e o mundo é seu."',
    your_next_action: 'Sua Próxima Ação',
    fastest_path: 'O caminho mais rápido para o seu próximo marco',
    continue: 'Continuar',
    ai_mentor: 'Mentor IA',
    ai_mentor_sub: 'Receba orientação personalizada do seu Mentor IA',
    chat_now: 'Conversar',
    daily_challenge: 'Desafio Diário',
    daily_challenge_sub: 'Complete o desafio de hoje e ganhe 50 pontos',
    start_challenge: 'Começar',
    live_session: 'Sessão ao Vivo',
    live_session_sub: 'Participe de perguntas ao vivo com especialistas',
    join_now: 'Participar',
    overall_progress: 'Progresso Geral',
    keep_going: 'Continue assim!',
    day_streak: 'Dias Seguidos',
    amazing: 'Consistência incrível!',
    points_earned: 'Pontos Ganhos',
    this_week: '+350 esta semana',
    labs_completed: 'Labs Concluídos',
    labs_week: '+3 esta semana',
    certifications: 'Certificações',
    in_progress: 'Em Andamento',
    ai_workforce: 'Programas de IA',
    programs_schools: 'programas em 4 escolas',
    view_all: 'Ver Todos os Programas →',
    prof_greeting: 'Bom dia',
    prof_analyzed: 'Analisei o seu progresso e preparei um plano personalizado para levá-lo ao próximo nível.',
    talk_prof: 'Falar com Prof. Didier',
    talent_score_label: 'Talent Score™',
    rising_star: 'Estrela em Ascensão',
    view_breakdown: 'Ver Detalhes Completos →',
    top_skills: 'Principais Competências',
    career_momentum: 'Impulso Profissional',
    live_feed: 'Ao Vivo',
    future_ready: 'Você está pronto para o futuro',
    future_sub: 'Continue construindo. O mundo precisa do seu talento.',
    done_day: 'Concluído por Hoje',
    hours_employable: 'Horas para Empregabilidade',
    lessons: 'Lições',
    start: 'Começar →',
    pro_member: 'Membro Pro',
    all_access: 'Passe Acesso Total™',
    overview: 'Visão Geral',
    my_academy: 'Minha Academia',
    my_career: 'Minha Carreira',
    talent: 'Talent Score™',
    certs: 'Certificações',
    career_tools: 'Ferramentas de Carreira',
    portfolio: 'Meu Portfólio',
    labs: 'Labs',
    community: 'Comunidade',
    leaderboard: 'Classificação',
    events: 'Eventos',
    settings: 'Configurações',
    management: 'Aladiah Management',
    refer: 'Indique e Ganhe',
    refer_sub: 'Convide amigos e ganhe recompensas premium',
    account: 'CONTA',
    got_hired: 'acabou de ser contratado como',
    completed: 'concluiu',
    earned: 'ganhou',
    at: 'na',
    year: '/ano',
    ago: 'atrás',
    min: 'min',
    new: 'Novo',
    ai_interview: 'Entrevista IA',
    practice_now: 'Praticar Agora',
    resume_builder: 'Criador de Currículo',
    optimize_cv: 'Otimizar Currículo',
    job_matches: 'Vagas',
    new_jobs: 'Novas Vagas',
    portfolio_analyzer: 'Analisador de Portfólio',
    get_feedback: 'Obter Feedback IA',
    salary_insights: 'Dados Salariais',
    know_worth: 'Saiba seu Valor',
    countries_community: 'Países na Comunidade',
    top_learners: 'dos Alunos',
    nav_my_portal: 'Meu Portal',
    nav_courses: 'Cursos',
    nav_talent_score: 'Talent Score™',
    nav_career: 'Carreira',
    nav_community: 'Comunidade',
    nav_resources: 'Recursos',
    rising: 'Em Ascensão',
    continue_learning: 'Continuar Aprendendo →',
  },
  it: {
    welcome: 'Bentornato',
    subtitle: '"Stai costruendo il futuro. Resta costante, resta concentrato, e il mondo è tuo."',
    your_next_action: 'La Tua Prossima Azione',
    fastest_path: 'Il percorso più veloce verso il tuo prossimo traguardo',
    continue: 'Continua',
    ai_mentor: 'Mentor IA',
    ai_mentor_sub: 'Ricevi una guida personalizzata dal tuo Mentor IA',
    chat_now: 'Chatta Ora',
    daily_challenge: 'Sfida Giornaliera',
    daily_challenge_sub: 'Completa la sfida di oggi e guadagna 50 punti',
    start_challenge: 'Inizia',
    live_session: 'Sessione dal Vivo',
    live_session_sub: 'Partecipa a Q&A dal vivo con esperti del settore',
    join_now: 'Partecipa',
    overall_progress: 'Progresso Generale',
    keep_going: 'Continua così!',
    day_streak: 'Giorni Consecutivi',
    amazing: 'Costanza incredibile!',
    points_earned: 'Punti Guadagnati',
    this_week: '+350 questa settimana',
    labs_completed: 'Lab Completati',
    labs_week: '+3 questa settimana',
    certifications: 'Certificazioni',
    in_progress: 'In Corso',
    ai_workforce: 'Programmi IA',
    programs_schools: 'programmi in 4 scuole',
    view_all: 'Vedi Tutti i Programmi →',
    prof_greeting: 'Buongiorno',
    prof_analyzed: 'Ho analizzato i tuoi progressi e preparato un piano personalizzato per portarti al livello successivo.',
    talk_prof: 'Parla con Prof. Didier',
    talent_score_label: 'Talent Score™',
    rising_star: 'Stella Nascente',
    view_breakdown: 'Vedi Dettaglio Completo →',
    top_skills: 'Competenze Principali',
    career_momentum: 'Slancio Professionale',
    live_feed: 'Dal Vivo',
    future_ready: 'Sei pronto per il futuro',
    future_sub: 'Continua a costruire. Il mondo ha bisogno del tuo talento.',
    done_day: 'Fatto per Oggi',
    hours_employable: 'Ore verso l’Impiegabilità',
    lessons: 'Lezioni',
    start: 'Inizia →',
    pro_member: 'Membro Pro',
    all_access: 'Pass Accesso Totale™',
    overview: 'Panoramica',
    my_academy: 'La Mia Accademia',
    my_career: 'La Mia Carriera',
    talent: 'Talent Score™',
    certs: 'Certificazioni',
    career_tools: 'Strumenti di Carriera',
    portfolio: 'Il Mio Portfolio',
    labs: 'Lab',
    community: 'Comunità',
    leaderboard: 'Classifica',
    events: 'Eventi',
    settings: 'Impostazioni',
    management: 'Aladiah Management',
    refer: 'Invita e Guadagna',
    refer_sub: 'Invita amici e guadagna ricompense premium',
    account: 'ACCOUNT',
    got_hired: 'è stato appena assunto come',
    completed: 'ha completato',
    earned: 'ha ottenuto',
    at: 'presso',
    year: '/anno',
    ago: 'fa',
    min: 'min',
    new: 'Nuovo',
    ai_interview: 'Colloquio IA',
    practice_now: 'Esercitati Ora',
    resume_builder: 'Creatore di CV',
    optimize_cv: 'Ottimizza CV',
    job_matches: 'Offerte di Lavoro',
    new_jobs: 'Nuovi Lavori',
    portfolio_analyzer: 'Analizzatore Portfolio',
    get_feedback: 'Ottieni Feedback IA',
    salary_insights: 'Dati sugli Stipendi',
    know_worth: 'Conosci il tuo Valore',
    countries_community: 'Paesi nella Comunità',
    top_learners: 'degli Studenti',
    nav_my_portal: 'Il Mio Portale',
    nav_courses: 'Corsi',
    nav_talent_score: 'Talent Score™',
    nav_career: 'Carriera',
    nav_community: 'Comunità',
    nav_resources: 'Risorse',
    rising: 'In Crescita',
    continue_learning: 'Continua ad Imparare →',
  },
  ru: {
    welcome: 'С возвращением',
    subtitle: '"Вы строите будущее. Будьте последовательны, сосредоточены, и мир — ваш."',
    your_next_action: 'Ваше Следующее Действие',
    fastest_path: 'Самый быстрый путь к вашей следующей цели',
    continue: 'Продолжить',
    ai_mentor: 'ИИ-Наставник',
    ai_mentor_sub: 'Получите персональные советы от вашего ИИ-наставника',
    chat_now: 'Начать чат',
    daily_challenge: 'Ежедневный Вызов',
    daily_challenge_sub: 'Выполните сегодняшнее задание и заработайте 50 баллов',
    start_challenge: 'Начать',
    live_session: 'Прямой Эфир',
    live_session_sub: 'Присоединяйтесь к живым вопросам и ответам с экспертами',
    join_now: 'Присоединиться',
    overall_progress: 'Общий Прогресс',
    keep_going: 'Так держать!',
    day_streak: 'Серия Дней',
    amazing: 'Невероятная последовательность!',
    points_earned: 'Заработано Баллов',
    this_week: '+350 на этой неделе',
    labs_completed: 'Лабы Завершены',
    labs_week: '+3 на этой неделе',
    certifications: 'Сертификаты',
    in_progress: 'В Процессе',
    ai_workforce: 'Программы ИИ',
    programs_schools: 'программ в 4 школах',
    view_all: 'Все Программы →',
    prof_greeting: 'Доброе утро',
    prof_analyzed: 'Я проанализировал ваш прогресс и подготовил индивидуальный план, чтобы вывести вас на новый уровень.',
    talk_prof: 'Поговорить с Проф. Дидье',
    talent_score_label: 'Talent Score™',
    rising_star: 'Восходящая Звезда',
    view_breakdown: 'Подробный Обзор →',
    top_skills: 'Ключевые Навыки',
    career_momentum: 'Карьерный Импульс',
    live_feed: 'В Эфире',
    future_ready: 'Вы готовы к будущему',
    future_sub: 'Продолжайте строить. Миру нужен ваш талант.',
    done_day: 'Готово на Сегодня',
    hours_employable: 'Часов до Трудоустройства',
    lessons: 'Уроки',
    start: 'Начать →',
    pro_member: 'Pro-участник',
    all_access: 'Полный Доступ™',
    overview: 'Обзор',
    my_academy: 'Моя Академия',
    my_career: 'Моя Карьера',
    talent: 'Talent Score™',
    certs: 'Сертификаты',
    career_tools: 'Карьерные Инструменты',
    portfolio: 'Моё Портфолио',
    labs: 'Лабы',
    community: 'Сообщество',
    leaderboard: 'Рейтинг',
    events: 'События',
    settings: 'Настройки',
    management: 'Aladiah Management',
    refer: 'Пригласи и Заработай',
    refer_sub: 'Приглашайте друзей и получайте премиум-награды',
    account: 'АККАУНТ',
    got_hired: 'только что устроился на работу как',
    completed: 'завершил',
    earned: 'получил',
    at: 'в',
    year: '/год',
    ago: 'назад',
    min: 'мин',
    new: 'Новый',
    ai_interview: 'ИИ-Интервью',
    practice_now: 'Практиковаться',
    resume_builder: 'Конструктор Резюме',
    optimize_cv: 'Оптимизировать Резюме',
    job_matches: 'Вакансии',
    new_jobs: 'Новые Вакансии',
    portfolio_analyzer: 'Анализатор Портфолио',
    get_feedback: 'Получить ИИ-Отзыв',
    salary_insights: 'Данные о Зарплатах',
    know_worth: 'Узнайте свою Ценность',
    countries_community: 'Стран в Сообществе',
    top_learners: 'Учащихся',
    nav_my_portal: 'Мой портал',
    nav_courses: 'Курсы',
    nav_talent_score: 'Talent Score™',
    nav_career: 'Карьера',
    nav_community: 'Сообщество',
    nav_resources: 'Ресурсы',
    rising: 'Растёт',
    continue_learning: 'Продолжить обучение →',
  },
};

export function overviewT(lang: string, key: string): string {
  return (OVERVIEW_STR[lang] || OVERVIEW_STR.en)[key] || OVERVIEW_STR.en[key] || key;
}
