import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { requireAdmin } from "../_shared/auth.ts";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const courseData = {
  "title": "AI Governance Professional",
  "description": "Master the frameworks, policies, and accountability structures that make AI responsible at enterprise scale. Cover EU AI Act, NIST AI RMF, ISO 42001, bias and fairness, audit methodologies, and board-level AI governance.",
  "translations": {"es": {"title": "AI Governance Professional", "description": "Master the frameworks, policies, and accountability structures that make AI responsible at enterprise scale. Cover EU AI Act, NIST AI RMF, ISO 42001, bias and fairness, audit methodologies, and board-level AI governance."}, "fr": {"title": "AI Governance Professional", "description": "Master the frameworks, policies, and accountability structures that make AI responsible at enterprise scale. Cover EU AI Act, NIST AI RMF, ISO 42001, bias and fairness, audit methodologies, and board-level AI governance."}, "de": {"title": "AI Governance Professional", "description": "Master the frameworks, policies, and accountability structures that make AI responsible at enterprise scale. Cover EU AI Act, NIST AI RMF, ISO 42001, bias and fairness, audit methodologies, and board-level AI governance."}, "zh": {"title": "AI Governance Professional", "description": "Master the frameworks, policies, and accountability structures that make AI responsible at enterprise scale. Cover EU AI Act, NIST AI RMF, ISO 42001, bias and fairness, audit methodologies, and board-level AI governance."}, "ar": {"title": "AI Governance Professional", "description": "Master the frameworks, policies, and accountability structures that make AI responsible at enterprise scale. Cover EU AI Act, NIST AI RMF, ISO 42001, bias and fairness, audit methodologies, and board-level AI governance."}, "ja": {"title": "AI Governance Professional", "description": "Master the frameworks, policies, and accountability structures that make AI responsible at enterprise scale. Cover EU AI Act, NIST AI RMF, ISO 42001, bias and fairness, audit methodologies, and board-level AI governance."}},
  "modules": [
  {"title": "Module 1: The AI Governance Landscape", "desc": "Understand why AI governance matters, the global regulatory environment, and how leading organizations are structuring their AI governance programs.", "lessons": [
    {"title": "1.1 Why AI Governance: The Stakes, The Incidents, The Imperative", "desc": "The real-world AI incidents that created demand for governance professionals, and the business case for taking AI governance seriously."},
    {"title": "1.2 The EU AI Act: The World's First Comprehensive AI Regulation", "desc": "Deep dive into the EU AI Act framework — risk tiers, obligations, conformity assessment, and what compliance actually requires in practice."},
    {"title": "1.3 NIST AI Risk Management Framework: The US Approach to AI Governance", "desc": "Master the NIST AI RMF — the US voluntary framework that is rapidly becoming the de facto standard for enterprise AI risk management globally."},
    {"title": "1.4 Bias, Fairness, and Discrimination: Technical and Legal Dimensions", "desc": "Master the technical definitions of algorithmic bias, the legal frameworks for AI discrimination, and practical bias testing methodologies for production AI systems."},
    {"title": "1.5 Building an AI Governance Program: Policies, Committees, and Culture", "desc": "Translate governance principles into an operating program — the policies, organizational structures, training curricula, and cultural change that make governance real."}
  ]},
  {"title": "Module 2: AI Risk Assessment — Frameworks, Methods, and Enterprise Practice", "desc": "Risk assessment is the foundation of AI governance. NIST AI RMF risk taxonomy, impact assessment methodologies, quantitative vs. qualitative risk scoring, bias audits, and the risk assessment practices at JPMorgan, IBM, and Salesforce.", "lessons": [
    {"title": "2.1 AI Risk Taxonomy: Mapping Harm Categories", "desc": "AI harms span safety (physical injury from autonomous systems), reliability (incorrect medical diagnoses), privacy (training data memorization), fairness (discriminatory credit decisions), security (adversarial attacks), accountability (unclear responsibility for AI decisions), and societal (misinformation, job displacement). IBM's AI Ethics Board taxonomy: 12 harm categories each with severity le"},
    {"title": "2.2 AI Impact Assessments: Methodology and Documentation", "desc": "AI Impact Assessments (AIAs) — also called Algorithmic Impact Assessments — evaluate potential harms before deployment. AIA methodology: system description (purpose, data, model type, decision scope), stakeholder mapping (who is affected, who benefits, who bears risk), harm identification (apply risk taxonomy, identify affected groups), probability and severity scoring, mitigation options analysis"},
    {"title": "2.3 Quantitative AI Risk Scoring: FAIR and Monte Carlo Methods", "desc": "Factor Analysis of Information Risk (FAIR) applied to AI: decompose AI risk into Loss Event Frequency (how often will the harm occur) × Loss Magnitude (how bad when it occurs). Quantitative inputs: historical incident data, red team testing results, threat intelligence on AI attacks. Monte Carlo simulation: run 10,000 scenarios with probability distributions for each risk factor — output is a prob"},
    {"title": "2.4 Algorithmic Bias Auditing: Methods and Tools", "desc": "Algorithmic bias audits assess whether AI systems produce discriminatory outcomes across protected groups. Bias audit methodology: define protected attributes (race, gender, age, disability, religion, national origin — varies by jurisdiction and use case), collect outcome data disaggregated by protected attribute, compute fairness metrics, compare to legal and ethical thresholds, document findings"},
    {"title": "2.5 Continuous Risk Monitoring: Drift, Incidents, and Ongoing Assessment", "desc": "AI risk is not static — risk profiles change as data drifts, deployment contexts change, and new attack techniques emerge. Continuous risk monitoring program: model performance monitoring (accuracy, bias metrics computed on production traffic monthly), data drift monitoring (PSI computed on input features weekly), incident tracking (catalog every production AI failure with impact assessment), thre"},
    {"title": "2.6 Enterprise AI Risk Governance: Committees, Escalation, and Risk Appetite", "desc": "Enterprise AI risk governance requires organizational structures that operationalize risk assessment findings. The AI Risk Committee: cross-functional (CTO, CISO, Chief Risk Officer, Chief Privacy Officer, General Counsel, business leaders), meeting cadence (monthly for operational risks, quarterly for strategic), decision authority (approve or reject new AI deployments above risk threshold, set A"},
    {"title": "2.7 Module 2 Assessment: AI Risk Assessment Practice", "desc": "Apply the full risk assessment methodology to a provided AI system (automated resume screening tool for a financial services firm): build the risk taxonomy, complete an AI Impact Assessment, compute bias metrics from provided outcome data, quantify top 3 risks using FAIR methodology, design continuous monitoring program, and document residual risks with governance recommendations."}
  ]},
  {"title": "Module 3: AI Ethics Frameworks — From Principles to Operational Practice", "desc": "AI ethics moves from abstract principles to operational constraints. Principle operationalization, ethics review boards, value alignment, the principal-agent problem in AI, and case studies from Google, Microsoft, and Accenture.", "lessons": [
    {"title": "3.1 AI Ethics Principles: The Global Landscape", "desc": "Since 2016, governments and organizations have published 160+ AI ethics frameworks (mapped by AlgorithmWatch's Global AI Ethics Index). Common principles: beneficence (AI should benefit humanity), non-maleficence (do no harm), autonomy (respect human agency and oversight), justice (fair outcomes, equitable access), explicability (transparency and accountability). Alignment across frameworks: the M"},
    {"title": "3.2 Operationalizing Ethics: From Principles to Technical Requirements", "desc": "The translation from abstract ethics principle to concrete technical requirement is the governance professional's core skill. Transparency principle → technical requirements: model cards documenting training data and limitations (required for all consumer-facing models), prediction explanations for individual decisions using SHAP or LIME values, confidence scores communicated with predictions, dis"},
    {"title": "3.3 AI Ethics Review Boards: Structure, Process, and Case Studies", "desc": "Ethics review boards provide governance oversight for AI deployments that raise significant ethical concerns. Ethics board models: internal (Google's now-disbanded Advanced Technology External Advisory Council, IBM's AI Ethics Board — internal executive committee), external (Salesforce's Office of Ethical and Humane Use — internal team with external advisory board), hybrid (Accenture's AI Ethics B"},
    {"title": "3.4 Value Alignment: Encoding Human Values in AI Systems", "desc": "Value alignment — ensuring AI systems pursue the values their designers and users intend — is the deepest challenge in AI governance. Sources of misalignment: reward hacking (RL agents find unintended shortcuts to maximize reward — boat racing agent that spins in circles collecting boost items instead of racing), specification gaming (AI fulfills the letter but not spirit of instructions), instrum"},
    {"title": "3.5 The Ethics of AI Automation: Displacement, Autonomy, and Human Dignity", "desc": "AI automation raises ethical questions beyond individual system deployment. Labor displacement: McKinsey estimates 400-800 million jobs could be displaced by automation by 2030, with 75-375 million requiring significant occupational transitions. The ethics of responsible deployment: consultation with affected workers before deployment, transition support and retraining programs, distribution of au"},
    {"title": "3.6 Ethics in Practice: Case Studies of Ethical Failures and Recoveries", "desc": "Learning from documented ethical failures accelerates governance maturity. Case 1 — Amazon Hiring Tool (2018): ML model trained on historical hiring data learned to penalize women's resumes — outcome of a biased historical distribution. Lesson: historical data encodes historical discrimination; bias auditing before deployment is mandatory. Case 2 — COMPAS Recidivism Algorithm (2016): ProPublica an"},
    {"title": "3.7 Module 3 Assessment: Ethics Framework Application", "desc": "Apply a complete ethics analysis to three AI use cases: (1) predictive policing in a major city, (2) AI-powered hiring screening for a Fortune 500 company, (3) LLM-powered mental health chatbot for teenagers. For each: identify applicable ethical principles, operationalize principles into technical requirements, design ethics review process, and document your recommendation (approve/reject/approve"}
  ]},
  {"title": "Module 4: AI Policy and Regulation — Global Landscape and Implementation", "desc": "AI regulation is accelerating globally. EU AI Act deep dive, US Executive Order on AI, China's AI regulations, UK's principles-based approach, and building the regulatory affairs function for AI-driven organizations.", "lessons": [
    {"title": "4.1 The Global AI Regulatory Landscape: Convergence and Divergence", "desc": "As of 2024, 60+ countries have active AI governance initiatives. Three regulatory models: rules-based (EU — specific requirements mapped to risk tiers, legally enforceable), principles-based (UK, Singapore — high-level principles with flexibility for industry implementation), sectoral (US — FDA regulates AI medical devices, CFPB regulates algorithmic credit decisions, EEOC regulates AI hiring tool"},
    {"title": "4.2 EU AI Act Deep Dive: High-Risk Requirements and Implementation Timeline", "desc": "The EU AI Act's four risk tiers and their technical governance requirements. Unacceptable risk (prohibited August 2024): social scoring, real-time biometric in public spaces, manipulation of vulnerable groups, subliminal techniques. High-risk AI (regulated February 2025 onwards): recruitment and HR, credit scoring, education assessment, law enforcement, biometric identification, critical infrastru"},
    {"title": "4.3 US AI Governance: Executive Order, NIST AI RMF, and Sectoral Regulation", "desc": "The US has not passed comprehensive AI legislation but has significant regulatory activity. Executive Order on AI (October 2023, Biden administration): mandates federal agencies use NIST AI RMF, establishes AI Safety Institute at NIST, requires safety testing for dual-use foundation models, directs agencies to develop sector-specific guidance. NIST AI RMF (2023): voluntary framework structured aro"},
    {"title": "4.4 China's AI Regulations: Generative AI Rules and Algorithmic Recommendations", "desc": "China has moved faster than any other jurisdiction on specific AI regulations. Algorithm recommendation provisions (effective March 2022): service providers must disclose when algorithmic recommendations are used, provide mechanisms to opt out, prohibit addiction-inducing algorithms for minors, prohibit using algorithms to impose different prices on users (anti-discriminatory pricing). Deep synthe"},
    {"title": "4.5 Building the AI Regulatory Affairs Function", "desc": "Enterprise AI regulatory affairs requires dedicated organizational capacity. The AI regulatory affairs team structure: regulatory counsel (interprets regulations and advises on compliance obligations), technical compliance engineers (implement technical requirements for documented regulations), policy affairs specialists (monitor emerging regulations, engage with regulators), and governance progra"},
    {"title": "4.6 AI Liability: Product Liability, Professional Liability, and Insurance", "desc": "When AI systems cause harm, who is legally responsible? EU AI Liability Directive (proposed 2022): reverses burden of proof for high-risk AI — victims get presumption of causality if non-disclosure of evidence, providers must disclose technical documentation for liability claims. Product liability framework: AI as product — manufacturer liable for design defects (foreseeable misuse not addressed),"},
    {"title": "4.7 Module 4 Assessment: Regulatory Compliance Plan", "desc": "Develop a regulatory compliance plan for a multinational financial services company deploying AI-powered loan origination in the EU, US, and Singapore. Map the AI system against EU AI Act high-risk requirements, US CFPB algorithmic credit rules, and MAS (Monetary Authority of Singapore) FEAT principles. Identify the most restrictive requirements, design unified compliance architecture, document th"}
  ]},
  {"title": "Module 5: Explainability and Transparency — Technical Methods and Governance Requirements", "desc": "Explainability is required by regulation and demanded by users. SHAP, LIME, attention visualization, model cards, algorithmic transparency reports, and designing explainability systems for high-stakes AI applications.", "lessons": [
    {"title": "5.1 Why Explainability Matters: Legal, Ethical, and Operational Imperatives", "desc": "Explainability serves four distinct governance purposes. Legal compliance: GDPR Article 22 right to explanation for automated decisions, EU AI Act transparency requirements for high-risk AI, ECOA adverse action notices for credit decisions (must specify factors). Trust building: users trust AI systems they understand — IBM's AI explainability consumer research found 82% of consumers want explanati"},
    {"title": "5.2 SHAP: Shapley Values for Model-Agnostic Explanation", "desc": "SHAP (SHapley Additive exPlanations, Lundberg & Lee, 2017) is the most widely used explanation method in production. Shapley values: from cooperative game theory — each feature's contribution is its average marginal contribution across all possible feature coalitions. SHAP properties: efficiency (feature contributions sum to prediction minus baseline), symmetry (identical features get identical co"},
    {"title": "5.3 LIME and Counterfactual Explanations for Business Users", "desc": "LIME (Local Interpretable Model-agnostic Explanations, Ribeiro et al., 2016): fit a simple interpretable model (linear regression or decision tree) to a small neighborhood around the prediction point — the simple model approximates the complex model locally. LIME strengths: works with any model, produces human-readable feature importance for the local prediction, text and image explainability (whi"},
    {"title": "5.4 Model Cards and Datasheets: Transparency Documentation Standards", "desc": "Model cards (Mitchell et al., Google, 2019) are structured model documentation covering: model details (architecture, training), intended uses and out-of-scope uses, factors (groups and conditions affecting performance), metrics (evaluation results with disaggregated analysis by subgroup), training and evaluation data, quantitative analyses (performance visualizations), ethical considerations, and"},
    {"title": "5.5 Algorithmic Transparency Reports and Public Disclosure", "desc": "Algorithmic transparency reports communicate AI governance practices to external stakeholders — customers, regulators, civil society, and investors. Report structure (emerging standard): inventory of AI systems (what AI does the company use and for what purposes), governance framework (how decisions are made about AI deployment), bias audit results (aggregate findings without revealing proprietary"},
    {"title": "5.6 Explainability for Deep Learning and LLMs", "desc": "Traditional explainability methods (SHAP, LIME) work well for tabular models but have limitations for deep learning and LLMs. Image explanation: Grad-CAM (Gradient-weighted Class Activation Mapping) highlights image regions that drove classification — used in medical imaging AI to show which tissue features influenced the diagnosis. NLP explanation for traditional models: SHAP for text classifiers"},
    {"title": "5.7 Module 5 Assessment: Explainability Architecture Design", "desc": "Design the explainability architecture for a credit scoring system used by a US bank: select appropriate explanation methods (SHAP for regulatory adverse action notices, LIME for customer-facing explanations, counterfactuals for actionable guidance), design the explanation data pipeline (compute and log explanations for every prediction), create the model card template, and write the algorithmic t"}
  ]},
  {"title": "Module 6: AI Governance Program Design — Building the Enterprise Practice", "desc": "Designing and operating a mature AI governance program. Governance operating models, policy development, stakeholder management, governance technology stack, and building the AI governance function from startup to enterprise scale.", "lessons": [
    {"title": "6.1 AI Governance Operating Models: Centralized, Federated, and Hybrid", "desc": "Three AI governance operating models with different tradeoffs. Centralized model: a central AI governance team owns all AI deployment approvals, maintains all AI policy, conducts all bias audits — high control, low scalability, creates bottleneck at high AI deployment volume. Federated model: governance responsibilities distributed to business units, central function sets standards and provides to"},
    {"title": "6.2 AI Policy Development: Frameworks, Processes, and Maintenance", "desc": "AI governance policies are the codified rules that guide AI development and deployment decisions. Policy hierarchy: AI principles (high-level, stable, public) → AI standards (specific requirements, internal) → AI guidelines (implementation guidance, practical) → AI procedures (step-by-step processes). Policy development process: stakeholder consultation (legal, compliance, technical, business, eth"},
    {"title": "6.3 AI Governance Technology: GRC Platforms and AI-Specific Tooling", "desc": "Governance, Risk, and Compliance (GRC) platforms extended for AI governance provide workflow automation and audit trail management. AI-specific GRC capabilities needed: AI system inventory (catalog of all AI systems with metadata), AIA workflow management (route assessments through approval process with tracking), policy compliance tracking (map each AI system to applicable policies with complianc"},
    {"title": "6.4 Stakeholder Engagement: Boards, Executives, and External Parties", "desc": "AI governance professionals must communicate effectively with diverse stakeholders who have different mental models and risk tolerances. Board of directors: fiduciary responsibility for material AI risks — report on AI risk exposure, regulatory developments, and governance investment in quarterly board materials. Framing: financial risk exposure, reputational risk scenarios, competitor regulatory "},
    {"title": "6.5 Third-Party AI Risk: Vendor Management and Open-Source Governance", "desc": "Most enterprise AI deployments incorporate third-party components — foundation models, open-source libraries, AI SaaS tools — each introducing risk that the enterprise is ultimately responsible for. Third-party AI risk management program: pre-contract due diligence (request vendor AI governance documentation, assess bias audit results, review incident history), contractual risk transfer (represent"},
    {"title": "6.6 Measuring AI Governance Program Effectiveness", "desc": "AI governance programs must demonstrate value to sustain investment. Governance program metrics: coverage (percentage of AI systems with completed AIAs and active monitoring), velocity (average time from AI development start to governance approval — governance should accelerate, not block), quality (percentage of AIAs that identify and mitigate material risks before incidents), incident prevention"},
    {"title": "6.7 Module 6 Assessment: AI Governance Program Design", "desc": "Design the complete AI governance program for a Series B fintech with 50 ML engineers, 30 production AI systems, and upcoming EU market entry. Define operating model, policy library (5 core policies), governance technology stack, AIA process with stakeholder roles, third-party AI vendor assessment process, board reporting structure, and 18-month program buildout roadmap with quarterly milestones a"}
  ]},
  {"title": "Module 7: AI Fairness and Non-Discrimination — Law, Measurement, and Remediation", "desc": "AI fairness is simultaneously a legal requirement and an ethical imperative. Disparate impact doctrine, intersectional fairness, fairness-accuracy tradeoffs, bias remediation techniques, and enforcement actions from the CFPB, EEOC, and EU.", "lessons": [
    {"title": "7.1 Legal Framework: Disparate Impact Doctrine Applied to AI", "desc": "The disparate impact doctrine (Griggs v. Duke Power, US Supreme Court, 1971) prohibits facially neutral practices that disproportionately harm protected groups without business necessity. Applied to AI: if an employment AI tool selects candidates from protected groups at a rate less than 80% of the highest-selected group (4/5ths rule), this constitutes prima facie disparate impact — the employer m"},
    {"title": "7.2 Fairness Metrics: Technical Definitions and Legal Alignment", "desc": "The impossibility theorem (Chouldechova, 2017; Kleinberg et al., 2016): you cannot simultaneously satisfy Demographic Parity, Equalized Odds, and Calibration when base rates differ across groups — governance professionals must understand this and make explicit tradeoffs. Metric definitions: Demographic Parity (equal positive prediction rates regardless of group membership), Equalized Odds (equal t"},
    {"title": "7.3 Intersectional Fairness: Beyond Single-Dimension Analysis", "desc": "Traditional fairness analysis examines one protected attribute at a time — this misses intersectional harms affecting people at the intersection of multiple protected groups. Intersectionality (Kimberlé Crenshaw, 1989): legal and social frameworks that consider how different aspects of identity overlap and interact to create unique forms of discrimination. Applied to AI: a hiring model may appear "},
    {"title": "7.4 Bias Sources and Remediation Techniques", "desc": "Bias enters AI systems at every lifecycle stage. Pre-processing bias (in training data): historical bias (data reflects past discrimination), sampling bias (underrepresentation of minority groups), label bias (human labels encode human biases). Pre-processing remediation: resampling (oversample underrepresented groups), reweighting (assign higher weight to minority group examples), relabeling (hum"},
    {"title": "7.5 Enforcement Actions: Regulatory Cases and Consent Orders", "desc": "Regulatory enforcement actions for AI discrimination are accelerating. CFPB enforcement: Upstart Network (2023) examination found no disparate impact in their AI underwriting model — demonstrating that proactive bias auditing can withstand regulatory scrutiny; Apple Card (2019) investigated for gender discrimination in credit limit setting after viral reports of disparate treatment. EEOC enforceme"},
    {"title": "7.6 Fairness in Generative AI: Content Moderation and Representation", "desc": "Generative AI systems have fairness dimensions beyond traditional ML model bias. Representation bias in generative models: early image generation models (DALL-E 2, Midjourney) defaulted to Western, white, male representations for neutral prompts — systematic underrepresentation of diverse groups. Measurement: CLIP-based gender and race classifiers applied to large prompt samples to quantify demogr"},
    {"title": "7.7 Module 7 Assessment: Fairness Audit and Remediation Plan", "desc": "Conduct a complete fairness audit of a provided employment screening AI system: select appropriate fairness metrics with legal rationale, compute metrics from provided outcome data, identify disparate impact findings that exceed legal thresholds, apply three bias remediation techniques and evaluate effectiveness, document residual risk, and write the compliance report for the EEOC annual review in"}
  ]},
  {"title": "Module 8: AI Accountability and Human Oversight — Implementation and Systems Design", "desc": "Accountability ensures someone is responsible when AI systems cause harm. Human-in-the-loop design, meaningful oversight vs. rubber stamping, accountability attribution in complex AI systems, and oversight mechanisms for autonomous AI agents.", "lessons": [
    {"title": "8.1 The Accountability Gap in AI: Why Traditional Frameworks Fail", "desc": "Traditional accountability frameworks assume a clear chain from action to responsible actor. AI systems create accountability gaps: the algorithm gap (algorithmic processes that are too complex for human understanding — can you be accountable for what you don't understand?), the many hands problem (multiple actors contribute to AI system development and deployment — no single responsible party), t"},
    {"title": "8.2 Human-in-the-Loop Design: Meaningful Oversight vs. Rubber Stamping", "desc": "EU AI Act Article 14 requires human oversight for high-risk AI — but human presence without meaningful ability to intervene is compliance theater. Criteria for meaningful human oversight: comprehension (the human understands enough to make an informed decision), authority (the human has actual authority to override or reject the AI recommendation), accountability (the human is accountable for the "},
    {"title": "8.3 Accountability Assignment: Roles, Responsibilities, and RACI", "desc": "Clear pre-assignment of accountability for AI system outcomes is the foundation of an effective governance program. The AI accountability RACI: Responsible (AI development team — builds and tests the system), Accountable (business owner — ultimately answers for outcomes), Consulted (AI governance team, legal, compliance — review before deployment), Informed (affected stakeholders, users, impacted "},
    {"title": "8.4 Oversight for AI Agents: Control Problems in Autonomous Systems", "desc": "AI agents that take real-world actions — browsing the web, executing code, sending emails, making purchases — require oversight mechanisms not needed for predictive models. Oversight requirements for agentic AI: pre-execution review (for irreversible or high-impact actions, show the proposed action and require approval), post-execution monitoring (log all actions with ability to review and flag an"},
    {"title": "8.5 Audit Trails and Recordkeeping for AI Accountability", "desc": "An audit trail is the technical foundation of accountability — without it, accountability is aspirational rather than operational. AI audit trail requirements: prediction inputs (the exact feature values the model used to make a prediction), model version (which version of the model made the prediction), prediction outputs (the model's recommendation and confidence), human decision (what decision "},
    {"title": "8.6 Accountability in Procurement: Vendor Contracts and SLAs for AI", "desc": "When enterprises procure AI systems, accountability must be contractually established before deployment. AI vendor contract requirements: performance SLAs (accuracy, availability, latency — with remedies for breach), fairness warranties (vendor represents model meets fairness standards, provides audit rights), indemnification (who is responsible for regulatory fines arising from AI system failures"},
    {"title": "8.7 Module 8 Assessment: Accountability Architecture Design", "desc": "Design the complete accountability architecture for a healthcare AI system that provides diagnostic recommendations to physicians: meaningful oversight design (what information, time allocation, interface design ensures genuine physician review), accountability RACI for five failure categories, audit trail schema with retention requirements, agent control mechanisms if the AI also places orders, v"}
  ]},
  {"title": "Module 9: AI Governance in Regulated Industries — Finance, Healthcare, and Critical Infrastructure", "desc": "Regulated industries face sector-specific AI governance requirements on top of general frameworks. AI governance for financial services, healthcare AI under FDA, AI in critical infrastructure, and how leading regulated enterprises have built governance programs.", "lessons": [
    {"title": "9.1 AI in Financial Services: SR 11-7, Model Risk Management, and CFPB Guidance", "desc": "Financial services AI is governed by the most mature regulatory framework for algorithmic systems. SR 11-7 (Federal Reserve, 2011): supervisory guidance on model risk management — requires model validation (independent review of model development), model inventory (register of all models with risk ratings), ongoing monitoring (model performance tracking), and governance documentation. Model risk m"},
    {"title": "9.2 Healthcare AI: FDA Regulation of SaMD and Clinical Decision Support", "desc": "The FDA regulates AI as Software as a Medical Device (SaMD) when software intended to diagnose, treat, cure, mitigate, or prevent disease meets the device definition. Regulatory pathways: 510(k) clearance (most common — demonstrate substantial equivalence to a predicate device), De Novo (for novel device types with moderate risk), PMA (Pre-Market Approval — highest risk devices like AI replacing p"},
    {"title": "9.3 AI in Critical Infrastructure: NERC CIP, CISA, and Operational Technology Security", "desc": "AI systems integrated with critical infrastructure (power grids, water systems, transportation) face the highest-consequence failure scenarios. NERC CIP (Critical Infrastructure Protection) standards apply to the North American bulk electric system — AI systems used for grid management must meet CIP requirements for cybersecurity, access control, and incident response. CISA AI security guidance (2"},
    {"title": "9.4 Insurance and AI: Underwriting Algorithms, Pricing, and State Regulation", "desc": "Insurance AI governance operates under a complex state-by-state regulatory patchwork in the US. Rate and form filings: AI-based pricing models must be filed with state insurance regulators in most states — the model is reviewed for actuarial soundness and non-discriminatory pricing. Proxy discrimination in insurance: factors correlated with protected attributes (zip code correlating with race, cre"},
    {"title": "9.5 AI Governance for Public Sector and Government AI", "desc": "Government AI deployments have special governance obligations because they affect citizens' rights and access to public services. Legal constraints: government AI decisions affecting individual rights (benefits, enforcement, housing) may trigger due process requirements (notice, opportunity to respond, right to human review). Transparency requirements: FOIA applies to government AI systems — algor"},
    {"title": "9.6 Emerging Sector Challenges: Autonomous Vehicles, Hiring AI, and Education Technology", "desc": "Three sectors with rapidly evolving AI governance requirements. Autonomous vehicles: SAE Levels 0-5 autonomy, NHTSA AV guidance (voluntary in US vs. type approval in EU), safety case documentation, black box data recorders (NHTSA requires EDR for AV), liability for AV collisions (40+ states have passed AV liability legislation). Hiring AI: proliferating state and city laws — NYC Local Law 144 (ann"},
    {"title": "9.7 Module 9 Assessment: Sector-Specific Governance Plan", "desc": "Develop the AI governance plan for a healthcare fintech company launching an AI-powered medical credit product (financing for healthcare expenses, incorporating medical history as a factor). Map applicable regulations (CFPB ECOA/adverse action, FDA CDS vs. SaMD analysis, state insurance regulations, HIPAA for medical data). Design the governance framework for a system at the intersection of financ"}
  ]},
  {"title": "Module 10: AI Governance Career — Leadership, Strategy, and the Future of the Field", "desc": "AI governance is one of the fastest-growing professional disciplines. Career paths from practitioner to Chief AI Ethics Officer, building governance influence without authority, the future of AI governance as a field, and your 5-year career roadmap.", "lessons": [
    {"title": "10.1 The AI Governance Profession: Roles, Titles, and Organizational Positioning", "desc": "AI governance as a distinct profession emerged between 2018-2022, accelerated by GDPR enforcement and the proliferation of AI ethics incidents. Current role landscape: AI Ethics Manager (operational, focuses on AIA process, bias auditing), AI Governance Engineer (technical, implements monitoring and compliance infrastructure), AI Policy Specialist (regulatory, monitors and interprets regulations),"},
    {"title": "10.2 Influencing Without Authority: The Governance Professional's Core Skill", "desc": "AI governance professionals often have oversight authority without direct control over AI development decisions — influence is the primary tool. Influence strategies: building credibility (demonstrate deep technical and regulatory knowledge — governance advice only works if it's trusted as accurate), building relationships (the governance professional who participates in product design from the st"},
    {"title": "10.3 Building an AI Governance Center of Excellence", "desc": "A Center of Excellence (CoE) provides shared governance capabilities that individual business units cannot maintain independently. AI Governance CoE services: AIA facilitation (CoE team leads the assessment process), bias audit capability (CoE maintains bias testing infrastructure and expertise), policy library management (CoE maintains and updates policy library with regulatory tracking), trainin"},
    {"title": "10.4 AI Governance Strategy: 3-Year Roadmap Development", "desc": "Strategic AI governance programs require multi-year planning aligned with regulatory timelines and organizational maturity. Governance maturity assessment: baseline against a governance maturity model (Level 1: reactive, Level 3: systematic, Level 5: optimized). Gap analysis: identify gaps against current regulatory requirements, anticipated regulatory requirements (EU AI Act 2026, state laws 2024"},
    {"title": "10.5 The Future of AI Governance: AGI, Autonomous Systems, and Governance at Scale", "desc": "AI governance as a field is evolving rapidly to address increasingly capable AI systems. Near-term governance challenges (2025-2027): agentic AI oversight (how do you govern AI agents that take thousands of actions per day?), foundation model governance (regulating base models that power thousands of downstream applications), and AI-generated disinformation at scale. Medium-term challenges (2027-2"},
    {"title": "10.6 Certifications, Education, and Professional Development", "desc": "AI governance is building its professional infrastructure. Current certifications: CIPP/E (IAPP Certified Information Privacy Professional — Europe, highly relevant for GDPR/EU AI Act compliance), CIPT (Certified Information Privacy Technologist — technical privacy for AI engineers), IEEE Certified Ethicist (early stage, limited recognition), ISACA CGEIT (Governance of Enterprise IT — applicable t"},
    {"title": "10.7 Final Capstone: AI Governance Strategy Presentation", "desc": "Design and present the 3-year AI governance strategy for a global technology company with 100 production AI systems, 5,000 employees in 20 countries, and upcoming EU AI Act compliance deadlines. Deliverable: executive presentation (10 slides) covering current governance maturity assessment, regulatory compliance gap analysis (EU AI Act, GDPR intersection, sector-specific regulations), proposed gov"}
  ]}
]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    // SECURITY: founder/admin only — this seeder writes content with the service role.
    const __adminCheck = await requireAdmin(req);
    if (__adminCheck instanceof Response) return __adminCheck;
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const COURSE_TITLE = courseData.title;
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({ title: courseData.title, description: courseData.description, is_published: true, translations: courseData.translations }).select().single();
    if (ce) throw ce;
    let chaptersCreated = 0; let videosCreated = 0;
    for (let mi = 0; mi < courseData.modules.length; mi++) {
      const mod = courseData.modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: mod.title, description: mod.desc, order_index: mi, translations: {} }).select().single();
      if (che) throw che; chaptersCreated++;
      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = les.title + "\n\n" + les.desc + "\n\nThis is a world-class lesson from Aladiah Academy's professional certification program. Prof. Didier teaches this with production depth, real case studies, and implementation guidance. Module context: " + mod.title + ". " + mod.desc;
        const trans = { en:{title:les.title,transcript}, es:{title:les.title,transcript}, fr:{title:les.title,transcript}, de:{title:les.title,transcript}, zh:{title:les.title,transcript}, ar:{title:les.title,transcript}, ja:{title:les.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: les.title, description: les.desc, order_index: li, translations: trans }).select().single();
        if (ve) throw ve; videosCreated++;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: "What production expertise does this lesson build?", scenario_context: "Applying this in a professional role.", options: [les.desc.substring(0,120)+"...", "Only theoretical background", "Covered elsewhere", "Optional content"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: "Which real-world organizations' practices are referenced?", scenario_context: "Grounding knowledge in production reality.", options: ["Leading global organizations — case studies ground every lesson in production reality", "No real organizations referenced", "Only academic examples", "Only startups"], correct_answer_index: 0, explanation: "Every lesson uses production case studies from world-class organizations.", order_index: 1 },
        ]);
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: "What expert-level competency does this module develop?", scenario_context: "Module completion assessment.", options: [mod.desc.substring(0,140)+"...", "Only introductory familiarity", "Theoretical knowledge only", "Not career-relevant"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "What career level does mastery of this module support?", scenario_context: "Professional development planning.", options: ["Senior professional and leadership roles in the fastest-growing AI specialization globally", "Entry-level only", "Academic roles only", "No direct career value"], correct_answer_index: 0, explanation: "Each module builds expertise directly valued in high-compensation AI professional roles.", order_index: 1 },
      ]);
    }
    return new Response(JSON.stringify({ message: courseData.title + " — 10-module world-class version seeded", courseId: course.id, modules: chaptersCreated, lessons: videosCreated }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
