import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { CalendarDays, Sparkles } from 'lucide-react';
import { DailyCommandReport, UrgencyLevel } from '@/types/agentReports';

const URGENCY_STYLES: Record<UrgencyLevel, string> = {
  normal: 'bg-green-100 text-green-700 border-green-200',
  elevated: 'bg-amber-100 text-amber-700 border-amber-200',
  high: 'bg-orange-100 text-orange-700 border-orange-200',
  critical: 'bg-red-100 text-red-700 border-red-200',
};

interface DailyReportCardProps {
  report: DailyCommandReport;
}

/** The executive-summary banner at the top of the Command Center. */
const DailyReportCard = ({ report }: DailyReportCardProps) => {
  const urgency = (report.urgency_level || 'normal') as UrgencyLevel;
  return (
    <Card className="border-primary/20">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <CardTitle className="flex items-center gap-2 text-base">
            <Sparkles className="w-4 h-4 text-primary" />
            Daily Executive Summary
          </CardTitle>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="gap-1 text-xs font-normal">
              <CalendarDays className="w-3 h-3" />
              {report.report_date}
            </Badge>
            <Badge className={`text-xs border ${URGENCY_STYLES[urgency]}`}>
              {urgency.toUpperCase()}
            </Badge>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <p className="text-sm leading-relaxed text-foreground/90">
          {report.executive_summary || 'No summary available.'}
        </p>
        <p className="text-[11px] text-muted-foreground mt-3">
          Generated by {report.agent_name}
        </p>
      </CardContent>
    </Card>
  );
};

export default DailyReportCard;
