// Generated from supabase/functions on 2026-07-02 — evidence for first-generation genomes.
export const SHADOW_SEEDERS: { slug: string; publishes: boolean; destructive: boolean; classification: 'legacy' | 'unknown' }[] = [
  { slug: 'seed-ai-agent-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-agent-engineer-course', publishes: true, destructive: false, classification: 'unknown' },
  { slug: 'seed-ai-agent-engineer-v2', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-auditor', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-business-analyst', publishes: false, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-business-operations', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-cloud-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-cloud-engineer-course', publishes: true, destructive: false, classification: 'unknown' },
  { slug: 'seed-ai-cloud-engineer-v2', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-compliance-officer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-data-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-devops-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-enterprise-architect', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-ethics-specialist', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-experience-architect', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-governance-professional', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-governance-professional-course', publishes: true, destructive: false, classification: 'unknown' },
  { slug: 'seed-ai-mlops-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-platform-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-pm-course', publishes: true, destructive: true, classification: 'legacy' },
  { slug: 'seed-ai-policy-designer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-product-manager', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-product-manager-course', publishes: true, destructive: false, classification: 'unknown' },
  { slug: 'seed-ai-program-manager', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-risk-manager', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-sales-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-security-engineer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-security-engineer-v2', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-solutions-architect', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-solutions-consultant', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-transformation-manager', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-ux-designer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-ai-workflow-designer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-all-quizzes', publishes: false, destructive: false, classification: 'legacy' },
  { slug: 'seed-business-analysis-course', publishes: true, destructive: true, classification: 'legacy' },
  { slug: 'seed-conversation-designer', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-cybersecurity-course', publishes: true, destructive: true, classification: 'legacy' },
  { slug: 'seed-data-analytics-course', publishes: true, destructive: true, classification: 'legacy' },
  { slug: 'seed-devops-course', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-human-ai-interaction-specialist', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-pm-professional-course', publishes: true, destructive: true, classification: 'legacy' },
  { slug: 'seed-responsible-ai-specialist', publishes: true, destructive: true, classification: 'unknown' },
  { slug: 'seed-scrum-course', publishes: true, destructive: false, classification: 'legacy' },
  { slug: 'seed-solution-architect-course', publishes: true, destructive: true, classification: 'unknown' },
];

export const OPERATIONAL_EDGE_FUNCTIONS: string[] = [
  'admin-analytics',
  'ai-grading',
  'ai-proxy',
  'create-checkout',
  'elevenlabs-conversation-token',
  'enrollment-chat',
  'generate-lesson-audio',
  'generate-question-bank',
  'generate-visuals',
  'get-quiz-questions',
  'get-student-recap',
  'handle-payment-webhook',
  'interview-simulator',
  'lesson-qa',
  'recompute-learning-profiles',
  'scrum-simulation',
  'send-assignment-reminder',
  'send-email',
  'send-payment-reminder',
  'send-study-reminders',
  'send-weekly-report',
  'send-welcome-email',
  'student-assistant',
  'submit-quiz',
  'translate-content',
];
