import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const COURSE_TITLE = "AI Cloud Engineer";

const modules = [
  {
    title: "Module 1: Cloud Foundations — Architecture, Economics, and the AI Engineer's Mindset",
    desc: "The mental models and economic principles behind every great cloud decision. Inspired by Google Cloud's Associate Cloud Engineer foundations and AWS's Well-Architected Framework — covering the 6 pillars, pets vs. cattle, immutable infrastructure, distributed systems fallacies, and the FinOps discipline that keeps AI workloads economically sustainable.",
    lessons: [
      { title: "1.1 What Cloud Computing Actually Is: Virtualization, Hypervisors, and the Economics That Changed Everything", desc: "From bare metal to VMs to containers — how virtualization enabled the cloud economics model. The five NIST characteristics of cloud computing, the three service models (IaaS, PaaS, SaaS), and why Google, Amazon, and Microsoft invest hundreds of billions in data centers. Real case: how Netflix moved from physical data centers to AWS in 7 years, eliminated their last data center in 2016, and gained the ability to scale from 0 to 1M concurrent users in minutes — impossible with owned infrastructure." },
      { title: "1.2 The Well-Architected Framework: Six Pillars Applied to AI Workloads", desc: "AWS Well-Architected Framework + Google Cloud Architecture Framework combined. Operational Excellence (deployment automation, observability), Security (defense-in-depth, least privilege), Reliability (design for failure, automatic recovery), Performance Efficiency (selecting the right compute for AI), Cost Optimization (eliminate waste, right-size), Sustainability (energy efficiency for GPU training). Each pillar examined through the lens of production AI systems at Netflix, Stripe, and Airbnb." },
      { title: "1.3 Pets vs. Cattle, Immutable Infrastructure, and Cloud-Native Design Principles", desc: "The most important mental model shift in cloud engineering — from maintaining unique servers to orchestrating disposable compute. Immutable infrastructure (Chad Fowler, 2013), the cattle model for GPU training fleets, auto-scaling groups as cattle herds, and why every manual SSH into a production server is a governance failure. Case study: how Etsy's 2012 infrastructure transformation from 'pets' to 'cattle' reduced deployment time from hours to minutes and became the model for cloud-native engineering." },
      { title: "1.4 Distributed Systems Fallacies and Why They Matter for AI", desc: "Peter Deutsch and James Gosling's 8 fallacies (1994) that still cause production incidents today. The network is reliable: how packet loss corrupts streaming ML inference. Latency is zero: how inter-AZ latency (1-2ms) compounds across a 10-step AI pipeline. Bandwidth is infinite: why moving 50TB training datasets between regions requires architectural planning. Topology doesn't change: what happens when an AZ goes down during distributed training. Each fallacy with a real AI production incident." },
      { title: "1.5 FinOps for AI: Unit Economics, Cost Attribution, and the 96% Cloudflare Case Study", desc: "FinOps Foundation's Inform-Optimize-Operate cycle applied to AI workloads. Computing cost-per-prediction, cost-per-training-run, and cost-per-model-version. How Cloudflare achieved 96% AI inference cost reduction through worker-based batching and edge deployment. GPU utilization economics: why a p3.8xlarge at 30% GPU utilization is 3.3x more expensive than necessary. Building cost dashboards with AWS Cost Explorer and GCP Billing." },
      { title: "1.6 AWS vs. GCP vs. Azure: Choosing Your AI Cloud Platform", desc: "Hyperscaler comparison across five dimensions: AI/ML services maturity (SageMaker vs. Vertex AI vs. Azure ML), GPU availability and pricing (A100, H100, TPU v4), global network performance, pricing models, and ecosystem lock-in risk. Real enterprise decision frameworks: when to go single-cloud (90% of enterprises), when multi-cloud is warranted (regulatory data residency, best-of-breed services), and how to architect for portability using open standards (Kubernetes, ONNX, OpenTelemetry)." },
    ]
  },
  {
    title: "Module 2: Hands-On Google Cloud Infrastructure — The GCP Engineer's Complete Toolkit",
    desc: "Google Cloud from first principles through production patterns. Covering Compute Engine, Cloud Storage, VPC networking, Cloud SQL, BigQuery, Cloud Run, and GKE — inspired by the Google Cloud Associate Cloud Engineer specialization's 50+ hours of content, enriched with AI-specific use cases and production incident post-mortems.",
    lessons: [
      { title: "2.1 Google Cloud Console, gcloud CLI, and Project Architecture", desc: "GCP's resource hierarchy (Organization → Folders → Projects → Resources), IAM inheritance and policy propagation, the gcloud CLI for every production operation, Cloud Shell for zero-setup engineering, and project architecture patterns for AI teams (separate projects for dev/staging/prod, shared VPC for network centralization). Case study: how a fintech startup used GCP project architecture to achieve SOC2 compliance in 6 months." },
      { title: "2.2 Compute Engine: VMs, Custom Machine Types, and Preemptible GPUs for Training", desc: "GCE machine families (N2, C2, M2, A2 for GPU), custom machine types for right-sizing training workloads, Preemptible (86% cheaper) and Spot VMs for interruptible training jobs, live migration for zero-downtime maintenance, startup scripts for automated configuration, and instance templates + managed instance groups for auto-scaling AI serving fleets. Real benchmarks: training a ResNet-50 on 8x A100 vs. 4x V100 — cost and time tradeoffs." },
      { title: "2.3 Cloud Storage: Objects, Buckets, and the Data Lake Foundation for AI", desc: "GCS storage classes (Standard, Nearline, Coldline, Archive) and lifecycle policies for training data cost management, uniform bucket-level access vs. ACLs, Object Versioning for training dataset reproducibility, CMEK encryption with Cloud KMS, Signed URLs for time-limited model artifact access, Transfer Service for petabyte-scale data migration, and FUSE mount for training jobs that expect filesystem access. Case study: Spotify's PetaBytes of audio training data on GCS." },
      { title: "2.4 Cloud SQL and Firestore: Managed Databases for AI Application State", desc: "Cloud SQL (PostgreSQL, MySQL) for ML metadata and experiment tracking, read replicas for analytics workloads, point-in-time recovery for audit trails, automatic backups with configurable retention. Firestore for real-time AI application state (low-latency user context, session management), security rules, composite indexes for ML feature queries, and the Datastore vs. Firestore decision. Case study: how a recommendation engine uses Firestore for real-time user preference state." },
      { title: "2.5 BigQuery: Petabyte Analytics for ML Feature Engineering and Training Data", desc: "BigQuery's serverless architecture (Dremel paper, 2010), columnar storage with automatic clustering, partitioned tables for time-series ML features (partition pruning = 100x query cost reduction), ML features via BigQuery ML (train models directly in SQL), INFORMATION_SCHEMA for cost governance, Authorized Views for secure data sharing across teams, and integration with Vertex AI for feature engineering pipelines." },
      { title: "2.6 Cloud Run and Cloud Functions: Serverless AI Inference Patterns", desc: "Cloud Run for containerized ML inference (CPU and GPU instances, min-instances for cold start elimination, concurrency tuning for LLM serving), Cloud Functions for event-triggered ML pipelines (trigger retraining when new data arrives in GCS), Eventarc for event routing, Cloud Scheduler for batch inference jobs, and the serverless vs. Kubernetes decision framework for different AI workload profiles." },
      { title: "2.7 Module 2 Lab: Build a Complete GCP Data and Serving Pipeline", desc: "Hands-on project: provision Compute Engine training instance, store training data in GCS, train a model, store artifacts in GCS, deploy inference endpoint on Cloud Run, set up Cloud Monitoring alerts, and configure lifecycle policies for cost management." },
    ]
  },
  {
    title: "Module 3: VPC Architecture, Networking, and Zero-Trust Security for AI",
    desc: "Production network design drawing from Google Cloud's networking specialization, AWS's Advanced Networking certification content, and the Capital One breach post-mortem. Three-tier VPC, security groups, NACLs, VPC endpoints ($4,500/month savings at scale), Cloud Interconnect, and the Zero Trust principles from NIST SP 800-207.",
    lessons: [
      { title: "3.1 VPC Fundamentals: CIDR, Subnets, Route Tables, and NAT Architecture", desc: "IPv4 CIDR notation and subnetting for AI platform design (/16 VPCs, /24 subnets), public vs. private vs. isolated subnet patterns, NAT Gateway vs. NAT Instance economics, route table design for multi-tier applications, VPC peering for cross-account model serving, and the three-tier architecture (public: load balancers, private: GPU compute, isolated: databases) used by every regulated enterprise." },
      { title: "3.2 The Capital One Breach: What a Misconfigured WAF and SSRF Teach AI Cloud Engineers", desc: "Detailed technical post-mortem of the 2019 Capital One breach (106M records compromised). The SSRF attack path: WAF misconfiguration → EC2 metadata service (169.254.169.254) access → IAM role credential extraction → S3 bucket enumeration and download. Defense stack: IMDSv2 requirement (eliminates SSRF metadata access), Security Group deny rules for metadata service, least-privilege IAM for EC2 roles, and network segmentation that would have contained the breach." },
      { title: "3.3 Security Groups vs. NACLs: Stateful and Stateless Defense-in-Depth", desc: "Stateful Security Groups (connection tracking, return traffic automatic), stateless NACLs (explicit allow in both directions, ordered rules, subnet-level), designing Security Groups as whitelists (never 0.0.0.0/0 for compute), NACL as subnet-level backstop for Security Group misconfigurations, and the defense-in-depth pattern that prevents the 78% of incidents caused by single-layer security failures." },
      { title: "3.4 VPC Endpoints: Eliminating Internet Exposure and $4,500/Month NAT Costs", desc: "Gateway endpoints (S3, DynamoDB — zero data transfer cost), Interface endpoints (SageMaker, Secrets Manager, ECR — stay on AWS backbone), Private Link for SaaS and cross-account services, and detailed ROI calculation: at 100TB/month training data in S3, NAT Gateway costs $4,500/month in data processing fees vs. $0 with VPC Gateway Endpoint. GCP equivalent: Private Google Access, Private Service Connect." },
      { title: "3.5 Zero Trust Network Architecture for AI Platforms: NIST SP 800-207", desc: "Never trust, always verify — replacing perimeter-based security with identity-based access. BeyondCorp (Google's zero trust implementation), VPC Service Controls (GCP) for data exfiltration prevention, AWS Verified Access for zero-trust application access, microsegmentation with Kubernetes NetworkPolicies (default-deny all, explicit allow), and how Google's BeyondCorp has eliminated VPN requirements for 100K+ employees." },
      { title: "3.6 Hybrid Connectivity: VPN, Direct Connect, and Cloud Interconnect for Enterprise AI", desc: "AWS Site-to-Site VPN (IPSec, BGP routing), AWS Direct Connect (1-100 Gbps dedicated fiber, 99.99% SLA), GCP Cloud Interconnect (Dedicated and Partner), Azure ExpressRoute — when each is appropriate, latency and bandwidth characteristics, redundancy design (dual-homed Direct Connect for mission-critical AI serving), and cost modeling for different traffic volumes." },
      { title: "3.7 Module 3 Lab: Design and Implement a Production AI VPC", desc: "Complete VPC design challenge: create three-tier VPC, configure Security Groups for model training and serving, implement VPC endpoints for S3 and Secrets Manager, set up VPC Flow Logs, and demonstrate that training instances have no internet access while still reaching S3." },
    ]
  },
  {
    title: "Module 4: Infrastructure as Code — Terraform, Pulumi, and GitOps for AI Platforms",
    desc: "IaC from fundamentals through production-grade practices. Terraform state management, module architecture, Terragrunt for DRY multi-environment configs, Atlantis for PR-based infrastructure review, Checkov/tfsec for security scanning, and Pulumi for Python/TypeScript IaC. The practices used at Stripe, HashiCorp, Airbnb, and Lyft.",
    lessons: [
      { title: "4.1 Infrastructure as Code Philosophy: Why Manual Console Changes Are Technical Debt", desc: "The IaC golden rule (if it's not in code, it doesn't exist), the drift problem (manual changes accumulating into unauditable state), reproducibility as a compliance requirement (EU AI Act demands training infrastructure documentation), the three IaC paradigms (declarative Terraform, imperative Pulumi, functional Dhall), and the business case: how Etsy reduced their deployment-related incidents by 89% after going full IaC." },
      { title: "4.2 Terraform Deep Dive: HCL, State, Providers, and the Dependency Graph", desc: "HCL resource blocks, data sources, and local values. The state file as Terraform's memory — why S3+DynamoDB remote state with locking is mandatory in teams. The dependency graph (implicit dependencies via references, explicit via depends_on), parallelism in provisioning (independent resources created simultaneously), and terraform plan as the surgical view of what will change before it does. Live coding: provision an EKS cluster with all dependencies." },
      { title: "4.3 Terraform Modules: Reusable AI Infrastructure Components", desc: "Module structure (main.tf, variables.tf, outputs.tf, versions.tf), the registry.terraform.io ecosystem, creating a vpc module, eks_cluster module, and model_serving module for your AI platform. Input validation with precondition blocks, sensitive variables for secrets, and module composition patterns. Security: auditing third-party modules (supply chain attacks against IaC modules are a documented threat vector)." },
      { title: "4.4 Terragrunt: Managing 50+ Modules Across Dev/Staging/Production", desc: "The DRY problem in Terraform (copy-pasting backend configs and provider configs), Terragrunt's inputs inheritance (define once, override per environment), separate state backends per environment, run-all commands for coordinated multi-module operations, and the directory structure used by Gruntwork to manage Lyft's, Coinbase's, and hundreds of other companies' entire cloud infrastructure." },
      { title: "4.5 Atlantis: Pull Request-Based Infrastructure with Policy Enforcement", desc: "How Atlantis brings code review discipline to infrastructure changes — plan output as PR comment, merge locks, apply-after-merge workflow, SSO integration for approval gates, and OPA (Open Policy Agent) for policy-as-code (enforce 'no Security Groups with 0.0.0.0/0 inbound' as an automated policy that blocks PRs). Case study: how GitHub uses Atlantis to manage their production infrastructure changes with full audit trails." },
      { title: "4.6 Pulumi: Python and TypeScript IaC for Complex AI Platform Abstractions", desc: "When Pulumi outperforms Terraform: dynamic resource creation (create N model serving deployments from a list of models), component resources (encapsulate complete AI platform patterns), testing infrastructure with pytest/jest, and the Automation API (run Pulumi from Python to build self-service GPU provisioning portals). AWS CDK and GCP CDK as Pulumi alternatives in cloud-native contexts." },
      { title: "4.7 Module 4 Assessment: IaC Architecture, Security Review, and Module Design", desc: "Complete IaC challenge: review a Terraform codebase for security misconfigurations (Checkov findings), refactor into reusable modules with proper variable validation, design the Atlantis workflow with OPA policies, and write a Terragrunt configuration for three environments." },
    ]
  },
  {
    title: "Module 5: IAM, Secrets Management, and AI Security Architecture",
    desc: "Security architecture for production AI — Zero Trust IAM, the identity threat landscape, IRSA for keyless Kubernetes, Secrets Manager with automatic rotation, KMS envelope encryption, GuardDuty for ML platform threat detection, and lessons from the Capital One breach (SSRF + overprivileged IAM) and Tesla cryptojacking (exposed Kubernetes dashboard + no pod security).",
    lessons: [
      { title: "5.1 The Identity Threat Landscape: Why 83% of Cloud Breaches Involve Credentials", desc: "Verizon 2024 DBIR analysis of cloud incidents, the lifecycle of a compromised IAM credential (discovery → privilege escalation → lateral movement → data exfiltration), static access keys as 'time bombs' (Truffle Security found 4,000+ valid AWS keys in public GitHub repos), and the architectural shift from long-lived credentials to ephemeral role-based access that eliminates the entire credential theft threat class." },
      { title: "5.2 IAM Architecture: Policies, Roles, Permission Boundaries, and SCPs", desc: "IAM policy evaluation logic (explicit deny → SCP → permissions boundary → identity policy → resource policy), writing least-privilege policies for ML training jobs (S3:GetObject on specific prefix, not s3:* on *), permission boundaries as hard limits on delegated administration, Service Control Policies for organization-wide guardrails (prevent any role from disabling CloudTrail), and the AWS IAM Access Analyzer for automated policy review." },
      { title: "5.3 IRSA and Workload Identity: Eliminating Static Credentials from Kubernetes", desc: "The complete IRSA (IAM Roles for Service Accounts) mechanism — OIDC federation between EKS and AWS STS, pod-level IAM scoping (each pod assumes only its required role), credential rotation at the STS level (1-12 hour expiry), and how this eliminates the entire class of static credential incidents. GCP Workload Identity (identical concept for GKE). Production implementation: every Kubernetes pod at Affirm, Brex, and Robinhood uses workload identity." },
      { title: "5.4 Secrets Manager: Architecture, Automatic Rotation, and Audit Trail", desc: "Secrets Manager vs. Parameter Store (when to use each), automatic rotation for RDS databases (Lambda rotation function, zero-downtime rotation mechanics), custom rotation for third-party APIs, reading secrets in Python (boto3 with caching for cost control), the $0.40/secret/month economics, CloudTrail logging of every secret access (the audit trail that detected the Capital One breach), and cross-account secret sharing for multi-account AI platforms." },
      { title: "5.5 KMS Envelope Encryption: Protecting AI Model Artifacts and Training Data", desc: "Envelope encryption explained (data encryption key + key encryption key), KMS Customer Managed Keys vs. AWS Managed Keys (control, auditability, rotation schedule), S3 default encryption with KMS CMK (transparent to training jobs), encrypting model artifacts in ECR, field-level encryption for PII in training datasets, and the compliance value: why KMS + CloudTrail satisfies HIPAA, PCI-DSS, and FedRAMP encryption requirements for AI systems." },
      { title: "5.6 GuardDuty, Security Hub, and Threat Detection for AI Platforms", desc: "GuardDuty's ML-based threat detection (analyzes CloudTrail, VPC Flow Logs, DNS logs), critical finding types for AI platforms: CredentialAccess (IAM credential theft), CryptoCurrency (Tesla incident would have been caught), Exfiltration (unusual S3 data download patterns). Security Hub for aggregated findings across accounts, automated remediation with EventBridge + Lambda (auto-isolate compromised instances), and building a Security Operations Center for AI infrastructure." },
      { title: "5.7 Module 5 Assessment: Security Architecture Audit", desc: "Complete security review: identify and remediate 12 security vulnerabilities in a provided AI platform architecture spanning IAM policies, network controls, secrets management, and encryption gaps." },
    ]
  },
  {
    title: "Module 6: Containers, Docker, and GPU Container Engineering",
    desc: "Docker from filesystem internals through GPU container production — inspired by the CKA curriculum and cloud provider container documentation. Layer architecture, multi-stage builds (12GB → 3GB), the NVIDIA Container Toolkit, CUDA version management, container security (non-root, capabilities, Seccomp), supply chain security (SafeTensors vs. Pickle), and ECR lifecycle management.",
    lessons: [
      { title: "6.1 Container Architecture: Union Filesystem, Namespaces, and cgroups", desc: "How containers actually work at the Linux kernel level — overlay filesystem (each layer is a read-only filesystem stack), Linux namespaces (network, PID, mount, user — the isolation primitives), cgroups (CPU and memory limits enforcement), and why containers are 'not VMs' but also 'not just processes'. The Docker daemon vs. containerd architecture, OCI (Open Container Initiative) spec, and why Kubernetes deprecated Docker in favor of containerd." },
      { title: "6.2 Dockerfile Mastery: Layer Caching, Build Arguments, and ONBUILD Instructions", desc: "The Docker build cache as the #1 optimization lever (putting requirements.txt before COPY . . reduces AI container builds from 25 minutes to 30 seconds), ARG vs. ENV for build-time vs. runtime variables, HEALTHCHECK for Kubernetes liveness probes, multi-platform builds (ARM64 for Graviton inference, AMD64 for GPU training), .dockerignore best practices, and BuildKit for parallel multi-stage builds." },
      { title: "6.3 Multi-Stage Builds: Engineering 12GB AI Containers Down to 3GB Production Images", desc: "Builder stage (nvidia/cuda:12.1-devel for compilation, all build tools) vs. runtime stage (nvidia/cuda:12.1-cudnn8-runtime for serving, compiled artifacts only). How Netflix achieved 60-80% image size reduction with multi-stage builds, the compound economics at scale (1,000 deployments × 5GB saved = 5TB of network transfer eliminated daily), distroless base images for zero-CVE containers, and the three-stage pattern (build, test, release) for CI/CD integration." },
      { title: "6.4 GPU Containers: NVIDIA Container Toolkit, CUDA Matrix, and Production GPU Workloads", desc: "The NVIDIA Container Toolkit architecture (libnvidia-container, nvidia-container-runtime), the CUDA version compatibility matrix (driver 525 → max CUDA 12.1, driver 535 → max CUDA 12.2), pinning base images (FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04 for reproducibility), the runtime class configuration in Kubernetes (runtimeClass: nvidia), testing GPU access (nvidia-smi inside container), and diagnosing 'CUDA driver version insufficient' failures." },
      { title: "6.5 Container Security: Non-Root Users, Capabilities, Seccomp, and Pod Security", desc: "Container escape vulnerabilities (CVE-2019-5736 runc escape, why root containers give host access), USER directive and non-root runtime (appuser with UID 1000), --cap-drop ALL with selective cap-add (NET_BIND_SERVICE for port 80), read-only root filesystem with specific writable tmpfs mounts, Seccomp profiles for syscall allowlisting, Pod Security Admission (baseline/restricted standards), and Snyk's finding that 78% of critical container CVEs come from base image packages." },
      { title: "6.6 Container Registry, SBOM, and Supply Chain Security for AI Models", desc: "ECR immutable tags (prevent silent model replacement), lifecycle policies for AI artifact cost control (retain last 10 semantic versions, delete untagged after 7 days), Trivy and Snyk for automated CVE scanning in CI/CD, the dependency confusion attack (attackers publish malicious packages with internal names — affected Microsoft and Uber in 2021), SafeTensors format vs. Pickle (Pickle executes arbitrary code on load — JFrog discovered real malicious model files on HuggingFace in 2022), and SBOM generation with Syft." },
      { title: "6.7 Module 6 Lab: Build, Secure, and Deploy a Production GPU Container", desc: "Complete container engineering project: write an optimized multi-stage Dockerfile for a PyTorch model server, implement all security controls (non-root, capabilities, Seccomp), run Trivy scan with zero critical CVEs, push to ECR with immutable tag, and deploy to Kubernetes with GPU resource requests." },
    ]
  },
  {
    title: "Module 7: Kubernetes for AI — From Control Plane to Production GPU Orchestration",
    desc: "Kubernetes from architecture internals through advanced AI-specific production patterns — aligned with the Certified Kubernetes Administrator (CKA) curriculum and enriched with AI workload-specific content. Control plane deep dive, all workload types for ML, GPU scheduling, KEDA for event-driven inference, Helm/ArgoCD for GitOps, Istio for canary deployments, and KubeRay for distributed training.",
    lessons: [
      { title: "7.1 Kubernetes Architecture: Control Plane, etcd, and the Reconciliation Philosophy", desc: "API Server as single source of truth and admission webhook chain, etcd as the cluster's brain (RAFT consensus, why backup is existential — without etcd, your cluster state is unrecoverable), Controller Manager reconciliation loops (desired state → actual state), Scheduler's bin-packing and scoring algorithm, Kubelet's node agent role, kube-proxy networking modes (iptables vs. IPVS), and the Container Runtime Interface (containerd, CRI-O). Case study: how Datadog's 2021 cluster-wide outage traced to an etcd performance degradation." },
      { title: "7.2 AI Workload Types: Jobs, CronJobs, Deployments, StatefulSets, and DaemonSets", desc: "Training jobs (completions, parallelism, backoffLimit for failure handling), scheduled retraining CronJobs (concurrencyPolicy, startingDeadlineSeconds), model serving Deployments (rolling update strategy, maxUnavailable, maxSurge), distributed training with StatefulSets (stable network identity for PyTorch DDP, PyTorch Elastic), DaemonSets for node-level monitoring (node exporter, GPU metrics), and when to use each workload type for specific ML tasks." },
      { title: "7.3 GPU Scheduling: Taints, Tolerations, Affinity, Resource Limits, and MIG", desc: "nvidia.com/gpu as a non-divisible resource (request = limit = 1), tainting GPU nodes (gpu=true:NoSchedule) to prevent CPU workloads consuming expensive capacity, tolerations in ML training job specs, node affinity for specific GPU types (nodeAffinity: A100 for training, T4 for inference), Pod Anti-affinity for HA inference replicas (spread across 3 AZs), ResourceQuota per team namespace for GPU budget enforcement, and NVIDIA MIG (Multi-Instance GPU) for sharing A100 across smaller models." },
      { title: "7.4 Autoscaling AI Workloads: HPA, VPA, KEDA, Cluster Autoscaler, and Karpenter", desc: "HPA with custom Prometheus metrics (GPU utilization via KEDA's Prometheus scaler, not CPU which stays low under GPU load), VPA for right-sizing training job memory (Recommendation mode first), KEDA ScaledObjects on SQS queue depth (scale inference fleet to zero when queue is empty, spin up when messages arrive), Cluster Autoscaler vs. Karpenter (30s vs. 5min node provisioning — the difference between training jobs starting in minutes vs. during the next coffee break), and Karpenter NodePool configurations for GPU instance diversity." },
      { title: "7.5 Helm, Kustomize, and ArgoCD: GitOps for 100+ ML Services", desc: "Helm chart architecture (Chart.yaml, values.yaml, templates with Go templating), Helm test hooks for post-deployment validation, Kustomize base/overlays pattern for dev/staging/prod differentiation, ArgoCD Application and ApplicationSet (one template → 100 applications across 3 clusters), drift detection (OutOfSync = someone manually edited production), auto-sync with Prune (delete resources not in Git), and how Lyft's and Datadog's ML platform teams manage hundreds of services with ArgoCD." },
      { title: "7.6 Service Mesh with Istio: mTLS, Canary Deployments, and Circuit Breaking for AI APIs", desc: "Istio sidecar injection (Envoy proxy alongside every model server), automatic mTLS for service-to-service encryption (zero code changes), VirtualService traffic weights for canary model rollout (5% → 25% → 100% with metrics validation), DestinationRule circuit breaking for feature store timeouts (prevent cascade failures), request mirroring (shadow traffic to new model for validation), and distributed tracing integration (every inference request traced end-to-end through the serving pipeline)." },
      { title: "7.7 KubeRay and Distributed Training: Multi-Node GPU Workloads on Kubernetes", desc: "KubeRay Operator (RayCluster custom resource for distributed training), Ray's actor model for distributed ML, multi-node PyTorch DDP on EKS (NCCL for GPU-to-GPU communication, EFA for high-bandwidth networking), the Kubeflow Training Operator for TFJob and PyTorchJob, gang scheduling (all training pods start simultaneously or none do — prevents GPU waste), and a complete distributed fine-tuning architecture for 70B parameter models on 8× A100 nodes." },
      { title: "7.8 Module 7 Assessment: Production Kubernetes Architecture Design", desc: "Design the complete Kubernetes architecture for a production AI inference platform: GPU scheduling for two model tiers (large: A100, small: T4), autoscaling with KEDA on queue depth, ArgoCD GitOps with drift detection, Istio canary deployment for model updates, and circuit breaking for feature store dependency — with a full defense of every architectural decision." },
    ]
  },
  {
    title: "Module 8: Observability, SRE Practices, and AI System Reliability",
    desc: "The Google SRE Book applied to AI systems — the complete observability stack (Prometheus, Grafana, Loki, Jaeger/OTel), the four golden signals for AI inference, SLOs and error budgets, AI-specific monitoring (prediction drift, feature freshness, model quality), runbooks, chaos engineering, and the practices that allow AI systems to achieve 99.9%+ reliability while deploying multiple times per day.",
    lessons: [
      { title: "8.1 Observability vs. Monitoring: The Charity Majors Distinction and Why It Matters", desc: "Traditional monitoring (dashboards, threshold alerts, CPU/memory) vs. observability (understanding internal state from external outputs). The three pillars: metrics (quantitative time-series), logs (discrete events), traces (request journeys across services). Why the combination of all three is required: metrics tell you something is wrong (p99 latency spike), traces tell you where (feature store at step 3 is slow), and logs tell you why (Redis connection pool exhausted). Building the complete observability stack from scratch." },
      { title: "8.2 Prometheus Deep Dive: Custom AI Metrics, PromQL, and Alert Engineering", desc: "Prometheus architecture (pull model, service discovery, TSDB), the four metric types in practice (inference_latency_seconds as Histogram, gpu_utilization_percent as Gauge, predictions_total as Counter, active_model_connections as Gauge), ServiceMonitor resources for auto-discovery of model servers, PromQL for meaningful alerting (histogram_quantile(0.99, rate(inference_latency_seconds_bucket[5m])) > 0.1), multi-window alert rules to prevent flapping (for: 5m), and the Recording Rules that pre-compute expensive queries." },
      { title: "8.3 Grafana Dashboards: Designing AI Operations Command Centers", desc: "Grafana dashboard design principles for AI systems, the four golden signals panel layout (Latency, Traffic, Errors, Saturation), GPU utilization heatmaps per node group, model performance panels (prediction confidence p50/p95/p99 over time), feature freshness indicators, cost-per-prediction tracking, alert integration with PagerDuty and Slack, and the variable and template system that makes one dashboard serve all model versions and environments." },
      { title: "8.4 Structured Logging with Loki and Log-Based Alerting", desc: "JSON structured logging best practices for ML systems (request_id, model_version, latency_ms, prediction_score, feature_hash — every field that enables ML-specific debugging), FluentBit DaemonSet configuration for pod log collection, Grafana Loki architecture (Promtail → Loki → Grafana), LogQL for ML debugging (find all predictions where model_version='v2.3.1' and latency_ms > 500), and log-based alerting for security events (failed authentication, unexpected API patterns)." },
      { title: "8.5 OpenTelemetry Distributed Tracing for AI Inference Pipelines", desc: "OTel SDK instrumentation for Python model servers (auto-instrumentation for Flask/FastAPI, manual span creation for feature retrieval and model inference), trace context propagation across service boundaries (W3C TraceContext header), the OTel Collector architecture (receive → process → export), backend options (Jaeger for self-hosted, Honeycomb for SaaS, Grafana Tempo integrated with Loki and Prometheus), and diagnosing p99 latency spikes from trace analysis in under 2 minutes." },
      { title: "8.6 SLOs, Error Budgets, and the Google SRE Reliability Framework", desc: "Defining AI service SLIs (inference request success rate, latency p99, feature freshness percentage), SLO target-setting (the 'reliability target' vs. 'aspirational target' split), error budget math (99.9% SLO = 43.8 min/month allowable downtime), the error budget policy (full budget → deploy freely, 50% consumed → investigate, depleted → freeze non-essential deploys), SLO-based alerting (burn rate alerts are 14x more actionable than threshold alerts), and how Google, Netflix, and Airbnb use SLOs to replace the dysfunctional ops-vs-dev reliability dynamic." },
      { title: "8.7 AI-Specific Monitoring: Prediction Drift, Feature Freshness, and Model Quality", desc: "The silent failure modes of production ML (no exceptions, just wrong predictions). Prediction score distribution monitoring (p50 confidence dropping from 0.89 to 0.72 is an early warning signal), label distribution monitoring (positive rate shifting from 8% to 15% without business reason), feature distribution drift (PSI > 0.2 = retrain trigger), feature freshness SLA (user_purchases_last_hour stale for 6 hours = degraded fraud detection), and Evidently AI, Arize, and WhyLabs for operationalizing ML monitoring." },
      { title: "8.8 Chaos Engineering, Runbooks, and the GameDay Practice", desc: "Netflix's Chaos Monkey principle (inject failure before it injects itself), chaos experiments for AI platforms (kill a model server pod, inject feature store latency, disable a GPU node), verifying circuit breakers and fallback behaviors, runbook structure (alert description → triage steps → likely causes → remediation → escalation), quarterly runbook testing, the Facebook 2021 outage lesson (untested rollback procedures cause 6-hour incidents), and designing GameDay exercises for AI platform teams." },
      { title: "8.9 Module 8 Assessment: Observability Architecture and Incident Response Simulation", desc: "Design the complete observability stack for an AI platform. Write three AI-specific runbooks. Given a production incident scenario (model serving p99 latency spiked from 45ms to 840ms at 14:32 UTC), use the provided metrics, logs, and traces to diagnose root cause and document remediation steps within 30 minutes." },
    ]
  },
  {
    title: "Module 9: Serverless AI, GPU Inference Optimization, and Advanced Deployment Patterns",
    desc: "Serverless AI patterns (Lambda, Cloud Run, Modal), GPU inference optimization (TensorRT, vLLM's PagedAttention, Triton Inference Server, batching strategies), model deployment patterns (blue-green, canary, shadow, feature flags), and the CI/CD for ML pipeline that takes a code commit to production in under 4 hours.",
    lessons: [
      { title: "9.1 Serverless AI: AWS Lambda, Google Cloud Run, and Modal for Burst Inference", desc: "Lambda container images for ML inference (10GB image limit, SnapStart for cold start reduction, provisioned concurrency for latency SLAs), Cloud Run GPU instances (NVIDIA L4, A100, zero-scale-to-zero cost), Modal's cloud-native Python framework (GPU-attached functions in 5 lines), and the serverless vs. Kubernetes decision matrix: serverless wins for bursty, unpredictable traffic; Kubernetes wins for steady-state high-throughput AI serving." },
      { title: "9.2 TensorRT: Compiling Models for Maximum NVIDIA GPU Throughput", desc: "TensorRT's optimization pipeline (graph optimization, layer fusion, INT8/FP16 precision calibration, kernel auto-tuning), the 2-4x throughput improvement on A100 over native PyTorch, TensorRT-LLM for large language model optimization, the calibration dataset requirement for INT8 quantization, dynamic shapes for variable-length inputs, and Triton Inference Server integration for production serving with TensorRT engines." },
      { title: "9.3 vLLM and PagedAttention: Solving the LLM Memory Crisis", desc: "Kwon et al.'s 2023 PagedAttention paper — why traditional LLM serving wastes 60-80% of GPU memory through fragmentation, how PagedAttention manages KV cache like virtual memory pages (non-contiguous blocks, zero waste), vLLM's continuous batching (dramatically higher throughput vs. static batching), speculative decoding for latency reduction, and deployment architecture: vLLM on Kubernetes with autoscaling based on request queue depth via KEDA." },
      { title: "9.4 Triton Inference Server: Multi-Model, Multi-Framework Production Serving", desc: "Triton's model repository architecture (concurrent models, multiple frameworks: TensorRT, ONNX, PyTorch, TensorFlow), dynamic batching and preferred batch sizes, model ensemble pipelines (preprocessing → model → postprocessing as a single Triton request), perf_analyzer for throughput/latency benchmarking, Prometheus metrics export, and how AWS SageMaker and GCP Vertex AI both use Triton as their internal serving engine." },
      { title: "9.5 Model Deployment Patterns: Canary, Blue-Green, Shadow, and Feature Flags", desc: "Rolling update (simplest, some risk), blue-green (instant rollback, 2x cost during transition), canary with automated rollback (5% → 25% → 100% with Istio VirtualService weights, automated rollback if p99 latency or error rate exceeds threshold), shadow deployment (new model sees production traffic, results not served — safest for fraud detection), and feature flags (LaunchDarkly, Unleash) for user-segment-specific model rollouts. Netflix's canary deployment strategy for 1,000+ daily model updates." },
      { title: "9.6 CI/CD for ML: The 4-Hour Commit-to-Production Pipeline", desc: "Complete CI/CD for ML pipeline: PR triggers (code quality, unit tests, security scan), merge triggers (model training on 5% sample data, smoke test), main branch triggers (full training, model quality gates — accuracy, bias, latency, regression), model registry promotion (Staging on gate pass), staging validation (shadow traffic test), production promotion (manual gate or automated A/B), Kubernetes deployment via ArgoCD. The 4-hour commit-to-production metric that characterizes MLOps Level 2 teams." },
      { title: "9.7 Module 9 Lab: Build a Complete AI Inference Optimization Stack", desc: "End-to-end optimization project: take a PyTorch ResNet model, compile with TensorRT (measure throughput improvement), deploy on Triton Inference Server with dynamic batching, configure Kubernetes autoscaling with KEDA on request queue depth, and implement canary deployment with automated rollback." },
    ]
  },
  {
    title: "Module 10: Multi-Cloud AI, FinOps at Scale, Disaster Recovery, and Certification Capstone",
    desc: "The advanced practitioner curriculum — multi-cloud architecture avoiding vendor lock-in, FinOps optimization achieving 40-60% cost reduction, disaster recovery with tested failover procedures, and the production capstone where you architect a complete enterprise AI platform from scratch and defend every decision. This module transforms you from cloud engineer to cloud architect.",
    lessons: [
      { title: "10.1 Multi-Cloud AI Architecture: Open Standards and Avoiding Vendor Lock-in", desc: "Kubernetes as the multi-cloud abstraction layer, ONNX for portable model formats, OpenTelemetry for vendor-neutral observability, Terraform for consistent multi-cloud IaC, the data gravity problem (data has cost of egress — compute should move to data, not vice versa), regulatory data residency requirements driving multi-cloud (GDPR, Chinese PIPL, Indian PDPB), and architectural patterns for primary-cloud + burst-cloud (run steady-state on AWS, burst training to GCP for TPU access)." },
      { title: "10.2 FinOps at Scale: Achieving 40-60% AI Infrastructure Cost Reduction", desc: "Spot/Preemptible instance strategy for training (60-90% savings with checkpoint-and-resume), Reserved Instance and Savings Plan optimization for inference (1-year no-upfront RI for steady-state models, 3-year partial-upfront for established services), Karpenter's spot instance diversification (request 8 instance families → always find capacity), S3 Intelligent-Tiering for training datasets (automatic tiering for 40% storage cost reduction), and the FinOps governance model that keeps AI infrastructure costs from growing linearly with model count." },
      { title: "10.3 Disaster Recovery: RTO, RPO, and Tested Failover for AI Systems", desc: "RTO and RPO definitions in the context of AI systems (inference RTO vs. training RTO vs. feature freshness RPO), multi-region model artifact replication (S3 CRR, GCS multi-region), feature store DR architecture (Redis Cluster with cross-region replica), the four DR strategies (backup-restore, pilot light, warm standby, active-active) and their cost vs. RTO tradeoffs, and the Facebook 2021 lesson: an untested rollback procedure that causes a 6-hour outage is not a rollback procedure." },
      { title: "10.4 Compliance and Governance for AI Cloud Infrastructure", desc: "AWS Config and GCP Asset Inventory for continuous compliance monitoring, automated remediation for non-compliant resources (accidentally public S3 bucket → Lambda auto-remediates in 30 seconds), SOC2 Type II controls for AI infrastructure (AWS Artifact, GCP Compliance Reports), HIPAA for healthcare AI (Business Associate Agreements, PHI encryption requirements), PCI-DSS for payment AI (cardholder data environment segmentation), and EU AI Act's Article 15 infrastructure requirements for high-risk AI systems." },
      { title: "10.5 AI Platform Engineering: Building the Internal Developer Platform", desc: "The Platform Engineering movement (CNCF Platform Engineering WG, 2022), Spotify's Backstage IDP framework, Software Templates for one-click model deployment (generates Dockerfile, Kubernetes manifests, GitHub Actions CI/CD, Grafana dashboard), self-service GPU provisioning (Backstage form → Karpenter GPU node → RayCluster → auto-terminate on idle), developer experience metrics (Self-Service Rate > 90%, onboarding time reduction), and the Stripe Friction Log methodology for prioritizing platform improvements." },
      { title: "10.6 Production Capstone: Architect a Complete Enterprise AI Platform", desc: "The ultimate synthesis: given the requirements of a financial services company deploying AI for fraud detection, customer churn prediction, and document processing, design the complete infrastructure: VPC architecture, IAM and secrets management, Kubernetes cluster configuration with GPU scheduling, observability stack, CI/CD pipeline, model registry and deployment strategy, feature store, monitoring and alerting, DR architecture, and cost optimization plan. Present the architecture with cost estimates, justify every decision, and address the security, compliance, and operational requirements." },
      { title: "10.7 Final Certification Exam: AI Cloud Engineer Professional Certification", desc: "200-question comprehensive examination covering all 10 modules. Scenario-based questions drawn from real production situations — architecture design challenges, security incident response, cost optimization decisions, and operational troubleshooting. Requires 85% pass rate. Awarded upon completion: Aladiah Academy AI Cloud Engineer Professional Certification, demonstrating mastery equivalent to AWS Solutions Architect Professional + CKA + Google Professional Cloud Architect combined with AI infrastructure specialization." },
    ]
  }
];

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);

    const { data: course, error: ce } = await supabase.from("courses").insert({
      title: COURSE_TITLE,
      description: "The world's most comprehensive AI Cloud Engineering certification — 10 deep modules, 70+ lessons, inspired by Google Cloud Associate Cloud Engineer, AWS Solutions Architect Professional, and Certified Kubernetes Administrator combined with AI infrastructure specialization. Covers VPC architecture, Terraform, IAM/Zero Trust, GPU containers, Kubernetes, Istio, observability, vLLM, TensorRT, multi-cloud, FinOps, and disaster recovery. Every lesson grounded in real production case studies from Netflix, Stripe, Airbnb, Google, and Cloudflare.",
      is_published: true,
      translations: {
        es:{title:"Ingeniero de Nube IA",description:"La certificación más completa del mundo en ingeniería de nube para IA — 10 módulos profundos."},
        fr:{title:"Ingénieur Cloud IA",description:"La certification la plus complète au monde en ingénierie cloud IA — 10 modules approfondis."},
        de:{title:"KI-Cloud-Ingenieur",description:"Die umfassendste KI-Cloud-Engineering-Zertifizierung der Welt — 10 tiefe Module."},
        zh:{title:"AI云工程师",description:"全球最全面的AI云工程师认证 — 10个深度模块。"},
        ar:{title:"مهندس سحابة الذكاء الاصطناعي",description:"أشمل شهادة هندسة سحابة الذكاء الاصطناعي في العالم — 10 وحدات متعمقة."},
        ja:{title:"AIクラウドエンジニア",description:"世界最高峰のAIクラウドエンジニアリング認定 — 10の深いモジュール。"},
      }
    }).select().single();
    if (ce) throw ce;

    let chaptersCreated = 0;
    let videosCreated = 0;

    for (let mi = 0; mi < modules.length; mi++) {
      const mod = modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({
        course_id: course.id, title: mod.title, description: mod.desc,
        order_index: mi, translations: {}
      }).select().single();
      if (che) throw che;
      chaptersCreated++;

      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = `${les.title}\n\n${les.desc}\n\nThis is a world-class lesson from Aladiah Academy's AI Cloud Engineer certification program — the most comprehensive AI cloud infrastructure curriculum available, inspired by and surpassing Google Cloud Associate Cloud Engineer, AWS Solutions Architect Professional, and Certified Kubernetes Administrator.\n\nProf. Didier will teach this content with production-grade depth, real-world case studies from Netflix, Stripe, Airbnb, Google, Cloudflare, and Datadog, hands-on implementation guidance, and scenario-based knowledge that translates directly to $120K-$220K AI Cloud Engineer roles at top technology companies.\n\nKey references for this lesson include the AWS Well-Architected Framework, Google Cloud Architecture Framework, Google SRE Book, HashiCorp Terraform documentation, CNCF landscape, NIST security frameworks (SP 800-207 Zero Trust, SP 800-53 Security Controls), and primary research papers from Google, Netflix, and academic institutions.\n\nThis lesson is part of the ${mod.title} module, which covers: ${mod.desc}`;

        const trans = {
          en:{title:les.title,transcript},
          es:{title:les.title,transcript},
          fr:{title:les.title,transcript},
          de:{title:les.title,transcript},
          zh:{title:les.title,transcript},
          ar:{title:les.title,transcript},
          ja:{title:les.title,transcript}
        };

        const { data: video, error: ve } = await supabase.from("videos").insert({
          chapter_id: chapter.id, title: les.title, description: les.desc,
          order_index: li, translations: trans
        }).select().single();
        if (ve) throw ve;
        videosCreated++;

        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({
          video_id: video.id, chapter_id: chapter.id,
          quiz_type: "mini_video", passing_score: 85
        }).select().single();
        if (qe) throw qe;

        const shortTitle = les.title.replace(/^\d+\.\d+\s/, '');
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: `What is the production-critical insight from "${shortTitle}"?`, scenario_context: `You are applying this lesson's knowledge in a real enterprise AI deployment.`, options: [les.desc.substring(0, 80) + (les.desc.length > 80 ? "..." : ""), "This is only relevant for research environments", "This applies only to startups, not enterprises", "This concept is deprecated in modern cloud platforms"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: `Which $120K-$220K AI Cloud Engineer certification validates mastery of "${shortTitle}"?`, scenario_context: "Preparing for your AI Cloud Engineer job search.", options: ["Aladiah Academy AI Cloud Engineer Professional Certification — the most comprehensive AI cloud curriculum combining Google Cloud, AWS, and Kubernetes depth with AI infrastructure specialization", "Basic cloud practitioner certification", "General software development certification", "No certification covers this advanced content"], correct_answer_index: 0, explanation: "Aladiah Academy's AI Cloud Engineer certification covers this and 70+ other lessons across 10 modules — the depth of GCP Associate Cloud Engineer + AWS Solutions Architect Professional + CKA combined.", order_index: 1 },
          { quiz_id: quiz.id, question_text: `Which real-world companies provide case studies for "${shortTitle}"?`, scenario_context: "Learning from production incidents and successes at top tech companies.", options: ["Netflix, Stripe, Airbnb, Google, Cloudflare, and Datadog — world-class technology organizations whose production practices inform this curriculum", "No real companies were used as references", "Only startup examples are relevant", "Case studies are not applicable to this technical topic"], correct_answer_index: 0, explanation: "Every lesson in this program is grounded in real production examples from top technology organizations, making the knowledge immediately applicable in enterprise environments.", order_index: 2 },
        ]);
      }

      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({
        chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85
      }).select().single();
      if (eqe) throw eqe;

      const modShort = mod.title.replace(/^Module \d+:\s/, '');
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: `What production expertise does completing "${modShort}" demonstrate?`, scenario_context: "Module completion assessment.", options: [mod.desc.substring(0, 100) + "...", "Only introductory familiarity", "Theoretical knowledge without production application", "Skills not valued by employers"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "This module's content is equivalent to which industry certifications?", scenario_context: "Comparing certification value.", options: ["Combines depth from GCP Associate Cloud Engineer, AWS Solutions Architect, and CKA with AI-specific production content not covered by any individual certification", "Entry-level certification only", "A single vendor certification", "Primarily academic, not industry-recognized"], correct_answer_index: 0, explanation: "Aladiah Academy's curriculum draws from and exceeds the depth of Google Cloud, AWS, and Kubernetes certifications, with AI-specific enrichment throughout.", order_index: 1 },
        { quiz_id: eq.id, question_text: "What salary range does demonstrated mastery of this module support?", scenario_context: "Career planning with Aladiah Academy certification.", options: ["$120K-$220K AI Cloud Engineer roles at Fortune 500 and top technology companies globally", "Entry-level positions only", "Only freelance consulting work", "Academic research positions"], correct_answer_index: 0, explanation: "AI Cloud Engineers with this depth of expertise command $120K-$220K globally — the supply-demand imbalance for engineers who can combine cloud infrastructure with AI systems expertise is significant and growing.", order_index: 2 },
        { quiz_id: eq.id, question_text: "Which production incident case studies are covered in this module?", scenario_context: "Learning from real-world failures to prevent them in your own systems.", options: ["Real documented incidents from Netflix, Datadog, Google, Facebook, Cloudflare, and others — with root causes and prevention measures", "Only hypothetical scenarios", "No incident analysis included", "Only successful deployments, not failures"], correct_answer_index: 0, explanation: "Learning from production incidents is the fastest path to expertise. This curriculum draws from documented post-mortems at world-class organizations to give you the pattern recognition of an engineer with 10 years of production experience.", order_index: 3 },
        { quiz_id: eq.id, question_text: "What is the correct sequence for applying this module's knowledge in a new AI platform project?", scenario_context: "You are the AI Cloud Engineer for a Series B startup's first production AI deployment.", options: ["Apply the architectural patterns from this module systematically: design first, implement with IaC, validate security, configure observability, then iterate — the production engineering sequence", "Skip to implementation without design", "Use only managed services without understanding the underlying infrastructure", "Copy configurations from StackOverflow without understanding them"], correct_answer_index: 0, explanation: "Production-grade AI infrastructure requires systematic application of architectural patterns — design before implementation, security built-in not bolted-on, observability from day one. This is the sequence this module teaches.", order_index: 4 },
      ]);
    }

    return new Response(JSON.stringify({
      message: `AI Cloud Engineer — 10-module world-class version seeded`,
      courseId: course.id,
      modules: chaptersCreated,
      lessons: videosCreated
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });

  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
});
