import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { requireAdmin } from "../_shared/auth.ts";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const courseData = {
  "title": "AI DevOps Engineer",
  "description": "Build the CI/CD pipelines, Kubernetes infrastructure, GitOps workflows, and SRE practices that power production AI systems. From containerization to chaos engineering — every DevOps skill modern AI teams require.",
  "translations": {"es": {"title": "AI DevOps Engineer", "description": "Build the CI/CD pipelines, Kubernetes infrastructure, GitOps workflows, and SRE practices that power production AI systems. From containerization to chaos engineering — every DevOps skill modern AI teams require."}, "fr": {"title": "AI DevOps Engineer", "description": "Build the CI/CD pipelines, Kubernetes infrastructure, GitOps workflows, and SRE practices that power production AI systems. From containerization to chaos engineering — every DevOps skill modern AI teams require."}, "de": {"title": "AI DevOps Engineer", "description": "Build the CI/CD pipelines, Kubernetes infrastructure, GitOps workflows, and SRE practices that power production AI systems. From containerization to chaos engineering — every DevOps skill modern AI teams require."}, "zh": {"title": "AI DevOps Engineer", "description": "Build the CI/CD pipelines, Kubernetes infrastructure, GitOps workflows, and SRE practices that power production AI systems. From containerization to chaos engineering — every DevOps skill modern AI teams require."}, "ar": {"title": "AI DevOps Engineer", "description": "Build the CI/CD pipelines, Kubernetes infrastructure, GitOps workflows, and SRE practices that power production AI systems. From containerization to chaos engineering — every DevOps skill modern AI teams require."}, "ja": {"title": "AI DevOps Engineer", "description": "Build the CI/CD pipelines, Kubernetes infrastructure, GitOps workflows, and SRE practices that power production AI systems. From containerization to chaos engineering — every DevOps skill modern AI teams require."}},
  "modules": [
  {"title": "Module 1: DevOps Foundations, DORA Research, and CI/CD for AI", "desc": "The science of high-performing engineering teams — four metrics that predict business outcomes, the culture required for DevOps transformation, and CI/CD pipelines built specifically for AI systems.", "lessons": [
    {"title": "1.1 The DORA Research: What Separates Elite DevOps Teams from the Rest", "desc": "Nicole Forsgren, Jez Humble, and Gene Kim's landmark Accelerate research — the four keys, psychological safety, and what it all means for AI engineering teams."},
    {"title": "1.2 CI/CD Pipeline Architecture for AI Systems", "desc": "Building production-grade CI/CD specifically for AI — model quality gates, artifact management, deployment strategies, and the automated safety nets that prevent bad models from reaching users."},
    {"title": "1.3 GitOps for AI Platforms: ArgoCD, Flux, and Infrastructure as Code", "desc": "How GitOps principles make AI platform infrastructure declarative, auditable, and self-healing — preventing the configuration drift that silently degrades AI system reliability."},
    {"title": "1.4 Observability and SRE Practices for AI Systems", "desc": "Google's SRE Book, the three observability pillars, the Four Golden Signals, SLOs and error budgets, and the AI-specific monitoring that catches model degradation before users notice."},
    {"title": "1.5 Platform Engineering for AI: Internal Developer Platforms and the Paved Road", "desc": "How Spotify's Backstage, Netflix's Paved Path, and the CNCF Platform Engineering movement transform AI team productivity — building self-service infrastructure that lets data scientists focus on ML, not DevOps."}
  ]},
  {"title": "Module 2: Container Orchestration with Kubernetes for AI Workloads", "desc": "Kubernetes is the operating system of modern AI infrastructure. Pod lifecycle, deployments, services, GPU scheduling, resource quotas, and production Kubernetes patterns for model serving and training.", "lessons": [
    {"title": "2.1 Kubernetes Architecture: Control Plane, Node Components, and the API Server", "desc": "Kubernetes control plane: API Server (all communication passes through it — kubectl, controllers, kubelets), etcd (distributed key-value store, the cluster's ground truth — back it up daily), Scheduler (assigns pods to nodes based on resource requirements and affinity rules), Controller Manager (runs reconciliation loops: ReplicaSet controller ensures desired pod count). Node components: kubelet ("},
    {"title": "2.2 Deploying AI Models with Deployments, ReplicaSets, and Pod Disruption Budgets", "desc": "The Deployment resource manages the lifecycle of model serving pods: desired replica count, container image, resource requests/limits, liveness and readiness probes. Rolling update strategy: maxSurge (extra pods during update) and maxUnavailable (pods that can be down). Blue-green deployments via two Deployments + Service selector swap. Pod Disruption Budgets: guarantee minimum available replicas "},
    {"title": "2.3 GPU Scheduling: NVIDIA Device Plugin, GPU Sharing, and Multi-Instance GPU", "desc": "Kubernetes GPU scheduling requires the NVIDIA device plugin: discovers GPUs on nodes, advertises as nvidia.com/gpu resources, assigns GPU devices to pods. Resource request: resources.limits.nvidia.com/gpu: 1 reserves a full GPU exclusively. GPU sharing strategies: time-slicing (multiple pods share one GPU via NVIDIA time-slicing — cost efficient for small inference workloads), Multi-Instance GPU ("},
    {"title": "2.4 Helm Charts: Packaging and Deploying AI Platform Components", "desc": "Helm is the package manager for Kubernetes — charts are templated YAML packages that can be configured for different environments. Chart structure: Chart.yaml (metadata), values.yaml (defaults), templates/ (Go-templated Kubernetes manifests). The values override pattern: helm install my-app ./chart --values prod-values.yaml separates chart logic from environment config. Official charts: cert-manag"},
    {"title": "2.5 Horizontal Pod Autoscaler and KEDA for AI Inference Scaling", "desc": "Scaling model serving pods in response to real traffic. HPA v2: scale on CPU (simple), memory (for memory-bound inference), and custom metrics (scale on requests-per-second from Prometheus). The HPA algorithm: current_replicas × (current_metric / target_metric). KEDA (Kubernetes Event-Driven Autoscaling): scale on any external metric — Kafka consumer lag (scale consumers when lag grows), queue dep"},
    {"title": "2.6 Kubernetes Networking: Services, Ingress, and Service Mesh for AI APIs", "desc": "Kubernetes networking stack for model serving. ClusterIP: internal service for pod-to-pod communication (feature store → model server). NodePort/LoadBalancer: external access (cloud load balancer provisioned automatically). Ingress: HTTP routing rules (route /api/v1/predict → model-serving-service, /api/v1/embed → embedding-service). NGINX Ingress Controller with rate limiting, authentication, and"},
    {"title": "2.7 Module 2 Lab: Deploy a Model Serving Stack on Kubernetes", "desc": "Complete Kubernetes deployment: containerize a FastAPI model serving application, write Deployment and Service manifests, configure resource requests with GPU limits, deploy KEDA with HTTP scaling, set up NGINX Ingress with rate limiting, configure HPA, and deploy monitoring with Prometheus and Grafana. Test autoscaling under load."}
  ]},
  {"title": "Module 3: GitOps and Advanced CI/CD for AI Systems", "desc": "GitOps makes infrastructure and model deployments auditable, reproducible, and reversible. ArgoCD, Flux, model deployment pipelines, canary releases for ML, and the deployment practices at Spotify, GitHub, and Shopify.", "lessons": [
    {"title": "3.1 GitOps Principles: Git as the Source of Truth for AI Infrastructure", "desc": "GitOps (coined by Weaveworks in 2017) defines four principles: declarative (all system state described in Git), versioned (Git history is the audit log), automated (approved changes applied automatically), and continuously reconciled (controllers detect and correct drift). The operational benefits: every infrastructure change is a Git commit (who, what, when, why), rollbacks are Git reverts (one c"},
    {"title": "3.2 ArgoCD: Continuous Delivery for Kubernetes Applications and ML Models", "desc": "ArgoCD architecture: Application controller (reconciles desired state from Git with actual cluster state), API server (Web UI + CLI + API), Repository server (clones Git repos and generates manifests), Redis (cache). The Application resource: source (Git repo + path + revision), destination (cluster + namespace), sync policy (automatic vs. manual approval). Sync waves: order resource creation (dep"},
    {"title": "3.3 Advanced CI/CD for ML: Testing Models Before Production", "desc": "ML models require a different CI/CD paradigm than application code — the artifact isn't code, it's a trained model with statistical properties. The ML CI/CD pipeline stages: code quality (linting, unit tests for preprocessing), integration tests (load model artifact, run inference on test cases, validate output format), performance tests (benchmark inference latency and throughput, compare to base"},
    {"title": "3.4 Canary Deployments for ML Models: Statistical Significance and Traffic Splitting", "desc": "Deploying a new model version to 5% of production traffic while the old version handles 95% — validating improvements before full rollout. Kubernetes traffic splitting approaches: Istio VirtualService (weight-based routing: 95/5 split by percentage), NGINX Ingress canary annotations, Argo Rollouts (purpose-built progressive delivery). The statistical challenge: how much canary traffic do you need "},
    {"title": "3.5 Model Registry Integration: MLflow, SageMaker Model Registry, and Automated Promotion", "desc": "The model registry is the bridge between ML experiment tracking and deployment pipelines. MLflow Model Registry lifecycle: None → Staging → Production → Archived. Automated promotion triggers: CI/CD pipeline registers model after training, runs evaluation against holdout set, promotes to Staging if metrics exceed threshold, requires human approval for Production. Deployment automation: when a mode"},
    {"title": "3.6 Deployment Security: SLSA Framework and Supply Chain Security for AI", "desc": "Supply chain attacks on ML deployment pipelines — SolarWinds-style attacks can compromise model artifacts or infrastructure as code. SLSA (Supply-chain Levels for Software Artifacts) framework: provenance (who built it, from what source, with what process), integrity (artifact not tampered with after build), isolation (build environment hermetically sealed). Signing artifacts: Cosign for container"},
    {"title": "3.7 Module 3 Assessment: Design a Complete ML Deployment Pipeline", "desc": "Architecture challenge: design the complete CI/CD pipeline for a fraud detection model — from training completion to production serving. Include: model quality gates with specific thresholds, container build and signing, ArgoCD Application definition, Argo Rollouts canary strategy with statistical guardrails, rollback triggers, and post-deployment monitoring. Document the approval workflow and aud"}
  ]},
  {"title": "Module 4: Infrastructure as Code — Terraform and Pulumi for AI Platforms", "desc": "Every AI platform resource — VPCs, EKS clusters, GPU node pools, S3 buckets, IAM roles — must be defined in code. Terraform mastery, module design, state management, Atlantis for team workflows, and security scanning.", "lessons": [
    {"title": "4.1 Terraform State Management: Remote Backends, Locking, and Workspace Strategy", "desc": "Terraform state is the mapping between your configuration and real infrastructure — lose it and Terraform can't manage existing resources. Remote state backends: S3+DynamoDB (AWS, most common — S3 stores state, DynamoDB provides atomic locking preventing concurrent applies), GCS+Cloud Storage (GCP), Terraform Cloud/Enterprise (SaaS, with run history). State locking: prevents two engineers from run"},
    {"title": "4.2 Terraform Modules for AI Platform Components: EKS, VPC, and GPU Node Groups", "desc": "Module design for reusable AI infrastructure components. The vpc module: inputs (cidr_block, availability_zones, enable_nat_gateway), outputs (vpc_id, private_subnet_ids, public_subnet_ids). The eks_cluster module: inputs (cluster_name, kubernetes_version, node_groups config), outputs (cluster_endpoint, kubeconfig, oidc_provider_arn). The gpu_node_group module: inputs (instance_type, min_size, max"},
    {"title": "4.3 Terragrunt: DRY Multi-Environment AI Platform Configuration", "desc": "Managing dev/staging/prod with Terraform alone requires duplicating backend configs and provider configs in every module directory. Terragrunt solves this with a hierarchy of terragrunt.hcl files. Root terragrunt.hcl: defines remote state backend once (bucket, key pattern, region). Environment-level terragrunt.hcl: inputs override for environment-specific values (cluster_size: dev=1, staging=3, pr"},
    {"title": "4.4 Atlantis: Pull Request-Based Infrastructure Review and Policy Enforcement", "desc": "Atlantis brings code review discipline to infrastructure — every Terraform change is a PR with plan output as a comment. Architecture: Atlantis server receives GitHub/GitLab webhooks, runs terraform plan on PR open, posts plan output as PR comment, runs terraform apply on PR merge. Approval workflows: require CODEOWNERS approval before apply. OPA (Open Policy Agent) integration: Conftest runs OPA "},
    {"title": "4.5 Pulumi: Python IaC for Complex AI Platform Automation", "desc": "Pulumi uses real programming languages (Python, TypeScript, Go) instead of HCL — enabling loops, conditionals, functions, and testing that HCL can't express cleanly. Pulumi advantages over Terraform: create N GPU node groups from a list of model configurations (Python list comprehension), test infrastructure code with pytest, use Python libraries in infrastructure logic (compute cluster sizing bas"},
    {"title": "4.6 Security Scanning and Policy as Code for AI Infrastructure", "desc": "Every Terraform codebase accumulates security debt — misconfigured security groups, overprivileged IAM roles, unencrypted S3 buckets. Checkov: static analysis for Terraform (2,000+ checks, CIS Benchmark coverage, HIPAA/SOC2 mapping). tfsec: fast Terraform security scanner with custom check support. Integration pattern: run Checkov and tfsec in CI (GitHub Actions) on every PR touching infrastructur"},
    {"title": "4.7 Module 4 Lab: Terraform AI Platform From Zero to Production", "desc": "Complete IaC challenge: write Terraform modules for a complete AI serving platform (VPC, EKS cluster, GPU node group, S3 bucket for model artifacts, IAM roles with IRSA). Implement Terragrunt for dev/prod environments. Run Checkov and fix all HIGH severity findings. Deploy to a real AWS account. Document all resources with tags."}
  ]},
  {"title": "Module 5: SRE Practices and Reliability Engineering for AI Systems", "desc": "Site Reliability Engineering applied to AI — error budgets, SLOs for model serving, incident management, chaos engineering, and the reliability practices that keep AI systems at 99.9%+ availability.", "lessons": [
    {"title": "5.1 The SRE Book Applied to AI: Error Budgets, Toil, and the Reliability Contract", "desc": "Google's SRE book (Beyer et al., 2016) defines the reliability contract between development teams (want to ship features) and operations (want stability). The error budget: if your SLO is 99.9% availability, you have 43.8 minutes of downtime budget per month. When error budget is healthy, ship freely. When error budget is exhausted, reliability work takes priority over features. Applying to AI: mo"},
    {"title": "5.2 Defining SLOs and SLIs for Model Serving: Availability, Latency, and Quality", "desc": "SLO (Service Level Objective) definition for AI model serving. Availability SLI: (successful predictions / total predictions) × 100 — measured over 28-day rolling window. Latency SLI: P99 inference time < 100ms — measured against 1% sample of production requests. Quality SLI: ML-specific — prediction accuracy on labeled production sample > 94%, precision/recall balance for classification models, R"},
    {"title": "5.3 Incident Management: On-Call Rotations, Runbooks, and Post-Mortems", "desc": "Production incidents in AI systems are inevitable — the goal is detection in minutes, response in minutes, resolution in hours, and prevention through post-mortems. On-call structure: primary + secondary rotation, escalation policy (primary → secondary → engineering lead → VP Engineering), PagerDuty integration with alert severity routing. Runbooks: documented response procedures for every categor"},
    {"title": "5.4 Chaos Engineering: Validating AI System Resilience Under Failure", "desc": "Chaos engineering proactively introduces failures to validate that systems behave correctly — and discover reliability gaps before users do. Chaos Monkey (Netflix, 2011): randomly terminates production EC2 instances. Modern chaos engineering with LitmusChaos (Kubernetes-native): pod deletion, CPU stress, memory stress, network partition, disk I/O stress. AI-specific chaos experiments: feature stor"},
    {"title": "5.5 Capacity Planning for AI Workloads: GPU Utilization and Traffic Forecasting", "desc": "AI systems have resource profiles unlike traditional web services — GPU memory is the binding constraint for model serving, training jobs have bursty compute requirements. GPU utilization optimization: p99 utilization should be 60-70% (leave headroom for traffic spikes), GPU memory utilization should be 80%+ (underutilized GPU memory is waste). Traffic forecasting for capacity planning: time-serie"},
    {"title": "5.6 Disaster Recovery and Business Continuity for AI Platforms", "desc": "RTO (Recovery Time Objective) and RPO (Recovery Point Objective) for AI systems. RTO: how long can the business tolerate the AI system being down? (fraud detection: 0 minutes, internal analytics: 4 hours). RPO: how much data loss is acceptable? (training data: 1 hour, model artifacts: 0). DR strategies: warm standby (full replica in secondary region, 5-minute switchover), cold standby (infrastruct"},
    {"title": "5.7 Module 5 Assessment: SRE Design for a Production AI System", "desc": "Design the complete SRE practice for a production recommendation system: define SLOs with measurement methodology, design on-call rotation and escalation policy, write runbooks for the 5 most likely incidents, design chaos experiments to validate reliability, create capacity planning model for 2x traffic growth, and document the DR procedure for a regional failure."}
  ]},
  {"title": "Module 6: Advanced Observability — Distributed Tracing, Metrics, and AI-Specific Monitoring", "desc": "You can't improve what you can't measure. OpenTelemetry for distributed tracing, Prometheus and Grafana for metrics, ELK Stack for log aggregation, and AI-specific monitoring: model drift, prediction latency, and feature health.", "lessons": [
    {"title": "6.1 The Three Pillars of Observability: Metrics, Logs, and Traces for AI Systems", "desc": "Peter Bourgon's 2016 framing of observability as metrics, logs, and traces remains the foundation. Metrics: numerical measurements over time (inference requests/second, GPU utilization, prediction latency P99) — low cardinality, long retention, cheap to store. Logs: timestamped event records (prediction inputs/outputs for debugging, errors with stack traces) — high cardinality, expensive to store "},
    {"title": "6.2 Prometheus and Grafana: Production Metrics for AI Infrastructure", "desc": "Prometheus architecture: pull-based scraping (Prometheus polls /metrics endpoints every 15s), time-series database (chunks stored in local SSD, remote write to Thanos/Cortex for long-term retention), PromQL for query and alerting. Critical AI platform metrics: model_inference_duration_seconds histogram (P50/P95/P99), model_requests_total counter (by model version, status), gpu_utilization gauge (f"},
    {"title": "6.3 OpenTelemetry: Distributed Tracing for Multi-Service AI Pipelines", "desc": "A production prediction request touches 5-10 services: API gateway → auth service → feature store → model server → post-processing → response cache. Without distributed tracing, you can't determine which service caused a 500ms latency spike. OpenTelemetry instrumentation: SDK for Python/Java/Go, auto-instrumentation for common frameworks (FastAPI, Flask, SQLAlchemy, Redis). Trace context propagati"},
    {"title": "6.4 Log Management at Scale: ELK Stack and Structured Logging for AI", "desc": "At 1M predictions/hour, unstructured logs are impossible to analyze — structured JSON logging is mandatory. Structured log format for ML: {timestamp, service, model_version, request_id, prediction, confidence, latency_ms, feature_names, feature_values}. The ELK Stack: Elasticsearch (distributed search and analytics), Logstash/Fluentd/Fluent Bit (log collection and forwarding from Kubernetes pods),"},
    {"title": "6.5 ML-Specific Observability: Model Drift, Prediction Quality, and Shadow Mode", "desc": "Production ML monitoring requires telemetry that generic infrastructure tools can't provide. Model drift monitoring: compare prediction distribution today to baseline (distribution captured at training time). Statistical tests: Population Stability Index (PSI > 0.2 indicates significant drift requiring retraining), Kolmogorov-Smirnov test, Jensen-Shannon divergence. Feature drift: monitor input fe"},
    {"title": "6.6 Cost Observability: Infrastructure Cost Attribution for AI Teams", "desc": "Infrastructure costs without attribution are invisible — and invisible costs don't get optimized. Kubernetes cost attribution with OpenCost: per-namespace cost allocation (ML training namespace vs. serving namespace), per-deployment costs (model-serving-v1 vs. model-serving-v2 cost comparison). GPU cost efficiency: cost_per_prediction metric (total_gpu_cost / total_predictions) — track weekly, ale"},
    {"title": "6.7 Module 6 Lab: Build a Complete AI Observability Stack", "desc": "Hands-on observability project: instrument a Python FastAPI model serving application with OpenTelemetry (traces + metrics), configure Prometheus scraping with custom ML metrics (prediction latency, confidence histograms), set up Grafana dashboards with USE and RED method panels, configure Alertmanager rules for SLO violations, implement structured JSON logging with Fluentd collection, and create "}
  ]},
  {"title": "Module 7: Platform Engineering for ML Teams — Developer Experience and Internal Tools", "desc": "Platform engineering reduces the cognitive load on ML engineers by providing golden paths for common tasks. Internal Developer Portals, self-service ML infrastructure, developer productivity metrics, and the platform engineering practices at Spotify, Backstage, and Airbnb.", "lessons": [
    {"title": "7.1 Platform Engineering Philosophy: The Paved Road and the Enabling Team", "desc": "Platform engineering (Team Topologies: the Enabling Team topology) reduces cognitive load on stream-aligned teams (ML engineers) by providing curated, opinionated tooling for common infrastructure needs. The 'paved road' metaphor: the platform team builds a smooth, well-maintained road (self-service infrastructure, sensible defaults, golden path templates); teams can go off-road (use custom toolin"},
    {"title": "7.2 Backstage: Building an Internal Developer Portal for AI Teams", "desc": "Backstage (open-sourced by Spotify in 2020) is the foundation for Internal Developer Portals. Core features: Software Catalog (searchable registry of all services, models, and datasets with owners and documentation), TechDocs (markdown documentation rendered in the portal), Software Templates (click-to-deploy new services using scaffolding templates). Backstage plugins for ML teams: MLflow plugin "},
    {"title": "7.3 Self-Service GPU Infrastructure: Kubeflow and Argo Workflows for ML Teams", "desc": "ML engineers shouldn't need to understand Kubernetes to run training jobs. Self-service ML infrastructure abstracts the platform complexity. Kubeflow Pipelines: Python SDK for defining ML workflows (data ingestion → preprocessing → training → evaluation → deployment), automatic Kubernetes resource management, experiment tracking integration. Argo Workflows: general-purpose Kubernetes workflow engi"},
    {"title": "7.4 Developer Productivity Metrics: Measuring Platform Impact", "desc": "Measuring the value of platform engineering investments requires rigorous metrics. DORA metrics (DevOps Research and Assessment): Deployment Frequency (how often teams deploy to production), Lead Time for Changes (commit to production time), Change Failure Rate (percentage of deployments causing incidents), Mean Time to Restore (incident resolution time). Space framework (GitHub, 2021): Satisfacti"},
    {"title": "7.5 Multi-Tenancy and Team Isolation for Shared AI Infrastructure", "desc": "A shared ML platform serving 50 teams must isolate workloads for security, cost attribution, and fair resource allocation. Kubernetes namespace isolation: each team gets a dedicated namespace with ResourceQuota (CPU/GPU/memory limits), LimitRange (default requests, maximum per-pod), NetworkPolicy (restrict inter-namespace traffic). RBAC design: team-scoped roles (team leads can create Deployments "},
    {"title": "7.6 Documentation, Runbooks, and the Platform Team Knowledge Base", "desc": "Platform engineering knowledge is worthless if it's not accessible. Documentation-as-code with Backstage TechDocs: Markdown docs in Git, automatically rendered in the portal, versioned with the code they describe. Runbook structure: title, symptoms (what the alert message says), probable causes (ordered by likelihood), investigation steps (specific commands with expected outputs), resolution steps"},
    {"title": "7.7 Module 7 Assessment: Platform Engineering Roadmap", "desc": "Design a complete platform engineering roadmap for a 50-person ML team. Assess current state (DORA metrics, developer satisfaction survey, toil percentage). Prioritize platform investments by impact and effort. Design the self-service developer portal with Backstage, GPU provisioning automation, golden path templates for ML services, and documentation system. Define success metrics for each invest"}
  ]},
  {"title": "Module 8: Security, Compliance, and AI Governance for DevOps Engineers", "desc": "DevSecOps integrates security into every stage of the AI development lifecycle. Container security, secrets management, network policies, SBOM, compliance as code, and the security practices that satisfy SOC2, ISO 27001, and the EU AI Act.", "lessons": [
    {"title": "8.1 DevSecOps: Shifting Security Left in the AI Development Lifecycle", "desc": "Traditional security: security team reviews deployments after they're built. DevSecOps: security controls embedded in every stage of the development lifecycle — catching vulnerabilities at commit time instead of deployment time. The security gates pipeline: pre-commit hooks (secrets detection with detect-secrets, IaC scanning with checkov), PR checks (container image scanning with Trivy, dependenc"},
    {"title": "8.2 Container Security: Scanning, Signing, and Runtime Protection", "desc": "Container images are the deployment artifact for AI systems — and they frequently contain critical vulnerabilities in base image packages. Vulnerability scanning with Trivy: scan container images for CVEs in OS packages, language dependencies, and IaC files. Integrating Trivy in CI/CD: fail builds with CRITICAL CVEs, warn on HIGH, report MEDIUM/LOW. Base image hygiene: use minimal base images (dis"},
    {"title": "8.3 Secrets Management: Vault, External Secrets Operator, and Zero Static Credentials", "desc": "Static credentials (API keys, database passwords) in environment variables or ConfigMaps are the leading cause of cloud security incidents. HashiCorp Vault: secrets engine (KV, database, AWS, PKI), dynamic secrets (Vault generates short-lived database credentials on demand — no static passwords), lease and renewal, audit log. External Secrets Operator (Kubernetes): syncs secrets from AWS Secrets M"},
    {"title": "8.4 Network Security: Zero-Trust Kubernetes with Cilium and Service Mesh", "desc": "Kubernetes default networking: all pods can communicate with all other pods — a compromised pod has network access to every service in the cluster. NetworkPolicy: define explicit allow rules (model-serving pods can only communicate with feature-store and redis; cannot reach etcd or other system components). Cilium: eBPF-based Kubernetes CNI with L7 network policies (allow GET /predict but not POST"},
    {"title": "8.5 Compliance as Code: SOC2, ISO 27001, and EU AI Act for AI Platforms", "desc": "Manual compliance processes (annual audits, Excel checklists) don't scale to continuous deployment. Compliance-as-code automates evidence collection and policy enforcement. OPA/Gatekeeper for Kubernetes compliance: enforce policies that map to controls (CIS Benchmark, NIST 800-53). Cloud Security Posture Management (CSPM): AWS Security Hub, GCP Security Command Center — automated scanning against "},
    {"title": "8.6 SBOM, Dependency Management, and AI Supply Chain Security", "desc": "The SolarWinds attack (2020) demonstrated that supply chain compromise can affect 18,000 organizations simultaneously — through a trusted software update mechanism. SBOM (Software Bill of Materials): a machine-readable inventory of all components in a software artifact. SBOM formats: SPDX (Linux Foundation standard), CycloneDX (OWASP standard, ML-specific extensions for model components). Generati"},
    {"title": "8.7 Module 8 Assessment: Security Architecture Audit", "desc": "Conduct a complete security audit of a provided AI platform architecture. Identify and remediate: exposed secrets in environment variables, missing NetworkPolicies, unsigned container images, overprivileged RBAC roles, unencrypted secrets, missing audit logging, and compliance gaps against SOC2 Type II controls. Produce a risk-ranked remediation roadmap."}
  ]},
  {"title": "Module 9: Cost Engineering — FinOps for GPU-Heavy AI Infrastructure", "desc": "GPU compute is expensive — a single A100 costs $32/hour. FinOps for AI infrastructure covers spot instance strategies, reserved capacity optimization, multi-cloud cost arbitrage, and the practices that reduce AI infrastructure costs by 40-70%.", "lessons": [
    {"title": "9.1 The AI Infrastructure Cost Problem: Why GPU Bills Spiral Out of Control", "desc": "The AI infrastructure cost problem is unique among software costs: a single training run for a large model can cost $500K-$10M in GPU compute. The cost spiral pattern: research team provisions GPU clusters on-demand (3x cost premium), leaves clusters running overnight (GPU utilization: 12% during off-hours), uses redundant experiments without cost tracking (no visibility into per-experiment cost),"},
    {"title": "9.2 Spot and Preemptible Instances: 80% Cost Reduction for Training", "desc": "AWS Spot Instances and GCP Preemptible VMs offer GPU compute at 60-80% discount in exchange for interruption risk (instances can be reclaimed with 2-minute warning). The critical engineering requirement: training jobs must checkpoint state periodically so interruption means resuming from last checkpoint rather than restarting from scratch. Checkpointing strategies: PyTorch save_checkpoint() every "},
    {"title": "9.3 Reserved Instances and Savings Plans: Optimizing Baseline GPU Spend", "desc": "For predictable baseline GPU usage (model serving, continuous training pipelines), Reserved Instances and Savings Plans provide 30-60% discounts over on-demand pricing. AWS Savings Plans: Compute Savings Plans (most flexible — applies to any EC2, ECS, Lambda compute), EC2 Instance Savings Plans (specific family commitment, highest discount — up to 72%). Commitment strategy: analyze 3-month usage h"},
    {"title": "9.4 GPU Utilization Optimization: Profiling, Batching, and Quantization", "desc": "A GPU running at 30% utilization costs the same as one at 95% utilization — optimization is pure cost reduction. GPU profiling tools: NVIDIA Nsight Systems (timeline visualization of CPU/GPU activity, memory transfers), PyTorch Profiler (operator-level timing, memory allocation), DCGM (fleet-level utilization metrics). Batching for inference: serving a batch of 32 requests simultaneously increases"},
    {"title": "9.5 Multi-Cloud Cost Arbitrage for AI Workloads", "desc": "GPU availability and pricing differ across AWS, GCP, and Azure — and multi-cloud enables cost arbitrage. GPU price comparison (2024): A100 80GB — AWS p4d.24xlarge ($32.77/hr), GCP a2-megagpu-16g ($27.70/hr), Azure Standard_ND96asr_v4 ($32.77/hr). H100 pricing: AWS p5.48xlarge ($98.32/hr), GCP a3-megagpu-8g ($111.29/hr). Spot availability varies: during GPU shortages, diversifying across clouds red"},
    {"title": "9.6 FinOps Culture: Cost Visibility, Accountability, and Continuous Optimization", "desc": "FinOps is a cultural practice as much as a technical one — the most sophisticated cost optimization tooling fails without organizational accountability. The FinOps operating model: Inform (make costs visible — daily cost dashboard by team, per-experiment cost tracking), Optimize (identify waste — idle GPUs, oversized instances, unnecessary data transfer), Operate (continuously improve — monthly co"},
    {"title": "9.7 Module 9 Capstone: AI Infrastructure Cost Optimization Audit", "desc": "Complete FinOps audit of a provided AI infrastructure setup: identify GPU underutilization (utilization < 60%), over-provisioned instances, missed Savings Plan opportunities, training jobs that could run on Spot, models that could benefit from quantization. Produce a cost optimization roadmap with specific actions, estimated savings, and implementation timeline. Target: 40% cost reduction within 9"}
  ]},
  {"title": "Module 10: Production AI Systems — Architecture Patterns, Scaling, and the Future of AI DevOps", "desc": "Bringing together all modules into complete AI system architectures. Multi-region AI serving, LLM serving infrastructure, edge AI deployment, the EU AI Act's technical requirements, and your career roadmap as an AI DevOps Engineer.", "lessons": [
    {"title": "10.1 Production AI Architecture Patterns: From Single Model to AI Platform", "desc": "The evolution of AI infrastructure maturity. Level 1 (single model): Flask API + single GPU server — appropriate for 100 req/day. Level 2 (model serving): Kubernetes deployment + load balancer + monitoring — 10,000 req/day. Level 3 (ML platform): feature store + model registry + CI/CD + observability — 100 models. Level 4 (AI platform): self-service infrastructure + governance + FinOps + complianc"},
    {"title": "10.2 LLM Serving Infrastructure: vLLM, Triton, and Production Scale", "desc": "Serving large language models in production requires specialized infrastructure. vLLM: PagedAttention algorithm (manages KV cache as virtual memory pages, enabling 24x more concurrent users than naive serving), continuous batching (dynamically adds requests to running batches — eliminates padding waste), tensor parallelism (split model across multiple GPUs). NVIDIA Triton Inference Server: model e"},
    {"title": "10.3 Multi-Region AI Serving: Latency, Data Residency, and Global Load Balancing", "desc": "Serving AI predictions to global users requires multi-region infrastructure. Latency impact: an inference request from São Paulo to us-east-1 adds 130ms RTT — unacceptable for real-time applications. Multi-region patterns: active-active (model serving in every region, global load balancing routes to nearest), active-passive (primary region serves all traffic, secondary on standby), edge deployment"},
    {"title": "10.4 Edge AI Deployment: TensorFlow Lite, ONNX Runtime, and Embedded Inference", "desc": "Edge AI runs inference on devices (phones, cameras, vehicles, IoT sensors) without cloud round-trips — enabling real-time responses with privacy preservation and offline capability. ONNX (Open Neural Network Exchange): export models from PyTorch/TensorFlow to a standardized format, optimize with ONNX Runtime for CPU/GPU/NPU acceleration. TensorFlow Lite: quantized model format for mobile and embed"},
    {"title": "10.5 EU AI Act Technical Requirements for DevOps Engineers", "desc": "The EU AI Act (effective August 2024, enforcement from August 2026) imposes technical requirements on AI systems that AI DevOps engineers must implement. High-risk AI systems (credit scoring, hiring, medical devices) require: technical documentation (training data sources, model architecture, performance metrics), data governance measures (training data quality assessment, bias evaluation), accura"},
    {"title": "10.6 The Future of AI DevOps: Platform Engineering, AI Agents, and What's Next", "desc": "The AI DevOps landscape is evolving faster than any adjacent engineering discipline. Near-term (2025-2026): AI-assisted infrastructure (GitHub Copilot for IaC, AI-generated runbooks, AI-powered anomaly detection replacing threshold-based alerting), GPU-as-a-Service abstraction (platform teams hide GPU scheduling complexity behind simple APIs), eBPF becoming the universal observability substrate (C"},
    {"title": "10.7 Capstone: Design and Present a Complete AI DevOps Architecture", "desc": "Final capstone project: design the complete AI DevOps architecture for a Series C AI company. Deliverables: infrastructure architecture diagram (all components from VPC to monitoring), CI/CD pipeline design for model deployment, Kubernetes resource configuration, cost optimization strategy with projected annual savings, security architecture against OWASP Top 10 for ML, observability stack design,"}
  ]}
]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    // SECURITY: founder/admin only — this seeder writes content with the service role.
    const __adminCheck = await requireAdmin(req);
    if (__adminCheck instanceof Response) return __adminCheck;
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const COURSE_TITLE = courseData.title;
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({ title: courseData.title, description: courseData.description, is_published: true, translations: courseData.translations }).select().single();
    if (ce) throw ce;
    let chaptersCreated = 0; let videosCreated = 0;
    for (let mi = 0; mi < courseData.modules.length; mi++) {
      const mod = courseData.modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: mod.title, description: mod.desc, order_index: mi, translations: {} }).select().single();
      if (che) throw che; chaptersCreated++;
      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = les.title + "\n\n" + les.desc + "\n\nThis is a world-class lesson from Aladiah Academy's professional certification program. Prof. Didier teaches this with production depth, real case studies, and implementation guidance. Module context: " + mod.title + ". " + mod.desc;
        const trans = { en:{title:les.title,transcript}, es:{title:les.title,transcript}, fr:{title:les.title,transcript}, de:{title:les.title,transcript}, zh:{title:les.title,transcript}, ar:{title:les.title,transcript}, ja:{title:les.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: les.title, description: les.desc, order_index: li, translations: trans }).select().single();
        if (ve) throw ve; videosCreated++;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: "What production expertise does this lesson build?", scenario_context: "Applying this in a professional role.", options: [les.desc.substring(0,120)+"...", "Only theoretical background", "Covered elsewhere", "Optional content"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: "Which real-world organizations' practices are referenced?", scenario_context: "Grounding knowledge in production reality.", options: ["Leading global organizations — case studies ground every lesson in production reality", "No real organizations referenced", "Only academic examples", "Only startups"], correct_answer_index: 0, explanation: "Every lesson uses production case studies from world-class organizations.", order_index: 1 },
        ]);
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: "What expert-level competency does this module develop?", scenario_context: "Module completion assessment.", options: [mod.desc.substring(0,140)+"...", "Only introductory familiarity", "Theoretical knowledge only", "Not career-relevant"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "What career level does mastery of this module support?", scenario_context: "Professional development planning.", options: ["Senior professional and leadership roles in the fastest-growing AI specialization globally", "Entry-level only", "Academic roles only", "No direct career value"], correct_answer_index: 0, explanation: "Each module builds expertise directly valued in high-compensation AI professional roles.", order_index: 1 },
      ]);
    }
    return new Response(JSON.stringify({ message: courseData.title + " — 10-module world-class version seeded", courseId: course.id, modules: chaptersCreated, lessons: videosCreated }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
