import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const courseData = {
  title: "AI DevOps Engineer",
  description: "Master the CI/CD pipelines, GitOps workflows, infrastructure automation, and observability practices that ship AI systems to production reliably. Grounded in DORA research, the DevOps Handbook, and practices from Netflix, Google, and Amazon.",
  chapters: [
    {
      title: "Module 1: DevOps Foundations, DORA Research, and CI/CD for AI",
      description: "The science of high-performing engineering teams — four metrics that predict business outcomes, the culture required for DevOps transformation, and CI/CD pipelines built specifically for AI systems.",
      order_index: 0,
      videos: [
        {
          title: "1.1 The DORA Research: What Separates Elite DevOps Teams from the Rest",
          description: "Nicole Forsgren, Jez Humble, and Gene Kim's landmark Accelerate research — the four keys, psychological safety, and what it all means for AI engineering teams.",
          order_index: 0,
          lessonScript: {
            mainPoints: [
              "The DORA (DevOps Research and Assessment) program, founded by Nicole Forsgren, Jez Humble, and Gene Kim, represents the most rigorous scientific study of software delivery ever conducted — spanning six years, 36,000+ survey respondents, and published in their 2018 book 'Accelerate: The Science of Lean Software and DevOps.' The central finding is both simple and profound: software delivery performance is measurable, it varies enormously between organizations, and it directly predicts business outcomes including profitability, market share, and productivity. For AI DevOps engineers, this research provides the scientific foundation for every CI/CD and operational practice decision you make. This isn't opinion — it's peer-reviewed statistical analysis that changed how the world thinks about software engineering.",

              "DORA identified four key metrics — the 'four keys' — that characterize software delivery performance. Deployment Frequency: how often does your organization deploy to production? Elite performers deploy multiple times per day; low performers fewer than once per month. Lead Time for Changes: from code commit to running in production? Elite: under one hour. Low: one to six months. Time to Restore Service (MTTR): how long to recover from a production incident? Elite: under one hour. Low: one week to one month. Change Failure Rate: what percentage of deployments cause production failure? Elite: 0-15%. Low: 46-60%. The most important insight: elite performers deploy MORE frequently AND have LOWER failure rates — definitively disproving the false tradeoff between speed and stability that paralyzes many engineering organizations.",

              "The 2023 DORA State of DevOps Report added a fifth metric: Reliability, measured as meeting SLO targets. Elite performers meet their SLOs 100% of the time; low performers only 50%. The report also introduced the concept of 'platform engineering' as a key driver of developer productivity — teams with Internal Developer Platforms (IDPs) that provide self-service infrastructure show 4x improvement in delivery performance. For AI systems specifically, reliability has unique dimensions beyond uptime: model serving reliability (prediction API availability), data pipeline reliability (feature freshness), and model quality reliability (predictions remain accurate within defined thresholds). An AI system can have 99.9% infrastructure uptime but 40% model quality reliability — tracking all three dimensions requires AI-specific observability beyond standard DevOps metrics.",

              "Nicole Forsgren's research identified the technical capabilities driving high performance across five categories. Continuous Delivery practices (version control, deployment automation, trunk-based development, test automation, shift-left security) have the highest measured impact on DORA metrics. Architecture practices (loosely coupled systems, empowered teams) enable high deployment frequency without cross-team coordination overhead — a monolithic AI platform requiring 10 teams to coordinate for each model deployment is architecturally constrained from achieving elite performance. Product management practices (small batches, visible work, limited WIP) reduce lead time. Lean management practices (lightweight change approval, proactive monitoring) reduce MTTR. Cultural practices (generative culture, learning from failure) create the foundation for all other capabilities.",

              "The Knight Capital incident of August 1, 2012 — $440 million lost in 45 minutes — is the canonical case study for what happens when DevOps principles are violated at catastrophic scale. Knight Capital deployed new trading software to 7 of 8 production servers; the 8th still ran 2003 code that reactivated a dormant feature when a specific flag was set. The new code set that flag. For 45 minutes, one server executed 4 million unintended trades accumulating a $7 billion position. Root causes: no automated deployment verification (did all 8 servers update?), no automated rollback (no mechanism to detect and revert partial deployment), no tested kill switch. Knight Capital filed for bankruptcy 4 days later. For AI DevOps: automated verification that all inference servers run the same model version, automated rollback triggers, and tested kill switches are not optional practices — they are existential requirements.",

              "Gene Kim's 'Three Ways' framework from 'The Phoenix Project' and 'The DevOps Handbook' provides the mental model for DevOps transformation. The First Way: Flow — optimize the flow of work from Development through Operations to the customer. Everything slowing this flow (long approval chains, manual testing, large batch deployments) reduces performance. The Second Way: Feedback — create feedback loops at every stage so problems are detected and fixed immediately. Fast CI/CD pipelines are feedback loops; monitoring alerts are feedback loops; post-incident reviews are feedback loops. The Third Way: Continual Learning and Experimentation — create a culture where experimentation is encouraged and failures are learning opportunities. For AI teams, the feedback dimension is especially critical: a model deployed without monitoring has no feedback loop, meaning model degradation is discovered by customers, not engineers — the most expensive and damaging form of discovery.",

              "Psychological safety — the belief that one can speak up, make mistakes, and take risks without fear of punishment — is the #1 predictor of team performance according to both Google's Project Aristotle (2016) and the DORA research. Amy Edmondson's research at Harvard showed high-performing medical teams reported more errors, not fewer — because they felt safe to report problems early, enabling faster resolution. The DORA research found that generative organizational culture (high cooperation, messengers are rewarded, risks are shared, failures lead to inquiry not blame) predicts both software delivery performance and organizational performance. For AI DevOps teams: psychological safety determines whether engineers report pipeline failures immediately (enabling fast resolution) or hide them (leading to cascading failures). It determines whether post-incident reviews find systemic improvements or assign individual blame — making culture a technical concern with measurable business impact."
            ]
          },
          questions: [
            { question_text: "What false tradeoff did the DORA research definitively disprove?", scenario_context: "Your CTO argues that deploying more frequently will increase production incidents.", options: ["Cost vs. quality tradeoff", "Elite performers deploy more frequently AND have lower failure rates — speed and stability are complementary outcomes of good DevOps, not opposing forces", "Security vs. functionality tradeoff", "Speed only applies to small teams"], correct_answer_index: 1, explanation: "DORA's analysis of 36,000+ respondents found elite performers (multiple deploys/day) have 0-15% change failure rates while low performers (monthly deploys) have 46-60% failure rates. The automation and small batches that enable speed also reduce failure rates — disproving the tradeoff." },
            { question_text: "What three DevOps failures caused the Knight Capital $440M loss?", scenario_context: "Reviewing deployment practices to prevent a similar incident.", options: ["Poor code quality, slow testing, bad architecture", "No automated deployment verification (partial update undetected), no automated rollback (couldn't revert quickly), and no tested kill switch (emergency stop never validated)", "Too many deployments per day", "Insufficient developer training"], correct_answer_index: 1, explanation: "Knight Capital required no sophisticated failure — just a partial deployment (7/8 servers updated) with no safety nets. All three missing controls are now table stakes for production deployments: verify completeness, automate rollback, test kill switches." },
            { question_text: "What is DORA Lead Time for Changes and what does elite look like?", scenario_context: "Benchmarking your team's delivery performance.", options: ["Time between hiring engineers", "Time from code commit to running in production — elite: under 1 hour. Achieved through automated CI/CD, small PRs, fast automated testing, and automated deployment with no manual approval gates for normal changes.", "Time between major releases", "Time to resolve customer tickets"], correct_answer_index: 1, explanation: "Lead time under 1 hour characterizes elite teams. The compounding effect: faster lead time means faster error correction (MTTR), faster feature delivery, and smaller batch sizes — all of which reduce change failure rate. Lead time is the 'master metric' that improves all others." },
            { question_text: "What does the DORA 'Second Way' (Feedback) mean for AI model deployments?", scenario_context: "Your model was degrading for 2 weeks before a customer reported it.", options: ["Getting user feedback surveys", "Creating fast feedback loops at every stage — model monitoring is a feedback loop that catches degradation in minutes (not weeks). Without monitoring, customer complaints are your feedback loop — the slowest and most expensive form.", "Feedback from code review", "A/B test results from users"], correct_answer_index: 1, explanation: "The Second Way demands feedback loops throughout the system. A deployed model without monitoring has only one feedback mechanism: customer complaints. Model performance monitoring creates an engineering feedback loop — degradation detected in minutes by dashboards, not weeks by user support tickets." },
            { question_text: "Why does the DORA research classify organizational culture as a technical engineering concern?", scenario_context: "Making the case for investing in blameless post-incident reviews.", options: ["It isn't — culture is HR's domain", "Generative culture statistically predicts delivery performance metrics — blameless cultures find failures faster (people report immediately) and fix root causes (PIRs are honest). Blame cultures hide failures until they cascade, measurably increasing MTTR and change failure rate.", "Culture only affects large organizations", "Culture impacts morale but not metrics"], correct_answer_index: 1, explanation: "DORA's statistical analysis shows culture directly predicts MTTR and change failure rate. Blameless cultures: engineers report failures fast (low MTTR) and PIRs find real root causes (low repeat incidents). Blame cultures: engineers hide failures (high MTTR) and PIRs assign blame rather than fixing systems (high repeat incidents)." }
          ]
        },
        {
          title: "1.2 CI/CD Pipeline Architecture for AI Systems",
          description: "Building production-grade CI/CD specifically for AI — model quality gates, artifact management, deployment strategies, and the automated safety nets that prevent bad models from reaching users.",
          order_index: 1,
          lessonScript: {
            mainPoints: [
              "Continuous Integration and Continuous Delivery are the technical practices that make high deployment frequency possible without sacrificing reliability. CI means every code commit is automatically integrated and validated by an automated test suite — developers get feedback within minutes, not days. CD means every passing build is automatically prepared for deployment — the deployment process itself is automated, reliable, and repeatable. Together, CI/CD is the assembly line that takes a commit and produces a production-ready artifact. For AI systems, CI/CD has requirements beyond traditional software: model quality must be evaluated (not just code correctness), model artifacts (gigabytes of weights) require specialized versioning, and deployments may need shadow traffic or canary evaluation before full rollout.",

              "GitHub Actions has become the dominant CI/CD platform for AI systems. A GitHub Actions workflow defines: triggers (on push to main, on pull_request, on schedule), jobs (parallel or sequential units of work), and steps (individual commands within a job). A production AI CI/CD PR workflow runs three parallel jobs: code-quality (black, isort, flake8, mypy for Python formatting and type checking), unit-tests (pytest on data processing code with coverage requirements for critical paths), and security-scan (Bandit for Python security issues, Safety for dependency CVEs, Trivy for container image vulnerabilities). A fourth job — model-smoke-test — runs only on merges to main: trains on 5% of data, validates accuracy above minimum threshold, and fails the pipeline if below. This architecture catches four categories of problems before any code reaches production.",

              "Model quality gates are the CI/CD component that prevents bad models from reaching production — the critical differentiator of AI CI/CD from standard software pipelines. A quality gate is an automated check with pass/fail criterion that blocks deployment if not met. Production quality gate suite: accuracy threshold (F1 > 0.85 on held-out test set), bias test (no statistically significant performance difference across demographic groups — using IBM AI Fairness 360 or Google Fairness Indicators), latency gate (p95 inference latency must be under 100ms under load test), regression test (new model must perform at least as well as the current production model on a fixed evaluation set), and data quality gate (training data must pass Great Expectations validations). All gates must pass; any single failure blocks the entire pipeline. At Lyft, implementing model quality gates in their CI pipeline reduced production model failures by 85%.",

              "The model artifact registry — MLflow, Weights & Biases, or Vertex AI Model Registry — connects CI/CD pipelines to deployment systems. Every successful training run produces an artifact logged to the registry with: semantic version (v2.3.1), Git SHA of the producing code, dataset version used for training, all quality gate results (accuracy, latency, bias scores), and training run ID for complete lineage. The staging workflow — Staging → Production → Archived — provides governance: Staging is for automated CI/CD promotion after quality gate passage; Production requires either manual approval or an automated A/B test gate showing the new model is statistically significantly better than the current production model; Archived retains retired models for compliance auditing. Without a registry, teams lose track of what's deployed, can't roll back reliably, and can't answer the audit question: 'what model was serving predictions on January 15th?'",

              "The Facebook 2021 outage — six hours of complete unavailability for 3.5 billion users, estimated $60M revenue loss — provides a critical CI/CD lesson: runbooks and rollback procedures must be tested before incidents. On October 4, 2021, an automated network configuration CI/CD deployment accidentally withdrew all Facebook BGP routes, making DNS servers and all services unreachable. Recovery was delayed because: engineers needed physical data center access (remote access systems also went down), the emergency runbook assumed network connectivity that didn't exist, and the rollback procedure had never been tested in a real outage. For AI DevOps: test your rollback procedures monthly. Run chaos engineering exercises that simulate production failures. Verify emergency access procedures work when normal access paths are unavailable. The difference between a 30-minute recovery and a 6-hour recovery is almost always preparation.",

              "Deployment strategies for AI model updates require different approaches than traditional software because model changes affect prediction quality — not just functionality. The four strategies with increasing safety: Rolling update — replace model server instances one at a time; zero downtime, no special infrastructure, instant rollback by redeploying old version. Blue-green — two identical environments; switch traffic at load balancer level; instant rollback but requires 2x infrastructure cost. Canary — route small percentage (1-5%) to new model; monitor metrics; progressively increase; best risk management; requires metric comparison infrastructure. Shadow (dark launch) — new model receives all traffic and computes predictions but results aren't served to users; safest for validating model behavior; requires 2x inference cost. Netflix uses canary with automated rollback for all production model changes: if any metric (accuracy proxy, latency, error rate) degrades beyond configured threshold, the canary automatically reverts to 0% — no human intervention required.",

              "Trunk-based development — all developers commit to a single main branch rather than long-lived feature branches — is the version control practice most strongly correlated with elite delivery performance in DORA research. Feature flags enable trunk-based development safely: new code merges to main but is hidden behind a flag disabled in production until ready. For AI systems, feature flags serve a distinct additional purpose: enabling gradual model rollouts. A 'new_recommendation_model' flag routes 5% of users to the new model; 95% continue with the current model — real-traffic evaluation without full deployment risk. Tools: LaunchDarkly (commercial, full-featured, ML-specific targeting), Unleash (open-source, self-hosted), Split.io (commercial). The technical implementation: the model serving router reads the flag state per request and selects the appropriate model version. Flag consistency (the same user always sees the same model) is critical for A/B test validity — inconsistent assignment invalidates statistical comparisons."
            ]
          },
          questions: [
            { question_text: "What makes an AI CI/CD pipeline fundamentally different from a standard software pipeline?", scenario_context: "Explaining to a traditional DevOps engineer why you need additional pipeline stages for ML.", options: ["AI pipelines require more compute", "AI pipelines must validate model quality (accuracy, bias, latency) not just code correctness, manage gigabyte model artifacts requiring specialized versioning, and use deployment strategies (canary, shadow) specific to probabilistic system validation", "AI pipelines use different languages", "AI pipelines don't need unit tests"], correct_answer_index: 1, explanation: "Traditional CI/CD validates 'does the code work correctly?' AI CI/CD additionally validates 'does the model perform accurately, fairly, and within latency requirements?' — requiring quality gates, artifact registries with training lineage, and deployment strategies designed for probabilistic rather than deterministic systems." },
            { question_text: "What five quality gates should a production AI deployment pipeline include?", scenario_context: "Designing quality gates for a customer-facing recommendation model.", options: ["Code review, unit tests, integration tests, performance tests, security scans", "Accuracy threshold (F1 > 0.85), bias test (no demographic disparity), latency gate (p95 < 100ms under load), regression test (no worse than production baseline), and data quality gate (training data passes validation). All must pass; any failure blocks deployment.", "Manual review by data science team", "Only accuracy and latency checks"], correct_answer_index: 1, explanation: "Each gate catches a different failure mode: accuracy (model too inaccurate), bias (model discriminatory), latency (model too slow), regression (model worse than what it replaces), data quality (corrupt training data). Lyft's 85% reduction in production failures came from implementing all five as CI/CD gates." },
            { question_text: "What is shadow deployment and when should you use it over canary?", scenario_context: "Preparing to deploy a new fraud detection model where even 1% degradation causes real financial harm.", options: ["Deploying to a shadow (staging) environment", "New model receives all production traffic and computes predictions but results aren't served to users — enabling full production validation with zero user impact. Use when even 1% of users experiencing degraded quality is unacceptable, like fraud detection where missed fraud directly causes financial loss.", "A backup model activated during outages", "Running parallel models for comparison in dev"], correct_answer_index: 1, explanation: "Shadow mode provides the highest safety: real production traffic patterns, real data distributions, zero user impact. Canary always exposes some users (1-5%) to risk. For fraud detection, shadow validates the new model processes real transactions correctly before any decision affects actual fraud outcomes." },
            { question_text: "Why did Facebook's 6-hour outage reveal an untested rollback as the critical failure?", scenario_context: "Reviewing your emergency response procedures after the incident.", options: ["Facebook's software had critical bugs", "The automated CI/CD deployment withdrew all BGP routes; recovery took 6 hours because rollback procedures assumed network connectivity that didn't exist and had never been tested in a real outage. Lesson: test rollback procedures and emergency access paths before incidents.", "Facebook's hardware was faulty", "The incident was caused by a cyberattack"], correct_answer_index: 1, explanation: "Facebook's automated network config deployment caused the outage; untested rollback procedures caused the 6-hour recovery. Runbooks written and never tested fail during incidents. Monthly rollback drills would have revealed the dependency on network connectivity before it mattered. Test your recovery procedures before you need them." },
            { question_text: "How do feature flags enable safe trunk-based development for AI model rollouts?", scenario_context: "Rolling out a new recommendation model to 5% of users while maintaining rollback capability.", options: ["Feature flags are only for UI changes", "Flags route specific users to the new model version (5%) vs. current model (95%) — enabling real-traffic validation without full deployment. Rollback is instant (flip flag to 0%). User consistency (same user always gets same model) is critical for valid A/B test statistics.", "Feature flags require separate infrastructure", "Flags only work for binary on/off features"], correct_answer_index: 1, explanation: "Feature flags give you gradual rollout control at the application level — more flexible than infrastructure canary because you can target by user segment, not just random percentage. The consistency requirement prevents users from seeing different model behavior between requests, which would corrupt A/B test statistics." }
          ]
        },
        {
          title: "1.3 GitOps for AI Platforms: ArgoCD, Flux, and Infrastructure as Code",
          description: "How GitOps principles make AI platform infrastructure declarative, auditable, and self-healing — preventing the configuration drift that silently degrades AI system reliability.",
          order_index: 2,
          lessonScript: {
            mainPoints: [
              "GitOps — coined by Alexis Richardson at WeaveWorks in 2017 — extends Infrastructure as Code with a specific operational model: Git is the single source of truth for all infrastructure state, and automated controllers continuously reconcile actual system state with the desired state declared in Git. The operational guarantee: the only way to change production infrastructure is through a Git commit that passes code review. Manual kubectl edits, console changes, and emergency 'quick fixes' are automatically reverted. For AI platform engineers, GitOps solves configuration drift — the silent accumulation of undocumented changes that makes AI systems unreliable over time. WeaveWorks' research found 78% of production incidents in non-GitOps organizations involved configuration drift as a contributing factor.",

              "ArgoCD (CNCF graduated project) is the leading Kubernetes GitOps controller with a reconciliation loop: every 3 minutes, ArgoCD compares live cluster state with desired state in your Git repository. If they differ — an engineer manually scaled a deployment, changed an environment variable, or added a label — ArgoCD reports the application as 'OutOfSync' and either auto-reconciles or alerts for review. For AI platforms with dozens of model serving deployments, ArgoCD provides: a single dashboard showing health and sync status of every deployment, one-click rollback to any previous Git commit, and automatic recovery if a deployment crashes. The organizational impact: Lyft, Intuit, and Datadog use ArgoCD to manage ML platform Kubernetes deployments — their GitOps adoption reduced configuration-related incidents by over 60%.",

              "Secret management in GitOps requires special architecture because secrets cannot be stored in plaintext in Git. Three production patterns: Sealed Secrets (Bitnami) encrypts secrets client-side using a public key — the SealedSecret resource is safe to commit to Git; the cluster controller decrypts using the private key. External Secrets Operator syncs secrets from AWS Secrets Manager, HashiCorp Vault, or GCP Secret Manager into Kubernetes Secrets — secrets never touch Git, the operator fetches from the authoritative source with automatic rotation. Vault Agent Injector injects secrets directly into pod filesystems at startup — zero secret storage in Kubernetes etcd. For AI platforms with OpenAI API keys, vector database credentials, and feature store credentials across environments, External Secrets Operator with AWS Secrets Manager is the production standard: centralized management, automatic rotation, CloudTrail audit logging, and IAM-based access control.",

              "Kustomize and Helm serve complementary roles in GitOps configuration management. Helm packages Kubernetes resources into versioned charts with values file parameterization — ideal for distributing reusable application packages (model serving templates, monitoring stacks) with extensive customization options. Kustomize uses patch-based overlays — base/ defines canonical configuration, overlays/dev/ overlays/staging/ overlays/prod/ apply environment-specific patches (different replica counts, resource limits, image tags). Kustomize is built into kubectl (zero additional tools), preferred by the Kubernetes community for internal configuration management. Production AI platform pattern: Helm for third-party dependencies (NGINX ingress, Prometheus, cert-manager — versioned charts from public repositories), Kustomize for your own model serving configurations (patch-based environment differences on internal manifests).",

              "The Terraform + ArgoCD workflow is the production standard for complete AI platform infrastructure management. Terraform manages cloud infrastructure (VPCs, EKS clusters, IAM roles, RDS databases, S3 buckets) — stateful resources existing outside Kubernetes. ArgoCD manages Kubernetes resources (Deployments, Services, ConfigMaps, Secret references) — the application layer on top of Terraform-provisioned infrastructure. The governance workflow: an engineer creates a PR modifying either Terraform (infrastructure) or Kubernetes manifests (application), automated validation runs (terraform plan, manifest validation, Checkov security scan), a second engineer reviews, PR merges, the appropriate controller applies the change. Neither Terraform nor ArgoCD runs outside this PR workflow in production — any local terraform apply or kubectl apply violates the GitOps contract and creates audit trail gaps.",

              "Infrastructure drift is the silent killer of AI platform reliability — the accumulation of undocumented, unreviewed changes to production systems. The mechanism: an engineer makes a quick fix to a model serving configuration (increases memory limit to resolve an OOMKill), doesn't document it, doesn't create a PR. Three months later, the configuration is overwritten by a routine deployment. The OOMKill returns. The engineer who made the fix is no longer on the team. Nobody knows why memory was increased. This scenario is ubiquitous in organizations without GitOps discipline. The cumulative effect: production systems become 'snowflakes' — unique configurations that can't be reproduced, can't be audited, and fail in ways nobody understands. GitOps eliminates this failure category entirely: the only authoritative state is Git, and controllers enforce it continuously.",

              "Multi-cluster GitOps management becomes necessary as AI platforms grow — separate clusters for dev, staging, and production, potentially across regions or cloud providers. ArgoCD's ApplicationSet resource dynamically creates ArgoCD Applications across multiple clusters from a single template: instead of manually creating 30 ArgoCD Applications for 10 model serving services across 3 clusters, one ApplicationSet with a cluster generator creates all 30 automatically. The cluster generator iterates over registered clusters; the template defines per-cluster values (environment name, resource limits, replica counts). For AI platforms: dev cluster gets 1 replica with small instances; production gets 3 replicas with GPU instances — same ApplicationSet template, different cluster-specific values. Flux's multi-tenancy model provides an alternative: each team manages their own Flux configuration in their namespace, with the platform team managing the cluster-wide Flux installation."
            ]
          },
          questions: [
            { question_text: "What is the core GitOps guarantee and how does it prevent AI platform configuration drift?", scenario_context: "An engineer manually patched a model server config at 3am; the fix was overwritten by the next deployment.", options: ["GitOps guarantees faster deployments", "The only way to change production infrastructure is through a reviewed Git commit — automated controllers revert all manual changes. All production state is auditable, reviewed, and reproducible, eliminating mystery configurations that cause incidents when overwritten.", "GitOps only applies to Kubernetes", "GitOps prevents all incidents"], correct_answer_index: 1, explanation: "GitOps makes Git authoritative — ArgoCD reverts any manual change diverging from Git state. The 3am manual patch must be committed to Git (creating an audit trail) before the controller maintains it. No more configurations that get overwritten and cause recurring incidents because nobody documented why they were made." },
            { question_text: "What is External Secrets Operator and why is it the production standard for AI platform secrets?", scenario_context: "Managing OpenAI API keys, vector database credentials, and feature store credentials across dev/staging/prod.", options: ["A tool for encrypting Kubernetes secrets", "Syncs secrets from AWS Secrets Manager/Vault/GCP Secret Manager into Kubernetes Secrets automatically — secrets never touch Git, are centrally managed with rotation and audit logging in Secrets Manager, and automatically updated when rotated. One source of truth for all secrets across all clusters.", "A Git-based secret storage system", "A manual secret rotation tool"], correct_answer_index: 1, explanation: "External Secrets Operator provides: secrets never in Git (no accidental exposure), centralized rotation in Secrets Manager (rotate once, synced everywhere automatically), CloudTrail audit trail (every access logged), and IAM access control (which pods can access which secrets). Superior to Sealed Secrets for enterprise environments requiring rotation and auditing." },
            { question_text: "What did WeaveWorks find about configuration drift and production incidents?", scenario_context: "Making the business case for GitOps adoption.", options: ["Configuration drift causes 10% of incidents", "78% of production incidents in non-GitOps organizations involved configuration drift as a contributing factor — undocumented manual changes creating snowflake systems that fail in ways nobody understands. GitOps eliminates this entire failure category.", "Drift only affects databases", "GitOps has no measurable incident reduction"], correct_answer_index: 1, explanation: "78% incident involvement makes configuration drift the largest single contributing factor to production failures. Engineers make quick fixes, don't document them, they get overwritten or interact unexpectedly. GitOps eliminates this by making all changes tracked, reviewed, and enforced by automated controllers." },
            { question_text: "What is ArgoCD ApplicationSet and why is it valuable for multi-cluster AI platforms?", scenario_context: "Managing 10 model serving services across dev/staging/prod clusters — 30 ArgoCD Applications to maintain manually.", options: ["A set of best practice ArgoCD configurations", "Dynamically creates ArgoCD Applications across multiple clusters from one template — instead of 30 manually created Applications, one ApplicationSet with cluster generator creates all 30 automatically with per-cluster values (dev: 1 replica small instances; prod: 3 replicas GPU instances).", "A backup system for ArgoCD", "A visualization tool for ArgoCD"], correct_answer_index: 1, explanation: "ApplicationSet eliminates N×M manual Application management. With 10 services × 3 clusters = 30 Applications to keep in sync, manual management guarantees drift. ApplicationSet generates all 30 from a template with cluster-specific overrides — one change propagates correctly to all environments automatically." },
            { question_text: "What is the governance workflow that ensures no production infrastructure changes without review in a Terraform + ArgoCD environment?", scenario_context: "Preventing an engineer from running terraform apply locally against production.", options: ["Trust engineers not to make unauthorized changes", "All changes via PR: engineer creates PR (Terraform or K8s manifest change), automated validation runs (terraform plan, Checkov scan), second engineer reviews, PR merges, controller applies. Neither Terraform nor ArgoCD runs outside this workflow — no local applies, no direct kubectl. The PR is the audit trail.", "Only senior engineers can deploy", "Require two-person authorization for all changes"], correct_answer_index: 1, explanation: "The PR-based workflow enforces: automated validation (catches security issues, configuration errors), peer review (catches logic errors, compliance violations), and audit trail (every production change has a PR with who approved it and when). Local terraform apply bypasses all three — GitOps makes this architecturally impossible." }
          ]
        },
        {
          title: "1.4 Observability and SRE Practices for AI Systems",
          description: "Google's SRE Book, the three observability pillars, the Four Golden Signals, SLOs and error budgets, and the AI-specific monitoring that catches model degradation before users notice.",
          order_index: 3,
          lessonScript: {
            mainPoints: [
              "Observability — the ability to understand the internal state of a system from its external outputs — is the concept that distinguishes modern production engineering from traditional monitoring. The distinction made famous by Charity Majors at Honeycomb: monitoring tells you when something is wrong; observability tells you why. Traditional monitoring: 'CPU is at 95%.' Observability: 'CPU is at 95% on node group ai-inference-2, caused by a 3x increase in request rate to /v2/predict endpoint, originating from a client that started sending batch requests at 14:32 UTC, with p99 latency increasing from 45ms to 340ms affecting 2.3% of users.' The three pillars of observability — metrics, logs, and distributed traces — together provide this diagnostic depth. For AI systems, a fourth pillar is required: model behavior metrics that track prediction quality over time.",

              "Prometheus, the CNCF-graduated time-series database, is the industry standard for Kubernetes-native metrics collection. The four metric types: Counters (monotonically increasing — total requests, total errors; use rate() to get per-second rates), Gauges (values up and down — memory usage, active connections, prediction confidence scores), Histograms (distributions — inference latency percentiles; enable calculating p50/p95/p99 with histogram_quantile()), and Summaries (pre-calculated quantiles, less flexible). For AI systems, critical custom metrics to expose via /metrics endpoint: inference_latency_seconds (Histogram — directly enables p95/p99 SLA monitoring), predictions_total (Counter labeled by model_version and prediction_label — enables output distribution monitoring), model_load_time_seconds (Gauge), feature_retrieval_latency_seconds (Histogram), and gpu_utilization_percent (Gauge). These metrics detect model degradation, capacity issues, and pipeline failures before they become customer-impacting incidents.",

              "The Four Golden Signals from Google's SRE Book (Chapter 6) are the minimum viable monitoring set for any production service. Latency: time to service a request — critically distinguish successful vs. failed request latency (a slow database query hidden in success latency metrics). Traffic: volume of demand — requests per second, events per second, active connections. Errors: rate of failed requests — both explicit (HTTP 500s) and implicit (HTTP 200 with model confidence below threshold, prediction distribution anomalies). Saturation: how 'full' the service is — for AI inference: GPU utilization, memory, request queue depth. For each signal: a Grafana dashboard panel showing current value and trend, a Prometheus alert firing when threshold is exceeded for 5+ continuous minutes (multi-window prevents flapping), and a linked runbook providing diagnosis and remediation steps. The SRE Book's guidance: if you only implement four metrics, implement these four.",

              "Service Level Objectives (SLOs) and Error Budgets, codified in Google's SRE Book, make reliability a quantified engineering concern. An SLO is a target: '99.9% of inference requests complete successfully within 100ms, measured over a 28-day rolling window.' The error budget is allowable unreliability: 1 - 99.9% = 0.1% = 43.8 minutes/month. When budget is full: deploy frequently, experiment, ship features. When budget depletes: freeze non-essential deployments, prioritize reliability work. This framework creates a rational mechanism for balancing velocity and reliability — replacing the dysfunctional dynamic where product pushes for speed and ops pushes for stability with a shared, data-driven framework where both teams own the SLO. Netflix, Airbnb, Stripe, and Google all attribute significant reliability improvements to SLO-based error budget management.",

              "Distributed tracing follows a request through every service it touches, recording time and metadata at each hop. OpenTelemetry (OTel), the CNCF standard merging OpenTracing and OpenCensus, is the vendor-neutral instrumentation standard. When a request enters your AI API gateway, a Trace ID is generated. Every downstream call (feature store lookup, model inference, post-processing) creates a child Span with timing and metadata. Traces are collected by an OTel Collector and stored in Jaeger, Zipkin, Honeycomb, or Datadog. When a p99 latency alert fires, engineers open the trace and see exactly: API gateway (5ms) → feature retrieval (285ms — this is the bottleneck) → model inference (22ms) → post-processing (8ms). For AI systems: instrument feature retrieval, model inference, and postprocessing as separate spans — turning 'something is slow' into 'the feature store is slow' in under 2 minutes.",

              "AI-specific observability goes beyond the Four Golden Signals to include model behavior monitoring — tracking whether predictions remain statistically consistent with training behavior. The key model behavior metrics: prediction score distribution (track p50/p95 of model confidence scores — a drop from 0.89 to 0.72 p50 confidence signals the model is less certain, indicating possible input distribution shift), prediction label distribution (track positive prediction rate — shifting from 8% to 15% positive without a known business reason requires immediate investigation), and feature distribution statistics (track mean, stddev, null rate for key input features — features drifting from training distribution are the leading cause of prediction quality degradation, involved in 73% of unexplained model failures per Airbnb's research). Tools: Evidently AI (open-source drift reports), Arize (commercial ML observability with SHAP root cause analysis), WhyLabs (statistical monitoring with automatic anomaly detection). Alert when distributions shift beyond 2 standard deviations from training baseline.",

              "Runbooks are the operational documentation that determine whether on-call engineers resolve incidents in 10 minutes or 3 hours. For every alert you configure, write the runbook before creating the alert — the alert is only as good as the response it enables. Production runbook structure: what is this alert measuring, what threshold triggers it, what are the likely causes in order of probability, what are the diagnostic steps for each cause, what are the remediation steps, and who to escalate to if unresolved in 30 minutes. For AI-specific alerts: 'Model prediction confidence p50 dropped > 20% from baseline' — likely causes: (1) feature pipeline staleness (check feature store dashboard), (2) upstream data distribution change (compare input feature statistics in Grafana), (3) model was silently replaced (verify deployed model version in registry). Store runbooks in the same Git repository as the service code — test and update them quarterly, every time there's an incident involving that alert."
            ]
          },
          questions: [
            { question_text: "What distinguishes observability from monitoring for AI system diagnosis?", scenario_context: "Explaining to your team why investing in distributed tracing is worth the engineering effort.", options: ["Observability is just newer terminology for monitoring", "Monitoring tells you when something is wrong (CPU at 95%). Observability tells you why — distributed traces show exactly which service at which step caused p99 latency to spike, reducing diagnosis from hours of guesswork to 2-minute trace inspection.", "Monitoring is for infrastructure; observability is for applications", "They require different tools but provide the same insight"], correct_answer_index: 1, explanation: "Monitoring without observability means knowing a problem exists but guessing the cause. Observability (correlated metrics + logs + traces) means diagnosing directly: the trace shows feature retrieval at 285ms is the bottleneck, not model inference at 22ms. This difference is hours of investigation vs. 2 minutes of trace inspection." },
            { question_text: "What Prometheus metric type correctly captures AI inference latency percentiles?", scenario_context: "Setting up p95 and p99 inference latency monitoring for SLA compliance.", options: ["Counter — counts inferences", "Histogram — records value distribution across buckets, enabling PromQL histogram_quantile(0.99, rate(inference_latency_seconds_bucket[5m])) for exact p99 calculation. The only metric type that enables percentile SLA monitoring.", "Gauge — tracks current latency", "Summary — pre-calculated at client"], correct_answer_index: 1, explanation: "Histograms bucket observations and enable server-side percentile calculation via histogram_quantile(). Counters only count; Gauges only snapshot; Summaries pre-calculate percentiles on the client (losing flexibility to calculate arbitrary quantiles in Grafana). Histograms are the correct choice for any SLA-monitored latency metric." },
            { question_text: "How does the SRE Error Budget create a rational speed-vs-reliability mechanism?", scenario_context: "Product wants 5 deployments/week; ops wants a 2-week freeze after every incident.", options: ["Error budgets are only for Google-scale systems", "Error budget = 1 - SLO (43.8 min/month for 99.9%). Budget full: deploy freely. Budget depleted: freeze non-essentials. Both teams agreed to the SLO, both own the budget. Deployment decisions are objective (how much budget remains?) not political (who argues louder?).", "Error budgets require expensive tooling", "Error budgets only apply to uptime metrics"], correct_answer_index: 1, explanation: "Error budgets transform the speed-reliability negotiation from opinion-based to data-based. When the budget is healthy, product's deployment requests are valid. When depleted by incidents, engineering's reliability focus is valid. The SLO is the pre-agreed contract — budget consumption is the objective arbiter." },
            { question_text: "What does Airbnb's research reveal about the leading cause of unexplained model performance degradation?", scenario_context: "Investigating why a production model's accuracy dropped 15% without any code changes.", options: ["Model architecture was insufficient", "Feature distribution drift was involved in 73% of unexplained model degradation incidents — input features changing from training distribution without the model retraining. Feature monitoring (statistical drift, freshness, null rates) catches this before it manifests as user-visible quality loss.", "Random statistical variance in model outputs", "Production traffic distribution changed"], correct_answer_index: 1, explanation: "73% of unexplained model failures traced to feature drift. The world changed (user behavior, upstream systems), features changed, but the model was trained on the old distribution. Feature monitoring with drift alerts catches this when it starts, not weeks later when users complain about recommendation quality." },
            { question_text: "What is the production runbook structure that reduces 3-hour incidents to 10-minute resolutions?", scenario_context: "Writing a runbook for your 'model prediction confidence dropped 20%' alert.", options: ["A brief description of the alert", "Alert measurement + trigger threshold + likely causes in probability order + diagnostic steps per cause + remediation steps + escalation path. Written before the alert, tested quarterly, updated after every incident that touches it. The alert is only as good as the runbook it triggers.", "A list of people to call during incidents", "A post-mortem template"], correct_answer_index: 1, explanation: "Runbooks written in calm conditions capture diagnostic expertise that's unavailable at 3am under pressure. Structured causality (most likely cause first), specific diagnostic steps (not 'investigate'), and remediation steps (not 'fix the problem') turn a 3-hour investigation into a 10-minute diagnosis-and-fix process." }
          ]
        },
        {
          title: "1.5 Platform Engineering for AI: Internal Developer Platforms and the Paved Road",
          description: "How Spotify's Backstage, Netflix's Paved Path, and the CNCF Platform Engineering movement transform AI team productivity — building self-service infrastructure that lets data scientists focus on ML, not DevOps.",
          order_index: 4,
          lessonScript: {
            mainPoints: [
              "Platform Engineering — building Internal Developer Platforms (IDPs) that abstract infrastructure complexity into self-service interfaces — emerged as a formal discipline with the CNCF Platform Engineering working group in 2022. The fundamental economic insight: every hour a data scientist spends waiting for infrastructure (ticket to provision a training cluster, deployment pipeline for their model, access to the data catalog) is an hour not spent on ML work. At scale, this compounds dramatically: a 200-person ML organization where each person loses 30% of time to infrastructure friction is equivalent to losing 60 full-time ML engineers in productivity. At $250K all-in per engineer, that's $15M/year in lost productivity that a platform team of 10 engineers ($2.5M/year) can recover — a 6x ROI even if the platform only recovers half the friction.",

              "Spotify's Backstage — open-sourced in 2020 and donated to the CNCF — is the leading Internal Developer Portal framework. Backstage provides: a Software Catalog (searchable registry of all services, ML models, datasets, and infrastructure with ownership and documentation), Software Templates (one-click project scaffolding generating production-ready repository structure — model serving template includes Dockerfile, Kubernetes manifests, GitHub Actions CI/CD, Grafana dashboard, runbook), TechDocs (documentation-as-code integrated into the service catalog), and a Plugin system (1,200+ community plugins for Kubernetes, Grafana, MLflow, SageMaker, and every tool in the ecosystem). Zalando, American Airlines, and Wayfair have built AI platforms on Backstage — with documented 3-5x improvements in engineer onboarding time and 40-60% reductions in infrastructure-related support tickets.",

              "The 'paved road' concept — popularized by Netflix and formalized in the Platform Engineering community — is the design philosophy that makes IDPs successful. A paved road is an opinionated, well-supported path for a common task incorporating security, observability, compliance, and operational best practices by default. Engineers can go 'off-road' for special requirements, but the paved road handles 80% of use cases without requiring deep infrastructure expertise. Netflix's Paved Path: a model serving template (deploy a model by providing the model artifact and a YAML config — security, monitoring, autoscaling configured automatically), a training pipeline template (distributed training on GPU clusters without writing Kubernetes YAML), and a feature engineering template (create dbt models and register features in the feature store with a single PR). The success metric: new engineers shipping their first model to production in one day vs. three weeks.",

              "Self-service GPU provisioning is the highest-impact platform capability for AI team productivity. The architecture: a Backstage software template generates a RayCluster or Jupyter Notebook Server Kubernetes resource, applied to a dedicated GPU namespace via ArgoCD auto-sync. Resource quotas per team namespace prevent any team from monopolizing GPU capacity. Cost attribution labels (team: ml-fraud, project: fraud-detector-v2, env: dev) enable per-team cost reporting. Automatic idle detection (no activity for 4 hours → cluster terminates) prevents wasted GPU spend. Karpenter provisions actual EC2 GPU instances on-demand (~30 seconds to node ready) and terminates them when the cluster is deleted. The operational result: a data scientist provisions a 16-GPU training cluster by filling a form (not learning Kubernetes and Terraform), runs training, and the cluster auto-terminates when complete — zero infrastructure tickets.",

              "Developer Experience (DevEx) metrics provide quantitative evidence for platform investment — transforming platform engineering from a cost center to a measurable productivity multiplier. Key DevEx metrics: DORA metrics for the engineering organization overall (delivery performance impact of the platform), Self-Service Rate (percentage of infrastructure requests resolved through self-service without a support ticket — target >90%), Cognitive Load survey ('How much infrastructure knowledge do you need to do your job?'), and Flow State Frequency ('How often do you achieve deep focus in your work?'). The '2023 DevEx Report' (Abi Noda et al., IEEE Software) found that perceived DevEx explains 25% of variance in developer productivity — stronger predictor than team size, experience, or tech stack. For AI platform teams: track Self-Service Rate quarterly. Below 70% means engineers still file tickets for common tasks — the paved road needs improvement.",

              "Stripe's Friction Log user research methodology revealed the highest-value platform investments with precision. Engineers recorded every frustrating interaction during a one-day coding session — not complaints they could remember from weeks ago, but real-time friction as it occurred. The analysis: provisioning staging environments and deploying test models accounted for 40% of reported friction. Without this research, the platform team would have invested in documentation or tooling improvements based on assumptions. With it, they built self-service environment provisioning and one-click test model deployment — directly addressing the 40% friction. For AI platform teams: run Friction Log sessions quarterly with 5-10 data scientists and ML engineers. The sessions take 2 hours each and consistently reveal priorities that surveys miss — because surveys ask what engineers think bothers them, while Friction Logs capture what actually slows them down in real work.",

              "Security-by-default in platform templates is the property that makes platform engineering a security force multiplier. Every paved road template should incorporate: mandatory non-root container execution (prevent container escape escalation), read-only root filesystem (prevent malware write operations), dropped Linux capabilities (remove unnecessary system call permissions), resource limits (prevent noisy-neighbor and DoS-by-runaway-training-job), NetworkPolicies (default-deny with minimal explicit allows), Pod Security Admission (enforce baseline or restricted security standards at namespace level), and automated image scanning (Trivy or Grype in CI pipeline — Snyk found 78% of critical container vulnerabilities come from base image packages). When security is the path of least resistance — built into the template — engineers inherit it automatically without thinking about it. Security-by-default beats security-by-requirement because requirements are skipped under deadline pressure; templates are not."
            ]
          },
          questions: [
            { question_text: "What is the quantifiable productivity cost that Platform Engineering addresses?", scenario_context: "Making the ROI case for an Internal Developer Platform to a CFO.", options: ["Platform engineering has no measurable ROI", "A 200-person ML org losing 30% time to infrastructure friction = 60 FTE equivalents lost. At $250K/engineer = $15M/year lost productivity. A platform team of 10 ($2.5M/year) recovering even half that friction delivers 3x ROI — documented as 3-5x onboarding improvement and 40-60% support ticket reduction at Zalando, American Airlines, and Wayfair.", "ROI is only measurable after 3+ years", "ROI depends entirely on cloud provider"], correct_answer_index: 1, explanation: "The ROI of Platform Engineering is quantifiable: FTE equivalents lost to infrastructure friction × engineering cost. The Backstage-based platform teams at Zalando and Wayfair document concrete metrics — onboarding time improvements, support ticket reductions — that translate directly to engineering capacity recovered." },
            { question_text: "What does Spotify's Backstage Software Templates provide that eliminates 3-week onboarding?", scenario_context: "A new ML engineer needs to deploy their first model. Without templates, this takes 3 weeks of infrastructure learning.", options: ["A model training framework", "One-click project scaffolding generating a complete, production-ready repository: Dockerfile with security best practices, Kubernetes manifests with resource limits and health checks, GitHub Actions CI/CD pipeline, Grafana dashboard, and runbook. New engineer ships to production in one day — inheriting all platform expertise.", "Visual model debugging tools", "Automated ML hyperparameter tuning"], correct_answer_index: 1, explanation: "Templates encode 3 weeks of infrastructure learning into a one-click operation. The engineer fills a form (model name, owner team, resource requirements) and gets a complete, production-ready repository with all security, observability, and operational requirements pre-configured — not learned from scratch." },
            { question_text: "What did Stripe's Friction Log research reveal about developer time allocation?", scenario_context: "Prioritizing your platform roadmap for maximum ML engineer productivity impact.", options: ["Code review was the largest friction source", "Provisioning staging environments and deploying test models accounted for 40% of recorded developer friction in one-day coding sessions — revealing the highest-value platform investments. Surveys predicted different priorities; real-time Friction Log captured actual friction during real work.", "Documentation was the primary bottleneck", "Meeting overhead was the biggest productivity drain"], correct_answer_index: 1, explanation: "Friction Logs (real-time recording during actual work) vs. surveys (remembered complaints) reveal different priorities. Stripe discovered 40% of friction came from just two tasks. Without this research, the platform team would have invested in the wrong things. Quarterly Friction Log sessions with 5-10 engineers keep the roadmap aligned with real pain points." },
            { question_text: "What is the 'Self-Service Rate' metric and what does a below-70% rate indicate?", scenario_context: "Evaluating whether your AI platform is actually reducing infrastructure burden.", options: ["Percentage of services running without operators", "Percentage of infrastructure requests resolved through self-service without a support ticket. Below 70% means engineers still file tickets for common tasks — the paved road covers only half the use cases. Target: >90%, meaning the platform handles the vast majority of common infrastructure needs without human intervention.", "Rate of successful automated deployments", "Percentage of ML models deployed without review"], correct_answer_index: 1, explanation: "Self-Service Rate directly measures whether the platform solves the problems it was built to solve. A 50% rate means half of all infrastructure requests still require ticket-filing and human intervention. Quarterly tracking toward a >90% target keeps the platform team focused on the highest-friction remaining use cases rather than building features nobody needs." },
            { question_text: "Why does security-by-default in platform templates outperform security guidelines and checklists?", scenario_context: "Engineers consistently skip security configurations when setting up model serving deployments manually.", options: ["Templates are technically enforced by policy", "When security is the path of least resistance — pre-configured in the template — engineers inherit it without deliberate effort. Security checklists require remembering and applying each requirement under deadline pressure; they get skipped. Templates make the secure configuration the only available starting point.", "Security automation is expensive to build", "Guidelines are equally effective with proper training"], correct_answer_index: 1, explanation: "Security guidelines require deliberate effort at a moment when engineers are focused on shipping features. Templates make security automatic — the non-root user, resource limits, and image scanning are already configured before the engineer writes a single line of code. Snyk's 78% critical vulnerability figure from base images drops dramatically when templates enforce automated scanning." }
          ]
        }
      ],
      endQuizQuestions: [
        { question_text: "What are the DORA four keys and which has the most dramatic gap between elite and low performers?", scenario_context: "Benchmarking your team and presenting to leadership.", options: ["Velocity, quality, security, reliability", "Deployment Frequency, Lead Time for Changes, MTTR, Change Failure Rate. Lead Time has the most dramatic gap: elite teams under 1 hour, low performers 1-6 months — a 1000x+ difference that compounds across all other metrics.", "Sprint velocity, bug count, on-call hours, customer NPS", "Build time, test coverage, deployment size, incident count"], correct_answer_index: 1, explanation: "The four keys measure distinct delivery dimensions. Lead Time's 1000x+ gap (minutes vs. months) is the most dramatic because it's the root cause of other gaps — fast lead time enables fast error correction (MTTR), small batch sizes (low failure rate), and high frequency. Improving lead time improves all four keys." },
        { question_text: "What is 'shift-left security' and what tools implement it in AI CI/CD pipelines?", scenario_context: "Building security into your AI CI/CD pipeline rather than discovering vulnerabilities post-deployment.", options: ["Moving security team to earlier in the org chart", "Moving security validation earlier in development — pre-commit hooks (secret scanning with git-secrets/gitleaks), PR-time SAST (Bandit for Python, Semgrep), and CI/CD gates (Trivy for container images, Checkov for Terraform/Kubernetes manifests). IBM research: vulnerabilities cost 100x more to fix in production vs. development.", "Encrypting data before it's processed", "A political stance on security regulation"], correct_answer_index: 1, explanation: "Shift-left catches issues when they're cheapest to fix. A CVE caught in the CI container scan costs 30 minutes to fix. The same CVE caught in a production security audit costs days of remediation, potential compliance penalties, and emergency patching of live systems. For AI: checking model artifact provenance in CI prevents backdoored models reaching production." },
        { question_text: "What is the 'toil' concept from Google's SRE Book and why does reducing it improve reliability?", scenario_context: "Your team spends 40% of time on manual operational tasks: restarting failed pods, responding to disk space alerts, rotating API keys manually.", options: ["Toil refers to difficult technical challenges", "Toil is manual, repetitive, automatable work that scales with service growth but provides no lasting value. The SRE book recommends keeping toil below 50% of team time. Reducing toil (automating restarts, disk cleanup, key rotation) frees capacity for reliability improvements that prevent future incidents.", "Toil is a type of technical debt", "Toil only applies to on-call rotations"], correct_answer_index: 1, explanation: "Toil scales with service growth — each new model deployment adds monitoring to check, configurations to rotate, incidents to triage. Without automation, toil consumes increasing engineering capacity, leaving less for reliability improvements. Each automation compounds: eliminating manual key rotation across 50 services saves 50x the effort of automating once." },
        { question_text: "What is 'chaos engineering' and how does it apply specifically to AI inference systems?", scenario_context: "Preparing your AI platform for production failures before they happen unexpectedly.", options: ["Deliberately introducing code bugs for testing", "Proactively injecting failures (pod crashes, GPU failures, feature store timeouts, network partitions) in controlled conditions to verify AI systems fail gracefully and recovery mechanisms work — before discovering they don't at 3am during a real incident.", "A testing methodology for machine learning accuracy", "A security testing approach for AI systems"], correct_answer_index: 1, explanation: "Netflix's Chaos Monkey proactively tests failure modes before unplanned incidents. For AI: injecting a feature store latency spike verifies your circuit breaker triggers and fallback activates; killing a model server pod verifies Kubernetes replaces it within SLO; disabling a GPU node verifies workloads reschedule correctly. Discovering these work via chaos experiment > discovering they don't during a production incident." },
        { question_text: "What is 'blue-green deployment' and what is its primary advantage and disadvantage vs. canary?", scenario_context: "Choosing a deployment strategy for a model update that requires zero-downtime deployment with fast rollback.", options: ["Two separate development branches", "Two identical production environments — switch traffic at load balancer level. Advantage: instant rollback (point back to blue) and zero risk that the new model serves any user until you're confident. Disadvantage: 2x infrastructure cost while both environments run simultaneously.", "A color-coding system for deployment environments", "A deployment strategy only for web applications"], correct_answer_index: 1, explanation: "Blue-green's instant rollback (load balancer weight change completes in seconds) is its key advantage for models where even a 5% canary with degraded predictions is unacceptable. The 2x infrastructure cost is its limitation — acceptable for high-stakes models during the validation window, unsustainable as a permanent architecture." },
        { question_text: "What is the OpenTelemetry Collector and why is it important for AI platform observability?", scenario_context: "Designing observability infrastructure for an AI platform with multiple model serving services.", options: ["A metrics database for Prometheus", "A vendor-neutral telemetry pipeline that receives traces, metrics, and logs from all services, processes them (batching, filtering, transforming), and exports to multiple backends (Jaeger, Prometheus, Datadog, Grafana) simultaneously — enabling observability backend changes without re-instrumenting services.", "A log aggregation tool", "A Kubernetes monitoring agent"], correct_answer_index: 1, explanation: "The OTel Collector decouples instrumentation from backend: services instrument once with OTel SDK, the Collector routes to any backend. When you switch from Jaeger to Honeycomb, you update the Collector config — not all 30 model serving services. Critical for AI platforms where the observability stack evolves independently of the ML services it monitors." },
        { question_text: "What is 'feature flag consistency' and why does it matter for A/B testing AI models?", scenario_context: "Your A/B test comparing two recommendation models shows inconsistent results that violate statistical assumptions.", options: ["All users see the same feature flag state", "The same user always gets assigned to the same model version (based on user ID hashing, not random assignment per request). Without consistency, a user experiences different models between requests — violating the independence assumption of A/B tests and producing invalid statistical comparisons.", "Feature flags are consistent across regions", "Consistency means flags are deployed to all servers simultaneously"], correct_answer_index: 1, explanation: "A/B test validity requires stable assignment. If user A sees Model 1 on request 1, Model 2 on request 2, and Model 1 on request 3, you can't attribute their behavior to either model. User ID-based hashing provides deterministic assignment: user A always sees Model 1, user B always sees Model 2 — producing valid statistical comparisons." },
        { question_text: "What is 'Infrastructure as Code' and what specific problem does it solve for AI platform operations?", scenario_context: "Explaining to a new team member why all infrastructure is managed through Terraform rather than the AWS console.", options: ["Writing code that runs on infrastructure", "Defining all cloud resources (VPCs, EKS clusters, IAM roles, S3 buckets) in version-controlled code files. Solves: reproducibility (recreate exact infrastructure in a new region), auditability (every change tracked in Git with who made it and why), consistency (dev/staging/prod use identical configurations differing only in scale).", "Using code to test infrastructure performance", "Automating infrastructure billing"], correct_answer_index: 1, explanation: "IaC solves three critical problems simultaneously: reproducibility (disaster recovery requires recreating infrastructure exactly), auditability (compliance requires knowing who changed what and when), and consistency (dev/staging/prod differences that cause 'works in staging but not prod' are eliminated). For AI platforms: model training environment must exactly match serving environment — IaC enforces this." },
        { question_text: "What is the SRE 'toil budget' recommendation and how should AI platform teams apply it?", scenario_context: "Deciding how much engineering time to allocate to automation vs. product feature work.", options: ["Toil should be minimized completely", "The SRE Book recommends keeping toil below 50% of team time, with a goal of continuous reduction. For AI platform teams: if >50% of time is spent on manual model deployments, incident triage, and ticket resolution, investment in automation (deployment automation, auto-scaling, self-service) takes priority over new features.", "Toil budget only applies to on-call rotations", "60-70% toil is acceptable for small teams"], correct_answer_index: 1, explanation: "50% toil threshold is the signal for automation investment. Below 50%, teams can balance automation and feature work. Above 50%, toil is consuming capacity faster than reliability improvements can be made — a downward spiral. For AI platforms: tracking toil percentage monthly identifies when manual work is crowding out the platform improvements that would eliminate that manual work." },
        { question_text: "What is 'Prometheus alerting fatigue' and how do multi-window alerts prevent it?", scenario_context: "Your on-call team is ignoring alerts because 60% are false positives from transient spikes.", options: ["Too many Prometheus instances running", "Alert fatigue from false positives on transient metric spikes. Multi-window alerts require the condition to persist for N consecutive minutes before firing (e.g., error rate > 1% for 5 continuous minutes) — filtering out sub-minute transient spikes while still catching real problems quickly. Result: higher signal-to-noise ratio, alerts that actually require action.", "Prometheus running out of storage", "Too many metrics being collected"], correct_answer_index: 1, explanation: "A single spike above threshold in 1 second triggers a naive alert — causing 60% false positives from transient load spikes that self-resolve. Multi-window alerts (for: 5m means continuously for 5 minutes) filter transients while still catching persistent problems within minutes. Reducing false positives from 60% to under 10% is the difference between an on-call team that responds to every alert and one that ignores them." }
      ]
    }
  ]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const { data: ex } = await supabase.from("courses").select("id").eq("title", courseData.title).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({
      title: courseData.title, description: courseData.description, is_published: true,
      translations: {
        es: { title: "Ingeniero DevOps IA", description: "Domina los pipelines CI/CD y workflows GitOps para sistemas IA." },
        fr: { title: "Ingénieur DevOps IA", description: "Maîtrisez les pipelines CI/CD et GitOps pour les systèmes IA." },
        de: { title: "KI-DevOps-Ingenieur", description: "Meistern Sie CI/CD-Pipelines und GitOps für KI-Systeme." },
        zh: { title: "AI DevOps工程师", description: "掌握AI系统的CI/CD流水线和GitOps工作流。" },
        ar: { title: "مهندس DevOps للذكاء الاصطناعي", description: "أتقن خطوط CI/CD وسير عمل GitOps لأنظمة الذكاء الاصطناعي." },
        ja: { title: "AI DevOpsエンジニア", description: "AIシステムのCI/CDパイプラインとGitOpsワークフローをマスターする。" },
      }
    }).select().single();
    if (ce) throw ce;
    for (const ch of courseData.chapters) {
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: ch.title, description: ch.description, order_index: ch.order_index, translations: {} }).select().single();
      if (che) throw che;
      for (const vid of ch.videos) {
        const transcript = vid.lessonScript.mainPoints.join("\n\n");
        const trans = { en:{title:vid.title,transcript}, es:{title:vid.title,transcript}, fr:{title:vid.title,transcript}, de:{title:vid.title,transcript}, zh:{title:vid.title,transcript}, ar:{title:vid.title,transcript}, ja:{title:vid.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: vid.title, description: vid.description, order_index: vid.order_index, translations: trans }).select().single();
        if (ve) throw ve;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        for (let i = 0; i < vid.questions.length; i++) {
          const q = vid.questions[i];
          await supabase.from("quiz_questions").insert({ quiz_id: quiz.id, question_text: q.question_text, scenario_context: q.scenario_context, options: q.options, correct_answer_index: q.correct_answer_index, explanation: q.explanation, order_index: i });
        }
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      for (let i = 0; i < ch.endQuizQuestions.length; i++) {
        const q = ch.endQuizQuestions[i];
        await supabase.from("quiz_questions").insert({ quiz_id: eq.id, question_text: q.question_text, scenario_context: q.scenario_context, options: q.options, correct_answer_index: q.correct_answer_index, explanation: q.explanation, order_index: i });
      }
    }
    return new Response(JSON.stringify({ message: "AI DevOps Engineer — rich version seeded", courseId: course.id }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
