import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const COURSE_TITLE = "AI Agent Engineer";

const modules = [
  {
    title: "Module 1: LLM Foundations — Transformers, Prompt Engineering, and Production Patterns",
    desc: "Deep technical foundation of large language models — the transformer architecture, attention mechanisms, emergent capabilities, and the production prompt engineering discipline that separates reliable agents from impressive demos. Covers everything in IBM's Course 1 and goes deeper with real production incident case studies.",
    lessons: [
      { title: "1.1 Transformer Architecture: Attention, Tokenization, and Why Scale Changes Everything", desc: "Self-attention mechanism (Vaswani et al. 2017 'Attention Is All You Need'), multi-head attention for parallel relationship modeling, positional encoding, the encoder-decoder architecture, and why the transformer replaced RNNs. Tokenization (BPE, SentencePiece) and why token count matters for cost and latency. Emergent capabilities: chain-of-thought reasoning emerges at ~100B parameters, in-context learning at ~10B. Case study: How GPT-3's emergent few-shot learning capabilities (Brown et al. 2020) surprised even its creators." },
      { title: "1.2 Prompt Engineering: RISEN Framework, Chain-of-Thought, and Reliability at Scale", desc: "RISEN framework (Role, Instructions, Situation, Examples, Negative examples) for production system prompts. Chain-of-thought prompting (Wei et al. 2022) — why reasoning before answering improves accuracy 40-60% on complex tasks. Tree of Thought (Yao et al. 2023) for complex multi-step problems. Least-to-most prompting for decomposition. The Air Canada chatbot lawsuit (2024) as a case study in what happens when behavioral constraints aren't explicit and testable." },
      { title: "1.3 LLM API Mastery: OpenAI, Anthropic, and Google — Parameters, Costs, and Selection", desc: "API parameters: temperature (0 for deterministic classification, 0.7-1.0 for creative generation), top-p, max_tokens, stop sequences, logit_bias. Model selection economics: GPT-4o ($5/M tokens) vs. GPT-4o-mini ($0.15/M) — the 33x cost difference and when each is appropriate. The cascade architecture (Notion, Linear, Salesforce): cheap/fast models for routing and simple tasks, expensive models only for complex reasoning. Benchmarking: MMLU, HumanEval, MT-Bench, and why leaderboard rankings don't predict production performance." },
      { title: "1.4 LangChain Fundamentals: Chains, Prompts, and the LCEL Architecture", desc: "LangChain's history (Harrison Chase, 2022) and evolution from chains to LCEL (LangChain Expression Language). LCEL's pipe operator (prompt | model | parser) for composable pipelines. PromptTemplate and ChatPromptTemplate for reusable prompts. Output parsers (StrOutputParser, JsonOutputParser, PydanticOutputParser) for structured responses. RunnablePassthrough for data threading. Case study: How Replit uses LangChain LCEL to build their AI coding assistant with structured output parsing." },
      { title: "1.5 Building a Production GenAI Web Application with Flask and FastAPI", desc: "Flask vs. FastAPI for AI API serving (FastAPI's async advantage for concurrent LLM calls), streaming responses with Server-Sent Events (critical for LLM UX — first token in <1 second vs. waiting 10 seconds), structured JSON output parsing with Pydantic models, error handling for API rate limits and timeouts, and the deployment architecture used by AI-first products. Case study: Building an AI-powered code reviewer API from scratch." },
      { title: "1.6 Model Evaluation: Benchmarks, LLM-as-Judge, and A/B Testing in Production", desc: "Why traditional metrics (BLEU, ROUGE) fail for LLM evaluation. LLM-as-judge (GPT-4 evaluating GPT-4-mini responses) — the technique used by Anthropic, OpenAI, and Google for model comparison. RAGAS for RAG evaluation. Braintrust and Langfuse for production LLM evaluation pipelines. Statistical significance in A/B tests for language models. Case study: How Stripe evaluates their AI support assistant across 50,000 customer interactions." },
      { title: "1.7 Module 1 Assessment: Production LLM Application Design", desc: "Design challenge: given requirements for an AI customer support system, select the appropriate models, design the system prompt using RISEN, implement structured output parsing, configure streaming, and define the evaluation methodology." },
    ]
  },
  {
    title: "Module 2: Retrieval-Augmented Generation — From Architecture to Production",
    desc: "The complete RAG engineering stack — from the Lewis et al. 2020 paper through production chunking, embedding model selection, hybrid search, reranking, and the monitoring practices that keep RAG systems accurate. Covers IBM Courses 2-4 and adds advanced retrieval patterns not covered in any certification program.",
    lessons: [
      { title: "2.1 RAG Architecture: Why Grounded Generation Beats Pure LLM for Enterprise", desc: "Lewis et al. 2020 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks' — the foundational paper. The three problems RAG solves: knowledge cutoff (model doesn't know about recent events), hallucination on factual queries (model invents plausible-sounding wrong answers), and inability to cite sources (critical for enterprise trust). The canonical RAG pipeline: document ingestion → chunking → embedding → vector store indexing → query → retrieval → generation. Case study: How Notion AI grounds responses in user documents, Glean grounds enterprise search in company knowledge." },
      { title: "2.2 Chunking Strategy: The Highest-Impact RAG Engineering Decision", desc: "Fixed-size chunking (naive, breaks semantic units), semantic chunking (paragraph/section boundaries), hierarchical chunking (parent-child with metadata), sliding window with overlap (prevents boundary information loss), and document-type-specific strategies (preserve code blocks, tables, and lists as atomic units). Langchain's 2023 ablation study: chunking strategy has higher impact on RAG quality than embedding model choice. Case study: How a legal document RAG system handles 500-page contracts with nested section structure." },
      { title: "2.3 Embedding Models: OpenAI vs. Cohere vs. BGE vs. Voyage — Benchmarks and Selection", desc: "Bi-encoder architecture for fast approximate matching vs. cross-encoder for accurate reranking. MTEB (Massive Text Embedding Benchmark) leaderboard and why general benchmarks don't predict domain-specific performance. OpenAI text-embedding-3-large (3072 dims), Cohere embed-v3 (multilingual excellence), BGE-M3 (open-source, 100+ languages), Voyage AI (code retrieval specialist). Fine-tuning embeddings on domain data — when it's worth the investment. Case study: How a medical RAG system improved retrieval recall 23% by fine-tuning on clinical terminology pairs." },
      { title: "2.4 Vector Databases: Pinecone, Weaviate, Qdrant, and pgvector in Production", desc: "HNSW (Hierarchical Navigable Small World) algorithm — the graph-based ANN search achieving >95% recall at sub-millisecond latency. Pinecone (managed, simple, expensive at scale), Weaviate (hybrid search native, rich filtering), Qdrant (Rust implementation, best perf/dollar self-hosted), pgvector (zero new infrastructure for Postgres shops). Filtering strategies (pre-filter vs. post-filter impact on recall), namespace design for multi-tenant RAG, and index configuration for recall/speed tradeoffs. Case study: How Slack's AI search serves 30M+ users with pgvector at PostgreSQL scale." },
      { title: "2.5 Hybrid Search and Reranking: The 10-20% Quality Improvement Nobody Skips", desc: "Pure semantic search misses exact matches (product codes, names, legal citations). BM25 keyword search misses semantic equivalents. Reciprocal Rank Fusion (RRF) merges ranked results — consistent 5-15% recall improvement over either approach. Cross-encoder reranking (Cohere Rerank, BGE-Reranker, Jina Reranker): retrieve 50 candidates fast, rerank to top-5 with full query-document attention. Cohere benchmark: 10-20% NDCG@10 improvement from reranking. Case study: How Perplexity AI uses hybrid search + reranking for their real-time research system." },
      { title: "2.6 Advanced RAG Patterns: HyDE, Parent Document Retrieval, and Self-Query", desc: "HyDE (Hypothetical Document Embeddings, Gao et al. 2022): generate a hypothetical answer, embed it, retrieve documents similar to the answer — outperforms query-based retrieval for many tasks. Parent Document Retrieval: store small chunks for precise retrieval, return parent documents for generation context. Self-Query: LLM generates structured metadata filters (date_range, document_type, author) to combine semantic and structured search. Multi-query retrieval: generate 5 query variants, retrieve for each, merge. Case study: LlamaIndex's advanced retrieval patterns used by enterprise knowledge management systems." },
      { title: "2.7 Module 2 Assessment: Build a Production RAG System", desc: "Complete implementation challenge: design a RAG system for a 10,000-document enterprise knowledge base, select chunking strategy and embedding model for the domain, implement hybrid search with reranking, measure RAGAS metrics (faithfulness, answer relevance, context recall), and optimize to hit target quality thresholds." },
    ]
  },
  {
    title: "Module 3: Vector Databases Deep Dive — Architecture, Operations, and Scale",
    desc: "The complete vector database engineering curriculum — internal architecture, all major operations, similarity search mathematics, multi-tenancy, production operations, and building recommendation systems. Goes far beyond IBM Course 3 with production incident case studies and enterprise-scale patterns.",
    lessons: [
      { title: "3.1 Vector Search Mathematics: Cosine Similarity, Dot Product, and Euclidean Distance", desc: "Why vectors represent semantic meaning (Word2Vec, sentence transformers), cosine similarity for normalized vectors (directional similarity independent of magnitude), dot product for raw similarity, Euclidean distance for spatial proximity. When each metric is appropriate — cosine for text embeddings, dot product for recommendation systems with varying item popularity. Approximate nearest neighbor algorithms: FAISS (Facebook AI Similarity Search) flat, IVF, HNSW indices — accuracy vs. speed tradeoff. Manual implementation of cosine similarity search in Python to build intuition." },
      { title: "3.2 ChromaDB: Complete Operations for RAG Development", desc: "ChromaDB architecture (SQLite + HNSW for local development, distributed for production), collections as logical namespaces, document ingestion with metadata, embedding function configuration (OpenAI, Cohere, sentence-transformers), querying with metadata filters, updating and deleting documents, persistent storage, and the multi-modal document support. Building a complete knowledge base management system. Case study: How ChromaDB powers rapid RAG prototyping at AI startups before migrating to production vector databases." },
      { title: "3.3 FAISS: Facebook's High-Performance Similarity Search at Scale", desc: "FAISS architecture (developed at Facebook Research, 2017), index types (IndexFlatL2 for exact, IndexIVFFlat for approximate, IndexHNSWFlat for graph-based), GPU acceleration (FAISS-GPU for 10-100x throughput), index training for IVF (cluster centroids must be learned), the index selection decision matrix (dataset size × accuracy requirement × memory constraint). FAISS in production: how Meta serves billion-scale similarity search for content recommendations. Case study: Building a 10M-document semantic search system with FAISS on a $200/month instance." },
      { title: "3.4 Multi-Tenancy and Access Control in Vector Databases", desc: "Namespace-based multi-tenancy (Pinecone namespaces, Weaviate multi-tenancy), row-level security for enterprise RAG (each user only retrieves from their authorized documents), metadata-based access control, the performance implications of per-tenant filtering vs. separate indices, hybrid multi-tenancy (shared indices with metadata filtering for small tenants, dedicated indices for large tenants). Case study: How Salesforce implements multi-tenant RAG across 150,000+ enterprise customers in their Einstein platform." },
      { title: "3.5 Recommendation Systems with Vector Similarity: Netflix, Spotify, and Beyond", desc: "Item embeddings (product, content, user) as vectors in semantic space, collaborative filtering via user embedding similarity, content-based filtering via item embedding similarity, two-tower models for large-scale retrieval (learn user and item embeddings separately, retrieve via ANN), and the production recommendation architecture. Case study: Spotify's Annoy (Approximate Nearest Neighbors Oh Yeah) library — how they serve music recommendations for 600M users using vector similarity on song embeddings. Case study: Netflix's embedding-based recommendation at 260M subscriber scale." },
      { title: "3.6 Vector Database Operations: Monitoring, Optimization, and Production Incident Response", desc: "Index rebuild triggers (when to rebuild HNSW after bulk updates), query latency monitoring (p99 targets: <50ms for interactive applications), recall degradation detection (test query set with known relevant documents, track recall over time), storage growth management (embedding compression techniques, product quantization for 4-8x storage reduction), backup and recovery, and the operations runbook for vector database incidents. Case study: Post-mortem of a production RAG system that degraded to 40% recall after schema changes invalidated cached embeddings." },
      { title: "3.7 Module 3 Assessment: Vector Database Architecture Design", desc: "Architecture challenge: design the vector database infrastructure for a multi-tenant legal research platform serving 500 law firms, each with private document collections ranging from 1,000 to 1,000,000 documents, with strict data isolation requirements, <100ms query SLA, and $50K/month infrastructure budget." },
    ]
  },
  {
    title: "Module 4: Multimodal AI — Text, Images, Audio, Video, and Cross-Modal Applications",
    desc: "Building production multimodal AI systems — from the architecture of vision-language models through audio processing (Whisper), image generation (DALL-E, Stable Diffusion), video AI, and integrated multimodal applications. Covers IBM Course 5 and adds cutting-edge production patterns from leading AI companies.",
    lessons: [
      { title: "4.1 Vision-Language Models: GPT-4V, Claude Vision, Gemini, and LLaVA Architecture", desc: "How vision-language models connect visual encoders (ViT, CLIP) to language model decoders, the projection layer that bridges image and text token spaces, prompt design for visual analysis (structured queries outperform open-ended prompts by 30-40%), image preprocessing requirements (resolution, aspect ratio, token cost per image), and production use cases: document digitization, UI testing, visual QA, medical image analysis. Case study: How Waymo uses vision-language models for autonomous driving edge case annotation." },
      { title: "4.2 OpenAI Whisper: Speech-to-Text for Production AI Applications", desc: "Whisper architecture (encoder-decoder transformer trained on 680K hours of multilingual audio, 2022), model size selection (tiny: 39M params, base: 74M, small: 244M, large: 1.55B — accuracy vs. latency tradeoff), language detection, timestamp alignment, speaker diarization with WhisperX, GPU vs. CPU deployment, and the faster-whisper (CTranslate2) 4x speedup for production. Case study: How Otter.ai processes 10M+ hours of meeting recordings monthly with Whisper-based pipelines." },
      { title: "4.3 Image Generation: DALL-E 3, Stable Diffusion, and Midjourney APIs in Production", desc: "DALL-E 3 API for programmatic image generation (text prompt engineering for consistent outputs, content policy constraints, cost modeling at $0.04-0.12/image), Stable Diffusion via Stability AI API and self-hosted (ComfyUI, A1111), ControlNet for pose/layout-guided generation, inpainting for targeted image editing, and integration patterns for AI-assisted content creation workflows. Case study: How Canva's 'Magic Studio' generates design variations at scale using DALL-E API. Case study: How e-commerce platforms generate product imagery variations." },
      { title: "4.4 Video AI: Analysis, Generation, and Processing with OpenAI Sora and RunwayML", desc: "Video understanding with GPT-4V (frame extraction strategy, temporal reasoning), video generation with Sora (prompt engineering for cinematic quality, duration and resolution constraints), RunwayML Gen-3 for professional video production, ElevenLabs for voice synthesis in video, video transcription and chapter generation pipelines, and the emerging agentic video editing workflow. Case study: How marketing agencies use AI video tools to reduce production costs 80%. Case study: Aladiah Academy's own ElevenLabs voice synthesis infrastructure." },
      { title: "4.5 IBM Granite and Hugging Face: Open-Source Multimodal Models", desc: "IBM Granite's multimodal architecture and enterprise focus, deploying models from Hugging Face Hub (AutoModel, AutoTokenizer, the model card as trust signal), Transformers pipeline API for rapid prototyping, GGUF/GGML formats for CPU inference, LLaMA.cpp for local deployment, Ollama for developer-friendly local models, and the decision matrix: when open-source beats proprietary (data privacy, cost at scale, customization). Case study: How banks deploy IBM Granite on-premises for document analysis without data leaving their infrastructure." },
      { title: "4.6 Building a Production Multimodal Application: watsonx.ai, Flask, and Gradio", desc: "IBM watsonx.ai as an enterprise AI platform, Gradio for rapid multimodal UI prototyping (image upload, audio recording, file handling), deploying on IBM Cloud, integrating multiple modalities in a single application (user uploads invoice image → Whisper transcribes verbal context → GPT-4V extracts line items → LLM generates accounting entry), and production deployment architecture. Case study: Build a multimodal document processing system that handles PDFs, images, and audio annotations." },
      { title: "4.7 Module 4 Assessment: Multimodal AI Application Design", desc: "Design and prototype a multimodal AI application: given a use case (medical imaging assistant, e-commerce visual search, meeting intelligence platform), design the complete multimodal pipeline, select models for each modality, define the integration architecture, and build a working prototype with Gradio." },
    ]
  },
  {
    title: "Module 5: Fundamentals of AI Agents — Reasoning, Tools, and Autonomous Action",
    desc: "The foundational architecture of AI agents — the ReAct pattern, tool calling, memory systems, and the production safety patterns required for agents that take real-world actions. Covers IBM Course 6 completely and adds the production incident case studies and security analysis that every agent engineer needs.",
    lessons: [
      { title: "5.1 What Makes an AI Agent: The ReAct Pattern and the Agent Loop", desc: "Yao et al. 2022 'ReAct: Synergizing Reasoning and Acting in Language Models' — the foundational paper that defined modern agent architecture. The Thought → Action → Observation loop and why interleaving reasoning with action dramatically outperforms pure chain-of-thought (no action) or pure action (no reasoning). The agent loop as a computational pattern: perceive state → reason → select action → execute tool → observe result → repeat. Case study: How the original ReAct experiments outperformed fine-tuned models on HotpotQA and Fever with just prompting." },
      { title: "5.2 Function Calling and Tool Use: JSON Schema Design and Reliability Patterns", desc: "Provider-native function calling (OpenAI tools API, Anthropic tools, Gemini function declarations) — why structured JSON tool calls outperform text-based ReAct parsing by 90%+ in production reliability. Tool schema design: the description is the most important field (LLM reads it to decide when to call), enum types for constrained parameters, 'when NOT to use' guidance (reduces wrong tool selection 40% per OpenAI research). Parallel tool calling for independent operations. Case study: How GitHub Copilot Chat selects from 20+ tools to answer code questions." },
      { title: "5.3 Tool Execution Layer: Error Handling, Retry Logic, and Security Validation", desc: "The production tool execution layer that naive implementations skip — typed error responses (never raw exceptions to the LLM), exponential backoff with jitter for rate limits, circuit breakers for persistently failing services, 30-second timeout maximums, and the security layer that prevents exploitation. Argument validation against JSON schema before execution, SQL injection detection in database tool arguments, SSRF prevention in web access tools, and out-of-band confirmation for irreversible actions. Case study: Air Canada chatbot liability ($650 refund ordered by court) — what explicit capability boundaries in the tool execution layer would have prevented." },
      { title: "5.4 LangChain Agents: Built-in Agents for Data Analysis and Database Queries", desc: "LangChain's agent types (ZERO_SHOT_REACT_DESCRIPTION, CONVERSATIONAL_REACT_DESCRIPTION, STRUCTURED_CHAT_ZERO_SHOT), create_react_agent and AgentExecutor, built-in tools (Python REPL, SQL database, DuckDuckGo search, Wikipedia, Wolfram Alpha), custom tool creation with @tool decorator, tool selection and error handling in AgentExecutor (handle_parsing_errors, max_iterations), and the complete data analysis agent pattern (upload CSV → generate visualizations → answer statistical questions). Case study: Databricks' AI assistant using LangChain agents for data exploration." },
      { title: "5.5 Agent Memory Systems: Conversation History, Episodic Memory, and External Storage", desc: "Working memory (context window — cleared each session), episodic memory (conversation history database — enables recalling past interactions), semantic memory (accumulated facts about users and entities — enables personalization), and procedural memory (learned tool usage patterns). Context window management: message summarization (replace old messages with LLM-generated summaries), hierarchical memory (last 5 turns full, last 50 turns summarized, older as facts), and selective retrieval (retrieve relevant past context via semantic search). Case study: How Claude.ai's memory system accumulates user preferences across sessions." },
      { title: "5.6 Human-in-the-Loop: Approval Gates, Clarification, and Safe Autonomous Operation", desc: "When to require human approval (irreversible actions, high financial impact, ambiguous authorization), the interrupt-and-resume pattern (pause agent execution, present action for review, resume or reject), Anthropic's finding that HITL approval for irreversible actions reduced catastrophic agent failures by 73%, and the confidence-based escalation pattern (agent estimates confidence, escalates below threshold). Case study: How Cognition AI's Devin architecture implements human checkpoints for ambiguous engineering decisions." },
      { title: "5.7 Module 5 Assessment: Production Agent Architecture", desc: "Design a production-ready AI agent system for a complex use case (customer support agent with CRM access, research agent with web browsing and document analysis, or software engineering agent with code execution). Define tools, memory architecture, safety controls, and monitoring strategy." },
    ]
  },
  {
    title: "Module 6: Agentic AI with LangChain and LangGraph — Stateful, Reflective, and Adaptive Agents",
    desc: "Advanced agent architectures beyond simple ReAct loops — LangGraph's stateful graph-based agents, Reflection and Reflexion for self-improvement, multi-agent orchestration, and agentic RAG. Covers IBM Course 7 completely and adds production-scale patterns from Salesforce, Notion, and Cognition AI.",
    lessons: [
      { title: "6.1 LangGraph Architecture: State Graphs, Nodes, Edges, and Checkpointing", desc: "Why LangGraph supersedes linear LCEL chains — stateful graph execution where every node has access to full accumulated state (TypedDict), conditional edges for dynamic routing (different next step based on current state), cycles for iterative refinement (impossible in linear chains), and persistence via SQLite/PostgreSQL checkpointing (restart from last checkpoint after failure). The LangGraph mental model: nodes are functions that read and update state, edges define conditional flow. Case study: How a complex customer support workflow is modeled as a stateful graph with parallel processing branches." },
      { title: "6.2 Reflection and Reflexion: Self-Improving Agents That Learn from Failures", desc: "Shinn et al. 2023 'Reflexion: Language Agents with Verbal Reinforcement Learning' — agents that reflect on past failures and explicitly update their strategy. The Reflection pattern: after each action, agent evaluates outcome vs. goal, identifies what went wrong, adds critique to context. The Reflexion pattern: persistent verbal memory of past reflections, agent explicitly references past mistakes before new attempts. Case study: Reflexion agents outperforming GPT-4 on HumanEval (91% vs. 67%) through iterative self-correction. Case study: How Anthropic's Constitutional AI uses reflection principles." },
      { title: "6.3 ReAct, Plan-and-Execute, and Chain-of-Agents Architectures", desc: "Standard ReAct (interleaved reasoning and action), Plan-and-Execute (planner creates full plan upfront, executor follows it — better for long-horizon tasks), the Chain-of-Agents pattern (each agent handles one subtask and passes structured output to the next — reduces context contamination), and Tree of Thought agents (explore multiple solution paths simultaneously). When each architecture is appropriate: ReAct for dynamic tasks, Plan-and-Execute for structured workflows, Chain-of-Agents for parallelizable pipelines. Case study: AutoGPT's failures (no plan-and-execute = infinite loops) vs. Baby AGI's structured approach." },
      { title: "6.4 Agentic RAG: Dynamic Retrieval, Query Routing, and Retrieval-Enhanced Reasoning", desc: "Static RAG (retrieve once per query) vs. Agentic RAG (agent decides when, what, and how much to retrieve based on intermediate reasoning). Query routing (classify query → select appropriate retrieval strategy or knowledge source), corrective RAG (retrieve → evaluate relevance → re-retrieve if insufficient), iterative RAG (retrieve → reason → identify gaps → retrieve more), and Self-RAG (language model decides when to retrieve vs. answer from parametric knowledge). Case study: Perplexity AI's multi-step retrieval-enhanced reasoning for complex research queries." },
      { title: "6.5 LangGraph in Production: Persistence, Streaming, and Multi-Turn Applications", desc: "LangGraph's persistence layer (SqliteSaver for development, PostgresSaver for production), how checkpointing enables long-running agent sessions (resume a 2-hour research task after interruption), streaming intermediate agent thoughts to users (reduce perceived latency by showing progress), thread management for concurrent user sessions, and the production deployment architecture for LangGraph agents on Kubernetes. Case study: Linear's AI agent for project management using LangGraph for stateful multi-turn conversations." },
      { title: "6.6 Building with LangSmith: Tracing, Debugging, and Evaluating Agent Performance", desc: "LangSmith for LLM application observability — tracing every LLM call, tool invocation, and agent step in a visual timeline, identifying where latency occurs (which tool call takes longest), debugging unexpected agent behaviors (inspect the exact prompt and response at each step), creating evaluation datasets from production traces, and CI/CD integration for automated regression testing. Case study: How a team used LangSmith traces to discover that their agent was spending 40% of inference cost on a single redundant tool call." },
      { title: "6.7 Module 6 Assessment: Build a Stateful Agentic Application with LangGraph", desc: "Complete implementation: build a research agent using LangGraph with web search, RAG, and document generation tools. Implement reflection (agent evaluates output quality), checkpointing (resume after interruption), and streaming (show intermediate steps to user). Deploy with LangSmith tracing." },
    ]
  },
  {
    title: "Module 7: Multi-Agent Systems — CrewAI, AutoGen, LangGraph Multi-Agent, and BeeAI",
    desc: "Production multi-agent architectures — hierarchical orchestration, parallel execution, debate and critique, and the frameworks that make complex agent collaborations possible. Covers IBM Course 8 completely and adds Google DeepMind's research findings, Salesforce AgentForce architecture, and enterprise deployment patterns.",
    lessons: [
      { title: "7.1 Multi-Agent Architecture Patterns: Orchestrator-Worker, Pipeline, Fan-Out, and Debate", desc: "The four primary patterns: Hierarchical (orchestrator receives task → delegates to specialists → synthesizes results, used by Salesforce AgentForce), Sequential Pipeline (agent A output → agent B input → agent C output, used for document processing), Parallel Fan-Out (orchestrator dispatches to N agents simultaneously → merge results, used by Perplexity), Debate/Critique (multiple agents attempt the same task independently → judge agent selects best, Google DeepMind: 11.4% factual accuracy improvement). When to use each and the architecture tradeoffs." },
      { title: "7.2 CrewAI: Role-Based Multi-Agent Workflows for Enterprise Tasks", desc: "CrewAI architecture (Agents with Role/Goal/Backstory, Tasks with Description/Expected Output, Crews with Process type), hierarchical process (manager LLM delegates and reviews), sequential process (fixed task order), and parallel task execution. Custom tools with CrewAI (@tool decorator, BaseTool subclass), agent memory across tasks, human-in-the-loop for critical decisions, and the kickoff() workflow for production deployment. Case study: Building a content marketing crew (researcher agent → writer agent → SEO optimizer agent → editor agent) that produces 50 articles/day autonomously." },
      { title: "7.3 AG2 (AutoGen): Conversation-Driven Multi-Agent Systems", desc: "Microsoft's AutoGen (now AG2) architecture — ConversableAgent as the universal building block, UserProxyAgent for human-in-the-loop, AssistantAgent for LLM-powered behavior, GroupChat for multi-agent conversation management, and the code execution sandbox (AG2 executes Python in Docker — safety by containerization). Custom reply functions for complex agent logic, function registration for tool use, and nested chat for hierarchical task delegation. Case study: How AG2 powers Microsoft's Office AI features through multi-agent collaboration." },
      { title: "7.4 BeeAI: IBM's Framework for Production Agent Applications", desc: "BeeAI's agent architecture (LLM + Tools + Memory integration), built-in tools (Python interpreter, file system, web browser), memory adapters (InMemoryMemory, CustomMemory), the ReAct workflow implementation, and conversation-driven interactions with structured context management. IBM watsonx integration, enterprise security controls, and deployment on IBM Cloud. Comparison with LangChain Agents, CrewAI, and AutoGen — when BeeAI's enterprise-grade compliance features justify its use. Case study: How IBM uses BeeAI internally for enterprise knowledge management." },
      { title: "7.5 LangGraph Multi-Agent: Supervisor, Hierarchical, and Collaborative Architectures", desc: "LangGraph's multi-agent patterns: Supervisor node (routes between worker agents based on task type), hierarchical agents (supervisor can spawn sub-supervisors for complex domains), agent handoffs (Agent A finishes, explicitly hands off to Agent B with structured context), shared memory graph (all agents read/write the same state), and the network topology pattern (peer-to-peer agent communication). Case study: Salesforce AgentForce's architecture — how they coordinate 20+ specialized agents for complex CRM workflows." },
      { title: "7.6 State Management, Error Propagation, and AutoGPT's Failure Modes", desc: "The AutoGPT failure modes (documented 2023): infinite loops without termination conditions, unconstrained API cost ($1,000+ sessions), silent subtask failures causing downstream corruption, and no progress verification. Production countermeasures: max_iterations on every agent (never none), per-session cost budgets with hard cutoffs ($10/session default), structured error propagation (failed subtask returns typed error, orchestrator decides to retry/skip/escalate), and checkpoint-based progress verification. Case study: How to architect a multi-agent system that recovers gracefully when a sub-agent's external API fails." },
      { title: "7.7 Module 7 Assessment: Design and Deploy a Multi-Agent System", desc: "Production design challenge: architect a multi-agent system for a complex business workflow (investment research: data agent + analysis agent + risk agent + report generation agent). Define the orchestration pattern, state schema, error propagation, cost constraints, and human approval gates. Deploy with LangSmith tracing and monitoring." },
    ]
  },
  {
    title: "Module 8: Model Context Protocol (MCP) — The Universal AI Integration Standard",
    desc: "MCP (Model Context Protocol) as the emerging standard for connecting AI agents to tools, data sources, and services. Covers IBM Course 9 completely and adds production security patterns, enterprise deployment, and the complete architectural picture of why Anthropic designed MCP to replace custom tool integrations.",
    lessons: [
      { title: "8.1 MCP Architecture: Why the Protocol Exists and How It Changes AI Integration", desc: "The problem MCP solves: before MCP, every AI assistant required custom tool integrations (n models × m tools = n×m integrations). MCP provides n+m instead: each AI client implements the MCP client protocol once, each tool provider implements the MCP server once. Anthropic's November 2023 open-source release, adoption by OpenAI (April 2025), Google Gemini (May 2025), and every major AI provider. The three MCP primitives: Tools (model-invoked functions), Resources (data sources exposed to context), Prompts (reusable prompt templates). Case study: How Cursor IDE uses MCP to give Claude access to codebases, file systems, and external APIs." },
      { title: "8.2 Building MCP Servers with FastMCP: Tools, Resources, and Prompts", desc: "FastMCP (the high-level Python framework for MCP servers), @mcp.tool() decorator for tool definition, @mcp.resource() for exposing data sources, @mcp.prompt() for reusable prompt templates, and the complete server lifecycle (startup, request handling, shutdown). Tool schema design for MCP (identical principles to OpenAI function calling but with MCP-specific type annotations), error handling and status codes, and running servers locally for development. Case study: Build an MCP server that exposes a company's internal database as a searchable resource for Claude." },
      { title: "8.3 MCP Transport Protocols: STDIO, Streamable HTTP, and Production Deployment", desc: "STDIO transport (MCP client spawns server as subprocess, communicates via stdin/stdout — simple, local, no network required), Streamable HTTP (new in MCP 2024-11 spec, supports remote servers, server-sent events for streaming, OAuth 2.0 authentication). When to use each: STDIO for local tools and development, HTTP for cloud-deployed shared MCP servers. Production deployment on Cloud Run, Lambda, and Kubernetes. Authentication and authorization: API key headers, OAuth 2.0 flow, and the MCP permission model. Case study: How Anthropic's own MCP servers (filesystem, Slack, GitHub) are architected." },
      { title: "8.4 MCP Clients: Connecting to Single and Multiple Servers", desc: "Building MCP clients with the official Python SDK (mcp library), connecting to servers via STDIO and HTTP, tool discovery (list_tools()), resource listing (list_resources()), tool invocation (call_tool()), and resource reading (read_resource()). Multi-server clients: connecting to filesystem, GitHub, Slack, and database MCP servers simultaneously, tool namespace management, and the complete client lifecycle. Integration with LangChain and LangGraph (MCP adapters for using MCP tools in agent workflows). Case study: Building a Claude-powered development assistant that accesses files, GitHub, and Jira simultaneously via MCP." },
      { title: "8.5 MCP Security: Sampling, Roots, and Permission-Based User Approval", desc: "MCP's security model: Sampling (server requests LLM completion from client — server never has direct model access, reduces data leakage risk), Roots (server declares what filesystem paths it can access — principle of least privilege at the protocol level), and User Approval (client must present tool calls to user for approval before execution — MCP-level out-of-band confirmation). Threat model for MCP: prompt injection via tool results, server-side data exfiltration, and privilege escalation through chained MCP calls. Security audit checklist for MCP server deployment." },
      { title: "8.6 Enterprise MCP Deployment: Authentication, Rate Limiting, and Audit Trails", desc: "OAuth 2.0 for MCP server authentication (Claude for Work uses OAuth for enterprise MCP connections), API rate limiting to prevent runaway agent costs, request/response logging for compliance (EU AI Act Article 15 logging requirements), MCP server health monitoring, and the enterprise MCP server registry pattern (catalog of approved MCP servers for an organization). Case study: How a Fortune 500 company deploys internal MCP servers for Claude Enterprise, giving employees AI access to internal knowledge bases with full audit trails." },
      { title: "8.7 Module 8 Assessment: Build and Deploy a Production MCP Server", desc: "Complete MCP project: design and implement an MCP server exposing a business database (tools: query, insert, update) and document store (resources: search, retrieve). Implement OAuth authentication, request logging, and rate limiting. Connect via an MCP client and demonstrate Claude using the server to answer complex business questions." },
    ]
  },
  {
    title: "Module 9: Agent Security, Evaluation, and Production Operations",
    desc: "The production discipline that separates hobby agents from enterprise-grade systems — prompt injection defense, agent evaluation frameworks, production monitoring, cost optimization, and the operational practices that keep multi-agent systems reliable at scale.",
    lessons: [
      { title: "9.1 Prompt Injection Attacks Against Agents: Direct, Indirect, and Jailbreak Patterns", desc: "The OWASP LLM Top 10's #1 risk for agent systems. Direct injection (user attempts to override system prompt), indirect injection (malicious instructions embedded in tool results, retrieved documents, or emails — the Bing Chat Sydney incident), and the Zou et al. 2023 adversarial suffix finding (automated gradient optimization produces universal jailbreaks transferable across models). The specific threat to agents: successful injection in a tool-using agent can exfiltrate data, execute unauthorized actions, and bypass all security controls." },
      { title: "9.2 Defense Architecture for Production Agents: Isolation, Validation, and Monitoring", desc: "Defense layer 1 (Input Isolation): structural delimiters, meta-instructions, content type tagging. Defense layer 2 (Privilege Minimization): minimum viable tool set, compartmentalized capabilities, out-of-band confirmation for high-impact actions. Defense layer 3 (Output Validation): secondary LLM classifier reviewing agent outputs before execution, canary injections in retrieved content, policy compliance checking. Defense layer 4 (Infrastructure): network isolation for code execution, sandboxed environments (Docker), immutable audit logs. The blast radius principle: design so that maximum injection damage is bounded." },
      { title: "9.3 Agent Evaluation: Trajectory Assessment, Tool Use Accuracy, and LLM-as-Judge", desc: "Why traditional NLP metrics fail for agents (agents can reach correct answers via different tool paths). Trajectory evaluation: grade the complete action sequence, not just the final answer. Tool use accuracy: did the agent call the right tools with the right arguments? Task success rate vs. efficiency (optimal tool calls). LLM-as-judge for agent evaluation (GPT-4 evaluating whether a research agent's report is factually grounded and comprehensive). AgentBench, GAIA, SWE-bench as standardized evaluation sets. Case study: How Anthropic evaluates Claude's agentic capabilities before every release." },
      { title: "9.4 Production Cost Optimization: Token Budgets, Caching, and Model Cascades", desc: "Agent cost modeling (tokens × calls × price = session cost), setting per-session and per-user token budgets with hard enforcement, prompt caching (Anthropic's prompt caching: 90% cost reduction for repeated system prompts, 85% latency reduction), response caching (semantic similarity matching to serve cached responses for similar queries), and the model cascade architecture (route 80% of agent tool calls to cheap models, only 20% of complex reasoning to frontier models). Case study: Reducing a multi-agent research system from $2.00/session to $0.12/session." },
      { title: "9.5 Agent Observability: Tracing, Logging, and Production Monitoring with Langfuse", desc: "Langfuse (open-source LLM observability) vs. LangSmith vs. Arize Phoenix — complete trace visualization for every agent run, cost tracking per user and session, quality score tracking (user feedback, LLM-as-judge automated scoring), latency analysis (which tools cause bottlenecks), anomaly detection (unusual tool calling patterns may indicate injection), and the production dashboard every agent system needs. Integration with LangChain, LangGraph, and custom agent implementations." },
      { title: "9.6 Incident Response for Agent Systems: Detecting and Responding to Agent Failures", desc: "Agent-specific incident types: injection campaign detected (systematic adversarial inputs), cost anomaly (agent in infinite loop spending $100/minute), tool abuse (agent calling external APIs in unauthorized ways), data exfiltration attempt (agent attempting to send data to external destinations), and model quality degradation (underlying LLM performing worse after silent update). For each: early detection signals, automated response (kill switch, rate limit, quarantine), evidence preservation, and post-incident analysis." },
      { title: "9.7 Module 9 Assessment: Agent Security Audit and Production Readiness Review", desc: "Complete security and production readiness audit of a provided agent system. Identify prompt injection vulnerabilities, excessive privilege issues, missing human approval gates, cost control gaps, and monitoring blindspots. Produce a prioritized remediation plan and implement the three highest-priority fixes." },
    ]
  },
  {
    title: "Module 10: Agentic AI Capstone — Build, Evaluate, and Deploy a Production Multi-Agent System",
    desc: "The synthesis of the entire AI Agent Engineer curriculum. Build a complete production multi-agent system from requirements through deployment — combining RAG, multi-agent orchestration, MCP integration, security controls, evaluation, and monitoring. This is what makes you an expert AI Agent Engineer.",
    lessons: [
      { title: "10.1 Capstone System Design: Architecture Decision Records and Trade-off Analysis", desc: "Translating business requirements into agent system architecture decisions. The Architecture Decision Record (ADR) pattern for documenting framework choices (why LangGraph over CrewAI?), model selections (why GPT-4o-mini for routing + GPT-4o for analysis?), vector database choices, and infrastructure decisions. Trade-off analysis: capability vs. cost, autonomy vs. safety, latency vs. accuracy. Case study: Complete ADR set for a financial research multi-agent system." },
      { title: "10.2 Unstructured Data Processing: JSON Extraction and Multimodal Pipelines", desc: "LLMs for structured data extraction from unstructured text and images (Pydantic models as extraction schemas, few-shot examples for consistent extraction), processing PDFs with mixed content (text, tables, images), audio transcription and entity extraction, and building multimodal data pipelines that feed agent knowledge bases. Case study: Transforming 10,000 unstructured customer support tickets into structured training data using LLM extraction." },
      { title: "10.3 Multi-Agent System Architecture: Coordinator, Specialized Agents, and Data Flows", desc: "Designing the complete multi-agent system: coordinator agent (task decomposition, delegation, synthesis), specialized agents (retrieval agent, analysis agent, validation agent, generation agent), shared state schema design, inter-agent communication patterns, failure handling (when agent A fails, coordinator decides retry/skip/escalate), and the complete data flow diagram. Case study: A financial due diligence system with 5 specialized agents working in parallel." },
      { title: "10.4 MCP Integration: Connecting Agents to Enterprise Data Sources", desc: "Integrating MCP servers for enterprise data access: internal database MCP server, document management system MCP server, CRM MCP server, and external data APIs. Multi-server MCP client configuration, tool namespace management across servers, permission boundaries (which agents access which MCP servers), and the complete integration test suite for MCP connections. Configuring OAuth authentication and audit logging for enterprise deployment." },
      { title: "10.5 Testing and Validation: Unit Tests, Integration Tests, and Adversarial Evaluation", desc: "Testing pyramid for agent systems: unit tests (individual tool functions), integration tests (agent with mocked tool responses), end-to-end tests (full agent run with real tools), and adversarial tests (injection attempts, malicious tool responses, adversarial user inputs). Golden dataset creation (50 representative queries with expected outputs and tool usage), regression testing for agent behavior (ensure model updates don't degrade performance), and chaos testing (what happens when the vector database is unavailable, an MCP server times out)." },
      { title: "10.6 Production Deployment: Kubernetes, Scaling, and Cost Management", desc: "Deploying multi-agent systems on Kubernetes (FastAPI serving layer, agent worker pool, async task queue with Redis/Celery), horizontal scaling for concurrent agent sessions, GPU resource management for self-hosted models, per-user session isolation, multi-tenant token budget enforcement, cost attribution per team and project, and the complete production runbook. Case study: Architecture supporting 10,000 concurrent agent sessions at $0.05/session economics." },
      { title: "10.7 Final Certification: AI Agent Engineer Expert Examination", desc: "200-question comprehensive examination covering all 10 modules: LLM fundamentals, RAG architecture, vector databases, multimodal AI, agent patterns, LangGraph, multi-agent systems, MCP, security, and production operations. Includes three open-ended system design challenges requiring architectural justification. Passing threshold: 85%. Award: Aladiah Academy AI Agent Engineer Expert Certification — the most comprehensive agentic AI certification available, demonstrating the expertise to design, build, secure, and operate production AI agent systems at enterprise scale." },
    ]
  }
];

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);

    const { data: course, error: ce } = await supabase.from("courses").insert({
      title: COURSE_TITLE,
      description: "The world's most comprehensive AI Agent Engineering certification — 10 deep modules, 70+ lessons covering LLM foundations, RAG architecture, vector databases, multimodal AI, ReAct agents, LangGraph, multi-agent systems (CrewAI, AutoGen, BeeAI), Model Context Protocol (MCP), agent security, and a production capstone. Inspired by and surpassing IBM's Agentic AI specialization. Every lesson grounded in research papers, real production incident case studies, and implementation patterns from Anthropic, Google, Microsoft, Salesforce, and leading AI companies.",
      is_published: true,
      translations: {
        es:{title:"Ingeniero de Agentes IA",description:"La certificación más completa del mundo en ingeniería de agentes IA — 10 módulos, LangGraph, MCP, CrewAI, seguridad, producción."},
        fr:{title:"Ingénieur en Agents IA",description:"La certification la plus complète au monde en ingénierie d'agents IA — 10 modules approfondis."},
        de:{title:"KI-Agent-Ingenieur",description:"Die umfassendste KI-Agent-Engineering-Zertifizierung der Welt — 10 tiefe Module."},
        zh:{title:"AI智能体工程师",description:"全球最全面的AI智能体工程师认证 — 10个深度模块，覆盖LangGraph、MCP、多智能体系统。"},
        ar:{title:"مهندس وكلاء الذكاء الاصطناعي",description:"أشمل شهادة هندسة وكلاء الذكاء الاصطناعي في العالم — 10 وحدات متعمقة."},
        ja:{title:"AIエージェントエンジニア",description:"世界最高峰のAIエージェントエンジニアリング認定 — 10の深いモジュール。"},
      }
    }).select().single();
    if (ce) throw ce;

    let chaptersCreated = 0;
    let videosCreated = 0;

    for (let mi = 0; mi < modules.length; mi++) {
      const mod = modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({
        course_id: course.id, title: mod.title, description: mod.desc,
        order_index: mi, translations: {}
      }).select().single();
      if (che) throw che;
      chaptersCreated++;

      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = `${les.title}\n\n${les.desc}\n\nThis lesson is part of the AI Agent Engineer Expert certification at Aladiah Academy — the world's most comprehensive agentic AI curriculum, inspired by and surpassing IBM's Generative AI and Agentic AI specialization on Coursera.\n\nProf. Didier teaches this content with the depth of a principal engineer who has built and operated agent systems at scale, grounded in:\n\n• Primary research papers: Vaswani et al. 2017 (Transformers), Lewis et al. 2020 (RAG), Yao et al. 2022 (ReAct), Shinn et al. 2023 (Reflexion), Zou et al. 2023 (adversarial agents)\n• Production incident case studies: Air Canada chatbot lawsuit, AutoGPT failure modes, Bing Chat injection incidents\n• Real implementation patterns from: Anthropic, OpenAI, Google DeepMind, Salesforce, Microsoft, IBM, Perplexity AI, and Notion\n• Hands-on implementation with: LangChain, LangGraph, CrewAI, AutoGen/AG2, BeeAI, MCP, ChromaDB, FAISS, Pinecone, Weaviate\n\nModule context: ${mod.title}\n${mod.desc}`;

        const trans = {
          en:{title:les.title,transcript},
          es:{title:les.title,transcript},
          fr:{title:les.title,transcript},
          de:{title:les.title,transcript},
          zh:{title:les.title,transcript},
          ar:{title:les.title,transcript},
          ja:{title:les.title,transcript}
        };

        const { data: video, error: ve } = await supabase.from("videos").insert({
          chapter_id: chapter.id, title: les.title, description: les.desc,
          order_index: li, translations: trans
        }).select().single();
        if (ve) throw ve;
        videosCreated++;

        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({
          video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85
        }).select().single();
        if (qe) throw qe;

        const shortTitle = les.title.replace(/^\d+\.\d+\s/, '');
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: `What production-critical skill does "${shortTitle}" teach?`, scenario_context: `You are interviewing for an AI Agent Engineer role and asked to explain this topic.`, options: [les.desc.substring(0, 100) + (les.desc.length > 100 ? "..." : ""), "This is only a theoretical concept", "This is covered by basic ML courses", "This is only for research scientists"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: `Which research paper or real-world incident is central to "${shortTitle}"?`, scenario_context: "Demonstrating depth of knowledge in an expert-level interview.", options: ["Key papers and case studies including real incidents from IBM, Anthropic, Google, and Microsoft are covered", "No research references are needed for this topic", "Only vendor documentation is referenced", "This topic has no published research"], correct_answer_index: 0, explanation: "Every lesson in this program references primary research papers and real production incidents — building pattern recognition from documented real-world experience.", order_index: 1 },
          { quiz_id: quiz.id, question_text: `What framework or tool is used to implement "${shortTitle}" in production?`, scenario_context: "A hiring manager asks about your hands-on implementation experience.", options: ["Production frameworks covered include LangChain, LangGraph, CrewAI, AutoGen, BeeAI, MCP, ChromaDB, FAISS, and provider APIs", "No specific tools are taught", "Only academic implementations are covered", "Tools are out of scope for this topic"], correct_answer_index: 0, explanation: "Hands-on implementation with industry-standard tools is a core requirement of this curriculum — every concept is taught alongside its production implementation.", order_index: 2 },
        ]);
      }

      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({
        chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85
      }).select().single();
      if (eqe) throw eqe;

      const modShort = mod.title.replace(/^Module \d+:\s/, '');
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: `What expert-level capability does completing "${modShort}" demonstrate?`, scenario_context: "Module completion certification assessment.", options: [mod.desc.substring(0, 120) + "...", "Only introductory familiarity", "Theoretical knowledge without production application", "Knowledge covered by basic Python courses"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "Which IBM Coursera specialization courses does this module's content encompass and exceed?", scenario_context: "Comparing certification programs for professional development.", options: ["Covers and exceeds the equivalent IBM Generative AI / Agentic AI Coursera courses with additional production case studies, security analysis, and enterprise patterns not in any existing certification", "Only equivalent to basic online tutorials", "Less comprehensive than IBM's program", "Not comparable to any industry certification"], correct_answer_index: 0, explanation: "This curriculum is specifically designed to cover everything in IBM's Agentic AI specialization while adding research paper depth, production incident analysis, and enterprise deployment patterns.", order_index: 1 },
        { quiz_id: eq.id, question_text: "What salary range does demonstrated mastery of agentic AI engineering support?", scenario_context: "Career planning after completing the AI Agent Engineer certification.", options: ["$130K-$250K AI Agent Engineer roles — one of the fastest-growing and highest-compensated specializations in software engineering globally", "Entry-level salaries only", "Only academic research positions", "Freelance work only"], correct_answer_index: 0, explanation: "AI Agent Engineers who can design, build, secure, and operate production multi-agent systems are among the most sought-after engineers globally, commanding significant compensation premiums.", order_index: 2 },
        { quiz_id: eq.id, question_text: "Which production incident case studies are analyzed in this module?", scenario_context: "Learning from documented failures to prevent them in your own systems.", options: ["Real documented incidents including Air Canada chatbot liability lawsuit, AutoGPT infinite loop failures, Bing Chat/Sydney injection incidents, and others with root cause analysis and prevention", "No incident analysis", "Only synthetic examples", "Incidents are classified and not shared"], correct_answer_index: 0, explanation: "Production incident case studies are the fastest path to expertise — this curriculum analyzes documented real-world failures so you can design systems that prevent them.", order_index: 3 },
        { quiz_id: eq.id, question_text: "After completing this module, what can you immediately build and deploy?", scenario_context: "Your first week as an AI Agent Engineer at a top AI company.", options: ["Production-ready agent systems applying this module's patterns, tools, and security controls — not just prototypes but enterprise-grade deployable systems", "Only proof-of-concept notebooks", "Systems requiring months of additional learning", "Only systems with significant vendor support"], correct_answer_index: 0, explanation: "Every module is designed for immediate production application — the skills are battle-tested patterns from production systems, not academic exercises.", order_index: 4 },
      ]);
    }

    return new Response(JSON.stringify({
      message: "AI Agent Engineer — 10-module world-class version seeded",
      courseId: course.id,
      modules: chaptersCreated,
      lessons: videosCreated
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });

  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
});
