import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const courseData = {
  "title": "AI Security Engineer",
  "description": "Master AI-specific security engineering: adversarial ML, prompt injection defense, model supply chain security, differential privacy, red teaming, EU AI Act, NIST AI RMF, GDPR, secure AI architecture, and incident response.",
  "translations": {"es": {"title": "AI Security Engineer", "description": "Master AI-specific security engineering: adversarial ML, prompt injection defense, model supply chain security, differential privacy, red teaming, EU AI Act, NIST AI RMF, GDPR, secure AI architecture, and incident response."}, "fr": {"title": "AI Security Engineer", "description": "Master AI-specific security engineering: adversarial ML, prompt injection defense, model supply chain security, differential privacy, red teaming, EU AI Act, NIST AI RMF, GDPR, secure AI architecture, and incident response."}, "de": {"title": "AI Security Engineer", "description": "Master AI-specific security engineering: adversarial ML, prompt injection defense, model supply chain security, differential privacy, red teaming, EU AI Act, NIST AI RMF, GDPR, secure AI architecture, and incident response."}, "zh": {"title": "AI Security Engineer", "description": "Master AI-specific security engineering: adversarial ML, prompt injection defense, model supply chain security, differential privacy, red teaming, EU AI Act, NIST AI RMF, GDPR, secure AI architecture, and incident response."}, "ar": {"title": "AI Security Engineer", "description": "Master AI-specific security engineering: adversarial ML, prompt injection defense, model supply chain security, differential privacy, red teaming, EU AI Act, NIST AI RMF, GDPR, secure AI architecture, and incident response."}, "ja": {"title": "AI Security Engineer", "description": "Master AI-specific security engineering: adversarial ML, prompt injection defense, model supply chain security, differential privacy, red teaming, EU AI Act, NIST AI RMF, GDPR, secure AI architecture, and incident response."}},
  "modules": [
  {"title": "Module 1: AI Threat Landscape, Attack Taxonomy, and Defense Architecture", "desc": "The unique security risks of AI systems — OWASP LLM Top 10, documented production incidents, and defense-in-depth architecture.", "lessons": [
    {"title": "1.1 The AI Attack Surface: Five Threat Categories", "desc": "Data poisoning, adversarial examples, model theft, prompt injection, and inference attacks with real incident case studies."},
    {"title": "1.2 Prompt Injection: The #1 LLM Security Risk", "desc": "Direct vs indirect injection, documented incidents against Bing Chat and GitHub Copilot, and the multi-layer defense strategy."},
    {"title": "1.3 Adversarial Robustness: Attacks, Defenses, and Certified Guarantees", "desc": "FGSM to AutoAttack, adversarial training, randomized smoothing, and gradient masking detection."},
    {"title": "1.4 Differential Privacy: Mathematical Guarantees for Sensitive Data", "desc": "DP-SGD for neural network training, the privacy-utility tradeoff, and production implementations."},
    {"title": "1.5 AI Red Teaming: Methodology, Tools, and Production Security Operations", "desc": "Red teaming taxonomy, automated tools Garak and PyRIT, model supply chain security, and AI SecOps."}
  ]},
  {"title": "Module 2: LLM Security — Jailbreaks, Output Security, and Runtime Defense", "desc": "Advanced jailbreaking techniques, insecure output handling, LLM denial of service, sensitive information disclosure, and agentic AI security.", "lessons": [
    {"title": "2.1 Advanced Jailbreaking: Crescendo, Many-Shot, and Automated Attacks", "desc": "Full taxonomy of modern jailbreaking with defense strategies."},
    {"title": "2.2 Insecure Output Handling and LLM-Generated Code Security", "desc": "SQL injection, XSS, command injection from LLM-generated content, and secure output handling patterns."},
    {"title": "2.3 LLM Denial of Service, Resource Security, and Sensitive Information Disclosure", "desc": "Prompt flooding, context exhaustion, multi-tenant isolation, PII detection, and compliance requirements."},
    {"title": "2.4 Agentic AI Security: Tool Abuse, Privilege Escalation, and Multi-Agent Attacks", "desc": "Security challenges unique to agentic systems — tool abuse, multi-agent trust hierarchies, and the security architecture for production agent deployments."},
    {"title": "2.5 Model Supply Chain Security and Secure MLOps", "desc": "Securing ML infrastructure from training through deployment — artifact integrity, CI/CD security gates, and secrets management."}
  ]},
  {"title": "Module 3: Adversarial ML — Physical Attacks, NLP, Tabular Models, and Watermarking", "desc": "Adversarial attacks across all modalities — physical-world attacks, NLP adversarial examples, tabular model attacks, model watermarking, and security testing methodology.", "lessons": [
    {"title": "3.1 Physical-World Adversarial Attacks and Real-World AI Failures", "desc": "Stop sign attacks, autonomous vehicle exploits, face recognition bypasses, and medical imaging adversarial examples."},
    {"title": "3.2 NLP Adversarial Attacks and Model IP Protection", "desc": "Text perturbations, semantic attacks, LLM robustness, model watermarking, and IP protection for AI models."},
    {"title": "3.3 AI Governance, EU AI Act, and Compliance Engineering", "desc": "EU AI Act risk categories, high-risk requirements, NIST AI RMF, ISO 42001, bias fairness, and building a governance program."},
    {"title": "3.4 Secure AI Architecture: Zero Trust, Kubernetes, and API Security", "desc": "Zero trust for AI systems, Kubernetes security for ML workloads, API security for AI services, and secure model serving."},
    {"title": "3.5 AI Security Operations: Monitoring, Incident Response, and Security Program", "desc": "AI security incident taxonomy, detection mechanisms, incident response playbooks, security metrics, and building the AI security operations function."}
  ]},
  {"title": "Module 4: Supply Chain Security — Model Provenance, Dependencies, and SBOM", "desc": "The AI supply chain spans training data, open-source models, Python packages, and cloud services — each is an attack vector. Model signing, SLSA for ML, SBOM generation, and dependency security.", "lessons": [
    {"title": "4.1 The ML Supply Chain Attack Surface", "desc": "SolarWinds (2020) demonstrated that supply chain compromise can affect 18,000 organizations through a single trusted update. The ML supply chain has five attack surfaces: training data (Nightshade-style poisoning of public datasets), pre-trained models (backdoored weights on HuggingFace Hub), Python packages (typosquatting — ultralytics vs ulralytics), cloud ML services (compromised managed traini"},
    {"title": "4.2 SafeTensors vs Pickle: Secure Model Serialization", "desc": "Pickle is Python's default serialization format and enables arbitrary code execution — any Python object including os.system() calls can be embedded in a .pkl or .pt file. SafeTensors (Hugging Face, 2022): a safe, fast alternative that stores only tensor data — no arbitrary code execution possible. Adoption: Hugging Face Hub now defaults to SafeTensors for model weights, flagging Pickle-format mod"},
    {"title": "4.3 Model Signing and Provenance with Sigstore and ONNX", "desc": "Model signing provides cryptographic proof of origin and integrity — the same guarantee container image signing provides for code. Sigstore's keyless signing: OIDC-based identity (GitHub Actions OIDC token), Cosign signs the model artifact hash, signature stored in the public Rekor transparency log. ONNX model verification: hash the ONNX file with SHA-256, sign the hash, verify before loading in a"},
    {"title": "4.4 Software Bill of Materials for AI: SPDX and CycloneDX ML Extensions", "desc": "An SBOM for an AI system documents all components: training data (source, license, collection date), base model (architecture, parameter count, pre-training dataset), fine-tuning data, Python dependencies (with CVE status), and serving infrastructure components. SPDX 3.0 AI Profile: extends the software SBOM standard with AI-specific fields (model card reference, training dataset description, inte"},
    {"title": "4.5 Dependency Security: Typosquatting, Compromised Packages, and Auditing", "desc": "Python package supply chain attacks target ML teams specifically — popular ML package names are valuable typosquatting targets. Documented attacks: ultralytics (YOLO object detection) cloned as ulralytics, ultralytics2, ultralytics-gpu — malicious versions install cryptocurrency miners or exfiltrate environment variables. Defense stack: pip-audit (scan installed packages against OSV vulnerability "},
    {"title": "4.6 Training Data Provenance and Integrity Verification", "desc": "Training data is the input with the most impact on model behavior and the least security attention. Data provenance chain: collection (source URL, collection date, license), preprocessing (transformations applied, tools used, hashes of intermediate outputs), final dataset (SHA-256 hash of every file, manifest). Dataset versioning with DVC: content-addressed storage means the hash is the version id"},
    {"title": "4.7 Module 4 Assessment: Supply Chain Security Audit", "desc": "Conduct a complete supply chain security audit of a provided ML system: identify Pickle-format model loading, unsigned artifacts in the pipeline, dependencies with known CVEs, missing SBOM documentation, and training data provenance gaps. Produce a risk-ranked remediation plan with specific technical recommendations."}
  ]},
  {"title": "Module 5: Red Teaming AI Systems — Structured Adversarial Testing", "desc": "Red teaming is the systematic attempt to find failures in AI systems before adversaries do. LLM red teaming methodology, automated red teaming with PAIR and Garak, jailbreak taxonomy, and the red teaming practices at Anthropic, Microsoft, and OpenAI.", "lessons": [
    {"title": "5.1 AI Red Teaming Methodology: Scope, Threat Models, and Documentation", "desc": "AI red teaming differs from traditional penetration testing: the goal isn't finding code vulnerabilities but finding behavioral failures — content policy violations, safety bypasses, unintended capabilities, and privacy leakage. Red team methodology: define scope (which system behaviors are in-scope), develop threat model (what are the adversary archetypes — curious user, malicious actor, nation-s"},
    {"title": "5.2 Jailbreak Taxonomy: Understanding Attack Techniques", "desc": "Jailbreaks are techniques that cause LLMs to violate their guidelines. Taxonomy of jailbreak classes: persona attacks (DAN — Do Anything Now, fictional character roleplay), context manipulation (hypothetical framing, academic research framing), multi-turn attacks (gradually escalating requests to normalize boundary violations across turns), encoding tricks (ROT13, Base64, leetspeak to obscure poli"},
    {"title": "5.3 Automated Red Teaming: PAIR, Garak, and PyRIT", "desc": "Manual red teaming doesn't scale — automated tools enable comprehensive coverage across thousands of attack variations. PAIR (Prompt Automatic Iterative Refinement, Chao et al. 2023): uses an attacker LLM to iteratively refine jailbreaks against a target LLM, achieving 80%+ attack success rates against GPT-3.5 with 20 iterations. Garak (LLM Vulnerability Scanner): open-source tool that runs 30+ pr"},
    {"title": "5.4 Red Teaming LLM Agents: Tool Use and Agentic Attack Surfaces", "desc": "LLM agents with tool access have attack surfaces that don't exist for pure chat models. Agent-specific red teaming scenarios: tool permission escalation (agent granted read access manipulated into write access), context window poisoning (injecting malicious instructions into retrieved documents), multi-agent trust abuse (agent A instructs agent B to perform prohibited actions it could not do itsel"},
    {"title": "5.5 Multimodal Red Teaming: Visual Prompt Injection and Audio Attacks", "desc": "Vision-language models (GPT-4V, Claude 3, Gemini) combine image and text processing — creating new attack surfaces at the modality boundary. Visual prompt injection: embedding text instructions in images that the VLM processes as instructions while human reviewers see only an image. Research demonstration: placing white text on light background encoding jailbreak instructions in an image successfu"},
    {"title": "5.6 Red Team Reporting: Documentation, Severity Rating, and Remediation", "desc": "Red team findings are only valuable if they drive remediation. Vulnerability report structure: title (descriptive, non-jargon), reproduction steps (exact prompts, any required setup), observed behavior (what the model did), expected behavior (what the model should do), harm category (from defined taxonomy), severity rating (critical/high/medium/low based on harm probability × impact), and recommen"},
    {"title": "5.7 Module 5 Assessment: Red Team Exercise", "desc": "Execute a structured red team assessment of a provided LLM application (simulated). Apply the jailbreak taxonomy systematically, use automated tools (Garak) for broad coverage, document 5+ findings with full reproduction steps, severity ratings, and remediation recommendations. Present findings in a formal red team report format."}
  ]},
  {"title": "Module 6: Privacy Engineering for AI — Differential Privacy, Federated Learning, and GDPR", "desc": "AI systems process sensitive data at scale. Differential privacy mathematics, federated learning architectures, GDPR technical requirements, synthetic data for privacy-preserving ML, and the privacy engineering practices at Apple, Google, and Meta.", "lessons": [
    {"title": "6.1 Privacy Threats in ML: Membership Inference, Model Inversion, and Memorization", "desc": "ML models trained on sensitive data leak information through three attack vectors. Membership inference attacks (Shokri et al. 2017): determine whether a specific record was in the training set. Methodology: train shadow models to learn the distinction between training data (higher confidence predictions) and non-training data. Membership inference success rates of 80%+ against overfitted models. "},
    {"title": "6.2 Differential Privacy: Mathematical Guarantees for Training Data Protection", "desc": "Differential privacy (Dwork et al. 2006) provides a mathematical guarantee: an algorithm is ε-differentially private if the probability of any output changes by at most e^ε when any single training example is added or removed. The privacy parameter ε: smaller ε = stronger privacy guarantee = more noise = lower model accuracy. The privacy-utility tradeoff. DP-SGD (Abadi et al. 2016): add calibrated"},
    {"title": "6.3 Federated Learning: Training Without Centralized Data", "desc": "Federated learning (McMahan et al. 2017, Google) enables training on distributed data without centralizing sensitive information. The federated learning loop: server sends global model to selected clients, each client trains locally on their private data, clients send only model updates (gradients or weights) to server, server aggregates updates (FedAvg — weighted average by dataset size) into new"},
    {"title": "6.4 GDPR Technical Requirements for ML Systems", "desc": "GDPR (General Data Protection Regulation, EU, 2018) imposes specific technical obligations on AI systems. Article 5 (data minimization): collect only data necessary for the specific ML purpose. Article 17 (right to erasure): ability to delete a specific user's data from training datasets and retrain without it — machine unlearning. Article 22 (automated decision making): right to explanation for a"},
    {"title": "6.5 Machine Unlearning: Implementing the Right to Erasure for ML Models", "desc": "GDPR Article 17's right to erasure creates a technical problem for ML: deleting a data point from the training database doesn't remove its influence from a trained model. Machine unlearning approaches: exact unlearning (retrain from scratch excluding the data point — perfect guarantee, prohibitively expensive for large models), approximate unlearning (gradient-based methods that approximate exact "},
    {"title": "6.6 Synthetic Data Generation: Privacy-Preserving Training Data at Scale", "desc": "Synthetic data replaces sensitive training data with statistically equivalent artificial data that contains no real individuals. GAN-based synthesis: CTGAN (Conditional Tabular GAN) for tabular data — learns column distributions and correlations, generates synthetic rows. Diffusion models for image synthesis — generate synthetic medical images for training diagnostic models. Differential privacy f"},
    {"title": "6.7 Module 6 Assessment: Privacy Engineering Design", "desc": "Design the complete privacy engineering solution for a healthcare AI system processing patient records: identify privacy threats (membership inference, memorization), apply differential privacy to the training pipeline (select appropriate ε, implement DP-SGD), design federated learning architecture for multi-hospital training without centralizing patient data, document GDPR compliance (legal basis"}
  ]},
  {"title": "Module 7: Secure AI Architecture — Zero Trust, Access Control, and Runtime Defense", "desc": "Production AI systems require security architecture as rigorous as the models they serve. Zero trust for AI APIs, IAM for model access, runtime threat detection, API security, and the architectures at Stripe, Cloudflare, and AWS.", "lessons": [
    {"title": "7.1 Zero Trust Architecture for AI API Services", "desc": "Traditional perimeter security assumes everything inside the network is trusted — a model that worked when AI was internal fails when AI APIs serve external traffic. Zero trust principles (NIST SP 800-207): verify explicitly (authenticate and authorize every request, every time — no implicit trust from network location), use least privilege access (limit AI API permissions to minimum required), as"},
    {"title": "7.2 Authentication and Authorization for AI APIs: API Keys, OAuth, and RBAC", "desc": "AI API security requires layered authentication and authorization. API key management: API keys are bearer tokens — must be transmitted only over HTTPS, stored hashed (not plaintext), have defined scopes (read predictions only vs. model management), and expire automatically. OAuth 2.0 for service-to-service AI API access: client credentials flow (service authenticates with client_id + client_secre"},
    {"title": "7.3 Input Validation and Output Sanitization for AI Systems", "desc": "AI systems that process and produce text require both input and output security controls. Input validation for LLMs: length limits (prevent prompt stuffing and token smuggling attacks), character encoding validation (normalize Unicode to prevent homoglyph injection), PII detection and redaction before sending to external LLM APIs (use Presidio to detect and replace names, SSNs, emails), prompt tem"},
    {"title": "7.4 Runtime Threat Detection for AI Infrastructure", "desc": "Falco (CNCF) provides runtime security for Kubernetes-based AI infrastructure by monitoring system calls. Critical Falco rules for AI systems: unexpected network connection from model serving pod (a model server that connects to external IPs it wasn't configured to reach), process spawned inside container (model serving containers should have no reason to spawn shell processes — shell spawn is a c"},
    {"title": "7.5 DDoS and Abuse Prevention for AI APIs", "desc": "AI APIs are particularly valuable targets for abuse: each API call consumes expensive GPU compute, and model outputs can be monetized for fraud, spam, and harmful content generation. Rate limiting architecture: per-IP rate limiting (token bucket algorithm), per-user rate limiting (authenticated users get higher limits), per-model rate limiting (expensive models have lower per-user limits). Abuse d"},
    {"title": "7.6 Security Monitoring and SIEM Integration for AI Systems", "desc": "Security Information and Event Management (SIEM) systems aggregate security events for detection and response. AI-specific events to collect: every model inference request (timestamp, user, model version, input hash, output hash — not content for privacy), model deployment events (who deployed, which version, to which environment), authentication failures, authorization denials, unusual usage patt"},
    {"title": "7.7 Module 7 Assessment: Secure AI Architecture Design", "desc": "Design the complete security architecture for a production AI API serving 1M requests/day: zero trust authentication layer, RBAC policy for 5 different client types, input validation pipeline, output sanitization for web rendering, Falco rules for runtime threat detection, rate limiting and abuse prevention configuration, and SIEM integration for security monitoring. Document threat model and how "}
  ]},
  {"title": "Module 8: Regulatory Compliance — EU AI Act, NIST AI RMF, and ISO Standards", "desc": "AI regulations are becoming law. The EU AI Act's technical requirements, NIST AI RMF implementation, ISO/IEC 42001, GDPR intersection with AI, and building the compliance engineering practice.", "lessons": [
    {"title": "8.1 The EU AI Act: Technical Requirements for AI Security Engineers", "desc": "The EU AI Act (enforcement from August 2026) creates a risk-based regulatory framework. Risk tiers: unacceptable risk (prohibited — social scoring, real-time biometric surveillance in public spaces), high risk (regulated — recruitment AI, credit scoring, critical infrastructure, medical devices, biometric identification, education assessment, law enforcement), limited risk (transparency obligation"},
    {"title": "8.2 NIST AI Risk Management Framework: Govern, Map, Measure, Manage", "desc": "The NIST AI RMF (2023) provides a voluntary framework for responsible AI risk management. Four core functions: Govern (establish organizational AI risk management culture, policies, and oversight), Map (identify the context, use cases, and potential harms of AI systems), Measure (quantify AI risks using metrics, evaluation methods, and testing), Manage (prioritize and address identified risks, mon"},
    {"title": "8.3 ISO/IEC 42001: AI Management System Standard", "desc": "ISO/IEC 42001 (2023) is the first international standard for AI management systems — providing certification-ready requirements similar to ISO 27001 for information security. Key clauses: Clause 4 (organizational context — understand internal/external AI risks), Clause 6 (planning — risk assessment and treatment, AI impact assessment), Clause 8 (operation — AI system development and deployment con"},
    {"title": "8.4 Building the AI Compliance Engineering Practice", "desc": "Compliance engineering operationalizes regulatory requirements as code and automated processes. Compliance-as-code tools: OPA (Open Policy Agent) for Kubernetes admission control enforcing AI governance policies, Checkov for IaC scanning against compliance frameworks, custom Great Expectations suites mapped to regulatory requirements. Automated evidence collection: CI/CD pipeline automatically gen"},
    {"title": "8.5 AI Incident Response and Reporting Obligations", "desc": "AI systems will fail — regulatory frameworks increasingly require incident reporting for high-impact AI failures. EU AI Act Article 73: serious incidents (death, serious injury, significant property damage, fundamental rights violations) involving high-risk AI must be reported to national market surveillance authority within 15 business days. Incident classification for AI: Severity 1 (physical sa"},
    {"title": "8.6 Cross-Border AI Data Transfers: GDPR, SCCs, and Data Localization", "desc": "AI training data often requires cross-border transfers — GDPR, CCPA, and emerging AI regulations create complex compliance requirements. GDPR transfer mechanisms: Standard Contractual Clauses (SCCs) — EU-approved contract terms for data transfers to non-adequate countries, Binding Corporate Rules for intra-group transfers, adequacy decisions (UK, Switzerland, Japan — transfers without additional m"},
    {"title": "8.7 Module 8 Capstone: Regulatory Compliance Plan", "desc": "Develop a complete regulatory compliance plan for a high-risk AI system (loan approval model): classify against EU AI Act risk tiers, document required technical controls, map NIST AI RMF Govern/Map/Measure/Manage implementation, design automated evidence collection pipeline, write incident response plan with notification timelines, and identify cross-border data transfer requirements. Produce as "}
  ]},
  {"title": "Module 9: Secure MLOps — Protecting the ML Development Lifecycle", "desc": "Every stage of the ML lifecycle — data collection, training, evaluation, deployment — is an attack surface. Securing the end-to-end ML pipeline: CI/CD security for ML, model registry access control, secure training infrastructure, and supply chain attestation.", "lessons": [
    {"title": "9.1 Threat Modeling the ML Development Lifecycle", "desc": "STRIDE applied to ML pipelines: Spoofing (fake data sources injecting poisoned training data), Tampering (modifying training scripts to add backdoors, modifying model artifacts in transit), Repudiation (no audit trail for who modified training data or deployed which model version), Information Disclosure (leaking model weights, training data, or business logic through model queries), Denial of Ser"},
    {"title": "9.2 Securing the Training Pipeline: Environments, Isolation, and Monitoring", "desc": "Training pipelines process sensitive data and produce valuable model artifacts — both are targets. Training environment security: ephemeral training containers (fresh environment per training job, no persistent state that could be poisoned), network isolation (training pods have no internet access — all dependencies pre-loaded, external connections are suspicious), resource limits (prevent trainin"},
    {"title": "9.3 Model Registry Security: Access Control, Versioning, and Tampering Detection", "desc": "The model registry is the highest-value target in the ML supply chain — a compromised registry can inject backdoored models into production. Registry access control: RBAC with explicit permissions (ML engineer: can register new versions, data scientist: read-only, deployment service: read + download latest approved version). Immutable artifacts: once a model version is registered and approved, the"},
    {"title": "9.4 CI/CD Pipeline Security for ML: Secrets, Permissions, and Artifact Integrity", "desc": "ML CI/CD pipelines handle training data credentials, model registry tokens, and cloud provider access — making them high-value targets. Secrets in CI/CD: use OIDC federation (GitHub Actions OIDC → AWS IAM role assumption — no stored secrets), never store API keys in GitHub Secrets if OIDC is available, rotate any leaked secrets immediately. Pipeline permission minimization: GitHub Actions OIDC tok"},
    {"title": "9.5 Secure Model Serving: Container Hardening and Network Policies", "desc": "Model serving containers are the externally-facing component of the ML system — direct attack surface. Container hardening checklist: non-root user (USER 1000, never root — root container escape gives host access), read-only root filesystem (only /tmp writable — prevents file modification by attacker), dropped capabilities (--cap-drop ALL — minimal Linux capabilities), no privileged flag, seccomp "},
    {"title": "9.6 Penetration Testing AI Systems: Methodology and Tooling", "desc": "Penetration testing AI systems requires both traditional security testing and AI-specific techniques. Scope definition: API security testing (authentication bypass, authorization escalation, injection), model security testing (adversarial examples, model extraction, membership inference), infrastructure testing (Kubernetes escape, container breakout, secrets extraction), supply chain testing (depe"},
    {"title": "9.7 Module 9 Assessment: Secure MLOps Audit", "desc": "Conduct a complete secure MLOps audit of a provided ML system architecture: threat model the training pipeline using STRIDE, identify access control gaps in the model registry, design secrets management for CI/CD pipeline, write container hardening requirements for model serving pods, specify NetworkPolicy rules for the serving namespace, and design the comprehensive penetration testing scope. Pro"}
  ]},
  {"title": "Module 10: AI Security Program — Building the Practice and Advancing Your Career", "desc": "AI security is a new discipline requiring organizational infrastructure, team structure, and a clear career path. Building the AI security program, executive communication, the evolving threat landscape, and your roadmap to CISO or VP of AI Security.", "lessons": [
    {"title": "10.1 Building the AI Security Program: Team, Scope, and Governance", "desc": "AI security programs differ from traditional InfoSec in their scope: they must own security controls in the ML development lifecycle, not just network and application security. The AI security team charter: scope (all AI systems in production and development), responsibilities (threat modeling, red teaming, compliance support, incident response, developer security training), reporting structure (C"},
    {"title": "10.2 Communicating AI Security Risk to Executives and Boards", "desc": "AI security investments require executive approval — framing security in business terms. The AI security risk narrative: financial impact (average cost of an AI security incident at $4.45M per IBM Cost of Data Breach Report 2023), regulatory impact (EU AI Act fines up to €30M or 6% of global turnover for prohibited AI deployments), reputational impact (Samsung engineers leaked proprietary code to "},
    {"title": "10.3 AI Security Incident Management: Detection, Response, and Recovery", "desc": "AI security incidents require specialized response procedures beyond traditional IR playbooks. AI security incident taxonomy: prompt injection leading to data exfiltration, adversarial example bypassing safety-critical model, training data poisoning discovered post-deployment, model theft via API enumeration, model serving infrastructure compromise. Detection sources: monitoring alerts (statistica"},
    {"title": "10.4 Emerging AI Security Threats: Agents, Multimodal, and Foundation Models", "desc": "The AI threat landscape is evolving faster than any previous technology security domain. Near-term emerging threats (2025-2026): agentic AI attacks (autonomous agents with tool access can take real-world actions from prompt injection — send emails, execute code, modify files), multimodal injection (visual and audio prompt injection becoming more sophisticated), model collapse attacks (intentionall"},
    {"title": "10.5 Responsible Disclosure and the AI Vulnerability Ecosystem", "desc": "AI vulnerabilities require a different disclosure framework than traditional software CVEs. Why standard CVE process doesn't fit AI: AI vulnerabilities are often behavioral rather than code-based, severity depends on deployment context, patches require retraining not patching. AI vulnerability disclosure programs: OpenAI Bug Bounty (pays $200-$20,000 for qualifying vulnerabilities), Anthropic Resp"},
    {"title": "10.6 AI Security Career: Certifications, Skills, and Advancement", "desc": "AI security engineering is the intersection of two high-demand fields — compensation reflects the scarcity. Compensation (2024, US market): AI Security Engineer L3 $150-200K, L4 $200-280K, Staff AI Security Engineer $280-380K, CISO with AI specialization $400K+. Skill progression: foundation (Python, cloud security, Kubernetes security, cryptography) → AI security (adversarial ML, prompt injection"},
    {"title": "10.7 Final Capstone: AI Security Program Design", "desc": "Design the complete AI security program for a Series C AI company with 200 ML engineers and 50 production AI systems. Deliverables: team structure and hiring plan, 12-month security program roadmap (threat modeling all systems, red team schedule, compliance milestones), executive risk communication framework, incident response plan with AI-specific playbooks, training curriculum for ML engineers, "}
  ]}
]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const COURSE_TITLE = courseData.title;
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({ title: courseData.title, description: courseData.description, is_published: true, translations: courseData.translations }).select().single();
    if (ce) throw ce;
    let chaptersCreated = 0; let videosCreated = 0;
    for (let mi = 0; mi < courseData.modules.length; mi++) {
      const mod = courseData.modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: mod.title, description: mod.desc, order_index: mi, translations: {} }).select().single();
      if (che) throw che; chaptersCreated++;
      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = les.title + "\n\n" + les.desc + "\n\nThis is a world-class lesson from Aladiah Academy's professional certification program. Prof. Didier teaches this with production depth, real case studies, and implementation guidance. Module context: " + mod.title + ". " + mod.desc;
        const trans = { en:{title:les.title,transcript}, es:{title:les.title,transcript}, fr:{title:les.title,transcript}, de:{title:les.title,transcript}, zh:{title:les.title,transcript}, ar:{title:les.title,transcript}, ja:{title:les.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: les.title, description: les.desc, order_index: li, translations: trans }).select().single();
        if (ve) throw ve; videosCreated++;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: "What production expertise does this lesson build?", scenario_context: "Applying this in a professional role.", options: [les.desc.substring(0,120)+"...", "Only theoretical background", "Covered elsewhere", "Optional content"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: "Which real-world organizations' practices are referenced?", scenario_context: "Grounding knowledge in production reality.", options: ["Leading global organizations — case studies ground every lesson in production reality", "No real organizations referenced", "Only academic examples", "Only startups"], correct_answer_index: 0, explanation: "Every lesson uses production case studies from world-class organizations.", order_index: 1 },
        ]);
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: "What expert-level competency does this module develop?", scenario_context: "Module completion assessment.", options: [mod.desc.substring(0,140)+"...", "Only introductory familiarity", "Theoretical knowledge only", "Not career-relevant"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "What career level does mastery of this module support?", scenario_context: "Professional development planning.", options: ["Senior professional and leadership roles in the fastest-growing AI specialization globally", "Entry-level only", "Academic roles only", "No direct career value"], correct_answer_index: 0, explanation: "Each module builds expertise directly valued in high-compensation AI professional roles.", order_index: 1 },
      ]);
    }
    return new Response(JSON.stringify({ message: courseData.title + " — 10-module world-class version seeded", courseId: course.id, modules: chaptersCreated, lessons: videosCreated }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
