import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { requireAdmin } from "../_shared/adminGuard.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const courseData = {
  title: "AI Cloud Engineer",
  description: "Master building, deploying, and scaling AI workloads on AWS, Azure, and GCP. From IaC and Kubernetes to serverless AI patterns and MLOps pipelines — become the engineer enterprises hire to run AI at production scale.",
  chapters: [
    {
      title: "Module 1: Cloud Foundations for AI Engineers",
      description: "Understand the cloud landscape, core infrastructure primitives, and why cloud is the default platform for modern AI workloads.",
      order_index: 0,
      videos: [
        {
          title: "1.1 Why Cloud is the Backbone of Modern AI",
          description: "Explore why virtually every serious AI deployment runs on cloud infrastructure and what that means for your career.",
          order_index: 0,
          lessonScript: {
            mainPoints: [
              "Cloud computing became the default platform for AI because it solves three fundamental problems: elastic compute, on-demand GPU access, and global distribution — none of which traditional on-premise data centers provide cost-effectively. Training a large model from scratch can cost millions in compute; the cloud lets you access that power on-demand, use it for hours, then release it — transforming capital expenditure into operational expenditure.",
              "The major cloud providers collectively host over 90% of enterprise AI workloads. AWS leads with SageMaker, Bedrock, and EC2 GPU instances. Azure dominates enterprise AI through its exclusive OpenAI partnership and Azure AI Services. Google Cloud brings unique advantages through TPUs, Vertex AI, and first-party model access. Understanding when to use each — and how to design multi-cloud architectures — is a core AI Cloud Engineer skill.",
              "The AI Cloud Engineer role sits at the intersection of infrastructure engineering, ML operations, and cloud architecture. You are the person who makes the difference between a data scientist's notebook experiment and a production system serving millions of users reliably. Mastering this role means understanding compute, storage, networking, containers, orchestration, security, and cost optimization simultaneously.",
              "GPU instances are the workhorses of AI. NVIDIA A100 and H100 instances power both training and inference at scale. Understanding GPU memory requirements — a 70B parameter LLaMA model needs approximately 140GB of GPU memory in float16 — determines which instances and how many you need. AWS p4de.24xlarge, Google A3 (H100), and Azure NDv4 are the flagship GPU instance families you will use regularly.",
              "By the end of this course you will design multi-cloud AI architectures, automate infrastructure with Terraform, orchestrate AI workloads with Kubernetes, build serverless AI pipelines, implement full MLOps lifecycles including experiment tracking and CI/CD, and secure AI systems against real-world threats including prompt injection and data poisoning."
            ]
          },
          questions: [
            { question_text: "Why do enterprise AI workloads predominantly run on cloud infrastructure?", scenario_context: "A CTO asks you to justify a cloud-first AI strategy to the board.", options: ["Because it's cheaper than on-premise for all workloads", "Because it provides elastic compute, on-demand GPU access, and global distribution cost-effectively", "Because regulators require cloud for AI", "Because on-premise servers cannot run neural networks"], correct_answer_index: 1, explanation: "Cloud solves the three core AI infrastructure problems: elastic compute to scale up/down for bursty training, on-demand GPU access without millions in capital investment, and global distribution for low-latency serving." },
            { question_text: "Which cloud provider has the strongest enterprise AI position due to its OpenAI partnership?", scenario_context: "You're evaluating cloud providers for deploying GPT-4 in an enterprise application.", options: ["AWS via Amazon Bedrock", "Google Cloud via Vertex AI", "Microsoft Azure via Azure OpenAI Service", "Oracle Cloud via OCI AI"], correct_answer_index: 2, explanation: "Microsoft Azure holds an exclusive partnership with OpenAI, giving Azure customers production access to GPT-4, DALL-E, and Whisper through Azure OpenAI Service with enterprise SLAs, compliance certifications, and private network deployment options." },
            { question_text: "An H100 GPU instance costs $32/hour on-demand. A training job requires 100 hours. What financial model makes cloud viable versus buying an H100 server outright (~$200,000)?", scenario_context: "You're building the financial case for cloud AI compute.", options: ["Cloud is always cheaper than owning hardware", "Cloud converts capital expenditure to operational expenditure — pay only when training runs rather than owning idle hardware", "Cloud GPUs perform better than purchased hardware", "Cloud provides tax advantages that hardware does not"], correct_answer_index: 1, explanation: "Cloud transforms a $200K capital purchase (which sits idle 80% of the time) into $3,200 for 100 training hours. This is the fundamental economics of cloud AI — matching cost to actual utilization." },
            { question_text: "What uniquely distinguishes the AI Cloud Engineer from a data scientist on an ML team?", scenario_context: "Your team is writing a job description for an AI Cloud Engineer hire.", options: ["AI Cloud Engineers design neural network architectures", "AI Cloud Engineers take ML experiments from notebooks to reliable, scalable production systems", "AI Cloud Engineers clean and label training datasets", "AI Cloud Engineers write Python ML training code"], correct_answer_index: 1, explanation: "The AI Cloud Engineer bridges data science experiments and production systems — handling the infrastructure, reliability, scalability, monitoring, and operations that transform a working notebook into a system serving millions of users." },
            { question_text: "What is Google Cloud's unique hardware advantage for LLM training at scale?", scenario_context: "You're selecting cloud infrastructure for training a 175B parameter model.", options: ["The fastest NVIDIA GPU clusters in any cloud", "Tensor Processing Units (TPUs) — custom ASICs optimized for matrix operations that dominate neural network training", "Quantum computing resources for AI", "Custom ARM processors with built-in AI accelerators"], correct_answer_index: 1, explanation: "Google's TPUs (Tensor Processing Units) are custom ASICs designed specifically for the matrix multiply operations that dominate deep learning. TPU v4 pods provide petaflops of compute for LLM training at cost-efficiency that GPU clusters struggle to match." }
          ]
        },
        {
          title: "1.2 Core Cloud Services: Compute, Storage, and Networking for AI",
          description: "Deep dive into the foundational cloud services that underpin every AI system — and how to use them correctly.",
          order_index: 1,
          lessonScript: {
            mainPoints: [
              "Compute hierarchy for AI: Virtual machines (EC2/Compute Engine/Azure VMs) for full control and GPU access. Container services (ECS/GKE/AKS) for portable, orchestrated workloads. Serverless functions (Lambda/Cloud Functions) for event-driven AI tasks. For AI specifically, instance families matter enormously — p4de (A100), p5 (H100), g5 (A10G) on AWS; A3 (H100), A2 (A100), T4 nodes on GCP; NDv4 (A100), NCasT4 on Azure. Know these families and their GPU memory capacities by heart.",
              "Storage architecture is often the bottleneck in AI systems. Object storage (S3/Cloud Storage/Azure Blob) holds training data and model artifacts — it is infinitely scalable, 99.999999999% durable, and the foundation of every AI data lake. Block storage (EBS/Persistent Disk) attaches to compute instances for fast I/O during training. High-performance parallel filesystems (FSx for Lustre on AWS, GCS FUSE) are critical for distributed training — they provide the throughput to feed hundreds of GPUs without I/O bottlenecks.",
              "Networking for AI engineers: Virtual Private Clouds isolate your AI workloads. Subnets segment networks into public (internet-accessible load balancers) and private (training clusters, inference services). Security Groups are stateful firewalls at the instance level. Network ACLs are stateless firewalls at the subnet level. For distributed training, NVIDIA Collective Communication Library (NCCL) relies on high-bandwidth, low-latency interconnects — AWS Elastic Fabric Adapter and GCP's high-bandwidth networking provide the sub-microsecond latency required for efficient all-reduce operations.",
              "IAM is the security backbone. Roles define what cloud services can do. Policies attach permissions to roles. Service accounts allow AI services to call other cloud services. The most critical IAM principle is least privilege — training jobs should only read from specific S3 buckets, inference services should only call specific model endpoints. Never hardcode AWS access keys in code; use instance metadata service credentials (automatically rotated, no keys needed) or Kubernetes Workload Identity for container workloads.",
              "Managed AI/ML services layer on top of core infrastructure. SageMaker, Vertex AI, and Azure ML provide end-to-end ML platforms handling distributed training, hyperparameter optimization, deployment, and monitoring. The decision of when to use managed services versus raw infrastructure is architectural and cost-driven — managed services reduce operational overhead but add cost; raw infrastructure requires engineering expertise but enables maximum optimization."
            ]
          },
          questions: [
            { question_text: "For a distributed AI training job with 256 GPUs, what storage technology is required to feed GPUs without I/O bottlenecks?", scenario_context: "Your training job's GPU utilization is only 40% due to data loading bottlenecks.", options: ["Standard Amazon S3 with concurrent reads", "High-performance parallel filesystem like FSx for Lustre or GCS FUSE with local SSD caching", "Amazon EBS gp2 volumes attached to each node", "NFS shared storage from a central file server"], correct_answer_index: 1, explanation: "256 GPUs processing ImageNet-scale data require massive I/O throughput. FSx for Lustre provides hundreds of GB/s of throughput with sub-millisecond latency, integrating with S3 for data loading. Standard S3 throttles at ~5,500 GET requests/second per prefix — insufficient for large GPU clusters." },
            { question_text: "Why is AWS Elastic Fabric Adapter (EFA) critical for distributed model training?", scenario_context: "You're provisioning a 64-node GPU training cluster for a large language model.", options: ["EFA provides internet access to GPU instances", "EFA provides high-bandwidth, low-latency networking enabling efficient all-reduce operations between GPU nodes", "EFA reduces the cost of GPU instances", "EFA is required to use NVIDIA GPUs on AWS"], correct_answer_index: 1, explanation: "Distributed training uses NCCL all-reduce operations to synchronize gradients across GPUs. These operations require extremely low latency and high bandwidth between nodes. EFA provides sub-microsecond MPI latency — 4-10x better than standard TCP networking — directly translating to faster training." },
            { question_text: "A training job needs to read from S3. What is the most secure way to provide credentials?", scenario_context: "Your security audit found AWS access keys hardcoded in training Docker images.", options: ["Store access keys in environment variables", "Use IAM Instance Profiles — the EC2 instance automatically receives temporary, rotating credentials from the metadata service", "Pass credentials as command-line arguments", "Store credentials in a config file on the instance"], correct_answer_index: 1, explanation: "IAM Instance Profiles attach an IAM role to the EC2 instance. The instance metadata service automatically provides temporary credentials that rotate every few hours — no keys to manage, rotate, or accidentally expose. This is the AWS security standard." },
            { question_text: "What is the difference between a Security Group and a Network ACL in AWS VPC?", scenario_context: "You're designing network security for an ML inference cluster.", options: ["They are identical and interchangeable", "Security Groups are stateful instance-level firewalls; Network ACLs are stateless subnet-level firewalls", "Security Groups are for outbound traffic; Network ACLs for inbound", "Security Groups cost more than Network ACLs"], correct_answer_index: 1, explanation: "Security Groups are stateful (allowed inbound connections automatically allow return traffic) and operate at the instance/ENI level. Network ACLs are stateless (must explicitly allow both inbound and outbound) and operate at the subnet level, providing a second defense layer." },
            { question_text: "What storage service backs an AI data lake for training data at enterprise scale?", scenario_context: "You're architecting data storage for a petabyte-scale ML training dataset.", options: ["Amazon RDS for structured training data", "Object storage (Amazon S3, Google Cloud Storage, Azure Blob) — infinitely scalable, highly durable, low cost", "Amazon EBS with RAID configuration", "A managed NFS filesystem for all training data"], correct_answer_index: 1, explanation: "Object storage is the universal standard for AI training data lakes. S3 stores 11 9's of durability, costs $0.023/GB/month (vs $0.10+/GB for block storage), scales to exabytes, and integrates directly with every ML training framework and managed ML service." }
          ]
        },
        {
          title: "1.3 Infrastructure as Code with Terraform",
          description: "Automate cloud AI infrastructure provisioning with Terraform — the industry standard for reproducible, version-controlled infrastructure.",
          order_index: 2,
          lessonScript: {
            mainPoints: [
              "Infrastructure as Code means your entire AI platform — VPCs, subnets, security groups, GPU instance groups, S3 buckets, IAM roles, container registries, and managed ML services — is defined in version-controlled code. Changes go through pull request review before touching infrastructure. Drift between environments is eliminated. An entire production ML platform that took three weeks to manually configure can be reproduced in 15 minutes by running terraform apply.",
              "Terraform uses HCL (HashiCorp Configuration Language) to declare the desired state of infrastructure. Key concepts: providers (cloud-specific plugins for AWS, GCP, Azure), resources (actual cloud resources like aws_instance or google_container_cluster), data sources (read existing infrastructure you don't manage), variables (parameterize configurations), outputs (expose values for use by other modules), and modules (reusable infrastructure components). A well-structured Terraform codebase uses modules for ML platform components that teams can reuse.",
              "The Terraform workflow: `terraform init` downloads providers and initializes the backend. `terraform plan` generates an execution plan showing exactly what will change — this is your diff before touching production. `terraform apply` executes the plan. `terraform destroy` tears down all resources. In CI/CD pipelines, `terraform plan` output is posted as a PR comment for review, and `terraform apply` runs automatically after approval.",
              "Remote state is essential for teams. The state file tracks what Terraform has created — it's the source of truth that maps Terraform code to real cloud resources. Local state breaks in team environments (conflicts when two engineers run apply simultaneously). Remote state on S3 (with DynamoDB for locking) or Terraform Cloud ensures only one apply runs at a time and the state is durable. State files may contain sensitive values and must never be committed to git.",
              "A complete ML platform Terraform module typically provisions: VPC with public and private subnets, NAT gateway for private subnet internet access, S3 buckets for training data and model artifacts (with versioning and encryption), IAM roles for training jobs and inference services, ECR repositories for Docker images, EKS cluster with GPU and CPU node groups, and SageMaker domain — all reproducible with a single command."
            ]
          },
          questions: [
            { question_text: "What is the primary value of defining AI infrastructure with Terraform rather than clicking through the AWS console?", scenario_context: "Your team needs to provision identical ML platforms in US-East-1 and EU-West-1.", options: ["Terraform is required by AWS for GPU instances", "Terraform creates version-controlled, reproducible infrastructure — deploy identical environments reliably", "Terraform automatically optimizes costs", "Terraform runs faster than the AWS console"], correct_answer_index: 1, explanation: "Terraform code can deploy identical infrastructure to multiple regions with a variable change. Without IaC, each environment has configuration drift within weeks. With Terraform, dev/staging/production are genuinely identical except for parameterized differences like instance size." },
            { question_text: "What critical action does `terraform plan` perform before `terraform apply`?", scenario_context: "Your team requires peer review of all production infrastructure changes.", options: ["It applies changes to a test environment first", "It generates a diff showing exactly what will be created, modified, or destroyed — enabling review before any change", "It tests network connectivity", "It estimates monthly cloud costs"], correct_answer_index: 1, explanation: "terraform plan shows a detailed execution plan: + for additions, ~ for modifications, - for deletions. In CI/CD pipelines, this plan is posted as a PR comment allowing engineers to review infrastructure changes exactly as they review code changes." },
            { question_text: "Why must Terraform state be stored remotely with locking in a team environment?", scenario_context: "Two engineers both run terraform apply simultaneously and the state file becomes corrupted.", options: ["Remote state is required by AWS compliance", "Remote state with locking (S3+DynamoDB) prevents concurrent modifications that corrupt state and ensures single source of truth", "Remote state makes Terraform run faster", "Remote state provides automatic backups only"], correct_answer_index: 1, explanation: "Terraform state tracks the mapping between code and real resources. Without locking, concurrent applies corrupt the state file and cause Terraform to lose track of what it manages. S3+DynamoDB provides atomic locking — only one apply runs at a time." },
            { question_text: "What is a Terraform module and why are they essential for ML platform infrastructure?", scenario_context: "Five ML teams at your company all need identical Kubernetes clusters with GPU node pools.", options: ["Modules are Terraform's programming language", "Modules are reusable infrastructure components teams can instantiate with different parameters", "Modules are required for all Terraform configurations", "Modules are only for Terraform Enterprise users"], correct_answer_index: 1, explanation: "A Terraform module encapsulates a set of resources as a reusable component. An 'ml-platform' module might include VPC, EKS cluster, S3 buckets, and IAM roles. Each team instantiates it with different parameters (instance size, replica count) without duplicating the underlying infrastructure code." },
            { question_text: "Why should Terraform state files never be committed to git?", scenario_context: "A junior engineer has added terraform.tfstate to the repository.", options: ["State files are too large for git", "State files contain sensitive data (passwords, private keys, API tokens) and expose the full infrastructure layout", "Terraform doesn't support git", "State files change too frequently for version control"], correct_answer_index: 1, explanation: "Terraform state often contains sensitive values like database passwords, API keys, and private certificates in plaintext. Committing state to git exposes this data to everyone with repository access and in git history permanently." }
          ]
        },
        {
          title: "1.4 Docker and Container Registries for AI Systems",
          description: "Package AI models and applications as portable, reproducible containers and manage them through enterprise container registries.",
          order_index: 3,
          lessonScript: {
            mainPoints: [
              "Docker solved 'it works on my machine' — the most costly problem in AI deployment. A model that works in development fails in production because of dependency version mismatches, different CUDA versions, missing system libraries, or different Python environments. Docker packages everything — code, dependencies, CUDA libraries, system packages, and runtime configuration — into a portable image that runs identically everywhere: local laptop, CI/CD runner, Kubernetes cluster, or SageMaker endpoint.",
              "Production AI Dockerfiles follow strict best practices. Start from official NVIDIA CUDA base images (nvidia/cuda:11.8.0-runtime-ubuntu22.04) for GPU support. Use multi-stage builds to separate the build environment from the runtime image — dramatically reducing final image size. Copy requirements.txt and install dependencies before copying application code, leveraging Docker's layer caching so a code change doesn't re-install all Python packages. Pin exact dependency versions. Run as a non-root user. Use .dockerignore to exclude training data, notebooks, and test files.",
              "Container registries are the distribution layer for AI Docker images. AWS ECR (Elastic Container Registry), Google Artifact Registry, and Azure Container Registry provide enterprise-grade storage with IAM integration, vulnerability scanning, image signing, and geo-replication. ECR lifecycle policies automatically delete old image versions — preventing storage cost accumulation. Your CI/CD pipeline builds, tests, scans for vulnerabilities, and pushes new images on every merge to main.",
              "Volumes and bind mounts are critical patterns for AI containers. Model weights of 10-40GB should never be baked into Docker images — they make images enormous and slow to pull. Instead, store weights in S3/GCS and mount them at container startup via EFS, GCS FUSE, or a custom init container pattern. For local development, bind mounts reflect code changes instantly without rebuilding, while volumes provide persistent storage for databases and caches.",
              "Docker Compose orchestrates multi-container AI development environments. A typical ML service locally runs: a FastAPI inference server, Redis for feature caching, PostgreSQL for prediction logging, and a Prometheus/Grafana stack for monitoring — all defined in docker-compose.yml and started with one command. This local environment is a faithful replica of production, dramatically reducing integration bugs discovered only after deployment."
            ]
          },
          questions: [
            { question_text: "A PyTorch model works on a data scientist's Mac but fails on an AWS Linux GPU instance with 'CUDA version mismatch'. What Docker practice prevents this?", scenario_context: "You're diagnosing a production deployment failure.", options: ["Testing on more machines before deployment", "Using an NVIDIA CUDA base image that specifies the exact CUDA version, ensuring identical GPU runtime everywhere", "Installing the latest CUDA on the production server", "Running models in CPU mode only"], correct_answer_index: 1, explanation: "Starting FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04 ensures the exact CUDA version is baked into the container. The model runs on identical CUDA regardless of what's installed on the host — eliminating environment-specific failures." },
            { question_text: "Your AI inference Docker image is 18GB, causing 12-minute pull times at deployment. What reduces image size most dramatically?", scenario_context: "Kubernetes rolling deployments are slow because pulling the new image takes 12 minutes.", options: ["Deleting log files before building", "Multi-stage builds: compile/install in a build stage, copy only runtime artifacts to a minimal final stage", "Using alpine Linux base image", "Removing the model weights from the image"], correct_answer_index: 1, explanation: "Multi-stage builds separate the heavy build environment (gcc, build-essential, full Python build tools) from the runtime. A PyTorch training image of 18GB might produce a 2GB runtime image — 9x reduction — dramatically improving deployment speed." },
            { question_text: "Why should large ML model weights (10-40GB) never be baked directly into Docker images?", scenario_context: "You're designing the model deployment architecture for a 40GB LLM.", options: ["Docker images can't contain files larger than 1GB", "Baking weights makes images enormous (slow to pull and store), tightly couples model versions to image versions, and wastes registry storage", "Model weights can't run inside containers", "NVIDIA requires weights to be stored separately"], correct_answer_index: 1, explanation: "A 40GB Docker image takes 15-30 minutes to pull on every new node startup. Instead, store weights in S3/GCS and mount them via EFS/GCS FUSE or download with an init container — the image stays small and weights are shared across container versions." },
            { question_text: "What ECR lifecycle policy should be configured to prevent registry storage cost accumulation?", scenario_context: "Your ECR registry bill is $800/month from 5 years of accumulated Docker images.", options: ["Manually delete old images quarterly", "Lifecycle policies that automatically expire untagged images and keep only the last N tagged releases", "Use S3 instead of ECR", "Compress all images before storing"], correct_answer_index: 1, explanation: "ECR lifecycle policies run automatically: expire untagged images after 7 days, keep only the last 10 tagged releases per repository. A rule like {tagStatus: untagged, countType: sinceImagePushed, countNumber: 7} eliminates image accumulation without manual cleanup." },
            { question_text: "How does Docker layer caching accelerate CI/CD pipelines for AI Docker images?", scenario_context: "Your CI/CD pipeline rebuilds your ML service Docker image from scratch in 8 minutes on every commit.", options: ["Docker caching requires special CI/CD configuration", "Copying requirements.txt and installing dependencies before application code allows Docker to cache the dependency layer — rebuilding only changed layers on code changes", "Docker caching only works for the base image layer", "Docker caching is not available in CI/CD environments"], correct_answer_index: 1, explanation: "Docker builds layer by layer and caches unchanged layers. By installing dependencies (rarely changed) before copying application code (frequently changed), only the code layer rebuilds on code commits — reducing an 8-minute image build to 30 seconds for most code changes." }
          ]
        },
        {
          title: "1.5 Kubernetes for AI Workload Orchestration",
          description: "Master Kubernetes — the operating system of the cloud — to orchestrate AI training, inference, and data processing at enterprise scale.",
          order_index: 4,
          lessonScript: {
            mainPoints: [
              "Kubernetes is the industry standard for orchestrating containerized AI workloads at scale. It solves three critical problems: high availability (automatically restarting failed containers and rescheduling them on healthy nodes), horizontal scaling (adding inference Pods when traffic spikes, removing them when it drops), and declarative infrastructure (you define desired state in YAML, Kubernetes continuously reconciles reality to match). For AI teams, managed Kubernetes — Amazon EKS, Google GKE, Azure AKS — is almost always the right choice.",
              "The Kubernetes control plane includes the API server (all cluster operations go through this REST API), etcd (distributed key-value store holding all cluster state), scheduler (assigns Pods to nodes based on resource requirements and constraints), and controller manager (runs reconciliation loops ensuring actual state matches desired state). Worker nodes run the kubelet (Pod management agent), kube-proxy (network routing), and the container runtime. Understanding this architecture helps diagnose issues and make architectural decisions.",
              "For AI workloads, the critical Kubernetes resource types are: Deployments (stateless inference services with rolling updates), StatefulSets (distributed training jobs that need stable network identity), Jobs (batch inference, one-time model evaluation), CronJobs (scheduled batch inference), HorizontalPodAutoscaler (scales Pods on CPU, memory, or custom metrics like queue depth), VerticalPodAutoscaler (right-sizes Pod resource requests), PersistentVolumeClaims (model weight storage), and ConfigMaps/Secrets (configuration injection).",
              "GPU scheduling requires the NVIDIA device plugin daemonset. Once installed, GPUs appear as a resource type (nvidia.com/gpu) in node capacity. Request GPUs in your Pod spec with resources.limits['nvidia.com/gpu']: 1. Kubernetes guarantees that Pod is scheduled on a GPU node and gets exclusive access to that GPU. Node selectors and node affinity rules direct workloads to specific GPU types — ensuring H100 training jobs land on H100 nodes and A10G inference jobs land on cheaper A10G nodes.",
              "Cost optimization is where Kubernetes expertise pays off. Configure GPU node pools with min=0, max=10 and cluster autoscaler — nodes provision on demand when training jobs arrive and terminate after 10 minutes of idleness. This pattern reduces GPU costs by 70%+ for teams running experiments rather than continuous training. Combine with spot/preemptible node pools for training (90% discount) and on-demand for inference (reliability matters). Node affinity ensures training jobs prefer spot nodes and inference prefers on-demand."
            ]
          },
          questions: [
            { question_text: "What Kubernetes resource is best for a stateless LLM inference service that needs to scale based on HTTP request queue depth?", scenario_context: "You're deploying a production inference API that receives variable traffic throughout the day.", options: ["StatefulSet with manual scaling", "Deployment + HorizontalPodAutoscaler with custom metric on request queue depth", "DaemonSet running on every node", "Job that restarts hourly"], correct_answer_index: 1, explanation: "Deployments manage stateless replicated Pods with zero-downtime rolling updates. HPA scales replica count based on metrics including custom metrics (via Prometheus + KEDA). Queue depth from SQS or Kafka is an excellent autoscaling trigger for inference workloads." },
            { question_text: "A distributed PyTorch training job on Kubernetes requires stable network identity for gradient synchronization between worker Pods. Which resource type should be used?", scenario_context: "You're migrating a multi-node training job to Kubernetes.", options: ["Deployment — it handles Pod identity automatically", "StatefulSet — provides stable Pod names (worker-0, worker-1) and network identity required for NCCL distributed training", "Job with multiple completions", "DaemonSet running on GPU nodes"], correct_answer_index: 1, explanation: "Distributed training requires each worker to have a stable, predictable hostname for NCCL group initialization (master_addr=worker-0, worker addresses worker-0.training-service). StatefulSets provide this stable identity; Deployments assign random Pod names." },
            { question_text: "How do you request GPU resources for a training Pod in Kubernetes?", scenario_context: "Your training Pod is scheduled but not using the GPU — it defaults to CPU.", options: ["Set an environment variable GPU_ENABLED=true", "Add resources.limits: 'nvidia.com/gpu': 1 to the container spec after installing the NVIDIA device plugin", "Use a special GPU-enabled container image", "Configure GPU access in the namespace settings"], correct_answer_index: 1, explanation: "After installing the NVIDIA device plugin DaemonSet, GPUs appear as schedulable resources. Requesting resources.limits: {'nvidia.com/gpu': 1} causes Kubernetes to schedule the Pod only on GPU nodes and grants exclusive access to one GPU." },
            { question_text: "What cluster autoscaler configuration minimizes GPU costs for a team running experimental training jobs intermittently?", scenario_context: "Your team's GPU Kubernetes nodes cost $15,000/month sitting idle 70% of the time.", options: ["Set minimum node count to 5 for fast startup", "Configure GPU node pool with min=0, max=10 and cluster autoscaler — nodes provision on demand and terminate after idle timeout", "Use reserved GPU instances for consistent availability", "Run GPU workloads on shared CPU nodes instead"], correct_answer_index: 1, explanation: "min=0 means no GPU nodes run when there are no jobs — zero GPU cost during idle time. Cluster autoscaler provisions nodes in 2-3 minutes when a job arrives and terminates them 10 minutes after idle. For experimental teams, this pattern reduces GPU costs from $15K to $4-5K/month." },
            { question_text: "What is the purpose of PodDisruptionBudgets (PDB) for production AI inference services?", scenario_context: "During cluster maintenance, all your inference Pods are terminated simultaneously causing a service outage.", options: ["PDBs limit the number of Pods a Deployment can run", "PDBs ensure a minimum number of Pods remain available during voluntary disruptions like node drains", "PDBs restrict which namespaces Pods can run in", "PDBs control GPU allocation per namespace"], correct_answer_index: 1, explanation: "PodDisruptionBudgets specify that at least N Pods (or at most N Pods) can be unavailable during voluntary disruptions. For an inference service with 10 replicas, a PDB of minAvailable: 8 ensures node drain operations never take more than 2 Pods offline simultaneously — maintaining service availability." }
          ]
        }
      ],
      endQuizQuestions: [
        { question_text: "Your AI company needs to train a 70B parameter LLM requiring 16 A100 GPUs for 2 weeks. Compared to purchasing 16 A100 servers ($320,000 capital), what is the total cost and key advantage of cloud GPU instances at $12/hour/GPU?", scenario_context: "CFO is evaluating cloud vs on-premise for the training run.", options: ["Cloud is always cheaper long-term", "Cloud cost: ~$32,000 for 2 weeks — 10x cheaper for a one-time run, with no hardware maintenance, depreciation, or idle cost afterward", "Cloud provides better GPUs than purchasable hardware", "Cloud cost cannot be predicted accurately"], correct_answer_index: 1, explanation: "16 GPUs × $12/hr × 24hrs × 14 days ≈ $64,512 on-demand (or ~$32K with spot instances). This is 10-20x cheaper than purchasing for a one-time run, and the compute is released afterward with no ongoing cost." },
        { question_text: "A Terraform state file was accidentally committed to the public GitHub repository. What immediate actions are required?", scenario_context: "You discovered the state file in the public repository's git history.", options: ["Delete the repository and start over", "Rotate all credentials exposed in state, enable remote state with encryption, remove file from git history using git-filter-repo, audit access logs", "Simply delete the state file from the repository", "Make the repository private and hope nobody found it"], correct_answer_index: 1, explanation: "State files contain sensitive values. Required actions: immediately rotate all exposed credentials (DB passwords, API keys), remove the file from git history (git-filter-repo, not just delete), enable S3 remote state with encryption, audit CloudTrail for unauthorized access." },
        { question_text: "You need to deploy 3 inference replicas of a 40GB LLM. Each Pod pull takes 25 minutes due to image size. How do you bring pull time to under 2 minutes?", scenario_context: "Kubernetes rolling deployments take 25+ minutes because of the massive image.", options: ["Buy faster network connections", "Separate model weights from the image: keep the Docker image small (<2GB), mount weights from pre-populated EFS/PVC at startup", "Use image pre-pulling DaemonSets on all nodes", "Reduce the number of replicas"], correct_answer_index: 1, explanation: "The solution: Docker image contains only code and dependencies (~2GB, pulls in 30s). An init container downloads model weights from S3 to a PVC (~40GB takes 2-3 min). Main container mounts the PVC. Total startup: ~2-3 minutes versus 25 minutes for the monolithic image." },
        { question_text: "Your GPU training cluster has 40% GPU utilization because data loading is the bottleneck. What storage solution resolves this?", scenario_context: "nvidia-smi shows 40% GPU utilization on a 128-GPU training cluster.", options: ["Use faster GPUs", "Replace S3 direct reads with FSx for Lustre backed by S3 — provides parallel, high-throughput data access to match GPU throughput", "Reduce the batch size", "Add more GPU nodes to compensate"], correct_answer_index: 1, explanation: "40% GPU utilization means 60% of time is spent waiting for data. FSx for Lustre provides 200GB/s+ aggregate throughput with sub-millisecond latency, feeding data fast enough to fully saturate 128 GPUs. It integrates with S3 as a warm cache layer." },
        { question_text: "A Kubernetes training Job fails on a spot instance interruption after 6 hours. The next run starts from scratch, wasting 6 hours of GPU time. What architectural change fixes this?", scenario_context: "Your nightly training Job wastes 60% of its compute budget on spot interruptions.", options: ["Switch to on-demand instances only", "Implement checkpointing every 30 minutes with automatic resume from last checkpoint — maximum 30 minutes lost per interruption", "Use dedicated GPU instances that cannot be interrupted", "Run on multiple spot instances simultaneously for redundancy"], correct_answer_index: 1, explanation: "Model checkpointing saves optimizer state, model weights, and training progress to S3 every N steps. When a spot interruption occurs, the next Job starts from the last checkpoint — losing at most N steps of progress. Combined with spot discounts, this is the standard pattern for cost-efficient training." }
      ]
    },
    {
      title: "Module 2: MLOps — Operationalizing AI at Scale",
      description: "Build the full MLOps lifecycle: experiment tracking, CI/CD for ML, feature stores, model monitoring, and automated retraining pipelines.",
      order_index: 1,
      videos: [
        {
          title: "2.1 MLflow: Experiment Tracking and Model Registry at Scale",
          description: "Implement systematic experiment tracking and model lifecycle management with MLflow.",
          order_index: 0,
          lessonScript: {
            mainPoints: [
              "Without experiment tracking, ML development is chaos. Over 6 months a team might run 500 experiments — varying learning rates, architectures, data augmentations, and regularization. Without systematic tracking, the best configuration is lost, results are not reproducible, and teams duplicate experiments from 3 months ago. MLflow Tracking solves this by logging every experiment's parameters, metrics, artifacts, and environment information with a persistent record accessible to the entire team.",
              "MLflow is organized around four integrated components. Tracking logs and queries experiments via a REST API and visual UI. Models defines a standard format for packaging ML models with their dependencies, enabling deployment to any target (REST endpoint, batch job, Spark UDF). Model Registry provides centralized versioning with lifecycle stages (Staging → Production → Archived) and transition workflows. Projects packages ML code in a reproducible format specifying dependencies and entry points.",
              "MLflow autologging is one of the highest-ROI features in the entire ML toolchain. A single line — mlflow.sklearn.autolog() or mlflow.pytorch.autolog() — before your training code automatically captures all hyperparameters, training metrics per epoch, feature importances, model signatures, and input/output examples. For teams transitioning from spreadsheet-based experiment tracking, autologging provides immediate value with zero additional code.",
              "The Model Registry implements a production deployment workflow. A trained model is first logged to MLflow Tracking as a run artifact. Then registered to the Model Registry as a new model version. Automated quality gates evaluate it in Staging (accuracy thresholds, bias tests, latency benchmarks, shadow deployment results). After passing all gates and receiving human approval, it transitions to Production. The previous Production version moves to Archived. This audit trail satisfies regulatory requirements for high-stakes AI.",
              "Enterprise MLflow deployment: Databricks Managed MLflow provides enterprise-grade MLflow with SSO, RBAC, and 99.9% SLA. Self-hosted MLflow uses PostgreSQL or MySQL for the tracking backend (supporting concurrent writes from hundreds of training jobs) and S3/GCS for artifact storage. The MLflow server is typically deployed on Kubernetes with horizontal scaling. Model Registry webhooks trigger downstream CI/CD pipelines when model versions change stage."
            ]
          },
          questions: [
            { question_text: "A data scientist ran 300 experiments last month but cannot reproduce the best model because parameters weren't recorded. MLflow's which feature would have prevented this?", scenario_context: "Post-mortem for a reproducibility failure on your ML team.", options: ["MLflow Models for model packaging", "MLflow Tracking — automatically or manually logs all parameters, metrics, and artifacts to a persistent, queryable store", "MLflow Projects for environment packaging", "MLflow Recipes for standardized pipelines"], correct_answer_index: 1, explanation: "MLflow Tracking persists every experiment run with its parameters, metrics, code version, and artifacts. Any run can be reproduced by retrieving its logged parameters and running the same code version." },
            { question_text: "What are the three lifecycle stages in the MLflow Model Registry and what should gate each transition?", scenario_context: "You're implementing a model promotion workflow for a healthcare AI system.", options: ["Development → Testing → Production", "Staging → Production → Archived, with automated quality gates (accuracy, bias, latency) gating each transition", "v1 → v2 → v3, promoted on each training run", "Training → Validation → Deployment with manual review only"], correct_answer_index: 1, explanation: "Staging is where models await automated validation. Production is the live serving model. Archived holds deprecated versions. Staging→Production requires passing accuracy thresholds, fairness checks, latency benchmarks, and human approval — creating an auditable, safe promotion process." },
            { question_text: "How does MLflow autologging provide immediate value with minimal code changes?", scenario_context: "You're onboarding a team of 10 data scientists to MLflow.", options: ["Autologging writes reports automatically", "mlflow.[framework].autolog() intercepts training execution to automatically capture hyperparameters, metrics, feature importances, and model artifacts", "Autologging selects the best hyperparameters", "Autologging deploys models to production automatically"], correct_answer_index: 1, explanation: "One line — mlflow.sklearn.autolog() — before training code provides complete experiment tracking. The team immediately has searchable, comparable experiment history with zero additional logging code." },
            { question_text: "For a production MLflow deployment serving 100 simultaneous training jobs, what backend configuration is required?", scenario_context: "Your SQLite-backed MLflow server is crashing under team load.", options: ["Switch to a larger single MLflow server", "Use PostgreSQL or MySQL as the tracking backend (supports concurrent writes) with S3/GCS for artifact storage", "Limit teams to sequential experiment submission", "Use a NoSQL database for faster writes"], correct_answer_index: 1, explanation: "SQLite is single-writer and unsuitable for concurrent access. PostgreSQL with connection pooling handles hundreds of concurrent experiment logging requests. S3/GCS provides durable, scalable artifact storage. Deploy MLflow on Kubernetes with HPA for the tracking server." },
            { question_text: "A Model Registry webhook is most useful for:", scenario_context: "You want automatic deployment when a model is promoted to Production.", options: ["Notifying data scientists of training completion", "Triggering downstream CI/CD pipelines when model stage changes — e.g., auto-deploying to staging environment when a model is promoted from None to Staging", "Backing up the model registry database", "Sending daily experiment reports to leadership"], correct_answer_index: 1, explanation: "Model Registry webhooks fire on stage transitions. A Staging transition triggers automated testing. A Production transition triggers the deployment pipeline. This closes the loop between MLflow and your deployment infrastructure." }
          ]
        },
        {
          title: "2.2 CI/CD for Machine Learning: Building Automated Model Pipelines",
          description: "Implement production-grade ML CI/CD pipelines that automate testing, training, evaluation, and deployment.",
          order_index: 1,
          lessonScript: {
            mainPoints: [
              "CI/CD for ML extends traditional software CI/CD with model-specific concerns. A production ML pipeline does more than test code — it validates data quality with Great Expectations, runs model training on managed compute, evaluates model performance against production baselines, checks for bias across demographic groups, performs shadow deployment (running new model alongside production without serving its predictions), and promotes to production only when all automated gates pass.",
              "Data validation is the most-overlooked MLOps practice and the most common source of silent failures. Great Expectations lets you define expectations about your data — column types, value ranges, null rates, distribution bounds — and validates incoming training data against these expectations before any compute is spent. A single changed upstream data pipeline that introduces 30% null values in a critical feature will be caught immediately rather than producing a silently degraded model 6 hours of training later.",
              "The four phases of an ML CI/CD pipeline: Code CI (runs on every commit, tests code quality in minutes — unit tests, linting, data validation tests, schema validation). Model Training (triggers on new training data or significant model code changes, runs full training on managed compute). Model Evaluation (compares new model against production baseline on a held-out test set across accuracy, fairness, latency, and throughput). Model Deployment (canary rollout from 5% → 100% with automated rollback on metric degradation).",
              "Canary deployments are the safest ML deployment strategy. Traffic routing: 5% new model, 95% old model. Monitor: prediction latency, error rates, business metrics (click-through rate, conversion, fraud catch rate). If all metrics are healthy after 1 hour, promote to 25%. Continue incrementally to 100% over 24-48 hours. Automated rollback triggers return 100% traffic to the old model if any monitored metric falls outside defined bounds — protecting users from regressions without human intervention.",
              "GitHub Actions is the dominant platform for ML CI/CD. Define workflows in YAML files that trigger on push, pull_request, schedule, or repository_dispatch (triggered by data pipeline completion). Steps call cloud CLIs to provision training instances, submit training jobs to SageMaker or Vertex AI, retrieve evaluation metrics, and post results as PR comments. The workflow archives model evaluation reports, updates model registry status, and notifies on Slack. Keep the full ML pipeline under 90 minutes for developer velocity."
            ]
          },
          questions: [
            { question_text: "Why should data validation run before model training in a CI/CD pipeline?", scenario_context: "Your training pipeline spent 8 hours on expensive GPU compute only to discover the data had 40% null values in a critical feature.", options: ["Data validation improves model accuracy automatically", "Validating data upfront prevents wasting expensive GPU compute on bad data and catches pipeline regressions before they create bad models", "Data validation is a regulatory requirement", "Data validation is faster than model training"], correct_answer_index: 1, explanation: "GPU hours wasted on bad data are pure cost. Great Expectations validation runs in minutes and catches data quality regressions (missing values, distribution shifts, schema changes) before they trigger expensive training runs." },
            { question_text: "A new recommendation model has 2% better NDCG but 3x higher p99 inference latency (300ms vs 100ms, exceeding SLA of 150ms). Should CI/CD promote it?", scenario_context: "Your model evaluation gate must decide on promotion.", options: ["Yes — accuracy improvement always justifies promotion", "No — the latency SLA breach should block promotion regardless of accuracy improvement", "Yes, but with a note to optimize latency post-deployment", "Only promote if latency improves in the next release"], correct_answer_index: 1, explanation: "CI/CD evaluation gates check all production requirements, not just accuracy. A p99 latency of 300ms violating a 150ms SLA is a production blocker — users experience unacceptable response times. The model should be rejected and the latency issue investigated." },
            { question_text: "What is shadow deployment in ML CI/CD and what does it validate?", scenario_context: "You want to validate a new fraud detection model before it affects any real decisions.", options: ["Deploying to a shadow (test) environment with synthetic data", "Running the new model in parallel with production receiving real traffic, but not serving its predictions — comparing outputs to detect divergences before real impact", "Deploying to a subset of countries first", "Running the model overnight only"], correct_answer_index: 1, explanation: "Shadow deployment routes a copy of real production traffic to the new model. Predictions are logged but not served. Engineers compare new vs old model predictions, check for divergences, verify latency under real load, and confirm model behavior on production data distribution — all without impacting users." },
            { question_text: "What triggers model retraining in a modern ML CI/CD system?", scenario_context: "You're configuring automated retraining for a demand forecasting model.", options: ["Manual trigger only by data scientists", "Multiple triggers: scheduled (weekly/monthly), data drift detection (when input distribution shifts), performance degradation (accuracy below threshold), or new labeled data availability", "Only when code changes", "Only when cloud costs exceed budget"], correct_answer_index: 1, explanation: "Production ML systems need multiple retraining triggers: scheduled (catch gradual drift), performance-based (react to sudden degradation), data-triggered (new labeled data available), and drift-detected (input distribution has changed significantly). Manual-only retraining creates a response lag that causes silent model degradation." },
            { question_text: "At what canary traffic percentage should automated rollback trigger if you observe a 15% increase in prediction error rate?", scenario_context: "Your automated canary deployment system detects a metric anomaly at 5% traffic.", options: ["Wait until 50% traffic before rolling back for statistical significance", "Rollback immediately at any traffic percentage when metrics exceed defined thresholds — 5% traffic is sufficient signal for a 15% error rate increase", "Never rollback automatically — require human decision", "Only rollback if 100% of users are affected"], correct_answer_index: 1, explanation: "Automated rollback should trigger whenever metrics breach thresholds regardless of canary percentage. A 15% error rate increase at 5% canary is a strong, statistically significant signal. Waiting for higher traffic percentages unnecessarily degrades user experience." }
          ]
        },
        {
          title: "2.3 Model Monitoring and Drift Detection in Production",
          description: "Implement continuous monitoring systems that detect model degradation before it impacts business outcomes.",
          order_index: 2,
          lessonScript: {
            mainPoints: [
              "Production ML models degrade silently. Unlike traditional software, which either works or throws errors, ML models continue producing predictions as data distributions shift — just increasingly wrong ones. A credit scoring model trained on pre-COVID data will silently misclassify millions of applications as economic conditions change. Without model monitoring, companies discover model degradation through business impact reports weeks or months after the degradation begins.",
              "Two types of drift drive model degradation. Data drift (covariate shift): the distribution of input features changes. A fraud detection model trained on 2022 purchase patterns receives 2024 data with new merchant categories, payment methods, and transaction patterns it has never seen. Feature distributions have shifted. Concept drift: the relationship between features and the target changes. A churn prediction model trained when customer lifetime was 24 months now operates in a market where 6-month churn is normal — the same feature patterns predict different outcomes.",
              "SageMaker Model Monitor, Evidently AI, WhyLogs, and Arize are the leading model monitoring tools. SageMaker Model Monitor automatically captures a sample of inference requests and responses, computes statistics on the feature distribution, compares them against a baseline (from training data), and alerts when drift exceeds thresholds. Evidently AI is an open-source alternative that integrates with any deployment and provides rich drift reports, data quality checks, and model quality metrics.",
              "Model monitoring dashboards should track: prediction confidence distribution (are predictions becoming less certain?), feature drift scores (PSI/KL-divergence for each feature), label distribution drift (if ground truth is available), business metrics correlated with model quality (conversion rate, fraud catch rate), and latency/throughput SLAs. Anomaly detection on these signals — using statistical process control or ML-based anomaly detectors — fires alerts before human reviewers notice.",
              "Closing the feedback loop is the hardest part of production ML. Ground truth labels often arrive with delay — fraud labels when chargebacks clear (days to weeks), medical outcomes when results come back (days to months). Building systems to collect delayed ground truth, match it to predictions, compute model quality metrics, and trigger retraining requires thoughtful data architecture. Event streaming (Kafka), feature stores (Feast), and time-series databases (InfluxDB/TimescaleDB) are the technical building blocks."
            ]
          },
          questions: [
            { question_text: "Why do ML models degrade 'silently' in production, unlike traditional software?", scenario_context: "Your fraud detection model is making incorrect predictions but no errors are logged.", options: ["ML models have bugs that don't throw exceptions", "ML models continue producing predictions as data distributions shift — just increasingly wrong ones with no error signals", "ML models require manual updates unlike software", "ML model outputs are not logged by default"], correct_answer_index: 1, explanation: "Traditional software throws exceptions on invalid inputs. ML models produce output for every input regardless of how far it deviates from training data. Degradation is only detectable by monitoring prediction distributions and business metrics — not application logs." },
            { question_text: "What is the difference between data drift and concept drift?", scenario_context: "You're diagnosing why your e-commerce recommendation model performance degraded after a product catalog expansion.", options: ["Data drift is worse than concept drift", "Data drift: input feature distributions change. Concept drift: the relationship between features and target changes", "They are the same phenomenon", "Data drift only affects NLP models; concept drift only affects tabular models"], correct_answer_index: 1, explanation: "Data drift: the statistical distribution of inputs changes (new product categories enter the catalog). Concept drift: the same inputs predict different outcomes (user behavior toward existing categories changes). Both cause degradation; they require different detection methods and remediation strategies." },
            { question_text: "What statistical measure is commonly used to quantify feature drift between training and serving distributions?", scenario_context: "You need to configure automatic drift alerts for your 50-feature tabular model.", options: ["Accuracy decrease percentage", "Population Stability Index (PSI) or Jensen-Shannon divergence — measuring distribution distance between training and serving data", "Standard deviation of predictions", "Number of null values in serving data"], correct_answer_index: 1, explanation: "PSI quantifies how much a variable's distribution has shifted between two datasets. PSI < 0.1: no significant drift. 0.1-0.2: moderate drift requiring investigation. > 0.2: significant drift likely causing model degradation. It's the industry standard for tabular feature drift monitoring." },
            { question_text: "What is the hardest part of production model monitoring and why?", scenario_context: "You're designing a model monitoring system for a loan default prediction model.", options: ["Setting up monitoring infrastructure", "Closing the feedback loop — collecting ground truth labels that may arrive weeks or months after predictions, matching them to predictions, and computing actual model quality", "Visualizing drift metrics in dashboards", "Alerting on metric thresholds"], correct_answer_index: 1, explanation: "Loan defaults are observed 3-6 months after approval. Medical outcomes take days to weeks. Fraud chargebacks take 30-90 days. Building systems that collect delayed ground truth, match it to stored predictions (prediction store), and compute realized performance requires sophisticated data engineering beyond the monitoring tool itself." },
            { question_text: "A model monitoring alert fires: the average prediction confidence score has dropped from 0.87 to 0.61 over the past week. What does this indicate?", scenario_context: "You're investigating a model monitoring alert on your churn prediction model.", options: ["The model is becoming more accurate", "The model is encountering data that differs significantly from training distribution — inputs are in low-confidence regions of the feature space", "The monitoring system has a bug", "Confidence drops are expected and can be ignored"], correct_answer_index: 1, explanation: "A systematic drop in prediction confidence indicates the model is receiving inputs unlike its training data — it's less certain about its predictions. This is an early warning of concept or data drift, typically occurring weeks before accuracy metrics visibly degrade." }
          ]
        }
      ],
      endQuizQuestions: [
        { question_text: "Your MLflow Model Registry shows a model in Staging that passes all automated checks (accuracy +2%, latency P99 = 80ms, bias checks green). The next step is:", scenario_context: "All automated gates have passed for the new fraud detection model.", options: ["Immediately promote to Production", "Human review and approval, then promote with a canary deployment starting at 5% traffic", "Run more training experiments to improve accuracy further", "Deploy to Production at 100% traffic immediately after approval"], correct_answer_index: 1, explanation: "After automated gates pass, human review confirms the model makes sense from a business and risk perspective. Canary deployment at 5% provides a safe production validation before full rollout — critical for fraud detection where false negatives have direct financial impact." },
        { question_text: "SageMaker Model Monitor detects PSI > 0.25 on the 'account_age_days' feature — the distribution has shifted significantly. What is the correct response?", scenario_context: "A model monitoring alert fires on your credit scoring model.", options: ["Ignore — PSI alerts are rarely significant", "Investigate the upstream data pipeline for bugs, check if the customer base has changed, analyze model performance on new vs old distribution, consider retraining", "Immediately retrain the model", "Disable monitoring for that feature"], correct_answer_index: 1, explanation: "PSI > 0.25 indicates significant drift requiring investigation. First: is the data pipeline producing correct data? Second: has the customer demographic genuinely shifted? Third: how is model performance affected? Then determine if retraining is needed or if the upstream data issue needs fixing." },
        { question_text: "Your ML CI/CD pipeline takes 4 hours (30 min code CI, 3h training, 30 min evaluation). Code commits are blocked until the pipeline completes. How do you restore developer velocity?", scenario_context: "Engineers are frustrated waiting 4 hours for CI on every commit.", options: ["Optimize training to complete faster", "Split into fast code CI (runs on every commit) and slow model CI (runs only when model code or data changes), using separate pipeline triggers", "Run all pipelines in parallel", "Reduce CI requirements to speed up development"], correct_answer_index: 1, explanation: "Decouple code CI (unit tests, linting, data validation — 5-10 minutes, runs on every commit) from model CI (full training + evaluation — hours, triggered only by model code changes or new training data). Most commits don't affect the model and should never trigger a 3-hour training run." },
        { question_text: "Three months after your demand forecasting model was deployed, business users report it consistently underforecasts demand on Sundays. Model Monitor shows no drift alerts. Why might this happen?", scenario_context: "Post-incident investigation into systematic Sunday underprediction.", options: ["The model has a programming error", "The training data may have had underrepresented Sundays, or day-of-week feature was not included — monitoring without the right features misses these patterns", "Model Monitor is broken", "This is expected behavior from ML models"], correct_answer_index: 1, explanation: "Standard drift monitoring looks at overall feature distributions — it may miss systematic day-of-week patterns. If Sunday data was underrepresented in training or day_of_week wasn't a feature, the model has no mechanism to learn Sunday-specific patterns. Slice-based monitoring (performance by day of week) catches this; aggregate monitoring doesn't." },
        { question_text: "A fintech ML model in production begins making systematically riskier credit decisions after 6 months. No drift alerts fired. What monitoring gap allowed this?", scenario_context: "Post-mortem on a model that caused unexpected credit losses.", options: ["Drift monitoring was not configured", "Ground truth labels (actual loan outcomes) weren't collected and fed back to monitor realized model performance — only input drift was monitored", "The monitoring tool had a bug", "Credit models cannot be monitored effectively"], correct_answer_index: 1, explanation: "Input drift monitoring checks feature distributions but not model quality on actual outcomes. Without closing the feedback loop — collecting loan outcome labels 3-6 months later and computing realized precision/recall — the model appeared healthy while silently degrading on actual credit decisions." }
      ]
    }
  ]
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
    const _denied = await requireAdmin(req);
    if (_denied) return _denied;

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const { data: existing } = await supabaseClient
      .from("courses").select("id").eq("title", courseData.title).maybeSingle();

    if (existing) {
      return new Response(
        JSON.stringify({ message: "Course already exists", courseId: existing.id }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { data: course, error: courseError } = await supabaseClient
      .from("courses")
      .insert({
        title: courseData.title,
        description: courseData.description,
        is_published: true,
        translations: {
          es: { title: "Ingeniero de Cloud IA", description: "Domina el diseño y despliegue de cargas de trabajo de IA en AWS, Azure y GCP." },
          fr: { title: "Ingénieur Cloud IA", description: "Maîtrisez la conception et le déploiement de charges de travail IA sur AWS, Azure et GCP." },
          de: { title: "KI Cloud-Ingenieur", description: "Meistern Sie den Aufbau und die Bereitstellung von KI-Workloads auf AWS, Azure und GCP." },
          zh: { title: "AI云工程师", description: "掌握在AWS、Azure和GCP上构建和部署AI工作负载的技术。" },
          ar: { title: "مهندس السحابة الذكاء الاصطناعي", description: "أتقن تصميم ونشر أعباء عمل الذكاء الاصطناعي." },
          ja: { title: "AIクラウドエンジニア", description: "AWS、Azure、GCPでAIワークロードを構築・デプロイする技術をマスターする。" }
        }
      })
      .select().single();

    if (courseError) throw courseError;

    const chapterTranslations: Record<number, Record<string, any>> = {
      0: { es: { title: "Módulo 1: Fundamentos de Cloud para IA" }, fr: { title: "Module 1: Fondements Cloud pour IA" }, de: { title: "Modul 1: Cloud-Grundlagen für KI" }, zh: { title: "模块1：AI云基础" }, ar: { title: "الوحدة 1: أساسيات السحابة لمهندسي الذكاء الاصطناعي" }, ja: { title: "モジュール1：AIクラウド基礎" } },
      1: { es: { title: "Módulo 2: MLOps — Operacionalización de IA" }, fr: { title: "Module 2: MLOps — Opérationnalisation IA" }, de: { title: "Modul 2: MLOps — KI operationalisieren" }, zh: { title: "模块2：MLOps——AI大规模运营" }, ar: { title: "الوحدة 2: MLOps" }, ja: { title: "モジュール2：MLOps" } },
    };

    for (const chapterData of courseData.chapters) {
      const { data: chapter, error: chErr } = await supabaseClient
        .from("chapters")
        .insert({
          course_id: course.id,
          title: chapterData.title,
          description: chapterData.description,
          order_index: chapterData.order_index,
          translations: chapterTranslations[chapterData.order_index] || {},
        })
        .select().single();
      if (chErr) throw chErr;

      for (const videoData of chapterData.videos) {
        const transcript = videoData.lessonScript.mainPoints.join("\n\n");
        const { data: video, error: vErr } = await supabaseClient
          .from("videos")
          .insert({
            chapter_id: chapter.id,
            title: videoData.title,
            description: videoData.description,
            order_index: videoData.order_index,
            translations: {
              en: { title: videoData.title, transcript },
              es: { title: videoData.title, transcript },
              fr: { title: videoData.title, transcript },
              de: { title: videoData.title, transcript },
              zh: { title: videoData.title, transcript },
              ar: { title: videoData.title, transcript },
              ja: { title: videoData.title, transcript },
            },
          })
          .select().single();
        if (vErr) throw vErr;

        const { data: quiz, error: qErr } = await supabaseClient
          .from("quizzes")
          .insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 })
          .select().single();
        if (qErr) throw qErr;

        for (let i = 0; i < videoData.questions.length; i++) {
          const q = videoData.questions[i];
          await supabaseClient.from("quiz_questions").insert({
            quiz_id: quiz.id,
            question_text: q.question_text,
            scenario_context: q.scenario_context,
            options: q.options,
            correct_answer_index: q.correct_answer_index,
            explanation: q.explanation,
            order_index: i,
          });
        }
      }

      const { data: endQuiz, error: eqErr } = await supabaseClient
        .from("quizzes")
        .insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 })
        .select().single();
      if (eqErr) throw eqErr;

      for (let i = 0; i < chapterData.endQuizQuestions.length; i++) {
        const q = chapterData.endQuizQuestions[i];
        await supabaseClient.from("quiz_questions").insert({
          quiz_id: endQuiz.id,
          question_text: q.question_text,
          scenario_context: q.scenario_context,
          options: q.options,
          correct_answer_index: q.correct_answer_index,
          explanation: q.explanation,
          order_index: i,
        });
      }
    }

    return new Response(
      JSON.stringify({ message: "AI Cloud Engineer course seeded successfully", courseId: course.id }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : "Unknown error";
    return new Response(JSON.stringify({ error: msg }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
