-- ============================================================================
-- Map 100 REAL authored Scrum questions → live v2 flagship (0-BASED order_index).
-- CORRECTED reissue of 20260619020000: the live v2 course stores chapters with
-- 0-based order_index (0..17), but 020000 looked them up 1-based (1..18), so the
-- module-18 lookup (order_index=18) returned no row -> NULL quiz_id -> the whole
-- block aborted (no partial data). This version shifts every quiz lookup by -1
-- (1->0, 2->1, 4->3, 10->9, 12->11, 13->12, 18->17) and adds hard guards.
-- Maps ONLY quiz_questions onto EXISTING quizzes — inserts 0 lessons, 0 quizzes.
-- Apply by hand in Supabase (Claude does not auto-apply). Partial coverage:
-- 100 questions across 7 of 18 modules — NOT the 1,080-question bank.
-- ============================================================================
ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS translations JSONB DEFAULT '{}'::jsonb;
DO $$
DECLARE cid uuid; qz uuid; n int;
BEGIN
  SELECT id INTO cid FROM public.courses WHERE is_flagship ORDER BY created_at LIMIT 1;
  IF cid IS NULL THEN RAISE EXCEPTION 'Flagship course not found'; END IF;
  -- ---- v2-safe hard guards (0-based order_index; populated v2 course) ----
  IF cid <> 'f46d8fc2-50e4-4bd8-91da-f8bac4f7ba14' THEN
    RAISE EXCEPTION 'Flagship id % is not the expected v2 course — aborting', cid; END IF;
  SELECT count(*) INTO n FROM public.chapters WHERE course_id=cid;
  IF n <> 18 THEN RAISE EXCEPTION 'Expected 18 modules, found % — aborting', n; END IF;
  SELECT count(*) INTO n FROM public.videos v JOIN public.chapters c ON c.id=v.chapter_id WHERE c.course_id=cid;
  IF n <> 162 THEN RAISE EXCEPTION 'Expected 162 lessons, found % — aborting', n; END IF;
  SELECT count(*) INTO n FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id WHERE c.course_id=cid AND q.quiz_type='chapter_end';
  IF n <> 18 THEN RAISE EXCEPTION 'Expected 18 chapter_end quizzes, found % — aborting', n; END IF;
  SELECT count(*) INTO n FROM public.quiz_questions qq JOIN public.quizzes q ON q.id=qq.quiz_id JOIN public.chapters c ON c.id=q.chapter_id WHERE c.course_id=cid;
  IF n > 0 THEN RAISE EXCEPTION 'Flagship already has % mapped question(s) — aborting to avoid duplicates', n; END IF;
  -- the 7 target chapters (0-based) must each have a chapter_end quiz
  SELECT count(*) INTO n FROM public.chapters c JOIN public.quizzes q ON q.chapter_id=c.id AND q.quiz_type='chapter_end'
    WHERE c.course_id=cid AND c.order_index IN (0,1,3,9,11,12,17);
  IF n <> 7 THEN RAISE EXCEPTION 'Expected 7 target chapter_end quizzes (order_index 0,1,3,9,11,12,17), found % — aborting', n; END IF;
  RAISE NOTICE 'Guards passed: v2 flagship, 18 modules / 162 lessons / 18 quizzes / 0 questions; mapping 100 questions (0-based).';

  -- Module 1: 1 questions
  SELECT q.id INTO qz FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id
    WHERE c.course_id=cid AND c.order_index=0 AND q.quiz_type='chapter_end' LIMIT 1;
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What framework does this course primarily teach?', 'A friend asks what methodology you are studying.', '["Waterfall","Scrum","PRINCE2","Kanban"]'::jsonb, 1, 'This course is centered on the Scrum framework.', 1, 'scrum:framework', '{}'::jsonb);

  -- Module 2: 5 questions
  SELECT q.id INTO qz FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id
    WHERE c.course_id=cid AND c.order_index=1 AND q.quiz_type='chapter_end' LIMIT 1;
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the Scrum Master''s primary value to an organization?', 'An executive asks you to justify the Scrum Master role.', '["Writing code faster","Managing budgets","Enabling teams to deliver value continuously through Agile practices","Creating detailed project plans"]'::jsonb, 2, 'A Scrum Master enables continuous value delivery by coaching teams and removing obstacles.', 1, 'scrum:roles', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Which of the following is NOT a responsibility of a Scrum Master?', 'An interviewer asks you to describe what a Scrum Master does not do.', '["Facilitating Scrum events","Coaching the team on Agile practices","Assigning tasks to developers","Removing impediments"]'::jsonb, 2, 'Scrum Masters do not assign tasks — teams self-organize.', 2, 'scrum:roles', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How should a SM respond when asked to be the team''s project manager?', 'Your manager tells you to start managing the team''s tasks and reporting deadlines.', '["Accept the role immediately","Refuse all communication with management","Clarify the SM''s role and coach the organization on the difference","Start using Gantt charts alongside Scrum"]'::jsonb, 2, 'A SM should clarify their distinct role and use it as an opportunity to educate the organization.', 3, 'scrum:roles', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What do experts say about SMs who also code or do technical work?', 'You are a developer who just became a SM on the same team.', '["It is always a best practice to do both","It creates a conflict of interest and splits focus — the SM role should be primary","Technical SMs are always more effective","Only non-technical people should be SMs"]'::jsonb, 1, 'Combining SM and developer roles splits focus and can compromise the SM''s neutrality.', 4, 'scrum:roles', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is typically the first thing a SM does at the start of their workday?', 'You are preparing for your first day as a SM.', '["Checks and assigns tasks to team members","Reviews the team''s progress, checks for blockers, and prepares for the Daily Scrum","Writes the Sprint report","Attends a management briefing"]'::jsonb, 1, 'A SM begins the day by reviewing team status and preparing to facilitate the Daily Scrum.', 5, 'scrum:roles', '{}'::jsonb);

  -- Module 4: 3 questions
  SELECT q.id INTO qz FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id
    WHERE c.course_id=cid AND c.order_index=3 AND q.quiz_type='chapter_end' LIMIT 1;
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the primary benefit of daily Scrums for a development team?', 'A stakeholder questions why the team needs to meet every day.', '["To report status to management","To synchronize work and identify impediments quickly","To update the Product Backlog","To review completed user stories"]'::jsonb, 1, 'Daily Scrums help the team synchronize and surface impediments early.', 1, 'scrum:events', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How does a SM use retrospective techniques effectively?', 'Your team says the Retrospective always feels the same.', '["Cancel retrospectives to save time","Vary techniques like Start/Stop/Continue, 4Ls, and Sailboat to keep engagement high","Let the team run it with no structure","Use only one technique forever for consistency"]'::jsonb, 1, 'Rotating facilitation techniques keeps Retrospectives fresh and increases engagement.', 2, 'scrum:events', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What should a SM do when the Daily Scrum consistently runs over 15 minutes?', 'Your Daily Scrum has been running 30-40 minutes for three weeks.', '["Extend the time-box permanently","Accept it since longer meetings mean more collaboration","Coach the team on the purpose of the Daily Scrum and introduce techniques to stay focused","Cancel the Daily Scrum"]'::jsonb, 2, 'Chronic over-runs signal a facilitation opportunity — coach the team to keep to time-box.', 3, 'scrum:events', '{}'::jsonb);

  -- Module 10: 4 questions
  SELECT q.id INTO qz FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id
    WHERE c.course_id=cid AND c.order_index=9 AND q.quiz_type='chapter_end' LIMIT 1;
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Which Scrum value is demonstrated when team members share progress openly?', 'During a Daily Scrum, each member updates the team on blockers and progress.', '["Courage","Commitment","Transparency","Focus"]'::jsonb, 2, 'Transparency is reflected when team members openly share their work and impediments.', 1, 'scrum:empiricism', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What does continuous improvement mean in a Scrum context?', 'Your team completed a Retrospective and identified three process improvements.', '["Releasing features faster without quality checks","Regularly inspecting and adapting processes to become more effective","Replacing team members who underperform","Adding more tools and ceremonies"]'::jsonb, 1, 'Continuous improvement means regularly inspecting how the team works and adapting to improve.', 2, 'scrum:empiricism', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the role of transparency in a SM''s skill set?', 'The team is behind on Sprint goals but the SM has not communicated this to the PO.', '["Transparency is optional when information may cause concern","Transparency is a core skill — ensure all relevant information is visible to those who need it","Only the PO should be transparent","Transparency applies only during reviews"]'::jsonb, 1, 'Transparency is a foundational SM skill — ensuring relevant information is visible.', 3, 'scrum:empiricism', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What does a SM model through their own behavior?', 'A new team member watches how you respond to a tense situation in Sprint Planning.', '["Authority and control","The Scrum values: commitment, focus, openness, respect, and courage","Speed and efficiency above all else","Deference to the most senior person in the room"]'::jsonb, 1, 'Scrum Masters embody Scrum values — their behavior models commitment, openness, respect, focus, and courage.', 4, 'scrum:empiricism', '{}'::jsonb);

  -- Module 12: 10 questions
  SELECT q.id INTO qz FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id
    WHERE c.course_id=cid AND c.order_index=11 AND q.quiz_type='chapter_end' LIMIT 1;
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What does ''servant leadership'' mean in the Scrum context?', 'A hiring manager asks you to define servant leadership.', '["The SM serves coffee to the team","The SM prioritizes the needs of the team over personal authority","The SM reports to every team member","The SM avoids making any decisions"]'::jsonb, 1, 'Servant leadership means prioritizing enabling and supporting the team rather than exercising authority.', 1, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How does a Scrum Master handle a team conflict?', 'Two developers disagree on the technical approach for a user story.', '["Decides for the team which approach to use","Ignores it and hopes it resolves itself","Facilitates a conversation to help the team reach their own resolution","Escalates immediately to HR"]'::jsonb, 2, 'A Scrum Master facilitates conflict resolution by guiding the team to resolve it themselves.', 2, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the significance of asking powerful questions?', 'A team member comes to you with a problem and expects you to solve it.', '["It wastes time when direct answers are more efficient","Powerful questions help team members discover solutions themselves","It is a technique used only in coaching sessions","It shows the SM does not know the answer"]'::jsonb, 1, 'Powerful questions build team problem-solving capability rather than creating dependency.', 3, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the difference between coaching and mentoring?', 'A junior developer asks you to teach them everything about Scrum.', '["There is no difference","Coaching draws out the person''s own answers; mentoring shares the SM''s experience","Mentoring is for personal issues; coaching is for technical issues","Coaching is only for managers"]'::jsonb, 1, 'Coaching asks questions to help someone discover their own answers; mentoring shares knowledge.', 4, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Which demonstrates a SM''s conflict resolution skill?', 'Two senior developers are in a heated debate over architecture during Sprint Planning.', '["Taking sides with the more senior developer","Ending Sprint Planning early","Creating space for both views and guiding the team to a shared decision","Reporting the conflict to HR immediately"]'::jsonb, 2, 'Conflict resolution involves creating a safe space for all views and helping the team decide.', 5, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What does ''holding the space'' mean in facilitation?', 'The team goes silent after a difficult question during a Retrospective.', '["Filling silence with your own answers immediately","Booking the conference room in advance","Maintaining a safe environment that allows the team to reflect at their own pace","Scheduling the next meeting"]'::jsonb, 2, 'Holding the space means maintaining a safe environment and allowing silence and reflection.', 6, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How do experienced SMs approach a team that resists Agile?', 'Your new team says Scrum is just overhead.', '["Force compliance by enforcing all ceremonies strictly","Ignore their concerns and proceed as planned","Meet them where they are, understand frustrations, and build trust through small wins","Replace resistant team members"]'::jsonb, 2, 'Expert SMs build trust by meeting teams where they are and demonstrating value gradually.', 7, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How should a SM handle a technically superior team member who dismisses Scrum?', 'Your best developer openly says Scrum is a waste of time.', '["Remove them from the team","Agree with them publicly to avoid conflict","Acknowledge their expertise, explore concerns, and connect Scrum''s value to what they care about","Report them to the PO"]'::jsonb, 2, 'Effective SMs acknowledge expertise and make Scrum''s value relevant to individual goals.', 8, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What does ''holding a mirror'' mean as a SM technique?', 'Your team is not aware their estimation habits cause Sprint overload.', '["Bringing a physical whiteboard to retros","Reflecting observations back to the team to help them see their own patterns","Criticizing team members in public","Recording the team without their consent"]'::jsonb, 1, 'Holding a mirror means neutrally reflecting the team''s patterns back to prompt self-awareness.', 9, 'scrum:team-dynamics', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Why does a SM invest time in 1:1 conversations with team members?', 'You schedule a weekly 1:1 with each team member.', '["To evaluate their performance for HR purposes","To build trust and surface concerns that might not emerge in group settings","To assign personal targets and KPIs","To replace the Daily Scrum"]'::jsonb, 1, '1:1s build individual trust and surface concerns that people may not share in group settings.', 10, 'scrum:team-dynamics', '{}'::jsonb);

  -- Module 13: 37 questions
  SELECT q.id INTO qz FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id
    WHERE c.course_id=cid AND c.order_index=12 AND q.quiz_type='chapter_end' LIMIT 1;
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How does the Scrum Master support the Product Owner?', 'A Product Owner struggles to communicate priorities to the team.', '["By writing user stories for them","By helping them understand and apply effective Product Backlog management","By approving the product vision","By presenting the backlog to stakeholders instead"]'::jsonb, 1, 'The SM supports the PO by helping them manage the Product Backlog effectively.', 1, 'scrum:stakeholders', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How does a Scrum Master benefit the organization beyond the team?', 'A VP asks what value the Scrum Master brings to the broader company.', '["By managing project budgets","By coaching the organization in Agile adoption and removing systemic impediments","By writing technical documentation","By replacing the HR function"]'::jsonb, 1, 'Scrum Masters benefit the organization by coaching Agile adoption and removing systemic barriers.', 2, 'scrum:stakeholders', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How do expert Scrum Masters approach stakeholder management?', 'A senior executive keeps bypassing the Scrum process.', '["Always comply with executive requests immediately","Ignore stakeholders outside the team","Educate stakeholders on Scrum and find ways to engage them constructively","Escalate to HR every time"]'::jsonb, 2, 'Expert SMs educate stakeholders on Scrum and find constructive ways to engage them.', 3, 'scrum:stakeholders', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the value of understanding business context for a SM?', 'The PO mentions revenue goals when discussing backlog priorities.', '["Business context is irrelevant to the SM role","Understanding business goals helps the SM facilitate better prioritization and stakeholder alignment","Only the PO needs to understand business context","It helps the SM become a PO eventually"]'::jsonb, 1, 'Business context helps the SM facilitate more meaningful conversations about value and priority.', 4, 'scrum:stakeholders', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What skill helps a SM lead organizational change beyond their team?', 'Your company wants to scale Agile across all departments.', '["Project management certification","Change management skills and stakeholder influence","Database administration","Knowledge of accounting principles"]'::jsonb, 1, 'Change management skills allow SMs to guide organizational Agile transformations.', 5, 'scrum:stakeholders', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What do experts say about SMs with both Agile and business skills?', 'A recruiter tells you the most in-demand SMs have a business background.', '["Business skills are irrelevant to coaching","Combined Agile and business skills make SMs more credible organizational partners","Business skills make SMs too focused on profit","Only POs need business skills"]'::jsonb, 1, 'Business literacy combined with Agile expertise makes SMs more effective organizational partners.', 6, 'scrum:stakeholders', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How does the SM handle a stakeholder who demands daily status updates?', 'A VP emails you every morning asking for a team status report.', '["Writes a daily report to keep them happy","Ignores the emails","Engages the stakeholder and provides appropriate visibility through Scrum artifacts","Adds the VP to the Daily Scrum"]'::jsonb, 2, 'The SM connects the stakeholder to appropriate Scrum artifacts and review events.', 7, 'scrum:stakeholders', '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the primary focus of a traditional project manager?', 'You''re comparing PM and SM roles.', '["Facilitating and coaching","Planning, scheduling, and controlling","Removing impediments only","Writing code"]'::jsonb, 1, 'Traditional project managers focus on planning, scheduling, and controlling project activities.', 8, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How do Scrum Masters typically influence their teams?', 'You need to explain your leadership approach.', '["Through direct authority","Through servant leadership","Through financial incentives","Through threat of termination"]'::jsonb, 1, 'Scrum Masters influence through servant leadership rather than direct authority.', 9, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How does Scrum approach planning compared to traditional PM?', 'Stakeholders want a detailed 12-month plan.', '["Detailed upfront planning","Iterative planning that adapts to change","No planning at all","Planning only at the end"]'::jsonb, 1, 'Scrum uses iterative planning that adapts to change rather than detailed upfront planning.', 10, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How do project managers typically track progress?', 'You''re comparing tracking methods.', '["Daily standups only","Against a baseline plan","No tracking needed","Through Scrum events"]'::jsonb, 1, 'Project managers track progress against a baseline plan created at the start.', 11, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What common goal do both PMs and Scrum Masters share?', 'You''re explaining why both roles matter.', '["Following identical processes","Project success through their respective approaches","Maximizing team size","Creating documentation"]'::jsonb, 1, 'Both roles aim for project success, but through fundamentally different approaches.', 12, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the trend for Scrum Master demand?', 'You''re considering a career as a Scrum Master.', '["Decreasing significantly","Continues to grow as organizations adopt Agile","Staying exactly the same","Only growing in tech"]'::jsonb, 1, 'The demand for Scrum Masters continues to grow as more organizations adopt Agile practices.', 13, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'In which industries can Scrum Masters find opportunities?', 'You''re exploring different sectors.', '["Only software development","Only startups","Across all industries including tech, healthcare, finance","Only Fortune 500 companies"]'::jsonb, 2, 'Opportunities exist across all industries including tech, healthcare, finance, manufacturing, and more.', 14, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How has remote work affected Scrum Master opportunities?', 'You''re considering remote work options.', '["Eliminated all opportunities","Expanded opportunities for global team work","Had no impact","Reduced salary potential"]'::jsonb, 1, 'Remote work has expanded opportunities, allowing Scrum Masters to work with global teams.', 15, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What additional skill are many organizations seeking?', 'You want to make yourself more marketable.', '["Programming expertise","Enterprise-level coaching capabilities","Marketing skills","Legal expertise"]'::jsonb, 1, 'Many organizations are looking for Scrum Masters who can also coach at the enterprise level.', 16, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What career paths can Scrum Masters pursue?', 'You''re planning your long-term career.', '["Only staying as Scrum Master forever","Agile Coach, RTE, or organizational transformation roles","Only becoming a developer","Only moving to sales"]'::jsonb, 1, 'Career paths can lead to Agile Coach, Release Train Engineer, or organizational transformation roles.', 17, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What foundational document should you master first?', 'You''re starting your Scrum Master journey.', '["PMBOK Guide","The Scrum Guide","Company policies","Technical documentation"]'::jsonb, 1, 'Start with the basics - read and deeply understand the Scrum Guide. It''s the foundation.', 18, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Where can you practice facilitation skills?', 'You want to improve your facilitation.', '["Only in professional settings","Any setting - team meetings, community groups, anywhere","Only during Scrum events","Only with certification training"]'::jsonb, 1, 'Practice facilitation in any setting - team meetings, community groups, even family gatherings.', 19, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is a recommended way to accelerate your growth?', 'You want to develop faster as a Scrum Master.', '["Work alone and figure it out","Seek mentorship from experienced Scrum Masters","Avoid asking for help","Only read books"]'::jsonb, 1, 'Seek mentorship from experienced Scrum Masters or Agile Coaches to accelerate your growth.', 20, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Why should you join Scrum communities?', 'You''re wondering if networking is worth your time.', '["To find a new job","To learn from peers and stay current","To complain about your team","To avoid doing real work"]'::jsonb, 1, 'Join Scrum communities and attend meetups to learn from peers and stay current.', 21, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the role of certification in becoming a Scrum Master?', 'You''re deciding whether to get certified.', '["It''s not needed at all","It validates knowledge but is just the beginning of the journey","It guarantees job success","It replaces practical experience"]'::jsonb, 1, 'Get certified to validate your knowledge, but remember certification is just the beginning of your journey.', 22, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What trend exists in Scrum Master job postings?', 'You''re analyzing the job market.', '["Significant decrease","Significant increase in recent years","No change","Jobs only for seniors"]'::jsonb, 1, 'Job postings for Scrum Masters have increased significantly in recent years.', 23, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What type of experience do many companies value?', 'You''re tailoring your resume.', '["Any random experience","Industry-specific experience in their domain","Only technical experience","Only educational degrees"]'::jsonb, 1, 'Many companies seek Scrum Masters with industry-specific experience in their domain.', 24, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What alternative to full-time employment exists for Scrum Masters?', 'You''re exploring different work arrangements.', '["None available","Contract and consulting opportunities","Only volunteer work","Only government positions"]'::jsonb, 1, 'Contract and consulting opportunities allow flexibility and variety in your career.', 25, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What should you be aware of in some job postings?', 'You''re reviewing a job description.', '["All jobs are identical","Some organizations combine Scrum Master with other roles","Salaries are always the same","Experience never matters"]'::jsonb, 1, 'Some organizations combine Scrum Master with other roles - be aware of the expectations.', 26, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What can significantly boost your job search?', 'You''re preparing for your job search.', '["Avoiding social media","Building a strong LinkedIn presence and portfolio","Waiting for jobs to find you","Hiding your experience"]'::jsonb, 1, 'Building a strong LinkedIn presence and portfolio can significantly boost your job search.', 27, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the focus of entry-level Scrum Masters?', 'You''re just starting your SM career.', '["Organizational transformation","Learning the framework and facilitating basic events","Mentoring other SMs","Enterprise coaching"]'::jsonb, 1, 'Entry-level Scrum Masters focus on learning the framework and facilitating basic Scrum events.', 28, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What can mid-level Scrum Masters handle effectively?', 'You''ve been a SM for 2 years.', '["Only simple problems","Coaching teams and complex impediments","Only administrative tasks","Only single team facilitation"]'::jsonb, 1, 'Mid-level Scrum Masters can effectively coach teams and handle complex impediments.', 29, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What do senior Scrum Masters typically do?', 'You''re aspiring to senior level.', '["Focus only on one team","Work across multiple teams and influence organizational change","Avoid organizational politics","Only attend meetings"]'::jsonb, 1, 'Senior Scrum Masters work across multiple teams and influence organizational change.', 30, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is a Principal Scrum Master''s responsibility?', 'You''re learning about the highest SM levels.', '["Just facilitating ceremonies","Shaping Agile strategy and mentoring other Scrum Masters","Only technical work","Writing code"]'::jsonb, 1, 'Principal or Staff Scrum Masters shape Agile strategy and mentor other Scrum Masters.', 31, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is required to advance to higher Scrum Master levels?', 'You want to grow in your career.', '["Just more years of experience","Deeper coaching skills and broader organizational influence","Only more certifications","Switching companies frequently"]'::jsonb, 1, 'Each level requires developing deeper coaching skills and broader organizational influence.', 32, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Why do many Scrum Masters love their role?', 'You''re considering becoming a Scrum Master.', '["High salary only","Making a real difference in people''s work lives","Easy work","No meetings required"]'::jsonb, 1, 'Many Scrum Masters love the role because they can make a real difference in people''s work lives.', 33, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What keeps the Scrum Master role engaging?', 'You worry about getting bored.', '["Repetitive tasks","The variety of challenges - no two days are alike","Following the same routine","Avoiding problems"]'::jsonb, 1, 'The variety of challenges keeps the role engaging - no two days are exactly alike.', 34, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is a common source of job satisfaction for Scrum Masters?', 'You''re evaluating career happiness.', '["Avoiding all team interaction","Helping teams succeed","Working alone","Minimizing meetings"]'::jsonb, 1, 'Scrum Masters often report high job satisfaction from helping teams succeed.', 35, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What unique blend does the Scrum Master role offer?', 'You''re comparing different career paths.', '["Only technical skills","People skills, problem-solving, and continuous learning","Only administrative tasks","Only management duties"]'::jsonb, 1, 'The role offers a unique blend of people skills, problem-solving, and continuous learning.', 36, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Who might find the Scrum Master role incredibly fulfilling?', 'You''re assessing your fit for the role.', '["Those who avoid people","Those who love coaching and development","Those who want to work alone","Those who dislike change"]'::jsonb, 1, 'For those who love coaching and development, being a Scrum Master is incredibly fulfilling.', 37, NULL, '{}'::jsonb);

  -- Module 18: 40 questions
  SELECT q.id INTO qz FROM public.quizzes q JOIN public.chapters c ON c.id=q.chapter_id
    WHERE c.course_id=cid AND c.order_index=17 AND q.quiz_type='chapter_end' LIMIT 1;
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the current state of the Scrum Master job market?', 'You''re evaluating career stability.', '["Declining rapidly","Strong with continuous growth","Completely saturated","Only entry-level available"]'::jsonb, 1, 'The Scrum Master job market remains strong with continuous growth in demand.', 1, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What are companies increasingly looking for?', 'You''re preparing for job interviews.', '["Only new graduates","Experienced Scrum Masters who can hit the ground running","Only project managers converting","Only those with MBAs"]'::jsonb, 1, 'Companies are increasingly looking for experienced Scrum Masters who can hit the ground running.', 2, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What work arrangements have become standard for Scrum Masters?', 'You''re considering work-life balance options.', '["Only on-site full-time","Remote and hybrid work options","Only contract work","No flexibility available"]'::jsonb, 1, 'Remote and hybrid work options have become standard in many Scrum Master positions.', 3, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What combination creates particularly attractive candidates?', 'You want to stand out in applications.', '["Only certifications","Industry experience combined with Scrum expertise","Only educational degrees","Only years of experience"]'::jsonb, 1, 'Industry experience combined with Scrum expertise creates particularly attractive candidates.', 4, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What often leads to the best job opportunities?', 'You''re strategizing your job search.', '["Only applying online","Networking and community involvement","Waiting for recruiters","Avoiding social media"]'::jsonb, 1, 'Networking and community involvement often lead to the best job opportunities.', 5, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Which certification is one of the most recognized for Scrum Masters?', 'You''re choosing your first certification.', '["PMP","Certified Scrum Master (CSM) from Scrum Alliance","Six Sigma Black Belt","ITIL Foundation"]'::jsonb, 1, 'The Certified Scrum Master (CSM) from Scrum Alliance is one of the most recognized certifications.', 6, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What does the PMI-ACP certification cover?', 'You''re comparing different certifications.', '["Only Scrum","Multiple Agile frameworks, not just Scrum","Only Kanban","Only traditional PM"]'::jsonb, 1, 'PMI-ACP (Agile Certified Practitioner) covers multiple Agile frameworks, not just Scrum.', 7, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What does PMI-DASM focus on?', 'You''re evaluating PMI certifications.', '["Only theory","Practical application in various contexts","Only one methodology","Only large enterprises"]'::jsonb, 1, 'PMI-DASM (Disciplined Agile Scrum Master) focuses on practical application in various contexts.', 8, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What differs between certifications regarding prerequisites?', 'You''re checking if you qualify.', '["All are identical","Some require experience, others just training","None require training","All require 10+ years experience"]'::jsonb, 1, 'Each certification has different prerequisites - some require experience, others just training.', 9, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How should you choose your certification path?', 'You''re planning your professional development.', '["Pick the cheapest one","Based on career goals and target employer preferences","Get all of them at once","Avoid certifications entirely"]'::jsonb, 1, 'Choose your certification path based on your career goals and the preferences of your target employers.', 10, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'In what environments do Scrum Masters work?', 'You''re exploring different company types.', '["Only large corporations","Diverse environments from startups to large enterprises","Only tech companies","Only consulting firms"]'::jsonb, 1, 'Scrum Masters work in diverse environments from startups to large enterprises.', 11, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What significantly impacts how the Scrum Master role is perceived?', 'You''re evaluating potential employers.', '["Only salary levels","The culture of an organization","Office location only","Company age only"]'::jsonb, 1, 'The culture of an organization significantly impacts how the Scrum Master role is perceived and utilized.', 12, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What affects your daily challenges as a Scrum Master?', 'You''re preparing for different scenarios.', '["Only your skills","The Agile maturity of the environment","Only team size","Only the product type"]'::jsonb, 1, 'Some environments are more Agile-mature than others - this affects your daily challenges.', 13, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Where are Scrum Masters growing outside of IT?', 'You''re exploring non-traditional SM opportunities.', '["Nowhere","HR, marketing, and operations","Only manufacturing","Only healthcare"]'::jsonb, 1, 'Scrum Masters outside IT are growing in areas like HR, marketing, and operations.', 14, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is crucial for job satisfaction and effectiveness?', 'You''re considering job offers.', '["Only salary","Finding the right organizational fit","Only title","Only team size"]'::jsonb, 1, 'Finding the right organizational fit is crucial for job satisfaction and effectiveness.', 15, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How should aspiring Scrum Masters begin their journey?', 'You''re just starting out.', '["Immediately take charge","Observe experienced Scrum Masters and learn from them","Avoid all senior SMs","Only read books"]'::jsonb, 1, 'Start by observing experienced Scrum Masters and learning from their approaches.', 16, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What should you understand about developing mastery?', 'You feel frustrated with your progress.', '["It happens instantly","Mastery takes time and practice","Some people never learn","It requires no effort"]'::jsonb, 1, 'Be patient with yourself and your teams - mastery takes time and practice.', 17, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What relationships should Scrum Masters prioritize building?', 'You''re planning your stakeholder engagement.', '["Only with management","With Product Owners, developers, and stakeholders","Only with other Scrum Masters","Only with customers"]'::jsonb, 1, 'Build strong relationships with Product Owners, developers, and stakeholders.', 18, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Why should you never stop learning as a Scrum Master?', 'You have 10 years of experience.', '["Learning isn''t necessary","The Agile world evolves constantly","Only new SMs need to learn","Experience replaces learning"]'::jsonb, 1, 'Never stop learning - the Agile world evolves constantly and so should you.', 19, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the core purpose of a Scrum Master''s job?', 'You''re reflecting on your role.', '["To be the hero","To make others successful","To take credit for success","To manage every decision"]'::jsonb, 1, 'Remember that your job is to make others successful, not to be the hero yourself.', 20, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the primary goal of this course?', 'You''re recommending this course to a colleague.', '["To learn coding","To equip learners with knowledge to excel as Scrum Masters","To become a project manager","To learn waterfall methodology"]'::jsonb, 1, 'The course equips learners with knowledge and tools needed to excel as a Scrum Master.', 21, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How does a Scrum Master lead their team?', 'You''re explaining your leadership approach.', '["Through command and control","Through servant leadership","Through micromanagement","Through delegation only"]'::jsonb, 1, 'Scrum Masters lead through servant leadership, focusing on serving the team''s needs.', 22, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the Scrum Master''s role in Daily Scrum?', 'You''re facilitating your first Daily Scrum.', '["To give status updates","To facilitate the 15-minute sync","To assign tasks","To take meeting notes"]'::jsonb, 1, 'The Scrum Master facilitates the Daily Scrum but doesn''t run or direct it.', 23, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Why is emotional intelligence important for Scrum Masters?', 'You notice team tension during a Sprint.', '["It''s not important","To read and respond to team dynamics","To avoid all emotions","To manipulate team members"]'::jsonb, 1, 'Emotional intelligence enables Scrum Masters to read the room and respond appropriately.', 24, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What should a Scrum Master do when they identify an impediment?', 'A team member can''t access needed resources.', '["Ignore it","Work to remove it","Report it to HR","Blame the team member"]'::jsonb, 1, 'Scrum Masters work actively to remove impediments that block team progress.', 25, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the main difference between a PM and Scrum Master''s planning approach?', 'You''re comparing methodologies.', '["No difference","PMs use detailed upfront planning, SMs use iterative planning","SMs plan more","PMs never plan"]'::jsonb, 1, 'Traditional PMs use detailed upfront planning while Scrum uses iterative, adaptive planning.', 26, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What career paths are available for experienced Scrum Masters?', 'You''re planning your career growth.', '["Only staying as SM","Agile Coach, RTE, or transformation roles","Only becoming a PM","No growth paths exist"]'::jsonb, 1, 'Career paths can lead to Agile Coach, Release Train Engineer, or organizational transformation roles.', 27, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Why is certification important but not sufficient?', 'You just passed your CSM exam.', '["Certification guarantees success","It validates knowledge but is just the beginning","It replaces experience","It''s not important"]'::jsonb, 1, 'Certification validates knowledge but practical experience and continuous learning are essential.', 28, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What level focuses on organizational change?', 'You want to have broader impact.', '["Entry-level","Senior Scrum Master","Junior only","None of them"]'::jsonb, 1, 'Senior Scrum Masters work across multiple teams and influence organizational change.', 29, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What makes Scrum Master roles engaging according to experts?', 'You want to understand job satisfaction.', '["Repetitive work","Variety of challenges","Easy problems","No challenges"]'::jsonb, 1, 'The variety of challenges keeps the role engaging - no two days are exactly alike.', 30, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Which certification covers multiple Agile frameworks?', 'You want broad Agile knowledge.', '["CSM","PMI-ACP","PSM","SAFe only"]'::jsonb, 1, 'PMI-ACP (Agile Certified Practitioner) covers multiple Agile frameworks, not just Scrum.', 31, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What often leads to the best job opportunities for Scrum Masters?', 'You''re job hunting.', '["Mass applying online","Networking and community involvement","Waiting passively","Avoiding LinkedIn"]'::jsonb, 1, 'Networking and community involvement often lead to the best job opportunities.', 32, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Where are Scrum Masters increasingly finding opportunities outside IT?', 'You''re exploring diverse industries.', '["Nowhere","HR, marketing, and operations","Only manufacturing","Only retail"]'::jsonb, 1, 'Scrum Masters are growing in areas like HR, marketing, and operations outside IT.', 33, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is crucial when evaluating potential employers?', 'You have multiple job offers.', '["Only salary","Organizational culture and fit","Only location","Only company size"]'::jsonb, 1, 'Finding the right organizational fit is crucial for job satisfaction and effectiveness.', 34, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What work arrangements have become standard for Scrum Masters?', 'You value flexibility.', '["Only on-site","Remote and hybrid options","Only full-time","Only contract"]'::jsonb, 1, 'Remote and hybrid work options have become standard in many Scrum Master positions.', 35, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the purpose of a SWOT analysis for the Scrum Master role?', 'You''re starting the final project.', '["To criticize the role","To identify opportunities and threats for the organization","To avoid problems","To create documentation only"]'::jsonb, 1, 'SWOT analysis helps determine potential opportunities if done well or threats if not conducted successfully.', 36, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What is the core job of a Scrum Master according to experts?', 'You''re reflecting on your purpose.', '["To be the hero","To make others successful","To take all credit","To manage everyone"]'::jsonb, 1, 'The Scrum Master''s job is to make others successful, not to be the hero themselves.', 37, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'Why should experienced Scrum Masters continue learning?', 'You have many years of experience.', '["They shouldn''t","The Agile world evolves constantly","Learning stops after certification","Experience is enough"]'::jsonb, 1, 'The Agile world evolves constantly and Scrum Masters should evolve with it.', 38, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'What relationships are essential for Scrum Master success?', 'You''re building your network.', '["Only with managers","With POs, developers, and stakeholders","Only with customers","None needed"]'::jsonb, 1, 'Building strong relationships with Product Owners, developers, and stakeholders is essential.', 39, NULL, '{}'::jsonb);
  INSERT INTO public.quiz_questions(quiz_id, question_text, scenario_context, options, correct_answer_index, explanation, order_index, competency, translations) VALUES (qz, 'How should aspiring Scrum Masters approach their development?', 'You''re just starting your journey.', '["Rush to lead","Be patient - mastery takes time","Avoid all mentors","Skip observation"]'::jsonb, 1, 'Be patient with yourself and your teams - mastery takes time and practice.', 40, NULL, '{}'::jsonb);
END $$;

-- VERIFY: questions per module
-- SELECT c.order_index AS module, count(qq.*) AS questions
-- FROM chapters c JOIN quizzes q ON q.chapter_id=c.id LEFT JOIN quiz_questions qq ON qq.quiz_id=q.id
-- WHERE c.course_id=(SELECT id FROM courses WHERE is_flagship) GROUP BY c.order_index ORDER BY c.order_index;
