-- =============================================================================
-- Seed BA quiz questions — Modules 16, 17, 18 (15 questions each = 45 total)
-- AI Business Analyst & Product Discovery Specialist (ba-v1)
-- Apply AFTER structure and content migrations.
-- Uses direct INSERT (idempotent check by module).
-- =============================================================================

CREATE OR REPLACE FUNCTION pg_temp.fill_ba_exam_new(p_mod int, p_payload jsonb)
RETURNS void LANGUAGE plpgsql AS $fn$
DECLARE
  cid uuid; ch uuid; qz uuid; rec jsonb; i int := 0;
BEGIN
  SELECT id INTO cid FROM public.courses
    WHERE title = 'AI Business Analyst & Product Discovery Specialist'
      AND curriculum_version = 'ba-v1';
  SELECT id INTO ch FROM public.chapters
    WHERE course_id = cid AND order_index = p_mod;
  SELECT id INTO qz FROM public.quizzes
    WHERE chapter_id = ch AND quiz_type = 'chapter_end';
  IF qz IS NULL THEN RAISE NOTICE 'no exam for module %', p_mod; RETURN; END IF;
  IF EXISTS (SELECT 1 FROM public.quiz_questions WHERE quiz_id = qz) THEN
    RAISE NOTICE 'module % already has questions — skipping', p_mod; RETURN;
  END IF;
  FOR rec IN SELECT * FROM jsonb_array_elements(p_payload) LOOP
    i := i + 1;
    INSERT INTO public.quiz_questions
      (quiz_id, question_text, options, correct_answer_index, explanation,
       order_index, competency, translations)
    VALUES (qz, rec->>'q', rec->'opts', (rec->>'a')::int, rec->>'exp',
       i, rec->>'competency', '{}'::jsonb);
  END LOOP;
  RAISE NOTICE 'module %: inserted % questions', p_mod, i;
END;
$fn$;

-- ── MODULE 16: Agile BA & Product Ownership ───────────────────────────────
SELECT pg_temp.fill_ba_exam_new(16, '[
{"q":"In Agile, what is the primary shift in the BA role compared to waterfall?","opts":["BAs are no longer needed","BAs write more detailed documents","From requirements document author to continuous collaborator embedded in the team","BAs focus only on testing"],"a":2,"exp":"In Agile, the BA shifts from producing a complete upfront BRD to continuously elaborating requirements as part of the team. The BA''s value is distributed across the sprint lifecycle, not front-loaded.","competency":"ba:agile"},
{"q":"What is the Definition of Ready (DoR) and who owns it?","opts":["A done criteria owned by the tester","A sprint planning checklist owned by the Scrum Master","A set of conditions a user story must meet before entering a sprint — owned by the team and enforced by the BA","A technical architecture checklist"],"a":2,"exp":"The DoR is the BA''s quality gate for the backlog. A story is ready when: user type, capability, and value are clear; acceptance criteria are written; dependencies are identified; and the team can estimate it.","competency":"ba:agile"},
{"q":"What does INVEST stand for in user story quality?","opts":["Integrated, Novel, Valuable, Executable, Scalable, Testable","Independent, Negotiable, Valuable, Estimable, Small, Testable","Iterative, Notable, Verifiable, Essential, Scoped, Timed","Important, Needed, Vetted, Easy, Specific, Technical"],"a":1,"exp":"INVEST: Independent (can deploy alone), Negotiable (details TBD), Valuable (business value clear), Estimable (team can size it), Small (fits in a sprint), Testable (acceptance criteria exist).","competency":"ba:agile"},
{"q":"What is the Three Cs model for user stories?","opts":["Criteria, Context, Confirmation","Card, Conversation, Confirmation","Clarity, Completeness, Correctness","Create, Communicate, Confirm"],"a":1,"exp":"Card: a placeholder for a conversation (not a complete spec). Conversation: the real requirement lives in the discussion. Confirmation: acceptance criteria are the written output of the conversation.","competency":"ba:agile"},
{"q":"What is the best format for writing acceptance criteria?","opts":["Free-form paragraph descriptions","Only numerical thresholds","Given/When/Then (BDD format): Given [precondition], When [action], Then [expected result]","Developer task lists"],"a":2,"exp":"Given/When/Then forces specificity and creates the basis for automated testing. ''The system should validate input'' is not an acceptance criterion. ''Given an invalid email, When submitted, Then an error message appears within 1 second'' is.","competency":"ba:agile"},
{"q":"When a large user story cannot be estimated, the correct BA response is to:","opts":["Force the team to estimate it anyway","Remove it from the backlog","Split it into smaller stories that meet INVEST criteria","Escalate to the project manager"],"a":2,"exp":"An inestimable story is too large or too ambiguous. The BA''s job is to split it (by workflow step, user type, data type, or happy path/exception) until the team can confidently estimate each piece.","competency":"ba:agile"},
{"q":"In SAFe, what is a Program Increment (PI)?","opts":["A release to production","A certification milestone","A 10-week planning and delivery cycle for the Agile Release Train","A product backlog refinement session"],"a":2,"exp":"In SAFe, the PI is the fundamental cadence. Every 10 weeks, all teams in the Agile Release Train plan together (PI Planning) and deliver together. The BA operates at both team level (stories) and program level (features).","competency":"ba:agile"},
{"q":"What is the BA''s primary responsibility in a sprint review?","opts":["Presenting the sprint burndown chart","Validating delivered functionality against acceptance criteria and facilitating stakeholder feedback","Writing the next sprint''s user stories","Updating the project plan"],"a":1,"exp":"The sprint review is a validation event, not a demo. The BA validates acceptance criteria compliance, facilitates stakeholder feedback (''Does this solve the problem?''), captures new requirements, and documents acceptance or rejection.","competency":"ba:agile"},
{"q":"What is velocity in Agile and how does the BA use it?","opts":["The speed of individual developers","The number of bugs fixed per sprint","The average story points delivered per sprint — used by BAs for release planning and roadmap communication","The deployment frequency"],"a":2,"exp":"Velocity is the team''s average delivery capacity. BAs use it for release planning: if the team averages 30 points/sprint and the next release requires 90 points of stories, it will take approximately 3 sprints.","competency":"ba:agile"},
{"q":"What is story mapping and when is it most valuable?","opts":["A technique for mapping stories to developers","A visual technique organizing user stories across the user journey to reveal scope, gaps, and release slices — most valuable for new product or feature planning","A bug tracking technique","A test case organization method"],"a":1,"exp":"Story maps place user activities along the top (the journey) with prioritized stories beneath. This reveals: what is the minimum viable product? What is in scope? What are we missing? Far more useful than a flat backlog for product planning conversations.","competency":"ba:agile"},
{"q":"In LeSS (Large-Scale Scrum), how does the BA role differ from single-team Scrum?","opts":["LeSS eliminates the BA role","LeSS requires a dedicated BA per team","The BA works with a single Product Owner who owns the entire multi-team product backlog, supporting feature elaboration across multiple teams","LeSS requires a formal BA Program Office"],"a":2,"exp":"LeSS minimizes additional roles. The BA supports the single Product Owner whose backlog serves all teams, helps elaborate features for multiple teams simultaneously, and facilitates cross-team coordination without a formal program layer.","competency":"ba:agile"},
{"q":"What is backlog refinement and how often should it occur?","opts":["A monthly planning meeting","A session held only before PI Planning","A continuous process (typically 10% of sprint capacity) where the team elaborates, estimates, and prioritizes upcoming stories — the BA''s most important recurring activity","A one-time activity at project start"],"a":2,"exp":"Refinement is ongoing, not a one-time event. The BA''s role is to keep the backlog ''ready'' above the waterline — stories elaborated, estimated, and ordered so the team always has ready work for the next sprint.","competency":"ba:agile"},
{"q":"What is the WSJF prioritization method used in SAFe?","opts":["Weekly Sprint Job Framework","Weighted Shortest Job First: prioritizes work by dividing Cost of Delay by job size — maximizing value delivery at the program level","Work-Stream Job Function","Weekly Status, Job, and Forecast"],"a":1,"exp":"WSJF = Cost of Delay / Job Size. Cost of Delay = Business Value + Time Criticality + Risk Reduction. This ensures the team works on the highest-value items relative to their size, maximizing throughput of business value.","competency":"ba:agile"},
{"q":"A stakeholder asks to add scope mid-sprint. The Agile BA''s correct response is to:","opts":["Add it immediately to make the stakeholder happy","Refuse all mid-sprint changes","Evaluate it with the product owner — if urgent, pull lower-priority work out; if not urgent, add to the backlog for future refinement","Escalate to the project manager"],"a":1,"exp":"Mid-sprint scope changes disrupt the team''s commitments. The Agile BA negotiates: assess urgency with the PO, trade off against committed sprint work if truly urgent, or backlog for the next sprint. Protect the sprint while respecting legitimate urgency.","competency":"ba:agile"},
{"q":"What distinguishes a feature from a user story in SAFe?","opts":["Features are bigger user stories with no structural difference","Features are for management; user stories are for developers","Features are program-level deliverables (delivering value to users) decomposed into multiple team-level user stories for implementation within a PI","Features are always technical; user stories are always business"],"a":2,"exp":"In SAFe: Features are owned at the program level (ART backlog), take 1 sprint to a full PI to deliver, and are decomposed into user stories for team-level delivery. BAs operate at both levels simultaneously.","competency":"ba:agile"}
]'::jsonb);

-- ── MODULE 17: Enterprise Architecture & Digital Transformation ───────────
SELECT pg_temp.fill_ba_exam_new(17, '[
{"q":"What are the four domains of the TOGAF Enterprise Architecture framework?","opts":["Strategy, People, Process, Technology","Business, Data, Application, Technology","Vision, Mission, Goals, Objectives","Plan, Build, Run, Govern"],"a":1,"exp":"TOGAF''s four architecture domains: Business (how the organization operates), Data (what data exists and how it flows), Application (what systems exist and integrate), Technology (infrastructure). BAs primarily work in Business Architecture but need literacy in all four.","competency":"ba:enterprise"},
{"q":"What is a business capability and how does it differ from a business process?","opts":["They are the same thing","A capability is WHAT the organization does (stable), a process is HOW it does it (changeable)","A capability is more detailed than a process","Processes are for IT; capabilities are for business"],"a":1,"exp":"Capabilities are stable over time: ''Customer Acquisition'' existed before the internet and will exist after AI. Processes change with technology and method. Capability maps endure; process maps become outdated as soon as the process changes.","competency":"ba:enterprise"},
{"q":"What does a business capability heat map communicate?","opts":["CPU and memory usage by system","Performance levels across capabilities — highlighting investment priorities, gaps, and transformation focus areas","Employee satisfaction scores","Project milestone status"],"a":1,"exp":"Heat maps overlay performance data (red/yellow/green) onto capability maps, making transformation priorities visible to executives. A heat map answers ''where should we invest?'' in a language executives understand without reading process documentation.","competency":"ba:enterprise"},
{"q":"What is the primary reason digital transformation programs fail?","opts":["Technology is too expensive","Underestimating the human and organizational change required alongside technology implementation","Poor software selection","Insufficient IT budget"],"a":1,"exp":"McKinsey research: 70% of digital transformations fail. The most common cause is underestimating change management — people do not change just because technology does. BAs who understand this build roadmaps that account for adoption, not just implementation.","competency":"ba:enterprise"},
{"q":"In enterprise architecture, what is a value stream?","opts":["The financial value of a software system","An end-to-end sequence of activities that creates value for an external customer — crossing multiple capabilities and departments","A revenue reporting structure","A project delivery process"],"a":1,"exp":"Value streams (e.g., ''Customer Onboarding,'' ''Order to Cash'') cut across organizational silos to show how value flows to customers. They are more useful than org charts for identifying transformation priorities because they reveal where handoffs break down.","competency":"ba:enterprise"},
{"q":"What is the TIME model in technology portfolio management?","opts":["Time, Investment, Migration, Elimination","Tolerate, Invest, Migrate, Eliminate — four categories for rationalizing a technology application portfolio","Track, Improve, Migrate, Expand","Test, Implement, Maintain, Evaluate"],"a":1,"exp":"TIME: Tolerate (low value, low quality, too expensive to change now), Invest (high value, good quality — build on these), Migrate (move to a better solution), Eliminate (decommission — no strategic value). BAs use TIME to structure rationalization business cases.","competency":"ba:enterprise"},
{"q":"What is total cost of ownership (TCO) for a software application?","opts":["Only the annual license fee","Only the implementation cost","License/subscription + infrastructure + internal support FTE + integration maintenance + security/compliance costs + business productivity impact","Only direct IT costs"],"a":2,"exp":"TCO includes all costs of operating an application. The license fee is often the smallest component. BAs who calculate full TCO build compelling rationalization business cases: a ''free'' legacy system often costs $500K-2M annually in support and productivity loss.","competency":"ba:enterprise"},
{"q":"When building a digital transformation roadmap, what is the most critical sequencing principle?","opts":["Tackle the highest-cost initiatives first","Always start with the longest timeline items","Platform capabilities (data, integration, identity) before differentiation capabilities — you cannot build on an unstable foundation","Start with the most visible customer-facing features first, always"],"a":2,"exp":"Foundation-first sequencing prevents the common failure mode of building differentiated capabilities on a broken foundation. A new customer portal built on a fragmented customer data architecture will fail regardless of its UX quality.","competency":"ba:enterprise"},
{"q":"What distinguishes a transformation roadmap from a project plan?","opts":["They are the same document with different names","A roadmap is a strategic communication of direction and sequence with confidence levels; a project plan is a detailed execution schedule","A roadmap is more detailed than a project plan","Project plans are for IT; roadmaps are for business"],"a":1,"exp":"Roadmaps communicate direction: ''Now/Next/Later'' with confidence levels. Project plans commit to specific dates. Treating a roadmap as a commitment creates conflict when (not if) priorities change. BAs must communicate this distinction to stakeholders.","competency":"ba:enterprise"},
{"q":"What is Kotter''s first step in the 8-step change model and why is it critical for transformation?","opts":["Build a guiding coalition","Create short-term wins","Create a sense of urgency — without it, transformation competes with day-to-day operations and loses","Form a strategic vision"],"a":2,"exp":"Without urgency, people protect their current workloads over transformation activities. Urgency is not panic — it is a shared understanding of why the organization must change now. BAs contribute by making the cost of inaction visible and quantified.","competency":"ba:enterprise"},
{"q":"What is a business case for a digital transformation initiative?","opts":["A financial spreadsheet only","A technical requirements document","A structured argument connecting problem, solution options, costs, quantified benefits, risks, and a recommended course of action","A project charter"],"a":2,"exp":"A BA business case: problem (cost of current state), solution options (with trade-offs), costs (TCO for each option), benefits (quantified, time-phased), risks (probability × impact), recommendation. Executives use it to make go/no-go investment decisions.","competency":"ba:enterprise"},
{"q":"What is a capability gap analysis?","opts":["A gap in system documentation","The difference between current-state capability performance and the target performance required by the business strategy","A list of missing software features","A skills gap assessment for employees"],"a":1,"exp":"Capability gap analysis: ''We need loan origination in 1 day (strategic requirement) but currently achieve 5 days with 12% error rate (current state). The gap drives the initiatives, technology selection, and process redesign required.''","competency":"ba:enterprise"},
{"q":"What is the make/buy/partner decision in enterprise architecture?","opts":["A vendor negotiation technique","A build vs configure decision only","The strategic choice between building custom software, buying a packaged solution, or using a third-party provider to deliver a business capability","A team hiring decision"],"a":2,"exp":"Make/buy/partner: Make = maximum fit, maximum cost/risk. Buy = faster, less risk, requires process adaptation. Partner = fastest, creates vendor dependency. BAs evaluate: strategic differentiation of the capability × fit of available solutions × internal build capability.","competency":"ba:enterprise"},
{"q":"What is the role of an executive sponsor in digital transformation?","opts":["Approving invoices","Writing the requirements","Providing authority, removing cross-organizational barriers, and visibly championing the transformation — the single biggest predictor of transformation success","Attending all project meetings"],"a":2,"exp":"Without an active sponsor: transformation stalls at organizational boundaries, funding disappears when priorities shift, and middle management resistance wins. The BA''s role is to make it easy for the sponsor to sponsor: pre-briefed, armed with decisions to make, and connected to outcomes.","competency":"ba:enterprise"},
{"q":"What are outcome metrics in digital transformation measurement?","opts":["Milestones delivered on time","Stories completed per sprint","Business value delivered: revenue generated, costs reduced, customer satisfaction improved, time saved — the metrics executives actually care about","Systems deployed and users trained"],"a":2,"exp":"Output metrics (milestones, stories, systems deployed) measure activity. Outcome metrics measure impact. A transformation that deploys on time but delivers no measurable business improvement has failed, regardless of output metrics. BAs push for outcome measurement from day one.","competency":"ba:enterprise"}
]'::jsonb);

-- ── MODULE 18: BA Career Acceleration & Portfolio ─────────────────────────
SELECT pg_temp.fill_ba_exam_new(18, '[
{"q":"What are the experience requirements for CBAP certification?","opts":["3 years of any business experience","5,000 hours of BA work in any timeframe","7,500 hours of BA experience in the last 10 years, with 900 hours minimum in at least 4 of 6 BABOK Knowledge Areas","Any professional experience with a BA job title"],"a":2,"exp":"CBAP requires significant BA-specific experience. The 10-year lookback means recent experience is required. The 900-hour minimum per KA ensures breadth across BABOK''s knowledge framework, not just one area of BA practice.","competency":"ba:career"},
{"q":"How does PMI-PBA differ from CBAP?","opts":["PMI-PBA is more advanced than CBAP","They are identical certifications from different bodies","PMI-PBA is PM-centric, emphasizing BA activities within project management contexts; CBAP covers all BA contexts with broader BABOK focus","CBAP is only for IT BAs; PMI-PBA is for all industries"],"a":2,"exp":"PMI-PBA aligns BA practice to PMI''s project management lifecycle. It is the natural choice for PMP holders and BAs in project-structured organizations. CBAP covers a broader range of BA contexts including operations, product, and consulting.","competency":"ba:career"},
{"q":"What is the strongest LinkedIn headline strategy for a Business Analyst?","opts":["Just your current job title","Business Analyst | [Specialization] | [Top skills/certifications] — keyword-rich and specific","Your most recent company name","A creative personal brand statement with no keywords"],"a":1,"exp":"LinkedIn''s algorithm surfaces profiles matching recruiter searches. ''Business Analyst'' alone is too generic. ''AI Business Analyst | Requirements Engineering & Digital Transformation | CBAP | FinTech'' ranks for relevant searches and immediately communicates value.","competency":"ba:career"},
{"q":"What is the most effective way to quantify BA impact on a resume?","opts":["List all tools used","Use vague language to avoid making specific claims","Connect actions to measurable outcomes: ''Facilitated 12 stakeholder workshops across 4 business units → requirements approved 3 weeks early → project delivered on time''","Focus on responsibilities, not results"],"a":2,"exp":"Hiring managers scan for outcomes, not activities. Every BA ''gathered requirements.'' Few BAs document that their requirements quality improvement reduced sprint rework by 40%, or that their stakeholder alignment enabled an early go-live. Outcomes differentiate.","competency":"ba:career"},
{"q":"What is the primary purpose of a BA portfolio?","opts":["To replace the resume","To demonstrate actual work quality through concrete artifacts and case studies — showing hiring managers what you produce, not just what you claim","To list all projects you have worked on","To show the number of projects completed"],"a":1,"exp":"A portfolio converts abstract resume claims into evidence. ''Managed stakeholder relationships'' is a claim. A stakeholder analysis document with a case study explaining the challenge, approach, and outcome is proof. Portfolios win shortlists.","competency":"ba:career"},
{"q":"What is the correct salary negotiation sequence when receiving a job offer?","opts":["Accept the first offer to demonstrate enthusiasm","Negotiate only salary, not total compensation","Request 48 hours to review, research the market, counter with a specific number at the top of your range, and negotiate total compensation if base salary is fixed","Always reject the first offer regardless of amount"],"a":2,"exp":"Negotiation sequence: request time to review (48h), research the market (Glassdoor, levels.fyi, LinkedIn Salary), counter with a specific ask grounded in market data, and if base is fixed, negotiate signing bonus, additional PTO, or training budget.","competency":"ba:career"},
{"q":"Which BA specialization currently commands the highest salary premium?","opts":["General IT BA","Documentation specialist","AI/ML BA (15-25% premium) — defining requirements for AI/ML systems requires unique skills that are in high demand and short supply","Requirements-only BA"],"a":2,"exp":"AI/ML BAs specify training data, accuracy thresholds, fairness criteria, and explainability requirements — skills most BAs do not have. The combination of BA fundamentals + AI domain knowledge commands a significant market premium.","competency":"ba:career"},
{"q":"What is the most important element of a BA portfolio case study?","opts":["The length of the document","The technical tools used","The outcome: what changed because of your BA work, quantified where possible","The number of stakeholders involved"],"a":2,"exp":"Hiring managers care about: ''Did this BA''s work make a difference?'' Context without outcome is a story. Outcome without context is a claim. The combination — here is what I faced, here is what I did, here is what resulted — is evidence of impact.","competency":"ba:career"},
{"q":"What is the freelance BA career path, and when is it most viable?","opts":["Freelance BA is the entry-level path into BA","Freelance is only for BAs who cannot find employment","Freelance BA (independent contractor) is most viable after 8-10 years of in-house and consulting experience — when you have the network, reputation, and credentials to attract clients continuously","Freelance BAs earn less than employed BAs"],"a":2,"exp":"Freelance success depends on reputation, network, and credentials built over years. Day rates for experienced freelance BAs ($800-2,000/day) exceed most salaried positions, but feast/famine cycles require marketing discipline and financial reserves.","competency":"ba:career"},
{"q":"What AI tools should every modern BA be proficient with?","opts":["Only Microsoft Office tools","AI tools are not relevant for BAs","LLMs for requirements generation (ChatGPT/Claude), meeting intelligence tools (Otter.ai/Fireflies), AI diagramming tools, and AI prototyping tools (Figma AI/v0.dev)","Only project management tools like Jira"],"a":2,"exp":"AI fluency is becoming a baseline BA expectation. BAs who use AI to generate first-draft user stories, extract requirements from meeting transcripts, and produce process diagrams in minutes outcompete those who do everything manually.","competency":"ba:career"},
{"q":"How should a BA anonymize portfolio artifacts from confidential projects?","opts":["Share them as-is — it demonstrates real experience","Never share any work artifacts","Replace company names with industry descriptors, individual names with roles, specific financials with ranges, and obtain written permission for artifacts from current employers","Only share artifacts from past employers, not current ones"],"a":2,"exp":"Confidentiality obligations survive employment. Replace identifiers: ''ACME Bank'' becomes ''a global retail bank''; ''James Richardson (CFO)'' becomes ''the CFO''; ''$47M project'' becomes ''a $40-50M transformation.'' The substance of your work remains visible without breaching confidentiality.","competency":"ba:career"},
{"q":"What is the consulting BA career path and its primary trade-off?","opts":["Consulting BAs earn less than in-house BAs","Consulting provides maximum exposure and accelerated learning but requires accepting billable hour pressure, client dependency, and often extensive travel","Consulting is only for junior BAs","Consulting BAs do not need technical skills"],"a":1,"exp":"Big 4 and Tier 1 consulting firms pay 20-40% above in-house BA rates and provide exposure to multiple industries in accelerating succession. The trade-off: billable pressure, client dependency, and always-on culture. Most senior freelance BAs have a consulting chapter in their career.","competency":"ba:career"},
{"q":"What parts of BA work is AI least likely to automate?","opts":["Documentation and template completion","Political judgment in stakeholder conflicts, organizational context that shapes requirements, relationship building with resistant stakeholders, and ethical assessment of AI systems","User story writing","Meeting facilitation entirely"],"a":1,"exp":"AI automates the document-production parts of BA work. The judgment, political navigation, relationship trust, organizational context, and ethical reasoning that define elite BA work require human intelligence. BAs who develop these skills are AI-proof.","competency":"ba:career"},
{"q":"What is thought leadership for BAs and why does it matter for career growth?","opts":["Writing academic papers only","A technique only for BA managers","Publishing insights, lessons, and perspectives on BA practice (LinkedIn, blogs, speaking) that demonstrate expertise, build network, and attract opportunities","Becoming a BA certification instructor"],"a":2,"exp":"BAs who share their knowledge publicly become known in their field. Recruiters find them. Clients seek them out. Conference invitations follow. Thought leadership converts expertise into reputation, which converts reputation into opportunity.","competency":"ba:career"},
{"q":"What is the recommended 12-month career acceleration plan for a BA targeting a senior role?","opts":["Apply for senior roles immediately without additional preparation","Focus only on CBAP certification","AI tool proficiency → specialization selection → portfolio documentation → certification application → LinkedIn optimization and thought leadership → targeted applications to stretch roles","Wait for organic promotion opportunities"],"a":2,"exp":"Career acceleration requires deliberate action across multiple dimensions simultaneously: skill development (AI tools), specialization (depth), proof (portfolio), credentials (certification), visibility (LinkedIn/community), and targeting (specific stretch roles). Organic promotion is slower and less directed.","competency":"ba:career"}
]'::jsonb);

-- Verification
SELECT ch.order_index, ch.title, COUNT(qq.id) as question_count
FROM public.quiz_questions qq
JOIN public.quizzes qz ON qq.quiz_id = qz.id
JOIN public.chapters ch ON qz.chapter_id = ch.id
JOIN public.courses co ON ch.course_id = co.id
WHERE co.title = 'AI Business Analyst & Product Discovery Specialist'
  AND ch.order_index IN (16, 17, 18)
GROUP BY ch.order_index, ch.title
ORDER BY ch.order_index;
-- Expected: 3 rows, each with question_count = 15
