import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { requireAdmin } from "../_shared/adminGuard.ts";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const courseData = {
  "title": "AI MLOps Engineer",
  "description": "Master the full MLOps lifecycle: experiment tracking, model deployment, drift detection, CI/CD for ML, and the production reliability practices used at Spotify, Airbnb, and DoorDash.",
  "translations": {"es": {"title": "AI MLOps Engineer", "description": "Master the full MLOps lifecycle: experiment tracking, model deployment, drift detection, CI/CD for ML, and the production reliability practices used at Spotify, Airbnb, and DoorDash."}, "fr": {"title": "AI MLOps Engineer", "description": "Master the full MLOps lifecycle: experiment tracking, model deployment, drift detection, CI/CD for ML, and the production reliability practices used at Spotify, Airbnb, and DoorDash."}, "de": {"title": "AI MLOps Engineer", "description": "Master the full MLOps lifecycle: experiment tracking, model deployment, drift detection, CI/CD for ML, and the production reliability practices used at Spotify, Airbnb, and DoorDash."}, "zh": {"title": "AI MLOps Engineer", "description": "Master the full MLOps lifecycle: experiment tracking, model deployment, drift detection, CI/CD for ML, and the production reliability practices used at Spotify, Airbnb, and DoorDash."}, "ar": {"title": "AI MLOps Engineer", "description": "Master the full MLOps lifecycle: experiment tracking, model deployment, drift detection, CI/CD for ML, and the production reliability practices used at Spotify, Airbnb, and DoorDash."}, "ja": {"title": "AI MLOps Engineer", "description": "Master the full MLOps lifecycle: experiment tracking, model deployment, drift detection, CI/CD for ML, and the production reliability practices used at Spotify, Airbnb, and DoorDash."}},
  "modules": [
  {"title": "Module 1: MLOps Foundations, Experiment Tracking, and the Production ML Gap", "desc": "Why 87% of ML models never reach production, the Hidden Technical Debt paper's revelations, MLOps maturity levels, and the experiment tracking discipline that makes ML reproducible.", "lessons": [
    {"title": "1.1 Hidden Technical Debt in ML Systems: Why Production ML is Harder Than Research", "desc": "Sculley et al.'s landmark NeurIPS 2015 paper, the production ML gap, and why ML code is only a tiny fraction of real ML system complexity."},
    {"title": "1.2 Experiment Tracking and ML Reproducibility with MLflow and Weights & Biases", "desc": "Why every ML training run must be tracked, MLflow's architecture, W&B's advanced features, and the experiment management discipline that makes ML teams 10x more productive."},
    {"title": "1.3 Model Registry, Versioning, and Deployment Governance", "desc": "The model registry as single source of truth, semantic versioning for ML models, model cards, lineage tracking, and the approval workflows that satisfy both engineering and compliance requirements."},
    {"title": "1.4 Model Monitoring and Drift Detection: Catching Degradation Before Users Notice", "desc": "Statistical drift detection methods, prediction distribution monitoring, the PSI and KS test, Evidently AI, and the closed-loop retraining systems that keep production models accurate."},
    {"title": "1.5 MLOps Pipelines with Kubeflow and CI/CD for Machine Learning", "desc": "Kubeflow Pipelines architecture, containerized ML components, pipeline versioning, and the complete CI/CD for ML workflow that takes a code commit to a production model automatically."}
  ]},
  {"title": "Module 2: MLflow Deep Dive — Experiment Tracking, Model Registry, and Projects", "desc": "MLflow is the open-source MLOps platform used by thousands of production teams. Complete MLflow mastery: tracking APIs, autologging, model signatures, registry lifecycle, serving, and production deployment patterns.", "lessons": [
    {"title": "2.1 MLflow Tracking: Experiments, Runs, Parameters, Metrics, and Artifacts", "desc": "MLflow tracking API: mlflow.set_experiment(), mlflow.start_run(), mlflow.log_param(), mlflow.log_metric(), mlflow.log_artifact(). The run as the unit of ML reproducibility. Remote tracking server setup: MLflow server with Postgres backend and S3 artifact store — team-shared experiment database. Tags for organizational metadata. Case study: Databricks MLflow teams reduce model reproduction time fro"},
    {"title": "2.2 MLflow Autologging: Automatic Instrumentation for Sklearn, PyTorch, and XGBoost", "desc": "mlflow.sklearn.autolog() logs estimator parameters, training metrics, feature importances, and model artifact. mlflow.pytorch.autolog() logs optimizer params, training loss per epoch, gradient norms. mlflow.xgboost.autolog() logs booster params, feature importance, training curves. Customizing autolog: log_models, log_input_examples flags. Case study: Meta's production ML team uses autolog across "},
    {"title": "2.3 Model Signatures, Input Examples, and MLflow Model Format", "desc": "Model signatures define input/output schema — catching serving errors at deployment time. Input examples enable one-command local serving for validation. MLflow model flavors: native + python_function universal interface. Model registration with mlflow.register_model() creates registry versions with lineage back to training run. Case study: Netflix requires MLflow model signatures — preventing 15+"},
    {"title": "2.4 MLflow Model Registry: Lifecycle Management and Deployment Automation", "desc": "Registry workflow: registered → staging → production → archived. Transition triggers: CI/CD auto-promotes to Staging on quality gates, human approval for Production. Webhooks on stage transitions: Slack notification, automated deployment pipeline trigger. Model aliases (MLflow 2.0) for A/B testing. Case study: Coinbase uses MLflow Registry with 2-person approval for fraud detection production tran"},
    {"title": "2.5 MLflow Projects: Reproducible Training Environments", "desc": "MLproject file defines entry points, parameters, and environment (conda.yaml or Docker). Running projects locally or remotely. Databricks execution: mlflow run --backend databricks. Reproducibility guarantee: MLproject URI + run parameters + Git commit hash enables any engineer to reproduce any training run. Case study: Lyft requires all production models trained via MLflow Projects — any engineer"},
    {"title": "2.6 MLflow Serving and Model Deployment Patterns", "desc": "mlflow models serve provides REST API from any registered model. Batch scoring with mlflow models predict on Spark DataFrames. SageMaker deployment: mlflow.sagemaker.deploy(). Custom serving pattern: export model with mlflow.pyfunc, load in FastAPI endpoint. URI-based loading: mlflow.pyfunc.load_model('models:/fraud-detector/production') enables zero-config model updates. Case study: Shopify fraud"},
    {"title": "2.7 Module 2 Lab: Production MLflow Setup and Model Lifecycle", "desc": "Complete MLflow project: remote tracking server (Postgres + S3), training pipeline with autolog, model registration with signature, CI/CD quality gate workflow, Production approval flow, containerized REST API deployment."}
  ]},
  {"title": "Module 3: Model Monitoring and Drift Detection in Production", "desc": "Models degrade silently — drift detection catches deterioration before users notice. Statistical drift tests, Evidently AI, feature monitoring, prediction quality tracking, and monitoring stacks at Spotify, Faire, and Booking.com.", "lessons": [
    {"title": "3.1 The Four Types of ML Model Drift: Data, Concept, Feature, and Label", "desc": "Data drift (covariate shift): input feature distributions change. Concept drift: relationship between features and labels changes. Feature drift: specific features drift while overall distribution is stable. Label drift: ground truth label distribution changes. Detection cadence: data drift (real-time), concept drift (weekly evaluation), feature drift (per-materialization). Case study: Spotify's r"},
    {"title": "3.2 Statistical Tests for Drift Detection: PSI, KS Test, and Jensen-Shannon Divergence", "desc": "Population Stability Index (PSI): PSI < 0.1 (no drift), 0.1-0.2 (investigate), >0.2 (significant drift, retrain). Kolmogorov-Smirnov test for continuous features. Jensen-Shannon divergence, bounded [0,1]. Chi-squared test for categorical features. Multiple testing correction (Bonferroni) for 100+ features. Case study: LinkedIn's drift monitoring computes PSI for 500+ features daily, alerting when "},
    {"title": "3.3 Evidently AI: Production Model and Data Monitoring", "desc": "Evidently reports: DataDriftPreset, DataQualityPreset, RegressionPreset, ClassificationPreset. Test suites for automated alerting: TestDataDrift, TestColumnDrift with configurable thresholds. Airflow integration: Evidently TestSuite as a DAG task. MLflow integration: log Evidently reports as artifacts. Case study: Faire uses Evidently to monitor 200+ features, catching distribution shifts that pre"},
    {"title": "3.4 Prediction Monitoring: Output Distributions and Business Metrics", "desc": "Prediction distribution monitoring: track model score distributions — systematic shifts indicate model making different decisions. Calibration monitoring: Expected Calibration Error for probability models. Business metric correlation: connect predictions to downstream outcomes. Delayed feedback patterns: design monitoring for label lag. Shadow mode monitoring: compare new vs. production model dist"},
    {"title": "3.5 Automated Retraining Pipelines: Triggers, Quality Gates, and Champion-Challenger", "desc": "Trigger types: time-based, drift-triggered (PSI > 0.2), performance-triggered (accuracy drop), data-volume-triggered. Quality gates: new model must exceed champion on primary metric, guardrail metrics (latency, fairness) within bounds. Champion-challenger: challenger in shadow mode for 24 hours, auto-promote if wins without guardrail violations. Case study: Instacart's retraining triggers at PSI >"},
    {"title": "3.6 Fairness and Bias Monitoring for Production ML Systems", "desc": "Fairness metrics: Demographic Parity, Equalized Odds, Individual Fairness. Production monitoring: compute fairness metrics on each evaluation batch. The bias-accuracy tradeoff: document explicitly. Sliced evaluation: evaluate across protected attribute subgroups — 95% overall accuracy can hide 70% minority subgroup accuracy. Fairlearn and AI Fairness 360 frameworks. Case study: Amazon's hiring mod"},
    {"title": "3.7 Module 3 Assessment: Design a Model Monitoring System", "desc": "Design the complete monitoring system for a credit scoring model: drift detection strategy, retraining trigger logic, fairness monitoring across protected attributes, alerting hierarchy, runbooks per alert type, and performance dashboard with data flow from prediction to monitoring."}
  ]},
  {"title": "Module 4: Kubeflow and ML Pipeline Orchestration", "desc": "Kubeflow Pipelines is the Kubernetes-native ML workflow platform. Pipeline SDK, components, caching, artifact tracking, hyperparameter tuning with Katib, and production patterns at Google, Airbus, and Mercedes-Benz.", "lessons": [
    {"title": "4.1 Kubeflow Pipelines Architecture: Components, Runs, and the Argo Workflows Backend", "desc": "KFP v2: Pipeline SDK, Argo Workflows backend, ML Metadata store, Pipeline UI. The component as the unit of reuse: @dsl.component decorator creates containerized pipeline steps with typed inputs/outputs. Caching skips already-completed components with identical inputs. Case study: Vertex AI Pipelines processes 100,000+ pipeline runs daily across Google's internal ML teams."},
    {"title": "4.2 Building KFP Components: Python Functions, Containers, and Artifact Passing", "desc": "Lightweight Python components: @dsl.component with base_image and packages_to_install. Container-based components for complex dependencies. Typed artifacts: Input[Dataset], Output[Model], Input[Metrics] — KFP manages URIs and lineage. Artifact visualization in Pipeline UI. Component library pattern: 40 reusable components for data validation, feature engineering, evaluation. Case study: Airbus MLO"},
    {"title": "4.3 Pipeline Conditionals, Loops, and Dynamic Pipelines", "desc": "Conditional execution: dsl.If(evaluation.outputs['accuracy'] > 0.95). Parallel for loops: dsl.ParallelFor for training multiple model types simultaneously. ExitHandler for always-run cleanup. Dynamic configurations via pipeline parameters enable ML engineer customization without code changes. Case study: Lyft's parallel training cuts 12 model configuration training time from 12 hours to 2.5 hours."},
    {"title": "4.4 Hyperparameter Tuning with Katib: Bayesian Optimization at Scale", "desc": "Katib: Experiment (search space + objective), Trial (single run), Suggestion algorithm. Search algorithms: Grid, Random, Bayesian Optimization (Gaussian Process), Hyperband (early stopping), Neural Architecture Search. KFP integration: embed Katib Experiment as a pipeline component. Case study: Google AutoML uses Bayesian optimization to find configurations that would take researchers weeks to dis"},
    {"title": "4.5 ML Metadata and Lineage Tracking with MLMD", "desc": "MLMD concepts: Artifact (typed data object), Execution (component run), Context (grouping). Lineage queries: which models trained on this dataset? What data produced this production model? Compliance value for EU AI Act. MLMD Python client for custom scripts. KFP UI renders lineage graphs with upstream/downstream visualization. Case study: Vertex AI MLMD enables rapid root cause analysis for model"},
    {"title": "4.6 Vertex AI Pipelines: Managed Kubeflow on GCP", "desc": "Vertex AI Pipelines: no cluster management, pay-per-pipeline-run. Auto-integration with Vertex AI Training, Model Registry, Feature Store, BigQuery. Pipeline scheduling via Cloud Scheduler, event-triggered via Pub/Sub. Cost optimization: cached components save compute. Comparison: Vertex AI costs 30-50% more than self-hosted KFP but eliminates 2-3 months platform engineering. Case study: Wayfair r"},
    {"title": "4.7 Module 4 Lab: Production ML Pipeline with KFP", "desc": "End-to-end KFP pipeline: 6 components (data validation, feature engineering, training, evaluation with quality gates, MLflow registration, conditional deployment). Katib hyperparameter sweep as pipeline step. Caching behavior testing. Deploy to Kubernetes with KFP installed."}
  ]},
  {"title": "Module 5: Feature Stores for MLOps — Feast, Tecton, and Production Patterns", "desc": "Feature stores are the MLOps infrastructure investment with highest leverage. Training-serving skew elimination, point-in-time correctness, online/offline parity, and architectures at Uber, Twitter, and Airbnb.", "lessons": [
    {"title": "5.1 The Feature Store Problem: Why Training-Serving Skew Kills Production Models", "desc": "Training-serving skew root causes: different code (pandas vs. Java), different data sources, different preprocessing logic. Feature store solution: one definition, two environments — consistency by construction. Uber Michelangelo (2017): shared features reduced time-to-production by 60%, eliminated 40% of production ML bugs. Morgan Stanley estimate: training-serving skew costs $4B+ in poor trading"},
    {"title": "5.2 Feast Production Deployment: Architecture, Configuration, and Operations", "desc": "Registry backends: file (dev), SQL (team-shared), S3/GCS (object store). Offline stores: BigQuery, Snowflake, Redshift, Spark. Online stores: Redis (P99 < 3ms), DynamoDB, Bigtable. Feature server: HTTP or gRPC. Operational: materialize-incremental for online store updates, freshness monitoring, Redis capacity planning. Case study: Robinhood Feast serves 300K feature lookups/second at P99 < 3ms."},
    {"title": "5.3 Advanced Feature Engineering: On-Demand, Streaming, and Cross-Entity Features", "desc": "On-demand features: computed at serving time from request context (current_hour_of_day, days_since_signup). Streaming features: real-time event stream computation materialized continuously (purchases in last 5 minutes from Kafka). Cross-entity features: join across entity types (average order value for user's city). Embedding features for recommendation models. Batch entity lookup optimization: 10"},
    {"title": "5.4 Feature Versioning, Backfill, and Time-Travel for Reproducibility", "desc": "Feature versioning: every definition change creates a new version linked in model training metadata. Backfill for new/corrected features with historical date computation. Time-travel queries: retrieve feature values as of any past timestamp. Online store TTL: staleness protection for serving. Delta Lake/Iceberg time travel for training data generation. Case study: Waymo uses time-travel to investi"},
    {"title": "5.5 Tecton: Managed Feature Platform for Enterprise MLOps", "desc": "Tecton differentiators: managed infrastructure, native streaming features, Python transformation with auto batch/streaming/realtime execution, built-in monitoring, enterprise governance (RBAC, audit, lineage). Feature View types: BatchFeatureView, StreamFeatureView, OnDemandFeatureView. Cost model: economic when teams spend >$15K/month on platform labor. Case study: Comcast migrated from self-host"},
    {"title": "5.6 Feature Store Governance: Discovery, Reuse, and Cross-Team Collaboration", "desc": "Feature discovery: searchable catalog with name, description, owner, freshness, consumers. Feature reuse metrics: Netflix reports 30-50% reuse rate. Feature ownership and SLAs: owning team responsible for freshness and quality. Feature deprecation: zero-consumer features after 90 days are candidates. ROI calculation: compute hours saved by reuse vs. platform investment. Case study: Spotify 400+ fe"},
    {"title": "5.7 Module 5 Assessment: Feature Store Architecture Design", "desc": "Design complete feature store for a fintech app with 8 ML models: entities, feature views, data sources, online/offline stores, streaming vs. batch strategy, freshness SLAs per model, and governance model for feature discovery and reuse."}
  ]},
  {"title": "Module 6: LLMOps — Operating Large Language Models in Production", "desc": "LLMs require a specialized MLOps practice. Prompt versioning, RAG monitoring, fine-tuning workflows, evaluation frameworks, cost management, and LLMOps practices at Anthropic, OpenAI, and Cohere.", "lessons": [
    {"title": "6.1 LLMOps vs. Classical MLOps: What's Different and What Carries Over", "desc": "What's different: model is often a 3rd-party API, artifact is the prompt + config, evaluation is subjective (LLM-as-judge), cost is token-based, latency is 1-10s. What carries over: versioning (prompts are code), A/B testing, monitoring, CI/CD. Case study: Intercom's LLMOps: prompt versioning in Git, automated evaluation on 500 golden examples, staged rollout with quality gates."},
    {"title": "6.2 Prompt Engineering and Prompt Management at Production Scale", "desc": "Prompt versioning in Git with commit messages explaining expected impact. Prompt registry: central repository with version history, performance metrics, deployment status. Jinja2 templating with typed variables for dynamic construction. A/B testing prompts: 5% traffic to new version, compare quality metrics. LangSmith and Promptflow for team prompt management. Case study: Klarna's 200+ versioned p"},
    {"title": "6.3 LLM Evaluation: LLM-as-Judge, RAGAS, and Golden Dataset Testing", "desc": "LLM-as-judge: use GPT-4/Claude to score outputs on rubrics — 85-90% agreement with human raters, scalable. RAGAS metrics: Context Precision, Context Recall, Answer Relevance, Faithfulness. Golden dataset testing: 200-500 curated input-output pairs as regression tests. Behavioral testing: specific assertions (never recommend competitors). Braintrust and Langfuse for evaluation infrastructure. Case "},
    {"title": "6.4 RAG Pipeline Monitoring and Optimization", "desc": "Retrieval monitoring: precision, recall, latency. Generation monitoring: faithfulness, hallucination rate, answer relevance. End-to-end: user satisfaction signals, escalation rate. Optimization: chunking strategy, embedding model, retrieval k, reranker model. A/B testing RAG configurations on production queries. Case study: Notion AI improved answer faithfulness from 72% to 91% through systematic "},
    {"title": "6.5 LLM Fine-Tuning MLOps: Data Curation, Training, and Quality Gates", "desc": "Data curation: quality over quantity — 1,000 curated > 100,000 noisy. Dataset versioning with DVC. Fine-tuning: LoRA/QLoRA (0.1% parameter tuning), Axolotl framework, Hugging Face TRL. Quality gates: capability benchmarks, golden dataset, safety evals before deployment. Case study: Anyscale's quality gate prevents 30% of fine-tuned models from deploying due to capability regressions."},
    {"title": "6.6 LLM Cost Management: Token Optimization and Model Routing", "desc": "Token counting: tiktoken for precise counting, max_tokens budget per request. Cascade architecture: GPT-4o-mini ($0.15/M) for simple queries, GPT-4o ($5/M) for complex reasoning. LLM classifier for request routing. LLMLingua for 3-5x prompt compression. Cost attribution tags: user, feature, model_version. Budget alerts at 80% consumption. Case study: Intercom reduced LLM API costs by 73% through m"},
    {"title": "6.7 Module 6 Lab: Production LLMOps Pipeline", "desc": "Build complete LLMOps pipeline: RAG system with versioned prompts, RAGAS evaluation on golden dataset, LLM-as-judge quality gate in CI/CD, model routing (GPT-4o-mini/GPT-4o), token cost tracking, monitoring dashboards for retrieval quality, faithfulness, and cost per query."}
  ]},
  {"title": "Module 7: Advanced CI/CD for ML — Testing, Deployment, and Rollback", "desc": "ML CI/CD tests model artifacts, not just code. Shadow mode, quality gates, rollback strategies, and deployment pipelines at Airbnb, Netflix, and Stripe.", "lessons": [
    {"title": "7.1 The ML Testing Pyramid: Unit, Integration, Performance, and Model Tests", "desc": "Unit tests: preprocessing functions, utilities — milliseconds. Integration tests: end-to-end pipeline on small datasets, schema verification. Performance tests: inference latency benchmarks vs. SLO thresholds. Model quality tests: holdout set accuracy/F1/AUC thresholds. Behavioral tests: fraud model must classify known fraud as fraud. Differential testing: new model matches old model on >90% of te"},
    {"title": "7.2 Model Validation Pipelines: Automated Quality Gates", "desc": "Quality gate layers: training data validation (Great Expectations), convergence checks, evaluation dataset performance, serving infrastructure checks, shadow mode smoke test. Gate configuration in versioned YAML. Hard gates (block deployment) vs. soft gates (warn only). Case study: Stripe's quality gates blocked 23% of model updates, preventing estimated $2M+ in incident costs."},
    {"title": "7.3 Blue-Green and Canary Deployments for ML Models", "desc": "Blue-green: full new model deployed alongside old, instant cutover via load balancer, instant rollback. Canary: 1% → 5% → 20% → 50% → 100% with validation at each stage. Argo Rollouts AnalysisTemplate: auto-promote or auto-rollback based on Prometheus metrics. MLflow registry integration: canary controlled by model version tags. Case study: LinkedIn runs 50+ simultaneous canary deployments with au"},
    {"title": "7.4 Rollback Strategies: Fast, Safe Recovery", "desc": "Rollback triggers: automated (Argo Rollouts analysis, < 5 minutes), semi-automated (alert + one-click engineer approval), manual (delayed degradation). Rollback runbook: who is authorized, how to verify, post-rollback communication. Version pinning: serving infrastructure pins to specific model URI. Database/feature store compatibility: coordinate schema changes with blue-green. Case study: Netfli"},
    {"title": "7.5 Model Versioning and Artifact Management with DVC and MLflow", "desc": "DVC: Git extension for large file versioning (S3/GCS backend). dvc add for datasets, dvc push/pull for remote sync. DVC pipelines: dvc.yaml for transformation and training steps. Full versioning stack: Git (code), DVC (data/models), MLflow (experiments/metrics), model registry (deployment versions). Reproducibility guarantee: registry record enables anyone to reproduce training environment, data v"},
    {"title": "7.6 Multi-Environment ML Deployments: Dev, Staging, Production Parity", "desc": "Environment parity: same Kubernetes infrastructure, same containers, same feature store (populated from production data snapshots), same schemas. Environment promotion checklist. The staging trap: tests that don't represent production load miss concurrency bugs. IaC parameterized by environment: dev (1 GPU, 1 replica) vs. prod (10 GPUs, autoscaling to 50). Case study: Booking.com staging processes"},
    {"title": "7.7 Module 7 Assessment: ML Deployment Pipeline Design", "desc": "Design complete CI/CD pipeline for a recommendation model: test pyramid with specific thresholds, canary configuration with automated analysis, rollback strategy with trigger conditions and RTO, artifact versioning stack, multi-environment configuration. Include pipeline YAML and rollback runbook."}
  ]},
  {"title": "Module 8: MLOps for Large-Scale Systems — Distributed Training and Serving", "desc": "At Google, Meta, and OpenAI scale, ML requires distributed training across thousands of GPUs. Data parallelism, model parallelism, DeepSpeed, and high-throughput serving architectures.", "lessons": [
    {"title": "8.1 Distributed Training Fundamentals: Data Parallelism and Model Parallelism", "desc": "Data parallelism: identical model copies on each GPU, gradient averaging via NCCL. PyTorch DDP: gradient bucketing for communication efficiency. Model parallelism: split model across GPUs for memory-bound models (LLaMA-70B needs 140GB). Tensor parallelism: split matrix multiplications (Megatron-LM). Pipeline parallelism: split by layer groups (GPipe, PipeDream). Case study: Meta LLaMA-2 trained wi"},
    {"title": "8.2 DeepSpeed ZeRO: Memory-Efficient Distributed Training", "desc": "ZeRO Stage 1: partition optimizer states (8x memory reduction). Stage 2: partition gradients. Stage 3: partition model parameters (train arbitrarily large models). ZeRO-Infinity: offload to CPU RAM and NVMe. DeepSpeed JSON config file. Hugging Face Trainer integration: one-line deepspeed config. Case study: Microsoft Turing-NLG (530B parameters) trained with ZeRO-3 across 560 A100 GPUs."},
    {"title": "8.3 Gradient Accumulation, Mixed Precision, and Training Efficiency", "desc": "Gradient accumulation: simulate large batches on memory-constrained GPUs. AMP: FP16 activations (2x memory, 2x throughput), FP32 master weights. BF16 vs FP16: BF16 more numerically stable for LLMs, supported on A100/H100. Flash Attention: 3x faster attention, 10x memory reduction for long sequences. Gradient checkpointing: recompute activations vs. store them. Case study: AMP + Flash Attention red"},
    {"title": "8.4 High-Throughput Inference: vLLM, TensorRT, and Continuous Batching", "desc": "vLLM PagedAttention: KV cache as virtual memory pages, 24x more concurrent users. Continuous batching: dynamic request addition, GPU utilization from 30% to 85%. NVIDIA TensorRT: 2-4x throughput for traditional deep learning. TensorRT-LLM: INT8/INT4 quantization for LLMs. Speculative decoding: 2-3x throughput improvement. Triton Inference Server: multi-model serving standard. Case study: Meta uses"},
    {"title": "8.5 MLOps at Billion-Prediction Scale: Reliability and Efficiency", "desc": "Prediction caching: LinkedIn caches 40% of recommendation inferences, saving 40% GPU compute. Model compression pipeline: automated quantization and pruning loop. Multi-model serving efficiency: Triton model concurrency serves 20+ models per GPU cluster. 0.1% error rate at 1B/day = 1M failed predictions — reliability investment proportional to volume. Case study: TikTok processes 2B predictions/ho"},
    {"title": "8.6 Multi-Model Architectures: Ensembles, Cascades, and Mixture of Experts", "desc": "Ensemble serving: 2-5% accuracy improvement from combining models. Cascade: cheap/fast model for easy cases, expensive/accurate for hard. Routing logic: lightweight classifier determines model tier — used by GPT-4, Gemini, Claude. MoE: Mixtral 8x7B — 8 experts, 2 selected per token. MLOps complexity: coordinated versioning, latency budgets, failure handling. Case study: Google's ranking uses 12-mo"},
    {"title": "8.7 Module 8 Assessment: Distributed Training and Serving Architecture", "desc": "Design distributed training and serving for a 13B parameter language model: GPU cluster config, parallelism strategy, DeepSpeed ZeRO stage, mixed precision, checkpointing. For serving: vLLM config, quantization, expected throughput at 1M requests/day, autoscaling, cost estimate."}
  ]},
  {"title": "Module 9: MLOps Platform Engineering — Self-Service ML Infrastructure", "desc": "Building the internal ML platform enabling 100 ML engineers to work independently. Developer portals, self-service training, compute orchestration, and platform engineering practices at LinkedIn, Pinterest, and Shopify.", "lessons": [
    {"title": "9.1 The Internal ML Platform: Why and What to Build", "desc": "Platform enables ML engineers to work without Kubernetes/DevOps expertise. ROI: 50-person team without platform spends 30-40% time on infra — with mature platform, 5-10%. Build differentiating tools (custom evaluation, domain feature stores), buy commodity (cloud ML services, MLflow). Maturity levels: 0 (no platform) → 3 (full self-service with governance). Case study: LinkedIn's 50 platform engin"},
    {"title": "9.2 Self-Service Training Infrastructure: Job Submission, Queuing, and Priority", "desc": "Python SDK: ml_platform.submit_training_job(config=TrainingConfig(gpu_count=8, priority='research')). Fairshare scheduling, priority queues, preemption (production retraining preempts research). Job packaging: ML engineers specify Python function or Docker image, platform generates Kubernetes Job. Per-job monitoring: GPU utilization, training loss, ETA via portal. Spot instance management with aut"},
    {"title": "9.3 Experiment Management at Scale: Organizing 10,000 Runs", "desc": "Taxonomy: Project → Experiment Group → Experiment → Run. Mandatory tags: team, model_type, dataset_version, author. Experiment templates for common model types. Cross-experiment comparison and statistical significance testing. Lifecycle: active → completed → archived (metrics retained, artifacts deleted). Searchable catalog prevents re-doing completed work. Case study: Weights & Biases hosts 500M+"},
    {"title": "9.4 Model Governance: Approval Workflows, Access Control, and Audit Logging", "desc": "Approval workflows: model owner + technical reviewer + compliance sign-off for regulated industries. RBAC: ML engineer (train/register), approver (promote to prod), auditor (read-only). Audit logging: all changes in WORM storage for tamper-proof compliance. Model cards: mandatory documentation for every production model. EU AI Act Article 13: model cards + training data docs + MLMD lineage = compl"},
    {"title": "9.5 Developer Experience: Golden Paths, Templates, and Documentation", "desc": "Golden paths: opinionated, well-maintained paths reducing choices and cognitive load. Python SDK: ml.train(model_fn, dataset, config) — one call handles distributed training, checkpointing, MLflow, registration. Scaffolding: ml-platform new-project --type classification generates complete repository. Backstage TechDocs for versioned documentation. Platform NPS: quarterly 10-question survey. The pa"},
    {"title": "9.6 Compute Cost Attribution and FinOps for ML Platforms", "desc": "Cost attribution: tag every pod with team/project/experiment, OpenCost for per-namespace costs, daily cost reports. Chargeback model: team GPU budget, monthly review, 80% alerts. Efficiency metrics: cost per training run, cost per deployed model, cost per million predictions. GPU utilization reporting: teams below 60% are over-provisioned. Case study: Lyft ML platform team reduced compute costs by"},
    {"title": "9.7 Module 9 Capstone: ML Platform Design Document", "desc": "Design complete ML platform for 100-person organization: self-service training infrastructure, experiment management, governance workflow with approval process, SDK API design, golden path templates, documentation plan, cost attribution model, and 12-month roadmap with quarterly milestones."}
  ]},
  {"title": "Module 10: MLOps Maturity, Organizational Practices, and Career Mastery", "desc": "Transforming ML organizations from ad-hoc to elite through the MLOps maturity model. Organizational design, executive communication, regulatory compliance, and your career from MLOps engineer to ML platform lead.", "lessons": [
    {"title": "10.1 The MLOps Maturity Model: From Level 0 to Level 4", "desc": "Google MLOps maturity: Level 0 (manual, 87% of enterprises) → Level 1 (pipeline automation, CT) → Level 2 (CI/CD automation) → Level 3 (automated feature engineering) → Level 4 (autonomous ML). Assessment: audit against each level's requirements, prioritize improvements by impact. Case study: Capital One progressed Level 0 to Level 2 in 18 months, reducing deployment time from 3 months to 2 weeks."},
    {"title": "10.2 Building the MLOps Practice: Team Structure and Organizational Design", "desc": "Team topologies: platform team (high leverage), embedded MLOps, center of excellence. MLOps-to-ML-engineer ratio: 1:5-10 (platform) vs. 1:1 (doesn't scale). Cross-functional: ML engineers, MLOps engineers, data engineers, ML PMs. Embedded vs. centralized tradeoff. On-call responsibility alignment. Case study: Airbnb's ML infrastructure: 30 platform engineers supporting 200 ML engineers — 6.7:1 rat"},
    {"title": "10.3 Communicating MLOps Value to Executive Stakeholders", "desc": "Translation framework: map capabilities to business outcomes. Experiment velocity in revenue impact. Time-to-production in competitive advantage. Reliability in avoided losses. ROI calculation: platform investment vs. (time saved + quality improvement + risk reduction). Executive presentation: current state → investment → outcomes → measurement. Case study: DoorDash secured $5M platform investment"},
    {"title": "10.4 MLOps Incident Management: Post-Mortems and Prevention", "desc": "ML incident types: silent degradation, serving failure, feature pipeline failure, training failure, data quality incident. Severity levels P0-P3. Blameless post-mortem structure: timeline, contributing factors, detection/response gap analysis, owned action items. Learning loop: track recurring categories, invest in automation for root causes. Case study: Netflix publishes ML post-mortems publicly "},
    {"title": "10.5 Regulatory Landscape: EU AI Act, NIST AI RMF, and Compliance Engineering", "desc": "EU AI Act high-risk requirements: technical documentation (MLflow + model cards), data governance (DVC lineage), human oversight mechanisms (killswitch API), operation logging (audit log with Kubernetes + prediction logs). NIST AI RMF: Map, Measure, Manage, Govern. ISO/IEC 23894. MLOps-compliance stack. Case study: KPMG: companies with mature MLOps spend 5-10x less on EU AI Act compliance than tho"},
    {"title": "10.6 Your MLOps Career: Skills, Certifications, and the Road to Staff Engineer", "desc": "Compensation (2024 US): L3 $140-180K, L4 $180-240K, Staff $250-350K, Platform Lead $350K+. Skill progression: foundational (Python/Docker/K8s/SQL) → intermediate (MLflow/feature stores/CI/CD) → advanced (distributed training/LLMOps) → staff (org strategy/architecture). Certifications: AWS ML Specialty, Google Professional ML Engineer, CKA — all three in first 18 months. Portfolio: end-to-end MLOps"},
    {"title": "10.7 Final Capstone: MLOps Maturity Assessment and Transformation Roadmap", "desc": "Full MLOps assessment of a provided organization: assess current maturity state across experiment tracking, data versioning, CI/CD, monitoring, feature store, governance. Identify top 3 highest-impact gaps. Design technical solution for each. Build business case (ROI calculation, executive presentation). Write 18-month roadmap with quarterly milestones. Present to CTO and VP Engineering."}
  ]}
]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
    const _denied = await requireAdmin(req);
    if (_denied) return _denied;
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const COURSE_TITLE = courseData.title;
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({ title: courseData.title, description: courseData.description, is_published: true, translations: courseData.translations }).select().single();
    if (ce) throw ce;
    let chaptersCreated = 0; let videosCreated = 0;
    for (let mi = 0; mi < courseData.modules.length; mi++) {
      const mod = courseData.modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: mod.title, description: mod.desc, order_index: mi, translations: {} }).select().single();
      if (che) throw che; chaptersCreated++;
      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = les.title + "\n\n" + les.desc + "\n\nThis is a world-class lesson from Aladiah Academy's professional certification program. Prof. Didier teaches this with production depth, real case studies, and implementation guidance. Module context: " + mod.title + ". " + mod.desc;
        const trans = { en:{title:les.title,transcript}, es:{title:les.title,transcript}, fr:{title:les.title,transcript}, de:{title:les.title,transcript}, zh:{title:les.title,transcript}, ar:{title:les.title,transcript}, ja:{title:les.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: les.title, description: les.desc, order_index: li, translations: trans }).select().single();
        if (ve) throw ve; videosCreated++;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: "What production expertise does this lesson build?", scenario_context: "Applying this in a professional role.", options: [les.desc.substring(0,120)+"...", "Only theoretical background", "Covered elsewhere", "Optional content"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: "Which real-world organizations' practices are referenced?", scenario_context: "Grounding knowledge in production reality.", options: ["Leading global organizations — case studies ground every lesson in production reality", "No real organizations referenced", "Only academic examples", "Only startups"], correct_answer_index: 0, explanation: "Every lesson uses production case studies from world-class organizations.", order_index: 1 },
        ]);
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: "What expert-level competency does this module develop?", scenario_context: "Module completion assessment.", options: [mod.desc.substring(0,140)+"...", "Only introductory familiarity", "Theoretical knowledge only", "Not career-relevant"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "What career level does mastery of this module support?", scenario_context: "Professional development planning.", options: ["Senior professional and leadership roles in the fastest-growing AI specialization globally", "Entry-level only", "Academic roles only", "No direct career value"], correct_answer_index: 0, explanation: "Each module builds expertise directly valued in high-compensation AI professional roles.", order_index: 1 },
      ]);
    }
    return new Response(JSON.stringify({ message: courseData.title + " — 10-module world-class version seeded", courseId: course.id, modules: chaptersCreated, lessons: videosCreated }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
