import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const courseData = {
  title: "AI MLOps Engineer",
  description: "Master ML experiment tracking, model registry governance, automated retraining pipelines, production model monitoring, and the MLOps maturity model. Build ML systems that improve continuously and reliably — grounded in Chip Huyen's Designing Machine Learning Systems, Sculley et al.'s Hidden Technical Debt paper, and practices from Netflix, Uber, and Google.",
  chapters: [{
    title: "Module 1: MLOps Foundations, Experiment Tracking, and the Production ML Gap",
    description: "Why 87% of ML models never reach production, the Hidden Technical Debt paper's revelations, MLOps maturity levels, and the experiment tracking discipline that makes ML reproducible.",
    order_index: 0,
    videos: [
      {
        title: "1.1 Hidden Technical Debt in ML Systems: Why Production ML is Harder Than Research",
        description: "Sculley et al.'s landmark NeurIPS 2015 paper, the production ML gap, and why ML code is only a tiny fraction of real ML system complexity.",
        order_index: 0,
        lessonScript: { mainPoints: [
          "Sculley et al.'s 2015 NeurIPS paper 'Hidden Technical Debt in Machine Learning Systems' — authored by Google engineers with direct experience operating ML systems at scale — opened with a diagram that shocked the ML community: a small box labeled 'ML Code' surrounded by a vast system of supporting infrastructure. The point: the ML model itself is a tiny fraction of a production ML system. The surrounding infrastructure includes data collection, feature extraction, data verification, resource management, serving infrastructure, process management, configuration, and monitoring — all of which accrue technical debt that compounds faster than traditional software debt because ML systems have uniquely problematic debt patterns. This paper is why the term 'MLOps' emerged — it named the engineering discipline required to manage production ML systems responsibly.",
          "The Sculley et al. paper identified several ML-specific technical debt patterns not present in traditional software. Entanglement (CACE principle): Changing Anything Changes Everything — changing the input features, hyperparameters, training data, or sampling methods can change the model's behavior in unpredictable ways. Unlike a function that changes one output given a changed input, an ML model's predictions change for all inputs when any aspect of training changes. Undeclared consumers: a model that serves predictions to downstream systems creates hidden dependencies — if you retrain with different output schema, all consumers break, and you may not even know all consumers exist. Feedback loops: when a model's predictions influence future training data (a recommendation model influences user behavior which influences future training data), the model's own outputs corrupt its future training set.",
          "The production ML gap is the most cited statistic in MLOps: according to a 2019 VentureBeat survey, 87% of ML models never reach production. Of those that do, 40% are taken offline within 6 months due to reliability issues, concept drift, and maintenance burden. Chip Huyen's 2022 book 'Designing Machine Learning Systems' (O'Reilly) identified the root causes: most ML education focuses on model development (the 5% of production ML work that involves selecting algorithms and tuning hyperparameters) while ignoring the 95% of work involved in building reliable data pipelines, serving infrastructure, monitoring systems, and operational processes. The gap between 'model that works in a notebook' and 'model that reliably serves production traffic while maintaining accuracy over time' requires the MLOps discipline this course teaches.",
          "Google's MLOps maturity model defines three levels that describe how automated and reliable your ML system is. Level 0 (Manual Process): data scientists work in notebooks, manual training, manual deployment, no monitoring. Models decay silently, CI/CD doesn't exist, training is not reproducible. Most enterprise ML teams are here. Level 1 (ML Pipeline Automation): automated training pipelines triggered by data changes or schedules, automated validation, automated deployment to staging, basic monitoring. Models retrain automatically but may still drift undetected. Level 2 (CI/CD Pipeline Automation): full CI/CD for ML pipelines themselves (not just models), A/B testing infrastructure, automated model evaluation with quality gates, production monitoring with automated retraining triggers. Models continuously improve with minimal human intervention. The goal of MLOps engineering: move your organization from Level 0 to Level 2 systematically.",
          "Reproducibility is the foundational requirement of production ML — the ability to exactly recreate any experiment, any training run, and any deployed model. Without reproducibility, you cannot: debug why model performance changed, comply with regulatory requirements (EU AI Act requires training data provenance), roll back to a previous model version reliably, or onboard new team members who need to understand existing models. The four dimensions of ML reproducibility: data reproducibility (exact dataset version used for training, including preprocessing logic), code reproducibility (exact code state, including all dependencies — use conda environments or Docker containers), configuration reproducibility (exact hyperparameters, random seeds, training duration), and environment reproducibility (GPU type, CUDA version, hardware configuration). Tools: DVC (Data Version Control, open-source Git extension for large data files), MLflow (experiment tracking), and Docker (environment encapsulation).",
          "The concept drift taxonomy defines why production models degrade without any changes to the model code or serving infrastructure. Data drift (covariate shift): the distribution of input features changes from training time. A fraud model trained on 2023 transaction patterns may fail on 2024 transactions with different merchant category distributions. Concept drift (real drift): the relationship between features and labels changes. What predicted fraud in 2023 (specific transaction patterns) may not predict fraud in 2024 (fraud patterns evolved). Label drift: the distribution of actual outcomes changes. If fraud rate increases from 2% to 8%, models calibrated for 2% positive rate will under-detect at 8%. Prior probability shift: the base rate of the target class changes. All four drift types degrade production models — distinguishing between them is essential for choosing the correct remediation (retraining on recent data fixes data drift; redesigning features may be needed for concept drift).",
          "The 'two-phase' nature of ML system failures creates unique operational challenges compared to traditional software. Traditional software: deterministic, fail-fast (exceptions are immediate, obvious, and self-announcing). ML systems: probabilistic, fail-slowly (accuracy degrades gradually over weeks, often with no error logs, no exceptions, and no alerts unless you've built specific monitoring). The analogy from Chip Huyen's book: traditional software failure is a car accident (immediate, obvious, easy to detect); ML failure is metal fatigue (gradual, silent, catastrophic only after a long period of undetected degradation). This is why reactive monitoring (wait for users to complain) is fundamentally inadequate for ML systems — you need proactive monitoring that detects degradation through statistical analysis of model outputs, input distributions, and ground truth labels before users notice."
        ]},
        questions: [
          {question_text:"What was the main insight of Sculley et al.'s 'Hidden Technical Debt in ML Systems' paper?",scenario_context:"Justifying MLOps infrastructure investment to a team that thinks model code is all that matters.",options:["ML models have more bugs than traditional software","ML code is a tiny fraction of production ML system complexity — the surrounding infrastructure (data pipelines, feature extraction, serving, monitoring) comprises the vast majority of the system and accumulates technical debt faster than traditional software","ML systems are cheaper to maintain than traditional software","The paper argued against using ML in production"],correct_answer_index:1,explanation:"The Sculley et al. diagram showing 'ML Code' as a small box surrounded by vast infrastructure was the paper's central visual argument. The point: teams that focus entirely on model development are ignoring 90%+ of the production system that determines reliability. This insight launched the MLOps discipline."},
          {question_text:"What is the CACE principle from Sculley et al.?",scenario_context:"Debugging why your model's performance changed after adding a new feature to the training data.",options:["Continuous Automated Continuous Evaluation","Changing Anything Changes Everything — in ML systems, changing any aspect of training (features, data, hyperparameters, sampling) can change model behavior for all inputs unpredictably, unlike traditional software functions with isolated changes",  "Careful Automated Compliance Engineering","Cross-Architecture Component Evaluation"],correct_answer_index:1,explanation:"CACE is the ML-specific version of software entanglement. Adding feature F to a model can change predictions for inputs that don't even use feature F — because the model redistributes attention across all features during training. This makes change management in ML fundamentally more complex than in traditional software."},
          {question_text:"What are the three levels of Google's MLOps Maturity Model?",scenario_context:"Assessing your organization's current MLOps maturity and planning the roadmap.",options:["Development, Testing, Production","Level 0 (Manual: notebooks, no CI/CD), Level 1 (ML Pipeline Automation: automated training and deployment), Level 2 (CI/CD Pipeline Automation: full CI/CD for pipelines, A/B testing, automated quality gates, retraining triggers)","Bronze, Silver, Gold","Prototype, Pilot, Production"],correct_answer_index:1,explanation:"The three-level model provides a clear progression path. Level 0 → Level 1 requires building automated training pipelines and basic monitoring. Level 1 → Level 2 requires building CI/CD for the pipeline code itself, A/B testing infrastructure, and closed-loop retraining. Most organizations start at Level 0 and should target Level 1 as the first milestone."},
          {question_text:"What is 'concept drift' and how does it differ from 'data drift'?",scenario_context:"Investigating why your fraud detection model accuracy dropped 15% without any code changes.",options:["They are the same phenomenon","Data drift: input feature distributions change (covariate shift). Concept drift: the relationship between features and labels changes — what used to predict fraud no longer does because fraud patterns evolved. Different root causes require different remediation: data drift often responds to retraining; concept drift may require feature redesign.",  "Concept drift is more severe than data drift","Data drift only affects image models"],correct_answer_index:1,explanation:"Distinguishing drift types guides the correct remediation. Retraining on recent data fixes data drift (same relationship, different distribution). If fraud patterns fundamentally changed (concept drift), retraining on recent data may help but redesigning features to capture new patterns may be necessary. Misdiagnosing drift type leads to ineffective remediation."},
          {question_text:"Why is the 'fail-slowly' nature of ML failures uniquely dangerous in production?",scenario_context:"Convincing leadership to invest in proactive model monitoring rather than waiting for user complaints.",options:["Slow failures are less impactful than fast failures","ML failures are silent and gradual — no exceptions, no error logs, no alerts — accuracy degrades over weeks while the system appears fully operational. Reactive monitoring (waiting for user complaints) means weeks of degraded service before detection. Proactive statistical monitoring is the only viable approach.",  "Slow failures are easier to debug","Users always notice model degradation quickly"],correct_answer_index:1,explanation:"The analogy is metal fatigue vs. car accident. Traditional software fails fast and loudly. ML systems degrade silently. A fraud model with 15% worse accuracy generates no logs, no exceptions, and no infrastructure alerts — only more undetected fraud. Proactive monitoring must detect the statistical signal before users experience the consequence."}
        ]
      },
      {
        title: "1.2 Experiment Tracking and ML Reproducibility with MLflow and Weights & Biases",
        description: "Why every ML training run must be tracked, MLflow's architecture, W&B's advanced features, and the experiment management discipline that makes ML teams 10x more productive.",
        order_index: 1,
        lessonScript: { mainPoints: [
          "Experiment tracking is the practice of systematically recording every ML training run's configuration, metrics, and artifacts — creating an auditable, searchable history of your team's ML work. Without experiment tracking, ML development is archaeology: you have models of unknown provenance, results you can't reproduce, and no way to understand what changed between the model that worked and the model that didn't. The practical consequence: data scientists spend 30-40% of their time trying to reproduce past experiments (Kaggle's State of Data Science 2022 survey), and teams routinely rediscover optimizations they already found months earlier. Experiment tracking transforms ML from individual heroics into systematic engineering.",
          "MLflow, open-sourced by Databricks in 2018, has become the industry-standard experiment tracking platform with four core components. MLflow Tracking: the experiment logging API — mlflow.log_param('learning_rate', 0.001) records hyperparameters, mlflow.log_metric('val_accuracy', 0.923) records metrics per epoch, mlflow.log_artifact('confusion_matrix.png') records artifacts, mlflow.set_tag('model_type', 'transformer') records free-form metadata. MLflow Projects: reproducible ML code in MLproject files with conda or Docker environments — run any MLflow project from any commit with mlflow run git://github.com/user/project -v abc123. MLflow Models: standardized model packaging supporting multiple 'flavors' (sklearn, pytorch, tensorflow, pyfunc) so any serving framework can load any model. MLflow Model Registry: versioned model staging (None → Staging → Production → Archived) with approval workflows.",
          "Weights & Biases (W&B) offers the most feature-rich experiment tracking platform — particularly valuable for deep learning teams with complex training dynamics. W&B's differentiating features: automatic system metrics (GPU utilization, memory, CPU logged automatically without any code), interactive visualizations (training curves with outlier detection, hyperparameter importance charts, confusion matrices that update as training progresses), W&B Sweeps (automated hyperparameter optimization with Bayesian, grid, or random strategies integrated with experiment tracking), W&B Artifacts (versioned datasets and model artifacts with lineage graphs showing which dataset → which training run → which model → which evaluation), and W&B Tables (interactive data tables for analyzing model predictions and failure modes). Netflix's ML Platform team documented that adopting W&B reduced the time to identify optimal model configurations by 60% compared to manual experiment management.",
          "The experiment naming and organization discipline separates teams that get value from experiment tracking from those who just have a lot of unorganized runs. Production standard: experiments are organized by business problem and model type (fraud/transaction_classifier, recommendations/user_embedding_model). Every run has a meaningful name that encodes key decisions (bert-base-lr0001-dropout02-epoch10-v2-ablation-no-entity-features). Tags encode the run's purpose: experiment_type: baseline|ablation|hyperparameter_search|production_candidate. The production_candidate tag is reserved for runs passing all quality thresholds and being considered for deployment — connecting the experiment tracking system to the model registry. Without naming discipline, experiment tracking databases accumulate thousands of runs with names like 'test', 'run_1', 'final_FINAL_v3' that are impossible to navigate.",
          "Hyperparameter optimization (HPO) is the process of systematically searching for the configuration that maximizes model performance. Grid search: exhaustive evaluation of all parameter combinations — complete but exponential complexity (3 parameters × 5 values each = 125 runs). Random search: sample randomly from the hyperparameter space — more efficient than grid search for high-dimensional spaces (Bergstra & Bengio 2012 proved random search outperforms grid search for most ML problems). Bayesian optimization: uses a surrogate model of the objective function to propose the next trial most likely to improve on the best known configuration — typically 10x more efficient than random search. Optuna (open-source, TPE algorithm), Hyperopt, and W&B Sweeps implement Bayesian HPO. The practical guidance: for < 5 parameters with known ranges, grid search is acceptable; for ≥ 5 parameters or continuous ranges, Bayesian optimization is significantly more efficient.",
          "DVC (Data Version Control) solves the large-file versioning problem that prevents Git from being used directly for ML reproducibility. DVC's architecture: large files (datasets, model weights) are tracked by a small pointer file in Git, while actual content is stored in remote storage (S3, GCS, Azure Blob). The pointer file is a 64-character content hash — identical to two data files produces identical hashes, enabling deduplication. The workflow: dvc add data/train.csv generates a data/train.csv.dvc pointer file that goes into Git; dvc push sends the actual data to remote storage; dvc pull retrieves it. The result: git pull + dvc pull reproduces both exact code AND exact data from any historical commit — full ML experiment reproducibility. GitHub's 2023 survey of ML teams found that teams using DVC reduced experiment reproduction failures by 78% compared to ad-hoc data management.",
          "Experiment comparison and decision-making is where experiment tracking delivers its ROI — enabling systematic improvement rather than random walk through hyperparameter space. The structured experiment design process: establish a baseline (train with default hyperparameters, log as 'baseline' tag — this is your reference point), run controlled ablations (change one factor at a time, compare to baseline — which features matter? does regularization help?), run HPO (Bayesian search around the region of hyperparameter space where ablations showed promise), select production candidate (run that meets all quality gates: accuracy, bias, latency, regression against current production model), and register in model registry (promote to Staging with links to the MLflow experiment runs that justify the promotion). This systematic process — compared to the 'try things and see what works' approach — is what enables ML teams to build institutional knowledge and compounding improvements."
        ]},
        questions: [
          {question_text:"What problem does experiment tracking solve for ML teams?",scenario_context:"Justifying MLflow investment to a team that currently tracks experiments in a shared spreadsheet.",options:["It makes model training faster","Creates an auditable, searchable history of all training runs — eliminating 30-40% of time spent reproducing past experiments, enabling systematic improvement over ad-hoc exploration, and providing the provenance required for regulatory compliance and model governance.",  "It automatically improves model accuracy","It replaces the need for version control"],correct_answer_index:1,explanation:"Kaggle's survey finding that 30-40% of data scientist time goes to reproducing past experiments quantifies the cost of poor experiment tracking. MLflow/W&B eliminate this waste by recording every run's exact configuration, environment, and results — making any experiment reproducible with a single command."},
          {question_text:"What are MLflow's four core components and what does each do?",scenario_context:"Evaluating MLflow for your ML platform's experiment management needs.",options:["Train, Test, Deploy, Monitor","MLflow Tracking (log parameters, metrics, artifacts per run), MLflow Projects (reproducible code packaging with environments), MLflow Models (standardized multi-framework model packaging), MLflow Model Registry (versioned staging workflow with approval processes)","Data, Model, Pipeline, Service","Ingest, Process, Train, Serve"],correct_answer_index:1,explanation:"Each component addresses a distinct MLOps need: Tracking solves experiment reproducibility, Projects solves code reproducibility, Models solves serving portability, Registry solves production governance. Together they form a complete ML lifecycle management system — which is why MLflow has become the open-source standard adopted at companies like Databricks, Microsoft, and thousands of enterprises."},
          {question_text:"Why does Bayesian hyperparameter optimization outperform random search?",scenario_context:"Tuning a transformer model with 12 hyperparameters — random search is taking weeks.",options:["Bayesian methods are always faster","A surrogate model of the objective function guides next trial selection — proposing hyperparameters most likely to improve on the best known configuration. This learns from past trials rather than sampling blindly, achieving 10x efficiency for large hyperparameter spaces vs. random search.",  "Bayesian search guarantees finding the global optimum","Bayesian optimization requires fewer hyperparameters"],correct_answer_index:1,explanation:"Bayesian optimization's efficiency gain comes from intelligent exploration vs. exploitation: it builds a probabilistic model of the objective function and uses it to select the next trial that maximizes expected improvement. For 12 hyperparameters, this can find near-optimal configurations in 50 trials where random search might require 500."},
          {question_text:"What does DVC (Data Version Control) enable that Git alone cannot?",scenario_context:"Your team needs to reproduce a training run from 6 months ago including the exact dataset version.",options:["DVC replaces Git for ML projects","Full dataset versioning with Git-compatible pointers — large files stored in remote storage (S3/GCS) with content-hash pointers in Git. git pull + dvc pull reproduces exact code AND exact data from any historical commit, providing full ML experiment reproducibility that Git alone can't handle for GB/TB-scale datasets.",  "DVC provides faster model training","DVC automatically labels training data"],correct_answer_index:1,explanation:"Git can't store 10GB training datasets — it breaks for files over a few MB. DVC's pointer system stores the hash in Git (tiny, versionable) and the actual data in cloud storage (cheap, scalable). The combination provides complete ML reproducibility: exact code (Git) + exact data (DVC) + exact environment (Docker/conda) = reproducible training."},
          {question_text:"What is the 'production_candidate' tag in experiment tracking and what does it gate?",scenario_context:"Your team has 500 experiment runs in MLflow and needs a workflow to promote the best to production.",options:["A tag for experimental production deployments","A reserved tag for runs passing all quality gates (accuracy, bias, latency, regression vs. current production model) — connecting the experiment tracking system to the model registry promotion workflow. Only production_candidate runs are considered for Staging promotion, creating an auditable selection process.",  "A tag for all training runs","A tag only for A/B test variants"],correct_answer_index:1,explanation:"The production_candidate tag creates a formal gate between experiment space and model registry — only runs explicitly tagged as candidates, after human review of quality gate results, enter the registry promotion workflow. This prevents the anti-pattern of teams promoting models directly from notebooks without documented quality validation."}
        ]
      },
      {
        title: "1.3 Model Registry, Versioning, and Deployment Governance",
        description: "The model registry as single source of truth, semantic versioning for ML models, model cards, lineage tracking, and the approval workflows that satisfy both engineering and compliance requirements.",
        order_index: 2,
        lessonScript: { mainPoints: [
          "A model registry is the centralized system that serves as the single source of truth for all production ML models — tracking versions, metadata, quality metrics, deployment history, and current production status. Without a model registry, teams face: inability to identify what model is currently serving production traffic, inability to reproduce the current production model for debugging, inability to roll back to a previous version reliably, and inability to answer the audit question 'what model was serving predictions on date X?' The model registry is to ML deployment what a container registry is to software deployment — the immutable, versioned artifact store that connects CI/CD pipelines to production serving infrastructure.",
          "Model cards, introduced by Mitchell et al. (2019) in their paper 'Model Cards for Model Reporting,' are the standardized documentation artifacts that every production model should have. A complete model card includes: intended use (specific use case, target users, out-of-scope uses, known misuse scenarios), performance metrics (accuracy, precision, recall, F1 — both overall and broken down by demographic group), evaluation data (description of the held-out test set, distribution, collection method), training data (high-level description, potential biases, preprocessing applied), ethical considerations (known failure modes, fairness considerations, potential for harm), and caveats (limitations, recommended monitoring, conditions under which performance may degrade). Model cards serve both internal teams (understanding model capabilities and limitations) and external accountability (demonstrating responsible AI practices to regulators and auditors). The EU AI Act's Article 13 transparency requirements for high-risk AI systems are essentially a regulatory version of model cards.",
          "Semantic versioning for ML models adapts software versioning conventions to the ML lifecycle with specific meanings for each version component. Major version (1.0.0 → 2.0.0): breaking change in output schema, fundamentally different model architecture, different feature input set that requires downstream integration updates — consumers must update their integration. Minor version (1.0.0 → 1.1.0): improved model trained on new data, same features and output schema, backward compatible — typically a quality improvement that's a drop-in replacement. Patch version (1.0.0 → 1.0.1): bug fix in preprocessing logic, correction to a feature transformation, no change to model weights — emergency fix for a data pipeline bug. The version string communicates compatibility expectations to all consumers of the model — an API client using model v1.x.x knows that major version changes require integration work while minor/patch versions are safe to accept automatically.",
          "Model lineage tracking records the complete provenance of every deployed model — the 'audit trail' that connects model predictions back to their data origins. Complete lineage includes: training data snapshot (dataset name, version, time range, source systems), training code (Git SHA, MLflow run ID, training script path), feature pipeline version (feature store configuration, transformation logic version), hyperparameters (as logged in MLflow or W&B), evaluation results (metrics on test set, fairness metrics, latency benchmarks), deployment history (when deployed, by whom, to what environment, with what approval), and incident history (any production incidents involving this model version). Complete lineage enables: debugging (what changed between the model that worked and the model that doesn't?), compliance (prove what data trained the production model for GDPR or EU AI Act audit), and reproducibility (recreate any production model for analysis). Tools: MLflow's run lineage, W&B Artifacts lineage graphs, and Neptune.ai's experiment tracking.",
          "The model staging workflow enforces governance and prevents unauthorized deployments. Standard stages: None (registered, not yet evaluated — output from CI/CD training runs), Staging (evaluation complete, all quality gates passed, approved for integration testing — automated promotion by CI/CD), Production (deployed and serving real traffic — requires human approval or automated A/B gate), Archived (retired, no longer serving traffic — retained for audit, lineage, and potential rollback). Transitions require documented justification: Staging promotion requires linked MLflow experiment run IDs and quality gate results; Production promotion requires A/B test results or explicit approval from ML engineer and product owner; Archival requires documentation of why the model was retired. This workflow creates a complete audit trail of every production decision — essential for regulated industries and increasingly required by AI governance frameworks.",
          "Model card automation reduces the friction of documentation compliance. Tools: the open-source model-card-toolkit (Google) generates card templates and integrates with TFX pipelines; huggingface_hub auto-populates model cards from training metadata; MLflow's model schema and tags can auto-generate sections of model cards. The practical workflow: require a model card template as part of the model registry's Staging promotion checklist — the CI/CD pipeline generates the template with auto-populated fields (training dataset, performance metrics, training date), and the ML engineer completes the ethical considerations and caveats sections manually. Model cards that take 30 minutes to write are completed; model cards that require 3 hours of custom documentation are skipped. Automation makes the right behavior the easy behavior.",
          "The model registry API enables programmatic integration with serving infrastructure. MLflow's Python client: mlflow.pyfunc.load_model('models:/fraud_classifier/Production') loads the current production model by name and stage — serving code always loads from the registry rather than a hardcoded path, enabling model updates without serving code changes. The Kubernetes operator pattern: a custom Kubernetes controller watches the model registry for Production stage changes and automatically updates Kubernetes Deployments with the new model version. Combined with ArgoCD's GitOps workflow, this creates a fully automated model deployment pipeline: CI/CD trains → promotes to Staging → quality gates pass → human approves Production → Kubernetes controller deploys. Deployment latency from approval to serving traffic: under 5 minutes."
        ]},
        questions: [
          {question_text:"What four operational failures does a model registry prevent?",scenario_context:"Justifying model registry infrastructure investment to an engineering director.",options:["It prevents model overfitting","Can't identify what model serves production, can't reproduce current model for debugging, can't reliably roll back, can't answer audit question 'what model served on date X?' — all four failures are catastrophic for production ML operations and compliance.",  "It prevents data drift","It prevents model deployment entirely"],correct_answer_index:1,explanation:"Each failure has a concrete operational cost: unknown production model means debugging requires reverse-engineering what's deployed; inability to reproduce means debugging is guesswork; unreliable rollback means incidents last longer; missing audit trail means compliance failures. A model registry eliminates all four with a single system."},
          {question_text:"What does a 'Major version' change in ML model semantic versioning signal to consumers?",scenario_context:"Your recommendation model v2.0.0 changes its output schema from a ranked list to a scored dictionary.",options:["A minor improvement to model accuracy","A breaking change — different output schema, different feature inputs, or fundamentally different architecture. Downstream consumers MUST update their integration. API clients using v1.x.x cannot safely upgrade to v2.0.0 without code changes.",  "A bug fix in data preprocessing","An incremental retraining on new data"],correct_answer_index:1,explanation:"Semantic versioning communicates a compatibility contract. Major version change = 'you need to update your code to use this.' Minor = 'safe drop-in replacement, probably better.' Patch = 'bug fix, definitely safe.' Communicating this clearly prevents consuming teams from being surprised by breaking changes."},
          {question_text:"What are model cards and what regulatory requirement do they satisfy?",scenario_context:"Preparing documentation for a high-risk AI system under EU AI Act compliance.",options:["A business card format for AI vendors","Standardized documentation covering intended use, performance by demographic group, training data, ethical considerations, and limitations (Mitchell et al. 2019). The EU AI Act's Article 13 transparency requirements for high-risk AI are essentially a regulatory model card mandate.",  "A credit card for AI API access","A government registration document"],correct_answer_index:1,explanation:"Model cards are both good practice (understanding what a model can/can't do) and regulatory compliance (EU AI Act Article 13 requires transparency documentation for high-risk AI). The Mitchell et al. 2019 paper that introduced model cards has directly influenced regulatory frameworks — making model card creation a compliance requirement for covered AI systems."},
          {question_text:"What is 'complete model lineage' and which compliance scenario requires it?",scenario_context:"A GDPR auditor asks which training data was used for your credit scoring model deployed 18 months ago.",options:["Just the training dataset name","The complete provenance chain: training data version, training code Git SHA, feature pipeline version, hyperparameters, evaluation results, and deployment history. GDPR and EU AI Act compliance requires being able to prove exactly what data trained the production model — incomplete lineage means audit failure.",  "The model's accuracy metrics only","The deployment date and serving infrastructure"],correct_answer_index:1,explanation:"GDPR's data accountability principle (Article 5) and EU AI Act's transparency requirements both require being able to document the complete provenance of deployed AI systems. Complete lineage connects model → training run → dataset → source data — answering 'what data trained this model?' with precision rather than approximation."},
          {question_text:"What does the model registry API pattern 'mlflow.pyfunc.load_model(models:/fraud_classifier/Production)' enable?",scenario_context:"Your serving code currently has the model path hardcoded — model updates require code deployments.",options:["Training a new model automatically","Serving code loads the current Production stage model by name — model updates only require changing the registry stage (not serving code). Combined with a Kubernetes operator watching for registry changes, model updates can deploy in under 5 minutes without any serving code changes.",  "Running model inference in the browser","Backing up the model to cloud storage"],correct_answer_index:1,explanation:"Registry-based model loading decouples model updates from serving code updates. The serving code always loads from the 'Production' stage — whoever promotes a new model version to Production automatically changes what gets served. This enables the ML registry to be the deployment trigger, not a separate serving code change."}
        ]
      },
      {
        title: "1.4 Model Monitoring and Drift Detection: Catching Degradation Before Users Notice",
        description: "Statistical drift detection methods, prediction distribution monitoring, the PSI and KS test, Evidently AI, and the closed-loop retraining systems that keep production models accurate.",
        order_index: 3,
        lessonScript: { mainPoints: [
          "Model monitoring is the operational discipline of detecting when deployed models start to degrade — before that degradation affects business outcomes. The challenge: model degradation typically produces no error logs, no exceptions, and no infrastructure alerts. A fraud model with 20% worse accuracy still returns HTTP 200 responses — the only signals are statistical: the model's prediction confidence distributions shift, the rate of positive predictions changes, and eventually (weeks later) business metrics like undetected fraud rate worsen. Production model monitoring requires building custom statistical monitoring infrastructure — it doesn't come for free with any infrastructure platform. Companies that have this capability (Netflix, Airbnb, Google) discover degradation in hours; companies that don't discover it in weeks when customers complain.",
          "Statistical drift detection methods provide the quantitative foundation for monitoring decisions. Population Stability Index (PSI): measures how much a feature's distribution has changed between a reference period (training time) and current production. PSI = Σ((Actual% - Expected%) × ln(Actual%/Expected%)). Interpretation: PSI < 0.1 indicates stable distribution (no action needed), 0.1-0.2 indicates moderate shift (monitor closely), > 0.2 indicates significant shift (investigate and consider retraining). PSI originated in credit risk management (where it's been used for 30+ years) and is widely adopted in ML monitoring because it's simple to compute and interpret. Kolmogorov-Smirnov (KS) test: a statistical hypothesis test for whether two samples come from the same distribution — provides a p-value indicating whether observed drift is statistically significant or within random variation. KL Divergence and Jensen-Shannon Divergence: information-theoretic measures of distribution difference, sensitive to tail distributions.",
          "Prediction monitoring tracks whether the model's output distribution matches the training-time distribution — often the earliest signal of underlying problems. Key prediction monitoring metrics: prediction score distribution (track mean, stddev, p5, p50, p95 of prediction scores — a 15% drop in mean confidence suggests the model is less certain about current inputs than training-time inputs), positive prediction rate (for classification models: track the fraction of positive predictions — unexplained changes indicate either distribution shift or model behavior change), calibration stability (track whether a model's confidence scores still correspond to actual frequencies — a calibrated model at 80% confidence should be correct 80% of the time), and prediction diversity (for recommendation models: if diversity of recommendations collapses, the model may be stuck in local optima). These signals catch issues before ground truth labels are available — critical for applications with delayed feedback (credit default known after 30 days, customer churn after 90 days).",
          "Evidently AI (open-source) is the leading ML monitoring framework for generating drift reports and monitoring dashboards. Core capabilities: DataDriftPreset (computes PSI/KS test for all input features, visualizes distributions, flags drifted features), DataQualityPreset (null rates, value ranges, cardinality changes), ModelPerformancePreset (accuracy, precision, recall, F1 if ground truth available), TargetDriftPreset (prediction distribution monitoring without ground truth). Integration: run Evidently reports on a schedule (daily or hourly for high-stakes systems), store results in a metrics database (Prometheus, ClickHouse), visualize in Grafana dashboards. Alert configuration: set thresholds per feature based on business impact — critical features (recent_transaction_count for fraud detection) warrant alerting at PSI > 0.1; less critical features may use PSI > 0.2. WhyLabs and Arize offer managed alternatives with additional ML-specific analytics.",
          "Ground truth collection and delayed label handling are the practical challenges that make production ML monitoring harder than development evaluation. Many production ML applications have significant label delays: credit risk (default known after 30-90 days), customer churn (churn confirmed after 30-180 days), content safety (human review takes days). Approaches for dealing with delayed labels: (1) Proxy metrics — leading indicators correlated with the true label available without delay (click-through rate as proxy for content quality, support ticket creation as proxy for product churn). (2) Stratified sampling — collect ground truth labels for a random sample of predictions (expensive but unbiased evaluation). (3) Active learning selection — prioritize ground truth collection for predictions the model is uncertain about (highest information per labeling effort). (4) Weak supervision — programmatic labeling functions that provide noisy approximations of ground truth. The Snorkel framework (Ratner et al., 2017, Stanford) formalized weak supervision as a production monitoring and retraining approach.",
          "Automated retraining pipelines close the loop between monitoring and model improvement. The trigger-based retraining pattern: monitoring alerts when PSI > 0.2 for key features → Airflow DAG triggered → retraining pipeline runs (pulls recent data, retrains model, runs quality gates) → if quality gates pass, new model promotes to Staging → human reviews (or automated A/B gate) and approves Production. The challenge: automated retraining without quality gates can deploy degraded models faster than manual processes — automation amplifies both improvement and risk. Amazon's Alexa ML team documented that adding automated quality gates to their retraining pipeline eliminated the category of 'retraining regression' incidents (where retraining made the model worse) entirely — by blocking deploys where the new model performed worse than the current production model on a fixed regression test set.",
          "The ML monitoring stack architecture combines multiple systems for complete coverage. Infrastructure monitoring (Prometheus + Grafana): latency, throughput, error rates, GPU utilization — standard DevOps monitoring. Feature monitoring (Evidently + custom): PSI, KS test, null rates for input features — custom ML monitoring. Prediction monitoring (custom): prediction score distribution, label distribution, calibration — custom ML monitoring. Business metrics monitoring (data warehouse + BI): conversion rate, fraud rate, customer satisfaction — business-level impact. Incident correlation: when a business metric alert fires, correlate with prediction and feature monitoring to determine if ML model degradation is the cause. The 4-layer architecture (infrastructure → features → predictions → business metrics) enables root cause analysis: infrastructure alert first means infrastructure issue, not model issue; business metric alert without infrastructure alert suggests model drift; prediction distribution alert without feature alert suggests concept drift.",
        ]},
        questions: [
          {question_text:"What does PSI > 0.2 indicate in feature drift monitoring?",scenario_context:"Your PSI alert fires for the 'days_since_last_login' feature with PSI = 0.31.",options:["Minor statistical noise","Significant distribution shift requiring investigation and likely model retraining — the feature's distribution has changed substantially from the training-time reference. For fraud detection, this warrants immediate investigation into what changed in user login patterns.",  "The model is performing better","PSI > 0.2 is always safe to ignore"],correct_answer_index:1,explanation:"PSI thresholds from credit risk monitoring: <0.1 = stable, 0.1-0.2 = moderate (monitor), >0.2 = significant (investigate). PSI = 0.31 means the days_since_last_login distribution has shifted substantially from training — users are logging in with different patterns. For fraud detection, this is a material change requiring investigation."},
          {question_text:"What are 'proxy metrics' and why are they necessary for models with delayed labels?",scenario_context:"Your churn prediction model won't have confirmed churn labels for 90 days after predictions.",options:["Backup metrics used when primary metrics fail","Leading indicators correlated with the true label, available without the label delay. Click-through rate as proxy for content quality; support ticket creation as proxy for churn — enable model quality monitoring before 90-day labels arrive, catching degradation in days rather than months.",  "Metrics from proxy servers","Approximate metrics used during development only"],correct_answer_index:1,explanation:"A model with 90-day label delay means you'd discover degradation 90 days too late using direct accuracy metrics. Proxy metrics (correlated leading indicators available immediately) close this gap — declining click-through rate or rising support tickets signal model quality issues weeks before confirmed churn labels arrive."},
          {question_text:"What did Amazon's Alexa ML team demonstrate about automated retraining quality gates?",scenario_context:"Your automated retraining pipeline occasionally deploys models that perform worse than the previous version.",options:["Automated retraining always improves models","Adding quality gates that block deployment when the new model underperforms the current production model on a fixed regression test set eliminated the 'retraining regression' incident category entirely — automation amplifies both improvement and risk; quality gates are mandatory.",  "Retraining should always be manual","Quality gates slow down the retraining pipeline too much"],correct_answer_index:1,explanation:"Automated retraining without quality gates can deploy degraded models faster than manual processes. The regression test gate (new model must perform ≥ current production model on a fixed test set) prevents the specific failure mode of retraining on recent data that happens to be unrepresentative or lower quality than the training set."},
          {question_text:"What is calibration in the context of ML model monitoring?",scenario_context:"Your fraud model's business performance has degraded even though its accuracy metrics look stable.",options:["Setting the model's temperature parameter","Whether a model's confidence scores correspond to actual outcome frequencies — a well-calibrated model at 80% confidence should be correct 80% of the time. Calibration drift (confident predictions becoming less reliable) is a leading indicator of model quality degradation before accuracy metrics show it.",  "The process of adjusting model weights","The latency of model serving infrastructure"],correct_answer_index:1,explanation:"Calibration drift is often the earliest detectable signal of model degradation. When a model becomes overconfident or underconfident, its confidence scores no longer correspond to actual outcome frequencies — the model is 'wrong about being right.' Business decisions made on model confidence (fraud score thresholds) degrade before accuracy metrics catch up."},
          {question_text:"What is the 4-layer ML monitoring stack and why does it enable root cause analysis?",scenario_context:"A business metric alert fires — you need to determine if it's an ML model problem or an infrastructure problem.",options:["Four separate monitoring systems with no integration","Infrastructure (latency/errors) → Features (PSI/KS drift) → Predictions (score distribution/calibration) → Business metrics (conversion/fraud rate). The sequence of alerts pinpoints root cause: infrastructure alert first = infrastructure issue; business alert without infrastructure alert + prediction distribution change = model drift.",  "A monitoring system with four dashboards","Four different ML models monitoring each other"],correct_answer_index:1,explanation:"The 4-layer stack creates a diagnostic decision tree. Infrastructure alert with no model alert = infrastructure issue (fix the infrastructure). Model prediction distribution change without infrastructure alert = model drift (investigate data changes). Business metric change without any model or infrastructure alert = business change (external factor, not ML issue). Correlation across layers pinpoints root cause."}
        ]
      },
      {
        title: "1.5 MLOps Pipelines with Kubeflow and CI/CD for Machine Learning",
        description: "Kubeflow Pipelines architecture, containerized ML components, pipeline versioning, and the complete CI/CD for ML workflow that takes a code commit to a production model automatically.",
        order_index: 4,
        lessonScript: { mainPoints: [
          "Kubeflow Pipelines (KFP) is the Kubernetes-native ML pipeline framework — defining ML workflows as directed acyclic graphs of containerized components. Each component in a Kubeflow Pipeline is a container that performs one step of the ML workflow: data validation, feature engineering, model training, model evaluation, model registration. The DAG structure ensures correct execution order (model training only runs after feature engineering completes) and enables parallelism (multiple hyperparameter search trials run simultaneously on separate GPU pods). The Kubeflow Pipeline specification is defined in Python using the KFP SDK — components are decorated Python functions that compile to Kubernetes Pod specifications. This pipeline-as-code approach means your ML workflow is version-controlled, testable, and reproducible.",
          "The KFP component design principles determine whether pipelines are maintainable and reusable. Single responsibility: each component does one thing (a validation component that also trains a model is an unmaintainable monolith). Explicit interfaces: components declare their inputs and outputs as typed parameters — the pipeline compiler validates type compatibility at compile time, not runtime. Containerization: each component specifies its own container image, enabling independent versioning of component dependencies. A training component using PyTorch 2.1 doesn't need to share a container with an evaluation component using scikit-learn 1.3 — they're independent containers. Caching: KFP automatically caches component outputs and skips re-execution if inputs haven't changed — a 4-hour data preprocessing step cached means subsequent runs start directly at model training. Kubeflow's caching system stores component output hashes and component parameters — changing the component code (new Docker image) or input parameters invalidates the cache.",
          "Vertex AI Pipelines (Google Cloud) and SageMaker Pipelines (AWS) offer managed alternatives to self-hosted Kubeflow that eliminate cluster management overhead. Vertex AI Pipelines: Google's managed KFP-compatible service — the same KFP SDK code runs on Vertex AI with no modification, but Google manages the Kubernetes infrastructure, auto-scales compute to zero when not running, and provides native integration with Vertex AI Model Registry and Vertex AI Experiments. SageMaker Pipelines: AWS-native ML workflow orchestration with native integration with SageMaker Training, SageMaker Model Registry, and SageMaker Model Monitor — uses a JSON-based pipeline definition rather than Python SDK. The build-vs-buy decision: organizations with existing Kubernetes infrastructure and multi-cloud requirements favor self-hosted Kubeflow; organizations deeply invested in a single cloud provider favor the managed alternative for reduced operational overhead.",
          "CI/CD for machine learning extends traditional software CI/CD with ML-specific stages. The complete CI/CD for ML pipeline (as defined by Google's MLOps paper, 2020): Source control trigger (PR to main branch), Code quality stage (linting, type checking, unit tests for data processing code), Integration test stage (run pipeline on a small data sample, validate outputs), Model training stage (full training run triggered on main branch merge), Model evaluation stage (run quality gates: accuracy threshold, bias tests, latency benchmark, regression vs. production model), Model registry stage (promote to Staging if all gates pass), Staging validation stage (integration tests against the new model in staging environment, potentially with shadow traffic), Production promotion stage (manual approval gate or automated A/B test gate), and Production deployment stage (Kubernetes controller deploys new model version). The total pipeline from commit to production: under 4 hours for teams at MLOps Level 2.",
          "Pipeline versioning and backward compatibility are operational requirements for production ML pipelines. Pipeline versioning: tag every pipeline version with the same Git SHA as the training code — mlflow.set_tag('pipeline_version', git.short_sha()) creates a permanent link between pipeline execution and pipeline code. Backward compatibility: when you change a pipeline component's interface (adding a new required parameter, changing an output type), you must version both the component and the pipeline — existing scheduled runs should continue using the old version until explicitly migrated. The 'Blue-Green' pipeline strategy: deploy a new pipeline version alongside the existing one, validate on a subset of training runs, then migrate scheduled jobs. Pipeline changes that look minor (changing a feature engineering step) can have large model impact — the CACE principle applies to pipeline components just as it applies to models.",
          "Feature pipeline testing is the most neglected but highest-impact testing practice in MLOps. The failure mode: a feature pipeline produces silently incorrect feature values (an off-by-one error in a rolling window calculation, a join producing duplicates, a timezone conversion error) that train the model on corrupted data — the model appears to work in offline evaluation but fails in production where the same feature pipeline produces correct values. Testing levels for feature pipelines: unit tests (individual transformation functions produce correct outputs for known inputs), integration tests (full pipeline runs on a sample dataset, outputs match expected values), statistical tests (feature value distributions match expectations — mean, std, null rate within bounds), and differential tests (comparing new pipeline version outputs to old version on the same input data — unexpected differences indicate regression). Great Expectations is the industry-standard framework for data quality testing integrated into feature pipeline CI/CD.",
          "The MLOps retrospective is the practice of systematically reviewing ML system performance, operational incidents, and technical debt — the ML analog of the software engineering post-mortem. Monthly MLOps retrospective agenda: review production model performance (are all models meeting their accuracy SLOs?), review operational incidents (what model-related incidents occurred, what were root causes?), review technical debt (what pipeline shortcuts, monitoring gaps, or documentation deficiencies accumulated?), and review team velocity (what slowed down model development and deployment this month?). The retrospective produces a prioritized technical debt backlog specifically for MLOps infrastructure — separate from the product feature backlog. Teams that run MLOps retrospectives systematically eliminate the operational friction that accumulates in production ML systems; teams that don't find themselves spending increasingly more time on operational fire-fighting and increasingly less time on model improvement."
        ]},
        questions: [
          {question_text:"What is KFP component caching and how does it accelerate iterative ML development?",scenario_context:"Your data preprocessing step takes 4 hours; you want to iterate quickly on model architecture changes.",options:["Caching model weights between runs","KFP automatically caches component outputs based on input hashes and component code — if inputs haven't changed, KFP skips re-execution and uses cached outputs. A 4-hour preprocessing step is only re-run when data or preprocessing code changes; model architecture changes skip directly to training.",  "Caching API requests to reduce costs","Storing previous model versions in memory"],correct_answer_index:1,explanation:"KFP caching provides the ML equivalent of build system incremental compilation — only rebuild what changed. Changing model architecture doesn't change preprocessing inputs or code, so preprocessing is skipped and cached outputs feed directly into the new training run. This can reduce iteration time from 6 hours to 30 minutes."},
          {question_text:"What is the single responsibility principle for KFP components?",scenario_context:"Your team built a single KFP component that validates data, engineers features, and trains the model.",options:["Each component should use minimal compute","Each component does one thing — data validation, feature engineering, and model training are separate components with explicit typed interfaces. Monolithic components can't be cached independently, can't be reused in other pipelines, and have untestable combinations of concerns.",  "Each component should have a single owner","Components should use the smallest possible container image"],correct_answer_index:1,explanation:"Single-responsibility components enable: independent versioning (update the training component without affecting feature engineering), independent caching (cache expensive steps independently), independent testing (unit test each step in isolation), and reuse (the same feature engineering component can serve multiple training pipelines). Monolithic components lose all these properties."},
          {question_text:"What is the 'differential test' for feature pipeline testing and what failure mode does it catch?",scenario_context:"You refactored your feature engineering pipeline and want to verify behavior is unchanged.",options:["Comparing model performance before and after","Comparing new pipeline version outputs to old version outputs on identical input data — unexpected differences indicate a regression introduced by refactoring. Catches the silent data corruption failure mode (off-by-one errors, join duplicates, timezone bugs) that appears correct but produces subtly wrong values.",  "A test that compares two different models","A test for differential privacy compliance"],correct_answer_index:1,explanation:"Differential testing is the safety net for refactoring — proving the new implementation produces identical outputs to the old one. A timezone bug in a rolling window calculation produces values that pass all unit tests (correct logic for individual records) but produce systematically different values than the original implementation. Differential tests catch this."},
          {question_text:"What does the complete CI/CD for ML pipeline timeline look like for an MLOps Level 2 team?",scenario_context:"Benchmarking your team's deployment velocity against the industry standard.",options:["Manual: days to weeks per deployment","Under 4 hours from code commit to production: code quality → integration test → full training → quality gates → Staging promotion → staging validation → production approval → deployment. Automated at every step except the production approval gate.",  "Always requires overnight batch processing","Impossible to automate — ML deployments always require manual steps"],correct_answer_index:1,explanation:"MLOps Level 2's defining characteristic is full CI/CD automation achieving sub-4-hour commit-to-production pipelines. This requires: automated training triggered by merges, automated quality gates blocking bad models, automated staging promotion, and (optionally) automated production approval via A/B test gates. The bottleneck shifts from automation to the quality gates — which is exactly right."},
          {question_text:"What is the 'Blue-Green' pipeline strategy for ML pipeline updates?",scenario_context:"Deploying a new feature engineering pipeline version that changes feature calculations for all scheduled training runs.",options:["Deploying to blue and green Kubernetes clusters","Running old and new pipeline versions simultaneously — validate the new version on a subset of training runs, monitor outputs and model quality, then migrate all scheduled jobs. Prevents the CACE principle from causing a 'pipeline update breaks all models simultaneously' catastrophe.",  "A testing strategy for color prediction models","A cost optimization technique for pipeline compute"],correct_answer_index:1,explanation:"Pipeline changes trigger the CACE principle — changing feature engineering changes all models that use those features. Blue-Green pipeline deployment validates the new pipeline on some training runs before migrating all scheduled runs, catching unexpected quality impacts before they affect all production models simultaneously."}
        ]
      }
    ],
    endQuizQuestions: [
      {question_text:"What is 'training-serving skew' and what architectural pattern prevents it?",scenario_context:"Your model performs well in offline evaluation but 10% worse in production.",options:["A scheduling conflict between training and serving","Features computed differently at training time (batch SQL) vs. serving time (real-time API) — the model learns patterns from training features that don't exist in serving features. Feature stores with shared feature definitions for offline and online serving prevent this.",  "A model that trains faster than it serves","An imbalance between training and production data sizes"],correct_answer_index:1,explanation:"Training-serving skew is one of the most common and most damaging production ML failures. The fix requires sharing feature computation logic between training (offline store) and serving (online store) — the feature store's central value proposition. Chip Huyen dedicates an entire chapter to this in Designing Machine Learning Systems because it's that impactful."},
      {question_text:"What is 'data freshness SLA' and why does violating it degrade model performance?",scenario_context:"Your real-time fraud model uses a feature 'purchases_last_hour' that's been stale for 6 hours.",options:["How recently the model was trained","The maximum acceptable time between feature computation and feature use in serving. A staleness_SLA violation means 'purchases_last_hour' shows yesterday's values — the model makes decisions on outdated context, degrading real-time fraud detection accuracy.",  "The age of the training dataset","The time between model deployments"],correct_answer_index:1,explanation:"Real-time models require real-time features. A 'purchases_last_hour' feature that's 6 hours stale is worse than useless — it's misleading. Feature freshness SLA monitoring alerts when materialization jobs fail silently, preventing stale features from degrading model decisions without any visible infrastructure failure."},
      {question_text:"What is 'shadow mode' in the context of ML model deployment and evaluation?",scenario_context:"You want to validate a new model's behavior with production traffic without any user impact.",options:["Running models in development environments","The new model receives all production traffic and computes predictions, but results are logged rather than served. Enables full production distribution validation — real traffic patterns, real data, zero user impact. When shadow mode metrics satisfy quality thresholds, the model promotes to canary or full deployment.",  "A backup model during outages","Testing models on synthetic data"],correct_answer_index:1,explanation:"Shadow mode provides the highest-fidelity production validation with zero risk. The new model processes the same requests as the production model — every prediction logged for comparison. This catches issues that offline evaluation misses: production data distribution differences, serving environment bugs, and edge cases not in the test set."},
      {question_text:"What is the 'ML Flywheel' and which companies have built the strongest competitive moats with it?",scenario_context:"Explaining the long-term strategic value of investing in ML data infrastructure.",options:["A mechanical component in AI robots","More users → more interaction data → better models → better products → more users. The compounding loop creates competitive moats that widen over time. Netflix (viewing data → better recommendations), Spotify (listening data → better discovery), Amazon (purchase data → better recommendations) have the strongest ML flywheels.",  "A hardware accelerator for model training","A metaphor for circular reasoning in ML research"],correct_answer_index:1,explanation:"The ML Flywheel is a virtuous cycle where data compounds into competitive advantage. Companies that invest in data collection infrastructure early (implicit feedback, user interactions, outcome labels) build flywheels that competitors cannot replicate — you can copy the model architecture but not 20 years of Netflix viewing data. MLOps infrastructure is what keeps the flywheel spinning efficiently."},
      {question_text:"What is Chip Huyen's insight about the '5% vs 95%' of ML work?",scenario_context:"Evaluating why your team's models don't reach production despite excellent offline metrics.",options:["Models only need to be 5% better than random","ML education focuses on model development (5% of production work: algorithm selection, hyperparameter tuning) while ignoring the 95% of work involved in data pipelines, serving infrastructure, monitoring systems, and operational processes. The 87% production gap reflects this educational mismatch.",  "Only 5% of features matter for ML models","Models should only be trained on 5% of available data"],correct_answer_index:1,explanation:"Huyen's observation from Designing Machine Learning Systems names the exact problem: the ML curriculum (and most ML competitions) focus on model performance on fixed datasets — the 5%. Production success requires the remaining 95%: reliable data collection, feature engineering, serving, monitoring, and iteration. MLOps is the discipline that teaches the 95%."},
      {question_text:"What is the 'Fail Loudly' principle for ML data pipelines?",scenario_context:"Your feature pipeline produces incorrect values silently — the model degrades without any alerts.",options:["Always use loud logging frameworks","Data pipelines should throw exceptions, trigger alerts, and halt execution when data quality checks fail — rather than producing incorrect results silently. A pipeline that produces wrong values without failing is more dangerous than one that fails with a clear error. Great Expectations implements this pattern.",  "Announcing pipeline failures publicly","Using verbose error messages"],correct_answer_index:1,explanation:"Silent data corruption is the most dangerous ML failure mode. A pipeline that produces wrong feature values continues running, training models on corrupted data, deploying those models to production — all without any alerts. The 'Fail Loudly' principle ensures data quality failures halt the pipeline and alert engineers immediately, preventing silent corruption from propagating."},
      {question_text:"What is the difference between 'online learning' and 'continual learning' in production ML?",scenario_context:"Deciding whether to update your recommendation model in real-time or through scheduled retraining.",options:["They are the same concept","Online learning: update model weights in real-time with each new example (fast adaptation, risk of catastrophic forgetting, convergence instability). Continual learning: periodic retraining on accumulated data batches preserving past knowledge (more stable, slight latency in adapting to new patterns). Most production systems use continual learning.",  "Online learning only works for classification","Continual learning is only for research"],correct_answer_index:1,explanation:"Online learning's real-time weight updates create instability risks (catastrophic forgetting of past patterns, convergence issues from noisy individual samples). Most production systems use continual learning — scheduled retraining on recent data batches, with quality gates ensuring new model doesn't regress. The exception: recommendation systems with explicit real-time feedback signals sometimes implement controlled online updates."},
      {question_text:"What is 'feature leakage' in ML pipelines and how does it produce falsely optimistic offline metrics?",scenario_context:"Your model achieves 97% accuracy in offline evaluation but only 71% in production.",options:["Features that escape the feature store","Including information in training features that wouldn't be available at prediction time — future information, target variable proxies, or post-event features. The model learns a shortcut (the leaked feature) that's available at training time but not production time, producing falsely high offline accuracy.",  "Features with high cardinality","Features that take too long to compute"],correct_answer_index:1,explanation:"Feature leakage is among the most damaging and hardest-to-detect ML pipeline failures. A 97% offline accuracy dropping to 71% in production is a classic signal. Leakage sources: using the target variable itself as a feature, using post-event data (a feature created after the event being predicted), or including information from future timestamps. Systematic temporal validation is the detection method."},
      {question_text:"What is the 'model staleness' problem and how does scheduled retraining address it?",scenario_context:"A model trained 12 months ago continues serving production traffic with declining accuracy.",options:["Models become outdated because of hardware changes","As time passes, the training data distribution diverges from current production data — a model trained on last year's patterns makes predictions based on relationships that no longer hold. Scheduled retraining (weekly, monthly) keeps the model's learned patterns current with actual data relationships.",  "Model files become corrupted over time","Older models use more compute resources"],correct_answer_index:1,explanation:"Model staleness is an instance of concept drift — the relationship between features and labels changes as the world changes. A fraud model trained on 2023 attack patterns misses 2024 attack patterns. Scheduled retraining on a rolling window of recent data ensures the model's learned patterns reflect current reality rather than historical patterns."},
      {question_text:"What is the 'Two-Sigma Problem' in ML model deployment and how does A/B testing address it?",scenario_context:"Your model shows improvement in offline metrics but you need statistical evidence of production improvement.",options:["A model with two standard deviations of error","Offline metrics improve but production impact is uncertain — offline test set may not represent production distribution (test set leakage, distribution shift). A/B testing with statistical significance testing (p < 0.05, minimum detectable effect size calculation) provides rigorous evidence that offline improvement translates to production improvement.",  "A two-model ensemble approach","A regulatory requirement for financial models"],correct_answer_index:1,explanation:"Offline evaluation, however careful, can't fully replicate production. A/B testing with proper statistical design (pre-registered hypothesis, power calculation for minimum detectable effect, controlled experiment with random assignment) provides the gold standard evidence that a model improvement is real and generalizes to production traffic."}
    ]
  }]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const { data: ex } = await supabase.from("courses").select("id").eq("title", courseData.title).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({
      title: courseData.title, description: courseData.description, is_published: true,
      translations: {
        es:{title:"Ingeniero MLOps IA",description:"Domina el seguimiento de experimentos ML y pipelines de reentrenamiento automatizados."},
        fr:{title:"Ingénieur MLOps IA",description:"Maîtrisez le suivi d'expériences ML et les pipelines de réentraînement automatisés."},
        de:{title:"KI-MLOps-Ingenieur",description:"Meistern Sie ML-Experiment-Tracking und automatisierte Neutrainings-Pipelines."},
        zh:{title:"AI MLOps工程师",description:"掌握ML实验跟踪和自动化再训练流水线。"},
        ar:{title:"مهندس MLOps للذكاء الاصطناعي",description:"أتقن تتبع تجارب ML وخطوط إعادة التدريب الآلي."},
        ja:{title:"AI MLOpsエンジニア",description:"ML実験追跡と自動再学習パイプラインをマスターする。"}
      }
    }).select().single();
    if (ce) throw ce;
    for (const ch of courseData.chapters) {
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: ch.title, description: ch.description, order_index: ch.order_index, translations: {} }).select().single();
      if (che) throw che;
      for (const vid of ch.videos) {
        const transcript = vid.lessonScript.mainPoints.join("\n\n");
        const trans = { en:{title:vid.title,transcript}, es:{title:vid.title,transcript}, fr:{title:vid.title,transcript}, de:{title:vid.title,transcript}, zh:{title:vid.title,transcript}, ar:{title:vid.title,transcript}, ja:{title:vid.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: vid.title, description: vid.description, order_index: vid.order_index, translations: trans }).select().single();
        if (ve) throw ve;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        for (let i = 0; i < vid.questions.length; i++) {
          const q = vid.questions[i];
          await supabase.from("quiz_questions").insert({ quiz_id: quiz.id, question_text: q.question_text, scenario_context: q.scenario_context, options: q.options, correct_answer_index: q.correct_answer_index, explanation: q.explanation, order_index: i });
        }
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      for (let i = 0; i < ch.endQuizQuestions.length; i++) {
        const q = ch.endQuizQuestions[i];
        await supabase.from("quiz_questions").insert({ quiz_id: eq.id, question_text: q.question_text, scenario_context: q.scenario_context, options: q.options, correct_answer_index: q.correct_answer_index, explanation: q.explanation, order_index: i });
      }
    }
    return new Response(JSON.stringify({ message: "AI MLOps Engineer — rich version seeded", courseId: course.id }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
