/**
 * moduleBoards — FOUNDER RULE: no two courses share a diagram, and every
 * module within every program has ITS OWN board. This registry assigns each
 * (program, module) a unique archetype + content pairing. Archetype shapes
 * may recur across the academy but never with the same content, and never
 * as the same rendered diagram.
 *
 * Module 1 of each program returns null → the program's signature board
 * (CourseBoardVisual) serves as Module 1's own diagram.
 */
import { ReactNode } from "react";
import {
  VennBoard, TreeBoard, PyramidBoard, MatrixBoard, ScaleBoard, ShieldBoard,
  FunnelBoard, NetworkBoard, StepsBoard, SwimlaneBoard, RadarBoard, CycleBoard,
  ChartBoard, FlowBoard,
} from "./BoardArchetypes";

export type ProgramKey = "scrum" | "pm" | "da" | "ba" | "cyber";

const SCRUM: Record<number, () => ReactNode> = {
  2: () => <VennBoard title="The Servant Leader" aria="The Scrum Master serves the team, the product owner and the organization" circles={[{ label: "Serves the Team", sub: "coach & unblock" }, { label: "Serves the PO", sub: "value & backlog" }, { label: "Serves the Org", sub: "adoption & change" }]} center="SCRUM MASTER" caption="one role · three services · zero command-and-control" />,
  3: () => <TreeBoard title="The Scrum Team" aria="One Scrum team with three accountabilities" root={{ label: "Scrum Team", sub: "one unit · one goal" }} children={[{ label: "Product Owner", sub: "maximizes value" }, { label: "Scrum Master", sub: "enables the system" }, { label: "Developers", sub: "build the increment" }]} caption="accountabilities, not job titles" />,
  4: () => <FlowBoard title="Sprint Planning" aria="Sprint planning flows from why to what to how, producing the sprint goal" steps={[{ label: "Why", sub: "sprint purpose" }, { label: "What", sub: "select items" }, { label: "How", sub: "plan the work" }, { label: "Forecast", sub: "capacity check" }]} result={{ label: "Sprint Goal", sub: "one commitment" }} caption="the team plans the sprint — nobody plans it for them" />,
  5: () => <SwimlaneBoard title="The Daily Scrum" aria="The daily scrum inspects progress toward the sprint goal in three lanes" lanes={[{ label: "Yesterday", sub: "what moved the Sprint Goal forward" }, { label: "Today", sub: "what will move it next" }, { label: "Impediments", sub: "what is blocking the goal" }]} caption="15 minutes · developers talking to developers" />,
  6: () => <ScaleBoard title="Review & Retrospective" aria="Sprint review inspects the product while the retrospective inspects the process" left={{ label: "Sprint Review", sub: "inspect the PRODUCT" }} right={{ label: "Retrospective", sub: "inspect the PROCESS" }} pivot="Inspect & Adapt" caption="two inspections close every sprint" />,
  7: () => <NetworkBoard title="Artifacts & Commitments" aria="Three artifacts each carry a commitment for transparency" hub={{ label: "Transparency" }} nodes={[{ label: "Product Backlog", sub: "→ Product Goal" }, { label: "Sprint Backlog", sub: "→ Sprint Goal" }, { label: "Increment", sub: "→ Definition of Done" }]} caption="every artifact carries a commitment" />,
  8: () => <ShieldBoard title="Definition of Done" aria="The definition of done is a quality shield of gates each increment must pass" segments={[{ label: "Code complete & reviewed" }, { label: "Tested — automated & passing" }, { label: "Integrated & documented" }, { label: "Releasable — no work left" }]} core="NO INCREMENT PASSES UNDONE" caption="quality is not negotiable at sprint's end" />,
  9: () => <FunnelBoard title="Backlog Refinement" aria="Ideas are refined down into ready sprint items" stages={[{ label: "Ideas & Requests", sub: "everything enters here" }, { label: "Ordered", sub: "PO sequences by value" }, { label: "Refined", sub: "sized & understood" }, { label: "Ready", sub: "meets Definition of Ready" }]} caption="the backlog is a conversation, not a contract" />,
  10: () => <PyramidBoard title="Empiricism & Values" aria="Five scrum values stand on the three empirical pillars" levels={[{ label: "Transparency · Inspection · Adaptation", sub: "the three pillars" }, { label: "Commitment · Focus · Openness" }, { label: "Respect · Courage" }, { label: "TRUST" }]} caption="values make empiricism possible" />,
  11: () => <NetworkBoard title="Facilitation Mastery" aria="The facilitator connects every voice in the room" hub={{ label: "Facilitator", sub: "neutral" }} nodes={[{ label: "Divergence" }, { label: "Timebox" }, { label: "Every voice" }, { label: "Convergence" }, { label: "Decision" }]} caption="the room does the thinking — you hold the space" />,
  12: () => <StepsBoard title="Team Dynamics" aria="Teams climb from forming through storming and norming to performing" steps={[{ label: "Forming", sub: "polite & unsure" }, { label: "Storming", sub: "conflict surfaces" }, { label: "Norming", sub: "agreements form" }, { label: "Performing", sub: "flow & trust" }]} flag="High-performing" caption="conflict is a stage, not a failure" />,
  13: () => <MatrixBoard title="Stakeholder Engagement" aria="Stakeholders are mapped by power and interest into four strategies" axisX="Interest" axisY="Power" quadrants={[{ label: "Keep Satisfied" }, { label: "Manage Closely" }, { label: "Monitor" }, { label: "Keep Informed" }]} caption="map them before they surprise you" />,
  14: () => <FlowBoard title="Impediment Removal" aria="Impediments flow from detection through visibility and escalation to removal" steps={[{ label: "Detect", sub: "see the blocker" }, { label: "Make Visible", sub: "name it openly" }, { label: "Escalate", sub: "right level, fast" }, { label: "Remove", sub: "and prevent" }]} result={{ label: "Flow Restored", sub: "team unblocked" }} caption="an impediment named is an impediment half-removed" />,
  15: () => <ChartBoard title="Metrics & Forecasting" aria="A sprint burndown compares actual work remaining against the ideal line" kind="burndown" xLabel="Sprint days" yLabel="Work remaining" note="burndown — trend beats promise" caption="measure flow, not busyness" />,
  16: () => <TreeBoard title="Scaling Scrum" aria="One product with multiple teams coordinated through shared goals" root={{ label: "One Product", sub: "one Product Backlog" }} children={[{ label: "Team A", sub: "cross-functional" }, { label: "Team B", sub: "cross-functional" }, { label: "Team C", sub: "cross-functional" }, { label: "Nexus / SAFe", sub: "coordination layer" }]} caption="scale the product, not the bureaucracy" />,
  17: () => <VennBoard title="AI for the Scrum Master" aria="Human judgment and AI leverage overlap to create the augmented scrum master" circles={[{ label: "Human Judgment", sub: "context · empathy · ethics" }, { label: "AI Leverage", sub: "signals · drafts · forecasts" }]} center="AUGMENTED SM" caption="ai amplifies the master — it never replaces the mastery" />,
  18: () => <StepsBoard title="Career Transformation" aria="The capstone climbs from certification through portfolio and interviews to career" steps={[{ label: "Capstone", sub: "prove it" }, { label: "Portfolio", sub: "show it" }, { label: "Interviews", sub: "tell it" }, { label: "Offer", sub: "land it" }, { label: "Career", sub: "grow it" }]} flag="Scrum Master" caption="the last module is the first day of the career" />,
};

const PM: Record<number, () => ReactNode> = {
  2: () => <FunnelBoard title="Initiation Funnel" aria="Ideas narrow through business case and charter to an approved project" stages={[{ label: "Ideas & Demands", sub: "everything competes" }, { label: "Business Case", sub: "benefits vs cost" }, { label: "Charter", sub: "mandate & authority" }, { label: "Approved Project", sub: "sponsored & funded" }]} caption="no charter, no project" />,
  3: () => <TreeBoard title="Work Breakdown Structure" aria="The project decomposes into deliverables and work packages" root={{ label: "Project Scope", sub: "100% rule" }} children={[{ label: "Deliverable 1", sub: "work packages" }, { label: "Deliverable 2", sub: "work packages" }, { label: "Deliverable 3", sub: "work packages" }, { label: "Deliverable 4", sub: "work packages" }]} caption="if it's not in the wbs, it's not in the project" />,
  4: () => <NetworkBoard title="Critical Path" aria="Activities network where the longest dependent chain sets the schedule" hub={{ label: "Milestone", sub: "delivery" }} nodes={[{ label: "A · 4d" }, { label: "B · 6d" }, { label: "C · 3d" }, { label: "D · 8d" }, { label: "E · 5d" }]} caption="the critical path owns your end date — know it by heart" />,
  5: () => <MatrixBoard title="Risk Assessment" aria="Risks are mapped by probability and impact into four responses" axisX="Impact" axisY="Probability" quadrants={[{ label: "Mitigate" }, { label: "Avoid / Act Now" }, { label: "Accept" }, { label: "Transfer / Watch" }]} caption="a risk register nobody reads is a risk itself" />,
  6: () => <ChartBoard title="Earned Value" aria="Planned value, earned value and actual cost curves reveal true progress" kind="scurve" xLabel="Time" yLabel="Value" note="EV vs PV vs AC — the truth curve" caption="percent spent is not percent done" />,
  7: () => <SwimlaneBoard title="Communication Plan" aria="Each audience gets its own channel cadence and message" lanes={[{ label: "Sponsor", sub: "monthly steering · decisions & risks" }, { label: "Stakeholders", sub: "biweekly summary · progress & asks" }, { label: "Team", sub: "daily standup · work & blockers" }, { label: "PMO", sub: "weekly report · metrics & baseline" }]} caption="right message · right audience · right rhythm" />,
  8: () => <PyramidBoard title="High-Performance Teams" aria="Team performance builds from trust through conflict and commitment to results" levels={[{ label: "Trust", sub: "the foundation" }, { label: "Healthy Conflict" }, { label: "Commitment" }, { label: "Accountability" }, { label: "RESULTS" }]} caption="results sit on trust — never the reverse" />,
  9: () => <FlowBoard title="Procurement Lifecycle" aria="Procurement flows from planning through solicitation and selection to closure" steps={[{ label: "Plan", sub: "make or buy" }, { label: "Solicit", sub: "RFP / RFQ" }, { label: "Select", sub: "evaluate & award" }, { label: "Administer", sub: "manage contract" }]} result={{ label: "Close-out", sub: "obligations met" }} caption="the contract is the relationship's constitution" />,
  10: () => <ShieldBoard title="Quality Gates" aria="Quality is protected by planning assurance control and acceptance gates" segments={[{ label: "Plan quality — define 'good'" }, { label: "Assure — audit the process" }, { label: "Control — inspect the output" }, { label: "Accept — customer signs off" }]} core="QUALITY IS PLANNED, NOT INSPECTED IN" caption="grade is a choice · quality is a duty" />,
  11: () => <CycleBoard title="Agile Delivery Loop" aria="Agile projects iterate through planning building reviewing and adapting" nodes={[{ label: "Plan", sub: "iteration" }, { label: "Build", sub: "increment" }, { label: "Review", sub: "demo & feedback" }, { label: "Adapt", sub: "reprioritize" }]} center={{ label: "VALUE", sub: "every loop" }} caption="deliver in loops, not in leaps of faith" />,
  12: () => <StepsBoard title="The Change Curve" aria="People move through denial and resistance to exploration and commitment" steps={[{ label: "Denial", sub: "'not happening'" }, { label: "Resistance", sub: "'not to me'" }, { label: "Exploration", sub: "'maybe how?'" }, { label: "Commitment", sub: "'this is us'" }]} flag="Adopted" caption="projects change systems — change management changes people" />,
  13: () => <NetworkBoard title="Portfolio Alignment" aria="Programs and projects connect to one strategy hub" hub={{ label: "Strategy", sub: "the why" }} nodes={[{ label: "Program A" }, { label: "Program B" }, { label: "Project X" }, { label: "Project Y" }, { label: "Ops" }]} caption="a portfolio is strategy expressed in money and time" />,
  14: () => <SwimlaneBoard title="Tech Delivery Streams" aria="Digital delivery runs discovery build integration and cutover lanes in parallel" lanes={[{ label: "Discovery", sub: "user needs · feasibility · spikes" }, { label: "Build", sub: "sprints · demos · increments" }, { label: "Integration", sub: "APIs · data · environments" }, { label: "Cutover", sub: "migration · training · go-live" }]} caption="digital projects fail at the seams — manage the seams" />,
  15: () => <RadarBoard title="PM Analytics" aria="A radar of delivery health metrics" axes={[{ label: "Schedule" }, { label: "Budget" }, { label: "Scope" }, { label: "Risk" }, { label: "Quality" }, { label: "Team" }]} caption="one glance · six truths · zero surprises" />,
  16: () => <ScaleBoard title="Executive Trade-offs" aria="Leaders balance speed against certainty when presenting to executives" left={{ label: "Speed", sub: "time-to-market" }} right={{ label: "Certainty", sub: "predictability" }} pivot="Executive Decision" caption="executives buy clarity — bring options, not problems" />,
  17: () => <VennBoard title="Responsible Delivery" aria="Ethics governance and AI overlap in responsible project leadership" circles={[{ label: "Ethics", sub: "should we?" }, { label: "Governance", sub: "who decides?" }, { label: "AI Capability", sub: "can we?" }]} center="RESPONSIBLE PM" caption="just because the model can, doesn't mean the project should" />,
  18: () => <StepsBoard title="PMP & Beyond" aria="The career ladder from certification to executive delivery leadership" steps={[{ label: "PMP Exam", sub: "the credential" }, { label: "Portfolio", sub: "proof of work" }, { label: "Senior PM", sub: "bigger stakes" }, { label: "Program Lead", sub: "many streams" }, { label: "Delivery Exec", sub: "the org's engine" }]} flag="Career" caption="certification opens the door — delivery keeps it open" />,
};

const DA: Record<number, () => ReactNode> = {
  1: () => <FlowBoard title="Data-to-Insight Pipeline" aria="Analysis flows from question through data and analysis to decision" steps={[{ label: "Question", sub: "what to decide?" }, { label: "Data", sub: "find & trust it" }, { label: "Analysis", sub: "SQL & stats" }, { label: "Insight", sub: "so what?" }]} result={{ label: "Decision", sub: "action taken" }} caption="analysts don't produce charts — they produce decisions" />,
  2: () => <SwimlaneBoard title="How SQL Executes" aria="SQL clauses execute in a fixed order from FROM to ORDER BY" lanes={[{ label: "FROM · JOIN", sub: "assemble the tables" }, { label: "WHERE", sub: "filter the rows" }, { label: "GROUP · HAVING", sub: "aggregate & filter groups" }, { label: "SELECT · ORDER", sub: "shape & sort the answer" }]} caption="write in one order — think in execution order" />,
  3: () => <StepsBoard title="SQL Mastery Ladder" aria="SQL skills climb from window functions to optimization" steps={[{ label: "ROW_NUMBER", sub: "rank in partitions" }, { label: "LAG / LEAD", sub: "row vs row" }, { label: "CTEs", sub: "readable logic" }, { label: "Optimization", sub: "plans & indexes" }]} flag="SQL Master" caption="window functions are where analysts become engineers" />,
  5: () => <FunnelBoard title="The ETL Funnel" aria="Raw data narrows through cleaning and transformation into trusted data" stages={[{ label: "Raw Sources", sub: "messy · duplicated · wild" }, { label: "Extracted", sub: "landed & versioned" }, { label: "Cleaned", sub: "typed · deduped · valid" }, { label: "Transformed", sub: "modeled for questions" }]} caption="garbage in stays garbage — clean before you count" />,
  6: () => <ChartBoard title="The Normal Distribution" aria="The bell curve with mean and standard deviations" kind="bell" xLabel="Value" yLabel="Frequency" note="68% within ±1σ" caption="know the shape of your data before you trust its average" />,
  7: () => <ScaleBoard title="Hypothesis Testing" aria="Evidence weighs the null hypothesis against the alternative" left={{ label: "H₀ · Null", sub: "no effect" }} right={{ label: "H₁ · Alternative", sub: "real effect" }} pivot="p < 0.05 ?" caption="the data doesn't prove — it weighs" />,
  8: () => <MatrixBoard title="Chart Chooser" aria="Chart types map to comparison relationship distribution and composition" axisX="Data points" axisY="Variables" quadrants={[{ label: "Comparison", sub: "bar" }, { label: "Relationship", sub: "scatter" }, { label: "Distribution", sub: "histogram" }, { label: "Composition", sub: "stacked" }]} caption="the question picks the chart — not the aesthetics" />,
  9: () => <TreeBoard title="Dashboard Hierarchy" aria="Dashboards drill from executive summary to detail" root={{ label: "Executive View", sub: "5-second answer" }} children={[{ label: "KPI Cards", sub: "state at a glance" }, { label: "Trends", sub: "direction & pace" }, { label: "Breakdowns", sub: "by segment" }, { label: "Drill-through", sub: "row-level truth" }]} caption="powerbi & tableau reward hierarchy, punish clutter" />,
  10: () => <PyramidBoard title="BI Architecture" aria="Business intelligence stacks from sources through warehouse to KPIs" levels={[{ label: "Sources", sub: "apps · APIs · files" }, { label: "Warehouse / Lakehouse" }, { label: "Semantic Model", sub: "one truth" }, { label: "KPIs & Reports" }]} caption="every metric argument is a missing semantic layer" />,
  11: () => <ShieldBoard title="BI Governance" aria="Governance shields certified data definitions access and refresh" segments={[{ label: "Certified datasets only" }, { label: "One metric dictionary" }, { label: "Access by role" }, { label: "Refresh SLAs honored" }]} core="SELF-SERVE ≠ SELF-INVENTED" caption="governance is what makes self-serve trustworthy" />,
  12: () => <ChartBoard title="Time Series & Forecast" aria="A time series with trend and seasonality projected forward" kind="timeseries" xLabel="Time" yLabel="Metric" note="trend + seasonality + noise" caption="the past has patterns — the forecast borrows them" />,
  13: () => <ChartBoard title="Regression & Prediction" aria="A scatter plot with a fitted regression line" kind="scatter" xLabel="Driver (x)" yLabel="Outcome (y)" note="ŷ = a + bx" caption="correlation earns a model — causation earns a decision" />,
  14: () => <VennBoard title="NL-to-SQL Analytics" aria="Natural language and SQL overlap in AI-augmented analysis" circles={[{ label: "Natural Language", sub: "the question" }, { label: "SQL / Code", sub: "the computation" }]} center="AI ANALYST" caption="ai writes the query — you own the answer" />,
  15: () => <CycleBoard title="The ML Loop" aria="Machine learning iterates through data features training and evaluation" nodes={[{ label: "Data", sub: "collect & label" }, { label: "Features", sub: "engineer" }, { label: "Train", sub: "fit model" }, { label: "Evaluate", sub: "test honestly" }, { label: "Deploy", sub: "and monitor" }]} center={{ label: "ITERATE" }} caption="a model is never done — it's only currently useful" />,
  16: () => <NetworkBoard title="Decision Intelligence" aria="A decision hub connects data models risks and options" hub={{ label: "Decision", sub: "the point" }} nodes={[{ label: "Data" }, { label: "Models" }, { label: "Options" }, { label: "Risks" }, { label: "Stakes" }]} caption="analytics ends where a decision begins" />,
  17: () => <FunnelBoard title="Data Storytelling" aria="Analysis narrows into a story an executive can act on" stages={[{ label: "All the Analysis", sub: "everything you found" }, { label: "What Matters", sub: "the 3 things" }, { label: "The Story", sub: "context → conflict → resolution" }, { label: "The Ask", sub: "one clear action" }]} caption="executives remember stories, not spreadsheets" />,
  18: () => <NetworkBoard title="Data Governance Mesh" aria="Governance connects quality privacy ethics and ownership around trusted data" hub={{ label: "Trusted Data" }} nodes={[{ label: "Quality" }, { label: "Privacy" }, { label: "Ethics" }, { label: "Ownership" }, { label: "Lineage" }, { label: "Capstone" }]} caption="the capstone: analysis people can bet the company on" />,
};

const BA: Record<number, () => ReactNode> = {
  2: () => <RadarBoard title="The BA Competency Wheel" aria="Business analyst competencies across six dimensions" axes={[{ label: "Elicitation" }, { label: "Analysis" }, { label: "Modeling" }, { label: "Facilitation" }, { label: "Communication" }, { label: "AI Toolkit" }]} caption="the wheel turns together — grow every spoke" />,
  3: () => <NetworkBoard title="Stakeholder Map" aria="The business analyst connects sponsors users SMEs vendors and delivery" hub={{ label: "The BA", sub: "trusted bridge" }} nodes={[{ label: "Sponsor", sub: "funds it" }, { label: "Users", sub: "live it" }, { label: "SMEs", sub: "know it" }, { label: "Delivery", sub: "build it" }, { label: "Vendors", sub: "supply it" }]} caption="influence flows along relationships — map them first" />,
  4: () => <NetworkBoard title="Elicitation Techniques" aria="Elicitation techniques radiate from the requirement goal" hub={{ label: "True Need", sub: "not the ask" }} nodes={[{ label: "Interviews" }, { label: "Workshops" }, { label: "Observation" }, { label: "Surveys" }, { label: "Documents" }, { label: "Prototypes" }]} caption="the stated requirement is a clue, not the answer" />,
  5: () => <CycleBoard title="Workshop Leadership" aria="Workshops cycle through preparation opening divergence convergence and commitment" nodes={[{ label: "Prepare", sub: "purpose & people" }, { label: "Open", sub: "frame & rules" }, { label: "Diverge", sub: "all options" }, { label: "Converge", sub: "decide" }, { label: "Commit", sub: "owners & dates" }]} center={{ label: "OUTCOME" }} caption="a workshop without a decision is a meeting" />,
  6: () => <TreeBoard title="Requirements Taxonomy" aria="Requirements branch into business stakeholder solution and transition types" root={{ label: "Requirements", sub: "traceable tree" }} children={[{ label: "Business", sub: "the why" }, { label: "Stakeholder", sub: "the who needs" }, { label: "Solution", sub: "the what" }, { label: "Transition", sub: "the getting there" }]} caption="every solution requirement traces up to a business why" />,
  7: () => <SwimlaneBoard title="BPMN Process Lanes" aria="A BPMN process crosses customer, front office and back office lanes" lanes={[{ label: "Customer", sub: "request → receive value" }, { label: "Front Office", sub: "capture → validate → confirm" }, { label: "Back Office", sub: "process → approve → fulfill" }, { label: "Systems", sub: "record → route → notify" }]} caption="processes fail at hand-offs — model the hand-offs" />,
  8: () => <PyramidBoard title="Business Architecture" aria="Business architecture stacks strategy capabilities processes and systems" levels={[{ label: "Systems & Data", sub: "what runs it" }, { label: "Processes", sub: "how work flows" }, { label: "Capabilities", sub: "what the business can do" }, { label: "Strategy", sub: "where it's going" }]} caption="architecture is strategy made buildable" />,
  9: () => <VennBoard title="Product Strategy" aria="Desirability viability and feasibility overlap at a winning product" circles={[{ label: "Desirable", sub: "users want it" }, { label: "Viable", sub: "business sustains it" }, { label: "Feasible", sub: "tech can build it" }]} center="WINNING PRODUCT" caption="two circles make a hobby — three make a product" />,
  10: () => <FunnelBoard title="Discovery Funnel" aria="Opportunities narrow through experiments and validation into the backlog" stages={[{ label: "Opportunities", sub: "problems worth solving" }, { label: "Hypotheses", sub: "riskiest assumptions" }, { label: "Experiments", sub: "cheapest tests" }, { label: "Validated", sub: "evidence-backed" }]} caption="kill ideas cheaply — before they kill the roadmap" />,
  11: () => <MatrixBoard title="Decision Analysis" aria="Options are scored against value and effort" axisX="Value" axisY="Effort" quadrants={[{ label: "Quick Wins", sub: "low effort · high value" }, { label: "Big Bets", sub: "invest deliberately" }, { label: "Fill-ins", sub: "when idle" }, { label: "Money Pits", sub: "decline politely" }]} caption="decision intelligence: score it before you argue it" />,
  12: () => <ScaleBoard title="Solution Acceptance" aria="Delivered capability is weighed against expected value at acceptance" left={{ label: "Expected", sub: "acceptance criteria" }} right={{ label: "Delivered", sub: "actual capability" }} pivot="Accept?" caption="evaluation closes the loop the business case opened" />,
  13: () => <FlowBoard title="AI-Augmented BA" aria="AI assists each step from elicitation through drafting to human validation" steps={[{ label: "Elicit", sub: "human conversation" }, { label: "AI Draft", sub: "stories & models" }, { label: "Validate", sub: "human judgment" }, { label: "Refine", sub: "together" }]} result={{ label: "Better, Faster", sub: "never blinder" }} caption="ai drafts · the analyst decides" />,
  14: () => <ShieldBoard title="Risk & Compliance" aria="Regulatory risk and compliance shield the change the BA delivers" segments={[{ label: "Know the regulation" }, { label: "Trace requirements to controls" }, { label: "Evidence the compliance" }, { label: "Audit without fear" }]} core="COMPLIANCE IS A REQUIREMENT TYPE" caption="the ba who reads the regulation owns the room" />,
  15: () => <StepsBoard title="Capstone Journey" aria="The capstone climbs from discovery to transformation" steps={[{ label: "Discover", sub: "real problem" }, { label: "Analyze", sub: "real data" }, { label: "Design", sub: "real solution" }, { label: "Present", sub: "real executives" }]} flag="Certified BA" caption="discovery to transformation — the whole craft, once through" />,
  16: () => <CycleBoard title="Agile BA Ceremonies" aria="The agile BA cycles through refinement planning building and review" nodes={[{ label: "Refine", sub: "stories ready" }, { label: "Plan", sub: "sprint scope" }, { label: "Support", sub: "answer fast" }, { label: "Review", sub: "accept & learn" }]} center={{ label: "VALUE FLOW" }} caption="the agile ba works one sprint ahead and one behind" />,
  17: () => <TreeBoard title="Scaling the BA Craft" aria="BA practice scales from team to program to portfolio levels" root={{ label: "Enterprise BA", sub: "one practice" }} children={[{ label: "Team BA", sub: "stories & sprints" }, { label: "Program BA", sub: "features & PI" }, { label: "Portfolio BA", sub: "epics & strategy" }]} caption="safe & less scale the role — the craft stays the same" />,
  18: () => <PyramidBoard title="Transformation Stack" aria="Digital transformation builds from systems through architecture to enterprise change" levels={[{ label: "Legacy Reality", sub: "where we are" }, { label: "Target Architecture" }, { label: "Roadmap & Waves" }, { label: "TRANSFORMED ENTERPRISE" }]} caption="transformation is architecture with a deadline" />,
};

const CYBER: Record<number, () => ReactNode> = {
  2: () => <SwimlaneBoard title="SOC Operations" aria="Security operations tier lanes from triage to hunt" lanes={[{ label: "Tier 1 · Triage", sub: "alerts → validate → route (SIEM)" }, { label: "Tier 2 · Investigate", sub: "correlate → contain (EDR/XDR)" }, { label: "Tier 3 · Hunt", sub: "hypothesis → hunt → harden" }, { label: "Engineering", sub: "rules → tuning → coverage" }]} caption="the soc is a pipeline for turning noise into action" />,
  3: () => <PyramidBoard title="Cloud Shared Responsibility" aria="Cloud security responsibility layers between provider and customer" levels={[{ label: "Physical & Hypervisor", sub: "provider" }, { label: "Network & Platform", sub: "shared" }, { label: "OS · Containers · Apps", sub: "customer" }, { label: "DATA & IDENTITY", sub: "always yours" }]} caption="the cloud secures the cloud — you secure what's in it" />,
  4: () => <NetworkBoard title="The Attack Path" aria="Penetration testing maps the attack path across exposed nodes" hub={{ label: "Crown Jewels", sub: "target" }} nodes={[{ label: "Recon" }, { label: "Exposed Web" }, { label: "Weak Creds" }, { label: "Lateral Move" }, { label: "Priv-Esc" }]} caption="pentesters walk the graph your defenses forgot" />,
  5: () => <CycleBoard title="DevSecOps Loop" aria="Security is built into every stage of the delivery loop" nodes={[{ label: "Plan", sub: "threat model" }, { label: "Code", sub: "SAST · secrets" }, { label: "Build", sub: "SCA · sign" }, { label: "Deploy", sub: "IaC scan" }, { label: "Run", sub: "monitor · WAF" }]} center={{ label: "SHIFT LEFT" }} caption="security at the end costs 100× security at the start" />,
  6: () => <FlowBoard title="DFIR Chain" aria="Digital forensics flows from preservation through analysis to lessons" steps={[{ label: "Preserve", sub: "chain of custody" }, { label: "Collect", sub: "images & logs" }, { label: "Analyze", sub: "timeline & artifacts" }, { label: "Report", sub: "defensible findings" }]} result={{ label: "Lessons Learned", sub: "harden & train" }} caption="evidence mishandled is evidence lost" />,
  7: () => <TreeBoard title="GRC Foundations" aria="GRC branches into governance risk and compliance disciplines" root={{ label: "GRC", sub: "one program" }} children={[{ label: "Governance", sub: "who decides & how" }, { label: "Risk", sub: "what could hurt us" }, { label: "Compliance", sub: "what we must prove" }]} caption="grc is security speaking the board's language" />,
  8: () => <ShieldBoard title="SOC 2 Trust Criteria" aria="SOC 2 shields security availability integrity confidentiality and privacy" segments={[{ label: "Security", sub: "the common criteria" }, { label: "Availability" }, { label: "Processing Integrity" }, { label: "Confidentiality" }, { label: "Privacy" }]} core="TYPE II = PROVEN OVER TIME" caption="soc 2 is trust, evidenced" />,
  9: () => <StepsBoard title="ISO 27001 Journey" aria="ISO 27001 implementation climbs from gap analysis to certification" steps={[{ label: "Gap Analysis", sub: "where we stand" }, { label: "ISMS Design", sub: "scope & SoA" }, { label: "Controls", sub: "Annex A live" }, { label: "Internal Audit", sub: "find it first" }, { label: "Certification", sub: "stage 1 & 2" }]} flag="ISO 27001" caption="the isms is a system, not a binder" />,
  10: () => <MatrixBoard title="Privacy Obligations" aria="Privacy work maps by data sensitivity and subject rights" axisX="Data sensitivity" axisY="Subject rights" quadrants={[{ label: "Minimize", sub: "collect less" }, { label: "Protect Hard", sub: "encrypt · restrict" }, { label: "Standard Care", sub: "baseline controls" }, { label: "Honor Fast", sub: "DSARs on clock" }]} caption="gdpr & hipaa: the data you don't hold can't hurt you" />,
  11: () => <FunnelBoard title="Vendor Risk Funnel" aria="Vendors narrow through assessment and contracting into monitored partners" stages={[{ label: "All Vendors", sub: "the full inventory" }, { label: "Risk-Tiered", sub: "by data & access" }, { label: "Assessed", sub: "questionnaires & evidence" }, { label: "Contracted", sub: "DPAs & SLAs signed" }]} caption="your security perimeter includes their security" />,
  12: () => <VennBoard title="AI × Security" aria="Securing AI using AI and governing AI overlap in one discipline" circles={[{ label: "Secure the AI", sub: "models under attack" }, { label: "AI for Security", sub: "detection & response" }, { label: "Govern the AI", sub: "policy & accountability" }]} center="AI SECURITY PRO" caption="three fronts · one professional" />,
  13: () => <NetworkBoard title="Identity Fabric" aria="Identity connects MFA SSO PAM RBAC and lifecycle around each person" hub={{ label: "Identity", sub: "the new perimeter" }} nodes={[{ label: "MFA" }, { label: "SSO" }, { label: "PAM", sub: "privileged" }, { label: "RBAC" }, { label: "Lifecycle", sub: "join→move→leave" }]} caption="attackers don't hack in — they log in" />,
  14: () => <RadarBoard title="Threat Intel Coverage" aria="Threat intelligence coverage across sources and disciplines" axes={[{ label: "OSINT" }, { label: "IOCs" }, { label: "TTPs" }, { label: "Dark Web" }, { label: "ISACs" }, { label: "Hunting" }]} caption="know the adversary better than they know you" />,
  15: () => <FlowBoard title="SOAR Playbook" aria="Automation flows from trigger through enrichment and decision to action" steps={[{ label: "Trigger", sub: "alert fires" }, { label: "Enrich", sub: "context added" }, { label: "Decide", sub: "auto or human" }, { label: "Act", sub: "contain & notify" }]} result={{ label: "Learn", sub: "tune the playbook" }} caption="automate the repeatable — escalate the judgment" />,
  16: () => <ScaleBoard title="Audit Readiness" aria="Control cost weighs against assurance in executive communication" left={{ label: "Control Cost", sub: "friction & spend" }} right={{ label: "Assurance", sub: "evidence & trust" }} pivot="Board Story" caption="auditors want evidence — boards want confidence" />,
  17: () => <PyramidBoard title="The CISO Track" aria="Security leadership climbs from operator to boardroom" levels={[{ label: "Operator", sub: "hands on keyboard" }, { label: "Manager", sub: "team & program" }, { label: "Strategist", sub: "risk & roadmap" }, { label: "CISO", sub: "boardroom voice" }]} caption="the ciso translates packets into P&L" />,
  18: () => <ChartBoard title="Capstone Engagement" aria="The security program maturity S-curve across the full engagement" kind="scurve" xLabel="Engagement timeline" yLabel="Security maturity" note="assess → build → prove" caption="the capstone: one enterprise, end to end" />,
  19: () => <StepsBoard title="2030 → 2050 Horizon" aria="Security careers climb through the autonomous-SOC quantum and agentic eras" steps={[{ label: "2030", sub: "autonomous SOC" }, { label: "2035", sub: "post-quantum shift" }, { label: "2040", sub: "agentic defense" }, { label: "2050", sub: "trust architects" }]} flag="Your Career" caption="the future is a threat model — and a job description" />,
};

const REGISTRY: Record<ProgramKey, Record<number, () => ReactNode>> = {
  scrum: SCRUM, pm: PM, da: DA, ba: BA, cyber: CYBER,
};

/** Unique board for (program, module) — null falls back to the program signature. */
export function getModuleBoard(program: ProgramKey, moduleIndex?: number | null): ReactNode | null {
  if (!moduleIndex) return null;
  const entry = REGISTRY[program]?.[moduleIndex];
  return entry ? entry() : null;
}
