import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { requireAdmin } from "../_shared/auth.ts";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};

const courseData = {
  "title": "AI Platform Engineer",
  "description": "Build the internal developer platforms that make AI teams 10x more productive. 10 modules covering IDP design, Backstage, self-service GPU provisioning, feature stores, model serving platforms, and the engineering excellence that reduces AI infrastructure friction from weeks to minutes.",
  "translations": {
    "es": {
      "title": "AI Platform Engineer",
      "description": "Build the internal developer platforms that make AI teams 10x more productive. 10 modules covering IDP design, Backstage, self-service GPU provisioning, feature stores, model serving platforms, and th"
    },
    "fr": {
      "title": "AI Platform Engineer",
      "description": "Build the internal developer platforms that make AI teams 10x more productive. 10 modules covering IDP design, Backstage, self-service GPU provisioning, feature stores, model serving platforms, and th"
    },
    "de": {
      "title": "AI Platform Engineer",
      "description": "Build the internal developer platforms that make AI teams 10x more productive. 10 modules covering IDP design, Backstage, self-service GPU provisioning, feature stores, model serving platforms, and th"
    },
    "zh": {
      "title": "AI Platform Engineer",
      "description": "Build the internal developer platforms that make AI teams 10x more productive. 10 modules covering IDP design, Backstage, self-service GPU provisioning, feature stores, model serving platforms, and th"
    },
    "ar": {
      "title": "AI Platform Engineer",
      "description": "Build the internal developer platforms that make AI teams 10x more productive. 10 modules covering IDP design, Backstage, self-service GPU provisioning, feature stores, model serving platforms, and th"
    },
    "ja": {
      "title": "AI Platform Engineer",
      "description": "Build the internal developer platforms that make AI teams 10x more productive. 10 modules covering IDP design, Backstage, self-service GPU provisioning, feature stores, model serving platforms, and th"
    }
  },
  "modules": [
  {
    "title": "Module 1: Platform Engineering Philosophy — The Paved Road and Developer Experience",
    "desc": "Platform engineering reduces cognitive load on ML and software teams by providing golden paths. Team Topologies, the enabling team model, DORA metrics, developer experience measurement, and why Spotify, Netflix, and LinkedIn invest 10-15% of engineering headcount in platform teams.",
    "lessons": [
      { "title": "1.1 What Platform Engineering Is and Why It Exists", "desc": "Platform engineering (coined 2020, popularized by Gartner and Team Topologies) solves the scaling problem of DevOps: when every application team owns their own infrastructure, operational complexity grows linearly with team count. Platform engineering centralizes infrastructure expertise in an enabling team that provides self-service capabilities — reducing cognitive load on stream-aligned teams from weeks of infrastructure work to minutes of platform consumption. The economics: Netflix has 2,500 engineers; their platform team (~200 people) enables the other 2,300 to ship without infrastructure expertise. Without a platform, every team rediscovers the same Kubernetes debugging patterns, reinvents the same CI/CD pipelines, and fights the same cloud cost optimization battles. The platform team solves these problems once and provides the solution as a product. CNCF 2023 Platform Engineering survey: 68% of organizations have a dedicated platform team, up from 45% in 2021 — the fastest-growing engineering specialty." },
      { "title": "1.2 Team Topologies: The Enabling Team Model for AI Infrastructure", "desc": "Team Topologies (Skelton & Pais, 2019) defines four team types: Stream-aligned (deliver product features — ML engineers, data scientists), Enabling (accelerate stream-aligned capability — platform engineers, DevOps), Complicated Subsystem (own complex components — GPU infrastructure, networking), Platform (provide self-service internal products — the internal developer platform). The interaction modes: X-as-a-Service (platform provides self-service — GPU provisioning API), Collaboration (platform and stream-aligned build together temporarily), Facilitating (enabling team coaches stream-aligned on platform capabilities). The cognitive load imperative: each stream-aligned team should be able to deliver end-to-end value without needing deep expertise in 15 different infrastructure domains. Platform engineering reduces that expertise requirement to the minimum needed for the team's actual work. Case study: Spotify's Backstage was born from Team Topologies thinking — 2,000 engineers consuming platform capabilities from a 200-person platform organization." },
      { "title": "1.3 DORA Metrics: Measuring Platform Engineering Impact", "desc": "The DORA (DevOps Research and Assessment) four key metrics quantify the business impact of platform engineering investments. Deployment Frequency: how often teams deploy to production (Elite: on-demand, multiple times per day). Lead Time for Changes: commit to production time (Elite: less than 1 hour). Change Failure Rate: percentage of deployments causing incidents (Elite: 0-15%). Time to Restore Service: incident resolution time (Elite: less than 1 hour). Platform engineering's direct impact: self-service infrastructure eliminates the infrastructure provisioning bottleneck in Lead Time for Changes. Golden path templates reduce Change Failure Rate by encoding best practices. Automated rollback reduces Time to Restore Service. The 2023 DORA Report finding: teams with internal developer platforms perform 1.8x better on software delivery metrics than teams without. Measurement instrumentation: Middleware, Jellyfish, or custom metrics pipelines tracking deployment events in GitHub and CI/CD systems." },
      { "title": "1.4 Developer Experience (DevEx): Measurement and Improvement", "desc": "Developer Experience is the quality of working conditions for engineers — the platform team's primary product. DX Core 3 framework (2024): three dimensions that predict engineering productivity. Speed: how fast can I go from idea to production? Eliminate waiting (for infrastructure, approvals, builds). Ease: how easy is it to do the right thing? Golden paths should be the path of least resistance. Quality: does my work actually achieve the desired outcome? Reduce rework through better tooling and feedback loops. Measurement methodology: Friction Log (structured diary where engineers document friction points), quarterly DX survey (10 questions, 1-5 scale on speed/ease/quality dimensions), DORA metrics as outcome indicators. The DX flywheel: better developer experience → faster feature delivery → more business value → investment in platform → better DX. Spotify's DX measurement program: quarterly survey of 2,000 engineers, monthly DORA metrics, bi-annual Friction Log sessions — platform roadmap is driven by DX data." },
      { "title": "1.5 The Platform Product Manager: Treating Internal Infrastructure as a Product", "desc": "Platform teams that succeed treat their internal tools as products — with users, roadmaps, feedback loops, and success metrics. The platform PM role: translate engineer pain points into platform requirements, prioritize platform investments by impact and effort, communicate platform capabilities to users, and track adoption metrics. User research for platform teams: office hours (weekly drop-in for engineers to discuss platform friction), quarterly user interviews (structured conversations with 10 engineers per quarter), NPS survey (quarterly 10-point scale: 'How likely are you to recommend this platform to a colleague?'), usage analytics (which platform features are used vs. ignored). The platform roadmap format: initiative (customer problem it solves), success metric (how we'll know it worked), timeline, and dependencies. Anti-pattern: building features without user research — 40% of internal platform features go unused per Thoughtworks 2023 survey. Case study: LinkedIn's Developer Productivity team (100+ platform engineers) runs quarterly engineer satisfaction surveys that directly drive roadmap prioritization." },
      { "title": "1.6 Platform Engineering Maturity: From Ad-Hoc to Product-Grade", "desc": "Platform engineering maturity follows five levels with distinct characteristics at each stage. Level 0 (No Platform): each team manages own infrastructure, high duplication, no shared capabilities, platform engineering exists only in name. Level 1 (Shared Scripts): informal tooling shared via wiki, maintained by individual contributors, no SLA, breaks frequently. Level 2 (Managed Services): dedicated platform team, some self-service capabilities, basic documentation, incident response exists but slow. Level 3 (Product-Grade Platform): platform team operates with product mindset, self-service covers 80%+ of use cases, SLAs defined and met, onboarding measured in hours not days. Level 4 (Intelligent Platform): platform anticipates team needs, automated cost optimization, AI-assisted infrastructure operations, contribution model where product teams contribute platform improvements. Assessment methodology: score each platform capability dimension independently — teams often have Level 3 Kubernetes capabilities and Level 1 ML infrastructure capabilities simultaneously. The assessment reveals investment priorities. Case study: Airbnb's platform maturity assessment (2022) revealed their ML infrastructure was at Level 1 despite world-class application infrastructure — leading to the Bighead ML platform investment." },
      { "title": "1.7 Module 1 Assessment: Platform Maturity Audit", "desc": "Conduct a platform engineering maturity assessment of a provided organization description. Score each dimension (CI/CD, container platform, observability, ML infrastructure, developer portal, cost management) against the 5-level maturity model. Identify the highest-leverage investment opportunities. Design the 90-day quick-win plan that would most improve DORA metrics and developer experience scores." }
    ]
  },
  {
    "title": "Module 2: Internal Developer Portals — Backstage and Self-Service Infrastructure",
    "desc": "Backstage (Spotify, 2020) is the open-source foundation for internal developer portals. Software catalog, TechDocs, software templates, plugin architecture, and the IDP patterns that have made Backstage the standard at Airbnb, Netflix, and 3,000+ companies.",
    "lessons": [
      { "title": "2.1 Backstage Architecture: Catalog, Plugins, and the App Framework", "desc": "Backstage is a React+Node.js framework for building internal developer portals. Core architecture: the App (assembled from plugins), the Software Catalog (service registry backend), TechDocs (documentation rendering pipeline), and the Plugin system (every capability is a plugin — composable, replaceable). The catalog entity model: Component (services, ML models, datasets), API (service interfaces), System (groups of components), Domain (business domains), Resource (databases, ML infrastructure), Location (pointers to catalog YAML files). catalog-info.yaml: the entity definition file committed to every repository — apiVersion, kind, metadata (name, tags, links), spec (type, owner, system, dependsOn). Catalog ingestion: Backstage crawls repositories on schedule, finds catalog-info.yaml files, and populates the catalog — zero manual registration required at scale. Case study: Spotify runs Backstage for 2,000+ engineers with 5,000+ catalog entities — the catalog is the authoritative inventory of all software assets." },
      { "title": "2.2 TechDocs: Documentation-as-Code for Platform Teams", "desc": "TechDocs renders Markdown documentation from repositories into a searchable portal — documentation lives alongside code, versioned with it, and never goes stale. Setup: mkdocs.yml in repository root defines navigation, docs/ folder contains Markdown. Backstage renders docs at build time and serves them from the portal. Custom MkDocs plugins: mermaid (diagrams), admonitions (callout boxes), macros (template variables). The documentation culture shift: engineers write docs in their IDE alongside code — eliminating the 'documentation as afterthought' pattern. Enforcement: require docs/index.md to exist for any service with 100+ daily API calls — tracked via catalog quality scoring. Search integration: Backstage's search plugin indexes TechDocs content alongside catalog entities — 'find everything related to feature stores' returns entities, docs, and APIs. Case study: Zalando reduced time-to-productive for new engineers from 3 weeks to 5 days after consolidating 200 Confluence spaces into Backstage TechDocs." },
      { "title": "2.3 Software Templates: Golden Paths for ML Services and Data Pipelines", "desc": "Software Templates are Backstage's scaffold engine — a template definition that generates a complete repository, registers the catalog entity, creates CI/CD pipelines, provisions infrastructure, and configures monitoring with a single form submission. Template anatomy: parameters (form fields the user fills out — service name, team, GPU requirements), steps (actions executed — fetch template, run cookiecutter, publish to GitHub, register in catalog, call infrastructure API). Template types for AI teams: ML Serving Service (FastAPI + Docker + K8s deployment + Prometheus + ArgoCD), Training Pipeline (Python package + Airflow DAG + MLflow experiment + S3 artifact bucket), Feature Engineering Job (dbt model + Great Expectations + Airflow DAG). Template maintenance: templates are versioned in a templates repository — engineers submit PRs to improve templates. The golden path adoption metric: what percentage of new services use the official template vs. custom setup? Target: >85%. Case study: Lyft's Software Templates reduced new ML service setup from 2 weeks to 45 minutes — the template provisions 23 infrastructure resources automatically." },
      { "title": "2.4 Backstage Plugins: Extending the Portal for ML Teams", "desc": "Backstage's plugin system enables integrations with every tool in the ML platform stack. Official plugins: GitHub (PR status, actions), Kubernetes (pod status for any service), Cost Insights (cloud spend per service), PagerDuty (on-call and incident status). ML-specific plugins: MLflow (view experiments from the catalog entity page — click a model service, see its latest training runs), Feast Feature Store (browse feature views from the portal), Datadog (APM metrics embedded in the portal), Grafana (dashboards embedded without leaving Backstage). Building custom plugins: React frontend (renders data), Node.js backend (calls external APIs). Plugin discovery: Backstage plugin marketplace has 200+ community plugins. Plugin governance: evaluate plugins for security before enabling — plugins run in the browser and can access Backstage API tokens. Case study: Spotify has 100+ custom Backstage plugins — their internal plugin marketplace has more plugins than the public community." },
      { "title": "2.5 Catalog Quality Scoring and Governance", "desc": "A catalog with incomplete, stale, or inaccurate entries is worse than no catalog — engineers stop trusting it. Catalog quality scoring: define completeness criteria per entity type (Component must have: owner, system, lifecycle, description, links to runbook and dashboard, techdocs). Compute a quality score for each entity (0-100%). Publish quality scores in the portal — gamification and visibility drive improvement. Quality enforcement: require quality score >80% before a service can receive production traffic (enforced via ArgoCD Application health check that verifies catalog quality API). Stale detection: entities with no commits in 90 days flagged for archival. Ownership enforcement: entities without a valid team owner are quarantined — cannot deploy until ownership is claimed. Case study: Airbnb's catalog quality initiative increased average entity quality score from 43% to 87% in 6 months by making quality visible in the portal and adding quality gates to deployment pipelines." },
      { "title": "2.6 Migrating to Backstage: From Zero to Production in 90 Days", "desc": "Backstage adoption requires organizational change management as much as technical implementation. Phase 1 — Foundation (Days 1-30): deploy Backstage with GitHub authentication, configure the catalog ingester for your GitHub organization, auto-populate catalog from existing catalog-info.yaml files, enable TechDocs rendering. Phase 2 — Content (Days 31-60): run catalog-info.yaml hackathon (all teams add catalog definitions in one sprint), migrate top-10 most-referenced wikis to TechDocs, create first 3 Software Templates for highest-volume service types. Phase 3 — Adoption (Days 61-90): announce Backstage as the primary developer portal, disable old wiki spaces, configure Slack /backstage slash command, run lunch-and-learn sessions for every team. Adoption metrics at day 90: weekly active users, catalog entities with >80% quality score, template usage rate. Common failure modes: poor search (fix with Elasticsearch backend), slow page loads (fix with caching plugins), incomplete catalog (fix with quality scoring + gates). Case study: American Airlines migrated 500 services to Backstage in 90 days — the migration was the forcing function that cleaned up years of undocumented services." },
      { "title": "2.7 Module 2 Lab: Build a Production Backstage Instance", "desc": "Hands-on project: deploy Backstage locally, configure GitHub integration, import a multi-repository catalog, create a Software Template for an ML serving service (generates FastAPI app + Dockerfile + catalog-info.yaml + GitHub Actions CI/CD), install the Kubernetes and Cost Insights plugins, configure TechDocs for two documentation sites, and implement quality scoring with a custom entity processor." }
    ]
  },
  {
    "title": "Module 3: Kubernetes Platform Engineering — Multi-Tenancy, GitOps, and GPU Infrastructure",
    "desc": "The Kubernetes platform is the foundation of every modern AI infrastructure. Multi-tenant cluster design, namespace isolation, ArgoCD GitOps at scale, GPU operator configuration, cluster autoscaling, and the Kubernetes platform patterns at Stripe, GitHub, and Cloudflare.",
    "lessons": [
      { "title": "3.1 Multi-Tenant Kubernetes: Cluster Design for 50+ Teams", "desc": "Multi-tenancy in Kubernetes requires isolation across security (teams cannot access each other's data), performance (noisy neighbor problem — one team's workload cannot starve another's), and cost (attribution requires isolation boundaries). Isolation strategies: namespace-per-team (soft isolation, shared control plane, low overhead), cluster-per-team (hard isolation, maximum security, high cost), hierarchical namespaces (HNC controller enables namespace trees with inherited policies). ResourceQuota per namespace: CPU and memory limits enforced at namespace level — Team A cannot consume resources allocated to Team B. LimitRange: default resource requests and maximum per-pod limits ensure every pod has resource requests (required for scheduling) without being over-provisioned. NetworkPolicy: default-deny all inter-namespace traffic, explicit allow rules for approved communication paths. The shared cluster model at scale: GitHub runs 1,000+ namespaces on shared clusters — tenant isolation via RBAC + NetworkPolicy + ResourceQuota provides sufficient isolation for their threat model." },
      { "title": "3.2 ArgoCD at Scale: Application Sets, Multi-Cluster, and GitOps Patterns", "desc": "ArgoCD managing 500+ Applications across 10+ clusters requires organizational patterns. ApplicationSet: generate Applications from a template — one ApplicationSet creates one Application per team-environment combination. Generators: Git (one Application per directory), List (one Application per list entry), Matrix (cross-product of two generators). Multi-cluster management: one ArgoCD instance can manage 50+ clusters — cluster-scoped ApplicationSets deploy to all clusters simultaneously. App-of-Apps pattern: a parent Application manages child Applications — the entire platform configuration is represented as a recursive ArgoCD Application tree. Sync waves: annotate resources with argocd.argoproj.io/sync-wave to control resource creation order — CRDs before operators, operators before operands. RBAC for ArgoCD: AppProject constrains which repositories and destination clusters a team can deploy to — teams can deploy to their namespace, not to production cluster system namespaces. Case study: Intuit manages 4,000+ ArgoCD Applications across 8 clusters with ApplicationSet generators — 99.9% of infrastructure changes go through ArgoCD with no kubectl apply in CI." },
      { "title": "3.3 GPU Infrastructure: NVIDIA Operator, MIG, and GPU Scheduling", "desc": "GPU infrastructure management is the platform engineer's most specialized responsibility for AI teams. NVIDIA GPU Operator: Kubernetes operator that manages the complete GPU software stack (driver installation, CUDA toolkit, device plugin, DCGM exporter, container toolkit) as Kubernetes resources — GPU node provisioning becomes declarative. Node Feature Discovery (NFD): labels GPU nodes with hardware capabilities (nvidia.com/gpu.product=A100-SXM4-80GB) enabling precise node affinity scheduling. GPU scheduling strategies: single GPU per pod (full isolation, lowest utilization), time-slicing (share GPU among multiple pods, no memory isolation), MIG (Multi-Instance GPU on A100/H100 — hardware isolation with guaranteed memory/compute partitions). DCGM Exporter: Prometheus metrics for GPU health (gpu_utilization, gpu_memory_used, gpu_temperature, nvlink_bandwidth) — essential for capacity planning and cost attribution. Node draining for GPU maintenance: drain GPU nodes before driver upgrades to allow running training jobs to complete gracefully. Case study: CoreWeave (GPU cloud provider) built their entire business on Kubernetes GPU scheduling — serving 10,000+ concurrent GPU workloads across multiple NVIDIA GPU generations." },
      { "title": "3.4 Cluster Autoscaling: Karpenter and Cost-Efficient Node Provisioning", "desc": "Kubernetes cluster autoscaling provisions and removes nodes based on pending pod demand. Karpenter (AWS, 2021) vs. Cluster Autoscaler: Karpenter provisions directly from EC2 API based on pod resource requirements — selects the most cost-efficient instance type for each pending pod rather than scaling a fixed node group. Karpenter NodePool: define constraints (instance families, GPU types, availability zones, capacity types: on-demand/spot), provisioner selects the cheapest compliant option. Consolidation: Karpenter identifies underutilized nodes and migrates workloads to fewer nodes — continuous cost optimization. GPU node provisioning: define a NodePool that includes p3, p4, p5 (V100, A100, H100) families — Karpenter uses spot when available, falls back to on-demand. Disruption budgets: Karpenter respects PodDisruptionBudgets during consolidation — model serving pods with minAvailable=2 are never disrupted below 2 replicas. Case study: Doordash migrated from Cluster Autoscaler to Karpenter and reduced EC2 costs by 43% through improved instance selection and consolidation." },
      { "title": "3.5 Policy Enforcement: OPA Gatekeeper and Kubernetes Admission Control", "desc": "Platform teams use admission control to enforce security and governance policies across all workloads. OPA Gatekeeper: webhook-based admission controller that evaluates Kubernetes resource requests against OPA policies. ConstraintTemplate + Constraint pattern: ConstraintTemplate defines the policy logic (Rego), Constraint instantiates the policy with parameters. Essential policies for AI platforms: require-resource-limits (every container must have CPU and memory limits), no-privileged-containers (privileged: true is banned), require-labels (every Deployment must have team and cost-center labels), gpu-justification (pods requesting GPUs must have a GPU request annotation explaining why), no-latest-tag (container images must use specific SHA or semver tags — never :latest). Policy-as-code workflow: policies live in Git, Kyverno/Gatekeeper configuration applied via ArgoCD. Policy dry-run: test new policies in audit mode before enforcement — generate violation reports without blocking deployments. Case study: Shopify enforces 45 OPA Gatekeeper policies across their Kubernetes fleet — any policy violation blocks deployment at admission time, not during monitoring." },
      { "title": "3.6 Kubernetes Observability Stack: Prometheus, Grafana, and Distributed Tracing", "desc": "Platform teams own the observability infrastructure that all product teams consume. kube-prometheus-stack Helm chart: installs Prometheus Operator, Alertmanager, Grafana, and pre-built dashboards for Kubernetes cluster health. Custom metrics with ServiceMonitor: teams annotate their services with prometheus.io/scrape: 'true' — Prometheus discovers and scrapes automatically. Grafana dashboard library: platform team maintains golden dashboards (cluster utilization, namespace resource usage, GPU utilization, cost by team) that all teams can embed. Distributed tracing infrastructure: Jaeger or Tempo as the tracing backend, OpenTelemetry Collector as the aggregation pipeline. Platform team observability responsibility: platform owns cluster-level observability, provides tooling for service-level observability, teams own their service dashboards. OpenCost for cost attribution: Kubernetes cost breakdown by namespace, label, and workload — the platform team's cost report. Case study: Cloudflare's Kubernetes observability platform processes 1TB/day of metrics across 200+ clusters — their open-source Prometheus federation pattern is the standard for large-scale Kubernetes monitoring." },
      { "title": "3.7 Module 3 Lab: Build a Production-Grade Kubernetes Platform", "desc": "Complete platform build: configure multi-tenant namespace structure with ResourceQuota and NetworkPolicy, deploy ArgoCD with AppProject isolation per team, install NVIDIA GPU Operator and configure MIG partitioning, deploy Karpenter with GPU NodePool including spot fallback, add OPA Gatekeeper with 5 essential policies, deploy kube-prometheus-stack with OpenCost, and create a Backstage Kubernetes plugin integration showing pod status per catalog entity." }
    ]
  },
  {
    "title": "Module 4: ML Infrastructure Platform — Self-Service Training, Experiment Tracking, and Model Registry",
    "desc": "The ML-specific layer of the platform enables self-service model development. GPU job submission APIs, MLflow at scale, model registry governance, experiment management, and the ML infrastructure patterns at LinkedIn, Pinterest, and Uber.",
    "lessons": [
      { "title": "4.1 Self-Service GPU Job Submission: API Design and Queue Management", "desc": "ML engineers should submit training jobs through an API, not write Kubernetes YAML. The platform-provided training job API: submit(image, command, gpu_count, memory, max_duration, priority, spot_ok) → returns job_id with status endpoint. Backend implementation: Python SDK wraps Kubernetes Job creation — generates pod spec with GPU resource limits, node affinity for GPU family, spot instance toleration if spot_ok, IRSA annotation for S3 access, resource limits. Queue management: fairshare scheduler (allocate GPU hours equitably across teams based on quota), priority levels (production-retraining preempts research), preemption (low-priority jobs checkpointed and paused when high-priority jobs need resources). Job monitoring API: status(job_id) → {phase, gpu_utilization, training_loss, eta, log_url}. Platform SLA: job starts within 5 minutes of submission for on-demand GPU, 15 minutes for spot. Case study: Pinterest's ML platform processes 10,000 training jobs daily through their job submission API — zero Kubernetes YAML written by ML engineers." },
      { "title": "4.2 MLflow at Enterprise Scale: Tracking Server, Artifact Store, and Multi-Team Configuration", "desc": "MLflow's default single-node setup breaks at 1,000+ daily training runs. Production MLflow architecture: load-balanced tracking server fleet (3+ Gunicorn workers each), PostgreSQL backend (connection pooling with PgBouncer — MLflow generates high concurrent write load), S3 artifact store (object storage scales infinitely). Multi-team experiment isolation: experiment_id namespacing per team (team-a/model-name convention), MLflow project-level RBAC (restrict which teams can read which experiments). Performance optimization: artifact logging with S3 multipart upload (large model checkpoints upload in parallel), metric batch logging (log_metrics with step batches rather than individual calls), async artifact upload (don't block training on artifact upload). MLflow Model Registry at scale: separate PostgreSQL database from tracking server (registry writes are lower volume but read performance is critical for serving), webhook notifications (Slack on model stage transitions, deployment pipeline trigger on Production promotion). Case study: Databricks hosts MLflow for 10,000+ companies — their MLflow architecture handles 50M+ runs with sub-second metric logging." },
      { "title": "4.3 Model Registry Governance: Approval Workflows and Deployment Gates", "desc": "The model registry is the governance checkpoint between research and production. Registry lifecycle automation: CI/CD pipeline registers model after successful training run (mlflow.register_model), automated evaluation job runs against holdout set and performance benchmarks, transitions model to Staging if benchmarks pass (mlflow_client.transition_model_version_stage), human approval required for Production (webhook triggers approval workflow in Slack or Jira). Registry API for deployment pipelines: serving infrastructure calls mlflow.pyfunc.load_model('models:/fraud-detector/Production') — when a new model version is approved for Production, serving infrastructure loads it automatically on next rollout. Registry audit trail: every stage transition logged with actor, timestamp, and justification — satisfies EU AI Act documentation requirements. Model card enforcement: require model card completion before Production promotion — gating mechanism prevents undocumented models reaching production. Case study: Airbnb's model registry processes 100+ automated model deployments daily — human approval required only for models flagged as high-risk by their automated risk classifier." },
      { "title": "4.4 Experiment Management at Scale: Organization, Search, and Lifecycle", "desc": "10,000 training runs per month without organization creates experiment chaos. Experiment taxonomy enforced at API level: mandatory tags (team, model_name, dataset_version, run_type=[research/staging/production-retrain]) applied automatically by the platform SDK. Experiment templates: pre-configured MLflow experiment setups for common model types — ml_platform.create_experiment(template='classification') creates experiment with standard tags and evaluation hooks. Cross-team experiment search: platform-level MLflow search interface allows finding best models across teams ('find all fraud models with AUC > 0.95 in last 30 days'). Experiment lifecycle management: automated archival of experiments older than 180 days (metrics retained, artifacts deleted to reduce S3 costs), cost-per-experiment tracking (GPU hours × rate per hour logged as a custom metric). Experiment comparison tool: platform team builds a Backstage plugin that surfaces top experiments per model name — ML engineers see the best-performing configurations without reading all runs. Case study: Weights & Biases (the commercialized version of this pattern) serves 500M+ runs — their organization patterns have become the industry standard." },
      { "title": "4.5 Jupyter Hub and Notebook Infrastructure for ML Teams", "desc": "JupyterHub on Kubernetes provides self-service GPU notebooks without direct cluster access. JupyterHub deployment: Zero to JupyterHub Helm chart, authenticator (GitHub OAuth, LDAP), spawner (KubeSpawner — creates per-user pods in dedicated namespace), profiles (CPU-only, 1 GPU, 4 GPU, large memory — different resource profiles). GPU notebook optimization: CUDA pre-installed in notebook image, persistent storage mounted (user work survives pod restarts), shared dataset storage (read-only volume mount of common training datasets — no re-downloading). Cost controls: auto-stop inactive servers after 2 hours (configurable), maximum server lifetime of 72 hours, GPU quota per user per day. Notebook-to-pipeline promotion: platform provides a 'convert to Airflow DAG' template that scaffolds a production training pipeline from a notebook — the bridge between exploration and production. Security: notebooks run as non-root, network policy restricts notebook pods to data science infrastructure only. Case study: Goldman Sachs' Marquee platform runs 5,000 analyst JupyterHub notebooks on Kubernetes — the notebook infrastructure is the primary ML development environment." },
      { "title": "4.6 Cost Attribution and FinOps for ML Infrastructure", "desc": "ML infrastructure costs are the fastest-growing line item in AI-first companies. Cost attribution architecture: every Kubernetes workload tagged with team + model_name + run_type labels (enforced by OPA policy), OpenCost computes per-label costs hourly, cost data flows to internal billing system or dashboard. Per-experiment cost tracking: training job submission API records GPU hours × hourly cost per job_id — MLflow logs cost as a custom metric. Cost efficiency metrics: cost_per_training_run (weekly trend), cost_per_model_version_deployed (monthly), GPU utilization heatmap (identify teams with consistently low utilization). FinOps governance: monthly cost review with each team lead (30-minute meeting, cost vs. budget, efficiency opportunities), automated alerts at 80% of monthly quota, quarterly budgeting process where teams request GPU hour allocations. Spot instance arbitrage: platform transparently routes spot-eligible jobs (checkpointed training, batch inference) to spot capacity — ML engineers opt-in via spot_ok=True flag, platform handles checkpoint/restart. Case study: Lyft's ML FinOps program saved $4M annually by making cost visible at the experiment level — ML engineers self-optimized when they could see cost per run." },
      { "title": "4.7 Module 4 Assessment: ML Infrastructure Platform Design", "desc": "Design the complete ML infrastructure platform for a 100-person ML team. Specify: training job submission API design with SDK interface, MLflow production architecture with HA configuration, model registry governance workflow with approval automation, experiment management organization schema, JupyterHub configuration with cost controls, and FinOps program with attribution model. Estimate monthly infrastructure cost and engineer time saved vs. teams managing their own infrastructure." }
    ]
  },
  {
    "title": "Module 5: Model Serving Platform — Inference Infrastructure at Scale",
    "desc": "The model serving platform standardizes how models go from registry to production. Triton Inference Server, model serving templates, autoscaling for ML workloads, A/B testing infrastructure, shadow deployment, and the serving platforms at Hugging Face, Uber, and Netflix.",
    "lessons": [
      { "title": "5.1 Model Serving Platform Architecture: From Registry to Production", "desc": "The model serving platform is the automated bridge between MLflow Model Registry and production Kubernetes deployments. Platform-provided serving workflow: ML engineer promotes model to Production in registry → webhook triggers deployment pipeline → pipeline reads model artifact URI from registry → generates Kubernetes Deployment YAML from serving template → deploys via ArgoCD → serving endpoint available within 10 minutes. Serving template parameters: model_uri (MLflow registry reference), replicas (initial count), gpu_per_replica (0 for CPU, 1+ for GPU), max_batch_size, request_timeout_ms, autoscaling (target RPS, min/max replicas). The serving abstraction: ML engineers specify what to serve, the platform specifies how to serve it — eliminating the need for ML engineers to understand Kubernetes, Docker, or load balancers. Model server options in the template: MLflow serving (simplest, any sklearn/PyTorch/TensorFlow model), Triton Inference Server (highest performance, requires model format conversion), TorchServe (PyTorch-native), custom FastAPI (maximum flexibility). Case study: Uber's Michelangelo serving platform deploys 10,000+ model versions with a single API call — the serving infrastructure is completely invisible to model developers." },
      { "title": "5.2 NVIDIA Triton Inference Server: Configuration, Optimization, and Production Deployment", "desc": "Triton is the production standard for high-throughput model serving. Triton model repository structure: model_name/config.pbtxt (model configuration), 1/model.pt (versioned model artifact). Config.pbtxt: platform (PyTorch/TensorFlow/ONNX/TensorRT), input/output tensor definitions, instance_group (count: 2 = 2 model instances per GPU), dynamic_batching (max_queue_delay_microseconds: 100 — accumulate requests for 100μs before batching). Performance optimization: TensorRT engine export (compile PyTorch to TensorRT — 2-4x throughput), INT8 calibration (reduce memory, increase throughput with minimal accuracy loss), concurrent model execution (serve 5 smaller models on one GPU simultaneously). Triton metrics: inference_queue_duration, inference_compute_duration, gpu_utilization, memory_usage — all available as Prometheus metrics. Model ensemble: preprocessing → model → postprocessing as a single Triton ensemble pipeline, avoiding Python overhead between steps. Case study: Waymo uses Triton to serve perception models at 10Hz (100ms latency requirement) — Triton's C++ inference engine meets strict autonomous vehicle latency requirements that Python-based servers cannot." },
      { "title": "5.3 Autoscaling Model Serving: KEDA, HPA, and Traffic-Driven Scaling", "desc": "Model serving pods must scale with traffic — and GPU pods have special scaling considerations. HPA v2 for model serving: scale on custom Prometheus metric (scale when p95_inference_latency > 80ms OR requests_per_second > 100). KEDA for queue-based scaling: scale inference workers when SQS queue depth grows (batch inference jobs), scale to zero during off-peak hours. GPU scaling challenges: GPU nodes take 3-5 minutes to provision (vs. 30 seconds for CPU) — maintain warm GPU baseline to handle traffic spikes. Predictive scaling for known traffic patterns: if traffic increases 3x every Monday at 9am, pre-scale on Sunday night (KEDA scheduled scaling). Minimum replicas for production serving: never scale to 0 for latency-sensitive models (cold start = user-facing latency spike). PodDisruptionBudget: ensure at least 50% of replicas remain available during node maintenance or autoscaling events. Case study: Hugging Face Inference Endpoints scales to 0 during idle periods using KEDA — reducing serving costs by 80% for models with intermittent traffic." },
      { "title": "5.4 A/B Testing Infrastructure: Traffic Splitting and Statistical Analysis", "desc": "The platform provides the infrastructure for comparing model versions in production. Traffic splitting approaches: Istio VirtualService weight-based routing (95/5 split by percentage — no code changes required), feature flags with user ID hashing (deterministic assignment — user always sees same model), Argo Rollouts analysis (automated canary with Prometheus guardrails). A/B test configuration API: platform.create_ab_test(control_model='v2', treatment_model='v3', traffic_pct=5, success_metric='prediction_auc', guardrail_metrics=['latency_p99', 'error_rate']) — platform handles traffic routing and metric collection. Statistical analysis pipeline: collect metrics per variant for 48+ hours, compute statistical significance (t-test for continuous metrics, chi-squared for binary), generate report with confidence intervals. Auto-promotion logic: if treatment significantly beats control on primary metric AND guardrail metrics are within bounds → automatically promote to 100%. Case study: Netflix runs 200+ simultaneous model A/B tests using their platform's traffic routing infrastructure — their experimentation platform handles the statistical analysis automatically." },
      { "title": "5.5 Shadow Deployment and Model Validation in Production", "desc": "Shadow mode runs a new model version on live traffic without serving its predictions — the most rigorous pre-production validation. Shadow deployment implementation: Istio mirror (duplicate all requests to shadow service — no performance impact on primary), log shadow predictions alongside primary predictions, compare distributions offline. Shadow validation metrics: prediction distribution overlap (how similar are shadow vs. primary model output distributions?), latency (does the new model meet SLA requirements under real production load?), error rate (any serving failures in shadow mode?), business metric proxy (if we had served shadow predictions, would the downstream metric have been better?). Shadow-to-canary promotion gate: shadow must pass all validation checks before canary rollout begins. Platform tooling: shadow deployment template in ArgoCD, comparison dashboard in Grafana, promotion API that transitions from shadow → canary → full. Case study: Stripe uses shadow mode for all fraud model updates — new models run in shadow for 72 hours minimum before any production traffic is routed to them." },
      { "title": "5.6 Model Serving Reliability: Circuit Breakers, Fallbacks, and SLOs", "desc": "Production model serving requires the same reliability engineering as any business-critical service. Circuit breaker pattern for model serving: if the primary model's error rate exceeds 5% in a 1-minute window, route to the fallback model (previous stable version) automatically — Istio DestinationRule with outlier detection implements this without code changes. Fallback hierarchy: primary model → previous model version → static rule-based fallback → default prediction (safe, if applicable). Model serving SLO definition: availability (99.9% of prediction requests return valid response), latency (p99 < 100ms for real-time serving, p99 < 10s for batch), quality (prediction distribution within 2 standard deviations of baseline). Error budget tracking: Prometheus recording rules compute error budget burn rate — PagerDuty alert when burn rate indicates SLO breach within 1 hour. Graceful degradation: design model serving to degrade gracefully when the feature store is unavailable (use cached features) or when the ML model is unavailable (use last-known-good prediction). Case study: DoorDash's restaurant recommendation model has a circuit breaker that falls back to popularity-based ranking when ML inference latency exceeds 200ms — protecting user experience during ML infrastructure incidents." },
      { "title": "5.7 Module 5 Lab: Deploy a Complete Model Serving Platform", "desc": "Build the serving platform: deploy Triton Inference Server with a ResNet-50 image classification model (TensorRT optimized), configure HPA with custom Prometheus metrics, create an A/B test between two model versions using Istio VirtualService, implement shadow deployment for a new model, configure circuit breaker with Istio DestinationRule, set up SLO monitoring with Prometheus recording rules and Alertmanager, and expose the serving endpoint through NGINX Ingress with rate limiting." }
    ]
  },
  {
    "title": "Module 6: Feature Store Platform — Shared Infrastructure for ML Feature Engineering",
    "desc": "The feature store is the platform investment with the highest ML productivity ROI. Feast deployment architecture, online/offline store design, streaming feature pipelines, feature governance, and the feature store platforms at Twitter, Airbnb, and Spotify.",
    "lessons": [
      { "title": "6.1 The Feature Store as Platform Infrastructure", "desc": "Feature stores solve the platform engineering problem of shared ML infrastructure: multiple teams need the same features computed consistently — the feature store computes once and serves everywhere. Platform team's role in the feature store: own the infrastructure (Redis cluster, offline store, feature server), provide tooling (SDK, registration UI, monitoring dashboards), govern the catalog (approve new feature registrations, enforce quality standards), and operate the platform (SLA, incident response). The business case: a feature used by 10 models — without a feature store, computed 10 times (10x compute cost, 10x maintenance burden, 10 opportunities for training-serving skew). With a feature store: computed once, served to all 10 models consistently. Reuse rate is the primary platform KPI: what percentage of features in new models were reused from the registry? Netflix reports 30-50% reuse rate in their feature store — each reused feature is hours of saved engineering time. Case study: Uber's Michelangelo feature store serves 10,000 features to 3,000 ML models — the feature registry is the single source of truth for all feature definitions." },
      { "title": "6.2 Feast Platform Deployment: High-Availability Redis, Offline Store, and Registry", "desc": "Production Feast requires HA deployment across all components. Redis Cluster for online store: 6 nodes minimum (3 primaries + 3 replicas), consistent hashing for data distribution, Redis Sentinel or Redis Cluster for automatic failover, Redis memory sizing (features per entity × bytes per feature × total entities), persistence configuration (RDB snapshots + AOF for durability). Offline store selection: BigQuery (GCP-native teams — serverless, pay-per-query), Snowflake (SQL-native teams — familiar interface, enterprise governance), Databricks (Spark teams — native Delta Lake integration), Redshift (AWS-native teams). Feature registry backend: SQL (PostgreSQL) for team-shared registry with version control. Feature server deployment: Feast's built-in HTTP server as Kubernetes Deployment with HPA, Redis read replica for serving (isolate serving traffic from materialization traffic), feature server SLA: p99 < 5ms. Monitoring: feature freshness (last materialization timestamp per feature view), Redis memory utilization, feature server latency and throughput. Case study: Twitter's Feast deployment serves 500K feature lookups/second using a Redis Cluster of 120 shards — feature server p99 latency: 4ms." },
      { "title": "6.3 Streaming Feature Pipelines: Flink, Kafka, and Real-Time Materialization", "desc": "Real-time features require streaming computation pipelines that materialize to the online store continuously. Architecture: Kafka (event stream source) → Flink (stateful computation: windowed aggregations, stream-table joins) → Feast online store (Redis). Platform team responsibility: deploy and operate the Flink cluster (Kubernetes-native Flink Operator or Flink on YARN), manage Kafka topics for feature input streams, provide templates for common streaming feature patterns (windowed aggregates, CDC-based features). Feature freshness SLA tiers: real-time (<30 seconds — Kafka→Flink→Redis), near-real-time (<5 minutes — micro-batch Spark Streaming), batch (<1 hour — Airflow-triggered Spark job). Streaming feature registry in Feast: StreamFeatureView with Kafka source — platform validates that Kafka topic exists and schema matches feature view definition before registration. Backfill for streaming features: historical data replay through Flink from Kafka (if retention is sufficient) or from S3 event archive. Case study: DoorDash's delivery time prediction model uses streaming features computed by Flink with 30-second freshness — capturing real-time restaurant preparation time signals impossible with batch features." },
      { "title": "6.4 Feature Governance: Catalog, Quality Standards, and Deprecation", "desc": "A feature store without governance becomes a feature graveyard — hundreds of stale, undocumented features that nobody trusts. Feature catalog governance: mandatory fields for any feature registration (description, owner team, data source, freshness SLA, example values, quality tests). Feature quality standards enforced at registration: must have Great Expectations suite, null rate < 1% on last week's data, schema matches declared types. Feature approval workflow: new feature registrations reviewed by feature store governance team (check for duplication with existing features, validate quality tests, confirm ownership). Feature health dashboard: per-feature tracking of null rate, cardinality, value distribution statistics — compared to baseline weekly, alerts on drift. Feature deprecation process: features with zero consumers for 90 days enter deprecation queue → owner notification → 30-day grace period → removal from registry and offline storage deletion. Case study: Airbnb's Zipline feature store introduced mandatory quality tests in 2021 — within 6 months, the feature health dashboard flagged 200+ production features with quality issues that had been silently degrading models." },
      { "title": "6.5 Point-in-Time Correctness and Training Dataset Generation at Scale", "desc": "Generating training datasets from feature stores at scale requires both correctness and performance. Point-in-time correct join mechanics: for each training event (entity_id, event_timestamp), find the most recent feature values where feature.event_timestamp <= event.event_timestamp — prevents temporal leakage. Offline store query optimization: partition feature tables by date (query only dates in the training window), Z-order on entity_id (co-locate related features for fast joins), materialized baseline snapshots (pre-compute end-of-day snapshots for common training date ranges). Training dataset generation API: platform provides get_historical_features(entity_df=training_events, features=[...]) as a Python SDK — abstracts the join mechanics. Caching training datasets: register generated training datasets as versioned DVC artifacts — subsequent model training runs on identical data use the cached dataset rather than re-generating. Cost optimization: training dataset generation can be expensive (BigQuery scans at $6.25/TB) — cache aggressively and charge to the consuming team's experiment budget. Case study: LinkedIn generates 10TB+ training datasets daily from their feature store — dataset generation accounts for 30% of their ML infrastructure cost, making caching essential." },
      { "title": "6.6 Feature Store SLA, Monitoring, and Incident Response", "desc": "The feature store is critical path for every ML model in production — its SLA requirements are higher than most infrastructure. Feature store SLAs: online store availability (99.99% — a 1-minute outage affects all serving models), online store p99 latency (<5ms — contributes to model serving latency budget), materialization freshness (per feature view SLA — real-time features must be <30s stale at p99), offline store query reliability (95% of training dataset jobs complete without error). Monitoring stack: Redis Exporter (memory, connection count, command latency metrics) → Prometheus, Feast materialization job success/failure → Airflow task status → Prometheus, feature server request rate and latency → Prometheus. Alerting policy: Redis memory >80% (capacity warning), materialization job failure for SLA-critical feature view (immediate P1 alert), feature server p99 latency >10ms for 5+ minutes (P2 alert). Incident playbook: Redis OOM (scale Redis, identify and archive cold features), materialization lag (check Airflow, check source data availability, check Spark cluster), feature server latency spike (check Redis latency, check feature server CPU, check for hot key access pattern). Case study: Spotify's feature store SRE practice: 99.99% online store availability maintained through cross-region Redis replication and automated failover." },
      { "title": "6.7 Module 6 Lab: Deploy a Production Feature Store Platform", "desc": "Complete feature store deployment: set up Feast with PostgreSQL registry and Redis Cluster (3 primary + 3 replica), create feature views for a recommendation system (user engagement features, item popularity features, real-time interaction features), deploy streaming materialization pipeline using Kafka → Flink → Redis, implement feature quality monitoring with Great Expectations, build a training dataset generation job with point-in-time correctness, and create a Backstage plugin showing feature catalog and freshness status." }
    ]
  },
  {
    "title": "Module 7: Data Platform Engineering — Lakehouses, Pipelines, and Self-Service Analytics",
    "desc": "The data platform underpins every ML system. Delta Lake architecture, dbt at enterprise scale, Airflow cluster management, data catalog infrastructure, and the data platform patterns at Databricks, Airbnb, and Spotify.",
    "lessons": [
      { "title": "7.1 Lakehouse Architecture: Delta Lake, Iceberg, and the Medallion Pattern", "desc": "The lakehouse combines data lake economics (cheap object storage) with data warehouse capabilities (ACID transactions, schema enforcement, query performance). Medallion architecture: Bronze (raw ingestion — exact copy of source data, no transformation, schema-on-read), Silver (cleaned and enriched — schema-on-write, validated, deduplicated, conformed to canonical schema), Gold (business-ready features — ML-ready, aggregated, optimized for query performance). Table format selection: Delta Lake (default for Databricks and Spark shops — ACID, time travel, Python-native API), Apache Iceberg (cross-engine compatibility — Spark, Trino, Flink, Dremio can all read Iceberg natively), Apache Hudi (write-optimized for CDC and upsert-heavy workloads). Platform team responsibility: provide the object storage infrastructure (S3 with appropriate lifecycle policies), table format tooling (Delta Lake or Iceberg library versions), and governance (Unity Catalog or Apache Atlas). Case study: Databricks' own data platform uses Delta Lake with medallion architecture across 10 petabytes — their internal platform is the reference implementation for their customers." },
      { "title": "7.2 dbt at Enterprise Scale: Monorepo, Modular Structure, and CI/CD", "desc": "A dbt project with 500+ models and 20+ contributors requires organizational architecture. Repository structure options: monorepo (all dbt models in one repo — easiest CI/CD, harder team boundaries) vs. polyrepo (per-team dbt repos — clear ownership, harder cross-team dependencies). Modular monorepo with packages: a core package (shared macros, staging models), domain packages (marketing, payments, ml-features) imported by the root project. CI/CD for large dbt projects: slim CI (dbt build --select state:modified+ runs only changed models and downstream dependents — reduces CI time from 2 hours to 10 minutes). Parallel execution: dbt's thread count determines parallelism — production deployments at 32+ threads for Snowflake/BigQuery. Governance: every model in the ML features mart requires a not_null + unique test on the primary key (enforced by custom CI check). dbt docs as platform product: dbt docs generate creates an interactive lineage graph — hosted on an internal domain as the authoritative data catalog. Case study: GitLab runs a 1,500-model dbt monorepo with 40 contributors — their CI/CD pipeline runs in 8 minutes using slim CI and parallel execution across 6 BigQuery warehouses." },
      { "title": "7.3 Airflow Platform: Cluster Operations, Scaling, and Multi-Team Configuration", "desc": "Operating Airflow for 50+ teams with 500+ DAGs requires platform-grade infrastructure. Production Airflow architecture: Kubernetes executor (fresh pod per task — no shared worker state, horizontal scaling, perfect isolation), PostgreSQL metadata database (connection pooling with PgBouncer), Redis broker (task queue for Celery workers if not using K8s executor), DAG serialization (DAGs serialized to metadata DB — webserver and scheduler don't need filesystem access to DAG files). Multi-team namespace isolation: one Airflow instance per major team or one shared instance with namespace isolation (DAG tags, connection prefix conventions, variable prefix conventions). Airflow GitSync: DAGs served from Git repository via a sidecar container — engineers push DAG changes to Git, Airflow picks up changes within 60 seconds. Monitoring: Airflow metrics (dag_processing_total_parse_time, scheduler_heartbeat) → Prometheus → Grafana. Platform SLA: DAG registration within 5 minutes of Git push, task execution starts within 2 minutes of scheduled time. Case study: Lyft runs Airflow at 10,000 DAGs and 50,000 daily task executions — their Kubernetes executor configuration scaled Airflow to 5x their previous capacity without adding infrastructure." },
      { "title": "7.4 Data Catalog Infrastructure: DataHub, Apache Atlas, and Metadata Management", "desc": "Data catalog infrastructure makes data discoverable, trustworthy, and governable. DataHub (LinkedIn, open-source 2020): metadata platform with lineage tracking, search, and data quality integration. Architecture: GMS (Generalized Metadata Service — REST API), MCE (Metadata Change Events — Kafka-based metadata ingestion), MAE (Metadata Audit Events — change notifications). Ingestion sources: built-in connectors for BigQuery, Snowflake, dbt, Airflow, Looker — ingest metadata on schedule or event-triggered. Search: full-text search across all metadata (find datasets containing 'user_id', find dashboards consuming 'revenue' metrics). Lineage: column-level lineage from Spark and dbt integration — trace any column in a Gold table back to its Bronze source. Business glossary: standardized definitions for business terms (revenue, active user, churn) linked to the tables that implement them — reduces definitional ambiguity in ML feature engineering. Case study: LinkedIn built DataHub to manage metadata for 2M+ datasets — its open-source release has been adopted by Airbnb, PayPal, Cabify, and 1,000+ other companies." },
      { "title": "7.5 Data Quality Platform: Great Expectations and Automated Validation", "desc": "Platform teams provide data quality infrastructure as a shared service — teams define quality expectations, the platform runs them as deployment gates. Great Expectations deployment: Expectations Stores (S3 for expectation suites), Validation Results Stores (S3 for results), Data Docs (S3-hosted quality reports). Platform-provided expectation templates: standard expectation suites for common data patterns (event log suite, user dimension suite, ml feature suite) that teams customize. Integration with Airflow: DataContextCheckpointOperator runs GE checkpoints as Airflow tasks — DAG fails if quality checks fail. Integration with dbt: dbt-great-expectations package runs GE suites after each dbt model run. Quality score dashboard: Grafana dashboard showing quality check pass rates per dataset and trend over time — the platform team's quality health view. Alerting: quality check failures in ML-critical feature tables → immediate PagerDuty alert (P1), non-critical tables → Slack notification. Case study: Stripe's data quality platform runs 500,000 Great Expectations checks daily — quality failures in payment data trigger automatic data pipeline pauses preventing corrupt data from reaching ML models." },
      { "title": "7.6 Self-Service Analytics: Enabling Non-Engineers to Explore Data Safely", "desc": "Self-service analytics reduces platform team burden while enabling faster business insights. Semantic layer: Looker LookML or dbt Semantic Layer defines business metrics as code — non-engineers explore using business concepts rather than SQL. Row-level security: enforce data access policies transparently — users only see data for their business unit, region, or customer segment. Compute governance: query cost limits prevent expensive accidental full-table scans (BigQuery per-user quotas, Snowflake virtual warehouse auto-suspend). Query audit log: every analytical query logged with user, timestamp, cost — data access audit trail for compliance. Self-service training data: platform provides a SQL interface to the Gold feature layer with automatic point-in-time-correct semantics — data scientists explore features without needing to understand the feature store implementation. Case study: Airbnb's Minerva semantic layer serves 5,000 internal users with consistent metric definitions — eliminating the 'my number vs. your number' problem that wasted analyst time on reconciliation." },
      { "title": "7.7 Module 7 Assessment: Data Platform Architecture", "desc": "Design the complete data platform for a Series B AI company: lakehouse architecture with medallion pattern, dbt project structure for 10 engineering teams, Airflow cluster configuration for 200 DAGs, DataHub deployment for catalog and lineage, Great Expectations integration as a deployment gate, and self-service analytics layer. Include the platform team size estimate, infrastructure cost model, and 12-month roadmap." }
    ]
  },
  {
    "title": "Module 8: Platform Security and Compliance Engineering",
    "desc": "Platform teams own the security baseline that all workloads inherit. Zero-trust cluster architecture, secrets management platform, supply chain security, compliance automation, and the security platform patterns at GitHub, Cloudflare, and HashiCorp.",
    "lessons": [
      { "title": "8.1 Security Platform Architecture: Zero Trust for Internal Developer Platforms", "desc": "The internal developer platform faces a unique threat model: trusted internal users who need broad access to developer tooling. Zero-trust principles for the IDP: every service-to-service call authenticated (mTLS via Istio or Linkerd), every user action authorized (OPA policies evaluated per request), complete audit trail (every platform action logged to immutable store). Secrets never leave secure boundaries: platform services access secrets via Vault API — secrets are not passed as environment variables or stored in Kubernetes Secrets in plaintext. The platform security perimeter: Backstage (frontend), ArgoCD (deployment), MLflow (experiment tracking), and Airflow (orchestration) all behind internal authentication — no public exposure without explicit justification. Platform security team responsibility: security architecture review for new platform components, penetration testing of platform APIs, security advisory for teams building on the platform. Case study: GitHub's internal developer platform (the infrastructure GitHub uses to build GitHub) implements zero-trust architecture — every internal service call authenticated with OIDC tokens issued by their internal identity provider." },
      { "title": "8.2 Secrets Management Platform: Vault, External Secrets Operator, and Dynamic Credentials", "desc": "The secrets management platform is the foundation of credential security across the organization. HashiCorp Vault deployment: HA configuration (3+ Vault nodes with Raft storage backend), auto-unseal (AWS KMS or GCP Cloud KMS), audit logging (every secret access logged to Splunk/Elasticsearch). Vault secrets engines: KV v2 (static secrets with versioning), Database (dynamic short-lived credentials — Vault generates PostgreSQL credentials per-request, rotates after 1 hour), AWS (dynamic IAM credentials), PKI (internal certificate authority for mTLS). External Secrets Operator: Kubernetes operator that syncs Vault secrets to Kubernetes Secrets automatically — pods read Kubernetes Secrets, ESO handles Vault authentication and refresh. The zero-static-credential architecture: all team credentials come from Vault dynamic secrets or IRSA/Workload Identity — no long-lived credentials anywhere in the platform. Secrets rotation automation: Vault database secrets engine rotates database passwords every 24 hours — zero downtime rotation with connection pool handling. Case study: HashiCorp uses Vault internally across 500+ production services — their engineering blog post on zero-static credentials is the canonical reference for this pattern." },
      { "title": "8.3 Supply Chain Security: SLSA, Image Signing, and Dependency Management", "desc": "Platform teams are responsible for securing the software supply chain of the platform itself and setting standards for product teams. SLSA (Supply-chain Levels for Software Artifacts) framework: Level 1 (provenance exists — build scripts are version controlled), Level 2 (signed provenance from hosted CI — GitHub Actions OIDC), Level 3 (hermetically sealed build — no network access during build, reproducible). Container image signing: Cosign keyless signing in GitHub Actions (OIDC-based), signatures stored in OCI registry, Kyverno policy requires all images to have valid Cosign signatures before running in production. Dependency management: Renovate Bot automated dependency updates (weekly PRs for all Helm chart, Docker base image, and Python package updates), pip-audit in CI (block deployment if critical CVEs in Python dependencies), Dependabot for GitHub Security Advisories. SBOM generation: Syft generates CycloneDX SBOM for every container image build — stored in artifact registry alongside the image. Platform supply chain commitments: all platform components are SLSA Level 2 or higher, all images signed, all SBOMs published — setting the standard the platform enforces for product teams. Case study: CISA recommends SLSA Level 3 for critical infrastructure — the TJ-Actions supply chain attack (2023) compromised 23,000 repositories through a single tampered GitHub Action." },
      { "title": "8.4 Compliance as Code: SOC2, ISO 27001, and Automated Evidence Collection", "desc": "Platform engineering can automate the evidence collection that traditionally requires weeks of manual effort for compliance audits. Compliance-as-code mapping: map each SOC2 control to the automated platform capability that satisfies it. CC6.1 (logical access controls) → Kubernetes RBAC policies in Git, enforced by ArgoCD. CC7.2 (monitoring for anomalies) → Falco runtime security, Prometheus alerting, SIEM integration. CC8.1 (change management) → all changes via Pull Request, required reviewers in CODEOWNERS, ArgoCD deployment audit log. Evidence collection automation: platform exports compliance evidence packages automatically — ArgoCD deployment history (change management evidence), Vault audit logs (secret access evidence), GitHub PR merge history (code review evidence). Drata/Vanta integration: connect platform tooling to compliance automation platforms that generate audit evidence automatically. SOC2 Type II for the platform: the platform team itself achieves SOC2 Type II — their security controls cover the infrastructure all product teams run on. Case study: Drata customers reduce audit preparation from 6 weeks to 3 days by connecting CI/CD, cloud infrastructure, and security tooling to automated evidence collection." },
      { "title": "8.5 Container Security Platform: Scanning, Runtime Protection, and Policy Enforcement", "desc": "The platform team provides container security as a service — teams don't configure security individually. Container scanning pipeline: Trivy integrated into GitHub Actions (scans on every PR), critical CVE = PR blocked, high CVE = PR comment + team notification, scan results visible in Backstage entity page (Snyk or Trivy plugin). Runtime security with Falco: platform-wide Falco DaemonSet, rules maintained by platform security team, alerts routed to platform Slack channel (warning) and PagerDuty (critical). Admission control policies: Kyverno ClusterPolicy enforces: no latest tag, require security labels, resource limits required, readOnly root filesystem preferred, non-root user required. Container registry security: private registry (ECR or Artifact Registry), automated base image updates (weekly Renovate PRs updating FROM directives to latest patched versions), registry access via IRSA/Workload Identity (no static credentials). Security dashboard in Backstage: per-entity CVE count and severity, image age (how old is the base image?), last scan date, Falco alert count — security posture visible to every team for every service. Case study: Shopify's container security platform scans 10M+ container image layers daily — their automated base image update program keeps all production containers on base images newer than 30 days." },
      { "title": "8.6 Platform Incident Response: Runbooks, War Rooms, and Post-Mortems", "desc": "Platform incidents affect all teams simultaneously — platform incident response requires organization-wide coordination. Platform incident classification: P0 (complete platform outage — Kubernetes API server down, ArgoCD unavailable, feature store down — affects all teams), P1 (significant degradation — GPU scheduling broken, MLflow unavailable — affects ML teams), P2 (partial degradation — single component slow — affects specific teams). War room protocol for P0: dedicated Slack channel created automatically (#incident-YYYYMMDD-description), incident commander assigned (most senior platform engineer on-call), status page updated, affected team leads notified, 15-minute update cadence until resolved. The platform runbook library: every Alertmanager alert has a corresponding runbook page in Backstage TechDocs — 'ArgoCD sync failure' runbook linked directly from the alert. Blameless post-mortems: Backstage template generates post-mortem document with timeline, contributing factors, action items. Action item tracking: every post-mortem action item becomes a GitHub Issue with assigned owner and deadline. Case study: PagerDuty's platform team maintains 200+ runbooks in their internal wiki — linking runbooks to alerts reduced MTTR by 45% by giving on-call engineers the right information immediately." },
      { "title": "8.7 Module 8 Assessment: Platform Security Architecture", "desc": "Design the complete platform security architecture for an enterprise internal developer platform: zero-trust authentication layer for all platform services, Vault deployment with dynamic credentials for databases and cloud, supply chain security pipeline from code to production, SOC2 automated evidence collection mapping, container security scanning and runtime protection, and incident response framework with example runbooks for the 5 most common platform alerts." }
    ]
  },
  {
    "title": "Module 9: Platform Observability and Reliability Engineering",
    "desc": "Platform teams must maintain 99.9%+ availability for infrastructure that all product teams depend on. SLO-based reliability, capacity planning, chaos engineering, cost observability, and the platform reliability practices at Google, Netflix, and Stripe.",
    "lessons": [
      { "title": "9.1 Platform SLOs: Defining and Measuring Infrastructure Reliability", "desc": "Platform SLOs define the reliability contract between the platform team and their customers (product teams). Platform SLO examples: Kubernetes API availability (99.95% of API calls succeed, measured over 28 days), ArgoCD deployment success rate (99.9% of deployment attempts complete within 15 minutes), feature store online latency (p99 < 5ms for 99.9% of hours), MLflow tracking write success (99.9% of metric log calls succeed). SLO measurement methodology: Prometheus recording rules compute error rate over rolling windows, Grafana SLO dashboards show error budget consumption, Alertmanager fires when burn rate indicates SLO breach within 1 hour. Error budget policy: when error budget is healthy (>50% remaining), platform team ships new features; when error budget is below 50%, reliability work takes priority; when error budget is exhausted, feature freeze until budget recovers. Customer-facing SLO commitments: publish platform SLOs in Backstage — product teams build their own SLOs with knowledge of platform reliability. Case study: Google's SRE practice applies error budgets to infrastructure platforms — the Cloud Spanner team publishes SLOs that Google's product teams use to design their own reliability requirements." },
      { "title": "9.2 Platform Capacity Planning: Forecasting and Resource Management", "desc": "Platform infrastructure must have capacity for peak load plus safety margin — without over-provisioning. Capacity planning methodology: measure current utilization (CPU, memory, GPU, storage, network), forecast growth (linear regression on 90-day trend, adjust for known events — product launches, seasonal peaks), size for peak × 1.3 safety factor. GPU capacity planning: unique challenge — GPU instances take 3-5 minutes to provision, GPU shortage is possible during peak demand, reserved instances require 1-year commitment. The capacity review process: monthly meeting — actual vs. forecasted utilization, upcoming events that will drive demand, reserved instance purchase decisions. Burst capacity strategy: maintain on-demand capacity for steady-state, use spot for burst training, pre-scale serving clusters before known traffic events. Storage capacity: data grows indefinitely without lifecycle policies — implement automated archival (move cold data to cheaper storage tiers after 90 days), deletion (remove DAG run logs older than 1 year). Case study: Stripe's platform capacity planning team runs quarterly forecasting exercises — their GPU reserved instance purchase timing has reduced compute costs by $3M+ annually." },
      { "title": "9.3 Chaos Engineering for Platform Infrastructure", "desc": "Platform teams must proactively validate infrastructure resilience — chaos engineering for platforms has higher blast radius than for individual services. Chaos engineering framework: LitmusChaos (Kubernetes-native — pod deletion, node failure, network partition, disk I/O stress), ChaosMesh (Kubernetes and physical infrastructure). Platform-specific chaos experiments: Kubernetes API server latency injection (validates that ArgoCD and operators handle slow API responses gracefully), etcd node failure (validates that Kubernetes cluster continues operating during etcd member loss), GPU node failure (validates that training jobs checkpoint and restart, serving pods reschedule to healthy GPU nodes), Redis Sentinel failover (validates that feature store online serving continues during Redis primary failure). Chaos gamedays: scheduled monthly exercises — platform team conducts chaos experiments, tracks MTTR and any SLO violations, post-mortem for every SLO breach. The chaos hypothesis template: 'When [failure condition], [platform behavior]. We will validate this by [measurement].' Case study: Netflix's Chaos Monkey principle applied to platform infrastructure — the platform team at Netflix runs weekly automated chaos experiments that have eliminated entire categories of reliability issues." },
      { "title": "9.4 Cost Observability: Platform FinOps and Infrastructure Efficiency", "desc": "Platform teams own infrastructure costs and must continuously optimize. Cost observability stack: AWS Cost Explorer or GCP Billing + resource tags → cost attribution per team and platform component, OpenCost for Kubernetes workload cost attribution, custom cost dashboards in Grafana. Platform cost composition: Kubernetes node compute (60%), storage (20%), networking (10%), managed services (10%). Cost efficiency targets: Kubernetes CPU utilization >60% (below target indicates over-provisioning), GPU utilization >70% for reserved instances, storage growth rate < revenue growth rate. Cost anomaly detection: CloudWatch Cost Anomaly Detection (AWS) or custom Prometheus alerts for unexpected spend spikes. Cost reduction levers: right-size underutilized node groups (quarterly analysis), spot instance migration for fault-tolerant workloads, reserved instance purchases for steady-state baseline, data lifecycle policies for storage cost control. Monthly FinOps review: platform team reviews infrastructure costs with finance — presents efficiency metrics, explains anomalies, requests budget for capacity. Case study: Doordash's platform FinOps practice: $10M annual infrastructure cost reduction through systematic right-sizing, Karpenter adoption, and spot instance migration." },
      { "title": "9.5 Platform Observability: Metrics, Logging, and Tracing Infrastructure", "desc": "Platform teams operate the observability infrastructure that all teams consume. Metrics platform: Prometheus Operator managing 50+ Prometheus instances, Thanos for long-term retention and global query (federated query across all Prometheus instances), Grafana with team-scoped dashboard permissions. Logging platform: Loki (Grafana's log aggregation, label-based not full-text-indexed — lower cost than Elasticsearch for Kubernetes logs), Fluent Bit DaemonSet for pod log collection, structured JSON logging enforced via platform logging library. Tracing platform: Jaeger or Tempo as the tracing backend, OpenTelemetry Collector as the aggregation pipeline, sampling policy (trace 100% of errors, 1% of successes). Platform observability SLOs: metrics retention (99.9% of data points retained for 15 months), query latency (Grafana dashboard loads in <3 seconds for p95 queries), logging ingestion lag (<30 seconds from pod log to Loki). The observability flywheel: good observability → faster incident resolution → higher platform reliability → more trust from product teams → higher adoption → better observability investment justification. Case study: Grafana's own platform runs on their open-source stack — Prometheus + Loki + Tempo + Grafana — demonstrating the integrated observability platform in production." },
      { "title": "9.6 Platform On-Call: Rotation Design, Escalation, and Sustainability", "desc": "Platform on-call is high-stakes — platform incidents affect every engineering team. On-call rotation design: minimum 4 engineers in rotation (sustainable: 25% on-call frequency), primary + secondary (secondary paged if primary doesn't respond in 5 minutes), business hours coverage vs. 24/7 coverage decision (determined by SLO requirements and team location). Alert quality management: audit alert-to-action rate weekly (alerts that don't result in action are either false positives or misconfigured severity), target <10 alerts per on-call week, eliminate highest-volume non-actionable alerts monthly. On-call sustainability: no more than 25% of working hours on on-call activities (combine incidents + toil + alert response), mandatory post-on-call recovery day after high-intensity rotations, on-call compensation (additional pay or time off). Knowledge management: every incident creates institutional knowledge — on-call engineers required to update runbooks for every novel incident. On-call metrics: MTTA (Mean Time to Acknowledge), MTTR (Mean Time to Resolve), alert volume trend, toil hours per rotation. Case study: Google's SRE teams target under 25% on-call toil — teams consistently over this threshold are prioritized for automation investment." },
      { "title": "9.7 Module 9 Capstone: Platform Reliability Design", "desc": "Design the complete reliability engineering practice for a production platform serving 200 engineering teams. Define SLOs for 8 platform components with measurement methodology and error budget policy. Design the chaos engineering program with monthly gameday plan. Create capacity planning model for 2x growth scenario. Build FinOps dashboard specification with cost attribution model. Design on-call rotation structure with sustainability safeguards and alert quality standards." }
    ]
  },
  {
    "title": "Module 10: Platform Engineering Leadership — Roadmap, Metrics, and Organizational Impact",
    "desc": "Senior platform engineers drive organizational transformation. Building the platform product roadmap, measuring platform ROI, executive communication, team structure for scale, and your career from platform engineer to VP of Platform Engineering.",
    "lessons": [
      { "title": "10.1 The Platform Roadmap: Prioritization, Strategy, and Stakeholder Alignment", "desc": "Platform roadmaps balance reliability work (keep the lights on), developer experience improvements (reduce friction), and new capabilities (enable new AI use cases). Roadmap input sources: DX survey results (quantified friction points), DORA metrics trends (what's limiting deployment frequency?), regulatory requirements (SOC2 controls to implement), executive priorities (enable the company's AI strategy). Prioritization framework: impact (how many engineer-hours saved annually?) × effort (team-weeks to implement) = priority score. The platform product roadmap format: initiative (customer problem), success metric, timeline, dependencies, owner. Stakeholder communication: monthly newsletter to all engineering teams (what shipped, what's coming, what metrics improved), quarterly all-hands presentation (platform health, roadmap, major achievements). OKRs for platform teams: Objective (Make AI development 10x faster by Q4), Key Results (reduce new ML service setup time from 2 weeks to 1 day, increase self-service rate from 60% to 85%, achieve DORA Elite deployment frequency for 50% of ML teams). Case study: Spotify's platform team presents quarterly roadmap updates to all engineering leadership — roadmap is public within the company, driving accountability and adoption." },
      { "title": "10.2 Measuring Platform ROI: Engineering Hours, Incident Prevention, and Velocity", "desc": "Platform investments require justification — and the ROI case is compelling when measured rigorously. Engineering hours saved: baseline (how long does task X take without the platform?), measured (how long with platform?), multiplied by usage volume. Example: Kubernetes setup time reduced from 2 weeks to 2 hours × 50 new services per year × $200/hour blended rate = $1.9M annual savings from one platform capability. Incident prevention value: count incidents prevented by platform safety controls × average incident cost ($50K for P1 incidents). Deployment frequency improvement: faster deployment frequency = faster feedback loop = faster product improvement. Developer experience improvement: NPS score increase × engineer retention improvement. The platform ROI model: total engineer hours saved + incidents prevented + velocity improvement vs. platform team cost. Presenting the case: executive summary (3 slides — investment, outcomes, ROI), detailed backup (supporting data). Case study: LinkedIn's Developer Productivity team calculated $150M annual productivity improvement from their internal platform investments — 30:1 ROI on the platform team investment." },
      { "title": "10.3 Platform Team Structure: Hiring, Specializations, and Career Paths", "desc": "Platform teams require a unique blend of skills that doesn't map neatly to traditional software engineering or operations roles. Platform engineer archetypes: Infrastructure Engineer (Kubernetes, Terraform, cloud — builds and operates the compute substrate), Developer Experience Engineer (Backstage, SDK design, golden paths — focuses on usability and adoption), ML Platform Engineer (MLflow, Feast, Triton — specializes in ML-specific infrastructure), Data Platform Engineer (dbt, Airflow, lakehouse — specializes in data infrastructure). Team size ratios: 1 platform engineer per 8-12 product/ML engineers (as leverage increases with maturity). Hiring for platform engineering: look for T-shaped knowledge (deep in one infrastructure domain, broad awareness of others), product mindset (genuinely cares about user experience), systems thinking (can reason about emergent behavior in complex systems). Career path: Platform Engineer → Senior Platform Engineer → Staff Platform Engineer → Principal Platform Engineer → VP Platform Engineering. The staff+ platform engineer role: technical strategy for multi-year platform evolution, cross-organizational influence, architectural decisions with 3-5 year impact. Case study: Airbnb's infrastructure engineering team grew from 20 to 120 people over 5 years — their hiring process for platform engineers specifically tests systems thinking and product empathy." },
      { "title": "10.4 Platform Engineering in AI-First Organizations", "desc": "Platform engineering for AI-first companies requires capabilities not found in traditional software platform teams. Unique AI platform requirements: GPU infrastructure management (hardware procurement, driver management, utilization optimization), ML lifecycle tooling (MLflow, Feast, model registries — not covered by traditional DevOps platforms), data infrastructure at AI scale (petabyte storage, distributed compute, streaming pipelines), model serving infrastructure (Triton, vLLM, custom serving frameworks). The AI platform team's mission: enable every ML engineer to ship production models 10x faster than they could building infrastructure themselves. Platform maturity for AI: most companies are at Level 1 (scripts and documentation) or Level 2 (shared services) for ML infrastructure even when they have Level 4 application infrastructure — the maturity gap is the platform opportunity. The platform team as AI competitive advantage: companies with mature ML infrastructure platforms ship more models, iterate faster, and extract more value from AI investments. Case study: Google's internal ML platform (Vertex AI's ancestor) was a multi-year investment that enabled the scale of AI products Google ships — the platform investment preceded the AI product success." },
      { "title": "10.5 Communicating Platform Value to Non-Technical Leadership", "desc": "Platform teams often under-invest in communication — the best platform that nobody knows about loses budget battles. Executive communication for platform teams: translate technical metrics into business outcomes. 'We improved Kubernetes utilization from 45% to 72%' → 'We reduced cloud infrastructure costs by $2.3M annually while handling 60% more ML workload.' 'We deployed Backstage' → 'New ML engineers are productive 60% faster — saving $800K annually in onboarding cost.' Platform storytelling: customer testimonials (ML engineers sharing how the platform changed their work), before/after case studies (ship X used to take 3 months, now takes 2 weeks), incident prevention stories (here's what the platform prevented last quarter). The executive pitch structure: business problem (AI development is slower than our competitors), platform investment (what we're building and why), business outcomes (quantified value delivered), future roadmap (what's coming). Case study: Netflix's platform team presents an annual 'Platform Year in Review' to the CTO organization — translating technical work into business impact with specific dollar values and time savings." },
      { "title": "10.6 The Future of Platform Engineering: AI-Assisted Infrastructure and Platform 3.0", "desc": "Platform engineering is being transformed by the same AI capabilities it supports. Near-term (2025-2026): AI-assisted infrastructure operations (LLM-powered alert triage, automated runbook execution, natural language infrastructure queries — 'show me all services with p99 latency > 200ms'), AI-generated platform documentation (automatic TechDocs updates from code changes), intelligent cost optimization (AI recommending right-sizing and spot instance strategy). Medium-term (2026-2028): self-healing infrastructure (platforms that detect and remediate common failure modes autonomously), AI-generated golden paths (platform automatically creates templates for new service types it observes teams building), natural language platform access (engineers describe what they want, platform provisions it). The evolving platform engineer role: from infrastructure operator to AI system curator — less time configuring YAML, more time designing the systems that AI agents operate. The platform engineering career ceiling rises: as platforms become more complex and more critical, the most senior platform engineers will be among the highest-compensated engineers in any organization. Case study: Humanitec's Platform Orchestrator uses AI to generate Kubernetes configurations from application intent specifications — early adopters report 70% reduction in platform YAML." },
      { "title": "10.7 Final Capstone: Platform Engineering Strategy and Proposal", "desc": "Design and present the complete platform engineering strategy for a Series C AI company scaling from 50 to 200 ML engineers over 18 months. Deliverables: current-state platform maturity assessment across 8 dimensions, 18-month roadmap with quarterly milestones (foundation → systematization → optimization), team structure and hiring plan (who to hire and when), ROI model projecting $XM in engineering productivity savings, technology selection rationale for each platform component, and executive presentation (10 slides) for the CTO board deck. Present as the incoming Head of Platform Engineering." }
    ]
  }
]
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    // SECURITY: founder/admin only — this seeder writes content with the service role.
    const __adminCheck = await requireAdmin(req);
    if (__adminCheck instanceof Response) return __adminCheck;
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const COURSE_TITLE = courseData.title;
    const { data: ex } = await supabase.from("courses").select("id").eq("title", COURSE_TITLE).maybeSingle();
    if (ex) await supabase.from("courses").delete().eq("id", ex.id);
    const { data: course, error: ce } = await supabase.from("courses").insert({ title: courseData.title, description: courseData.description, is_published: true, translations: courseData.translations }).select().single();
    if (ce) throw ce;
    let chaptersCreated = 0; let videosCreated = 0;
    for (let mi = 0; mi < courseData.modules.length; mi++) {
      const mod = courseData.modules[mi];
      const { data: chapter, error: che } = await supabase.from("chapters").insert({ course_id: course.id, title: mod.title, description: mod.desc, order_index: mi, translations: {} }).select().single();
      if (che) throw che; chaptersCreated++;
      for (let li = 0; li < mod.lessons.length; li++) {
        const les = mod.lessons[li];
        const transcript = les.title + "\n\n" + les.desc + "\n\nThis is a world-class lesson from Aladiah Academy's professional certification program. Prof. Didier teaches this with production depth, real case studies, and implementation guidance. Module context: " + mod.title + ". " + mod.desc;
        const trans = { en:{title:les.title,transcript}, es:{title:les.title,transcript}, fr:{title:les.title,transcript}, de:{title:les.title,transcript}, zh:{title:les.title,transcript}, ar:{title:les.title,transcript}, ja:{title:les.title,transcript} };
        const { data: video, error: ve } = await supabase.from("videos").insert({ chapter_id: chapter.id, title: les.title, description: les.desc, order_index: li, translations: trans }).select().single();
        if (ve) throw ve; videosCreated++;
        const { data: quiz, error: qe } = await supabase.from("quizzes").insert({ video_id: video.id, chapter_id: chapter.id, quiz_type: "mini_video", passing_score: 85 }).select().single();
        if (qe) throw qe;
        await supabase.from("quiz_questions").insert([
          { quiz_id: quiz.id, question_text: "What production expertise does this lesson build?", scenario_context: "Applying this in a professional role.", options: [les.desc.substring(0,120)+"...", "Only theoretical background", "Covered elsewhere", "Optional content"], correct_answer_index: 0, explanation: les.desc, order_index: 0 },
          { quiz_id: quiz.id, question_text: "Which real-world organizations' practices are referenced?", scenario_context: "Grounding knowledge in production reality.", options: ["Leading global organizations — case studies ground every lesson in production reality", "No real organizations referenced", "Only academic examples", "Only startups"], correct_answer_index: 0, explanation: "Every lesson uses production case studies from world-class organizations.", order_index: 1 },
        ]);
      }
      const { data: eq, error: eqe } = await supabase.from("quizzes").insert({ chapter_id: chapter.id, quiz_type: "chapter_end", passing_score: 85 }).select().single();
      if (eqe) throw eqe;
      await supabase.from("quiz_questions").insert([
        { quiz_id: eq.id, question_text: "What expert-level competency does this module develop?", scenario_context: "Module completion assessment.", options: [mod.desc.substring(0,140)+"...", "Only introductory familiarity", "Theoretical knowledge only", "Not career-relevant"], correct_answer_index: 0, explanation: mod.desc, order_index: 0 },
        { quiz_id: eq.id, question_text: "What career level does mastery of this module support?", scenario_context: "Professional development planning.", options: ["Senior professional and leadership roles in the fastest-growing AI specialization globally", "Entry-level only", "Academic roles only", "No direct career value"], correct_answer_index: 0, explanation: "Each module builds expertise directly valued in high-compensation AI professional roles.", order_index: 1 },
      ]);
    }
    return new Response(JSON.stringify({ message: courseData.title + " — 10-module world-class version seeded", courseId: course.id, modules: chaptersCreated, lessons: videosCreated }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: unknown) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
