// =============================================================================
// Admissions Authority — the 10 engines (code mirror of the dept architecture).
// Optimizes for enrollment QUALITY (fit, completion, certification, employment,
// salary), not volume. See docs/agents/admissions-authority/AGENT_SPEC.md.
// =============================================================================
import { AdmissionsEngineDef } from '@/types/admissions';

export const ADMISSIONS_ENGINES: AdmissionsEngineDef[] = [
  {
    id: 'lead_qualification',
    name: 'Lead Qualification Engine',
    purpose: 'Score and qualify prospects by motivation, commitment, timeline, and fit.',
    inputs: ['Prospect intake', 'Motivation', 'Commitment hours', 'Timeline', 'Budget'],
    outputs: ['Qualification score', 'Status (qualified/nurturing/disqualified)'],
    qualityStandards: ['Qualify on fit + commitment, not just interest', 'Disqualify low-fit honestly'],
    kpis: ['Qualified-lead rate', 'Lead-to-fit accuracy'],
    approval: 'Autonomous scoring; status change to enrolled needs founder approval',
  },
  {
    id: 'career_matching',
    name: 'Career Matching Engine',
    purpose: 'Match a prospect to the right career path/program by background and goals.',
    inputs: ['Target role', 'Current role', 'Background', 'Market demand'],
    outputs: ['Matched program', 'Match score'],
    qualityStandards: ['Match to genuine fit', 'Surface alternative paths when fit is weak'],
    kpis: ['Match accuracy', 'Program-fit score'],
    approval: 'Autonomous',
  },
  {
    id: 'program_recommendation',
    name: 'Program Recommendation Engine',
    purpose: 'Recommend the best-fit program and explain why.',
    inputs: ['Match result', 'Goals', 'Timeline'],
    outputs: ['Recommended program', 'Rationale (recommendation record)'],
    qualityStandards: ['Recommend best fit, not highest price'],
    kpis: ['Recommendation acceptance rate'],
    approval: 'Recommendation drafted; founder approves outreach',
  },
  {
    id: 'financial_readiness',
    name: 'Financial Readiness Engine',
    purpose: 'Assess ability to pay and suggest viable options (plan, scholarship).',
    inputs: ['Budget band', 'Region', 'Timeline'],
    outputs: ['Financial readiness', 'Financial score', 'Suggested options'],
    qualityStandards: ['Never push beyond means', 'Offer honest financing paths'],
    kpis: ['Financial-fit rate', 'Plan uptake'],
    approval: 'Autonomous assessment; offers need founder approval',
  },
  {
    id: 'objection_resolution',
    name: 'Objection Resolution Engine',
    purpose: 'Anticipate and draft honest responses to likely objections.',
    inputs: ['Background', 'Budget', 'Timeline', 'Motivation'],
    outputs: ['Objection list + drafted responses'],
    qualityStandards: ['Truthful, non-manipulative responses', 'Respect a genuine no'],
    kpis: ['Objection-resolution rate'],
    approval: 'Drafted only; founder approves before use',
  },
  {
    id: 'webinar_conversion',
    name: 'Webinar Conversion Engine',
    purpose: 'Convert webinar attendees into qualified, well-fit enrollments.',
    inputs: ['Webinar attendance', 'Engagement', 'Qualification'],
    outputs: ['Conversion play', 'Prioritized follow-up'],
    qualityStandards: ['Convert fit, not pressure'],
    kpis: ['Webinar→qualified rate', 'Webinar→enrollment rate'],
    approval: 'Follow-up drafted; founder approves sending',
  },
  {
    id: 'enrollment',
    name: 'Enrollment Engine',
    purpose: 'Determine enrollment readiness and prepare the enrollment step.',
    inputs: ['Qualification', 'Fit', 'Financial readiness', 'Success prediction'],
    outputs: ['Enrollment readiness', 'Enrollment recommendation'],
    qualityStandards: ['Enroll only well-fit, ready prospects'],
    kpis: ['Enrollment quality', 'Refund/dropout rate (inverse)'],
    approval: 'ENROLLMENT REQUIRES FOUNDER APPROVAL (no auto-enroll, no auto-charge)',
  },
  {
    id: 'follow_up',
    name: 'Follow-Up Engine',
    purpose: 'Draft a tailored, respectful multi-step follow-up sequence.',
    inputs: ['Prospect state', 'Objections', 'Timeline'],
    outputs: ['Drafted follow-up steps (approval-gated)'],
    qualityStandards: ['Helpful, not spammy', 'Stop on a genuine no'],
    kpis: ['Reply rate', 'Nurture→qualified rate'],
    approval: 'NEVER auto-sends; every message needs founder approval',
  },
  {
    id: 'employability_projection',
    name: 'Employability Projection Engine',
    purpose: 'Project realistic employment, salary, and time-to-placement outcomes.',
    inputs: ['Program', 'Market demand', 'Background', 'Completion probability'],
    outputs: ['Employability projection (employment %, salary range, time-to-placement)'],
    qualityStandards: ['Realistic, honest projections — never guaranteed claims'],
    kpis: ['Projection accuracy vs. actual outcomes'],
    approval: 'Autonomous (read-only projection)',
  },
  {
    id: 'student_success_prediction',
    name: 'Student Success Prediction Engine',
    purpose: 'Predict completion + certification success and flag risks early.',
    inputs: ['Motivation', 'Commitment', 'Fit', 'Background'],
    outputs: ['Completion probability', 'Certification-success likelihood', 'Risk factors'],
    qualityStandards: ['Honest prediction; recommend nurture/alternative for low probability'],
    kpis: ['Prediction accuracy', 'Completion rate of enrolled cohort'],
    approval: 'Autonomous (read-only prediction)',
  },
];
